### ISSUE TITLE
allow users to email the owner of a worksheet/Bundle

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#1]
<a href="https://github.com/Raisins"><img src="https://avatars.githubusercontent.com/u/123099?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Raisins](https://github.com/Raisins)**
_Friday Aug 01, 2014 at 19:41 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/556_

---

allow users to email the owner of the worksheet or a bundle

**Comment by kashizui** [comment]
This feature will require learning about how to query REST API and could also be a good start to learning about the frontend code.

**Comment by maxwang7** [comment]
How do we want to implement this feature? And should I just go ahead and implement it or put together a design doc and we can discuss it more?

**Comment by percyliang** [comment]
This will require some discussion about both UX and restructuring (to
handle other forms of messaging, commenting), so why don't you handle the
other smaller issues first?

**Comment by maxwang7** [comment]
I will write doc and post it on slack for comments

**Comment by maxwang7** [comment]
In terms of accessing users information, the user's email should not be revealed. On Github, it is possible to access a user's public email if they've chosen to display it: https://help.github.com/articles/searching-users/

**Comment by percyliang** [comment]
Not supporting for now.
