### ISSUE TITLE
action bar: copying past one screenful

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#10]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Friday Jun 12, 2015 at 05:18 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1110_

----

One can currently scroll up and down down the action bar, which is great, but one can't copy past one screenful by dragging and scrolling.

**Comment by percyliang** [comment]
Not necessary.
