### ISSUE TITLE
CLI doesn't work with Makefile

### ISSUE THREAD

**Issue by hhexiy** [codalab/codalab-worksheets#1009]
If I put the `cl` command in a Makefile, e.g.,
```
run:
    cl run :src
```
and execute it by running `make run`, it does not recognize the bundle references `:src`. Running `cl run :src` directly from the command line works.

**Comment by percyliang** [comment]
You are probably on a different worksheet in the two cases (type `cl work`
to see).  `cl` is associated with a session, which doesn't seem get
inherited by make.  You can either add an explicit `cl work <worksheet>`
before the `cl run` command in your Makefile, or set the CODALAB_SESSION
environment variable everywhere you want a consistent home worksheet.

**Comment by hhexiy** [comment]
I see. Yeah it was on the home worksheet.
