### ISSUE TITLE
`cl wls` shouldn’t print out all worksheets ever created

### ISSUE THREAD

**Issue by nikhilxb** [codalab/codalab-worksheets#1012]
Also, `wls` and `wsearch` right now these CLI commands are not intuitive. In the usual case, all I want to see are my own worksheets. At the least, need to limit results displayed.

**Comment by percyliang** [comment]
Let's limit the search results for now to be consistent with the behavior of `search` for bundles.

**Comment by percyliang** [comment]
The default is 10 options now.
