### ISSUE TITLE
Slurm Worker

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1019]
We want Codalab to be compatible with a university cluster running Slurm.
Immediately we want to let users of the Stanford NLP cluster use it to run their CodaLab jobs.

**Comment by percyliang** [comment]
Create a SlurmWorkerManager for this.  Note that this would ideally be run by the user client side (rather than by CodaLab) so that they can have full control over their jobs.

**Comment by candicegjing** [comment]
Feature summary:
1. Each user should be able to launch SlurmWorkerManager on `sc`.
1. SlurmWorkerManager can spawn multiple sessions(hosts) on clusters. 
1. Each session will launch 1 `cl-worker` on its host. (1 SlumrWorkerManager -> n hosts(sessions) -> n `cl-worker`)
1. Running `cl-worker` will remain the same as it is.
1. When preemption happens, clean up or kill jobs to free up resources as needed.
1. Provide logging to job status. 
1. Notify users when a job failed or killed or finished.

**Comment by nelson-liu** [comment]
One other thing I thought of: the workers should be fairly decentralized from the WorkerManager. If the SlurmWorkerManager dies for some reason, the workers should still be able to run properly (though no new slurm job will be created).

**Comment by candicegjing** [comment]
Summary based on the new discussion:
1. add a flag to the worker indicating the number of bundles allowed to be executed in this worker. See #2287
1. Slurm worker manager will run the same way as AWS worker manager and run 1 bundle per worker
1. Release the previously allocated worker resources once the bundle finished running on the worker.
1. Re-allocate a Slurm worker for any future staged bundles. (Might expect resource allocation on Slurm more frequently, not sure if there is bandwidth on Slurm side or an upper limit on the size of queued jobs)
