### ISSUE TITLE
[vm-clws-prod-server-0] TypeError: __call__() got an unexpected keyword argument 'parser'

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1027]
POST /cli/command

Query params:

Form params:

JSON body:
{
    "autocomplete": true,
    "command": "cl macro squad-utils/dev-evaluate-v1.1 cl macro squad-utils/dev-evaluate-v1.1 pred",
    "worksheet_uuid": "0x646fdf2c64b24c99ba58ff0319c1b68f"
}

Local variables:
parsed_args=Namespace(bundles=['cl', 'macro', 'squad-utils/dev-evaluate-v1.1'], command='macro', depth=10, dry_run=False, function=<function do_macro_command at 0x7f395fa03c08>, macro_name='squad-utils/dev-evaluate-v1.1', md_allow_failed_dependencies=None, md_description=None, md_name=None, md_request_cpus=None, md_request_disk=None, md_request_docker_image=None, md_request_gpus=None, md_request_memory=None, md_request_network=None, md_request_priority=None, md_request_queue=None, md_request_time=None, md_tags=None, print_version=False, shadow=False, tail=False, verbose=False, wait=False, worksheet_spec=None)
complete_remaining_positionals=True
isoptional=False
active_action=IntrospectAction(option_strings=[], dest='bundles', nargs='+', const=None, default=None, type=None, choices=None, help='Bundles: new_input_1 ... new_input_n named_input_name:named_input_bundle other_named_input_name:other_named_input_bundle ([[(<alias>|<address>)::](<uuid>|<name>)//](<uuid>|<name>|^<index>))', metavar=None)
parser=MonkeyPatchedIntrospectiveArgumentParser(prog='cl macro', usage=None, description='Use mimicry to simulate macros.\n  macro M A B <name1>:C <name2>:D <=> mimic M-in1 M-in2 M-in-name1 M-in-name2 M-out A B C D', version=None, formatter_class=<class 'argparse.RawTextHelpFormatter'>, conflict_handler='error', add_help=True)
completions=[]
greedy_actions=[]
cword_prefix=u'pred'
x=IntrospectAction(option_strings=[], dest='bundles', nargs='+', const=None, default=None, type=None, choices=None, help='Bundles: new_input_1 ... new_input_n named_input_name:named_input_bundle other_named_input_name:other_named_input_bundle ([[(<alias>|<address>)::](<uuid>|<name>)//](<uuid>|<name>|^<index>))', metavar=None)
completer=<codalab.lib.completers.BundlesCompleter object at 0x7f394c4cfcd0>
self=<argcomplete.CompletionFinder object at 0x7f394c787ad0>
next_positional=None

Traceback (most recent call last):
  File "/opt/codalab-cli/codalab/server/rest_server.py", line 148, in wrapper
    return callback(*args, **kwargs)
  File "/opt/codalab-cli/venv/local/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/opt/codalab-cli/codalab/server/json_api_plugin.py", line 18, in wrapper
    result = callback(*args, **kwargs)
  File "/opt/codalab-cli/codalab/rest/cli.py", line 46, in post_worksheets_command
    return {'completions': complete_command(query['worksheet_uuid'], query['command'])}
  File "/opt/codalab-cli/codalab/rest/cli.py", line 116, in complete_command
    return cli.complete_command(command)
  File "/opt/codalab-cli/codalab/lib/bundle_cli.py", line 811, in complete_command
    clean, cf._get_completions(comp_words, cword_prefix, cword_prequote, first_colon_pos)
  File "/opt/codalab-cli/venv/local/lib/python2.7/site-packages/argcomplete/__init__.py", line 251, in _get_completions
    completions = self.collect_completions(active_parsers, parsed_args, cword_prefix, debug)
  File "/opt/codalab-cli/venv/local/lib/python2.7/site-packages/argcomplete/__init__.py", line 464, in collect_completions
    completions)
  File "/opt/codalab-cli/venv/local/lib/python2.7/site-packages/argcomplete/__init__.py", line 418, in _complete_active_option
    prefix=cword_prefix, action=active_action, parser=parser, parsed_args=parsed_args)
TypeError: __call__() got an unexpected keyword argument 'parser'

Page 27 of 35

**Comment by teetone** [comment]
Closing as I will resolve it in #1959 .
