### ISSUE TITLE
Dependency cleanup doesn't seem to work

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1030]
Today (2/22/19) one of our gpuworkers became unresponsive as its dependency cache became full and it seemed like it couldn't clear out the cache appropriately. Potentially related to:
- #890 
- #413 
- #986 
- #952

**Comment by bkgoksel** [comment]
(3/20) One of the workers again had a very large dependency cache. We shouldn't close this until we added tests and confirmed this is definitely solved.

**Comment by percyliang** [comment]
In general, we should have more robust cleaning up of bundle dependencies and docker images.

Should have a fix broken state operation which is perhaps run on starting up a worker that checks that the json state files match what's in the actual cache, does a `docker image prune`, etc.

**Comment by candicegjing** [comment]
Just want to confirm several things after reading through our codebase:
1. the dependency cache we were referring to is currently handled by `LocalFileSystemDependencyManager._prune_failed_dependencies()`?
2. docker image cache is currently handled by `DockerImageManager._cleanup()`?
3. So we want to fix logic in these two or something else?
