### ISSUE TITLE
Worker connection loss during computation

### ISSUE THREAD

**Issue by SamuelGabriel** [codalab/codalab-worksheets#1032]
I experienced tonight not two Azure VMs I connected, that both of them show as 'worker_offline' in the Codalab CLI, even though both are still on and running. If you want to look in the worksheets.codalab.org logs, I experienced it with bundle '0xd24e0f' and bundle '0x60d5ae'. There are no outputs of the cl-worker regarding this, but it still is running.

**Comment by bkgoksel** [comment]
Looks like the worker eventually reconnected and bundles reached their final states. Sometimes when downloading large docker images for the first time workers get disconnected from the server, but should recover eventually.
Were there any other issues you ran into when using your own VMs as codalab workers?
Closing this issue as the worker offline problem seems to be solved but feel free to reply here/open new issues if there were any other humps for making your own workers.
