### ISSUE TITLE
cl run takes an initialization script

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1035]
Use case: when running a job, be able to specify an initialization script which has commands like `pip install....`.

This initialization script can be a bundle?

For now, just run the script every time the run executes.  Later, cache the docker image.

**Comment by epicfaace** [comment]
3 possibilities:
- Dockerfile
- initialization script
- requirements.txt

**Comment by percyliang** [comment]
Caching docker image is too complex...people can just put the script in the command for transparency.
