### ISSUE TITLE
make sure that run -t, wait -t work

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#104]
Currently, some output gets cut off.  Make sure we preserve the full contents.

**Comment by percyliang** [comment]
Can't seem to reproduce it (on codalab.org)...

**Comment by kashizui** [comment]
Is this still a problem?

**Comment by percyliang** [comment]
Last I checked it seemed okay, but can you double check?

The cases to worry about is when you call cl at different points during the
execution of the run and if the run outputs a lot of text (especially in a
bursty way).

**Comment by percyliang** [comment]
Seems to work, closing for now.
