### ISSUE TITLE
Non-deterministic 404 error on retrieving bundle data

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1043]
_From @robinjia on January 29, 2019 23:5_

There's this weird thing where like 50% of the time, for the same exact path in the same bundle, trying to load it in the web interface gives a 404 error. For example, this url https://worksheets.codalab.org/rest/bundles/0x2713d9c73b8a4242969b50499632126c/contents/blob/eval.json

If I just hit refresh a bunch of times, I sometimes get the 404 and sometimes get the actual data.

_Copied from original issue: codalab/codalab-worksheets#479_

**Comment by bkgoksel** [comment]
Maybe related to #996 ?

**Comment by epicfaace** [comment]
Are you still seeing this? Can't seem to reproduce this.

**Comment by percyliang** [comment]
Yes, this still happens, but kind of infrequently / sporadically.  But
frequently enough to cause problems.

**Comment by robinjia** [comment]
It's interesting that the original URL I reported doesn't give 404's anymore. But anyways here's a new URL https://worksheets.codalab.org/rest/bundles/0xba4beac2fc3f40898ef0cccd084584d9/contents/blob/out/test_results.json 

Same thing as before: sometimes you get a 404, sometimes you get the data.

**Comment by yipenghe** [comment]
Can't reproduce on both URLs right now..

**Comment by percyliang** [comment]
Can't reproduce either.
