### ISSUE TITLE
Web interface "New Run" should allow creation of powerful cl run commands

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1044]
_From @nikhilxb on January 11, 2019 21:42_

In general, should be able to (for the most common cases) not use CLI at all.

_Copied from original issue: codalab/codalab-worksheets#475_

**Comment by w0nche0l** [comment]
_From @percyliang on February 3, 2019 8:16_

Include `request-*` flags

**Comment by percyliang** [comment]
Done.
