### ISSUE TITLE
Simple deployment

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1046]
_From @percyliang on December 26, 2017 5:49_

Create a docker-compose file which allows anyone to setup and deploy a local CodaLab instance with essentially one command.

The docker-compose file should contain docker images for: mysql, webserver, bundleserver, worker.

External assets (mounted): path to mysql, bundle store, worker scratch, credentials

_Copied from original issue: codalab/codalab-worksheets#404_

**Comment by bkgoksel** [comment]
Closed with #1097
