### ISSUE TITLE
change time quota logic

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1048]
_From @percyliang on March 2, 2017 14:57_

When people run their own worker, it should not count against their time quota.

Consider increasing the default time quota from 7 days.

Another option: change the time quota to a bound on rate (max compute one can use per day or week).

_Copied from original issue: codalab/codalab-worksheets#280_

**Comment by percyliang** [comment]
For simplicity, this should just be maximum number of CPUs/GPUs that one can use (importantly, that's not a private worker) at any given time.

**Comment by bkgoksel** [comment]
Completed with #1151
