### ISSUE TITLE
be able to upload directories

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1050]
_From @codalab on December 27, 2015 10:10_

<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Tuesday Nov 17, 2015 at 15:26 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1406_

---

Do what DropBox or Google Drive do.

_Copied from original issue: codalab/codalab-worksheets#25_

**Comment by w0nche0l** [comment]
_From @bkgoksel on August 3, 2018 23:13_

Isn't this supported now?

**Comment by w0nche0l** [comment]
_From @percyliang on August 4, 2018 3:22_

From the CLI, but not the web interface.

**Comment by Levilian** [comment]
One issue I faced is that when uploading folders the file structure will not be preserved but stored as a metadata attached to each individual file. I tried to search online how to rebuild the file directory from individual files but can't find any relevant resources.
