### ISSUE TITLE
Worksheet markdown parsing of multiline commands

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1051]
_From @nikhilxb on January 11, 2019 21:46_

**Bug:**
After worksheet opened in the online editor, all runs with multiline command are not parsed int table properly. See https://worksheets.codalab.org/worksheets/0x453913e76b65495d8b9730d41c7e0a0c/

**Temporary fix (Kerem):**
A solution for now is to manually edit the markdown and remove the command in the square braces since those don't affect what's shown on the rendered worksheet
i.e. you can just remove everything in the square brackets,  and the bundle will still display correctly as long as its UUID is in the curly braces

e.g. `[run train-policy -- src:craigslistbargain,train-data:parse-train/parsed.json,dev-data:parse-dev/parsed.json,:nltk_data,:price-tracker/price_tracker.pkl,schema:craigslistbargain-schema : mkdir -p mappings/lf2lf; mkdir -p cache/lf2lf; mkdir -p checkpoint/lf2lf; PYTHONPATH=src python src/main.py --schema-path schema --train-examples-paths train-data --test-examples-paths dev-data \ --price-tracker price-tracker \ --model lf2lf \ --model-path checkpoint/lf2lf --mappings mappings/lf2lf \ --word-vec-size 300 --pretrained-wordvec "" "" \ --rnn-size 300 --rnn-type LSTM --global-attention multibank_general \ --num-context 2 --stateful \ --batch-size 128 --gpuid 0 --optim adagrad --learning-rate 0.01 \ --epochs 30 --report-every 500 \ --cache cache/lf2lf --ignore-cache \ --verbose \ ]{0x7f74f53dfa834cf78228afd18251926c}` can be turned into `[run train-policy ]{0x7f74f53dfa834cf78228afd18251926c}` and it should work

or even `[]{0x7f74f53dfa834cf78228afd18251926c}`

_Copied from original issue: codalab/codalab-worksheets#476_

**Comment by percyliang** [comment]
Dup of #1879 .
