### ISSUE TITLE
Transfer MLcomp

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1054]
_From @percyliang on April 5, 2017 16:55_

- Figure out how to structure datasets and programs (no dataset/program matrix view anymore)
- Copy all public things over

_Copied from original issue: codalab/codalab-worksheets#289_

**Comment by w0nche0l** [comment]
_From @kashizui on May 11, 2017 23:13_

Will this probably involve migrating things directly from the server, or can everything be downloaded straight from the website?

**Comment by w0nche0l** [comment]
_From @percyliang on May 12, 2017 3:23_

Would do things directly from the server.

The main thing to figure out is how we support the view: for each dataset,
ranking of the programs/runs based on accuracy.

Note that we already have some support for MLcomp checked into CodaLab.

**Comment by w0nche0l** [comment]
_From @kashizui on May 12, 2017 5:5_

Ah that's what that script was.

Did we want to copy over user's submissions on the datasets as well? Or just the datasets themselves?

**Comment by w0nche0l** [comment]
_From @percyliang on May 12, 2017 5:11_

Datasets, programs, and rerun all the programs on datasets.

**Comment by bkgoksel** [comment]
@percyliang Is this still relevant? Can we close it?

**Comment by percyliang** [comment]
This is still on my plate.

**Comment by percyliang** [comment]
Finally done: https://worksheets.codalab.org/worksheets/0x8b6d86f8d6a345dca607bd6d861951af/
Runs were not copied over since there are too many of them.
