### ISSUE TITLE
Improve performance of worksheets API

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1055]
_From @kashizui on November 1, 2016 1:49_

The new worksheets REST API can be kind of slow because it tries to fetch all of the related data necessary for a worksheet. This is not necessary for all calls. Allow querying for a subset of the fields or relationships.

_Copied from original issue: codalab/codalab-worksheets#229_

**Comment by w0nche0l** [comment]
_From @kashizui on January 25, 2017 23:4_

Wait for #655

**Comment by w0nche0l** [comment]
_From @maxwang7 on February 13, 2017 22:34_

Profiling tools:
cprofile

What to profile:
Loading of a worksheet faster - i.e. bundle endpoints, maybe search? Hits the legacy API. The legacy API does server side rendering --> does the interpretation or database queries take a long time?

The markdown rendering happens client side -- happens super quickly

**Comment by w0nche0l** [comment]
_From @percyliang on February 14, 2017 0:20_

bundle_cli.py already has some profiling code guarded by an (if False) - we
can make that an option.

Two known sources of slowness:

- There's a lot of bundles which are being displayed with '% display table
foo' where the schema 'foo' has tons of fields, each reading from JSON
files...

I suspect the disk reads and computing of the field values are are a
problem, but should double check.  Can check for this via 'cl print'.
Probably need some caching of bundles that have a 'ready' state so that we
know the contents won't change.  Can just have the cache in memory.

- If there are bundles that contains 1000 files - in the frontend, when
loading the worksheet, it fetches the contents of every single bundle
instead of only the bundle that is selected.  This should be fixed and is
an easy win.

**Comment by w0nche0l** [comment]
_From @maxwang7 on April 5, 2017 17:2_

Time estimate: 3-4 more hours

**Comment by w0nche0l** [comment]
_From @maxwang7 on April 5, 2017 18:33_

Steps:
- Figure out why Robin's worksheet is slow by making a copy of the worksheet and then removing parts
- On the parts that take the longest, find the lower limit on the total time to load the worksheet by removing time consuming lines
- Write design doc for changes if major (caching layer, etc.) and then implement

**Comment by percyliang** [comment]
Dup of #1234 

@epicfaace this issue has a bit more information
