### ISSUE TITLE
Move documentation into our repo (and build on a platform like read the docs)

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1058]
_From @bkgoksel on November 19, 2018 18:37_

https://readthedocs.org/ seems like a quasi-standard location for hosting documentation for a lot of open source software projects. It builds nice-looking documentation pages automatically from a `docs/` folder in a GitHub repo (using reStructuredText or Markdown). 

Moving our docs into our repo would make them more standardized and also allow us to version control our documentation, making it much easier in the future to ensure we can keep documentation up to date at a PR level rather than syncing changes with it every now and then as we remember.

_Copied from original issue: codalab/codalab-worksheets#468_

**Comment by epicfaace** [comment]
We could also use https://docusaurus.io/

**Comment by percyliang** [comment]
Already moved to RTD.
