### ISSUE TITLE
Can't detach first item (bundle) in a worksheet

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1059]
_From @maxwang7 on November 1, 2017 8:26_

Example worksheet (try to right click and detach): https://worksheets.codalab.org/worksheets/0x2644fd6a840e4c8790307bf32ef9161a/

It doesn't matter the permissions of the bundle, only that it's the first item in a worksheet (or maybe the first in a table?).

It is possible to remove non-first items.

Should probably spend some more time determining the exact failure cases.

_Copied from original issue: codalab/codalab-worksheets#373_

**Comment by bkgoksel** [comment]
Looks fixed.
