### ISSUE TITLE
Problem with dragging open web terminal

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1061]
_From @maxwang7 on December 11, 2017 18:55_

Clicking and dragging open the web terminal doesn't expand the area where the output is shown.

![screen shot 2017-12-11 at 10 54 13 am](https://user-images.githubusercontent.com/5680188/33848148-bf6dc8c2-de61-11e7-9fc7-68182f225379.png)

_Copied from original issue: codalab/codalab-worksheets#397_

**Comment by percyliang** [comment]
Doesn't seem to be an issue anymore.
