### ISSUE TITLE
List of contents don’t always show all files (in bundle preview)

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1062]
_From @fabeschan on May 27, 2017 6:14_

This cannot be reliably reproduced, however it does occur rather frequently so it should be easy to see with a bit of repetition.

```
Steps:
Locate a bundle with multiple files
Select this bundle and observe the list of contents.
Click on `/` and see if more files magically appear under it
Repeat: Click on `/` and see if even more files magically appear
```

_Copied from original issue: codalab/codalab-worksheets#328_

**Comment by bkgoksel** [comment]
Related to #996 and #1043 maybe?
