### ISSUE TITLE
generated summary inserts bundle uuid references too aggressively

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1063]
_From @fabeschan on June 3, 2017 8:15_

I have a bundle called `train` that has some uuid

Also a run bundle with command that includes the word `train` multiple times, none of them referring to the bundle named the same thing, yet the generated summary inserts the bundle uuid reference immediately after every `train` found.

Here is a screenshot (look at bundles named `run-answer`)

![screenshot 2017-06-03 01 09 35](https://cloud.githubusercontent.com/assets/4369332/26751962/0ebff516-47fa-11e7-905a-eab657c696d9.png)

_Copied from original issue: codalab/codalab-worksheets#333_

**Comment by percyliang** [comment]
We should probably just get rid of these {0x...} annotations since it's confusing.
Let's find another way to make dependencies more clear.

**Comment by candicegjing** [comment]
@percyliang I want to confirm with you that we want to remove those dependencies annotation for now and not change anything else right?

**Comment by percyliang** [comment]
Yes.
