### ISSUE TITLE
Dependencies found when there are none

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1067]
_From @rajpurkar on October 31, 2016 3:9_

While executing mimic on one of my bundles (let's call it x, and it depends on uploaded bundle y), a whole bunch of unrelated bundles (which use y) were reexecuted with x as a dependency in place of y.

_Copied from original issue: codalab/codalab-worksheets#226_

**Comment by bkgoksel** [comment]
Closing due to long period of inactivity and vague problem statement (without UUIDs to double check)
@rajpurkar feel free to chime in if you ran into any similar issues in the past 3 years :)
