### ISSUE TITLE
Collapse Tables

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1068]
_From @maxwang7 on January 26, 2017 1:1_

@maxwang7 commented on [Wed Jan 25 2017](https://github.com/codalab/codalab-cli/issues/658)

_Copied from original issue: codalab/codalab-worksheets#247_

**Comment by w0nche0l** [comment]
_From @percyliang on January 31, 2017 4:20_

To flesh this out: on large worksheets, be able to collapse a table which contains a long list of bundles or worksheets.  (Collapsing sections in markdown might be a bit annoying to do.)

**Comment by w0nche0l** [comment]
_From @robinjia on November 17, 2017 8:59_

+1 I would find this useful

**Comment by percyliang** [comment]
Too complicated to implement, closing.
