### ISSUE TITLE
Set up continuous back-ups for bundle data and prod databases

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1069]
_From @kashizui on February 8, 2017 22:57_

_Copied from original issue: codalab/codalab-worksheets#268_

**Comment by w0nche0l** [comment]
_From @fabeschan on June 15, 2017 0:38_

We did backups (only) during the Great Migration -- is that what you're looking for, or do you want continuous backups?

**Comment by w0nche0l** [comment]
_From @kashizui on June 15, 2017 0:57_

Probably good to have some sort of continuous / regular backups of the bundles!

**Comment by w0nche0l** [comment]
_From @bkgoksel on October 11, 2018 22:16_

We don't even have wsprod anymore. Any reason to keep this open @percyliang ?

**Comment by w0nche0l** [comment]
_From @percyliang on October 12, 2018 0:53_

I think this still applies to our current prod server...

**Comment by percyliang** [comment]
Done.
