### ISSUE TITLE
Support anonymous bundles and worksheets

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1070]
_From @kashizui on January 19, 2017 1:38_

Build out the UI components to support anonymous worksheets and bundles.

Implementation on the API/backend side, as well as support on CLI client:
codalab/codalab-cli#400 

_Copied from original issue: codalab/codalab-worksheets#243_

**Comment by w0nche0l** [comment]
_From @maxwang7 on February 1, 2017 9:48_

@kashizui Have there been any updates on this?

**Comment by w0nche0l** [comment]
_From @kashizui on February 1, 2017 9:54_

@maxwang7 No updates, backend implementation is still incomplete.

**Comment by bkgoksel** [comment]
Seems like this now just needs frontend as the backend issue is closed and PR merged

**Comment by leilenah** [comment]
done
