### ISSUE TITLE
Run bundle stderr does not display tqdm properly

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1074]
_From @nikhilxb on November 1, 2018 1:4_

Would like to be able to visualize my progress immediately, but tqdm terminal display instead prints each update on a separate line:
```
 0%|          | 0/859 [00:00<?, ?it/s]
  0%|          | 2/859 [00:00<00:43, 19.68it/s]
  1%|          | 5/859 [00:00<00:41, 20.69it/s]
  1%|          | 8/859 [00:00<00:38, 21.93it/s]
  1%|1         | 10/859 [00:00<00:42, 19.92it/s]
  2%|1         | 13/859 [00:00<00:39, 21.69it/s]
  2%|1         | 16/859 [00:00<00:37, 22.77it/s]
  2%|2         | 19/859 [00:00<00:35, 23.93it/s]
  3%|2         | 23/859 [00:00<00:32, 25.49it/s]
  3%|3         | 27/859 [00:01<00:31, 26.52it/s]
  3%|3         | 30/859 [00:01<00:30, 27.45it/s]
  4%|3         | 34/859 [00:01<00:29, 28.37it/s]
  4%|4         | 38/859 [00:01<00:27, 29.38it/s]
  5%|4         | 42/859 [00:01<00:26, 30.34it/s]
```

_Copied from original issue: codalab/codalab-worksheets#458_

**Comment by bkgoksel** [comment]
For context `tqdm` works fine on `cl cat` so this is likely caused because we literally print the `stdout/stderr` as a regular file and the clear last line/move cursor to the beginning of the last line special characters that tqdm use aren't useful there. A solution would need something that can use these characters to delete lines of files.

**Comment by percyliang** [comment]
So should we handle this on the frontend rendering side (e.g., in the side panel)?

**Comment by epicfaace** [comment]
maybe this will help - https://stackoverflow.com/questions/41707229/tqdm-printing-to-newline

**Comment by percyliang** [comment]
Don't fix it in CodaLab, programs should not output such things when running non-interactively.
