### ISSUE TITLE
Permissions for downloading predicitions

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1076]
_From @RishabGoel on March 29, 2017 3:13_

I was trying to download a model predicitions and got the following error...
User rishab does not have sufficient permissions on bundle (have none, need read).
how do i get around his??
Thanks in advance

_Copied from original issue: codalab/codalab-worksheets#285_

**Comment by w0nche0l** [comment]
_From @fabeschan on March 29, 2017 19:30_

Can you provide more information please? Otherwise this just looks like you don't have permissions to access it

**Comment by bkgoksel** [comment]
Closed due to inactivity.
