### ISSUE TITLE
Add colors to bundles to show permissions

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1077]
_From @maxwang7 on February 22, 2017 23:14_

Will need to discuss the design of this feature first before implementing it.

_Copied from original issue: codalab/codalab-worksheets#276_

**Comment by w0nche0l** [comment]
_From @percyliang on April 5, 2017 5:39_

What is this?  We have colors for permissions now...

**Comment by bkgoksel** [comment]
@percyliang Is this still relevant? Let's close otheriwse
