### ISSUE TITLE
1. 2. 3. numbering not working

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1079]
_From @codalab on December 27, 2015 10:10_

<a href="https://github.com/tonyyyang"><img src="https://avatars.githubusercontent.com/u/6948032?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tonyyyang](https://github.com/tonyyyang)**
_Sunday Sep 13, 2015 at 03:07 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1268_

---

If you add a bundle between 1. and 2., the index starts over from 1..

Reference: https://www.codalab.org/worksheets/0x45cea1e33f734c2ba0d0ea85a585408e/

_Copied from original issue: codalab/codalab-worksheets#15_

**Comment by w0nche0l** [comment]
_From @codalab on December 27, 2015 10:10_

<a href="https://github.com/Raisins"><img src="https://avatars.githubusercontent.com/u/123099?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Raisins](https://github.com/Raisins)**
_Monday Sep 14, 2015 at 18:01 GMT_

---

:+1:  
Mark down syntax is clashing with your raw text. Added label and moved in to milestone

**Comment by bkgoksel** [comment]
Looks related to #997 maybe?

**Comment by bkgoksel** [comment]
This is fixed looking at the bug report worksheet.
