### ISSUE TITLE
investigate Blob storage as a storage backend.  

### ISSUE THREAD

**Issue by Raisins** [codalab/codalab-worksheets#108]
Currently, bundle_store.py stores everything in ~/.codalab/data, which won't scale.  Instead store things in blob storage (hopefully just need to change the interface).  But definitely keep on supporting the on disk version.

We have to deal with the challenge of storing directories.

**Comment by percyliang** [comment]
Not supporting for now since it will require considerable work.  Will use hard drive or EFS in the short term.
