### ISSUE TITLE
Scrolling is erratic on mobile device

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1081]
_From @codalab on December 27, 2015 10:13_

<a href="https://github.com/kashizui"><img src="https://avatars.githubusercontent.com/u/614837?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kashizui](https://github.com/kashizui)**
_Thursday Dec 10, 2015 at 09:27 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1497_

---

Chrome on iOS

trying to scroll up sometimes pulls down the address bar instead (as if already reached the top of the page)

_Copied from original issue: codalab/codalab-worksheets#42_

**Comment by bkgoksel** [comment]
Could be related to #1082

**Comment by percyliang** [comment]
Basically dup of #1082, closing.
