### ISSUE TITLE
when mouseover metadata fields, show a description of them

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1087]
_From @codalab on December 27, 2015 10:12_

<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Tuesday Nov 17, 2015 at 15:55 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1409_

---

Fields include:
- everything in the side panel of the form <key>: <value>
- the fields in the metadata <key>:<value>
- headers of tables (for now, just show the schema used to generate that field - might have to ship that from the CLI)

_Copied from original issue: codalab/codalab-worksheets#27_

**Comment by leilenah** [comment]
tooltips added
