### ISSUE TITLE
Web terminal doesn't initialize if app loaded when window was too small

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1089]
_From @codalab on December 27, 2015 10:13_

<a href="https://github.com/kashizui"><img src="https://avatars.githubusercontent.com/u/614837?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kashizui](https://github.com/kashizui)**
_Wednesday Dec 09, 2015 at 23:51 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1496_

---

If the window is too narrow (and thus displays in tablet/smartphone mode) when the worksheet interface is loaded, the web terminal does not work even after we expand the window again.

_Copied from original issue: codalab/codalab-worksheets#41_

**Comment by bkgoksel** [comment]
@percyliang @nikhilxb @w0nche0l 
Is this even something we want to fix/change?
Seems acceptable to not have web terminal functionality available on phone/tablet interfaces...

**Comment by percyliang** [comment]
Sounds fine especially since we can put more effort into non CLI ways of
doing things.

**Comment by percyliang** [comment]
No more web terminal, closing.
