### ISSUE TITLE
Cache bundle contents

### ISSUE THREAD

**Issue by Raisins** [codalab/codalab-worksheets#109]
cl print and rendering on the website is slow for worksheets because rendering each worksheet requires going to disk and reading everything out.  If all the bundles on a worksheet are 'ready', then we should cache the rendered version so that things load much faster.

**Comment by percyliang** [comment]
In general, loading of large worksheets is pretty slow...how to make this faster?

**Comment by bkgoksel** [comment]
Related to #1083

**Comment by epicfaace** [comment]
Async loading helps with this a lot.
