### ISSUE TITLE
Errors about bundles information on dashboard page

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1090]
_From @caoyu1991 on February 20, 2019 6:50_

I tried to delete some bundles using "--force" command and delete the relevant worksheet, and it caused such errors on dashboard page. The information about bundles cannot be displayed normally. And the disk space is also abnormal, some bundles cannot be tracked by me but they still occupy disk space. 
Here is my dashboard link
https://worksheets.codalab.org/worksheets/0xb843335f02a9443995db2013fbe2e7f4/

If possible, could you just clean up all my data on codalab? Since I have all backup of them and I really need to free my disk space. Thank you very much!

_Copied from original issue: codalab/codalab-worksheets#482_

**Comment by bkgoksel** [comment]
Hi @caoyu1991, could you share your Codalab username so we can help look into this issue?
Thanks,
Kerem
