### ISSUE TITLE
Upload failed: Can't save bundle, bundle size 5646236541 greater than user's disk quota left: 1482116946.0

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1091]
_From @Jasperty on February 20, 2019 9:42_

how to upload big files larger than 5g !!! i retry many times and not work, who can help me??

_Copied from original issue: codalab/codalab-worksheets#483_

**Comment by bkgoksel** [comment]
Looks like @Jasperty's user quota was full. Closing until further inquiry.
