### ISSUE TITLE
how to work on a new account ?

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1092]
_From @Jasperty on March 3, 2019 1:27_

_Copied from original issue: codalab/codalab-worksheets#485_

**Comment by bkgoksel** [comment]
It's unclear what the issue asks. If you'd like to open a new account, please sign up from the website. If you'd like to change users on the CLI you can use the `cl logout` command and any subsequent `cl work` command should ask you to log in again. Make sure `CODALAB_USERNAME` and `CODALAB_PASSWORD` environment variables are not set if you want to work as a different user.
