### ISSUE TITLE
Fix frontend npm build warnings

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1094]
Currently we set `CI=false` in `.travis.yml` to prevent the default npm behavior of treating warnings as errors on prod builds since we don't have time to fix all the warnings before merging into master. Ideally we should NOT have any warnings and turn on the treat warnings as errors behavior to avoid introducing more code smells on the frontend. This issue should track the fixing of those warnings and the removal of the `CI=false` line in the `.travis.yml` file.
The warnings include:
- `===` instead of `==`
- unused vars
- images without alt text (bad for accessibility)
- fake links that should really just be buttons
- unused imports ?

**Comment by percyliang** [comment]
Any errors should show up when you run `pre-commit.sh`.
