### ISSUE TITLE
fix GitHub security vulnerabilities (pyyaml, marshmallow)

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1096]
As a note, we need:
- [x] `marshmallow >= 2.15.1`
- [x] `pyyaml >= 5.1`
- [x] `sqlalchemy >= 1.3.0`

**Comment by bkgoksel** [comment]
As a note, we need:
- `marshmallow >= 2.15.1`
- `pyyaml >= 4.1b4`

**Comment by epicfaace** [comment]
finished by #2042
