### ISSUE TITLE
action bar: long commands are rendered poorly

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#11]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Friday Jun 12, 2015 at 05:24 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1111_

----

If we type a long enough command that wraps, the start of the command gets shifted down to the second line, but then jumping to the beginning of the command takes part of the command to the first line, and things just get garbled.

**Comment by codalab** [comment]
<a href="https://github.com/Raisins"><img src="https://avatars.githubusercontent.com/u/123099?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Raisins](https://github.com/Raisins)**
_Thursday Aug 13, 2015 at 00:07 GMT_

----

Might be a bug with jquery.term.

**Comment by codalab** [comment]
<a href="https://github.com/Raisins"><img src="https://avatars.githubusercontent.com/u/123099?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Raisins](https://github.com/Raisins)**
_Thursday Sep 03, 2015 at 04:05 GMT_

----

Lower priority since issue #1171 is in place

**Comment by percyliang** [comment]
Fixed.
