### ISSUE TITLE
perform resource (CPU, space) accounting / sharing

### ISSUE THREAD

**Issue by ErickWa** [codalab/codalab-worksheets#110]
If multiple users submit lots of jobs, how do we balance latency and throughput?  Some considerations:
- Small jobs (e.g., cl run 'echo run') should take zero time.  This means always having a free server.  In general, we can workers on which jobs only take <5 seconds, and another one for <1h, etc.
- Need to store the total amount of resources a user is using (both hard drive space for having quotas and time spent).

**Comment by percyliang** [comment]
Need to create a new table which stores for each user:
- Disk quota
- Total CPU time used
- CPU quota

Total disk used can be gotten by doing `cl search owner=pliang size=.sum`.
Then when people create new bundles, we need to check these quotas.

Add a new command for getting / setting quotas (obviously setting quotas is only possible if you're an admin).

Also need a default quota for new users that sign up (default to 15GB, 168 hours).

**Comment by percyliang** [comment]
Fixed by #269
