### ISSUE TITLE
Large file uploading fail

### ISSUE THREAD

**Issue by tbright17** [codalab/codalab-worksheets#1100]
I have a 14G zip file, and I use cl up to upload it to my worksheet.
I got the following error after it finishes the uploading, and in the worksheet it shows uploading failed.

`
Uploading src.zip (0x48f207ed44124b60a8e98a99b34858ef) to https://worksheets.codalab.org
Sent 13629.02MiB / 13629.02MiB (100.0%) [0.59MiB/sec]
UsageError: Upload failed: Invalid archive upload.
`
Any suggestions?

Thanks

**Comment by bkgoksel** [comment]
Hello tbright17,
Could you share your username with us? And also could you check your disk quota info by running `uinfo` on the CLI? Perhaps you don't have enough disk quota for an 14GB file as the standard disk quota is 10GB.

**Comment by tbright17** [comment]
Thanks for the reply. I have make the file much smaller, less than 2G now. But I met another problem, which is also faced by other people: https://github.com/codalab/codalab-worksheets/issues/1099

My username is tuming1990 if it helps. Thanks again.

**Comment by bkgoksel** [comment]
Assuming your 2GB file update completed without an error, I'm closing this issue for now. 
We're investigating #1099 right now and will be updating the status there.

**Comment by tbright17** [comment]
Thanks!
