### ISSUE TITLE
manage

### ISSUE THREAD

**Issue by MadMenHitBooker** [codalab/codalab-worksheets#1101]
Hi,

i'm trying to run this app but i can't figure out what i'm missing .. 
i'm following the 
https://github.com/codalab/codalab-worksheets/wiki/Server-Setup

`
cd $HOME/codalab-worksheets/codalab
./manage config_gen
`

I can't find this file on the project. Am i missing something ? thanks

**Comment by bkgoksel** [comment]
Hello,
We recently had a major update where we merged previously separate front end and back end repositories but looks like the nginx.conf file wasn't migrated properly and that wiki page wasn't updated.

I went ahead and updated [the Wiki page](https://github.com/codalab/codalab-worksheets/wiki/Server-Setup) and also pushed a pre-configured `nginx.conf` file to the repository. Please ensure you're up to date on `master` and follow the renewed instructions on the updated Wiki page.

Our apologies for the out-of-date Wiki page, and do let us know if anything else goes wrong in the process.
Thanks for trying out Codalab and have a nice day!
Kerem from Codalab team
