### ISSUE TITLE
[DISCUSSION] Tighter git integration

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1121]
Can we better leverage git features for Codalab usage?
Some ideas:
- Store and display git metadata for bundles that have a `.git` directory on the root to better track your code bundles etc.
- Offer git commit hook scripts that upload your code to Codalab every time you commit with your commit message as the description
- Offer a GitHub bot that reruns a bunch of runs and reports result changes when making PRs etc.
- More?

This is an issue to discuss what more we can build around Git and Codalab.

**Comment by epicfaace** [comment]
I like the GitHub bot.

**Comment by leilenah** [comment]
@percyliang is this something that codalab users would benefit from?

**Comment by percyliang** [comment]
In principle, like the CodaLab & git connection, but not sure if this is the right hook.
