### ISSUE TITLE
Search bar to quickly switch between worksheets

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1123]
Perhaps a dropdown on the navbar, or if we add a search bar, good to upweight a user's own worksheets on the ranked results.

**Comment by percyliang** [comment]
This search bar can be universal where it can surface other things like bundles, users, and help.

**Comment by Levilian** [comment]
Search bar functionality v0.1:

- [x] display results for `cl wsearch`
- [x] toggle between different personal worksheets
- [x] search other people's worksheets by name

**Comment by Levilian** [comment]
Search bar functionality v0.2:

- [x] search multiple keywords at the same time
- [x] display advanced information - owner name, etc.
- [x] highlight the part of the title/name that matches keywords
- [x] make the search box bigger, more to the left
- [x] placeholder text: Search worksheets
- [x] keyboard shortcut to trigger (a + f)
- [x] rank .mine worksheets higher than others
