### ISSUE TITLE
Better landing page experience for registered users

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1125]
Currently there are a few issues:
- When a registered user navigates to our website, they get the default landing page with links to "My Home" and "My Dashboard"
- "My Home" is empty by default and its purpose unclear to users. Overall bad UX, we should probably get rid of this (especially if we end up making profile pages))
- "My Dashboard" is the useful one which lists your worksheets, recent bundles, floating bundles etc, but the name is ambiguous.

Ideally, we would name "My Dashboard" to something like Home and have it be the landing page for registered users, so they can jump into any of their worksheets they're working on with a single mouse click/see the status of their recent running bundles.

**Comment by percyliang** [comment]
In new frontend, Dashboard is more central, and with #1230 we should be good.
