### ISSUE TITLE
Accept name based URLs to open worksheets

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1126]
Since worksheet names are unique per instance, we should be able to navigate to worksheets via:
`https://worksheets.codalab.org/worksheets/<worksheet-name>` as well as `https://worksheets.codalab.org/worksheets/<worksheet-uuid>`.

Of course the risk there is that worksheet names might change, so the best behavior would be to have the UUID link be the canonical link and maybe just redirect to the UUID page if someone navigates by the name page.

**Comment by percyliang** [comment]
This is already a thing:
`https://worksheets.codalab.org/rest/worksheets/?name=dashboard`
