### ISSUE TITLE
[DISCUSSION] Better job allocation, resource management UXC

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1127]
Currently the Codalab system is more designed towards long-living, centrally managed workers.
Our worker abstraction:
- assumes a worker has a finite, static number of CPUs, GPUs and memory
- assumes a worker has a static cache of dependencies
- doesn't factor in the possibility of scaling workers for a run after it's submitted.

This makes it difficult to interface with dynamic resource allocating workers (like Slurm or AWS Lambda)

We probably want to make these assumptions weaker and decouple the worker interface from worker resource scaling. Ideally we want people to be able to submit jobs to Codalab interface first, and then either add their own workers, or let a worker implementation that scales dynamically to pick up on that job and allocate resources for it.

There are a few questions here:

- How do we separate workers with static resources and workers with dynamic resources?
- How do we communicate the current capacity of the system for them (public + their workers)?
- How do we handle bundles for which there aren't any workers at the moment?
- For dynamic resource workers:
    - How do we allocate runs between such workers if there are multiple?
    - How do we deal with an allocation failure for such workers? (fail bundle? restage?)

Also relevant to these questions is our own job allocation logic, which we want to improve (#1047)

**Comment by percyliang** [comment]
This is kind of handled by the worker manager interface.
