### ISSUE TITLE
Slurm Worker: Implement bundle commands

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1128]
Implement and test:
- [ ] read
- [x] write
- [x] kill
- [ ] netcat

**Comment by bkgoksel** [comment]
`netcat` is quite complicated to support (as the actual worker that has the auth credentials with the server and the docker container are on different machines, need to do some proxying/forwarding things between different machines), so for the initial release it probably won't be supported.

I'll likely open a separate issue for it.

**Comment by bkgoksel** [comment]
For `write` there are currently issues with Docker permissioning.

By default, any file/folder created by Docker is owned by root. When the Stanford deployment is running on Codalab, the bundle directories it creates are owned by root. 

The worker however has to run outside Docker (so it can issue Slurm jobs as there's no obvious way to submit Slurm jobs from inside a Docker container), which means the worker runs as the `codalab` user.

When `write` is called, the worker process running as `codalab` tries to write to a bundle directory, which is owned by `root`, which doesn't work.

There's a way to run docker containers as the current user, but then doing anything like `pip install` gets broken, and it is kind of necessary for performing the initialization.

One option would be to get `codalab` root access on the NLP cluster and generally say that the Slurm setup won't work unless you have root access to the cluster...

**Comment by bkgoksel** [comment]
For `read`, it's a bit tricky to make sure when a bundle is downloaded locally, the dependencies are not included. When the bundle is locally available, the server's bundle directory, the worker's bundle directory and the directory mounted to the docker container for the run are all the same. While the bundle is running, the dependencies are found in the bundle home directory, so downloading gets the dependencies as well. We probably need to filter them out in a special case for shared filesystem workers.

**Comment by percyliang** [comment]
No longer relevant since we're going to implement Slurm workers through the worker manager.
