### ISSUE TITLE
Ability to download and use a subfolder of a (maybe failed) packet 

### ISSUE THREAD

**Issue by SamuelGabriel** [codalab/codalab-worksheets#1134]
I train models, and I save the model in a subfolder of `.` Now I want to maybe do some evaluation of this model on my own machine and therefore only want to download the folder with the model and not all resources produced by the run. Or I might want to use this subfolder in another run.

Both is not directly possible. For the download I need to download every file on its own and then sort them together again on my local machine and to use the output in another run the run can't be failed or killed. I think that is not a good restriction here, since many failed or killed runs still have very valuable intermediate model data.

**Comment by bkgoksel** [comment]
Hi Samuel, 
Thanks for your feedback! 
To use a failed/killed bundle as a dependency you can use the `--allow-failed-dependencies` flag on your subsequent runs. 

As for downloading sub paths of bundles, that would be a good feature to have if we don't already. 

Kerem from Codalab team

**Comment by percyliang** [comment]
You can download subpaths of bundles by `cl download <bundle>/<subpath>`.
