### ISSUE TITLE
Problem with disk quota enforcement on workers

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1135]
A couple issues seen around disk requests:

1- When a bundle goes over its disk quota, it is killed by the worker when that is caught, but the worker still uploads all the results, making the disk quota effectively useless.

2- When the disk quota is the same as the user's total disk quota left, this upload step causes a failure with an unparsable (No JSON could be decoded) error message.

**Comment by candicegjing** [comment]
I ran tests in both local machine (MacBook Pro) and staging environment by setting the disk quota usage near fully used, see [worksheet:0x032d40893f75408e84f022183a44a934](https://worksheets-dev.codalab.org/worksheets/0x032d40893f75408e84f022183a44a934) in staging. In the same time, I logged the value of `run_state` in function `_transition_from_CLEANING_UP()` before entering into the next state `UPLOADING_RESULTS` as follows:
```
run_state= RunState(stage='RUN_STAGE.CLEANING_UP'
 run_status='Uploading results'
 bundle=<codalab.worker.bundle_state.BundleInfo object at 0x7f67986fc048>
 bundle_path='/mnt/scratch/bundles/runs/0x3e6c831075ae47099f387fa727e88f5c'
 bundle_dir_wait_num_tries=120
 resources=<codalab.worker.bundle_state.RunResources object at 0x7f6798624588>
 bundle_start_time=1581719869.5116475
 container_time_total=10.085699
 container_time_user=0
 container_time_system=0
 container=None
 container_id=None
 docker_image='codalab/default-cpu@sha256:ff7de716ac5f94d9b4ff8d6341d60166ed5b0163cc05d8d51da9418511caf5e1'
 is_killed=False
 has_contents=True
 cpuset={'0'}
 gpuset=set()
 max_memory=0
 disk_utilization=10491182
 exitcode=0
 failure_message=None
 kill_message=None
 finished=True
 finalized=False)
```
It appears that the `is_killed` field isn't set to `True` when the bundle's state transited from `RUNNING` to `CLEANUP`, which indicates that the program didn't catch the time when the disk usage exceeded the maximum usage allowed for the current user. 
It seems the problem falls back to how we can capture the time when disk usage is over the maximum limit.

**Comment by candicegjing** [comment]
Some related posts: https://github.com/moby/moby/issues/12462

**Comment by candicegjing** [comment]
`storage_opt` could be an option to limit user disk usage. However, it requires to use some specific types of filesystem which are not currently supported in our worker environment (could be configured?), e.g. XFS filesystem pre-mounted on host machine and `pquota` option is enabled.
This is what `docker info` returned in our staging worker:
```
vm-clws-dev-worker-0:~% docker info
Client:
 Debug Mode: false

Server:
 Containers: 33
  Running: 1
  Paused: 0
  Stopped: 32
 Images: 15
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
...
```
It's using extfs as backing filesystem. Also, we don't seem to have `pquota` option available now.
The detailed explanation could be found at [set storage driver option per container](https://docs.docker.com/engine/reference/commandline/run/#set-storage-driver-options-per-container). 
Some users chose to set up a backup filesystem which contains the prerequisites for using `storage_opt` option: https://github.com/machinelabs/machinelabs/issues/703

**Comment by candicegjing** [comment]
@bkgoksel Could you clarify the second item here: **When the disk quota is the same as the user's total disk quota left, this upload step causes a failure with an unparsable (No JSON could be decoded) error message.** Do you mean the error happens when **disk quota requested** is the same as the user's total disk quota left?

**Comment by candicegjing** [comment]
For item 2, did several tests in local by setting the requested user disk to be the same as disk quota left, bundles are able to proceed to `RUNNING` state and finish. As the first issue in this ticket is not valid anymore (see comments in #2007) and the second issue can't be reproduced. closing this ticket for now. Will fill new ticket if a similar issue happens again in the future.
