### ISSUE TITLE
[FEATURE REQUEST] Support Singularity

### ISSUE THREAD

**Issue by hongchengkuan** [codalab/codalab-worksheets#1139]
Many clusters and servers don't allow the installation of Docker. But they support Singularity, which is similar to docker but safer than docker.
You can find the link for singularity [here](https://singularityhub.github.io/).

**Comment by QwertyJack** [comment]
I'm a little confused.
Which singularity is THE singularity? [Singularityhub](https://singularityhub.github.io/) or [singularity](https://github.com/sylabs) ?

**Comment by hongchengkuan** [comment]
I mean the [singularity](https://github.com/sylabs). Singularityhub is just a place to store singularity images, like Docker hub.

**Comment by QwertyJack** [comment]
老哥 你知道怎么一次性下载bundle的所有依赖吗？或者一次性下载worksheet到本地？

**Comment by bkgoksel** [comment]
Thanks for the suggestion! Singularity is something we considered as we're thinking of making codalab easier to deploy on a cluster setting. This is not something very high priority for us at the moment as we're focusing on usability and stability improvements to the platform, but we will keep an eye on the Singularity project and depending on its maturity and adoption in wider community will consider it.

**Comment by epicfaace** [comment]
Closing this in favor of #3284
