### ISSUE TITLE
[USER ISSUE] How to find others‘ code or worksheet？

### ISSUE THREAD

**Issue by Feiyu-Zhang** [codalab/codalab-worksheets#1142]
**Describe the bug**
I would like to read others' code for study. But I can't find it. How to find others' code or worksheet?

**Codalab Information**
I'm using chrome browser on Web.

**Comment by Matt-F-Wu** [comment]
Hi, please check out the Gallery tab on the top bar, you will find published resources there. :-)

**Comment by Feiyu-Zhang** [comment]
![image](https://user-images.githubusercontent.com/34130100/57898965-c0178700-788d-11e9-807b-bb399daff70f.png)
Is this page? I can't find the Gallery tab.

**Comment by bkgoksel** [comment]
Hi,
You are looking at the [Codalab Competitions](https://competitions.codalab.org) platform, which is a different platform than [Codalab Worksheets](https://worksheets.codalab.org)
Unfortunately we cannot support issues with Codalab Competitions, please get in touch with their support team for issues on that platform.

Thanks,
Kerem from Codalab Worksheets Team
