### ISSUE TITLE
[USER ISSUE] infinite waiting if set --request-gpus

### ISSUE THREAD

**Issue by xixiaoyao** [codalab/codalab-worksheets#1143]
**Describe the bug**
run any command with `--request-gpus` would result in infinite waiting (stuck in 'staged' stage)
E.g.,
```
cl run --request-gpus 1 "nvidia-smi"
cl run --request-gpus 1 "ls"
```

**Codalab Information**
- *xixiaoyao*:
- * 0x97a906fb0ab94d97b3497872ce577c17*:
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:
 - *CLI*:
 - *0.3.0*: 
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :
just run any of following commands

```
cl run --request-gpus 1 "nvidia-smi"
cl run --request-gpus 1 "ls"
```

**Expected behavior**
run done

**Screenshots**
![image](https://user-images.githubusercontent.com/24541791/57610095-b7c7ff00-75a2-11e9-9ab0-d899cbc4d26c.png)

**Additional context**

**Comment by bkgoksel** [comment]
Closing as workers have freed up.
