### ISSUE TITLE
Unable to do pip3 install

### ISSUE THREAD

**Issue by vnadhan** [codalab/codalab-worksheets#1147]
Unable to do pip3 install allennlp

I get the following error:
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcfe16b3780>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/allennlp/

**Comment by TerenceCYJ** [comment]
Hi， @vnadhan How do you solve this problem？
