### ISSUE TITLE
[USER ISSUE] How to download a worksheet? Or bundle with dependencies?

### ISSUE THREAD

**Issue by QwertyJack** [codalab/codalab-worksheets#1153]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when reproduce other one's run. I want to download the full worksheet within one command.

**Describe the solution you'd like**
Something like `cl clone <worksheet_spec>`.
Or `cl down --with-dep <target_spec>`.

**Describe alternatives you've considered**
I have to download each bundles one by one.

**Additional context**
None.

**Comment by bkgoksel** [comment]
Related to #1053

**Comment by percyliang** [comment]
You can download all the bundles in a worksheet like this:
`for x in $(cl ls -u); do echo === Downloading $x; cl down $x -o $x; done`

**Comment by QwertyJack** [comment]
It works !
Thank you very much @percyliang
