### ISSUE TITLE
Top of keyboard shortcuts help is not visible

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1172]
When press Keyboard shortcuts, we get a popup showing the keyboard shortcuts modal.  But the top of it is hidden.

Also:
- remove 'c' for triggering the web terminal and 'esc' for focusing on worksheet
- escape should close the popup.

**Comment by epicfaace** [comment]
@percyliang the top of the keyboard shortcuts is visible for me -- are you sure this is still a problem? If so, can you send me a screenshot?


![image](https://user-images.githubusercontent.com/1689183/59120501-61807e80-890a-11e9-9247-b78ff5b8f6e4.png)


I've made #1183 with the other changes you requested, though.

**Comment by percyliang** [comment]
![Screenshot from 2019-06-07 10-12-19](https://user-images.githubusercontent.com/435384/59121450-f3898680-890c-11e9-92ca-0d2704ff73e8.png)
