### ISSUE TITLE
unify permissions

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1179]
Worksheet permissions - if click, should bring up a modal dialog, which allows you to select permissions.

Bundle permissions in the bundle details page should show a simple read-only description, and if you click, it pops up the modal dialog.

The look/feel of editing permissions should be the same throughout.

When hover over permissions, add a gray background to make it obvious that it's clickable.

**Comment by Matt-F-Wu** [comment]
![image](https://user-images.githubusercontent.com/6495979/59546395-81530c00-8ee1-11e9-9acb-c9807a9101b6.png)
