### ISSUE TITLE
Automatically bring up and down Azure VMs

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#118]
We want to be able to be able to launch, get info on, and terminate instances on the fly by invoking a script (for EC2, it's ec2-run-instances, etc.).  Something along the lines of:
https://github.com/percyliang/mlcomp/blob/master/site/lib/mlcomp/EC2Manager.rb
We can use azure-cli for this, and do things like:

```
azure vm create codalab-worker34 <image> ...
azure vm delete codalab-worker34
```

**Comment by fabeschan** [comment]
I recommend taking advantage of Azure Resource Templates (equivalent to Amazon CloudFormation I think) for this sort of automation.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates

**Comment by fabeschan** [comment]
Some work has already been done to automate the start up of workers (by converting them to docker images/containers)

**Comment by bkgoksel** [comment]
Dockerized workers + @percyliang's `manage.py` script already make this possible. Closing
