### ISSUE TITLE
Live reload on backend

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1182]
[This page](https://github.com/codalab/codalab-worksheets/wiki/Server-Setup) says:
"If you're making back end changes, the same functionality is not yet supported and you need to rebuild the relevant Docker image after each change."

@bkgoksel is this still the case? If so, what changes would we need in order to allow for live reload?

**Comment by bkgoksel** [comment]
Yeah this is a good feature to add. Basically we'd need to mount the backend code as a docker volume bind the same way the front end dev mode works.

**Comment by epicfaace** [comment]
This, unfortunately, still doesn't work, as the server doesn't automatically incorporate the changes...
