### ISSUE TITLE
[FEATURE REQUEST] Display title of worksheet more

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#1187]
**Is your feature request related to a problem? Please describe.**
It used to be the case that the title of the worksheet would show up, both in the name of the webpage (the title tag) and on the top of the webpage immediately (before the bundles get loaded). However, now the title doesn't show up in the page title, and only shows up on the page once everything has been loaded, which can be very slow. So when I click on a worksheet link, I have to wait many seconds before I know if I'm looking at the worksheet I want or not.

**Describe the solution you'd like**
The title of the webpage should include the title of the worksheet (currently it just says "Codalab Worksheets"). The page should also show the title at the top immediately, before the worksheet contents load.

**Describe alternatives you've considered**

**Additional context**

**Comment by percyliang** [comment]
Frontend refactor was responsible for this.  Should just make worksheet loading faster and more asynchronous in general (#1234).
