### ISSUE TITLE
Insert buttons show up behind rather than in front of the blocks

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1194]
Happens on Chrome Linux.
![Screenshot from 2019-06-10 16-49-34](https://user-images.githubusercontent.com/435384/59286552-cb5b9980-8c24-11e9-8142-4304f6eee3ff.png)

**Comment by epicfaace** [comment]
For me, those buttons only show up at the very bottom of the page -- I can't get them to show up above a table. How did you do that?

**Comment by percyliang** [comment]
I didn't do anything special...it's always like that for me.

**Comment by percyliang** [comment]
Not relevant.
