### ISSUE TITLE
make it visually clear that Upload/Run inserts

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1197]
One option is to add a solid black line across.

**Comment by epicfaace** [comment]
Not sure what you mean, can you elaborate @percyliang ?

![image](https://user-images.githubusercontent.com/1689183/59404521-a61d7700-8d5b-11e9-920e-7a91f134a1b4.png)

**Comment by percyliang** [comment]
The buttons kind of float in between a table, but it's not clear that if you click on one of them, where things will get inserted.  I suggested adding a dark line behind / through the buttons, so it highlights the space between rows.

**Comment by epicfaace** [comment]
Let's highlight the entire block when you hover and see the buttons.
