### ISSUE TITLE
action bar: scrolling should not affect worksheet

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#12]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Thursday Aug 06, 2015 at 06:13 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1174_

---

When focus is over action bar and use the scroll wheel, should not scroll the worksheet, but currently it does.

**Comment by codalab** [comment]
<a href="https://github.com/kashizui"><img src="https://avatars.githubusercontent.com/u/614837?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kashizui](https://github.com/kashizui)**
_Monday Oct 12, 2015 at 03:26 GMT_

----

As a corollary, would be great to have separate scrollbars for the action bar and worksheet as well!

**Comment by kashizui** [comment]
I actually can't reproduce this anymore, does this still happen for you @percyliang ?

**Comment by percyliang** [comment]
Hm, it doesn't seem to do anymore.
