### ISSUE TITLE
Jobs stuck in 'staged' state

### ISSUE THREAD

**Issue by wang-lx** [codalab/codalab-worksheets#1207]
My job has stuck in 'staged' state nearly half a day. Could you help me see what is the problem?
Here is my running bundle uuid: 0xe61e8e. Thanks!

**Comment by BoyMax** [comment]
I have the same problem now when I start to follow the tutorial of CodaLab, my running bundle uuid is: 0xea2fbd.

**Comment by percyliang** [comment]
Answered here: https://github.com/codalab/codalab-worksheets/wiki/FAQ#why-is-my-run-bundle-in-staged-for-a-long-time
