### ISSUE TITLE
[Frontend] Crashes when deleting a bundle

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1208]
- Have one bundle left.
- Delete that bundle.
- I get this error:

![image](https://user-images.githubusercontent.com/1689183/59403320-0cec6180-8d57-11e9-85c5-d646833fdcb7.png)

**Comment by epicfaace** [comment]
Confirmed.

**Comment by yipenghe** [comment]
Closing since it's done
