### ISSUE TITLE
show lines between table rows (currently only first column gets it)

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1221]

**Comment by percyliang** [comment]
![Screenshot from 2019-06-13 20-52-16](https://user-images.githubusercontent.com/435384/59482313-35d72a00-8e1d-11e9-9edd-8e2d3308feae.png)

**Comment by Matt-F-Wu** [comment]
Can't seem to reproduce somehow, maybe Nikhil fixed it?

**Comment by percyliang** [comment]
Still an issue, at least on Chrome on Linux.
