### ISSUE TITLE
make it possible to do everything with keyboard shortcuts

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1227]
For upload, run, inserting/editing markdown, etc.

- Insert text after current cell
- Upload after current cell
- Run after current cell

- Enter for showing details (expanding current table row)
- Rerun
- Kill
- Detach
- Download
- Delete

**Comment by Levilian** [comment]
Done for now, but per Percy's comment, we might want to add ‘x’ to select a bundle

**Comment by epicfaace** [comment]
X - tick a box in a bundle table
press "M" to move the selected rows to right above the row that is currently selected.

**Comment by epicfaace** [comment]
shift + R is not working to refresh

**Comment by epicfaace** [comment]
create a new bundle and then press Escape -> does not hide it.

**Comment by epicfaace** [comment]
pressing enter when selecting a call doesn't work, kind of nondeterministically fails
