### ISSUE TITLE
cl workers should report free disk space and what job they're running

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1252]

**Comment by percyliang** [comment]
`cl workers` should display have two more columns.

See `_checkin` in `worker.py` to see where the worker is generating other fields such as memory.

Probably want to add a function in `local_run_manager` to get the disk free by calling `df <worker_scratch_directory>` (should wrap it in a utility function).

**Comment by candicegjing** [comment]
@percyliang Want to clarify with you on following questions:
1. "Free disk space" meaning free disk space per user or on whole system?
2. 2rd column is going to display all of the running jobs concatenated together?

**Comment by percyliang** [comment]
1. On the whole system (`df` on the worker scratch directory).
2. This is a good question...this could get a bit long...ideally, we'd return this data to the CLI, and there would be command-line options to show or hide this information.  By default, we can just concatenate.  Later, we should build a frontend for this, in which case we can do fancier things in Javascript.

**Comment by percyliang** [comment]
Fixed via #1296
