### ISSUE TITLE
suppress PreconditionViolation if worker unreachable

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1255]
`

```JSON body:
<none>

Local variables:
message='Unable to reach worker'
condition=False

Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 148, in wrapper
    return callback(*args, **kwargs)
  File "/opt/codalab-worksheets/venv/local/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/opt/codalab-worksheets/codalab/server/json_api_plugin.py", line 18, in wrapper
    result = callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/rest/bundles.py", line 570, in _fetch_bundle_contents_blob
    uuid, path, head_lines, tail_lines, max_line_length, truncation_text, gzipped_stream
  File "/opt/codalab-worksheets/codalab/lib/download_manager.py", line 21, in wrapper
    return f(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/lib/download_manager.py", line 209, in summarize_file
    string = self._get_read_response_string(response_socket_id)
  File "/opt/codalab-worksheets/codalab/lib/download_manager.py", line 290, in _get_read_response_string
    with closing(self._get_read_response_stream(response_socket_id)) as fileobj:
  File "/opt/codalab-worksheets/codalab/lib/download_manager.py", line 279, in _get_read_response_stream
    precondition(header_message is not None, 'Unable to reach worker')
  File "/opt/codalab-worksheets/codalab/common.py", line 95, in precondition
    raise PreconditionViolation(message)
PreconditionViolation: Unable to reach worker```

This happens, especially with own workers...should tolerate it.

**Comment by percyliang** [comment]
Fixed by #1627

**Comment by epicfaace** [comment]
Understand why the previous fix didn't work, and decide whether it's a deeper issue or should just be suppressed.

**Comment by epicfaace** [comment]
Server code that raises this error: https://github.com/codalab/codalab-worksheets/blob/c2d8960bbdcda127e0ea8800b6ecd4b7849c48f7/codalab/lib/download_manager.py#L36 -- try printing out header_message

error_code instances in the worker (where the actual JSON messages are produced): https://github.com/codalab/codalab-worksheets/search?q=error_code

Example of preconditionviolation on prod (April 5, 8:14 PM ET):
/bundles/0xff7601a1e2cb4bfba1732f097ec45404/contents/blob/stderr

**Comment by adiprerepa** [comment]
when is this section called? I tried printing it with `logger.info` but either its not being called or `logger.info` isn't working. Will look into it.

**Comment by adiprerepa** [comment]
Trying to reproduce, but having trouble. Will wait for the freshest PreconditonViolation in #prod-monitoring

**Comment by adiprerepa** [comment]
try to reproduce by killing worker and then try to access bundle contents.

**Comment by epicfaace** [comment]
Steps to reproduce:
1. Create a run (such as `sleep 1800`) and wait for it to be in the "RUNNING" stage
2. Open the run bundle in the browser
3. Kill the worker
4. Refresh the browser page so you can request the bundle contents again. This should trigger the PreconditionViolation error.

**Comment by adiprerepa** [comment]
`header_message` is usually an empty dict, interesting...

![image](https://user-images.githubusercontent.com/43913660/116012147-a6386000-a5dd-11eb-83fa-0de401c8aee1.png)

**Comment by adiprerepa** [comment]
looks like we should just suppress it, it happens at random times throughout the bundle run.
![image](https://user-images.githubusercontent.com/43913660/116012194-f9121780-a5dd-11eb-9aa4-238da34a5be5.png)

**Comment by adiprerepa** [comment]
what I think is happening:

- in `download_manager.py#stream_file()`, `_get_read_response_stream` is called with a `socket_id` as a parameter.
   - this `socket_id` is taken from the `worker_socket` table (`model/tables.py#L450`)
- for some reason, in `_get_read_response_stream` the `socket_id` is invalid, so when `get_json_message` is read in `download_manager#L363`, `header_message` is `None` and we raise the `PreconditionViolation`.

is there any reason why the `socket_Id` field in the database would be wrong/no longer be valid?
