### ISSUE TITLE
automatically move uploading and running bundles to failed after a while

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1256]
Set a timeout of 60 days (which is configurable).

Also include staged bundles.  Essentially any bundle that's in `ready` or `failed`.

**Comment by percyliang** [comment]
Check out `bundle_manager.py`.

**Comment by candicegjing** [comment]
I have made some changes and tested in my local in this PR #1295 . But I am not sure using bundle.metadata.created to measure timeout is a good idea though.
