### ISSUE TITLE
pip install doesn't work : ERROR: Failed building wheel for watchdog

### ISSUE THREAD

**Issue by rcontesti** [codalab/codalab-worksheets#1257]
I 'm getting the following error, when trying to pip install in OS 10.14 into a conda python2.7 env:

`
(python2) rubens-Air-2:codelabs rcontesti$ pip install codalab
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting codalab
Collecting codalabworker>=0.3.2 (from codalab)
Requirement already satisfied: PyYAML==3.13 in /Users/rcontesti/.local/lib/python2.7/site-packages (from codalab) (3.13)
Requirement already satisfied: fusepy==2.0.4 in /Users/rcontesti/.local/lib/python2.7/site-packages (from codalab) (2.0.4)
Collecting psutil==5.4.6 (from codalab)
  Using cached https://files.pythonhosted.org/packages/51/9e/0f8f5423ce28c9109807024f7bdde776ed0b1161de20b408875de7e030c3/psutil-5.4.6.tar.gz
Collecting watchdog==0.8.3 (from codalab)
  Using cached https://files.pythonhosted.org/packages/54/7d/c7c0ad1e32b9f132075967fc353a244eb2b375a3d2f5b0ce612fd96e107e/watchdog-0.8.3.tar.gz
Requirement already satisfied: marshmallow-jsonapi==0.15.1 in /Users/rcontesti/.local/lib/python2.7/site-packages (from codalab) (0.15.1)
Requirement already satisfied: docker==3.7.0 in /Users/rcontesti/.local/lib/python2.7/site-packages (from codalab) (3.7.0)
Collecting SQLAlchemy==1.0.8 (from codalab)
Requirement already satisfied: six==1.11.0 in /Users/rcontesti/.local/lib/python2.7/site-packages (from codalab) (1.11.0)
Requirement already satisfied: marshmallow==2.6.1 in /Users/rcontesti/.local/lib/python2.7/site-packages (from codalab) (2.6.1)
Requirement already satisfied: bottle==0.12.9 in /Users/rcontesti/.local/lib/python2.7/site-packages (from codalab) (0.12.9)
Requirement already satisfied: setuptools>=40.0.0 in /Users/rcontesti/anaconda/envs/python2/lib/python2.7/site-packages (from codalab) (41.0.1)
Requirement already satisfied: argcomplete==1.9.4 in /Users/rcontesti/.local/lib/python2.7/site-packages (from codalab) (1.9.4)
Collecting argh>=0.24.1 (from watchdog==0.8.3->codalab)
  Using cached https://files.pythonhosted.org/packages/06/1c/e667a7126f0b84aaa1c56844337bf0ac12445d1beb9c8a6199a7314944bf/argh-0.26.2-py2.py3-none-any.whl
Collecting pathtools>=0.1.1 (from watchdog==0.8.3->codalab)
Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /Users/rcontesti/.local/lib/python2.7/site-packages (from docker==3.7.0->codalab) (3.7.0.1)
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /Users/rcontesti/.local/lib/python2.7/site-packages (from docker==3.7.0->codalab) (1.0.22)
Requirement already satisfied: websocket-client>=0.32.0 in /Users/rcontesti/.local/lib/python2.7/site-packages (from docker==3.7.0->codalab) (0.56.0)
Requirement already satisfied: requests!=2.18.0,>=2.14.2 in /Users/rcontesti/.local/lib/python2.7/site-packages (from docker==3.7.0->codalab) (2.22.0)
Requirement already satisfied: docker-pycreds>=0.4.0 in /Users/rcontesti/.local/lib/python2.7/site-packages (from docker==3.7.0->codalab) (0.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/rcontesti/anaconda/envs/python2/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.7.0->codalab) (2019.6.16)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/rcontesti/.local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.7.0->codalab) (1.25.3)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/rcontesti/.local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.7.0->codalab) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/rcontesti/.local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.7.0->codalab) (3.0.4)
Building wheels for collected packages: psutil, watchdog
  Building wheel for psutil (setup.py) ... error
  ERROR: Complete output from command /Users/rcontesti/anaconda/envs/python2/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/w7/8705gm1d18ldn5m5yjjl04m80000gn/T/pip-install-4uUDmN/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/w7/8705gm1d18ldn5m5yjjl04m80000gn/T/pip-wheel-uLNdjZ --python-tag cp27:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-2.7
  creating build/lib.macosx-10.6-x86_64-2.7/psutil
  copying psutil/_pswindows.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
  copying psutil/_common.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
  copying psutil/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
  copying psutil/_psosx.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
  copying psutil/_psbsd.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
  copying psutil/_psaix.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
  copying psutil/_pslinux.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
  copying psutil/_compat.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
  copying psutil/_psposix.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
  copying psutil/_exceptions.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
  copying psutil/_pssunos.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
  creating build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/test_contracts.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/test_connections.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/test_unicode.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/test_misc.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/test_posix.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/test_linux.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/test_sunos.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/test_aix.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/test_process.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/test_bsd.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/test_system.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/test_osx.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/test_memory_leaks.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/test_windows.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  copying psutil/tests/__main__.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
  running build_ext
  building 'psutil._psutil_osx' extension
  creating build/temp.macosx-10.6-x86_64-2.7
  creating build/temp.macosx-10.6-x86_64-2.7/psutil
  creating build/temp.macosx-10.6-x86_64-2.7/psutil/arch
  creating build/temp.macosx-10.6-x86_64-2.7/psutil/arch/osx
  gcc -fno-strict-aliasing -I/Users/rcontesti/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=546 -DPSUTIL_OSX=1 -I/Users/rcontesti/anaconda/envs/python2/include/python2.7 -c psutil/_psutil_common.c -o build/temp.macosx-10.6-x86_64-2.7/psutil/_psutil_common.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for psutil
  Running setup.py clean for psutil
  Building wheel for watchdog (setup.py) ... error
  ERROR: Complete output from command /Users/rcontesti/anaconda/envs/python2/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/w7/8705gm1d18ldn5m5yjjl04m80000gn/T/pip-install-4uUDmN/watchdog/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/w7/8705gm1d18ldn5m5yjjl04m80000gn/T/pip-wheel-IGX9g4 --python-tag cp27:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-2.7
  creating build/lib.macosx-10.6-x86_64-2.7/watchdog
  copying src/watchdog/watchmedo.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog
  copying src/watchdog/version.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog
  copying src/watchdog/events.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog
  copying src/watchdog/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog
  creating build/lib.macosx-10.6-x86_64-2.7/watchdog/utils
  copying src/watchdog/utils/unicode_paths.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/utils
  copying src/watchdog/utils/compat.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/utils
  copying src/watchdog/utils/win32stat.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/utils
  copying src/watchdog/utils/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/utils
  copying src/watchdog/utils/dirsnapshot.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/utils
  copying src/watchdog/utils/delayed_queue.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/utils
  copying src/watchdog/utils/platform.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/utils
  copying src/watchdog/utils/importlib2.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/utils
  copying src/watchdog/utils/bricks.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/utils
  copying src/watchdog/utils/echo.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/utils
  copying src/watchdog/utils/event_backport.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/utils
  copying src/watchdog/utils/decorators.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/utils
  creating build/lib.macosx-10.6-x86_64-2.7/watchdog/observers
  copying src/watchdog/observers/fsevents.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/observers
  copying src/watchdog/observers/inotify.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/observers
  copying src/watchdog/observers/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/observers
  copying src/watchdog/observers/api.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/observers
  copying src/watchdog/observers/inotify_buffer.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/observers
  copying src/watchdog/observers/winapi.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/observers
  copying src/watchdog/observers/read_directory_changes.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/observers
  copying src/watchdog/observers/kqueue.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/observers
  copying src/watchdog/observers/inotify_c.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/observers
  copying src/watchdog/observers/polling.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/observers
  copying src/watchdog/observers/fsevents2.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/observers
  creating build/lib.macosx-10.6-x86_64-2.7/watchdog/tricks
  copying src/watchdog/tricks/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/watchdog/tricks
  running egg_info
  writing requirements to src/watchdog.egg-info/requires.txt
  writing src/watchdog.egg-info/PKG-INFO
  writing top-level names to src/watchdog.egg-info/top_level.txt
  writing dependency_links to src/watchdog.egg-info/dependency_links.txt
  writing entry points to src/watchdog.egg-info/entry_points.txt
  reading manifest file 'src/watchdog.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.h' under directory 'src'
  writing manifest file 'src/watchdog.egg-info/SOURCES.txt'
  running build_ext
  building '_watchdog_fsevents' extension
  creating build/temp.macosx-10.6-x86_64-2.7
  creating build/temp.macosx-10.6-x86_64-2.7/src
  gcc -fno-strict-aliasing -I/Users/rcontesti/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DWATCHDOG_VERSION_STRING="0.8.3" -DWATCHDOG_VERSION_MAJOR=0 -DWATCHDOG_VERSION_MINOR=8 -DWATCHDOG_VERSION_BUILD=3 -I/Users/rcontesti/anaconda/envs/python2/include/python2.7 -c src/watchdog_fsevents.c -o build/temp.macosx-10.6-x86_64-2.7/src/watchdog_fsevents.o -std=c99 -pedantic -Wall -Wextra -fPIC -Wno-error=unused-command-line-argument-hard-error-in-future
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for watchdog
  Running setup.py clean for watchdog
Failed to build psutil watchdog
Installing collected packages: psutil, argh, pathtools, watchdog, SQLAlchemy, codalabworker, codalab
  Running setup.py install for psutil ... error
    ERROR: Complete output from command /Users/rcontesti/anaconda/envs/python2/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/w7/8705gm1d18ldn5m5yjjl04m80000gn/T/pip-install-4uUDmN/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/w7/8705gm1d18ldn5m5yjjl04m80000gn/T/pip-record-LlSdNa/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-x86_64-2.7
    creating build/lib.macosx-10.6-x86_64-2.7/psutil
    copying psutil/_pswindows.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
    copying psutil/_common.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
    copying psutil/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
    copying psutil/_psosx.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
    copying psutil/_psbsd.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
    copying psutil/_psaix.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
    copying psutil/_pslinux.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
    copying psutil/_compat.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
    copying psutil/_psposix.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
    copying psutil/_exceptions.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
    copying psutil/_pssunos.py -> build/lib.macosx-10.6-x86_64-2.7/psutil
    creating build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/test_memory_leaks.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.macosx-10.6-x86_64-2.7/psutil/tests
    running build_ext
    building 'psutil._psutil_osx' extension
    creating build/temp.macosx-10.6-x86_64-2.7
    creating build/temp.macosx-10.6-x86_64-2.7/psutil
    creating build/temp.macosx-10.6-x86_64-2.7/psutil/arch
    creating build/temp.macosx-10.6-x86_64-2.7/psutil/arch/osx
    gcc -fno-strict-aliasing -I/Users/rcontesti/anaconda/envs/python2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=546 -DPSUTIL_OSX=1 -I/Users/rcontesti/anaconda/envs/python2/include/python2.7 -c psutil/_psutil_common.c -o build/temp.macosx-10.6-x86_64-2.7/psutil/_psutil_common.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/Users/rcontesti/anaconda/envs/python2/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/w7/8705gm1d18ldn5m5yjjl04m80000gn/T/pip-install-4uUDmN/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/w7/8705gm1d18ldn5m5yjjl04m80000gn/T/pip-record-LlSdNa/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/w7/8705gm1d18ldn5m5yjjl04m80000gn/T/pip-install-4uUDmN/psutil/`

**Comment by bkgoksel** [comment]
Hi! 
Looks like it is the installation step for the `psutil` package that is failing.
Can you try to install `psutil` by itself using `pip install psutil` to confirm the issue isn't with the `psutil` installation? 
If the issue is with them, the maintainers of that package might be better at helping with the issue.

Let us know how it goes,
Kerem

**Comment by rcontesti** [comment]
Kerem, thanks a lot, it worked.

**Comment by dimitri320** [comment]
I could `pip install psutil`, got an error:

> Building wheels for collected packages: psutil
>   Building wheel for psutil (setup.py) ... error

**Comment by hackme** [comment]
for me this got resolved by xcode install  `xcode-select --install`

**Comment by HadleyKing** [comment]
> Hi!
> Looks like it is the installation step for the `psutil` package that is failing.
> Can you try to install `psutil` by itself using `pip install psutil` to confirm the issue isn't with the `psutil` installation?
> If the issue is with them, the maintainers of that package might be better at helping with the issue.
> 
> Let us know how it goes,
> Kerem

Worked for me too. Got a message that said `psutil` was already installed but then I re-ran the command for my program and `psutil` rebuilt itself. Took forever but worked!
