### ISSUE TITLE
Can't run cl work: $ bash: cl: command not found

### ISSUE THREAD

**Issue by rcontesti** [codalab/codalab-worksheets#1258]
Hi I have just installed codalab succesfully in a vm with debian and when I try to run `$cl work` it says, `bash: cl: command not found`. Any clues what might be wrong? Thanks

**Comment by percyliang** [comment]
Can you provide the exact commands you ran and the error message?  `pip install codalab` should work if you have a proper Python environment set up.

**Comment by rcontesti** [comment]
My apologies, my problem was strictly related to the path I had for codalab. Thank you.

**Comment by hrwise-nlp** [comment]
what does this mean "my problem was strictly related to the path I had for codalab" ?
I encounter this problem today.

**Comment by nelson-liu** [comment]
`path` is referring to the `$PATH` environment variable. see https://astrobiomike.github.io/unix/modifying_your_path for more info

**Comment by Opdoop** [comment]
I meet the same problem following https://codalab-worksheets.readthedocs.io/en/latest/examples/quickstart/
After ` pip install codalab -U --user`, run `cl work` get `bash: cl: command not found`.
Don't know what caused this bug, but I add alias manually, `alias cl="python ~/.local/lib/python3.6/site-packages/codalab/bin/cl.py"` solved this problem.
