### ISSUE TITLE
displaying hyperlinks of bundles

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#126]
It is useful to render bundles as hyperlinks (in addition to tables, contents).

Currently, we have % display link, which doesn't work.  We should remove the 'link' display mode.  As an aside, remove the 'inline' mode, which doesn't make sense on the web browser.

Instead, implement it as a column in a table:
% add "Parameters" url "append /output/parameters.txt | link params"
Here, 'url' is a genpath (to be implemented in worksheet_util.interpret_genpath), and append and link are new functions to support in apply_func.

Need to update documentation in worksheet_util.get_worksheet_lines.

Related to corresponding issue in:
https://github.com/codalab/codalab/issues/934

**Comment by pujun-ai** [comment]
```
% add "Parameters" url "append /output/parameters.txt | link params"
```

would add a column in the table titled Parameters with a link with text 'params' (linking to  /output/parameters.txt)

Is this the intended behavior? If so, then what is the use of 'append'? Is it only there to help us get the location of the file for which the link is to be made?

**Comment by percyliang** [comment]
This was what I was originally thinking:

url should return http://codalab.org/bundles/0x.... (but codalab.org should
not be hardcoded)

The post-processor append should append /output/parameters.txt

The post-processor link params should surround the string in a URL
So the final thing will look like:
<a href="http://codalab.org...">params</a>

I'm worried that the frontend doesn't render accept arbitrary
HTML...perhaps good to look into how to best get this information to the
frontend.

But actually, this is related to another issue.  The CLI is currently just
returning some text.  It would be good to a general mechanism of handing
more structured information back.
For example, a map from strings/offsets to a dict with more information
(this is a bundle, target, or worksheet).  This would be a more principled
way to do this.

 -Percy

**Comment by pujun-ai** [comment]
I see. I have been looking into how to make a hypertext out of the text. Returning text like 

```
 arg = '<a href="http://google.com">params</a>'                
return arg
```

does not work. Currently, I am trying to see how hyperlinks are created for the column of every table. 

Let me see if I can return a map and handle it on the codalab side without breaking a lot of things. I will keep you updated.
