### ISSUE TITLE
remove `titlejs` and `views`, `block_schemas.py`

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1260]
In general, just remove dead code that isn't being used.

**Comment by candicegjing** [comment]
I guess files under `views` are used in `codalab/rest/account.py `. 
I may look at the wrong place or have some misunderstanding about this ticket. Please let me know...

**Comment by percyliang** [comment]
I was thinking `titlejs.py` and all the places where it's referenced.  You're right you can't delete all of `views`, but delete anything that's not used.

**Comment by candicegjing** [comment]
Closed via #1354
