### ISSUE TITLE
Should blue highlight be full width?

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1266]
Should the blue highlight here be full width? Currently it's only as wide as the text, which looks odd.

![image](https://user-images.githubusercontent.com/1689183/60401661-cd38be80-9b39-11e9-97f7-a02f86479bfc.png)

**Comment by percyliang** [comment]
Yes, we should make it take up the entire width.

**Comment by yipenghe** [comment]
Looks like it's done
