### ISSUE TITLE
How to solve the " Out of time quota " ?

### ISSUE THREAD

**Issue by BIGKUANG** [codalab/codalab-worksheets#1274]
Executing any command on the control panel always return Out of time quota: 9d17h / 7d0h (139.1%), How can I fix this quickly ? Thanks~~

**Comment by percyliang** [comment]
What's your codalab username?

**Comment by BIGKUANG** [comment]
username: dakuang











------------------ 原始邮件 ------------------
发件人: "Percy Liang"<notifications@github.com>;
发送时间: 2019年7月3日(星期三) 晚上11:42
收件人: "codalab/codalab-worksheets"<codalab-worksheets@noreply.github.com>;
抄送: "Biku"<915320555@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [codalab/codalab-worksheets] How to solve the " Out of time quota" ? (#1274)




What's your codalab username?
