### ISSUE TITLE
Out of time quota: 12d0h / 7d0h (171.7%)

### ISSUE THREAD

**Issue by BiggHeadd** [codalab/codalab-worksheets#1281]
when i ran the bundle,  always return Out of time quota: 12d0h / 7d0h (171.7%), How can I fix this quickly ? Thanks~~

**Comment by BiggHeadd** [comment]
username: bighead

**Comment by percyliang** [comment]
Fixed.

**Comment by Yarkona** [comment]
Hello, i have the same problem like this. with Error: Out of time quota: 9d12h / 7d0h (136.1%). Could you please give me some advice?  username: zhying

**Comment by BiggHeadd** [comment]
Just leave a issue to the author, then he will fix it

**Comment by BiggHeadd** [comment]
> Hello, i have the same problem like this. with Error: Out of time quota: 9d12h / 7d0h (136.1%). Could you please give me some advice? username: zhying

Just leave a issue to the author, then he will fix it

**Comment by yylidiw** [comment]
Hello, i have the same problem like this. with Error: Out of time quota: 66d13h / 60d0h (110.9%). Could you please give me some advice? username: yylidiw
