### ISSUE TITLE
failure_message	Requested more disk (5.2g) than user disk quota left (5.2g)

### ISSUE THREAD

**Issue by BiggHeadd** [codalab/codalab-worksheets#1285]
**Describe the bug**

**Codalab Information**
- *Your username*:bighead
- *UUID of worksheet where problem occurred*:0xacbbfef678644251a1b9f14a3a8299e5
- *UUID of problem bundle (please don't delete)*:0xde260230648c45adb71d5d90ee9a5505
- *Error message received from Codalab (if applicable)*:failure_message	Requested more disk (5.2g) than user disk quota left (5.2g)
 - *OS (if on CLI)*:os
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;Google Chrome

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by percyliang** [comment]
Looks like you don't have more than 5GB, so your run must request less than that with `--request-disk`.
