### ISSUE TITLE
allow using CLI when behind a proxy

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1288]
Allow the proxy information to be passed into the CLI.

**Comment by prakhar6sharma** [comment]
Thanks for this issue.

Please look into this fast, as COIN workshop deadline is near and we can't upload our files since almost all universities work behind a proxy.

**Comment by percyliang** [comment]
It's unlikely that we will support this soon though.  You can always upload files via the web interface (for directories, upload a zip file).

**Comment by bkgoksel** [comment]
Isn't this solved by #959 ?

**Comment by percyliang** [comment]
I guess it is, thanks.
