### ISSUE TITLE
worker fails with docker network interface, doesn't remove containers

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1291]
worker-1    | 2019-07-16 17:23:00,122 http://localhost:None "POST /v1.35/containers/create HTTP/1.1" 201 201
worker-1    | 2019-07-16 17:23:00,129 http://localhost:None "GET /v1.35/containers/c7eb3ac6103454241a98e49bbbc29ac716be3dbf7d85f279a2836f918528d251/json HTTP/1.1" 200 None
worker-1    | 2019-07-16 17:23:05,891 http://localhost:None "POST /v1.35/containers/c7eb3ac6103454241a98e49bbbc29ac716be3dbf7d85f279a2836f918528d251/start HTTP/1.1" 204 0
worker-1    | 2019-07-16 17:23:05,892 Started Docker container for UUID 0x3ee3348280ce42a3ae76a437636caf03, container ID c7eb3ac6103454241a98e49bbbc29ac716be3dbf7d85f279a2836f918528d251,
worker-1    | 2019-07-16 17:23:05,895 http://localhost:None "POST /v1.35/networks/3fc7dba630171bf4a243563e30b0349e836ff61b12f63efffea32776eb7f2188/connect HTTP/1.1" 403 100
worker-1    | Traceback (most recent call last):
worker-1    |   File "/opt/worker/codalabworker/worker.py", line 51, in start
worker-1    |     self._run_manager.process_runs()
worker-1    |   File "/opt/worker/codalabworker/local_run/local_run_manager.py", line 171, in process_runs
worker-1    |     self._runs[bundle_uuid] = self._run_state_manager.transition(run_state)
worker-1    |   File "/opt/worker/codalabworker/fsm.py", line 35, in transition
worker-1    |     return self._transition_functions[state.stage](state)
worker-1    |   File "/opt/worker/codalabworker/local_run/local_run_state.py", line 254, in _transition_from_PREPARING
worker-1    |     self.worker_docker_network.connect(container)
worker-1    |   File "/usr/local/lib/python2.7/dist-packages/docker/models/networks.py", line 57, in connect
worker-1    |     container, self.id, *args, **kwargs
worker-1    |   File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 19, in wrapped
worker-1    |     return f(self, resource_id, *args, **kwargs)
worker-1    |   File "/usr/local/lib/python2.7/dist-packages/docker/api/network.py", line 248, in connect_container_to_network
worker-1    |     self._raise_for_status(res)
worker-1    |   File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 258, in _raise_for_status
worker-1    |     raise create_api_error_from_http_exception(e)
worker-1    |   File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
worker-1    |     raise cls(e, response=response, explanation=explanation)
worker-1    | APIError: 403 Client Error: Forbidden ("endpoint with name nifty_khayyam already exists in network codalab_worker_network_int")
worker-1    | 2019-07-16 17:23:06,922 http://localhost:None "GET /v1.35/images/tensorflow/tensorflow:1.12.0-gpu-py3/json HTTP/1.1" 200 None

Happening on prod.

**Comment by nelson-liu** [comment]
Seems related, but a bunch of my jobs (running on the nlp cluster via `nlp-cl-worker`) are failing with `Cannot start Docker container: Unable to start Docker container: 400 Client Error: Bad Request ("network codalab_worker_network_int is ambiguous (2 matches found on name)")--`

**Comment by nelson-liu** [comment]
Perhaps also relevant, I consistently see:
`2019-09-27 00:27:52,699 Cannot clear docker networks: 403 Client Error: Forbidden for url: http+docker://localhost/v1.35/networks/7f0695b45a583b9c381870375b56eb3c7c15247b47deb076d413584889dd5c59`

(with a different url)

after quitting a `nlp-cl-worker`

**Comment by bkgoksel** [comment]
Main issue fixed by #1438 
Will make a separate issue for the problem reported by @nelson-liu
