### ISSUE TITLE
cli commands should return more structured information

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#130]
cl wls, ls, etc. shows uuids which are too short to be able to recover URL on the client side.
Need to modify bundle_cli.do_*_command needs to somehow return more information; just return the dict mapping strings to information to render:
{‘refs’: {‘0x23523’: {‘type’: ‘bundle’, ‘uuid’: ‘0x235234982348972’, ‘name’: ‘asdf’}, …}}

**Comment by pujun-ai** [comment]
Should structured information be returned for all cl commands or just some specific ones (like cl wls, ls, info)?

 Because for some methods (like rm, mimic, macro), the returned information might not be required.  But to maintain consistency, this could be implemented for all do_\* methods.

**Comment by percyliang** [comment]
By default, the information returned is None.
Eventually, all commands that have some 0x... should return structured
information.
For now, just support cl wls, cl ls, and cl search with a general framework
and put a P3 ticket to handle the rest.
