### ISSUE TITLE
[USER ISSUE] Jobs run through cl-worker don't have root

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#1303]
**Describe the bug**
Jobs that are executed by a locally running `cl-worker` instance (in this case, on jagupard23.stanford.edu) do not have `root` access. This differs from behavior on azure machines, where jobs do have `root`.

**Codalab Information**
- *Your username*: robinjia
- *UUID of worksheet where problem occurred*: 0xf3d92e292674464ea2dc3b6a31059397
- *UUID of problem bundle (please don't delete)*: 0xb0f2fea72a1b41cdada862fb4d93cd9c

**To Reproduce**
Steps to reproduce the behavior :
1. Start up a `cl-worker` instance on the Stanford cluster
2. Run the exact command in the bundle provided above

**Expected behavior**
`whoami` should print `root` and the `touch` command should not fail, as in bundle 0xecc0d1ecacc843fb9441bf10dcc0bb9d

**Additional context**
This is important for the MRQA shared task, because multiple submissions have attempted to install dependencies at the beginning of a run bundle. The lack of `root` makes these installation attempts behave differently on Azure and our local machines. We want to test on local machines because we can use better GPUs---we are imposing a time limit for submissions based on how long they take to run on machines with good GPUs, which are not available on Azure.

**Comment by percyliang** [comment]
When you run your own `cl-worker`, we don't run the job as `root`, otherwise it will create a bunch of files in the `codalab-worker-scratch` directory that are owned by root and you can't delete them normally.  (Of course you can still delete them from inside docker - `docker run ... rm ...`)

The sane thing to do would be to always use a non-root environment (on Azure in particular), but this could break some people's jobs...do you know how big of a deal that would be?

**Comment by robinjia** [comment]
Hmm I see. It might break quite a few existing jobs because you would have to supply `--user` to `pip` and so on, but I don't think this is a huge issue if it's well documented.

**Comment by tscholak** [comment]
I'd like a switch that runs it as `root`.

**Comment by tscholak** [comment]
I'm going to hack this locally: https://github.com/codalab/codalab-worksheets/blob/462fc96371b74e7b79b3acccf1a385d42d36f873/codalab/worker/docker_utils.py#L172
