### ISSUE TITLE
[Python 3] Running codalab_service.py start twice gives an error

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1321]
If I run the following:

```
python3.6 codalab_service.py start -b -s default
python3.6 codalab_service.py start -b -s default
```

then I get the following error on the second time:

```
failed to export image: failed to create image: failed to get layer sha256:b6b704651fd77cbfd9ce3fb422cbfaaeb8a3c625669c6876f671544ffabfce8d: layer does not exist
```

However, it works fine if I do

```
python3.6 codalab_service.py start -b -s default
python3.6 codalab_service.py stop
python3.6 codalab_service.py start -b -s default
```

Not sure if this is present on master as well.

**Comment by percyliang** [comment]
@epicfaace Are you still getting this?  I've never seen this before.

**Comment by epicfaace** [comment]
Yeah, I'm still getting it. I have to keep running codalab twice in order for it to build properly. Not sure how to reproduce it though.

The following are the steps I take to make it work though:
```
python3.6 codalab_service.py start -b -s default # fails
python3.6 codalab_service.py start -b -s default # works a second time
```

It also happens with python 2, so perhaps it's a Docker issue.

**Comment by percyliang** [comment]
Once it works a second time, does it consistently work after that?

Does it only fail once you've made changes?

**Comment by epicfaace** [comment]
No to both.

Basically, to get around this, I've made an alias 
```
alias start='python3.6 codalab_service.py start -b -s default'
```

and whenever I want to run codalab again (whether or not I made changes), I run `start; start`.

**Comment by percyliang** [comment]
Is anyone else having this problem @candicegjing ?  I still have never seen this.

**Comment by epicfaace** [comment]
It's not coming for me anymore.
