### ISSUE TITLE
[USER ISSUE] size parameter on `display image` no longer works

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#1342]
**Describe the bug**
The `size=XYZ` parameter no longer does anything for a `display image` row item.

**Codalab Information**
- *Your username*: robinjia
- *UUID of worksheet where problem occurred*: 0xe3eb416773ed4883bb737662b31b4948
 - *Browser (if on Web)*; Chrome (also confirmed on Firefox)

**To Reproduce**
Steps to reproduce the behavior :
1. Go to https://worksheets.codalab.org/worksheets/0xe3eb416773ed4883bb737662b31b4948

**Expected behavior**
The image is supposed to be 400 pixels wide, but it is not. I'm very confident that when I made that worksheet originally, I made it sized properly, so it's not like I typed a directive wrong.

**Screenshots**
![image](https://user-images.githubusercontent.com/7267349/64072293-d846c280-cc40-11e9-9e32-0473d48e0515.png)

**Comment by yipenghe** [comment]
Will be fixed by #1441, thanks!
