### ISSUE TITLE
codalab_service.py: migrate first

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1345]
Currently, deployment doesn't work when we require a migration because we try to call `create-root-user.py` then do the alembic migrate, but then we're not using the right database schema for the former.

Instead we need to do:
- If database exists, alembic upgrade
- create-root-user
- alembic stamp

**Comment by candicegjing** [comment]
Want to confirm that is this ticket to update deployment documentation or add logic to our code?

**Comment by percyliang** [comment]
This should update our code codalab_service.py.
