### ISSUE TITLE
Get rid of codalabworker package and just have one codalab package

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1346]
This will simplify the currently convoluted dependencies between codalab and codalabworker.

**Comment by candicegjing** [comment]
For this ticket, I'll move everything underneath the `codalabworker` package to `codalab/worker` directory and change any related code/settings accordingly.

**Comment by percyliang** [comment]
That seems okay...the only thing that's suboptimal is that `codalab/worker` will now contain the bundle manager (server-side) and the worker code (client-side).  Perhaps put comments at the top to clearly indicate this.

In a separate PR, we can move `default_bundle_manager.py` into `bundle_manager.py` since there's only going to be one.

Remember to update the docs (especially Code Overview).

**Comment by candicegjing** [comment]
Maybe split them into two subdirectories: server and client respectiely under `codalab/worker`?

**Comment by percyliang** [comment]
Let's put the worker client code in `codalab/worker`, since `worker` should mean client.  We can move the `bundle_manager.py` to `codalab/server` for now, because it's only partially about workers anyway.
