### ISSUE TITLE
when update docker images, `cl run` should pull

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1355]
When run a job, should do the equivalent of `docker pull` to always make sure we have the latest version of a docker image.

**Comment by candicegjing** [comment]
This is for `do_run_command` in `bundle_cli.py` right?

**Comment by candicegjing** [comment]
Questions:
1. I searched through our code and documentation, I didn't find how the default-[c/g]pu is used/deployed. I must be missing something at somewhere. 
2. We want to add this to `bundle_cli.py` right?

**Comment by percyliang** [comment]
No, this needs to be done on the worker side, in particular in `docker_image_manager.py`, probably the `get` function.
