### ISSUE TITLE
Allow more than 10GB in a docker container 

### ISSUE THREAD

**Issue by tonyyyang** [codalab/codalab-worksheets#136]
Large disk size might be needed when processing image dataset. So far the default limitation is 10g, and simply `--requeset_disk 20g` doesn't change the limitation.

Reference bundle: https://www.codalab.org/bundles/0x3173a2557ca94135a8e8d94fa22e7e0f/
Side note: In the reference bundle, the folder lots_of_jpeg_files contains thousands of jpeg files. So it may take a while for the file browser to present the contents of it.

**Comment by percyliang** [comment]
It is possible to run jobs that write files more than 10GB now.
