### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1366]
http://worksheets.codalab.org and http://worksheets-dev.codalab.org should redirect to HTTPS.

https://security.stackexchange.com/questions/49645/actually-isnt-it-bad-to-redirect-http-to-https

**Comment by percyliang** [comment]
This is somewhat urgent as verification emails have http://... in them.

**Comment by epicfaace** [comment]
Turns out that #1399 didn't actually fix this (it's no longer a problem for email verification, though, because the link correctly has https:// in it)

http://worksheets-dev.codalab.org actually redirects to 127.0.0.1 because of this code:

https://github.com/codalab/codalab-worksheets/blob/0fa3fd3f66a8df199ac11f4563bf561f6d895694/docker/compose_files/files/nginx.conf.ssl#L71-L78

How do we get the actual server name in the nginx configuration?

(Also, it ends up doing a permanent redirect which will probably be cached, so maybe we should consider fixing / just removing this redirect before deploying to prod)
