### ISSUE TITLE
pushing to master doesn't trigger building readthedocs

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1368]

**Comment by epicfaace** [comment]
readthedocs has the following error: "Payload not valid, invalid or missing signature"

[This site](https://stackoverflow.com/questions/55475282/read-the-docs-with-github-webhook-results-in-400-payload-not-valid-invalid-or) suggests to remove the hook from readthedocs.org and github.com, then add it back.

**Comment by candicegjing** [comment]
I don't think I have the right permission to see `setting` page from Github, and `Integration` page from Readthedocs based on documenation: https://docs.readthedocs.io/en/stable/webhooks.html

**Comment by epicfaace** [comment]
Fixed by removing / adding the hooks.
