### ISSUE TITLE
Travis fails on specially-named branches 

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1369]
For example, dependabot creates branches with slashes in their name. This causes the travis ci build to fail with the following message:

Status: Downloaded newer image for codalab/server:master
invalid argument "codalab/server:dependabot/npm_and_yarn/frontend/bootstrap-4.3.1" for "-t, --tag" flag: invalid reference format

**Comment by percyliang** [comment]
I guess in `codalab_service.py` we should set the default version to be the branch name but replacing slashes with '_' or something.
