### ISSUE TITLE
don't try to push to Docker Hub if don't have credentials

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1378]
If someone not on the CodaLab team submits a PR, then tests fail because travis tries to push to docker hub.  If `$CODALAB_DOCKER_USERNAME` is not set, then we shouldn't try to do this.

There are several places where we could add this logic...maybe `travis-deploy.sh`?

**Comment by candicegjing** [comment]
I am not able to see Travis settings for our repo but found an example: https://travis-ci.org/codalab/codalab-worksheets/jobs/587900757. The error happened at the end of the **Functionality Build**. So will `travis-deploy.sh` be linked to travis ci settings somewhere? Just wondering how are we going to use this script and then determine what it should be returned.

**Comment by percyliang** [comment]
In `.travis.yml`, you can see the call to `./codalab_service.py ... --push`, which fails if the credentials are not in the envrionment.  `./travis-deploy.sh` should call `./codalab_service.py ... --push` too.  Actually, `travis-deploy.sh` seems to be an empty file right now, which is another problem that needs to be fixed.

So we just need to check if the environment variable `$CODALAB_DOCKER_USERNAME` exists, and if not then just don't push and print a warning.  It'd be easiest to do it in `./codalab_service.py` actually, though.
