### ISSUE TITLE
Add host_worksheets to genpath

### ISSUE THREAD

**Issue by tonyyyang** [codalab/codalab-worksheets#138]
We should be able to do

```
% display table host_worksheet
[bundle]
```

to show a column with a link to the host worksheet (if there is more than one, just return the first one).

To do this, several things need to happen:

1) We need to have get_bundle_infos return host_worksheet (similar to how we need the `-v` in  `cl info -f host_worksheets <bundle> -v`).

2) The returned value from worksheet_util.interpret_genpath should be a dict {type: 'worksheet', uuid: ..., name: ...} (or something like this; need to sync with displaying bundle links).

3) On the frontend, a link should be displayed.

**Comment by yipenghe** [comment]
It's working on dashboard
![Screenshot from 2019-11-26 00-53-46](https://user-images.githubusercontent.com/23012631/69613971-494f0980-0fe7-11ea-8b80-469e8f0d1dcd.png)

But not on public home..
![Screenshot from 2019-11-26 00-50-09](https://user-images.githubusercontent.com/23012631/69613772-00975080-0fe7-11ea-9434-bb1469fdbea8.png)
