### ISSUE TITLE
[USER ISSUE]

### ISSUE THREAD

**Issue by mcclow12** [codalab/codalab-worksheets#1390]
**Describe the bug**
Unable to activate account with authentication email link. I get the confirmation email to activate my account but when I try to follow the link I get the error:

(Chrome)
This site can’t be reached 
worksheets.codalab.org refused to connect.

(Firefox)
Unable to connect
Firefox can’t establish a connection to the server at worksheets.codalab.org.

I can access worksheets.codalab.org with no issues. I can also sign in to my account. (Though I can't use the account because it hasn't been activated.) I only have an error when following the confirmation email link.

**Codalab Information**
Tried with 
- *Your username*: mcclow12, mcclow121
- *Browser (if on Web)*: Chrome, Firefox

**Comment by epicfaace** [comment]
Try replacing http:// in the url to https://. (probably related to #1386)

**Comment by mcclow12** [comment]
Great that worked for me. Thanks for the quick reply!
