### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by h-peng17** [codalab/codalab-worksheets#1401]
When I use command "pip install codalab", it failed. 
**And my env was:**
     active environment : ph
    active env location : /home/penghao_tmp/.conda/envs/ph
            shell level : 1
       user config file : /home/penghao_tmp/.condarc
 populated config files : 
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : /usr/local/anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /usr/local/anaconda3/pkgs
                          /home/penghao_tmp/.conda/pkgs
       envs directories : /home/penghao_tmp/.conda/envs
                          /usr/local/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/4.15.0-51-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1013:1013
             netrc file : None
           offline mode : False 
**The log info was below:**
Collecting codalab
  Using cached https://files.pythonhosted.org/packages/56/3c/70f441cbb7e6df0cc667d6f924d797638c72e853f24ef013473ca6dc1d20/codalab-0.2.37.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/penghao_tmp/.conda/envs/ph/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ubgtugv5/codalab/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ubgtugv5/codalab/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-ubgtugv5/codalab/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ubgtugv5/codalab/setup.py", line 5, in <module>
        from codalab.common import CODALAB_VERSION
      File "/tmp/pip-install-ubgtugv5/codalab/codalab/common.py", line 7, in <module>
        import httplib
    ModuleNotFoundError: No module named 'httplib'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

How can i solve this issue? thank you

**Comment by candicegjing** [comment]
Is this blocking your work? A Github issue #1404 has been created to track this problem.
