### ISSUE TITLE
Pushing new version of codalab package to PyPI didn't happen during release. 

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1404]

**Comment by h-peng17** [comment]
**My pip version is the latest 19.2.3. But when I use "pip install codalab==0.3.3" for the latest codalab, it gived error:**
 ERROR: Could not find a version that satisfies the requirement codalab==0.3.3 (from versions: 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.18, 0.2.21, 0.2.23, 0.2.24, 0.2.25, 0.2.26, 0.2.31, 0.2.32, 0.2.33, 0.2.34, 0.2.35, 0.2.36, 0.2.37)
ERROR: No matching distribution found for codalab==0.3.3

**Comment by bkgoksel** [comment]
Since ver 0.2.38, codalab is only published to pip2.7, this error message is common when pip3 is used.

**Comment by h-peng17** [comment]
Thank you! I have solved this problem using pip2 install codalab==0.3.3.

**Comment by epicfaace** [comment]
@candicegjing were you referring to the issue above or to 0.4.0?

**Comment by epicfaace** [comment]
Never mind, I see this is from #1401, so closing this.
