### ISSUE TITLE
[USER ISSUE] Custom docker images are not always up to date

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#1413]
**Describe the bug**

For some reason, codalab seems to be using older versions of custom docker images (on dockerhub), even after the tag has been updated. Perhaps there's something about caching here? I was able to get codalab to use the updated custom docker image I pushed to docker hub after explicitly requesting the digest.

**Codalab Information**
- *Your username*: nfliu
 - *OS (if on CLI)*: os x
 - *Codalab CLI Version (if on CLI)*: 0.4.0

**To Reproduce**
Steps to reproduce the behavior :
1. Create image on docker hub
2. Run build with that image/tag
3. Update image
4. Run another build with that image/tag (it should use the updated one, but it doesn't).

**Additional context**
Sorry, this seems very difficult to debug / quite involved to repro---just thought I'd raise an issue anyway. Thanks!

**Comment by percyliang** [comment]
Believe this is the same as #1355 .  We fixed this problem in the past, but there must have been a regression.

**Comment by nelson-liu** [comment]
Yup, this is the same as #1355---sorry. Closing as duplicated, since both are on the kanban board anyway.
