### ISSUE TITLE
[FEATURE REQUEST] Write to an env variable when job is being executed on CodaLab

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#1414]
**Is your feature request related to a problem? Please describe.**

It'd be nice to be able to programmatically discern whether a particular run is happening within codalab or not (as opposed to, say, just running it interactively on your laptop).

**Describe the solution you'd like**

I'd like something similar to [TravisCI's environment variables](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables). For instance, in each CI run, they set `TRAVIS=true`. It'd be good if CodaLab set an environment variable like `CODALAB=true`

**Describe alternatives you've considered**

None yet, but all ears if anyone has better ideas.

**Comment by percyliang** [comment]
When we launch a run (`start_bundle_container` in `docker_utils.py`), just add an environment variable.
