### ISSUE TITLE
Upgrade GPU workers to use builtin Docker GPU support

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1426]
Currently we're using `nvidia-docker2` via specifying the docker runtime with the `--runtime nvidia` option when starting GPU containers. Turns out that too was deprecated as of Docker 19.03 as Docker now has builtin support for GPU devices. We should switch our worker code to use the builtin docker functionality, as described below:

https://github.com/NVIDIA/nvidia-docker

**Comment by bkgoksel** [comment]
Looks like support for this is still not in the docker-py package, which we use for launching containers:
docker/docker-py#2395
docker/docker-py#2419
docker/docker-py#2471

**Comment by epicfaace** [comment]
We no longer use nvidia-docker2. We use nvidia-docker now.
