### ISSUE TITLE
when upgrade CodaLab, leaves user in weird state

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1428]
Whenever we upgrade CodaLab, in a browser where a user is logged in, it still looks like you're logged in, but when you click on 'My Home', it errors out.  Right behavior is just to keep people logged in.

**Comment by epicfaace** [comment]
Yeah, this is because we changed the login cookie structure to store a json object rather than a pickle. I remember we discussed this and agreed this wasn't a big deal, but perhaps the least we should do is log the user out upon upgrade, rather than giving a confusing error.

**Comment by percyliang** [comment]
Are you sure this is the only problem?  If it is, then I think that's fine
since we've switched over.  But I thought it was more than that, but I
could be misremembering.
