### ISSUE TITLE
disappearing list of bundles

### ISSUE THREAD

**Issue by sidaw** [codalab/codalab-worksheets#143]
To reproduce,
1) go to a worksheet with a few dependent bundles, which are normally listed on the right panel.
2) Now edit source, and save. 
Result: the list of dependent bundles disappears, and they would reappear on refresh the page.
My environment: OSX and chrome.

**Comment by ChengshuLi** [comment]
Hi Sida,

I will try to fix it tonight. Thanks for letting us know.

**Comment by ChengshuLi** [comment]
Hi Sida, I was trying to reproduce the bug just now. Would you mind clarifying a little bit more about what you mean by the list of bundles? 

1) when your focus is on the worksheet
<img width="314" alt="screenshot" src="https://cloud.githubusercontent.com/assets/6732996/14408845/c4f983f0-feb9-11e5-9977-16ec3805f3f1.png">

2) when your focus is on a bundle
<img width="312" alt="screenshot" src="https://cloud.githubusercontent.com/assets/6732996/14408849/e9d43d0a-feb9-11e5-8b25-49cdb17f9cb9.png">

Do you mean the first one or the second one? Thank you!

**Comment by kashizui** [comment]
@sidaw are you still seeing this issue? Please respond with more details.
