### ISSUE TITLE
[USER ISSUE] some worksheets not shown in dashboard

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#1430]
**Describe the bug**
It used to be that all of my worksheets were listed on the web interface dashboard under "My worksheets". Now some are missing.

Actually, I figured out it's due to `cl wsearch` defaulting to limit of 10. If I run `cl wsearch .mine` I only see 10 worksheets, but doing `cl wsearch .mine .limit=100` gets all of them. So, I guess I know how to fix it for my dashboard, but I still think this is bad behavior.

**Codalab Information**
- *Your username*: robinjia
- *UUID of worksheet where problem occurred*: 0xb843335f02a9443995db2013fbe2e7f4
- *UUID of problem bundle (please don't delete)*: Not a bundle, but for example worksheet 0xbe5f6ba1dd1c47ab8fe68c9b885f3e22 is missing
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*; Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Go to https://worksheets.codalab.org/worksheets/0xb843335f02a9443995db2013fbe2e7f4/

**Expected behavior**
Lots of worksheets should show up, including 0xbe5f6ba1dd1c47ab8fe68c9b885f3e22 (called "MRQA 2019 Shared Task Private Leaderboard"). Instead only 10 worksheets show up.
**Screenshots**

**Additional context**

**Comment by epicfaace** [comment]
Perhaps we can make it so that limit=-1 returns all worksheets.

@percyliang does that sound good?

**Comment by robinjia** [comment]
I do understand the desire to have some limit. But then the UI should make it clear that there is a limit  and some worksheets are not displayed (my first reaction was, have my worksheets somehow been deleted?!).

**Comment by percyliang** [comment]
Already increased the limit, closing for now.
