### ISSUE TITLE
[USER ISSUE] Weird characters in worksheet name

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#1436]
**Describe the bug**
This is minor, but it seems like special characters aren't displayed properly in worksheet names in the dashboard.

**Codalab Information**
- *Your username*: robinjia
- *UUID of worksheet where problem occurred*: 0xb843335f02a9443995db2013fbe2e7f4
- *UUID of problem bundle (please don't delete)*: affects the listing of the worksheet 0x9a15a170809f4e2cb7940e1f256dee55 
- *Error message received from Codalab (if applicable)*: The following is displayed:

Know What You Donât Know: Unanswerable Questions for SQuAD (ACL 2018) [squadrun-acl2018]

 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*; Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Go to https://worksheets.codalab.org/worksheets/0xb843335f02a9443995db2013fbe2e7f4/
**Expected behavior**
Should say "Don't" instead of these weird characters.

**Screenshots**
![image](https://user-images.githubusercontent.com/7267349/65803789-89ebed00-e134-11e9-816d-2159919456a0.png)

**Additional context**

**Comment by yipenghe** [comment]
Hi, is it still displaying like this? Can't see the display myself since the worksheet is your dashboard

**Comment by robinjia** [comment]
Yes, in fact if you just visit this worksheet you'll see the same thing: https://worksheets.codalab.org/worksheets/0x9a15a170809f4e2cb7940e1f256dee55

**Comment by yipenghe** [comment]
Thanks! I will work on it

**Comment by yipenghe** [comment]
Thanks for reporting this, this will be fixed in the new frontend

**Comment by yipenghe** [comment]
It will also be fixed in current frontend in next release #1568
