### ISSUE TITLE
[USER ISSUE] Out of time quota: 21d23h / 7d0h (313.9%) 

### ISSUE THREAD

**Issue by LegendaryDan** [codalab/codalab-worksheets#1440]
I have two accounts that are out of quota and I even cannot create a bundle. 

username1: hongyu
username2: hongyu01

Could you please help to fix it?

Thanks. 

Jing

**Comment by candicegjing** [comment]
We noticed that you had registered two accounts in our system. We prefer to keep one account per user. If you would like to delete one, we can increase your time quota for another account. Please let us know which account you would like us to fix.
