### ISSUE TITLE
#worksheet_content hides dropdown of profile button

### ISSUE THREAD

**Issue by Levilian** [codalab/codalab-worksheets#1442]
**Description**
The dropdown menu of the profile button is hidden behind the #worksheet_content bar. 
This happens on any worksheet in the new frontend. 

**Screenshots**
<img width="1393" alt="Screen Shot 2019-09-30 at 11 19 29 PM" src="https://user-images.githubusercontent.com/13169407/65939107-c68c4280-e3d9-11e9-994f-c94a5c32849f.png">
<img width="1322" alt="Screen Shot 2019-09-30 at 11 51 56 AM" src="https://user-images.githubusercontent.com/13169407/65939110-c9873300-e3d9-11e9-8a3c-1ed128613c04.png">

**Comment by epicfaace** [comment]
This similarly happens when opening keyboard shortcuts (shift + /):

![image](https://user-images.githubusercontent.com/1689183/66002945-b3b95280-e459-11e9-8586-d3bff66c63cc.png)


We should decrease the z-index of the header.
