### ISSUE TITLE
make header take up less vertical space, buttons more consistent

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1456]
Also make the web terminal thinner.

Ideally, make the worksheet header the same height as the top header.

**Comment by epicfaace** [comment]
- Remove "View" button
- Hide terminal by default, have a "terminal" icon to open the terminal
- Replace buttons in mockup with material ui icons / texts
- worksheet info: say "home by codalab [you(all) public(read)]"
