### ISSUE TITLE
REST API for loading worksheet is slow

### ISSUE THREAD

**Issue by ppasupat** [codalab/codalab-worksheets#147]
It seems that the API for loading a worksheet (`/rest/api/worksheets/<uuid>`) is transferring a lot of data. It turns out that the response JSON contains the list of all files in all bundles even though they are not needed for displaying the worksheet. The transfer is also not compressed I think.

On the worksheet page, selecting a bundle issues another API request which loads the list of files in the selected bundle, so I'm not sure why the worksheet API needs to return the file lists.

Example:
https://worksheets.codalab.org/worksheets/0x03d1850e5dce4578948a38bcf760acab/

**Comment by ppasupat** [comment]
On a related note, loading the worksheets page also seems to issue bundle read API (`/rest/api/bundles/content/<uuid>`) for **each** bundle in addition to the worksheet read API. I'm not sure if this is redundant.

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1083
