### ISSUE TITLE
Search with .sum keyword fails on bundle metadata

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#148]
The "search" test in `test-cli.py` fails. 

Moreover, the following will always output a large integer that I can't seem to identify:

```
cl search name=test data_size=.sum
cl search name=test description=.sum
cl search name=test name=.sum
```

**Comment by percyliang** [comment]
Hm, works for me (Ubuntu 14.04).  More details about your environment?

**Comment by kashizui** [comment]
I'm on OS X 10.10, and the backing store is sqlite.

Might it make a difference if I probably have a lot of old bundles unattached to worksheets?

**Comment by kashizui** [comment]
I am also getting `UsageError: bundle spec LICENSE.txt doesn't match (want index 1 out of 0 bundles)` when I try relative indices like `cl info ^1` at the moment.

I should probably try resetting my database, but I will spend some time seeing if this is a real problem first.

**Comment by kashizui** [comment]
Hitting the same problems even after purging my `~/.codalab` directory.

**Comment by kashizui** [comment]
@pbhatnagar3 Let me know if you can run `cl info ^1` on Mac, or test-cli.py! Thanks a lot :)

**Comment by kashizui** [comment]
No longer able to reproduce this-- closing.
