### ISSUE TITLE
[USER ISSUE] Reduce cl-worker disk space usage

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#1484]
Perhaps related to #880

**Describe the bug**

Workers run out of disk space, partially because their working directory is quite massive.

**Codalab Information**
- *Your username*: nfliu
- *UUID of worksheet where problem occurred*:
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:

```
  File "/juice/u/nlp/data/codalab/cl-venv/local/lib/python2.7/site-packages/codalabworker/worker.py", line 52, in start
    self._run_manager.save_state()
  File "/juice/u/nlp/data/codalab/cl-venv/local/lib/python2.7/site-packages/codalabworker/local_run/local_run_manager.py", line 95, in save_state
    self._state_committer.commit(simple_runs)
  File "/juice/u/nlp/data/codalab/cl-venv/local/lib/python2.7/site-packages/codalabworker/state_committer.py", line 34, in commit
    shutil.copyfile(f.name, self._state_file)
  File "/usr/lib/python2.7/shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
  File "/usr/lib/python2.7/shutil.py", line 52, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device
```
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :
1. Go to jagupard19
2. Run `nlp-cl-worker`
3. Run a many bundles

**Expected behavior**

The worker seems like it could be better at cleaning up--here's the disk usage of the various folders in the worker directory.

```
(base) nfliu at jagupard19 in /jagupard19/scr1/nfliu-cl-worker
$ du -sh *
7.1G	dependencies
12K	dependencies-state.json
2.4G	runs
104K	run-state.json
```

Maybe there should be a way to control caching dependencies?

**Comment by nelson-liu** [comment]
To follow on: I could use `--max-work-dir-size`, but sometimes other jobs from other users take up a bunch of disk space while I'm running the worker and my `--max-work-dir-size` might not matter in the end. In general, I guess I wish there was a better way to handle failing when there is no disk space. Probably isn't high-priority, since I can always just change the work dir...

**Comment by candicegjing** [comment]
The current file stats of reported directory listed [above](https://github.com/codalab/codalab-worksheets/issues/1484#issue-504261904) is as follows:
```
(py-3.6.8) jingge19@jagupard19:/jagupard19/scr1/nfliu-cl-worker$ du -sh * 
2.2M	dependencies
4.0K	dependencies-state.json
6.2M	runs
8.0K	run-state.json
```
Contacted the reporter of this issue @nelson-liu, and it seems that his issue no longer appears as he also set up a cron job to clean up the dependencies. 
One additional thought for this ticket is that given we sync states between those dependency files whenever we restart the worker, and this syncing phase only happens at the beginning of a worker's life cycle, we might want to double-check on how those dependencies get emitted during the middle of a worker's life cycle.
