### ISSUE TITLE
[USER ISSUE] Worker finalizing bundles can be very slow

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#1485]
**Describe the bug**

I'm consistently seeing run bundles take an unreasonably long time to finalize, given their size (15 minutes for a 129k file).

**Codalab Information**
- *Your username*: nfliu
- *UUID of worksheet where problem occurred*: 0xf6bae43872f14e4a88bb2c549abfe873
- *UUID of problem bundle (please don't delete)*: [0x587da02384d541a38cf2b02d67901c0b](https://worksheets.codalab.org/bundles/0x587da02384d541a38cf2b02d67901c0b)
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*: Mac OS Mojave
 - *Codalab CLI Version (if on CLI)*: `master`
 - *Browser (if on Web)*; Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Run a `cl-worker` on master
2. Run a bundle.

**Expected behavior**
Finalizing the bundle should not take 15 minutes

**Screenshots**

Here's what I'm seeing in the worker logs:

```
2019-10-08 20:26:29,885 Uploading results for run with UUID 0x587da02384d541a38cf2b02d67901c0b
2019-10-08 20:40:40,248 Received mark_finalized message: {'type': 'mark_finalized', 'uuid': '0x587da02384d541a38cf2b02d67901c0b', 'meta': {'version': '0.4.3'}}
```

Note the timestamps, it takes nearly 15 minutes to "upload results" for a 129k bundle. I don't think it takes actually 15 minutes, so it'd be good to get some more information about what else is happening in the `finalizing` state.

**Additional context**

I have a `--max-work-dir-size` of `20g` on this worker.

**Comment by Levilian** [comment]
@candicegjing You know why bundles would stop at the staging stage? (e.g., date would go into staging and never move on)
