### ISSUE TITLE
Bundles taking a long time to run

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1494]

**Comment by yipenghe** [comment]
Can you provide a bit more details on this one (ie. which bundle (uuid) you are trying to run)

**Comment by percyliang** [comment]
Everything is slow right now.  Just try running anything.  It doesn't
happen locally on dev and it doesn't seem like prod is getting overloaded
so not sure what's happening.  You could try attaching a lot of workers to
the Dev server and see if you can reproduce the slowness.

**Comment by yipenghe** [comment]
I think it's running in reasonable time after restarting the servers for deployment, closing for now
