### ISSUE TITLE
Worksheets interface fetches data twice

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#151]
> Another reason why CodaLab is slow is when loading worksheets for some reason it actually calls /rest/api/worksheets/0x..../ twice. For a large worksheet it takes 1.5 seconds per each call or 3 seconds total. That sounds suboptimal. @klopyrev

**Comment by kashizui** [comment]
@ChengshuLi would you be interested in taking a look at this?

**Comment by ChengshuLi** [comment]
Yeah I will have a look! @kashizui

**Comment by ChengshuLi** [comment]
fixed #158
