### ISSUE TITLE
more options in New Run button

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#152]
Have an 'advanced' link that shows the following things:
- Allow users to specify the docker image (textbox with autocomplete).
- Allow people to specify the queue (e.g., jag).
- Allow people to specify a name.

Also allow people to paste in long commands.

**Comment by maxwang7** [comment]
This sounds cool! @percyliang Is this issue at design doc or implementation stage?

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1071
