### ISSUE TITLE
time used 161d20h but only registered a month

### ISSUE THREAD

**Issue by SUMMER1234** [codalab/codalab-worksheets#1533]
Date Joined (UTC)
Sun Sep 15 14:49:30 2019
Time Quota
60d0h
Time Used
161d20h

**Comment by candicegjing** [comment]
Could you provide your username/user id? We will investigate this.

**Comment by newstyn** [comment]
Hi @candicegjing. First of all am sorry i am interupting in this post but its kind of urgent and i need help.  i am also having an issue of this sort but a little bit different. I have already posted the issue but i didnt received any solution in this regard "UsageError: Out of time quota: 7d20h / 7d0h (112.3%) #1542". Can you help me out with the error. My username is newstyn

**Comment by yipenghe** [comment]
> Hi @candicegjing. First of all am sorry i am interupting in this post but its kind of urgent and i need help. i am also having an issue of this sort but a little bit different. I have already posted the issue but i didnt received any solution in this regard "UsageError: Out of time quota: 7d20h / 7d0h (112.3%) #1542". Can you help me out with the error. My username is newstyn

Sorry about this, I just checked your time quota and it was increased already so you should be able to run on codalab

**Comment by yipenghe** [comment]
Commenting to mark solved by #1542 , leaving this issue open for reminding to investigate this time issue.

**Comment by epicfaace** [comment]
Job time quota should only count the amount of time running the job:
- Do not count the amount of time taken in staged
- Do not count the amount of time taken to download / setup docker and dependencies
