### ISSUE TITLE
UsageError: Out of time quota: 7d20h / 7d0h (112.3%)

### ISSUE THREAD

**Issue by newstyn** [codalab/codalab-worksheets#1542]
**Out of time Quota Error**
Hi, I am trying to upload a file on my worksheet newstyn-nli and when i run the upload command it gives me the error of out of time quota. I have searched for the same issue and the solution written there was to report the issue to author and he will fix it. I guess i gave to just mention Percy Liang @percyliang here and he will help me. Following is my information here.

**Codalab Information**
- *newstyn*:
- *0xf7461e1d1a854069ace505271603c1d4*:
- *UUID of problem bundle (please don't delete)*:
- *UsageError: Out of time quota: 7d20h / 7d0h (112.3%)*:
 - *Windows8.1*:
 - *Codalab CLI Version 0.4.5*:

**Comment by candicegjing** [comment]
@newstyn Just to confirm with you that is newstyn your username?

**Comment by candicegjing** [comment]
@newstyn I saw your comment in another post. Your time quota is fixed now. Please check and let me know if you need any further assistance.

**Comment by newstyn** [comment]
@candicegjing Thank you so much. You have been an helping angel. I can start my project now because of you. Thousands thanks for your help

**Comment by yipenghe** [comment]
Seems fixed, closing^ ^happy coding!
