### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1555]
In production, here is an error caused by parsing json request:
```
2019-10-22 06:27:37,454 Error on request by anirudhjoshi(0x6356681d24354575be684ed5c7cd27ad):

POST /workers/deep23.stanford.edu(32138)/checkin

Query params:


Form params:


JSON body:
{
    "cpus": 8,
    "dependencies": [],
    "free_disk_bytes": 90595884269568,
    "gpus": 4,
    "hostname": "deep23.stanford.edu",
    "memory_bytes": 135170699264,
    "runs": [],
    "tag": null
}

Local variables:
socket_id=11063724
WAIT_TIME_SECS=3.0
worker_id='deep23.stanford.edu(32138)'

Traceback (most recent call last):
  File "/opt/codalab-worksheets/codalab/server/rest_server.py", line 106, in wrapper
    return callback(*args, **kwargs)
  File "/usr/local/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/opt/codalab-worksheets/codalab/server/json_api_plugin.py", line 18, in wrapper
    result = callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/server/authenticated_plugin.py", line 72, in wrapper
    return callback(*args, **kwargs)
  File "/opt/codalab-worksheets/codalab/rest/workers.py", line 40, in checkin
    for uuid, run in request.json["runs"].items():
AttributeError: 'list' object has no attribute 'items'
```

**Comment by bkgoksel** [comment]
This looks like a version mismatch between worker and server. 
Current master server loops over `runs` as a list and so does the current worker(sends it as a list)

Here it seems the worker is using a more recent version than the server.

**Comment by candicegjing** [comment]
I checked both prod server and worker, they are all using 0.4.5.

**Comment by bkgoksel** [comment]
The 4.5 worker reports its runs as a dict, not a list [(as sent by the local run manager)](https://github.com/codalab/codalab-worksheets/blob/a84760c601b8e68d6c3c7b4a889054bbb190a1ba/codalab/worker/local_run/local_run_manager.py#L335)

Since this worker looks like someone's personal worker on deep23.stanford.edu and not a prod worker, I'm suspecting they're running it off of 4.6 or master or something.

**Comment by candicegjing** [comment]
I think he must have started his personal worker using the latest code, but we actually haven't deployed the new code to production yet, which caused the error.
