### ISSUE TITLE
New Run button doesn't work correctly with Edit Source

### ISSUE THREAD

**Issue by klopyrev** [codalab/codalab-worksheets#156]
On the website if you click the "Edit Source" button and reorder bundles, the "New Run" button starts behaving incorrectly. Specifically, it displays the wrong file contents for the bundles.

@ChengshuLi take a look

**Comment by kashizui** [comment]
@ChengshuLi was this fixed by #169 ?

**Comment by ChengshuLi** [comment]
@kashizui Yes it was.
