### ISSUE TITLE
[USER ISSUE] "UsageError: Out of time quota" for stevezheng23

### ISSUE THREAD

**Issue by stevezheng23** [codalab/codalab-worksheets#1570]
Hi Team,

I have been facing "UsageError: Out of time quota" issue for my account stevezheng23, could you help?

Best,
Steve

**Comment by stevezheng23** [comment]
@candicegjing , could you help take a look? Here is the detail error message `UsageError: Out of time quota: 9d17h / 7d0h (139.3%)`

**Comment by stevezheng23** [comment]
@candicegjing my username is `stevezheng23`, thanks

**Comment by epicfaace** [comment]
@stevezheng23 I've doubled your time quota from 7d to 14d. Hope that helps!

**Comment by stevezheng23** [comment]
Thanks, @epicfaace ! It works now
