### ISSUE TITLE
[USER ISSUE] Cant delete bundles that I own

### ISSUE THREAD

**Issue by ajoshi80** [codalab/codalab-worksheets#1575]
**Describe the bug**

**Codalab Information**
- *Your username*:anirudhjoshi
- *UUID of worksheet where problem occurred*:
- *UUID of problem bundle (please don't delete)*:0x76cf45e5031f4290a3af0a6f84b105c5
- *Error message received from Codalab (if applicable)*:User anirudhjoshi does not have sufficient permissions on bundle 0x371c93891bcf403eb45d029a509f4440 (have none, need all).

 - *OS (if on CLI)*:macOS
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by epicfaace** [comment]
It doesn't look like either of the bundle uuids you posted correspond to bundles that exist (https://worksheets.codalab.org/bundles/0x76cf45e5031f4290a3af0a6f84b105c5, https://worksheets.codalab.org/bundles/0x371c93891bcf403eb45d029a509f4440). Did you already delete them?

**Comment by ajoshi80** [comment]
I don't believe so but I thought it was strange it was showing me this given that all I did was list the bundles that I have created on my worksheet and a cl rm command on those uids

**Comment by percyliang** [comment]
That's strange.  Closing for now.  Please repost if you can identify a specific bundle that exists that belongs to you and you can't delete.
