### ISSUE TITLE
[USER ISSUE] Can't delete bundles from web UI

### ISSUE THREAD

**Issue by ajoshi80** [codalab/codalab-worksheets#1576]
**Describe the bug**

**Codalab Information**
- *Your username*:anirudhjoshi
- *UUID of worksheet where problem occurred*: 0x54786f8d5b114abfb09b578042119608
- *UUID of problem bundle (please don't delete)*: 0xbe540952040f4b93bd0e5ea9295cc1a4
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*; Safari

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by epicfaace** [comment]
What error do you get when trying to delete it?

**Comment by ajoshi80** [comment]
No error. It just doesn't delete it.

**Comment by yipenghe** [comment]
> No error. It just doesn't delete it.

So from web UI, are you right clicking to get the menu and then choose 'remove bundle permanently'? Or are you using the terminal on Web UI to run 'rm [bundle uuid]' (possibly with --force)?

**Comment by ajoshi80** [comment]
Yes right clicking to remove bundle.

**Comment by yipenghe** [comment]
> Yes right clicking to remove bundle.

I think having dependencies or attached to multiple worksheets can cause delete failing. Try running the 'rm [bundle uuid' command on the web cli and it should print the error out. You can add '--force' flag to delete the bundle regardless of the constraints
