### ISSUE TITLE
Don't push docker images on Travis PR builds

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1581]
@yipenghe 's PR was somehow run with a tag of "frontend" instead of the correct tag for his PR branch. 

push (ran properly with branch `f-web-bulk`): https://travis-ci.org/codalab/codalab-worksheets/builds/604882894?utm_source=github_status&utm_medium=notification
PR (issue because branch is `frontend`): https://travis-ci.org/codalab/codalab-worksheets/builds/604883403?utm_source=github_status&utm_medium=notification

Solution: don't push docker images on Travis PR builds

**Comment by epicfaace** [comment]
Fix is here: https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/

**Comment by Levilian** [comment]
@epicfaace what's the status of this issue?
