### ISSUE TITLE
[USER ISSUE] I have "UsageError: Out of time quota: 259d9h / 60d0h (432.4%)"

### ISSUE THREAD

**Issue by parkce** [codalab/codalab-worksheets#1583]
**Describe the bug**
I have "UsageError: Out of time quota: 259d9h / 60d0h (432.4%)"
How can I solve it ?? 

**Codalab Information**
- *Your username*: parkce.tpu
- *UUID of worksheet where problem occurred*: 0xc573c2
- *UUID of problem bundle (please don't delete)*: 0x99c108
- *Error message received from Codalab (if applicable)*: UsageError: Out of time quota: 259d9h / 60d0h (432.4%)
 - *OS (if on CLI)*: 
 - *Codalab CLI Version (if on CLI)*:  0.4.6
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yipenghe** [comment]
Hi sorry about this, I think we have a issue related to time quota, I increased your time quota and your job should be able to go through. 
Do you mind sharing what actions you performed to help us fix it?

**Comment by yipenghe** [comment]
Closing, feel free to reopen if you encounter any more issue
