### ISSUE TITLE
Cleanup bundles that were assigned to a private worker which does not exist anymore.

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1584]
Currently, if there are bundles staying in `staged` state but were assigned to a private worker that doesn't exist anymore in the system, we don't do any operation to those bundles. If we don't do anything to those bundles, they will be included in the scheduling loop and nothing happens to them. Questions is that should we remove all those bundles that have private workers removed? Or reassigned them to one of the public workers.

**Comment by percyliang** [comment]
Private workers can come back, so we shouldn't delete anything immediately.  Do we need to do anything?  Just make sure users can kill / remove the bundle if the private worker goes away (but this should be the same for public workers too).
