### ISSUE TITLE
Performance bottleneck study on bundle_manager.py

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1589]
Some stats of running `bunlde_manager.py`.
Calling stack: 
1. `_run_iteration()`
    1. `_stage_bundles()`
    1. `_make_bundles()`
    1. `_schedule_run_bundles()`
          1. `_cleanup_dead_workers()`
          1. `_restage_stuck_starting_bundles()`
          1. `_bring_offline_stuck_running_bundles()`
          1. `_fail_on_too_many_resources()`
          1. `_acknowledge_recently_finished_bundles()`
          1. `_schedule_run_bundles_on_workers()`
    1. `_fail_unresponsive_bundles()`

The following table shows the performance stats that I collected from both production env and stanging env using roughly around 80 `created` bundles and 100 `staged` bundles. For stats collected in column (1), unlike the bundles in production, those bundles that I created in staging env don't have any dependencies. Time is measured in seconds.

| **Function Calls**                        | **Production**        |    **(1) Staging (Dev DB)**          |  **(2) Staging (Prod DB 11/04/2019)** |
|-------------------------------| ---------------- | ---------------------- | ---------------------- |
| _stage_bundles()                          | 4.893916368484497     |  0.007596492767333984   | 0.954134464263916 |
| _make_bundles()                           | 0.014322280883789062  |  0.00735783576965332    | 0.007351398468017578 | 
| _schedule_run_bundles()                   | 411.18663215637207    |  6.098901033401489      | 267.14445996284485 |
| _fail_unresponsive_bundles()              | 0.11637234687805176   |  0.07699465751647949    | 0.08106207847595215 |
| In _schedule_run_bundles() | | | |
| _cleanup_dead_workers()                   | 3.790855407714844e-05 |  6.67572021484375e-06   | 1.5974044799804688e-05 | 
| _restage_stuck_starting_bundles()         | 0.006481170654296875  |  0.0030193328857421875  | 0.003535747528076172  | 
| _bring_offline_stuck_running_bundles()    | 0.026740312576293945  |  0.006380558013916016   | 0.00631403923034668 | 
| _fail_on_too_many_resource()              | 299.062668800354      |  2.5921273231506348     | 129.30349040031433 |
| _acknowledge_recently_finished_bundles()  | 0.006404876708984375  |  0.003915309906005859   | 0.35086989402770996 |
| In _fail_on_too_many_resource() | |  | |
| fetch ~100 staged bundles                 |  0.06424236297607422    |  0.03273320198059082  | 0.05053114891052246 | 
| bundle_resources takes                    | 1.5082993507385254    |  0.012859582901000977   |  1.2910022735595703  |
| disk quota check takes                    | 1.4577548503875732    |  0.025880813598632812   |  1.2419383525848389  |
| time quota check takes                    | 0.008216142654418945  |  0.003352642059326172   | 0.003879547119140625 |
| memory quota check takes                  | 4.291534423828125e-06 |  3.0994415283203125e-06 | 3.337860107421875e-06 |

Those stats were collected using around 100 staged bundles. As we can see from the above data, `_schedule_run_bundles()` takes 99% of the time running each iteration. Within `_schedule_run_bundles()`, `_fail_on_too_many_resource()` takes around 70% of the total time. In `_fail_on_too_many_resource()`, getting `bundle_resource` and checking `disk_quota_left` takes most of the time.

Looking at where `bundle_resource` and `disk_quota_left` got calculated, both of them called function [get_user_disk_quota_left()](https://github.com/codalab/codalab-worksheets/blob/master/codalab/model/bundle_model.py#L2266-L2270), it seems that it makes two function calls as follows:
1. [get_user_info()](https://github.com/codalab/codalab-worksheets/blob/b5cbabe9839c994c0f31dcab06229401612b8843/codalab/model/bundle_model.py#L2183) to generate `disk_quota`.
2. [_get_disk_used()](https://github.com/codalab/codalab-worksheets/blob/b5cbabe9839c994c0f31dcab06229401612b8843/codalab/model/bundle_model.py#L2258) to generate `disk_used`.

Questions:
1. Checking at `user` table, it seems that for each user, it contains both `disk_quota` and `disk_used`. Could we directly use these two fields from `user` table to calculate `disk_quota_left` for each bundle instead of calling `_get_disk_used()`? 
2. The above data also explained why bundles take a long time to move from `created` to `staged`, as `_stage_bundles()` will be blocked by the rest of the three functions and all of them together takes around 6 minutes. Should we make `_stage_bundles()` non-blocking then? Maybe a message queue system (e.g. Redis) would be something to consider?

**Comment by bkgoksel** [comment]
Great find! I think (1) is very low hanging fruit here. As you said we can just replace the `_get_disk_used` call with `user_info[disk_used]` and that will probably get us all the gains here.

(2) probably won't be necessary once (1) is done since nothing else seems to take as much time as this.

**Comment by candicegjing** [comment]
@bkgoksel The `user_info[disk_used]` seems to be a rounded value against using `_get_disk_used()`. I am not sure if we want to consider that as well. But I guess compared with the performance improvement we get, it's probably trivial.

**Comment by candicegjing** [comment]
Given the fact that `_schedule_run_bundles()` always takes the majority of time to process and blocks `_stage_bundles()` to keep moving bundles from `created` to `staged`, it will be better to make `_stage_bundles()` as a non-blocking function.
