### ISSUE TITLE
Worker managers started from `codalab_service` with the rest of the Codalab service crash

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1594]
When starting the `codalab_service` from scratch, the rest server is not responsive by the time the worker manager containers start, so the worker managers just crash immediately as they can't check in with the server.

The current workaround is to start them later with `codalab-service start -s worker-manager-cpu worker-manager-gpu` but we should have logic that just has them wait for rest server or retrying to log in for some time before crashing.

**Comment by percyliang** [comment]
Goal is to move worker manager out of codalab_service.py anyway.
