### ISSUE TITLE
[USER ISSUE]  Disk Issues with Model Submission

### ISSUE THREAD

**Issue by dabin0616** [codalab/codalab-worksheets#1598]
**Describe the bug**
I had run out of capacity for two accounts.

So I filled out two forms and submitted them.

However, one of the two 10Gbyte is 20, the following error occurs.(ID is 'ICL2019')

   "Out of disk quota: 7.2g / 20 (38579300000.0%)"

And the rest of me hasn't changed at all.(ID is 'icl_check')

The IDs of the two accounts are 'icl_check' and 'ICL2019'.

I know you're busy with other things, but I'd be so grateful if you could take care of this quickly.

I look forward to your prompt reply.
**Codalab Information**
- *Your username*: icl_check, ICL2019
- *UUID of worksheet where problem occurred*:
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by candicegjing** [comment]
@dabin0616 Could you provide the uuid of your worksheet?

**Comment by Levilian** [comment]
@dabin0616 Can you double check now? We just increased your quota request and the issue should be fixed.
