### ISSUE TITLE
Inconsistency between raw edit and cl upload

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#16]
<a href="https://github.com/tonyyyang"><img src="https://avatars.githubusercontent.com/u/6948032?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tonyyyang](https://github.com/tonyyyang)**
_Tuesday Sep 15, 2015 at 02:53 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1270_

---

The following procedure may cause bundle without host worksheet
1. On website, you enter raw edit mode.
2. In command line, you upload a bundle. If you `cl ls` at this moment, you can see the bundle is successfully uploaded and appears at the bundle list.
3. You switch back to view mode. After updating according to plaintext in raw edit, the just-uploaded bundle is missing.

This inconsistency may cause bundle without host worksheet.

Reference bundle: https://www.codalab.org/bundles/0x8d63b4b6feb3433cae5b152623fa64e5/
Sidenote: `cl wedit` does not have this problem.

**Comment by kashizui** [comment]
Fixed by #308
