### ISSUE TITLE
Can't build branch with dashes in its name

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1600]
for example, see #1406

we get:

```
invalid argument "codalab/server:dependabot/pip/marshmallow-2.15.1" for "-t, --tag" flag: invalid reference format
```

https://travis-ci.org/codalab/codalab-worksheets/jobs/587031673?utm_medium=notification&utm_source=github_status

**Comment by bkgoksel** [comment]
Recently one of the travis builds for one of my PRs where the branch name had a `/` in it failed. Do we need to do something similar for that as well?

**Comment by epicfaace** [comment]
> Recently one of the travis builds for one of my PRs where the branch name had a `/` in it failed. Do we need to do something similar for that as well?

That was already fixed in another PR, I believe, so you should just rebase.
