### ISSUE TITLE
allow users to specify packages, automatically build docker images

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#161]
CodaLab should maintain a list of docker images that are built on behalf of users, so that people don't need an account on dockerhub to start doing stuff.

User should be able to type a sequence of commands (assume we can execute them in any order):

```
pip install ...
apt-get install ...
```

and have docker images that are automatically built for them.

**Comment by percyliang** [comment]
This will introduce a lot of complexity into the system.

**Comment by percyliang** [comment]
Suggestion: piggyback off of existing framework.

    cl run 'pip install' --save # outputs the docker image ID (augment)

It would be nice to have the Dockerfile to have a more declarative specification of what's inside the image.

**Comment by percyliang** [comment]
Need to be able to run as root.

**Comment by percyliang** [comment]
@fabeschan can we retarget this issue to what you're building?

What's missing still is a nice way to record the commands...

**Comment by fabeschan** [comment]
Yup, sure can. I'll look into command recording too.

**Comment by kashizui** [comment]
Addressed by #666
