### ISSUE TITLE
worksheet header icons - use icons with hover

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1618]
- use icons with hover instead of text
- when bundles are selected, hide the "cell/upload/run" icons
- make sure icons with hover are there for each worksheet item

**Comment by yipenghe** [comment]
- use icons with hover instead of text (With hiding I don't think this is necessary, let me know otherwise)
- when bundles are selected, hide the "cell/upload/run" icons (done)
- make sure icons with hover are there for each worksheet item (has text now, but let me know if we just want icons still)
