### ISSUE TITLE
Kill a bundle when selecting it and pressing "k"

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1620]

**Comment by yipenghe** [comment]
I'm mapping kill to 'v', 'k' is already mapped to move up and it will cause a lot of confusing scenarios to map it to kill as well

**Comment by percyliang** [comment]
We could also make all the bundle actions two key shortcuts (in gmail, like 'g i', 'g a').  So we do 'a k' for kill, 'a r' for delete, etc.
