### ISSUE TITLE
[USER ISSUE] Disk Issues with Model Submission

### ISSUE THREAD

**Issue by suda0221** [codalab/codalab-worksheets#1622]
**Describe the bug**

I want to submit a SQuAD model.

But the model is so big that it's hard to go through the last step.

model size: 6.5 Gbyte
disk capacity required by the dev set the final evaluation stage: 4 Gbyte

Can you increase capacity?

**Codalab Information**
- *Your username*: ICLICL
- *UUID of worksheet where problem occurred*:
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yipenghe** [comment]
Hi, please fill out this disk request form https://docs.google.com/forms/d/e/1FAIpQLSdS22MaLyE1kx0JL-w2a8f8IasDyc36H_ZuidNBVAE_afMCpw/viewform, thanks

**Comment by suda0221** [comment]
I have submitted a form. Please check.

**Comment by yipenghe** [comment]
> I have submitted a form. Please check.

I have increased your disk quota, should be able to go through now

**Comment by suda0221** [comment]
Thank you.
