### ISSUE TITLE
[USER ISSUE] "Create Run Bundle" modal UI issue when many dependencies are specified

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1624]
**Describe the bug**
Specifying a bunch of run bundle dependencies causes text to spill out of "Create Run Bundle" modal (seen screenshot for more detail).

**Codalab Information**
 - *Browser (if on Web)*: Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Go to 'My Home'
2. Click on 'New Run'
3. Add a bunch of Run Bundles as dependencies.
4. Text will spill out of Modal

**Expected behavior**
I would expect the modal or the command line box to be scrollable.

**Screenshots**
![modal bug](https://user-images.githubusercontent.com/16793796/68456307-4ca66080-01b2-11ea-9bbd-57b4d766d690.png)

**Comment by percyliang** [comment]
This is the old frontend which will disappear soon anyway.
