### ISSUE TITLE
 Requested more GPUs

### ISSUE THREAD

**Issue by Gabriellamin** [codalab/codalab-worksheets#1634]
I request 1 gpu but encounter a problem that 'Cannot assign enough resources: Requested more GPUs (1) than available (0 currently out of 1 on the machine)'.Is there any GPU?Would you like to tell me how to solve the problem?

**Comment by candicegjing** [comment]
@Gabriellamin Could you provide us with the link of your bundle that causes this problem?

**Comment by Gabriellamin** [comment]
Thanks for your reply. I Have tried again And the problem disappears.------------------ 原始邮件 ------------------
发件人: "Jing Ge"<notifications@github.com>
发送时间: 2019年11月13日(星期三) 凌晨2:00
收件人: "codalab/codalab-worksheets"<codalab-worksheets@noreply.github.com>;
抄送: "Gabriellamin"<308034429@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [codalab/codalab-worksheets]  Requested more GPUs (#1634)



@Gabriellamin Could you provide us with the link of your bundle that causes this problem?
 
&mdash;
