### ISSUE TITLE
ctrl+r should not trigger new run

### ISSUE THREAD

**Issue by yipenghe** [codalab/codalab-worksheets#1635]

**Comment by yipenghe** [comment]
Later in our discussion, I think the solution was to just use some combined keys for new run, something like 'a+r', so it no longer triggers a new run when the hard refresh

**Comment by Levilian** [comment]
> Later in our discussion, I think the solution was to just use some combined keys for new run, something like 'a+r', so it no longer triggers a new run when the hard refresh

Thanks so much Yipeng for the update!!

**Comment by Levilian** [comment]
#1649
