### ISSUE TITLE
Autocomplete docker image doesn't work

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#164]

**Comment by yashsavani** [comment]
@percyliang Can you try using the Autocomplete with a space instead of an equals. eg. `cl run --request-docker-image code`<tab><tab>

**Comment by percyliang** [comment]
Yes, you can try, but it doesn't work.

**Comment by kashizui** [comment]
We were looking at this together just now, and it looked like it worked for
us earlier, i'll try again too on my own computer later.
