### ISSUE TITLE
Add a script that creates tiny and giant worksheet from scratch (stress test front end rendering)

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1641]
Let us create a big worksheet that tries to exercise all the worksheet rendering logic (math, markdown, bundles, subworksheets, search directives, comments, invalid directives), bundles with invalid permissions, Unicode, etc.

**Comment by teetone** [comment]
Tiny Worksheet: 
https://worksheets-dev.codalab.org/worksheets/0x3b4d0d28aa324f13b196d401482deaa8

Giant Worksheet: 
https://worksheets-dev.codalab.org/worksheets/0x273a28662647406391f8f6e76a5c4121

**Comment by percyliang** [comment]
We should have two worksheets:
1) One that exercises all the functionality (code paths) but is as minimal as possible and fast to load.
2) Several large worksheets that have a large number of bundles, custom schemas that read from large files, etc. to exercise the performance aspect.
the current bundle kind of tries to do both...

**Comment by teetone** [comment]
@percyliang I copied over the tiny worksheet's source from my local to the dev environment as well. I forgot to include the link on this issue.

Tiny Worksheet: https://worksheets-dev.codalab.org/worksheets/0x3b4d0d28aa324f13b196d401482deaa8

Do you think this is sufficient? I think testing large files can be addressed in #1347 since it's stress testing the backend more.

**Comment by percyliang** [comment]
This tiny worksheet should exercise more features - like invalid bundle references, references to private bundles, other searches, table schemas, etc.  Basically look at `worksheet_util.py` and exercise all the functionality.

There should still be another worksheet for stress testing large worksheets (still frontend) - that's different from stress testing the backend.

**Comment by percyliang** [comment]
Add a script that creates these worksheets and uploads the relevant bundles.
