### ISSUE TITLE
[New Frontend] Images aren't displaying properly

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1654]
The image in [0xc86d3ebe69a3427d91f9aaa63f7d1e7d](https://worksheets-dev.codalab.org/worksheets/0xc86d3ebe69a3427d91f9aaa63f7d1e7d), isn't displaying properly.

**Comment by yipenghe** [comment]
I think the files in these bundles are lost....
see newly uploaded image https://worksheets-dev.codalab.org/worksheets/0x0863ee7909bf46b2b82d448e5e7f090c

**Comment by percyliang** [comment]
Missing data.
