### ISSUE TITLE
[New Frontend] Numbers in tables are missing.

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1655]
Please check out the following example. Scores are missing on the columns of **[Exact, F1, AdvExact, AdvF1]** 
![image](https://user-images.githubusercontent.com/1483372/68786371-86cd9300-05f4-11ea-8cdc-adc8f0a09a77.png)

**Comment by yipenghe** [comment]
I think these missing things related to bundles are acting weird because the file inside these bundles are lost..

**Comment by percyliang** [comment]
Missing data.
