### ISSUE TITLE
[New Frontend] Big empty space when expanding "files"

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1656]
Please check the following image out. When expanding "files", there is a large empty space, which seems to be a bug.
![image(1)](https://user-images.githubusercontent.com/1483372/68786640-fc396380-05f4-11ea-8fee-98ec2e4e051f.png)

**Comment by yipenghe** [comment]
If you open bundle details, there is no files/stdout/stderror for this bundle, so nothing to display, I should probably show a message or something

**Comment by yipenghe** [comment]
Not really a problem..
