### ISSUE TITLE
Spacebar doesn't work on web terminal

### ISSUE THREAD

**Issue by tummykung** [codalab/codalab-worksheets#166]
- cannot type spacebars (but I can get around by pressing a sequence of tabs and spacebars...)
- cannot paste

Browsers: Chrome, Firefox

**Comment by kashizui** [comment]
@tummykung What operating system are you using?

We've fixed the copy-paste issue in the development branch, which we'll be deploying soon. However I cannot reproduce your spacebar bug, could you describe that in more detail?

**Comment by tummykung** [comment]
Mac OS X El Capitan. The spacebar bug is that when I press spacebar it doesn't have any effects.

**Comment by ChengshuLi** [comment]
@kashizui Do you have Mac OS X EL Capitan? I am still using Yosemite. I can upgrade and test it if needed.

**Comment by kashizui** [comment]
I am on El Capitan using Chrome `Version 50.0.2661.94 (64-bit)` and Firefox `45.0.1` and my spacebar works fine in the web terminal.

**Comment by kashizui** [comment]
@tummykung I'm afraid we're going to have to assume that this issue is on your end until we can figure out a way to reproduce it.

**Comment by tummykung** [comment]
My chrome is Version 50.0.2661.102 (64-bit). Actually, I found out why (partly). It was due to an interaction with a Chrome extension called SmoothScroll (https://chrome.google.com/webstore/detail/smoothscroll/nbokbjkabcmbfdlbddjidfmibcpneigj). After I disable this extension, I can type spacebar fine. It's weird. Sorry for a false negative! Still curious to know why that interaction happened though.

**Comment by kashizui** [comment]
We use the [jquery.terminal plugin](http://terminal.jcubic.pl/), which uses some (arguably horrendous) DOM-hacking to emulate a fancy shell. There are probably a lot of ways this could cause problems with your Chrome extension.. 
We don't really have an alternative, so I'm afraid you're just going to have to disable it when using CodaLab :( Sorry!
