### ISSUE TITLE
[New frontend] Shortcut '?' is broken

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1670]
The shortcut '?' is broken saying
`TypeError: jquery__WEBPACK_IMPORTED_MODULE_8___default(...)(...).modal is not a function
`
_Originally posted by @yipenghe in https://github.com/codalab/codalab-worksheets/pull/1653_

**Comment by yipenghe** [comment]
Some more info: If you checkout to this commint: (1389ae6967e3032694a514adf8358ab4ab4aed5e) of #frontend branch and rebuild with -bd flag, the shortcut works fine, checking out to the fix path commit the shortcuts fails, I think there's still some bugs to fix for the CSS refactor

**Comment by epicfaace** [comment]
I'm working on removing jquery from this in the first place, PR upcoming

**Comment by yipenghe** [comment]
This is fixed
