### ISSUE TITLE
keyboard shortcut for Rerun

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1684]
Currently have to open the bundle details and click 'Rerun'.  Should be able to trigger this from the keyboard with 'a a' (in contrast to 'a r' for creating a run).

Furthermore, when the new run box pops up, the cursor should be at the end of the command-line, not the beginning.

The 'Rerun' button should perhaps say something like 'Edit and Rerun' to emphasize that you can make modifications.

**Comment by Levilian** [comment]
- [x] Trigger Rerun from the keyboard with 'a a' (in contrast to 'a r' for creating a run).

- [x] When the new run box pops up, the cursor should be at the end of the command-line, not the beginning.

- [x] The 'Rerun' button should say something like 'Edit and Rerun' to emphasize that you can make modifications.
