### ISSUE TITLE
fix argument parsing

### ISSUE THREAD

**Issue by tachim** [codalab/codalab-worksheets#17]
tudor@tudor-258:~/prediction$ cl run runner:runner lib:lib -t "python run_experiment.py ds/ner-conll2003-eng-tag/train ds/ner-conll2003-eng-tag/dev FINerProblem"

fails whereas

tudor@tudor-258:~/prediction$ cl run runner:runner lib:lib "python run_experiment.py ds/ner-conll2003-eng-tag/train ds/ner-conll2003-eng-tag/dev FINerProblem" -t

succeeds. Looks like the -t argument isn't declared correctly.

**Comment by percyliang** [comment]
The dependencies must be specified next to the command.
