### ISSUE TITLE
[Bundle Manager] Improve the way of resource checking in _fail_on_too_many_resources()

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1706]
_fail_on_too_many_resources() function currently checks for resources failure multiple times in different aspects(e.g. memory, disk quota, user quota) for a single bundle. To make the bundle manager run faster, the logic could be changed to as long as one check failed, we fail the bundle right away.

**Comment by percyliang** [comment]
This doesn't seem like it's an efficiency bottleneck.

**Comment by yipenghe** [comment]
The PR indicates we are keeping it as is, closing
