### ISSUE TITLE
[New Frontend] Error: Please provide worksheet uuid. Request for a better 404 page.

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1708]
**Describe the bug**
When going to https://worksheets-dev.codalab.org/worksheets, you will run into this following unexpected error screen. A user reported this issue when he was logged in, but I just reproduced it without logging in.

![worksheets](https://user-images.githubusercontent.com/16793796/69402738-9b252600-0cad-11ea-85dd-ec7fac5a68a5.png)

**Codalab Information**
- Environment: Dev
- Browser: Chrome

**Expected behavior**
We should show a 404 invalid url error page instead since it is indeed an invalid url. We also should show a better 404 page instead of the current one (see below).

Current:
![Screen Shot 2019-11-21 at 10 30 43 PM](https://user-images.githubusercontent.com/16793796/69403097-93b24c80-0cae-11ea-9ecf-0284315fa1e6.png)

**Comment by yipenghe** [comment]
I think this is a redirection issue, we should redirect to the dashboard worksheet, good catch
