### ISSUE TITLE
[New Frontend] Shortcut `i` does not work to add a cell below

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1709]
**Describe the bug**
Shortcut `i` key press event is ignored for the new front end. It should "add a cell right below the current focus".

**Codalab Information**
-Browser: Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Go to a worksheet.
2. Focus on a table cell.
3. Press `i`.

**Expected behavior**
Event should be handled as expected.

**Comment by percyliang** [comment]
Don't 'a t', 'a u', 'a r' cover it for creating text, upload and run bundles?

**Comment by yipenghe** [comment]
> Don't 'a t', 'a u', 'a r' cover it for creating text, upload and run bundles?

It might be just the keyboard shortcut help haven't been updated, I will double check

**Comment by yipenghe** [comment]
Yeh this is just the help haven't been updated, closing
