### ISSUE TITLE
[New Frontend] Double Clicking Save prompts the user to delete the worksheet

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1722]
**Describe the bug**
Double clicking the save button after editing the source will prompt the user to delete the worksheet.

**Codalab Information**
- Browser: Chrome
- Reproducible on any worksheet

**To Reproduce**
Steps to reproduce the behavior :
1. Go to any worksheet
2. Edit the source
3. Double click save quickly causing the delete button to get clicked.

**Expected behavior**
It should save the worksheet, then render the delete button.

**Comment by yipenghe** [comment]
It's because on the second click you would be clicking on the delete button. After I moved the delete button position, this shouldn't a problem anymore, you will click on show/hide terminal instead....but since you actually clicked on the button, I think the behaviour is correct in this sense
