### ISSUE TITLE
[New Frontend] "Typesetting math: 100%" just flashes even though typesetting is still in progress

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1723]
**Describe the bug**
While a worksheet is typesetting, the user just sees "Typesetting math: 100%" message, even though the typesetting is still progress.

**Codalab Information**
- Browser: Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Open any worksheet with some math functions. 
2. Should see a message that the typesetting has completed, even though it hasn't.

**Expected behavior**
Show the correct progress percentage.

![flashes_this__while_processing](https://user-images.githubusercontent.com/16793796/69419786-0c76d000-0cd2-11ea-9c46-298a75eb7654.png)

**Comment by yipenghe** [comment]
I think this progress refers to individual boxes' typesetting, I agree it would be better if we could have one typesetting progress

**Comment by percyliang** [comment]
Doesn't seem to be an issue anymore.
