### ISSUE TITLE
[New Frontend] HTML not respected in Worksheets

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1724]
**To Reproduce**
Steps to reproduce the behavior :
1. Go to any Worksheet.
2. Add some HTML
3. See that it does not render and gets spit out as plain text.

**Expected behavior**
HTML should be respected in Worksheets as it is markup too.

![html_not_respected](https://user-images.githubusercontent.com/16793796/69420090-d84fdf00-0cd2-11ea-836b-f0f40985f2b7.png)

**Comment by percyliang** [comment]
We actually don't want to render arbitrary HTML for security reasons.

**Comment by teetone** [comment]
@percyliang I will close this issue then.
