### ISSUE TITLE
[New Frontend] When editing a Worksheet on a larger screen, there is a lot of wasted space

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1728]
1. Edit a worksheet on a larger screen.
2. Expand the browser window.

**Codalab Information**
- Browser: Chrome

**Expected behavior**
The worksheet editor size should be dynamic with respect to browser window.

**Screenshots**
![wasted_space](https://user-images.githubusercontent.com/16793796/69421987-5ada9d80-0cd7-11ea-9707-9a5c25d8eb93.png)

**Comment by percyliang** [comment]
Add a expand/collapse button in the upper right.

**Comment by percyliang** [comment]
Done.
