### ISSUE TITLE
[New Frontend] Save Indicator is cut off for in-line Worksheet edits

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1729]
**Codalab Information**
 - Browser: Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Go to a Worksheet
2. Edit a line and see the save indicator being cut off.

**Expected behavior**
The indicator should be better styled.

**Screenshots**
![weird_save_button](https://user-images.githubusercontent.com/16793796/69422458-9a55b980-0cd8-11ea-913b-7ed934d9baf0.png)

**Comment by yipenghe** [comment]
The blue area now fills the rectangle part
