### ISSUE TITLE
[New Frontend] Multi-line comments not respected in Worksheets markdown

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1730]
**To Reproduce**
Steps to reproduce the behavior :
1. Go to a worksheet and edit its source.
2. Add a multiline comment and see the comment is not ignored when rendering the worksheet.

**Expected behavior**
Should respect the multiline comment syntax for markdown.

**Screenshots**
![multi-line-comments-not-respected](https://user-images.githubusercontent.com/16793796/69422746-544d2580-0cd9-11ea-8ebe-e3434f052530.png)

**Comment by percyliang** [comment]
We're not supporting this as it's too complicated.
