### ISSUE TITLE
[New Frontend] Hover style for rows in Worksheet tables needs to be improved

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1731]
**Codalab Information**
 - Browser: Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Go to a worksheet with a table.
2. Hover on a row and notice double lines appear.

**Expected behavior**
I think it can be styled better. Perhaps maybe just highlighting the row instead.

**Screenshots**
![table on hover shows double line](https://user-images.githubusercontent.com/16793796/69473669-d5ed9380-0d6b-11ea-8d1d-d7cfbfd9de7b.png)

**Comment by yipenghe** [comment]
This is the styling of gmail and was what we wanted

**Comment by teetone** [comment]
@yipenghe The hover experience in Gmail feels way better to me. The current styling in Codalab seems like a bug to me. Gmail uses a box-shadow on the bottom, which blends in better. Correct me if I'm wrong, but I think our current styling just adds another border when hovering over the row.

**Comment by yipenghe** [comment]
> @yipenghe The hover experience in Gmail feels way better to me. The current styling in Codalab seems like a bug to me. Gmail uses a box-shadow on the bottom, which blends in better. Correct me if I'm wrong, but I think our current styling just adds another border when hovering over the row.

Not really, when you hover, it actually is using box-shadow, copied exactly from gmail's css. The difference might be the border size is 2px on codalab currently. Feel feel to go to BundleRow.js component, and tweak the contentRow style. Maybe changing borderBottom to 1px will be a better experience? Let me know
That is, change 
`        borderBottom: '2px solid #ddd',
`to
` borderBottom: '1px solid #ddd',
`

**Comment by yipenghe** [comment]
I think we all got used to it...let's close it for now :p
