### ISSUE TITLE
[Frontend] Typesetting is slow on larger worksheets

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1732]
**Describe the bug**
Typesetting is very slow on larger worksheets.

Here is one example: https://worksheets-dev.codalab.org/worksheets/0x9ad289ce97614b48b5bd45d912247087

**Expected behavior**
1. I would expect a spinner that shows the progress for typesetting the worksheet and only show the worksheet once the typesetting is complete. It's not a good experience when the screen jumps and math equations suddenly appear here and there.
2. Possibly improve the rendering speed.

**Comment by teetone** [comment]
Sometimes it doesn't even finish for smaller worksheets as well.

**Comment by yipenghe** [comment]
> Sometimes it doesn't even finish for smaller worksheets as well.

@epicfaace  Sounds like the math not render bug a while ago, which was hard to reproduce

**Comment by percyliang** [comment]
Can't reproduce now.
