### ISSUE TITLE
[USER ISSUE] error while uploading

### ISSUE THREAD

**Issue by hhexiy** [codalab/codalab-worksheets#1734]
**Describe the bug**
A job running for a while failed with the message "Error while uploading: 'str' object has no attribute 'decode'". Not sure what the cause is.

**Codalab Information**
- *Your username*: hhe
- *UUID of worksheet where problem occurred*: 0x92f06c37b4034e0b8ff779ea64700d5c
- *UUID of problem bundle (please don't delete)*: 0xd572e8210f3a4611adabfe6d9333c702
- *Error message received from Codalab (if applicable)*: Error while uploading: 'str' object has no attribute 'decode'
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*: Safari

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hhexiy** [comment]
Looks like this is due to insufficient disk quota.

**Comment by yipenghe** [comment]
Fill out this form if you are running out of disk quota https://docs.google.com/forms/d/e/1FAIpQLSdS22MaLyE1kx0JL-w2a8f8IasDyc36H_ZuidNBVAE_afMCpw/viewform
