### ISSUE TITLE
[Bundle Manager] Avoid querying the database for every single bundle when calculating available resources on each worker

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1735]
This ticket is to avoid querying the database for every single bundle when calculating available resources on each worker. As we can see from the following code [_deduct_worker_resources()](https://github.com/codalab/codalab-worksheets/blob/master/codalab/server/bundle_manager.py#L328-L346), for each `uuid`, it checks for bundle's existence by querying the database, which is time-consuming. This ticket is to find an alternative way to improve the performance of the bundle manager overall.
```
    def _deduct_worker_resources(self, workers_list):
        """
        From each worker, subtract resources used by running bundles. Modifies the list.
        """
        for worker in workers_list:
            for uuid in worker['run_uuids']:
                try:
                    bundle = self._model.get_bundle(uuid)
                except NotFoundError:
                    logger.info(
                        'Bundle %s in WorkerInfoAccessor but no longer found. Skipping for resource deduction.',
                        uuid,
                    )
                    continue
                bundle_resources = self._compute_bundle_resources(bundle)
                worker['cpus'] -= bundle_resources.cpus
                worker['gpus'] -= bundle_resources.gpus
                worker['memory_bytes'] -= bundle_resources.memory
        return workers_list
```

**Comment by percyliang** [comment]
Can't we call `batch_get_bundles`?

**Comment by candicegjing** [comment]
> Can't we call `batch_get_bundles`?

I think that's a great idea. I am also looking for ways to completely getting rid of this kind of resource deduction.
