### ISSUE TITLE
[Bundle Manager] Cache public workers instead of fetching it for every single staged bundles

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1749]
This PR is to cache `public_workers` in logic [Line 336](https://github.com/codalab/codalab-worksheets/blob/master/codalab/server/bundle_manager.py#L336), as `public_workers` are the same for all staged bundles in the function. This could make the dispatching logic simplier.

**Comment by candicegjing** [comment]
This is needed for each staged bundle as the available resources on each worker need to be subtracted from the total value each time.

**Comment by percyliang** [comment]
I don't understand why we need to refetch...  is it because subtraction mutates?  Can we adjust the logic?
