### ISSUE TITLE
[New Frontend] Worksheet spinner needs to be styled better

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1751]
**Describe the bug**
When a worksheet is loading, the new spinner that shows up needs to be better styled. 

1. First, it can get covered by some elements of the worksheet (e.g. tables). See screenshot below.
2. I think the spinner can be bigger.

**Codalab Information**
- Browser: Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Load up any worksheet in our dev environment and see the loading spinner.

**Screenshots**
![spinner_better_styling](https://user-images.githubusercontent.com/16793796/69780154-41b27080-115f-11ea-9bdb-e1f030ded045.png)

**Comment by yipenghe** [comment]
To me I think the size is alright, but I guess we can use a slightly bigger one, also the cover problem should indeed be fixed@epicfaace

**Comment by leilenah** [comment]
fixed
