### ISSUE TITLE
[New Frontend] Referencing a worksheet using bundle syntax (i.e. {worksheet_uuid}) causes page to crash

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1756]
**Describe the bug**
Referencing a worksheet using bundle syntax (i.e. {worksheet_uuid}) causes page to crash.

**To Reproduce**
Steps to reproduce the behavior :
1. Go to a worksheet.
2. Add the following line: {worksheet_uuid}
3. Page will try to load and then crash (see screenshot below).

See also the tiny worksheet to reproduce this issue: 
https://worksheets-dev.codalab.org/worksheets/0x3b4d0d28aa324f13b196d401482deaa8

**Expected behavior**
Page should not crash, we should just output an error.

**Screenshots**

![page_crashed](https://user-images.githubusercontent.com/16793796/69887379-7b889180-129b-11ea-9277-e7ceaef7af2f.png)

**Comment by yipenghe** [comment]
This bug is not usual to trigger but very fatal once triggered, no way to access the worksheet after triggered. We should at least be able to access the source if we can get info back from the rest server

**Comment by yipenghe** [comment]
Closing for now, opening another issue for refactoring that part of code
