### ISSUE TITLE
Run state doesn't updated automatically until you refresh the webpage

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1770]
In the bundle page: https://worksheets-dev.codalab.org/bundles/0xcc7a32e374cf471cb7efa35f2f0dd45a. `run_state` which is showing as `state` is stuck in `running` state until you refresh the entire webpage. It should be updated automatically.

**Comment by percyliang** [comment]
@yipenghe is this fixed by some of your latest changes?

**Comment by yipenghe** [comment]
> @yipenghe is this fixed by some of your latest changes?

The bundle no longer exists. However, the bug is on bundle page. Since we didn't work on anything related to bundle page (I fixed things in bundle details & bundle rows), the bug should still be present.

**Comment by yipenghe** [comment]
Took a quick look at the bundle page code, I think it only fetches data once and doesn't periodically fetch data to update for all fields (stdout, stderr etc.), which is why the state is stuck

**Comment by percyliang** [comment]
Seems fixed now.
