### ISSUE TITLE
"manifest unknown" error when running docker on a non-master branch

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1771]
When I switch to the branch `f-download-run` and run the following command:

```
python3.6 codalab_service.py start -s default
```

I get the following error:

```
process: Pulling rest-server (codalab/server:f_download_run)...
process: manifest for codalab/server:f_download_run not found: manifest unknown: manifest unknown
Traceback (most recent call last):
  File "codalab_service.py", line 784, in <module>
    main()
  File "codalab_service.py", line 96, in main
    service_manager.execute()
  File "codalab_service.py", line 532, in execute
    self.start_services()
  File "codalab_service.py", line 705, in start_services
    self.run_service_cmd(' && '.join(commands))
  File "codalab_service.py", line 655, in run_service_cmd
    ' bash -c \'%s\'' % cmd
  File "codalab_service.py", line 630, in _run_compose_cmd
    raise Exception('Command exited with code {}'.format(popen.returncode))
Exception: Command exited with code 1
```

Note that the server still starts up successfully, but the actual `codalab_service.py` script returns with an error exit code.

Also, I can fix this by running

```
python3.6 codalab_service.py start -s default -b
```

Perhaps this issue only comes up when you are running a new branch for the first time without building the docker images first?

**Comment by bkgoksel** [comment]
Yeah, manifest unknown is a docker error complaining that it can't find the requested docker image. The script sets the requested version to be current branch name by default, which makes the service request the docker images tagged with the branch name, which don't exist by default unless you build them.
