### ISSUE TITLE
[New Frontend] Clicking "View Source" => "Save" while Worksheet is loading wipes it out

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1774]
Clicking "View Source" then "Save" while Worksheet is loading wipes it out (unrecoverable).

**To Reproduce**
Steps to reproduce the behavior :
1. Go to an existing worksheet.
2. While it is first loading, click "View Source".
3. Do nothing until the page finishes loading and "Save" button becomes clickable.
4. Hit "Save".
5. It wipes out the entire worksheet and saves.

**Expected behavior**
Disable the "View Source" button or "Save" button while worksheet is loading or some other safety mechanism.

**Comment by yipenghe** [comment]
how did you hit save when you can only view source?

**Comment by teetone** [comment]
@yipenghe: Let me update the steps to make it clear. It's easily reproducible.

**Comment by yipenghe** [comment]
Ok reproduced...very bad bug
