### ISSUE TITLE
[Frontend] Trailing whitespaces for worksheet or bundle references causes rendering problems

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1779]
**To Reproduce**
Steps to reproduce the behavior :
1. Go to a worksheet with worksheet or bundle references.
2. Edit the source and add some trailing spaces to some references.
3. The references from step 2 just get treated as plain text (see screenshot below).

Link: https://worksheets-dev.codalab.org/worksheets/0xc98f4a352680448fb1ff498993d9f1ce

**Expected behavior**
We should ignore trailing white space. This can be confusing to users.

**Screenshots**
![Screen Shot 2019-12-01 at 2 35 02 AM](https://user-images.githubusercontent.com/16793796/69912843-cf9e8d80-13e3-11ea-93c4-13e310172454.png)

**Comment by percyliang** [comment]
Should strip spaces.
