### ISSUE TITLE
optimization library doesn't work on Codalab

### ISSUE THREAD

**Issue by fereshte-** [codalab/codalab-worksheets#179]
Hi,

When I run my code on the Codalab I got an error while the code works fine on my own machine.
If you look at the last 4 bundles of the below worksheet (LS one, LS all, LP one, LP all), the first two works fine while the last two generate an error while running(copied at the end). 

https://worksheets.codalab.org/worksheets/0x808a8ec7f5734cc49ed0daca8e4563e2/

I use Scpsolver for solving LP. It probably uses some optimization that java in the Codalab machines cannot handle (or does not allow)!

my java version is:
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

and this is the error:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000019b96, pid=28, tid=140119082276608
#
# JRE version: Java(TM) SE Runtime Environment (8.0_20-b26) (build 1.8.0_20-b26)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.20-b23 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x0000000000019b96
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /0xc8ee3a08d3964df7a486f70f7dac8f84/build/hs_err_pid28.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
#
```

**Comment by percyliang** [comment]
This is a really weird case - seems like a bug with Docker/JVM.  Closing for now, since it is rare and we don't know how to fix it.
