### ISSUE TITLE
table widths are too narrow

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1796]
https://worksheets.codalab.org/worksheets/0xa590fd1b68944a1a95c1c40c4931dc7b
![Screenshot from 2019-12-01 20-03-06](https://user-images.githubusercontent.com/435384/69929917-b5ad8b00-1475-11ea-9bf8-1667e8f002a7.png)

In particular, the spacing between `command` and `state` is really small (more so than in the old UI).

**Comment by yshen-google** [comment]
Before change:
<img width="923" alt="before_change" src="https://user-images.githubusercontent.com/63320611/83105511-a8add500-a06f-11ea-9526-299c2cafe2cd.png">
After change:
<img width="938" alt="after_change" src="https://user-images.githubusercontent.com/63320611/83105527-b06d7980-a06f-11ea-8310-61ae552ed747.png">
Not sure why my change is not pushed to prod yet. Maybe I should close the comment to move it to Done...
