### ISSUE TITLE
[Worksheet not found]

### ISSUE THREAD

**Issue by philhchen** [codalab/codalab-worksheets#1797]
**Describe the bug**
Worksheet not found

**Codalab Information**
- *Your username*: philhc
- *UUID of worksheet where problem occurred*: 0xd4d112475dd643bf8ef99e2b7cde6a76
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*: Not found: '/worksheets/0xd4d112475dd643bf8ef99e2b7cde6a76'
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*: safari

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yipenghe** [comment]
I think this has been solved? Closing it for now
