### ISSUE TITLE
Can't upload files on Chrome

### ISSUE THREAD

**Issue by SayHelloToProgrammerWorld** [codalab/codalab-worksheets#1799]
**Describe the bug**
the request for uploading files doesn't work.

**Codalab Information**
- *Your username*: wangfan
- *UUID of worksheet where problem occurred*: 
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by huyhieupham** [comment]
I am facing the same issue. Any comments or suggestions?

Thanks.

**Comment by teetone** [comment]
> I am facing the same issue. Any comments or suggestions?
> 
> Thanks.

@huyhieupham Sorry for the inconvenience. A temporary workaround would be to use the CLI and run `cl upload [path to content]`, which will upload the content to your current worksheet.

Reference: https://codalab-worksheets.readthedocs.io/en/latest/CLI-Reference/

**Comment by percyliang** [comment]
Uploading from the frontend is working for me.  Note that you have to be on a worksheet you own (not the dashboard).  So either create a new worksheet (upper right) or select one of your existing worksheets from the dashboard.  If you still have problems, please include the worksheet that you're failing to upload to.

**Comment by candicegjing** [comment]
@SayHelloToProgrammerWorld and @huyhieupham  Could you provide more details of which steps of uploading didn't work on your side?

**Comment by yipenghe** [comment]
> I am facing the same issue. Any comments or suggestions?
> 
> Thanks.

It seems if using windows 10 & chrome, the upload fails. I can upload through Microsoft Edge. What OS and Browser are you using?

**Comment by yipenghe** [comment]
The upload seems to be failing on Mac & Windows when using Chrome Browser

Two workarounds: 
1. Use a different browser (Edge on Windows, Safari/Firefox on Mac both work), I think any non-chrome browser would probably work....on ubuntu, chrome works as well
2. use the terminal and the upload command

**Comment by huyhieupham** [comment]
Hi @teetone @percyliang @candicegjing and @yipenghe :

Thanks for your support. I confirm that the upload fails on Chrome Browser - Windows and macOS. 

I retried with Microsoft Edge and it is working.

Best,
Hieu

**Comment by SayHelloToProgrammerWorld** [comment]
> @SayHelloToProgrammerWorld and @huyhieupham Could you provide more details of which steps of uploading didn't work on your side?

@candicegjing ，I retried upload following the suggestion from @yipenghe ,now it works after change the brower(Edge on Windows),thank you!

**Comment by yipenghe** [comment]
It seems that Chrome on Windows & Mac doesn't fire the onchange event for file inputs...weird
