### ISSUE TITLE
don't log user out so frequently

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#18]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Saturday Sep 26, 2015 at 21:56 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1290_

----

Currently, users seem to get logged out every day or so.  User should be able to stay logged in for a month.

**Comment by percyliang** [comment]
Extended to 30 days.
