### ISSUE TITLE
Copy bundle uuid within and across tables in worksheet

### ISSUE THREAD

**Issue by yipenghe** [codalab/codalab-worksheets#1802]
**Is your feature request related to a problem? Please describe.**

Bulk attach bundles to a particular worksheet, would be handy

**Describe the solution you'd like**

Similar to bulk detach/kill/delete, except ask for a worksheet uuid as arguments in dialog, current cmd line supports bulk attach I think

**Comment by percyliang** [comment]
Maybe what we should support is bulk copy / paste of bundles.

**Comment by yipenghe** [comment]
> Maybe what we should support is bulk copy / paste of bundles.

Ah I think that makes more sense, but not sure if there is a easy way to do it, no backend code currently does that

**Comment by percyliang** [comment]
For copy, you just need to add it to the clipboard (to be general, use the worksheet raw items as if you're doing raw edit).

For paste, you just need to insert the raw items (which we must already be able to do).

This way, if we have raw markdown lying around (e.g., in a tutorial), people can paste it into their worksheet without having to go into raw edit mode.

**Comment by yipenghe** [comment]
> For copy, you just need to add it to the clipboard (to be general, use the worksheet raw items as if you're doing raw edit).
> 
> For paste, you just need to insert the raw items (which we must already be able to do).
> 
> This way, if we have raw markdown lying around (e.g., in a tutorial), people can paste it into their worksheet without having to go into raw edit mode.

But for search results (like floating bundles on Dashboard), they don't have raw items in source right? Should we construct []{uuid} raw items for them then?

**Comment by percyliang** [comment]
Yeah, we would have to do that.
