### ISSUE TITLE
[USER ISSUE] Easy to request insufficient memory

### ISSUE THREAD

**Issue by yipenghe** [codalab/codalab-worksheets#1809]
**Describe the bug**
No restriction on the minimum memory for run request. When user request insufficient memory by accident (i.e typed 30 in new run panel to request 30 bytes, when the user actually wants 30g) it will crash the docker container and the only solution is to restart the worker

**Expected behavior**
Place a restriction on frontend side, override insufficient memory request on backend side for cli

**Comment by percyliang** [comment]
Just let backend do it.
