### ISSUE TITLE
Add color to test-cli.py

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#181]
Colors for PASS and FAIL messages will help find issues visually.

A more fleshed out summary at the end would also be helpful. (collect all the error messages and reprint them at the end?)

**Comment by kdexd** [comment]
Hello @kashizui, @percyliang :  
I had an idea in my mind about this:
We can make a simple class, which contains variables for `ANSI` escape codes, such as these here... 
And this class will have method marked as `@classmethod` which would take an input param as string and name of color, and return a string appended with appropriate _ANSI_ code. This will require no object declaration of class, as I think it can be avoided for this specific utility. A rough skeleton is as below:

``` python
class Colorizer:
    RED = "\033[31m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"
    END = "\033[0m"

    @classmethod
    def _colorize(cls, string, color):
        return getattr(cls, color) + string + cls.END

    @classmethod
    def red(cls, string):
        return cls._colorize(string, "RED")
```

Another approach is to use `xtermcolor` module.

``` python
from xtermcolor import colorize
RED = 1
GREEN = 2

print colorize("TEST PASSED", ansi=GREEN)
print colorize("TEST FAILED", ansi=RED)
```

First approach saves us a dependency for a small purpose, while second approach saves us some lines of code. I am in favor of second approach, as the module is stable, and it also does some compatibility checks with terminal.

**Comment by kashizui** [comment]
I don't know that we want to add a dependency for such a small use case. I would personally prefer the first approach. We are not too concerned with compatibility here, since most users will not be running `test-cli.py`, and I don't see a big likelihood of using colors in the CLI commands in the future.

**Comment by kdexd** [comment]
I am comfortable with any of the two. Expect a PR within a day or two, cheers ! :smiley:

**Comment by kdexd** [comment]
I am confused about the meaning of `P1`, `P2`, `P3` labels, my best guess is that P stands for priority. Am I correct ?

**Comment by kashizui** [comment]
Correct, P1 is top priority, P3 is lowest priority.
