### ISSUE TITLE
[Frontend] With a certain table in a worksheet, page crashes with React Errors

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1819]
**To Reproduce**
Steps to reproduce the behavior :
1. Paste the following into a worksheet:

// Page crash culprit
### Schema
% schema schema1
% add uuid uuid '[0:8]'
% add name
% add summary
% add metadata
% add permission
% add group_permissions
% display table schema1
[run run-date- : date; echo hello]{0x7740626c82874067b75d030a415292ab}
[run run-pip3 : pip3 list]{0x5f7d47919a5a49679073e3928386c99e}
[run run-echo : echo date]{0xe58dd5eac1a249b285421bb208af462e}
[run run-date : date]{0xf767161392ad4d10aa02e82a5b7b244c}

2. Page should crash with the following error:

![react_errors](https://user-images.githubusercontent.com/16793796/70173279-5fb03180-1687-11ea-8b14-c249f208dfb4.png)

**Comment by yipenghe** [comment]
Did some quick testing, adding this after line 187 of BundleRow seems to work
`if (typeof rowContent === 'object'){
                rowContent = 'none';
            }`... not sure why rowContent sometimes is a string, sometimes is a object with key, need some more checking...

**Comment by yipenghe** [comment]
I think it's a bug when referencing an invalid bundle in a table that has specified schema

**Comment by Levilian** [comment]
@yipenghe should we open an issue for this, or did you already fix it?

**Comment by yipenghe** [comment]
> @yipenghe should we open an issue for this, or did you already fix it?

Haven't fixed it, not sure if it's better fixing it frontend or backend
