### ISSUE TITLE
Test performance

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#182]
Put together automated tests to get an idea of the performance of the bundle service, and also general stress testing.

**Comment by percyliang** [comment]
The goal is to get an idea of the number of people that can simultaneously use CodaLab without a noticeable degradation in performance.

**Comment by percyliang** [comment]
We should have an automatic way of benchmarking this so we can monitor this metric.

**Comment by percyliang** [comment]
Duplicate of #632
