### ISSUE TITLE
improve upload feedback

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1826]
- give more upload feedback
- fix loading sign to use regular loading sign

**Comment by SayHelloToProgrammerWorld** [comment]
hi@epicfaace, have you ever uploaded a file which datasize exceeds 1G? I tried this operation, but the state is always uploading , so I wonder if I have done something wrong

**Comment by yipenghe** [comment]
> hi@epicfaace, have you ever uploaded a file which datasize exceeds 1G? I tried this operation, but the state is always uploading , so I wonder if I have done something wrong

Have you tried to use the CLI upload, one of our members says that the CLI might be more stable (people have uploaded multiple gig files )

**Comment by Levilian** [comment]
Right now the upload function doesn't seem to work on macOS Chrome? @yipenghe
