### ISSUE TITLE
worksheet title and name are not displayed

### ISSUE THREAD

**Issue by sidaw** [codalab/codalab-worksheets#184]
See for example this screenshot:
![image](https://cloud.githubusercontent.com/assets/1948012/15810718/4d8e6fc8-2b56-11e6-9a72-bf4c80bcb35d.png)

The title of the worksheet and the name field above uuid is not displayed. Although the owner can edit them, and they are available.

**Comment by percyliang** [comment]
Fixed by #185 , deployed.
