### ISSUE TITLE
Worksheet markdown documentation has unreliable URL

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#184]
Many parts of CodaLab reference the worksheet markdown documentation using the URL `https://github.com/codalab/codalab-cli/worksheet-syntax.md`, but this URL doesn't actually work on GitHub. (try https://github.com/codalab/codalab-cli/worksheet-syntax.md)

Proposing that we move the markdown documentation to the wiki and updates the links/tutorial worksheets to reflect this.

**Comment by kashizui** [comment]
@percyliang can you update the link on [the main worksheet](https://www.codalab.org/worksheets/0x8e7d56a12b31419fba6d5299830247be/) to point to the new URL as well?
https://github.com/codalab/codalab/wiki/User_Worksheet-Markdown

**Comment by percyliang** [comment]
Link updated.
