### ISSUE TITLE
Improve CodaLab landing page mobile responsiveness

### ISSUE THREAD

**Issue by Levilian** [codalab/codalab-worksheets#1845]
- [ ] center landing page buttons
- [ ] fix sign-up button overlap when width smaller than a certain threshold (currently fails on iPhone 11 Pro Max)
- [ ] nice to have: use gifs instead of a youtube video to showcase product features

**Comment by leilenah** [comment]
Mobile view has been improved. At least for the bundle view.

Mobile could still use a lot of work but roughly 0 people use codalab on mobile so this is not a priority.
