### ISSUE TITLE
Readthedocs new UI updates & tutorials

### ISSUE THREAD

**Issue by yipenghe** [codalab/codalab-worksheets#1850]
The current tutorial sends users to the CLI quick start, which might be a pain to start with. We should create a new tutorial for using the web CLI, maybe similar to the one I created in this worksheet https://worksheets.codalab.org/worksheets/0x7ab7d3e7c3ab480d9549949aa454c6f8

- [Summarize new features]
- [Remind: needs to set print(flush=True) to get stdout] 
- [New tutorials]

**Comment by epicfaace** [comment]
This is too general, closing this to make way for more specific issues.
