### ISSUE TITLE
MathJax seems to be not working consistently

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1851]
Before  deploying the new frontend, the following worksheet with math symbols used to render properly. With the new frontend, it seems to be not working consistently.

https://worksheets.codalab.org/worksheets/0xd19352d4d7854ad484e4e04609c1671b

**Comment by yipenghe** [comment]
It works locally

Seems to be a problem related to https https://stackoverflow.com/questions/25827935/what-do-i-need-to-do-to-get-mathjax-to-render-it-works-locally-but-not-live?r=SearchResults

Maybe should move to use npm package? https://www.npmjs.com/package/mathjax
