### ISSUE TITLE
[FEATURE REQUEST] option for deleting all descendants of a bundle

### ISSUE THREAD

**Issue by hhexiy** [codalab/codalab-worksheets#1855]
**Is your feature request related to a problem? Please describe.**
Currently a bundle cannot be deleted if other bundles depend on it. It would make sense to allow deletion of a bundle along with all of its children. Otherwise the user would have to delete them in order one by one.

**Describe the solution you'd like**
Add an option to `rm` that allows deleting a bundles' descendants.

**Comment by percyliang** [comment]
`cl rm -r` should do this

**Comment by hhexiy** [comment]
Works - thanks!

**Comment by yipenghe** [comment]
@percyliang Does -r work for bulk deletion? Would it make sense to add this flag to web ui as well?

**Comment by percyliang** [comment]
I think one should be able to apply `-r` to a set of bundles too.  Yeah, we
can add that as a flag in the web UI too, as long as it doesn't change the
current default behavior.
