### ISSUE TITLE
[USER ISSUE] Inherit configs for GUI `edit and rerun`

### ISSUE THREAD

**Issue by hhexiy** [codalab/codalab-worksheets#1856]
**Describe the bug**
In the GUI, when I click `edit and rerun` for a bundle, only the command and dependencies are copied, but the machine configs such as docker image, GPU request are set to the default values. It would be more convenient to inherit these configs too for the `edit and rerun` function.

**Codalab Information**
- *Your username*:
- *UUID of worksheet where problem occurred*:
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yipenghe** [comment]
@percyliang  This indeed is helpful, maybe I can work on this?

**Comment by yipenghe** [comment]
I'm planning to let it inherit disk, memory, cpu, gpu, and docker request. Are these what you find most helpful to inherit (@hhexiy )?

**Comment by yipenghe** [comment]
Will be fixed in next release
