### ISSUE TITLE
installation cl 

### ISSUE THREAD

**Issue by CecileSun** [codalab/codalab-worksheets#187]
I tried to register the cl path in .bashrc (as you suggested in tutorial) but it didn't work as expected, so I tried with .bashrc. I don't know if that is a bug.

**Comment by percyliang** [comment]
What was the exact line that you put in your .bashrc?
Are you sure your .bashrc is getting run (try putting echo hello in it)?
What command did you type that didn't work?

**Comment by CecileSun** [comment]
Thank you Mr. Liang. You are right. My .bashrc is not running, because I am in a login shell. So I registered the path in .bash_profile, now it works well. 

Thank you very much!
