### ISSUE TITLE
Multiline commands screw up rendering

### ISSUE THREAD

**Issue by AnanyaKumar** [codalab/codalab-worksheets#1879]
**Describe the bug**
CodaLab bundles and images render as text instead of as tables and images. See worksheet at https://worksheets.codalab.org/worksheets/0xb6d027ee127e422989ab9115726c5411

After editing source, these stopped rendering correctly. One hack was to remove the command and instead just write something like "[run]{0x55194f86321848a9af23c15d85e932a2}" in the source. This worked initially, and rendered correctly, but now gets treated as text.

**Codalab Information**
- *Your username*: skywalker94
- *UUID of worksheet where problem occurred*: 0xb6d027ee127e422989ab9115726c5411
- *Browser (if on Web)*; Google Chrome and Microsoft Edge

**Expected behavior**
Render as tables and images instead of text.

**Screenshots**
![2019-12-31](https://user-images.githubusercontent.com/1862850/71608064-441e4500-2bb9-11ea-8388-cdbf97417058.png)

**Additional context**
The codalab commands I was running were pretty long, here's an example command:

cl run :experiments :calibration :data \
'export PYTHONPATH="."; \
python3 experiments/platt_not_calibrated/lower_bounds.py \
--logits_path=data/cifar_logits.dat --bins_list="2, 4, 8, 16, 32, 64, 128" --lp=2 \
--calibration_data_size=1000 --bin_data_size=1000 --plot_save_file=l2_lower_bound_cifar_plot.png \
--binning=equal_bins --num_samples=1000' \
--request-queue tag=nlp -n cifar_l2_lower_bound

**Comment by yipenghe** [comment]
I think the long command is causing some problem. I used 0x55194f86321848a9af23c15d85e932a2 for a bit testing
Write in source []{0x55194f86321848a9af23c15d85e932a2}, it renders correctly and becomes:
![Screenshot from 2019-12-31 07-31-14](https://user-images.githubusercontent.com/23012631/71625977-981c3000-2b9f-11ea-9104-d7d05b7e8232.png)

After clicking edit source and saving right after, it renders as plain text. 
There might be some bug in saving source and relates to how it deals with bundle references that span several lines. I moved the command line in source (removing all '\'), it renders again

**Comment by percyliang** [comment]
Dup of #1051 

This should be a one-line fix: when we render a bundle as a markdown raw item, just replace newlines with spaces, so that each raw item is actually a single line.

**Comment by AnanyaKumar** [comment]
That sounds good! Anything I should do on my end to make the worksheet work (or should I avoid new-lines in the future), or should I wait for the fix? Thanks!

**Comment by AnanyaKumar** [comment]
@yipenghe Writing in something like []{id} did work initially, but right now that doesn't work for my worksheet, is there something else I can try as a temporary solution? Thanks!

**Comment by yipenghe** [comment]
> Dup of #1051
> 
> This should be a one-line fix: when we render a bundle as a markdown raw item, just replace newlines with spaces, so that each raw item is actually a single line.

I don't quite follow. How do we differentiate between rendering a bundle as a markdown raw item and a normal text line? Also, isn't it more about saving? We don't have code that processes bundle lines that crosses multiple lines
for example:
`1:[\`
`2:]{0x...}`
won't be treated as a bundle right? So in this case, when we save source, the lines gets treated as  separate plain text lines. So when we fetch from database after saving source, we get text items...

**Comment by yipenghe** [comment]
> That sounds good! Anything I should do on my end to make the worksheet work (or should I avoid new-lines in the future), or should I wait for the fix? Thanks!

Might be better to avoid new lines for now...Will try to fix soon

**Comment by percyliang** [comment]
The way we render a bundle in markdown is pretty much up to us...the convention is `[...command...]{0x...}`, but the command is not used for markdown interpretation (it's just for readability).  So we can put anything we want there.  As I understand, the problem comes when command contains new line, so I'm suggesting we just remove the new lines, which shouldn't affect anything else.

**Comment by yipenghe** [comment]
Next release (0.5.5+) should fix this problem, however, renderings that currently fails (i.e: in source the bundle line is displayed as multiple line) probably need manual fixes (Fix after next release comes out)

**Comment by AnanyaKumar** [comment]
Awesome, thanks!
