### ISSUE TITLE
I do not receive any confirmation email

### ISSUE THREAD

**Issue by phusroyal** [codalab/codalab-worksheets#1880]
**Describe the bug**
I signed up on 30/12/2019 but didn't receive any confirmation email. Moreover, I did try to change the email address but still nothing

**Codalab Information**
- *Your username*: TeamChoiChoBiet

**Expected behavior**
I did expect to have a confirmation email

**Comment by teetone** [comment]
Hi @phusroyal, the issue has been fixed now and you should be able to get confirmation emails when signing up. Sorry for any inconvenience.
