### ISSUE TITLE
dropdown for actions in side panel

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#19]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Saturday Sep 26, 2015 at 23:10 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1292_

----

Have a dropdown box under a nice big button labeled 'Actions' under which we have:

- Upload bundle: performs 'cl upload'
- New worksheet: performs 'cl new' [popups up a search box for a name]
- Bookmark? worksheet: 'cl wadd . home_worksheet'
- Clone worksheet: performs 'cl clone' [applies to current worksheet]
- Delete worksheet: performs 'cl wrm' [applies to current worksheet]
- Search worksheet: performs 'cl wls' [popups up a search box]

Each action should issue a CLI command in the terminal.

**Comment by percyliang** [comment]
Buttons created already.
