### ISSUE TITLE
"Unexpected error while parsing line" error when worksheet contains "id=sort-"

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#1904]
We see the an error when opening the following worksheet:
https://worksheets.codalab.org/worksheets/0xcb30d042437f49b8aef37499c660e3ce

This is a regression since the  particular syntax "id=sort-" used to work.

![Screen Shot 2020-01-16 at 12 00 14 AM](https://user-images.githubusercontent.com/16793796/72504721-3987c080-37f3-11ea-80f7-81e64b243e97.png)

**Comment by teetone** [comment]
I cannot reproduce this issue anymore.

**Comment by teetone** [comment]
I'm seeing this again...reopening the issue.

**Comment by yshen-google** [comment]
When I open https://worksheets.codalab.org/worksheets/0xcb30d042437f49b8aef37499c660e3ce, I don't see an error. Maybe this issue is not reproducible any more?

**Comment by yshen-google** [comment]
Feel free to reopen if the issue still exists.
