### ISSUE TITLE
invalid bundle with custom tables throws 'list index out of range' error

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#191]
https://worksheets.codalab.org/worksheets/0x9214f386a43148c1a95cef1a750a3aab/

**Comment by karandesai-96** [comment]
I am unable to reproduce this bug locally, but a general code inspection led me to the culprit of this bug:

It looks like any Exception message produced, is displayed in a red div on the screen. I found this method: [(model/bundle_model.py)](https://github.com/codalab/codalab-cli/blob/master/codalab/model/bundle_model.py#L814). It returns `worksheets[0]` as it says.

It calls `batch_get_worksheets` method declared just below, which returns an empty list in one of the [conditions](https://github.com/codalab/codalab-cli/blob/master/codalab/model/bundle_model.py#L837).

I am not sure what treatment is suitable to suppress it.

**Comment by percyliang** [comment]
Something bad can happen in two ways: 

- When you try to view a private bundle (cl perm <bundle> public none) not logged in
- When you have an invalid bundle uuid (use cl wedit and just change one of the uuids)

Also, these problems I think show up when we have a display directive, because that fires logic.

For invalid bundles, we should display an error message within the worksheet (so most things still load).  In any case, we should always have the user be able to at least click 'Edit source' and fix the problem.  Currently, what's bad is that we get into a state where nothing displays at all except for the error message.  (Currently, you have to use 'cl' to go fix things.)

**Comment by karandesai-96** [comment]
I will investigate more on this and bring up anything I find ambiguous / interesting.

**Comment by kashizui** [comment]
Error report:
```
Error on request by sckoo(17411):

GET /api/worksheets/0x9214f386a43148c1a95cef1a750a3aab/

Query params: [('_', '1470641990780')]

Form params: []

JSON body:
<none>

Traceback (most recent call last):
  File "/home/azureuser/codalab-cli/codalab/server/rest_server.py", line 134, in wrapper
    return callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/server/json_api_plugin.py", line 16, in wrapper
    return callback(*args, **kwargs)
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 470, in get_worksheet_content
    return service.full_worksheet(uuid)
  File "/home/azureuser/codalab-cli/codalab/rest/legacy.py", line 179, in full_worksheet
    for row_map in item['interpreted'][1]:
IndexError: list index out of range
```

For reference the contents of the above linked worksheet is:
```
% schema sempre
% add error /foo.json:error %.3f

% display table sempre
[]{0x9214f386a43148c1a95cef1a750a3aae}
```

Note that the last item is an invalid bundle reference (points to a nonexistent bundle).

**Comment by karandesai-96** [comment]
Hello @kashizui @percyliang:
I don't think that invalid _UUIDs_ create any problem now:
![image](https://cloud.githubusercontent.com/assets/10494087/17510092/ff97aff6-5e3a-11e6-867f-5ff8febad20f.png)

**Comment by karandesai-96** [comment]
Great ! This is history :smile:

**Comment by kashizui** [comment]
Thanks for your help @karandesai-96
