### ISSUE TITLE
CPU/GPU reporting issue

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1911]
The highlighted line seems to have unreasonable number of CPUs. Might need some investigation to fix this.
<img width="1074" alt="Screen Shot 2020-01-18 at 11 09 57 AM" src="https://user-images.githubusercontent.com/1483372/72669132-2c312880-39e3-11ea-9c1e-938072108681.png">

**Comment by candicegjing** [comment]
Based on [this piece of code](https://github.com/codalab/codalab-worksheets/blob/master/codalab/worker/worker.py#L338-L339): `cpuset` setting will always return the first few cores, meaning jobs will only be allowed to execute on the first few cores. For example, assuming available CPUs are `{0,1,2,3}`, if a user doesn't specify the `request-cpu` option, the number of CPUs to be allocated will be `1`, which leads to the returning `cpuset` to be `{0}` all the time. This doesn't seem to be correct, as we might want to fully utilize all cores at any time?

**Comment by candicegjing** [comment]
For GPU reporting [here](https://github.com/codalab/codalab-worksheets/blob/master/codalab/rest/workers.py#L153), I might need additional parameters to determine the number of GPUs in use. Currently, we only have 1 GPUs per GPU worker which could be easy to handle. But with GPU workers containing more than 1 GPU, we can't just sum all requested GPUs up, as GPU's architecture is different than CPU's

**Comment by percyliang** [comment]
We should never be sharing GPUs across jobs.

**Comment by percyliang** [comment]
Try to reproduce this on dev first, possibly with a private worker.
