### ISSUE TITLE
Staged state has been going on for 10 days

### ISSUE THREAD

**Issue by Ajanulk** [codalab/codalab-worksheets#1920]
Hi, my running bundle has been staged for 10 days. The uuid is 0x4cf367, please check it.

**Comment by candicegjing** [comment]
@Ajanulk I just checked your bundle status https://worksheets.codalab.org/bundles/0x4cf3673a495748ec89dae54b9ec54989 and noticed that you requested 2 GPUs for your run. However, we only have 1 GPU per worker in our current system. Any bundle requests for more resources than we have will not be able to find a qualified worker to run on. If you think 1 GPU could work for your case, you can update the `request-gpus` field in your bundle. This should unblock the job. Another option is to attach your own worker that has more computing resources than our system.

**Comment by Ajanulk** [comment]
> @Ajanulk I just checked your bundle status https://worksheets.codalab.org/bundles/0x4cf3673a495748ec89dae54b9ec54989 and noticed that you requested 2 GPUs for your run. However, we only have 1 GPU per worker in our current system. Any bundle requests for more resources than we have will not be able to find a qualified worker to run on. If you think 1 GPU could work for your case, you can update the `request-gpus` field in your bundle. This should unblock the job. Another option is to attach your own worker that has more computing resources than our system.

Got it. Thanks very much!
