### ISSUE TITLE
Worksheet rendering problems 

### ISSUE THREAD

**Issue by Levilian** [codalab/codalab-worksheets#1921]
1. Terminal still present even if "show terminal" is not called
![Screen Shot 2020-01-22 at 10 06 14 PM](https://user-images.githubusercontent.com/13169407/72960832-fc2bb180-3d63-11ea-812c-9894adcc0f49.png)

2. Custom table in worksheet overflows
![Screen Shot 2020-01-22 at 10 05 33 PM](https://user-images.githubusercontent.com/13169407/72960989-883dd900-3d64-11ea-92ed-4e959f1f2d9d.png)

**Comment by bkgoksel** [comment]
The overflow issue is pretty crippling for the deployment at SM.
