### ISSUE TITLE
can't see the bundle details when click on image

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1934]
In the old UI, the side panel would be able to see the bundle info when the cursor was over an image, but now you can't.  Ideally, would show the same bundle details when press enter on other display modes (text, image, etc.).

**Comment by yipenghe** [comment]
I can take this, should it be a similar panel to the default mode?

**Comment by percyliang** [comment]
By default mode, you mean table mode?  Yes.
