### ISSUE TITLE
Unable to run macro [USER ISSUE]

### ISSUE THREAD

**Issue by moinnadeem** [codalab/codalab-worksheets#1942]
**Describe the bug**

I am unable to run a macro due to an issue with Docker.

**Codalab Information**
- *Your username*: moinnadeem
- *UUID of worksheet where problem occurred*: 0x3908d4e2e72e4c179e01e495551184a2
- *UUID of problem bundle (please don't delete)*: 0x156d45a546b7439193ea82ec147ea707
- *Error message received from Codalab (if applicable)*: Failed to download Docker image: Expecting value: line 1 column 1 (char 0)
 - *Browser (if on Web)*; Google Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Add the bundle `0x912604` to your worksheet, or create some empty JSON file.
2. Run the command `cl macro stereoset-utils/dev-evaluation {BUNDLE_NAME}` where `BUNDLE_NAME` is `predictions-bert-base-uncased` if you are using the above bundle.
3. You should see the resultant macro fail.

**Expected behavior**
The macro should succeed.

Link to problematic bundle: https://worksheets.codalab.org/bundles/0x156d45a546b7439193ea82ec147ea707

**Comment by moinnadeem** [comment]
Command to initially run the python script:
```
cl run :dev_evaluation.py input.json:dev-evaluation-in gold.json:dev_gold.json 'python3 dev_evaluation.py --gold-file gold.json --predictions-file input.json --output-file dev_scores.txt' -n dev-evaluation-run --request-docker-image codalab/default-cpu:latest
```

**Comment by yipenghe** [comment]
Can you try again? We made a few fixes on requesting docker image and should be handling the docker image problem, thanks

**Comment by Ajanulk** [comment]
> Can you try again? We made a few fixes on requesting docker image and should be handling the docker image problem, thanks

Unfortunately it seems to have not been resolved. The same situation appears here: (worksheet uuid) 0xd51af3a23aa54ba79dd3b953b839a1ba; (bundle uuid)0xcd7dc270d5ff428c849eeb2dc30d846e

**Comment by yipenghe** [comment]
> > Can you try again? We made a few fixes on requesting docker image and should be handling the docker image problem, thanks
> 
> Unfortunately it seems to have not been resolved. The same situation appears here: (worksheet uuid) 0xd51af3a23aa54ba79dd3b953b839a1ba; (bundle uuid)0xcd7dc270d5ff428c849eeb2dc30d846e

Is it a private docker image? 
Not quite sure what's happening for the docker image, but probably a lot of edge cases still aren't handled? @bkgoksel @candicegjing

**Comment by Ajanulk** [comment]
> Is it a private docker image?
> Not quite sure what's happening for the docker image, but probably a lot of edge cases still aren't handled? @bkgoksel @candicegjing

It's a macro run for hotpotqa competition.
 `cl macro hotpotqa-utils//dev-eval-distractor-v1.0 predict -n evaluate`

**Comment by candicegjing** [comment]
@moinnadeem Sorry for the delay. I think your [worksheet:0x156d45a546b7439193ea82ec147ea707](https://worksheets.codalab.org/bundles/0x156d45a546b7439193ea82ec147ea707) was failed at pulling docker image. We deployed a fix to address this issue in early Feb.2020. This problematic bundle was created in the late Jan.2020. I tested pulling image on my side today and it worked. Would it be possible to rerun this bundle from your side?

**Comment by Ajanulk** [comment]
> @moinnadeem Sorry for the delay. I think your [worksheet:0x156d45a546b7439193ea82ec147ea707](https://worksheets.codalab.org/bundles/0x156d45a546b7439193ea82ec147ea707) was failed at pulling docker image. We deployed a fix to address this issue in early Feb.2020. This problematic bundle was created in the late Jan.2020. I tested pulling image on my side today and it worked. Would it be possible to rerun this bundle from your side?

@candicegjing Thanks for your attention. This run bundle has worked.

**Comment by candicegjing** [comment]
@Ajanulk Great! If you run into other problems, please feel free to let us know!
