### ISSUE TITLE
Job assignment sometimes doesn't work well

### ISSUE THREAD

**Issue by yipenghe** [codalab/codalab-worksheets#1953]
Sometimes there are two jobs that are assigned to the same worker, and it shows cpu7/6 or 2/1 gpu, while there are workers that are idling. Since it requires root access to see this, ping me for screenshots if unclear

**Comment by candicegjing** [comment]
Job assignment goal:
1. Assign bundle with GPUs requested to GPU workers
2. Assign bundle without GPUs requested to idle workers (CPU workers and GPU workers are all included)

#### Things to consider when assigning jobs to workers: what's the relative weight we want to put on different factors? 
Available factors are:
1. number of gpus
2. if user requested gpus?
2. number of cpus
3. number of running jobs on the worker
4. number of dependencies

**Comment by candicegjing** [comment]
Revised job assignment logic:
| Factors        | Priority           |
| ------------- |:-------------:|
| If requested for GPUs          | P0 |
| Number of shared dependencies among all workers  | P1      |
| Number of running jobs among all worker | P2      | 
| A random seed | P3      | 

Note that P0 indicates the highest priority and P3 indicates the lowest priority. More detailed information could be found [Worker's Sorting Algorithm](https://docs.google.com/document/d/13ZAAzznVfdeayg5ojpYrXeN4HkIx3ySBs6dAsxSu4g4/edit#).
