### ISSUE TITLE
[USER ISSUE] Failed to download docker image when running CheXpert competition

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1955]
**Describe the bug**
I’m running the CheXpert competition on CodaLab, and all of the recent models I have just run have failed due to
“Failed to download Docker image: Expecting value: line 1 column 1 (char 0)”

Here’s an example failed bundles and worksheets:
https://worksheets.codalab.org/worksheets/0x7e4850e815d64d998381411d7b134e2e

Some example bundles:
https://worksheets.codalab.org/bundles/0x05169282f7d14a9b8dc7eeb3009f79d4
https://worksheets.codalab.org/bundles/0xa61742e367c7408cabb1c652084915d7
https://worksheets.codalab.org/bundles/0x10e4ed54033144d885415c0e9806ec11
https://worksheets.codalab.org/bundles/0x172acdfe8b2f4385b45e0dad9105d773
Config file is:
[codalab-v1.0.txt](https://github.com/codalab/codalab-worksheets/files/4149222/codalab-v1.0.txt)

**Comment by candicegjing** [comment]
Finished initial investigation, all the failed bundles are due to incorrect docker image names specified in `request-docker-image` field. Next step is to check how the docker image field got populated from competition script.

**Comment by Ajanulk** [comment]
@candicegjing Hi, is this problem solved? The same situation appears here: (worksheet uuid) 0xd51af3a23aa54ba79dd3b953b839a1ba; (bundle uuid)0xcd7dc270d5ff428c849eeb2dc30d846e
