### ISSUE TITLE
cl alias broken

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#196]
cl alias throws an error currently.

Also, during the interactive setup, we should ask:
- Do you want to connect to a codalab server (in which case, we don't want to use MockAuthHandler)?
- Do you want to set up docker (in which case docker_image + q needs to be added)?

**Comment by kashizui** [comment]
Just to clarify, using something besides `MockAuthHandler` is only necessary if you're running your own server, right? Should we still include this in the default setup dialog?

**Comment by percyliang** [comment]
That's true.  But so is MySQL, so It's probably good to include all the
choices there in one place.
