### ISSUE TITLE
bundle with low resource requirements is staged

### ISSUE THREAD

**Issue by guacamolia** [codalab/codalab-worksheets#1965]
Hi,

I was trying to run a simple bundle that outputs the date, but it seems to be stuck in the 'staged' state. I went to check the status of all the currently running bundles (https://worksheets.codalab.org/worksheets/0xa590fd1b68944a1a95c1c40c4931dc7b/), but it seems like nothing is running right now. Is this a problem of Codalab servers or is it something I should be looking into on my side? 

Thank you.

**Comment by josephch405** [comment]
It seems like the codalab.org cert just expired today - might have to wait until they fix that. My jobs are stuck in staged as well.
