### ISSUE TITLE
[USER ISSUE]Downloading dependencies using a codalabworker is very slow

### ISSUE THREAD

**Issue by Ajanulk** [codalab/codalab-worksheets#1974]
**Describe the bug**
We found that a codalabworker download dependencies very slowly, although we used the command line to upload `cl upload` quickly.

**Codalab Information**
- *Your username*: lrh001
- *UUID of worksheet where problem occurred*: 0xdcc8c840b5cd4243b6f90ade484aa9ae
- *UUID of problem bundle (please don't delete)*: 0x5c7f9b (failed), 0x86a7fe (ready), 0x90db97 (failed)
- *Error message received from Codalab (if applicable)*:

Failed to download Docker image: HTTPSConnectionPool(host='hub.docker.com', port=443): Max retries exceeded with url: /v2/repositories/lrh000/ubuntu/tags/?page=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5b640b4198>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

 - *OS (if on CLI)*: Ubuntu 16.04
 - *Codalab CLI Version (if on CLI)*: 0.5.8

**To Reproduce**
Steps to reproduce the behavior :
1. cl-worker
2. cl run -n predict --request-docker-image lrh000/ubuntu:nlp --request-gpus 2 --request-cpus 2 --request-memory 48g input.json:0xbdd8f3 :wsl_coda 'sh wsl_coda/work_dir/dev_preprocess.sh' (0x5c7f9b)  failed
3. cl run -n predict --request-docker-image lrh000/ubuntu:nlp --request-gpus 2 --request-cpus 2 'nvidia-smi' (0x86a7fe)  ready
4. cl run -n predict --request-docker-image lrh000/ubuntu:nlp --request-gpus 2 --request-cpus 2 :wsl_coda 'nvidia-smi' (0x90db97)  failed, same with step 2.

**Expected behavior**
An explanation of the mechanism for codalabworker to download dependencies and suggestions for improvement

**Additional context**
We think that the slow download of dependencies has led to excessive attempts to obtain images

**Comment by Ajanulk** [comment]
Is it possible to make the worker work behind a proxy? Or does `cl-worker`'s argument `--server` have an alternative?

**Comment by yipenghe** [comment]
@candicegjing Looks like a docker image related problem?

**Comment by Ajanulk** [comment]
@yipenghe @candicegjing  I did three experiments (0x5c7f9b, 0x86a7fe, 0x90db97) and it seems to be caused by slow downloading of dependencies. In fact, downloading the docker image is fast and ready. 

New problem: 
The worksheet `0xdcc8c840b5cd4243b6f90ade484aa9ae ` disappeared 15 minutes ago when I was uploading a zip file.  (bundle uuid 0x181bf3)

Upload failed: remove got non-existent path:: /home/azureuser/codalab-worksheets/var/codalab/home/partitions/codalab8/bundles/0x181bf31a1aba48cfb68b817116b08862/wsl_coda.zip

![image](https://user-images.githubusercontent.com/48608537/74214029-b6189c80-4cd6-11ea-8149-c1461aa6693e.png)

And this worksheet is no longer visible in the dashboard.

**Comment by teetone** [comment]
Hello again @Ajanulk, how large was your zip?

**Comment by Ajanulk** [comment]
@teetone Hi. About 2G. I have run an experiment using codalab's default worker, and download dependencies are fast (2G takes about 2min). So I guess if it is caused by the bad connection between the codalab server and my own worker.

https://codalab-worksheets.readthedocs.io/en/latest/Execution/#overview-how-the-worker-system-works
> The worker then downloads (if not downloaded already) all the relevant bundle dependencies from the CodaLab server and the Docker image from Docker Hub.

**Comment by teetone** [comment]
@Ajanulk I'm still looking into this. Did you worksheet disappear when you were uploading the zip?

**Comment by Ajanulk** [comment]
> @Ajanulk I'm still looking into this. Did you worksheet disappear when you were uploading the zip?

Thanks. Yes. The first time this happened was when I was uploading a bundle. The second time it happened suddenly when I refreshed the page after I finished uploading and running.

**Comment by teetone** [comment]
@Ajanulk Unfortunately, I couldn't reproduce this issue. Please, feel free to open up a new issue if this happens again. Sorry for the inconvenience.
