### ISSUE TITLE
when user not logged in, can't view any worksheets

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#198]
Example:
https://worksheets.codalab.org/worksheets/0xad3fc9f52f514e849b282a105b1e3f02/

Get this error:
'NoneType' object has no attribute 'user_id'

**Comment by kashizui** [comment]
Fixed by https://github.com/codalab/codalab-cli/commit/a8b449fdb248044b85e35dd7202b631711d2c901
