### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#198]
Remove '//' documentation at the top of the worksheet (expose this in wedit --help)

Make '//' a real comment (maps to current '%%').

Disable '%%'.

Note: when doing cl edit, '//' is still used to provide comments to the user which are ignored, but maybe this is okay?

**Comment by kashizui** [comment]
Should comments still be stored in the same format as "directives"?

**Comment by percyliang** [comment]
Yes.  Let's keep things backward compatible.

**Comment by kashizui** [comment]
fixed in #218
