### ISSUE TITLE
[USER ISSUE] Delete Bundle Button

### ISSUE THREAD

**Issue by hao-fang** [codalab/codalab-worksheets#1980]
**Is your feature request related to a problem? Please describe.**
It seems I cannot delete the bundle except using the terminal.

**Describe the solution you'd like**
Probably add a "DELETE" button next to the "DOWNLOAD" button.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by yipenghe** [comment]
Go to a worksheet that you have edit permission, attach your bundle there ('edit source, []{bundle_uuid}, save'), select the bundle row by hitting the checkbox, you should see delete appear on top left. You can delete multiple at once by selecting multiple bundles in your worksheet.
