### ISSUE TITLE
Competition dameon mimic docker issue 

### ISSUE THREAD

**Issue by Matthewdowney18** [codalab/codalab-worksheets#1987]
**Describe the bug**

Hello,

I am trying to run a competition with coda lab worksheets and i am having trouble with docker.

The competition Damion mimics a submitted models predictions on the dev set with the test set. Unfortunately, when it is running the model on the test set, I am getting this error:

(Failed to download Docker image: Expecting value: line 1 column 1 (char 0))

For the original prediction on the dev set, the "request_docker_image" is mattdowney18/quail and the "docker_image" is mattdowney18/quail@sha256:fb684487f6776a31eef06e2afd13bcf55fd08e37f02534fd03d301bc76f4d0c3

for the mimicked prediction on the test set,  the "request_docker_image" is mattdowney18/quail@sha256:fb684487f6776a31eef06e2afd13bcf55fd08e37f02534fd03d301bc76f4d0c3, the dame as the docker_image of the original prediciton

The same issue was happening to me when I was using macros to evaluate prediction files.

Sometimes, this issue will not happen and it will work fine, but it is not clear why that is happening and inconsistant.

**Codalab Information**
- *Your username*: matt.downey18
- *UUID of worksheet where problem occurred*: 0x07bedfc997d148389e494a58cd91310d
- *UUID of worksheet with original predictions: 0x531c8290bb3d45058c3750b1d67b70ca
- *UUID of problem bundle (please don't delete)*: 0xf77e50058e71441a908112e5a86f1efc
- *Error message received from Codalab (if applicable)*: Failed to download Docker image: Expecting value: line 1 column 1 (char 0)
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*; firefox

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**
I expected it to run with the same docker image as the previous prediction bundle, but it could not find it

**Screenshots**
competition config file:
![Screenshot from 2020-02-11 18-12-26](https://user-images.githubusercontent.com/39807857/74288312-18cf5f80-4cfa-11ea-8292-8b33c0b06152.png)

**Additional context**

**Comment by candicegjing** [comment]
@Matthewdowney18 Sorry for the inconvenience. What happened was that we had 3 workers went offline in the past and when we restarted them, they went up using a version that doesn't contain the correct pulling image logic. Whenever your jobs got assigned to those three workers, they will fail. That's why you observed jobs failed randomly. We just restarted our workers with the correct version. Could you please double check on your end to see if it's working?

**Comment by Matthewdowney18** [comment]
It working nicely now! Thank you!
