### ISSUE TITLE
interaction with bundles

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#199]
Summary: Be able to interact with your run bundles when they are executing by writing files that your process can read.

1) An example of the general usage:

```
cl write bundle_uuid/commands.txt "set eta 0.5"
```

Your program will be responsible for reading commands.txt and interpreting what's there.

2) A common use case is to prepend to your program with a standard script (which we can provide) to read commands and just executes them:

```
cl run './get_commands & your_command'
```

Then you can execute arbitrary commands in the same docker container as your main program:

```
cl write bundle_uuid/command.txt "grep error log.txt"
```

3) To have an interactive prompt, in your program, do this:

```
mkfifo stdin
sleep 100000 > stdin &
your_program < stdin
```

Then from the outside, you can write to the pipe.

```
cl write bundle_uuid/stdin "hello"
```

Implementation: This should be implemented by the 'actions' metadata field (handles 'kill' right now).
Need to record the time that the actions were carried out.

Move 'bundle_metadata / actions' into bundle_action, and add fields to keep track of time.

**Comment by kelvinguu** [comment]
Hi Percy, the `cl write` command looks sufficient to me, and is definitely something that I would use!

So, the bundle's metadata would have a field listing all the cl write commands issued?

**Comment by percyliang** [comment]
Yes, we would store all writes issued in the metadata.
