### ISSUE TITLE
[USER ISSUE] cannot `cl upload` multiple files for python 3.7

### ISSUE THREAD

**Issue by hao-fang** [codalab/codalab-worksheets#1990]
**Describe the bug**

I couldn't upload multiple files together using `cl upload`. It returns the following error.
```
$ touch foo1 foo2
$ cl up foo1 foo2
Preparing upload archive...
Traceback (most recent call last):
  File "/env/bin/cl", line 10, in <module>
    sys.exit(main())
  File "/env/bin/cl.py", line 10, in main
    cli.do_command(sys.argv[1:])
  File "/env/lib/python3.7/site-packages/codalab/lib/bundle_cli.py", line 839, in do_command
    structured_result = command_fn()
  File "/env/lib/python3.7/site-packages/codalab/lib/bundle_cli.py", line 833, in <lambda>
    command_fn = lambda: args.function(self, args)
  File "/env/lib/python3.7/site-packages/codalab/lib/bundle_cli.py", line 1199, in do_upload_command
    ignore_file=args.ignore,
  File "/env/lib/python3.7/site-packages/codalab/lib/zip_util.py", line 215, in pack_files_for_upload
    source, arcname=os.path.basename(source), recursive=True, exclude=should_exclude
TypeError: add() got an unexpected keyword argument 'exclude'
```

**Codalab Information**
- *Your username*:
- *UUID of worksheet where problem occurred*:
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*: MacOS
 - *Codalab CLI Version (if on CLI)*:  0.5.8
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :
(See the above commands)

**Expected behavior**
According to the CLI help message, it should upload a bundle contains the two files
```
  upload <path> ... <path> : Upload one bundle whose directory contents contain <path> ... <path>.
```

**Screenshots**
NA

**Additional context**
NA

**Comment by epicfaace** [comment]
This is a python 2 -> 3 migration error: `exclude` is deprecated, need to use `filter` instead. support for `exclude` was removed in Python 3.7.

https://docs.python.org/3/whatsnew/3.7.html
