### ISSUE TITLE
Document using `codalab-service` for server setup

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1993]
It might be easier if we allow someone to use `cld` to perform the equivalent of `python3 codalab_service.py`. This would be easier to type and would be in line with `mongod`, `dockerd`, etc.

**Comment by percyliang** [comment]
With `pip install codalab`, this should just be `codalab-service`.  Do we need anything else?

**Comment by epicfaace** [comment]
No, `codalab-service` is good -- I wasn't aware of it earlier. We may want to document this for server setup, though, and use it for deployment. I don't see the point in actively using two different ways to start the codalab server (`codalab-service` and `python codalab_service.py`) and it's probably better to consolidate.
