### ISSUE TITLE
visualize the bundle dependency graph

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#2]
<a href="https://github.com/Raisins"><img src="https://avatars.githubusercontent.com/u/123099?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Raisins](https://github.com/Raisins)**
_Friday Aug 01, 2014 at 22:40 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/567_

---

visualize the bundle dependency graph (using d3), zoom around, click on bundles to go to bundle page

**Comment by percyliang** [comment]
Not essential, closing for now.
