### ISSUE TITLE
when users sign up, ask for full information (name, affiliation)

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#200]

**Comment by karandesai-96** [comment]
Hi @percyliang:
So I have looked into the source and I see a possible way to fulfill this feature.

So first here is in the frontend, [here (apps/web/templates/web/account/signup.html)](https://github.com/codalab/codalab-worksheets/blob/master/codalab/apps/web/templates/web/account/signup.html#L19).

Analyzing the HTML, I could see the `action` attribute which led me [here (rest/account.py)](https://github.com/codalab/codalab-cli/blob/master/codalab/rest/account.py#L61)
And another PR will be at **codalab-cli** making suitable changes here.

I'd make the PRs if I am in the right direction. Thoughts ?

**Comment by percyliang** [comment]
Yes, that's right!  Remember to make the PR into the 'develop' branch.

**Comment by karandesai-96** [comment]
Please have a look at the above referenced PRs. I hope they fulfill the needs of this issue. :smiley:

**Comment by karandesai-96** [comment]
Both the referenced PRs have been merged. It might be safe to close it now :smile:
