### ISSUE TITLE
Improve worksheet manipulation commands

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#201]
cl add ^ -w worksheet

doesn't work and prints out

UsageError: bundle spec None doesn't match (want index 1 out of 0 bundles)

**Comment by kashizui** [comment]
@percyliang The problem is that `^` is currently interpreted as a relative reference within the worksheet specified by the `-w` flag. You probably didn't have any bundles on your destination worksheet at the time. Should I make sure that `^` is always relative to the current worksheet?

**Comment by kashizui** [comment]
Making `^` references relative to the current worksheet rather than the explicit worksheet reference provided through the `-w` flag may make the behavior of commands such as `cl rm ^ -w worksheet`, which would delete the last bundle on the current worksheet regardless of the specified worksheet, difficult to understand. 

One solution may be to make explicit in the helpdocs for `cl add` that the `-w` spec refers only to the _destination_ worksheet.

**Comment by percyliang** [comment]
Ah, I see.

I think it's better to preserve the semantics of -w, which means, interpret
all of these commands on this worksheet.

Probably we should have another option -o output_worksheet or simply have
the last argument be the target worksheet.  (This means people will have to
type 'cl add foo .' rather than 'cl add foo').  Same goes for cl wadd.

Actually, 'cl cp bundle worksheet' does exactly this, but it's not obvious
that's the command to use.

Thoughts?

**Comment by kashizui** [comment]
We could just put a warning like "Warning: relative bundle references will
refer to bundles on the worksheet specified with the -w tag. Please use `cl
cp` to copy bundles across worksheets." when we detect simultaneous use of
relative bundle references and the -w tag. It would just be a warning, and
the operation will still go through (though perhaps we could ask "Are you
sure you want to continue?").

**Comment by percyliang** [comment]
I remember why relative bundle references were resolved with respect to the
-w argument.  I had this way of editing worksheets in vim (explained in the
README) and executing commands on that worksheet, and I wanted to be able
to do everything relative to a worksheet (which could be on a different
CodaLab instance).

Not sure that we need a warning - seems like it would be annoying to have
it pop up.  Perhaps we should get rid of 'cl add' and just make people use
'cl cp', which is more general.  'cl add' can be reserved for adding
messages.

**Comment by kashizui** [comment]
That makes sense to me, if we're okay with changing interface (we're still
in alpha right?)

**Comment by percyliang** [comment]
The only problem is that
cl cp would be used for adding bundles, but
cl wadd (not cl wcp) would be used for adding worksheets - which is
confusing!
Yes, this is a good time to change the interface and just get it right.

**Comment by kashizui** [comment]
Hm
Just spitballing: We could use cp to copy bundles, and add to add text and
also links to other worksheets (so no more wadd).

**Comment by percyliang** [comment]
Seems pretty reasonable!

cl add -m "message"
cl add worksheet_spec

**Comment by kashizui** [comment]
To summarize:
`cl add` - adds items of any time to worksheets such as text, bundles, and subworksheets
`cl wadd` - slated to disappear

**Comment by kashizui** [comment]
to include on this issue:
--force rm should also allow deleting bundles from multiple worksheets
