### ISSUE TITLE
Replace private/secret bundles with empty placeholders when retrieving info

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#202]
rather than silently filtering them out

this causes a 500 server error on the website when trying to view bundle info of a private bundle (rather than providing any useful feedback)

**Comment by kashizui** [comment]
@percyliang is this desired behavior?

I noticed that the `get_bundle_infos` function on the client just silently filters out unreadable bundles.

**Comment by percyliang** [comment]
That was the intended behavior (to prevent leaking private information).
But we should make sure that the downstream code is aware of this contract
of only getting readable bundles.

**Comment by kashizui** [comment]
Should we instead throw a `PermissionError` or pretend that it doesn't exist?

**Comment by percyliang** [comment]
We still want to display a worksheet with a private bundle though.

Although it's weird if we just have missing bundles.

It might be cleaner then to always return an object for each bundle, even
the private ones, but just have no information on it other than the uuid
(which does reveal some information, but hopefully it's okay).

**Comment by kashizui** [comment]
OK, re-orienting this issue.

**Comment by kashizui** [comment]
This got a little more complicated than expected, since a lot of code depends on the bundle_info fields being populated with valid/non-empty values.

@percyliang Would it be better to modify all the code reading these fields to be able to handle these empty placeholders, or some how hack an empty bundle that would work with all existing code? (or other ideas)

**Comment by percyliang** [comment]
Hm...I was was afraid that was going to happen.

I think it would be good to just be able to work with bundle_infos which
are {'uuid': ...} everywhere without putting fake info, etc.

What are some places where you need this?  Some helper functions might make
this less annoying?  At least a is_valid_bundle()?

**Comment by kashizui** [comment]
So as you said we should make the code everywhere robust enough to handle incomplete bundle_infos (with only 'uuid' key) as necessary.

In addition, perhaps we can make a subclass of Bundle that is a PrivateBundle to serve as a placeholder?

I was also thinking it might be good to make the bundle_info dict creation a method of the Bundle classes...

**Comment by percyliang** [comment]
On Sat, Nov 7, 2015 at 2:48 PM, Stephen Koo notifications@github.com
wrote:

> So as you said we should make the code everywhere robust enough to handle
> incomplete bundle_infos (with only 'uuid' key) as necessary.
> 
> Well, not universally maybe.  I think code that deals with bundle_info in
> the context of a worksheet should handle incomplete bundle_infos.  But code
> that just handles bundle_infos in general may not need to.

In addition, perhaps we can make a subclass of Bundle that is a

> PrivateBundle to serve as a placeholder?
> 
> I was also thinking it might be good to make the bundle_info dict creation
> a method of the Bundle classes...
> 
> Maybe...although the website won't have the luxury of using these in the
> future...

A general inconsistency is that we have the bundle class, but that's not
really used.  In some ways that's a good thing because it's really
transparent what's going on, and because the website will also just have to
be dealing with bundle_info dicts.

**Comment by kashizui** [comment]
OK, I'll hold off on larger refactoring ideas until I have a better high-level understanding of the codebase and try to keep the scope of this change small, specifically fixing code that "deals with bundle_info in
the context of a worksheet should handle incomplete bundle_infos".

**Comment by kashizui** [comment]
Fixed with #211
