### ISSUE TITLE
[FEATURE REQUEST] Allow arguments to override cl mimic

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2020]
I'd like to mimic a run bundle that was originally executed on the `john` queue, but I'd like the mimic'd run to have no queue information (i.e., run on whatever workers are available). is there any way to clear the queue information? (doing `cl mimic ... --request-queue ` results in a `cl mimic: error: argument --request-queue: expected one argument` , as expected).

**Describe the solution you'd like**

There should be some way of allowing arguments to override the original values in bundles. For instance, maybe empty value would indicate override.

**Comment by epicfaace** [comment]
Might have to do with https://github.com/codalab/codalab-worksheets/blob/5a0f3e3a01679dbbc0e6dc544d11f6e6ffb31ada/codalab/lib/bundle_cli.py#L2567

@nelson-liu Does it read the value when you override `--request-queue` with another value? trying to see if this is only an issue about overriding with an empty value, or an issue with overriding in general.

**Comment by nelson-liu** [comment]
yes, i can properly override the value the existing if i pass in `cl mimic ... --request-queue foo` . It's just an issue about overriding to an empty value.
