### ISSUE TITLE
[FEATURE REQUEST] Support codeblock markdown

### ISSUE THREAD

**Issue by hao-fang** [codalab/codalab-worksheets#2022]
**Is your feature request related to a problem? Please describe.**
The codeblock markdown (triple ticks) isn't working in CodaLab worksheet when there is an empty line in it.

**Describe the solution you'd like**
It should render properly the codeblock, e.g.,
```
line 1
line 2

line 3
```

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by epicfaace** [comment]
@hao-fang can you please link to a sample worksheet? I tried doing that and I got the expected display:

![image](https://user-images.githubusercontent.com/1689183/75116795-be4ed100-5620-11ea-8cca-adf1be8328cd.png)

**Comment by hao-fang** [comment]
Ah... I think why this happens. See https://worksheets-dev.codalab.org/worksheets/0xdec4451d9ab24d2da51f5c392ec70d2c

The thing is if I have empty lines in the codeblock, then the rendering is wrong.
Maybe this is a bug.

**Comment by percyliang** [comment]
Newlines are currently used to break a worksheet into blocks.  We would have to change the parsing logic to pay attention to such quotes.

**Comment by leilenah** [comment]
closing per Percy's last comment
