### ISSUE TITLE
[FEATURE REQUEST] Tag for CodaLab public instances

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2025]
**Is your feature request related to a problem? Please describe.**

I'd like a way to force my jobs to be run on the CodaLab public Azure instances. Right now, the only way to make this work is to shut down all the other existing workers.

**Describe the solution you'd like**

you could do `--request-queue tag=public`, but I'm not sold on the name.

**Comment by candicegjing** [comment]
@nelson-liu want to confirm with you on the use case, do you want to just tag the public instances and run your job on any of them? Or do you want to tag a specific one of the public instances?

**Comment by nelson-liu** [comment]
the former—i'm fine with my job running on any of them.

**Comment by nelson-liu** [comment]
i'm not sure if a worker can have multiple tags, but if so, maybe the most ideal thing would be:
- a tag `codalab-public` that targets any codalab public instance
- a tag `codalab-public-cpu` that targets any codalab CPU public instance
- a tag `codalab-public-gpu` that targets any codalab GPU public instance

When running others' bundles, they sometimes have quirks in their dockerfiles (e.g., https://github.com/codalab/codalab-worksheets/issues/1704#issuecomment-562373449) such that they bundles themselves don't use the GPU, but they _must_ be run on a CPU machine (else, the GPU worker will crash). In this case, it's good to be able to explicitly target a CPU machine.
