### ISSUE TITLE
[USER ISSUE] Codalab docker permissions differ from non-codalab docker permissions

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2027]
**Describe the bug**
I have certain permissions when I run docker directly from the host (non-codalab), and these differ from the permissions I have when I interact with the host through codalab.

To reproduce:

This command on jagupard26 on the SAIL cluster prints `whoami`, followed by a listing of `/root` and then a `conda info` (note that the conda path is `/root/anaconda3`). The docker image is `nfliu/pqmn:latest`. The output is:

```
(base) nfliu at jagupard26 in ~
$ docker run --rm -it nfliu/pqmn:latest bash -c "whoami ; ls -al /root ; conda info"
root
total 40
drwx------ 1 root root 4096 Jun 18  2017 .
drwxr-xr-x 1 root root 4096 Feb 23 10:59 ..
-rw------- 1 root root  857 Jun 18  2017 .bash_history
-rw-r--r-- 1 root root 3214 Jun 18  2017 .bashrc
-rw-r--r-- 1 root root 3106 Jun 17  2017 .bashrc-anaconda3.bak
drwx------ 1 root root 4096 Jun 18  2017 .cache
drwxr-xr-x 3 root root 4096 Jun 18  2017 .conda
-rw-r--r-- 1 root root  148 Aug 17  2015 .profile
-rw------- 1 root root  108 Jun 18  2017 .python_history
drwxr-xr-x 1 root root 4096 Jun 18  2017 anaconda3
Current conda install:

               platform : linux-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /root/anaconda3  (writable)
    default environment : /root/anaconda3
       envs directories : /root/anaconda3/envs
                          /root/.conda/envs
          package cache : /root/anaconda3/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/3.6.1 Linux/4.15.0-66-generic debian/stretch/sid glibc/2.23
                UID:GID : 0:0
```

However, if I run the same command on codalab (with `--request-docker-image nfliu/pqmn:latest`), I see:

https://worksheets.codalab.org/bundles/0x263a41b4575f4f27b77381db9bab8d05

```
whoami: cannot find name for user ID 19658
ls: cannot open directory '/root': Permission denied
bash: conda: command not found
```

A few observations:
- on codalab, `whoami` tells me that I'm not `root`.
- `19658` is my userid on the sail cluster (the host itself)
- this is annoying because commands that work natively in docker don't work in codalab. it fails to find `conda`, which breaks the whole python install.
- I think there's inconsistency between hosts—if I were to run this job on the codalab public instances, I'm pretty sure i'd be `root` in codalab (i've fixed similar issues before by running on the codalab public instances). This makes me think it's an issue of the host configuration

Overall, not sure if this is a bug—the inconsistency between hosts is pretty annoying and doesn't lend itself to reproducibility (you get different results depending on where you run).

If it's not a bug, could someone explain to me what's going on / how I could possibly get `root` permissions in-codalab itself?

**Comment by nelson-liu** [comment]
Come to think of it, there's probably some `docker run -u=$(id -u) ...` going on somewhere? Which is why things work on azure public workers, since the default user there is `root`?

**Comment by epicfaace** [comment]
Probably -- I was just about to note that your commands [work on a regular worker](https://worksheets.codalab.org/bundles/0x606959447db546b1a112cbe7d1c63f59). What is the default user on the jagupard computers? Do you know if there's a difference in how codalab is installed / configured on those workers?

**Comment by armancohan** [comment]
@nelson-liu did you find any workarounds for this?

**Comment by nelson-liu** [comment]
@armancohan yeah, it's annoying but I rebuilt the affected docker images to not write into directories like `/root`, and instead used `/opt`. There were also some issues that arose from not using a nvidia image a base image, so I changed that as well. Lastly, I found that doing `RUN chmod -R a+w </affected path you can't run>` in the dockerfile would fix the problem as well.

If you're running into this for one of your own Dockerfiles and can't get it to work, I'd be happy to take a look? Feel free to send email.

iirc the allennlp docker image had this issue, but I never got around to submitting a PR upstream (not sure if that's what you're dealing with).

**Comment by armancohan** [comment]
Thanks for the tips! Yeah, I was able to make it work with `RUN /bin/bash -c 'chmod -R 777 /src/'` where `/src/` included the conda setup and source code. (it wasn't the allennlp docker image).
Your tip on downgrading docker version mentioned in the other issue was also helpful to make the worker detect my GPU. Also had some issues in inconsistency of the current working directory when using my own worker vs the default workers, but was able to make it work by preprending `cp * /src/` and `cd /src/`command to my main "cl run" command.
