### ISSUE TITLE
up navigation using keyboard broken

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2032]
On a list of bundles, hit 'k' or up, and the selected bundle will disappear as if the selection jumps to the top.

**Comment by yipenghe** [comment]
For this issue, is it the first bundle table, and when you hit 'k'/up, are you selecting the last bundle of the bundle table? or is it more general?
possible dup of #1998 ?

**Comment by percyliang** [comment]
Oh weird, this bug doesn't happen when there are two tables, but manifests when there is one table.  The cursor just disappears, and then when I hit down, the first row of the table is selected.

**Comment by yipenghe** [comment]
> Oh weird, this bug doesn't happen when there are two tables, but manifests when there is one table. The cursor just disappears, and then when I hit down, the first row of the table is selected.

I think its the same issue, when you are on a bundle table which is the first item of the worksheet, the cursor disappears because a check was buggy, should be fixed on master already

**Comment by yipenghe** [comment]
> Oh weird, this bug doesn't happen when there are two tables, but manifests when there is one table. The cursor just disappears, and then when I hit down, the first row of the table is selected.

I think its the same issue, when you are on a bundle table which is the first item of the worksheet, the cursor disappears because a check was buggy, should be fixed on master already
