### ISSUE TITLE
[USER ISSUE] DockerImageManager with max_image_size defined fail to pull images from digests

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2038]
**Describe the bug**

If a `DockerImageManager` has `self._max_image_size` defined, it fails to run jobs that request images from digests (but it works fine for tags).

Relevant logic in DockerImageManager: https://github.com/codalab/codalab-worksheets/blob/bd9171ab8a4dd38f55d2d1d536e01651395d3161/codalab/worker/docker_image_manager.py#L247

Link to the buggy function: https://github.com/codalab/codalab-worksheets/blob/master/codalab/worker/docker_utils.py#L279

The issue is that the `get_image_size_without_pulling` function makes a request to docker hub to get the image sizes, but docker hub only returns information about images that are *tagged*. e.g., for the image above, we have: https://hub.docker.com/v2/repositories/aexea/mono-base/tags/?page=1

The request returns information about all the tagged digests, but not the untagged ones. Doing `docker pull` on the sha above is still fine, it just isn't assigned a tag. So, since it doesn't have a tag, `get_image_size_without_pulling` returns `None`, and then the Docker image manager erroneously assumes the image just doesn't exist.

**This is particularly annoying since all the codalab public workers seem to be have `self._max_image_size` defined. So, any job that lands on them that requests a digest image (that isn't a tag) will fail instantly.**

**To Reproduce**

```
$ python -c "from codalab.worker.docker_utils import get_image_size_without_pulling; print(get_image_size_without_pulling(\"aexea/mono-base@sha256:cdc60244716b216afc61326950ab8cebc2dcefbf209a8f98980e6edaefb21514\"))"
None
```

Note that it returns `None`, while the image clearly exists on docker hub:

```
$ docker pull aexea/mono-base@sha256:cdc60244716b216afc61326950ab8cebc2dcefbf209a8f98980e6edaefb21514
sha256:cdc60244716b216afc61326950ab8cebc2dcefbf209a8f98980e6edaefb21514: Pulling from aexea/mono-base
cf0a75889057: Downloading  11.32MB/67.1MB
c8de9902faf0: Download complete
a3c0f7711c5e: Download complete
e6391432e12c: Download complete
624ce029a17f: Download complete
d4aea0bcfeb4: Waiting
fcb645e3eb17: Waiting
fc972ab4711a: Waiting
96f69738d38c: Waiting
de38c4b93cb4: Waiting
514ff2273631: Waiting
e870908e48b7: Waiting
45ff5e8cd5e7: Waiting
```

**Expected behavior**

The image downloads, the run begins.

**Additional context**
I'm not sure if it's possible to get the docker image size without pulling in this case...

**Comment by candicegjing** [comment]
@nelson-liu I just double-checked the image that caused the pulling failure. 
1. It seems that what shows in Docker Hub: [aexea/mono-base](https://hub.docker.com/r/aexea/mono-base/tags) matches what we get from [Docker Rest API V2](https://hub.docker.com/v2/repositories/aexea/mono-base/tags/?page=1). 
2. From the [docker push documentation](https://docs.docker.com/engine/reference/commandline/push/), `TAG` is **required** before pushing to a registry. 

I was wondering do you happen to know when this image was created and how was it pushed to Docker Hub? There might be some edge cases that we are missing here. Please let us know.

**Comment by nelson-liu** [comment]
so, if you generate a dockerfile, you get a sha. say you push this dockerfile with the tag latest. if you update the dockerfile, and re-push with the tag latest, then the sha associated with the tag is overwritten.

But the first sha still exists, and you can pull from it. This case is this first sha, that isn't associated with a tag (it formerly was, but was overwritten).
