### ISSUE TITLE
'list indices must be integers not str' error

### ISSUE THREAD

**Issue by rajpurkar** [codalab/codalab-worksheets#204]
When a worksheet includes a dependency that is not readable by the user viewing the worksheet, the following message is displayed.

'list indices must be integers not str'

Maybe there is a more graceful way to notify the user + worksheet owner of what is going on. At least, it shouldn't make the rest of the worksheet impossible to view.

**Comment by kashizui** [comment]
We really need to overhaul the worksheet interpretation code and make it more modular, transparent, and maintainable...

**Comment by kashizui** [comment]
I can take a look at this later tonight.

**Comment by kashizui** [comment]
Fixed by https://github.com/codalab/codalab-cli/commit/33a14f50a0574a6d38a672bbdea0c9dba226ff21

Deployed to worksheets.codalab.org
