### ISSUE TITLE
When verifing that we can evaluate the predictions on the development set: Failed to download Docker image: Unable to find Docker image

### ISSUE THREAD

**Issue by hello-deh** [codalab/codalab-worksheets#2066]
When submit for squad2.0, I have successed in doing the following:
cl run :dev-v2.0.json :src "python src/<path-to-prediction-program> dev-v2.0.json predictions.json" -n run-predictions
and
cl make run-predictions/predictions.json -n predictions-{MODELNAME}
but  the flowing step failed:
cl macro squad-utils/dev-evaluate-v2.0 predictions-{MODELNAME}
error message:
Failed to download Docker image: Unable to find Docker image
How to solve this?

**Comment by candicegjing** [comment]
@hello-deh Could you provide the uuid of the worksheet that caused the problem? Or any other details that can help us to reproduce the issue would be appreciated!

**Comment by lxylxyoo** [comment]
+1. I have same question.

Failed to download Docker image: Unable to find Docker image: codalab/ubuntu@sha256:a8369aaa7afdb4d242104d85aa660c034a7bf89e438963bf73ba197fe3731be0 from Docker HTTP API V2.

**Comment by sherman6** [comment]
+1 ; I have a similar issue.  
- My workbook is located here: https://worksheets.codalab.org/worksheets/0xa8e15f5c9f094bb98a3ce816220b6ebb
- The code I ran was:  cl macro squad-utils/dev-evaluate-v2.0 robinjia_example.json
- The following warning message resulted: 
`State`
`failed` 
`(Failed to download Docker image: Unable to find Docker image: codalab/ubuntu@sha256:a8369aaa7afdb4d242104d85aa660c034a7bf89e438963bf73ba197fe3731be0 from Docker HTTP API V2.)`

**Comment by candicegjing** [comment]
@lxylxyoo  and @sherman6 Could both of you rerun your bundle? I believe this issue should be fixed now.

**Comment by sherman6** [comment]
Thanks, this is now resolved for me!

**Comment by candicegjing** [comment]
> Thanks, this is now resolved for me!

Glad it worked! If you have any other questions in the future, please feel free to let us know!
