### ISSUE TITLE
Explore promoting new baseline images for Selenium tests with GitActions

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2072]
Currently, Travis requires us to configure AWS S3 to store the baseline and output images for our Selenium tests. When we move to GitActions, we should explore ways to easily manage output images and promote new baseline images. We might need to use something like SauceLabs.

**Comment by teetone** [comment]
Updated the issue. For a second, I thought we were going to use GitLab (another CI/CD pipeline).

**Comment by epicfaace** [comment]
@teetone any thoughts on this, now that we're using GitHub Actions?

All we do right now is upload the image diffs as artifacts if the screenshots ever differ and the frontend tests fail.

**Comment by epicfaace** [comment]
This isn't relevant for GHA anymore since it already stores the images as artifacts without needing S3.
