### ISSUE TITLE
Unclear ID and CLASS NAME values for HTML elements in Worksheets

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2073]
A lot of elements (buttons, text boxes, select boxes, check boxes, etc.) in Worksheets seem to have non-intuitive values (e.g. MuiButtonBase-root-265 MuiIconButton-root-285). Also, not all unique elements of the worksheet have an id specified, which I think it's best practice to do so. 

The inconsistency in naming makes it hard to write Selenium tests that query these elements.

**Comment by epicfaace** [comment]
@teetone apparently material-ui class names are nondeterministic, though you could provide your own class name generator: https://material-ui.com/styles/advanced/#class-names

This post gives a suggestion for working around it -- perhaps you could use an XPath selector that queries for an element based on the text that it contains: https://stackoverflow.com/questions/38962825/automated-material-ui-components-using-watir-or-selenium

**Comment by leilenah** [comment]
Closing for now. Plz leverage the HTML `data` attribute for selenium tests when necessary https://www.w3schools.com/tags/att_data-.asp
