### ISSUE TITLE
Memoize runs in cl mimic/run command

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#2075]
This ticket is to add two additional options `--memo` and `--memo-not-failed` when running `cl mimic` and `cl run` command. 
1. `--memo`: if command + dependencies already exist, then return that UUID
1. `--memo-not-failed`: above and not failed

**Comment by percyliang** [comment]
@nelson-liu Does this sound good to you?

**Comment by nelson-liu** [comment]
this sounds great to me, thanks so much!
