### ISSUE TITLE
Improve delete confirmation box

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2078]
For deleting a bundle row, 'Deletion cannot be undone' is not in red, but for deleting a markdown item, it is.  Make it consistent (red).

It's not clear whether ENTER triggers 'Delete' (as opposed to 'Cancel')...can we make 'Delete' selected (as if you tabbed over to it).

I think we can get rid of the 'You can modify the source to delete multiple blocks at once.' message, since I don't think this is a common case and it clutters things.

**Comment by yipenghe** [comment]
For the second point, I feel it's weird to make it like tab selected from a mouse clicking perspective. I would prefer making it a "contained" style
![Screenshot from 2020-04-08 21-31-13](https://user-images.githubusercontent.com/23012631/78858139-5a217a00-79e0-11ea-876e-530ff414d2ff.png)

**Comment by percyliang** [comment]
Your screenshot looks good.
