### ISSUE TITLE
How to copy worksheet from one server instance to another?

### ISSUE THREAD

**Issue by CecileSun** [codalab/codalab-worksheets#208]
Hello,

I have built a worksheet on a local server called 'see4c':
http://worksheets.see4c.eu/worksheets/0x0dd63f06fc3b4988bb321b8a5bd3702d/
Now I want to copy it to the official server https://worksheets.codalab.org
Could you please tell me how to move / copy / clone a worksheet between different server instances (in this case, see4c server -> official server)?

Thank you very much!!

**Comment by percyliang** [comment]
You can use the `cl wadd` command to copy contents between worksheets:
https://github.com/codalab/codalab-worksheets/wiki/CLI-Reference#codalab-instances

**Comment by kashizui** [comment]
Closing as solved.

@CecileSun if you hit any issues feel free to continue commenting on this thread.
