### ISSUE TITLE
Certain sequence of worksheet actions and keyboard shortcuts causes previous text to get copied and repeated

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2083]
A bit troublesome to reproduce, but here are the steps to reproduce the issue:

1. Add a title to worksheet
2. Add some long text to the worksheet
3. Add a bundle using your mouse and hit Confirm
4. Rerun the bundle with your mouse by opening the previous bundle and hitting "Edit and Rerun"
5. This time add a bundle using `a r`. Type "echo goodbye" and hit CTRL + ENTER to save the bundle.
6. Upon saving see the new bundle being added + the text from step 2 getting repeated (for some odd reason). 

See the gif attached below. You can see the big block of text at the top of the worksheet getting copied and added to the worksheet.

![shortcut_bug](https://user-images.githubusercontent.com/16793796/76487406-9365ca80-63df-11ea-94e1-e35972c03473.gif)

**Comment by leilenah** [comment]
unable to repro
