### ISSUE TITLE
Order of display on permissions

### ISSUE THREAD

**Issue by rajpurkar** [codalab/codalab-worksheets#209]
Permissions are currently displayed in the order in which they are added.
When making comparisons of permissions across files, it's a little difficult to check that two bundles share the same set of permissions.

Maybe the permissions can be listed in alphabetical order.
In addition, it would be nice to be able to easily distinguish between 'read' and 'all' access level visually.

**Comment by maxwang7** [comment]
@rajpurkar Is this issue referencing the `cl gls` command? Are there other commands that you would like to see changed?

**Comment by maxwang7** [comment]
@kashizui says that this issue probably refers to the `cl info --verbose <bundle_spec>` command. I'll begin implementation for alphabetizing these results and printing in a table format, but I would like some feedback on what the CLI interface for this should be (how would a user specify that they should alphabetize the results?).

**Comment by rajpurkar** [comment]
This is not a command-line issue, it's a UI issue referring to the bundle permissions displayed on the right sidebar.

**Comment by maxwang7** [comment]
@kashizui Ok, I'll order the permissions alphabetically on the API side javascript and color code "read" as yellow and "all" as green.
