### ISSUE TITLE
Migrate CI build from Travis to GitHub Actions

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#2094]
Move CI build from Travis to Git Action would save us around 10 mins (Travis build takes ~30 mins vs Action build takes ~20 mins)

**Comment by candicegjing** [comment]
Sample test runs have been created under this repo: https://github.com/candicegjing/codalab-worksheets.
During retesting in early March.2020, we have started to notice the performance issue which is documented at [Python workflow runs longer now than in late Jan 2020](https://github.community/t5/GitHub-Actions/Python-workflow-runs-much-longer-now-than-in-Jan-27-2020/td-p/49428). Escalated this issue and currently it's under investigation. To track its progress, please refer to: https://github.com/actions/virtual-environments/issues/533

**Comment by candicegjing** [comment]
Also tried to set up the CI build in Azure Pipeline, got a similar result: [Codala Azure Pipeline](https://dev.azure.com/jingge19/jingge19/_build/results?buildId=1&view=logs&j=19c563d8-3dcd-57d1-cd5e-9dd946b0a29b)
There seem to be other users that are facing the same situation: [Unusual-Minutes-Usage-and-Run-Durations](https://github.community/t5/GitHub-Actions/Unusual-Minutes-Usage-and-Run-Durations/m-p/50683)

**Comment by epicfaace** [comment]
@candicegjing what's the status with this? It seems like you resolved the hanging build problem in https://github.com/actions/virtual-environments/issues/533?
