### ISSUE TITLE
[FEATURE REQUEST] workers that _only_ run bundles with a matching tag

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2097]
**Is your feature request related to a problem? Please describe.**

Currently, tagged codalab workers will run bundles without a `request_queue` set. Would it be possible to have some flag that forces a worker to *only* run bundles with a particular tag?

Rationale: Sometimes, I have a lot of bundles running that are untagged. I've already developed these bundles, and I'm sure they'll work—I'm just letting them run (think 50+ staged jobs).

In parallel, though, I'd often like to set up the next round of experiments, which sometimes means running stuff on codalab and seeing if it works. However, the development cycle is super slow since it's hard to get a worker—they're all busy running the untagged jobs waiting in the queue (even if I give the worker a special tag). It'd be nice if, in this case, these dev jobs were able to instantly land somewhere (assuming there isn't another one before it).

**Describe the solution you'd like**

Not sure what a solution would look like here—maybe an extra flag on `cl-worker` that locks it to running bundles with a particular tag? If you use the flag with an untagged worker, it throws an error or something.

**Comment by percyliang** [comment]
@candicegjing was going to add a tag to the public workers, so you could do `--request-queue public-cpu` or `--request-queue public-gpu` if you don't want it to go to your own.  In general, every worker should have a tag so that one can target it.  Would this work for you?  This way we can avoid increasing the complexity of the scheduling logic.

**Comment by nelson-liu** [comment]
> @candicegjing was going to add a tag to the public workers, so you could do --request-queue public-cpu or --request-queue public-gpu if you don't want it to go to your own. In general, every worker should have a tag so that one can target it. 

I think this is a good feature to have, but I was looking for something slightly different here.

This is my concrete use-case: I've been running a lot of old code (think 2016 Theano), and the Theano graph doesn't compile on newer GPUs. So, I want to use the older GPUs if possible (K40s on the cluster). So I spun up some workers on those hosts (with the tag `oldgpu`), and things were running fine. But, it finished all the bundles tagged with `oldgpu`, and then started running my untagged jobs. But, my untagged jobs don't work on these `oldgpu` machines—the most recent binaries of PyTorch actually don't support the K40s anymore. So, a bunch of my runs failed.

In this case, I want the `oldgpu` machines to run things that are tagged with `oldgpu`, and only those bundles. I could get around this in theory  by just _always_ specifying a `request-queue` on _all_ my bundles, but I _do_ want to use public worker capacity if I can get it.

**Comment by percyliang** [comment]
Yeah, I was implicitly suggesting you would specify a `--request-queue` on every run.  What are the desired semantics you would like for runs with an empty `--request-queue`?  Is it something like `public  | nelson-newgpu` (admittedly more clunky than the empty string, but also easy to reason about)?

**Comment by nelson-liu** [comment]
I think the semantics of the empty `--request_queue` are fine as-is (something like `public | all tags that I might own, now or in the future`)...it's just that, practically speaking, it's nice to be able to reserve particular *workers*. Another use-case I've been running into: because a lot of my jobs are untagged [1] , it's difficult to reserve a machine for interactive debugging of codalab runs. Sometimes it's nice to just have a worker reserved for you, and you can run test jobs to see whether things fail or succeed on codalab before launching 10s of jobs. It's currently impossible to do this right now (as long as you have bundles with an empty `--request_queue`), and the `tag_exclusive` workers would give that to you.

I guess I'm still a bit torn whether this is an issue that should be handled on the worker side, or on the bundle side...I see strong arguments for either.

[1]: because, fundamentally, I believe they can run on any worker. Whether this is true or not changes over time as I write more code and run more jobs :) e.g., I didn't think that the k40's would break my runs, but they do.

**Comment by percyliang** [comment]
So to summarize the two options:

1) `--request-queue ''` means all workers EXCEPT any workers with `tag_exclusive`.
- Pros: easier/simpler to run jobs.
- Cons: more complexity on the worker side, semantics of `--request-queue` are slightly more complicated.

2) `--request-queue ''` means all workers period.
- Pros: `--request-queue` semantics is simpler, don't have to change code.
- Cons: have to think more explicitly about whitelisting workers and do `--request-queue public-gpu | nlpgpu`.

I don't think there's any obvious solution.  I think we should be somewhat conservative in adding complexity (favoring 2), but if 1 is going to be a big win in ergonomics, then we should do that.  So it depends on the actual use cases.

**Comment by nelson-liu** [comment]
is the `|` operator implemented? I think it's more typical for me to actually want a blacklist (with a few elements) than a whitelist (with more elements)...

A solution that might not semantically make much sense would be to add a `not` operator to `request-queue`. So, if I wanted to tag a worker `dev` and set it to tag_exclusive, I could run jobs with `--request-queue=not dev`.

The thing I don't like about (2) is that it requires knowing the set of tags / their names a-priori, which can be annoying...(1) does seem more flexible to me.

**Comment by percyliang** [comment]
`|` is not implemented yet, but it's easy to do.  If we support negation `--request-queue not dev`, then we don't need worker changes, right?  It seems like 2) is annoying because a) you need to change `--request-queue` and b) you need to explicitly whitelist all the tags.  Negation would allow you to at least not to b).  Would that be okay?

**Comment by nelson-liu** [comment]
Yeah, you're right. I'm just concerned that it might be a bit rigid. The negation solution easily covers the case where you'd normally just spin up 1 `tag_exclusive` worker, and it covers that when, at bundle creation time, you know that you want to do this.

But, if you decide that you need another later on (after you've run the jobs) / you don't know that you want to do this at bundle runtime, it seems a bit hard...the issue is that you don't always have all the information about what you're going to do while your jobs run (especially if they can take awhile to get started), so it can be difficult to set `request-queue`...

I feel like (1) is a lot more ergonomic, but I understand the reservations around extra worker complexity. I think I need to think more about my workflow and whether / how (2) could fit the bill.

**Comment by percyliang** [comment]
I agree that (1) easier to use.  The complexity change from `tag_exclusive` alone isn't that bad, so perhaps the right thing to do is just do that.  It would be nice if adding this covered most of general use cases...can you think of any other use cases?

**Comment by nelson-liu** [comment]
Hmm...I see it as covering the general case where you want to "reserve" a worker for near-interactive use, which is a pretty broad use-case unto itself.

**Comment by percyliang** [comment]
Ok, then (1) seems like a reasonable way to go.
