### ISSUE TITLE
Hosting WebApp on CodaLab - White Page of Death and Speed Issues

### ISSUE THREAD

**Issue by siddk** [codalab/codalab-worksheets#2098]
**Describe the bug**

I'm trying to host a web app using CodaLab's netcurl functionality. However, when I try to navigate to the site (https://worksheets.codalab.org/rest/bundles/0x32012ac03152440f8b0b3b2ddbe67fe0/netcurl/8000/index.html) , and refresh the page a few times, the page stops loading altogether.

Furthermore, I'm noticing some problematic speed issues, especially as multiple users try to use the system. 

**Codalab Information**
- *Username*: siddk
- *UUID of worksheet where problem occurred*: 0xa3b3c03d52a14a31b9293c5980fdcd9c
- *UUID of problem bundle (please don't delete)*: 0x32012ac03152440f8b0b3b2ddbe67fe0 / https://worksheets.codalab.org/rest/bundles/0x32012ac03152440f8b0b3b2ddbe67fe0/netcurl/8000/index.html
- *Error message received from Codalab (if applicable)*: No Error Message
 - *OS (if on CLI)*: N/A
 - *Codalab CLI Version (if on CLI)*: N/A
 - *Browser (if on Web)*; Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Go to https://worksheets.codalab.org/rest/bundles/0x32012ac03152440f8b0b3b2ddbe67fe0/netcurl/8000/index.html
2. Refresh the Page multiple times (on Chrome or Firefox)
3. Eventually the page stops loading, and only serves an empty white page. However, if you switch to incognito mode, the page loads again (maybe some weird caching issue?)

**Expected behavior**
Page should load, and should load somewhat quickly every time a user navigates to the site.

**Screenshots**

**Additional context**

App is currently a combination of a React frontend (compiled into a static build) that is served via a Flask application (that implements other backend logic), run with the Gunicorn WSGI.

**Comment by teetone** [comment]
@siddk Like you said, I think it is related to the browser's cache. Clearing the cache and refreshing loads the webapp for me every time. Also, I was able to reproduce this issue in Chrome and Firefox, but not in Safari.

**Comment by siddk** [comment]
Is there a way to fix this? I currently have the site deployed elsewhere on AWS, and I'm not getting this problem there...
