### ISSUE TITLE
Single-file dataset uploads don't preserve executable permissions

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2099]
**Describe the bug**
Not sure if this is intended, but executable files, when mounted as dependencies (just the file itself), are not executable.

**To Reproduce**

```
$ touch test.sh

$ chmod +x test.sh

$ ls -al test.sh
-rwxr-xr-x 1 nfliu staff 0 Mar 21 20:30 test.sh

$ cl up test.sh -n test.sh
Preparing upload archive...
Uploading test.sh (0x21c2c6599378432985b2ad842f25ba9b) to https://worksheets.codalab.org

0x21c2c6599378432985b2ad842f25ba9b

$ rm test.sh

$ cl down 0x21c2c6599378432985b2ad842f25ba9b
Downloading test.sh(0x21c2c6599378432985b2ad842f25ba9b)/ => /Users/nfliu/git/ood-variance/test.sh
Received 0.00MiB [0.00MiB/sec]

$ ls -al test.sh
-rw-r--r-- 1 nfliu staff 0 Mar 21 20:31 test.sh
```

Note that the file was executable when uploaded, but not when downloaded. If you try to `cl run test.sh:test.sh ./test.sh`, the run fails with `/bin/bash: ./test.sh: permission denied`

**Expected behavior**

I expected to be able to run the script.

**Additional context**

Pretty sure this works if you put test.sh into a folder, and then upload the folder...

**Comment by percyliang** [comment]
Dup of #745
