### ISSUE TITLE
can't view public files when not logged in

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#210]
This is a public bundle, so we should be able to view it even when not signed in, but this is not the case:
https://worksheets.codalab.org/rest/bundles/0x98fbc68c90d54345aaa6f972f74a714d/contents/blob/out07

**Comment by kashizui** [comment]
Just a heads up, I won't be able to get to this issue until later in
September, so if this is urgent this should probably be reassigned.

**Comment by percyliang** [comment]
No problem

**Comment by percyliang** [comment]
Fixed.
