### ISSUE TITLE
Error in prod - cl wait in monitor.py fails intermittently

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2102]
Heartbeat checks in monitor.py fails when waiting for the run to finish (`cl wait [uuid]`).
           
          uuid = run_command(
                ['cl', 'run', 'stress-test.pl:' + upload_uuid, 'perl stress-test.pl 5 10 10']
            )
            run_command(
                ['cl', 'wait', uuid], 600, 3600
            )  # Running might take a while (includes staged time)
            run_command(['cl', 'rm', upload_uuid, uuid])

**Comment by percyliang** [comment]
The 1 hour time limit is already pretty generous, so I think we should look into why things are not running fast enough (we don't have enough workers or workers being too slow?)
