### ISSUE TITLE
Refresh doesn't work properly

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#211]
With the new change to automatic refresh (v0.1.11), refreshing is broken:
- If one edits the metadata in the side panel, this doesn't get automatically updated in the table.
- Right clicking on 'Remove bundle' doesn't cause the page to refresh and show everything else except what's been deleted.
- When edit the source (even when it's as simple as inserting new markdown) and click save, then refreshing doesn't work.

**Comment by ChengshuLi** [comment]
For the three bugs mentioned above, the first one has been fixed. I am not sure how to reproduce the other two. 

- Right clicking and "Remove bundle" works fine for me. The bundle is removed and the worksheet is refreshed with that bundle removed. 
- edit the source works fine for me too. Do you mean after you insert new markdown and click save, the worksheet doesn't refresh and doesn't reflect the change you made? 

Would you mind providing more details about how to reproduce these two bugs? 

Thanks!
@percyliang

**Comment by percyliang** [comment]
@ChengshuLi 
For the third point:
- run 'sleep 100'
- edit markdown, add 'this is a test' and save
- notice that the markdown isn't added.
- However, when the run terminates, then after editing/saving, the markdown is refreshed

It's been too long that I don't remember what the second point was about.

In general, I notice other bugs...maybe it's worth stepping back and making sure the code is written with clear invariants so that the logic is just more robust.
