### ISSUE TITLE
empty args (`cl run --- echo ""`) broken

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2114]
`cl run 'echo ""'` works, but `cl run --- echo ""` doesn't.  Should make the latter work.

**Comment by candicegjing** [comment]
I tested both cases in [this sample worksheet](https://worksheets.codalab.org/worksheets/0x5fda8f6f886e4f7f967255568a762c72). The latter seems to be working. Could you provide more details on how it didn't work?

**Comment by percyliang** [comment]
The `command` field is different.  The latter just turns into just `echo`...the empty argument just disappears.  Basically the quoting logic with `---` is broken.

**Comment by candicegjing** [comment]
Did some initial investigation. It seems that in the latter case, shell eats the quotes before python sees them. Adding additional single quotes as `cl run --- echo '""'` seems to be working fine. Just want to confirm the expected behavior: do we want to reserve the raw `""` without single quotes?

**Comment by percyliang** [comment]
The fix is to use `shlex` here: https://github.com/codalab/codalab-worksheets/blob/master/codalab/lib/bundle_cli.py#L799

**Comment by candicegjing** [comment]
> The fix is to use `shlex` here: https://github.com/codalab/codalab-worksheets/blob/master/codalab/lib/bundle_cli.py#L799

I guess my question is that by the time when `""` passed into [L799](https://github.com/codalab/codalab-worksheets/blob/master/codalab/lib/bundle_cli.py#L799), it has already been turned into single quotes `''`. So I am not sure if we want to preserve the `""` though.

**Comment by percyliang** [comment]
Either `''` or `""` is fine, as long as it doesn't disappear.
