### ISSUE TITLE
Web terminal copy newline behavior

### ISSUE THREAD

**Issue by rajpurkar** [codalab/codalab-worksheets#212]
When a multi-line command is copied from the web-terminal output, newlines are printed. These then need to be manually deleted.

Example use case: Run `cl info -f args some_run`, then copy the output and paste as new command. I often need this if I want to change multiple arguments quickly.

**Comment by percyliang** [comment]
For now, you can just hit 'a' on a bundle to paste the command into the web
terminal.

**Comment by rajpurkar** [comment]
Ah that should suffice!

**Comment by kashizui** [comment]
Should this be closed or should we improve the copying behavior?

**Comment by percyliang** [comment]
Maybe close it for now.  I think we might considering getting a better
terminal library at some point with better copying down the line.
