### ISSUE TITLE
Limit the number of gpu resource per user?

### ISSUE THREAD

**Issue by graykode** [codalab/codalab-worksheets#2123]
I wonder if there is a limit on the number of GPU resources per user in codalab.
Some people use too many resources, so my worksheet stays staged for too long.

https://worksheets.codalab.org/worksheets/0xa590fd1b68944a1a95c1c40c4931dc7b

**Comment by nelson-liu** [comment]
On the public workers, this is 3 by default. 

https://github.com/codalab/codalab-worksheets/blob/master/alembic/versions/2019061021_add_parallel_run_quota_d24522e04593.py

**Comment by candicegjing** [comment]
@graykode Currently our GPU workers are all occupied. We do set limits on resources that can be used by each user. All jobs are executed in the order they are received. If you would like to avoid the waiting time and have extra computational resources, we could encourage you to attach your personal worker to speed up the process. Instruction could be found at [running your own worker](https://codalab-worksheets.readthedocs.io/en/latest/Execution/#running-your-own-worker).
