### ISSUE TITLE
How to request more disk space?

### ISSUE THREAD

**Issue by CecileSun** [codalab/codalab-worksheets#213]
Hi,

I would like to know if I can have more than 10g of disk-quota.

I have used 9.3g and tried to request more using 'uedit -d' but got the following error:
```
CodaLab> uedit -d 3t
These fields are read-only: email, time_quota, time_used, disk_quota, disk_used, date_joined, last_login
```

Thank you in advance!

**Comment by percyliang** [comment]
Is it possible to delete some of the bundles?

For example, this bundle is just a merge of all the datasets: I'd list the
dataset bundles directly on the webpage instead of creating a new one:
https://worksheets.codalab.org/bundles/0x41e31bd4ee43480bb332958031b0370f/

This is a failed run, which you might not need anymore:
https://worksheets.codalab.org/bundles/0x467303fda94c4f81a2e611158c940b2e/

Another option is to do `cl rm -d ...` which removes the contents of a
bundle without removing the metadata (which is all that's needed to
regenerate the contents in theory).  So this could be a good way of
removing temporary files without destroying the provenance.

If you're still out of space, then please send me a request for increasing
the disk quota.

**Comment by CecileSun** [comment]
Thank you very much for your reply!

I have deleted all failed bundles and decreased the used space from 9.3g to 8.5g.

However, I prefer to keep the merged bundle https://worksheets.codalab.org/bundles/0x41e31bd4ee43480bb332958031b0370f/
instead of having them separately, so I can avoid to make changes in my code.
In this case, I tried to remove the separate copies but that would affect my merged bundle and the codes using that merged bundle:
```
rm -d 0x6923b4
Can't delete bundles 0x6923b482313c423998c3f2ca020f0176 because the following bundles depend on them:
  data(0x41e31bd4ee43480bb332958031b0370f)
  Beating(0x1e2c3a8b182b4ff2b10f2f130df104dd)
```
Is there any way to remove these separate copies while keeping the merged one?

Thanks a lot in advance for your help!

**Comment by percyliang** [comment]
You can do 'rm -d --force', but you should be very careful anytime you use
--force.

**Comment by percyliang** [comment]
Also, please check your quota again.

**Comment by CecileSun** [comment]
Thank you for your help ! 

My quota now is 5.2g / 20.0g (26.2%).

**Comment by kashizui** [comment]
For the record, only the administrator of a CodaLab instance can increase a user's allocate disk space.

**Comment by becxer** [comment]
@percyliang 
Hi, Percy Liang. 

As the same issue as above, I'm in suffering now while submitting ensemble model for SQuAD.
Could you increase my Codalab disk quota to 20g?

My id / email  is SCV / scv.back@samsung.com

**Comment by fabeschan** [comment]
Hi @becxer, your quota has been increased.

**Comment by sunmeng01** [comment]
@percyliang @fabeschan 
Hi, Percy Liang, fabeschan .
We have the same problem when submitting ensemble model for SQuAD.
The total size of  ensemble models, LM and Glove is about 15G, and Could you also please increase our CodaLab disk quota  to 20G?
Our registered email is beidawl1992@126.com
 Thank you!

**Comment by sunmeng01** [comment]
@percyliang 
Hi, Percy Liang.
We are so sorry that we made a mistake, we used the above email to register  competitions.codalab not worksheets.codalab. We have registered worksheets.codalab with email beidawl1992@126.com
And we tried many ways to compress our models, but the total size of ensemble models was also 12G, Could you please increase our Codalab disk quota?

**Comment by s33rr** [comment]
@percyliang
Hi, Percy Liang. @fabeschan 

Because of quota, I cant run my dev-evaluate script.
Could you increase my Codalab disk quota to 20gb?

S3R / whitewest87@gmail.com

**Comment by percyliang** [comment]
We've standardized this process.  Please fill out the following form to
request more disk space:
https://goo.gl/forms/SFXd98mjZ3ZgAuNh1
