### ISSUE TITLE
Get codalab.stanford.edu instance running again

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2132]

**Comment by candicegjing** [comment]
Started codalab.stanford.edu instance and verfied all components are running fine. 
Take a closer look in database, and got the following results:
```
mysql> select COUNT(*) from bundle;
+----------+
| COUNT(*) |
+----------+
|    12898 |
+----------+
1 row in set (0.13 sec)

mysql> select COUNT(*) from user;
+----------+
| COUNT(*) |
+----------+
|       71 |
+----------+
1 row in set (0.00 sec)
```
@percyliang Is there anything else we want to add to this task?

**Comment by candicegjing** [comment]
Documented steps to deploy to `codalab.stanford.edu` at [here](https://github.com/codalab/deployment#deploy-to-codalabstanfordedu)
