### ISSUE TITLE
[USER ISSUE] Pasting strings followed by the space key in the web terminal would clear the command

### ISSUE THREAD

**Issue by hao-fang** [codalab/codalab-worksheets#2133]
**Describe the bug**
When I paste things to the web terminal, I need to press the left arrow first. Otherwise if I directly type space or other things, it will clear all the content.

**Codalab Information**
- *Your username*:
- *UUID of worksheet where problem occurred*:
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*; Chrome

**To Reproduce**
* Open the web terminal
* Paste a string to the terminal
* If you press "space", it will clear all the content.
* If you press the left arrow, it will be fine.

**Expected behavior**
Paste followed by a space or other keys should **not** clear the content.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by yuqijin** [comment]
This issue is going to close now since the bug no longer exists. If you have other questions, feel free to open another issue.
