### ISSUE TITLE
make file browser have less vertical spacing

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2134]
In the worksheets page the file browser under the bundle details has too much vertical spacing, which makes it annoying to view bundles with lots of files inside.  Instead match the spacing on the bundle page.

**Comment by yshen-google** [comment]
Hi @percyliang , just want to confirm with you whether I am looking at the right part.
Do you refer the file browser as the screenshot below?
<img width="769" alt="file_browser" src="https://user-images.githubusercontent.com/63320611/83956569-5e1d1d00-a814-11ea-93d2-d7ea9961bbad.png">
If so, which vertical spacing do you refer to? Is it the spacing between `FILES` and `.cache`, or is it the spacing within each folder, i.e. the top and bottom padding of `.cache`?

**Comment by percyliang** [comment]
I'm talking about the spacing between `.cache`, `stderr`, `stdout`.  It should be more like the spacing of the file browser on the bundle details page.
