### ISSUE TITLE
staged for long time

### ISSUE THREAD

**Issue by hello-deh** [codalab/codalab-worksheets#2137]
**Describe the bug**
I submit run task on codalab, but it staged for more than 40hours, Then I killed the bundle and retry, it still staged. 

**Codalab Information**
- *Your oppo.tensorlab*:
- *UUID of worksheet where problem occurred*: 0xb5ec515a19c54b68aab460041cbe6fd4
- *UUID of problem bundle (please don't delete)*: 0xcddcfb3d6b2e42df908c5516ac1350d1
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*; chrome

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by newstyn** [comment]
My issue is the same as yours,, its been 12 hours now,, and my bundles are still in staged, I thought its not a good idea to open two threads for the same issue, so i thought is should comment here too to make this issue more highlighted . I am also desperate as you are right now because i can see others people bundles running but mines is still in stage state

**Comment by candicegjing** [comment]
@hello-deh and @newstyn Sorry for the long waiting time. In our system, jobs are scheduled to run based on the order they are received. Currently, all of our workers are occupied with jobs. If you want to avoid the waiting time and speed up the process, we would encourage you to attach additional computing resources if there is any. Please refer to the documentation at [running your own worker](https://codalab-worksheets.readthedocs.io/en/latest/Execution/#running-your-own-worker)

**Comment by newstyn** [comment]
@candicegjing , thanks for your concern and reply. I was just wondering what if jobs are such that they run in a never ending loop. i mean, you can never know whether a program will halt or not. So is this the responsibility from the user end. implicitly i wanna know will my turn ever come or not :dagger :D

**Comment by candicegjing** [comment]
@newstyn Thanks for bringing up your concern! We do set limits on total running time per job. When the total running time of a job exceeds the limit, we will automatically kill the job. As I mentioned before, our jobs are scheduled to run **on the order they are received**, meaning your jobs will run once jobs ahead yours are finished. You can use this link [What's running in CodaLab?](https://worksheets.codalab.org/worksheets/0xa590fd1b68944a1a95c1c40c4931dc7b) to track your jobs' relative positions if that's something helpful. I hope this helps and please feel free to contact us if you have any other concerns.

**Comment by graykode** [comment]
I totally agree with this issue. I try to submit leaderboard but staged for 4 days... I hope this issue to be resolved.
