### ISSUE TITLE
Cursor goes to the wrong place after clicking "edit source"

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2140]
**Describe the bug**

https://worksheets.codalab.org/worksheets/0x18ec092a322049e59923927e403cd7d5

If I select the below cell and click "Edit source":

![image](https://user-images.githubusercontent.com/1689183/78820355-a1d6e000-79a5-11ea-8c90-389c6b046cd0.png)

My cursor goes to the right place:

![image](https://user-images.githubusercontent.com/1689183/78820385-b1562900-79a5-11ea-8ce6-d4abcb807a33.png)

But if I select the below cell and click "Edit source":

![image](https://user-images.githubusercontent.com/1689183/78820421-c3d06280-79a5-11ea-8f21-3c2c6cf6d60f.png)

My cursor goes to the wrong place.

![image](https://user-images.githubusercontent.com/1689183/78820436-cb900700-79a5-11ea-97fc-919bbd8cd396.png)

**Comment by yshen-google** [comment]
Hi @epicfaace I tried to reproduce the issue on a new worksheet since I don't have access to yours provided in the link, but in my worksheet the cursor is correctly placed to where it is selected. I am not able to reproduce this issue. Please feel free to reopen this issue if you still have this problem. Thanks.

**Comment by yshen-google** [comment]
I tried to reproduce the issue in the following way:

Put some random text,
on the next line, I put `% search .mine`.
Then on the next line, I put some random text again.

I selected the first random text and then `Edit Source`, cursor was correctly placed as expected. And then I highlighted the second random text and clicked `Edit Source`, the cursor was correctly moved to the second random text. Let me know if I should try it another way.

**Comment by yipenghe** [comment]
> I tried to reproduce the issue in the following way:
> 
> Put some random text,
> on the next line, I put `% search .mine`.
> Then on the next line, I put some random text again.
> 
> I selected the first random text and then `Edit Source`, cursor was correctly placed as expected. And then I highlighted the second random text and clicked `Edit Source`, the cursor was correctly moved to the second random text. Let me know if I should try it another way.

I think the issue was fixed along with another issue

**Comment by yshen-google** [comment]
> > I tried to reproduce the issue in the following way:
> > Put some random text,
> > on the next line, I put `% search .mine`.
> > Then on the next line, I put some random text again.
> > I selected the first random text and then `Edit Source`, cursor was correctly placed as expected. And then I highlighted the second random text and clicked `Edit Source`, the cursor was correctly moved to the second random text. Let me know if I should try it another way.
> 
> I think the issue was fixed along with another issue

Got it. Thanks @yipenghe for the confirmation.
