### ISSUE TITLE
CodaLab workers could be more robust to (temporary) network disconnections

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2150]
**Describe the bug**

I'm running several cl workers (think ~15), and when I logged in today, all my bundles were `worker_offline`. Checking the workers, I noticed that they all froze at `2020-04-11 05:06:16,786`.

Before, when this happens, I would have seen the "sleeping for 1 hour, help me" message. Now, even though there's no message, the process is still sleeping (I can't `Ctrl-C` out of it, need to go to htop and kill it and then restart). Ideally, it would reconnect to the server when it can and resume its checkins.

**To Reproduce**
Steps to reproduce the behavior :
1. Run a bunch of workers.
2. Wait for a network blip, or create one.

**Expected behavior**

The workers reconnect when they can.

**Comment by percyliang** [comment]
That message means some internal error happened corresponding to some CodaLab bug that needs to be fixed, which is why we're not automatically reconnecting (otherwise, we'd likely not fix the actual problem).  There's no error message / stack trace before that in the docker logs?

**Comment by nelson-liu** [comment]
Nope, there isn't—I expected there to be one too. Maybe something off with the logging level (the worker was run with `--verbose`)?

**Comment by percyliang** [comment]
Can you reproduce this easily?  I thought the workers should be generally robust to disruptions in network...

**Comment by nelson-liu** [comment]
This is fixed, I've seen them recover a few times now.
