### ISSUE TITLE
"not a gzip file" error

### ISSUE THREAD

**Issue by juliojj** [codalab/codalab-worksheets#216]
Dear all,

to reproduce the problem I am facing with worksheets, I created a testing worksheet (juliojj-test) and uploaded two datasets (training80_01 and training80_02, composed by several video files), and a testing script (link below)

https://worksheets.codalab.org/worksheets/0x61f291b312d947049a4d5daebf275bed/

Both datasets were downloaded from the First Impression copetition and work fine in my local computer. The problem is, when I run my testing script on both datasets, it works just with one of them (training80_02). When using the other one (training80_01) I receive the following error message: "not a gzip file". If I try to download both dataset bundles from the worksheets, the one which have failed have zero of size and I am not able to unzip it (it seems that the file is broken or something like that). However, the original zip file is ok in my local machine and I didn't receive any error message when uploading it to worksheet. Do you have any idea about how I could avoid this error? I tried to zip and upload the data in different ways, but it doesn't work. The stranger thing is that I am doing practically the same procedure on both cases and it just works in one of them. My apologies if I made any mistake.

thanks and best

**Comment by kashizui** [comment]
Hi juliojj, could you provide us access to your original dataset files somehow so we can investigate this issue? Thanks!

**Comment by kashizui** [comment]
I believe the problem is due to how we gzip our files: one of the filenames in your first dataset starts with a hyphen and might be causing problems. I am looking into how to fix this. Thanks for reporting this!

**Comment by juliojj** [comment]
Hi kashizui, if you still need, you can download the data from my dropbox:
https://www.dropbox.com/sh/v0v5cmfy9xg0hmg/AAD1aJn6RLDqqgI-Rr33ixFua?dl=0
thanks for your support

**Comment by kashizui** [comment]
We just deployed a fix for this to https://worksheets.codalab.org, please try your experiment again and let us know if you still have problems!

**Comment by juliojj** [comment]
Dear kashizui, it worked. Thanks for your very quick support.
best
