### ISSUE TITLE
Clean up frontend code & add documentation

### ISSUE THREAD

**Issue by yipenghe** [codalab/codalab-worksheets#2168]
We might want to revisit the frontend code and do some refactoring
Examples:
I would like to revisit the popup dialogs, there are several types of dialogsin the frontend, it would be better if we could get them all into the worksheetdialog component

The header component also contains quite a few sub components, and adding new features may require passing some information from Worksheet all the way to three or four level component down

Change var => let & const where appropriate

**Comment by percyliang** [comment]
I think this is subsumed by existing issues.
