### ISSUE TITLE
Focusing issue with the upload button

### ISSUE THREAD

**Issue by yipenghe** [codalab/codalab-worksheets#2170]
When you click on the upload button in the header, it opens up the upload menu. However, it auto focuses on the first menu item even if I'm not hovering on the menu. 
![Screenshot from 2020-04-15 23-52-49](https://user-images.githubusercontent.com/23012631/79423985-5b205180-7f74-11ea-95ed-daa280cc1de6.png)
When my mouse hovers around the second upload item, it adds shades to the item, but the first menu still has a blue "selected" color, which is confusing

![Screenshot from 2020-04-15 23-55-45](https://user-images.githubusercontent.com/23012631/79424211-aaff1880-7f74-11ea-8488-c07cff67b063.png)

The ideal behaviour would be to not auto-select the first menu item after clicking

**Comment by Levilian** [comment]
https://github.com/mui-org/material-ui/issues/5186 The multiple state seems quite common. It's indeed an UI problem.

**Comment by Levilian** [comment]
The temporary fix is to reduce the confusion on the user end by having the default item to be a placeholder with style `display: "none"`

**Comment by Levilian** [comment]
> The temporary fix is to reduce the confusion on the user end by having the default item to be a placeholder with style `display: "none"`

The issue with using `display: "none"` is that it makes the element inaccessible to screen readers and keyboard users. Therefore, we resort to the method described [here](https://css-tricks.com/places-its-tempting-to-use-display-none-but-dont) to manually make an invisible element.
