### ISSUE TITLE
Add precommit to GitHub Actions

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2176]
- Add flag (--check?) to doc generating script to fail if file isn’t up to date
- Run pre-commit in GitHub Actions
- Everyone just remember to run pre-commit.sh

**Comment by nelson-liu** [comment]
> Everyone just remember to run pre-commit.sh

Why not just turn this into a git hook?

**Comment by epicfaace** [comment]
pre-commit.sh runs a lot of things (such as pip install) which we wouldn't necessarily want to run before every commit. We already have a git hook for frontend formatting, and we might want to add the black formatting to the git hook as well.

**Comment by nelson-liu** [comment]
I've been using https://github.com/pre-commit/pre-commit for a few of my projects, and it's pretty nice—the first time you set up the hook, it installs whatever requirements it needs (e.g., black) in a venv (so you're not pip installing every time). Then, it sets up hooks to auto run all the checks every time you commit (I usually have flake8 and black on my projects).

**Comment by nelson-liu** [comment]
Oh wait, it's already set up for this repo, oops (but just with black).

**Comment by epicfaace** [comment]
@yiboliu are you interested in working on this? It's kind of like a follow-up to #2674

**Comment by yiboliu** [comment]
sure. I'll talk to you when I have finished the current task.

**Comment by yiboliu** [comment]
PR closed
