### ISSUE TITLE
Missing remote column after v0.5.12 deployement

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#2180]
In [What's running on CodaLab?](https://worksheets.codalab.org/worksheets/0xa590fd1b68944a1a95c1c40c4931dc7b), we used to have a column that displays information about which worker the current bundle runs on. Now after `v0.5.12` deployment, this column disappeared as follows:

<img width="1367" alt="Screen Shot 2020-04-16 at 8 04 28 PM" src="https://user-images.githubusercontent.com/1483372/79527898-9591f900-801d-11ea-8421-33f9da87068c.png">

This ticket is to investigate this issue and add that column back.

**Comment by nelson-liu** [comment]
the name also wasn't there before
