### ISSUE TITLE
[FEATURE REQUEST] cl search host_worksheet should take worksheet names

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2188]
**Is your feature request related to a problem? Please describe.**

Currently, `cl search host_worksheet=X` only works if `X` is a uuid. It'd be nice if we could also use a worksheet name here (assuming there is only 1 worksheet with the name).

**Comment by Levilian** [comment]
Great suggestion! Search by worksheet name will be available on the front end. We should add that soon to the CLI.

**Comment by percyliang** [comment]
I think @nelson-liu is talking not searching for worksheets by name but rather searching for bundles that are on some worksheet by name.

@nelson-liu , can you just do `cl search ... host_worksheet=$(cl wsearch ... -u)`?

**Comment by nelson-liu** [comment]
> @nelson-liu , can you just do cl search ... host_worksheet=$(cl wsearch ... -u)?


Oops yes I can, thanks! That was exactly what I was looking for, sorry for the noise.
