### ISSUE TITLE
continuous-integration/travis-ci stuck on Expected — Waiting for status to be reported

### ISSUE THREAD

**Issue by yshen-google** [codalab/codalab-worksheets#2191]
It seems continuous-integration/travis-ci is stuck on "Expected — Waiting for status to be reported" without any update. Shall we follow https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories and https://github.community/t5/GitHub-Actions/GitHub-Actions-Pull-requests-always-include-some-outdated-checks/m-p/31444#M794 to resolve this issue?

**Comment by epicfaace** [comment]
This appears to be working for certain PRs, but not for others. Are you sure it's due to the problem linked above?

**Comment by yshen-google** [comment]
Hi Ashwin, I am not completely sure it's due to the problem in the links, though they are the top 2 results I found. Yeah, I agree with you. Based on the observation, it seems some PRs have this problem but not others.

**Comment by nelson-liu** [comment]
Seems like the PRs coming in from forks aren't being run on travis, while the PRs created from branches of `codalab/codalab-worksheets` are being run fine.

**Comment by yshen-google** [comment]
Yup, were there any changes made to travis-ci? It seems in the past (not long time ago), travis-ci could still run on PRs originated from a forked repo.

**Comment by nelson-liu** [comment]
can someone with write access to the repo go to https://travis-ci.org/github/codalab/codalab-worksheets/settings and make sure the "Build pushed pull requests" button is on?

<img width="1439" alt="Screen Shot 2020-04-22 at 6 42 52 PM" src="https://user-images.githubusercontent.com/7272031/80049971-3f173580-84c9-11ea-8641-a043f544e89f.png">

**Comment by candicegjing** [comment]
I just updated the setting as follows:
<img width="935" alt="Screen Shot 2020-04-24 at 10 20 42 AM" src="https://user-images.githubusercontent.com/1483372/80239540-464b5a00-8615-11ea-89ca-2d9a654fbf76.png">
@yshen-google  and @nelson-liu Is this what we want?

**Comment by percyliang** [comment]
No longer using travis.
