### ISSUE TITLE
Suggestions new features for 'What's Running on CodaLab?' Page

### ISSUE THREAD

**Issue by graykode** [codalab/codalab-worksheets#2194]
I feel uncomfortable not knowing when the `staged` state changes to the `running` state in [What's running on CodaLab?](https://worksheets.codalab.org/worksheets/0xa590fd1b68944a1a95c1c40c4931dc7b/) So, I have to wait endlessly.
On this page, the private permission bundle is blocked by the row, but more than that, command, and owner are hidden, but I wish I could see the row.
In addition, it would be good to know the amount of GPU and memory currently in use and the whole amount. Thanks.

**Comment by candicegjing** [comment]
@graykode Thanks for suggesting this! We are working on providing more information about `staged` jobs to users. Will let you know once we have any updates.

**Comment by graykode** [comment]
@candicegjing 
Also If there are more than 2 `requests_cpus` and less than 6, it will change to a `running` state but I can't expect when it will be changed. So, I'd like to add the currently available amount of CPU.

**Comment by candicegjing** [comment]
@graykode Thank you very much for your suggestions! Just to clarify, a bundle changed its status from `staged` to `running` will completely depend on whether we can find a worker that has enough computing resources (CPUs, GPUs and memory) requested by the bundle. So more than `2` requested CPUs are not required for the change of status. We will try to see what we can do to provide more information to users.

**Comment by percyliang** [comment]
Should be handled by #2234 once that's in.
