### ISSUE TITLE
Support GPU isolation

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#220]
If we run a custom worker from an environment where $CUDA_VISIBLE_DEVICES is set, we should respect that and only allow the docker container to use that GPU.

**Comment by kashizui** [comment]
https://github.com/NVIDIA/nvidia-docker/wiki/GPU-isolation

**Comment by percyliang** [comment]
In docker, perhaps specify which of /dev/nvidia* you want.

**Comment by kashizui** [comment]
@percyliang To clarify, do we want:

- allow the person who is running the worker to specify what GPUs that worker is allowed to access
- or allow CodaLab users to specify which GPUs to use in a run bundle

or both?

**Comment by percyliang** [comment]
I think we definitely need the former, since other people might be using
the machine who aren't on CodaLab.  Let's not worry about the latter for
now.

**Comment by kashizui** [comment]
Should we just read from $CUDA_VISIBLE_DEVICES as we originally discussed, or add a command line argument like `worker.sh --cuda-visible-devices=0,1` ?

**Comment by percyliang** [comment]
I think $CUDA_VISIBLE_DEVICES is sufficient, since that's standard.
