### ISSUE TITLE
Aggregate search queries are rendered twice on the dashboard

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2205]
Some contents are rendered twice on the dashboard:
https://worksheets.codalab.org/worksheets/0xb843335f02a9443995db2013fbe2e7f4/
![Screenshot from 2020-04-23 21-56-18](https://user-images.githubusercontent.com/435384/80176404-53ccf980-85ad-11ea-991a-09971c6efe6b.png)
Maybe this has something to do with the recent changes for async loading? @epicfaace

**Comment by epicfaace** [comment]
Minimal reproduction: https://worksheets.codalab.org/worksheets/0x3d0fea197211492b9bc355d6c3f1c677

This happens when we have code such as 

```
## **Basic statistics**
Number of bundles owned by me:
% search .mine .count
```

Essentially, when we use `.count` or `.sum` in a search directive, it returns only a single value, and the async loading doesn't handle this properly.

**Comment by yipenghe** [comment]
I think we want it to be on the same block
for example:
a
b

would appear as one block, unless you add # a to mark it as a title
