### ISSUE TITLE
Unexpected error while parsing line 4, please fix the line in source

### ISSUE THREAD

**Issue by hello-deh** [codalab/codalab-worksheets#2213]
When I delete some bundles in my worksheet on website, error occurs:
"Unexpected error while parsing line 4, please fix the line in source"
my worksheet is https://worksheets.codalab.org/worksheets/0xb5ec515a19c54b68aab460041cbe6fd4
OS system: windows 10
web browser: chrome

**Comment by yipenghe** [comment]
The message seems to have a off-by-one error, the problem is actually on line 3 in the source
removing this [make predictions-ALBert -- /predictions.json]{0xafb0ff35728e4949b8b2a2abc6c089ab} would help render the rest.
Can you tell us more about the operations you performed?

**Comment by hello-deh** [comment]
I force delete "run-predictions" bundle "src" bundle and "model_save" boundle on web interface at the same time, then this error occured.

**Comment by yipenghe** [comment]
Did the three bundles have anything to do with 0xafb0ff35728e4949b8b2a2abc6c089ab? (the bundle I mentioned above)

**Comment by hello-deh** [comment]
> Did the three bundles have anything to do with 0xafb0ff35728e4949b8b2a2abc6c089ab? (the bundle I mentioned above)

yes

**Comment by hello-deh** [comment]
hello, the problem still exists when reopen the website

**Comment by yipenghe** [comment]
> hello, the problem still exists when reopen the website

For now can you go to edit source and remove the line [make ...] which is causing the parsing error? Since you force deleted some dependencies, there might be some error we didn't check for. We will try to fix it in the next release

**Comment by hello-deh** [comment]
Thank you very much, It works!
