### ISSUE TITLE
Enable editing any bundle field through the CLI

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2217]
**Is your feature request related to a problem? Please describe.**

Right now, `cl edit` on the CLI only allows you to edit the name, description, and tags. However, on the web interface, you can change arbitrary fields on bundles (e.g., `request_memory`, `request_network`, etc). It'd be nice to be able to do this on the CLI as well.

**Describe the solution you'd like**

The ability to do `cl edit <insert any field here> <insert your value here>`

**Comment by candicegjing** [comment]
@nelson-liu What are the most needed fields in your mind? For instance, the fields in metadata list?

**Comment by candicegjing** [comment]
@nelson-liu When you do `cl edit <uuid>` from CLI, it will pop up a window that lists all of the metadata fields that can be modified. Do you mean to update directly from CLI without editing from this pop-up window?

**Comment by nelson-liu** [comment]
yes, I'd like to able to programmatically edit from a script, and it's hard to make the pop-up editor scale. This isn't a huge priority, though, since I can write one-off scripts to edit particular fields.

**Comment by percyliang** [comment]
How about `cl edit <bundle> -f <key> <value>`?

**Comment by nelson-liu** [comment]
that seems good to me, makes sense for the interface to be consistent with `cl info`.

**Comment by yshen-google** [comment]
If the user fetches an unknown field/key, an error message saying "unknown field" shall be sufficient?
