### ISSUE TITLE
[Errno 28] No space left on device

### ISSUE THREAD

**Issue by ppasupat** [codalab/codalab-worksheets#223]
When I created a run bundle with large dependencies (code + dataset), the bundle failed with the failure message "[Errno 28] No space left on device". One example is https://worksheets.codalab.org/bundles/0x5eb338ffbf434af3a858e33246bdd8ab/

Run bundles with smaller dependencies successfully ran.

My remaining disk space quota is at least 2.5g, which should be able to store the dependencies of that run (less than 1g combined).

**Comment by percyliang** [comment]
This is because the worker ran out of disk space.

This is mainly because of all the docker images that people have been
using.  I went ahead and cleared out them, so you should be able to run
jobs again, but we should definitely have a more automatic way of removing
unused docker containers.

**Comment by ppasupat** [comment]
Thank you, @percyliang!

**Comment by schmmd** [comment]
@percyliang this is happening again.

I may be contributing to this with multiple versions of similar docker images.  CodaLab would not pull updates to docker images, so I created new tags.  I expect that most of the layers would be shared, but perhaps not.

![image](https://user-images.githubusercontent.com/954798/30553296-ae53ba86-9c55-11e7-87ac-634a1b0d1da2.png)

**Comment by percyliang** [comment]
We have a known bug that we're working on fixing (
https://github.com/codalab/codalab-worksheets/issues/351).  In the
meantime, please try again - disk space should be cleared up now.

**Comment by diogoff** [comment]
It's probably my fault, since I have been uploading some large submission files, but I had no clue it could come to this:

```
Traceback (most recent call last):
  File "/worker/worker.py", line 299, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 160, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 120, in get_bundle
    z.extractall(bundle_path)
  File "/usr/local/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1084, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/local/lib/python2.7/shutil.py", line 66, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device
```

I'm currently unable to submit to [TrackML Throughput Phase](https://competitions.codalab.org/competitions/20112).

Is it possible to delete my previous Failed submissions? Thanks.

I have also posted this in the [Forum](https://competitions.codalab.org/forums/16834/2894/).
