### ISSUE TITLE
Sort keys should not be duplicated for the same bundle items

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2232]
When we have bundles like

```
[]{a}
[]{a}
[]{b}
[]{a}
```

We get the following sort keys: `[132432, 132432, 132431, 132432]`

This is not good, because this makes it impossible to insert an item right after the first row in a table (even with #2190 merged in) -- instead, because all bundle rows referring to "a" have the same sort keys, it will be inserted at the end of the table.

To fix this, we should change the logic for `item_sort_key`:

https://github.com/codalab/codalab-worksheets/blob/5b9390b5ecdead2ef736c4e43dc94037f2aeb161/codalab/objects/worksheet.py#L20-L21

We should also do some sort of migration (either a one-time migration or a dynamic migration upon worksheet load) that would correct these duplicate sort keys for existing worksheets.

**Comment by yipenghe** [comment]
ids also should be fixed along, so the replace item can work correctly for deletion
