### ISSUE TITLE
[FEATURE REQUEST] Shorter URLs for inclusion in papers

### ISSUE THREAD

**Issue by chrisdonahue** [codalab/codalab-worksheets#2233]
**Is your feature request related to a problem? Please describe.**

The URLs for worksheets are quite long (in terms of number of characters) and wrap to 2 or more lines when included inline. This is especially problematic in two-column LaTeX formats.

**Describe the solution you'd like**

It would be great if we could generate shorter URLs for certain worksheets and perhaps simultaneously improve the user-friendliness / author optics.

Suggestion:

`https://worksheets.codalab.org/worksheets/0x0000000000000000000000000000000`
->
`https://codalab.org/pliang/projectname`

**Describe alternatives you've considered**

I've considered using external websites like bit.ly to shorten URLs, but I'm not convinced of their long-term preservation.

**Comment by percyliang** [comment]
Currently you can already do `https://worksheets.codalab.org/worksheets/?name=worksheetname`.  But you can change the worksheet name, which makes the URLs not super stable...that's why the uuid's are there.  There are three axes here: (i) stability, (ii) interpretability, and (iii) brevity.  We are maximizing (i) right now.  (ii) you can get by just `?name=`.  For (iii) we can make CodaLab's own URL shortener, but it seems redundant with `bit.ly`.

**Comment by chrisdonahue** [comment]
Neither `?name=` nor `bit.ly` have all three desiderata though (`?name=` lacks brevity and `bit.ly` lacks stability). While I'd say that rolling a custom shortening system is pretty low priority, I do think it's worth considering in the long term as a researcher's proclivity towards linking to CodaLab from their paper is likely a function of all three axes.

**Comment by percyliang** [comment]
So how about `https://codalab.org/w/0x0000000000000000000000000000000` or ``https://codalab.org/w/worksheet-name`?

**Comment by chrisdonahue** [comment]
That would be perfect!

**Comment by chrisdonahue** [comment]
I'm not sure if you meant that both could be supported (mimicking the current interchangeability between `?name=` and `0x0000...`) but if it's one or the other my preference would be for the latter.

**Comment by percyliang** [comment]
Not prioritizing for now.
