### ISSUE TITLE
Long commands take up too much space on a worksheet

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2238]
This particular [bundle](https://worksheets.codalab.org/bundles/0x84146537cb724e16a9601c939458430a) with a super long command takes up too much space on the worksheet and the user has to scroll endlessly. We should truncate at some point. 

![Screen Shot 2020-05-02 at 10 17 20 AM](https://user-images.githubusercontent.com/16793796/80870942-77074100-8c5e-11ea-940a-62d6db83c6ed.png)

**Comment by percyliang** [comment]
I assume that is the `summary` field, which I think we should just truncate on the backend.  In general, users can define custom schemas to truncate on the frontend.

**Comment by yshen-google** [comment]
> I assume that is the `summary` field, which I think we should just truncate on the backend. In general, users can define custom schemas to truncate on the frontend.

Right, according to [the markdown reference](https://codalab-worksheets.readthedocs.io/en/latest/Worksheet-Markdown/#schemas), users can truncate fields by specifying number of characters, i.e. `[0:8]`. So in this case, I think we want to return limited number of characters from server response (json object)? What's the magic number for number of characters to be returned by server? Any opinion or suggestion?

**Comment by percyliang** [comment]
This should be one in the definition of the default schema for `summary` (see how this is done for `uuid`).  As for the max length, maybe 1024?
