### ISSUE TITLE
anaconda docker image doesn't work

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#224]
This command just returns an exit code of 127 without an error message:

```
cl run --request-docker-image continuumio/anaconda3 ls
```

Docker file looks normal otherwise: https://github.com/ContinuumIO/docker-images/blob/master/anaconda3/Dockerfile

and doing `docker run` loads it just fine.

**Comment by percyliang** [comment]
Other image that doesn't work: ekazakov/python-opencv

**Comment by kashizui** [comment]
Fixed
