### ISSUE TITLE
[USER ISSUE] - cl-competitiond fails if any one of the submission bundles are not accessible

### ISSUE THREAD

**Issue by OrthoDex** [codalab/codalab-worksheets#2242]
**Describe the bug**
The cl-competitiond script fails during a run if at least one run bundle has a private dependency. Based on the fetch order, the script either fails at the first mimic or runs a few bundles and then fails.

**Codalab Information**
- *Your username*: imalhi
- *UUID of worksheet where problem occurred*: local cli
- *Error message received from Codalab (if applicable)*: 404 Bundle not found
 - *OS (if on CLI)*: Mac Os, Ubuntu 18
 - *Codalab CLI Version (if on CLI)*: 0.5.13
 - *Browser (if on Web)* : N/A

**To Reproduce**
Steps to reproduce the behavior :
1. Create a competition, or use an existing one
2. Make the src bundle of a submission bundle's upstream run bundle private.
3. Run cl-competitiond for the competition
4.  Script fails with a 404 error

**Expected behavior**
The script should skip the 404'd bundle and run the rest.

**Screenshots**
N/A

**Additional context**
I have a semi-working fix that uses a try-catch to ignore 404 errors when looping through submissions.

**Comment by teetone** [comment]
@OrthoDex I would expect it to error, since the user doesn't have access to a dependency. Can you explain a bit more on why you would expect the error to be caught and then ignored?

**Comment by OrthoDex** [comment]
@teetone I would expect evaluation bundles to run on the submitted entries that I have access to. If there's an entry that has a private dependency, the evaluation doesn't run on any of the other submissions. Right now, it's a one vs all setup where none of the other (valid) submissions (that I have access to) can be evaluated because at least 1 of the submissions is private.

**Comment by percyliang** [comment]
@robinjia Have you run into any of these issues?

**Comment by robinjia** [comment]
Yes I have added a try/catch block to competitiond.py so it can just skip bad submissions. I could send a PR, I forget why this was never merged.

**Comment by robinjia** [comment]
Also cc @candicegjing because we talked about this change before, don't remember if there was a good reason to not include this change officially.

**Comment by epicfaace** [comment]
> Yes I have added a try/catch block to competitiond.py so it can just skip bad submissions. I could send a PR, I forget why this was never merged.

Yes, this sounds like the right solution and would also solve https://github.com/codalab/codalab-worksheets/issues/3705 (which is, I think, the same issue). Where did you add the try/catch block? Could you share, or make a PR?
