### ISSUE TITLE
[FEATURE REQUEST] download a folder with `cl download`

### ISSUE THREAD

**Issue by hao-fang** [codalab/codalab-worksheets#2245]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to download a folder in a bundle. But currently `cl download` only works for files.

**Describe the solution you'd like**
`cl download` should work with a folder, e.g., `cl download BUNDLE_ID/folder_name`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by teetone** [comment]
This should already be working. If it's not, it's a bug. I just tried it and it works for me. Can you add a link to your bundle and the download command you ran on it?

**Comment by hao-fang** [comment]
Ah my bad. It indeed works on the public CodaLab instance.
(I got the error on our internal CodaLab instance probably our version is behind the latest one.)
