### ISSUE TITLE
Cannot read property 'refs' of undefined

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2248]
Happened randomly when running locally.

![image](https://user-images.githubusercontent.com/1689183/81241140-78769780-8fd7-11ea-9a01-5b3e07bbac79.png)

**Comment by teetone** [comment]
@epicfaace Do you know if this happens in `prod` or `dev`? I've never seen this before.

**Comment by yipenghe** [comment]
> @epicfaace Do you know if this happens in `prod` or `dev`? I've never seen this before.

I think react  suppresses such errors in prod build

**Comment by percyliang** [comment]
Does this still happen?

**Comment by epicfaace** [comment]
It still happens occasionally.

**Comment by yipenghe** [comment]
This seems to happen when: edit source, click outside the source editor and then save, not sure how to fix this yet
