### ISSUE TITLE
Slim down docker images

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2251]
- We don't need to package node_modules in the frontend Docker container -- it just makes the container way bigger than it needs to be, as the dependencies are already included in the bundled JS. The container is nearly 500 MB -- see https://hub.docker.com/r/codalab/frontend/tags

- We can also slim down the backend images -- worker, server, and default-gpu/default-cpu (around 5 GB)

**Comment by percyliang** [comment]
You did this, right?

**Comment by epicfaace** [comment]
Fixed by #2604.
