### ISSUE TITLE
[USER ISSUE] Failing to setup my own GPU worker

### ISSUE THREAD

**Issue by MFajcik** [codalab/codalab-worksheets#2255]
**Describe the bug**
Despite installing `nvidia-docker` successfully, I fail to run `cl-worker` with GPU support. I follow the official docs https://codalab-worksheets.readthedocs.io/en/latest/Execution/#setting-up-workers-to-use-gpus
The public GPUs are hopelessly full these days and I am unable to evaluate my model (staged "forever") :(.

**Codalab Information**
- *Your username*: ifajcik
- *OS (if on CLI)*: Ubuntu 18.04
- *Codalab CLI Version (if on CLI)*: 0.5.13
- *GPU*: 2080Ti 12GB
- *Driver Version*: 440.64      
- *CUDA Version*: 10.2 

**To Reproduce**
Steps to reproduce the behavior :
1. Install GPU driver
2. Install latest nvidia docker, (version 19.03.8 at the time of reporting)
3. Check that docker works with `docker run --gpus all nvidia/cuda:10.0-base nvidia-smi` (drawn from official docs)

> $ docker run --gpus all nvidia/cuda:10.0-base nvidia-smi
> Sat May  9 08:13:05 2020
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  GeForce RTX 208...  Off  | 00000000:01:00.0 Off |                  N/A |
> | 39%   43C    P0    42W / 260W |      0MiB / 11016MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+

3. Run worker as `cl-worker --verbose --tag pcf_worker`

> Username: ifajcik
> Password:
> 2020-05-09 10:15:52,765 Loaded 0 dependencies, 0 paths from cache.
> 2020-05-09 10:15:52,800 http://localhost:None "GET /v1.35/version HTTP/1.1" 200 860
> 2020-05-09 10:15:52,801 Looking for auth config
> 2020-05-09 10:15:52,801 Looking for auth entry for 'docker.io'
> 2020-05-09 10:15:52,801 Found 'https://index.docker.io/v1/'
> 2020-05-09 10:15:52,801 Found auth config
> 2020-05-09 10:15:54,272 http://localhost:None "POST /v1.35/images/create?tag=9.0-cudnn7-devel-ubuntu16.04&fromImage=nvidia%2Fcuda HTTP/1.1" 200 None
> 2020-05-09 10:15:54,280 http://localhost:None "GET /v1.35/images/nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04/json HTTP/1.1" 200 None
> 2020-05-09 10:15:54,286 http://localhost:None "POST /v1.35/containers/create HTTP/1.1" 400 47
> **2020-05-09 10:15:54,286 Cannot initialize NVIDIA runtime, no GPU support: Problem getting NVIDIA devices: 400 Client Error: Bad Request ("Unknown runtime specified nvidia")**
> 2020-05-09 10:15:54,287 Trying paths: ['/home/ifajcik/.docker/config.json', '/home/ifajcik/.dockercfg']
> 2020-05-09 10:15:54,287 Found file at path: /home/ifajcik/.docker/config.json
> 2020-05-09 10:15:54,287 Found 'auths' section
> 2020-05-09 10:15:54,287 Found entry (registry='https://index.docker.io/v1/', username='ifajcik')
> 2020-05-09 10:15:54,287 Trying paths: ['/home/ifajcik/.docker/config.json', '/home/ifajcik/.dockercfg']
> 2020-05-09 10:15:54,287 Found file at path: /home/ifajcik/.docker/config.json
> 2020-05-09 10:15:54,288 Found 'auths' section
> 2020-05-09 10:15:54,288 Found entry (registry='https://index.docker.io/v1/', username='ifajcik')
> 2020-05-09 10:15:54,288 Creating docker network codalab_worker_network_general
> 2020-05-09 10:15:54,391 http://localhost:None "POST /v1.35/networks/create HTTP/1.1" 201 87
> 2020-05-09 10:15:54,393 http://localhost:None "GET /v1.35/networks/7b65a00720f7993697f37f7cbb61195e157d819a7e9785524d33a1a10ee9d8ed HTTP/1.1" 200 458
> 2020-05-09 10:15:54,394 Creating docker network codalab_worker_network_ext
> 2020-05-09 10:15:54,564 http://localhost:None "POST /v1.35/networks/create HTTP/1.1" 201 87
> 2020-05-09 10:15:54,567 http://localhost:None "GET /v1.35/networks/2f6f230cfbc6d273bdc326f2fd27642db5f2326a7af178e72c7dd0549f42f60f HTTP/1.1" 200 455
> 2020-05-09 10:15:54,568 Creating docker network codalab_worker_network_int
> 2020-05-09 10:15:54,697 http://localhost:None "POST /v1.35/networks/create HTTP/1.1" 201 87
> 2020-05-09 10:15:54,700 http://localhost:None "GET /v1.35/networks/bb5255ac18fdf0052337652bf5b1eaec0817bba4104fcd0ed1d84f05c4b2a222 HTTP/1.1" 200 454
> 2020-05-09 10:15:54,700 Worker started!
> 2020-05-09 10:15:54,700 Starting docker image manager
> 2020-05-09 10:15:54,700 Starting local dependency manager
> 2020-05-09 10:15:58,278 Connected! Successful check in!

**Expected behavior**
GPU support should work

**Additional context**
Is there a possibility of getting more debugging information? I have no idea what is failing currently. Docker works, I tried to create a symlink `/usr/bin/nvidia-docker` linked to docker executable `/usr/bin/docker`, so it is named like older versions, but with no apparent success.

**Comment by nelson-liu** [comment]
see https://github.com/codalab/codalab-worksheets/issues/2109#issuecomment-604670889 . The docker-py library that codalab depends on doesn't support the `--gpus` docker flag yet.

I've heard that this also works: https://github.com/NVIDIA/nvidia-docker/issues/857#issuecomment-439586831

**Comment by MFajcik** [comment]
Thanks, following [#2109 (comment)](https://github.com/codalab/codalab-worksheets/issues/2109#issuecomment-604670889) resolved the issue :).

> see [#2109 (comment)](https://github.com/codalab/codalab-worksheets/issues/2109#issuecomment-604670889) . The docker-py library that codalab depends on doesn't support the `--gpus` docker flag yet.
> 
> I've heard that this also works: [NVIDIA/nvidia-docker#857 (comment)](https://github.com/NVIDIA/nvidia-docker/issues/857#issuecomment-439586831)
