### ISSUE TITLE
Possible race condition in codalab bundle manager

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2256]
**Describe the bug**

Sometimes, I see runs that don't have `request_priority` set landing on nodes, while almost-identical (metadata is the same, the only thing that differs is a single dependency) bundles that _have_ `request_priority` set are not run. I have a feeling that this might be due to a race condition in https://github.com/codalab/codalab-worksheets/blob/master/codalab/server/bundle_manager.py#L367-L386 , but I'm not entirely sure.

Basically, I think the issue lies in the fact that worker resources for the current user / the public workers are updated on-demand when the bundle is about to be run. I could imagine a scenario where, in the middle of looping through all the staged run bundles (which are already sorted into the order that they should be run), a codalab worker frees up. So, the code thinks that the worker can take the bundle, and starts the bundle on the worker. However, there are bundles that were earlier in `staged_bundles_to_run` that have now being skipped over as a result.

**Expected behavior**
The ordering of the bundles as stored in `staged_bundles_to_run` is always respected.

**Comment by candicegjing** [comment]
@nelson-liu Just want to have a better understanding of this issue: does this happen when there are two bundles with similar resource requirements, one has `request_priority` set and another one doesn't, and for some reasons, the one without `request_priority` set gets to run earlier than the one does?

**Comment by nelson-liu** [comment]
@candicegjing yes, exactly.

**Comment by nelson-liu** [comment]
In fact, the resource requirements are the exact same.
