### ISSUE TITLE
uuid doesn't link to bundle page when it's not the first column in the schema

### ISSUE THREAD

**Issue by yipenghe** [codalab/codalab-worksheets#2269]
![Screenshot from 2020-05-13 17-31-46](https://user-images.githubusercontent.com/23012631/81879450-b3308080-953f-11ea-93cc-99d73dac9094.png)

**Comment by percyliang** [comment]
I think there's nothing special about uuids...I think the intended logic is just to have the first column link to the bundle row, since the link is more a function of the row rather than a particular cell.
