### ISSUE TITLE
now. cn't access codalab sheet

### ISSUE THREAD

**Issue by HansolHyewon** [codalab/codalab-worksheets#2280]
**Describe the bug**

**Codalab Information**
i don't access worksheet
![image](https://user-images.githubusercontent.com/45479160/82280284-7f36de80-99c9-11ea-9617-4c39f1066d09.png)

**To Reproduce**
Steps to reproduce the behavior :
1. Go to 'https://codalab.org/'
2. Click on 'worksheets'
3. I could not get a response.

**Comment by shaonan1993** [comment]
me too

**Comment by epicfaace** [comment]
We are facing some Azure issues and CodaLab is down for now -- will let you know when we have an ETA for when the issues will be resolved.

**Comment by vzhong** [comment]
Hi @epicfaace do you anticipate data loss upon recovery? We're attempting official evaluations for EMNLP, which is in less than two weeks, and would like to know if we should make contingency plans in case intermediate bundles and results are lost.

**Comment by percyliang** [comment]
There should be no data loss.  We are working to bring things back ASAP.  Apologies for the unexpected and rather unusual downtime.

**Comment by vzhong** [comment]
Thanks @percyliang ! Seems to be back up.
