### ISSUE TITLE
Connect AWS batch runners to a codalab instance in a VPN

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2286]
Use case: we have a stanford private codalab instance that needs to communicate with AWS Batch workers.

Look at these links:
https://medium.com/@nZenitram/connecting-an-aws-vpc-to-your-vpn-from-the-cloud-to-the-colo-ed1f2985ccf1

https://uit.stanford.edu/sites/default/files/2019/06/27/AWS_VPC_EndUserGuide_0619c.pdf

**Comment by nelson-liu** [comment]
is anyone working on this? I can tick the necessary boxes in AWS, as long as i have the vpc and tunnel interface networks from UIT. I can also reach out to request those, if no one has done so yet?

**Comment by percyliang** [comment]
Deciding against VPN, closing in favor of #2547 .
