### ISSUE TITLE
Non-final bundles appear as invalid in dest worksheet after wadd

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2294]
When using `wadd` across instances, some bundles appear as invalid:

<img width="1366" alt="Screen Shot 2020-05-22 at 5 09 32 PM" src="https://user-images.githubusercontent.com/7272031/82720088-21262780-9c65-11ea-9591-4be16b3a9bad.png">

Examining more, it's exactly the bundles in nonfinal states.

<img width="1416" alt="Screen Shot 2020-05-22 at 5 10 01 PM" src="https://user-images.githubusercontent.com/7272031/82720079-15d2fc00-9c65-11ea-8f57-9ee2c92387c3.png">

I guess this is because `wadd` saves all of the bundles in the source to the dest, even though not all of them eventually get copied:

https://github.com/codalab/codalab-worksheets/blob/master/codalab/lib/bundle_cli.py#L3345-L3352

Removing this chunk (and setting `add_to_worksheet=True` in `self.copy_bundle`) would fix this issue, but then the `replace` parameter wouldn't work...

**Comment by candicegjing** [comment]
Yes, in the copy step, `wadd` ignores bundles in non-terminal states. The `staged` state is one of them. Just to clarify the use cases: 
1. do we want to be able to `wadd` bundles in the `staged` state?
1. do we want to be able to `wadd` bundles in other non-terminal states [preparing, running, etc]?

**Comment by nelson-liu** [comment]
I think the current behavior is fine (only copy stuff in terminal states). I just don't like that it pollutes the destination worksheet markdown (maybe there are also extraneous objects created in the backend, I'm not sure of that).

**Comment by candicegjing** [comment]
That's true. I am also wondering for those bundles in the `staged` state, maybe we should copy their metadata over, instead of marking them as `invalid`?

**Comment by nelson-liu** [comment]
> That's true. I am also wondering for those bundles in the staged state, maybe we should copy their metadata over, instead of marking them as invalid?

Hm, but it'd be inaccurate to mark them as "staged" on the destination instance right? Since they'll never be run? (I actually am not sure how the bundle manager handles this, maybe they will be run if their state is marked as staged)

**Comment by candicegjing** [comment]
> > That's true. I am also wondering for those bundles in the staged state, maybe we should copy their metadata over, instead of marking them as invalid?
> 
> Hm, but it'd be inaccurate to mark them as "staged" on the destination instance right? Since they'll never be run? (I actually am not sure how the bundle manager handles this, maybe they will be run if their state is marked as staged)

Yeah, I think a bundle in the `staged` state will eventually get scheduled to run once all of its dependencies are ready, so it's possible.
For those bundles in the `invalid` state when they copied over, do we want to not copy them at all? Or do we want to mark them with something else?

**Comment by nelson-liu** [comment]
I think just not copying would be the safe thing for now?

**Comment by candicegjing** [comment]
> I think just not copying would be the safe thing for now?

Sounds good! Will avoid copying bundles that are not in final states for now.
