### ISSUE TITLE
Environment variables in run commands are sometimes parsed as LaTeX in worksheets

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2296]
If I refresh, sometimes the text is displayed properly, sometimes it isn't:

<img width="1420" alt="Screen Shot 2020-05-25 at 10 43 40 AM" src="https://user-images.githubusercontent.com/7272031/82834021-acc1d300-9e74-11ea-896e-3b0c160adfb5.png">

Link to ws: https://worksheets.codalab.org/worksheets/0x6c26647dad70404eb6ea6a01ed8b6a99

**Comment by percyliang** [comment]
Dup of #1108
