### ISSUE TITLE
Command line text clipped on Worksheets page

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#23]
<a href="https://github.com/ErickWa"><img src="https://avatars.githubusercontent.com/u/4361560?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ErickWa](https://github.com/ErickWa)**
_Monday Nov 02, 2015 at 05:13 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1375_

----

![image](https://cloud.githubusercontent.com/assets/4361560/10874654/fa305c0c-80dc-11e5-8789-fbbc4b6e12cb.png)

_Observed behavior_: First line of text in Worksheet Command Prompt is clipped horizontally, making text difficult to read.

_Expected behavior_: First line of text is not clipped and easily readable.

_Environment_: reproducible in both Chrome and Edge.

**Comment by percyliang** [comment]
Fixed.
