### ISSUE TITLE
bundle state in table not updating

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2302]
The state in the bundle table stays in 'created' even though the bundle details page updates.
![Screenshot from 2020-05-26 21-03-39](https://user-images.githubusercontent.com/435384/82976631-78ddcf00-9f94-11ea-88b7-cb751befd60b.png)

**Comment by percyliang** [comment]
@yipenghe I think you fixed this.  Did this somehow get unfixed?

**Comment by yipenghe** [comment]
I think I fixed the one in bundle detail, but didn't fix/notice the bundle row one

**Comment by yipenghe** [comment]
Hmmm, apparently this was working before, some changes might broke it
