### ISSUE TITLE
improve keyboard shortcuts popup documentation

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2304]
We should make this fit on one screen (currently we're not using horizontal space very well).  Also, there's some weird rendering that happens at the bottom.
![Screenshot from 2020-05-26 21-11-14](https://user-images.githubusercontent.com/435384/82977040-89db1000-9f95-11ea-816d-122c0966e6c8.png)

**Comment by yuqijin** [comment]
It seems like the problems have already been fixed. So currently all the shortcut doc occupies exactly one line, and there is no rendering issue at the bottom of the popup modal.
Close it for now.
<img width="757" alt="Screen Shot 2021-05-20 at 11 03 49 AM" src="https://user-images.githubusercontent.com/34461466/119032190-c18a5700-b960-11eb-8537-3d14986c8f8e.png">
