### ISSUE TITLE
Don't save all events in DB

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#231]
Currently, event_log is taking up a lot of space.  Maybe better to just keep count statistics (number of views, downloads, etc.).  The event_log if we keep it maybe should go somewhere else?

**Comment by kashizui** [comment]
Could we use a text file/CSV and periodic log compaction/compression?

**Comment by kashizui** [comment]
After clearing out worker checkins, event log is no longer super big -- we can probably postpone this issue. The event log as a SQL table is actually pretty useful for querying runtime/profiling data.

**Comment by percyliang** [comment]
Sounds good.  We can keep things in the DB as long as we are careful about
how much we're logging.  (Probably should add this to the monitor script).
