### ISSUE TITLE
Update testing docs

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2315]
It seems like the docs at https://codalab-worksheets.readthedocs.io/en/latest/Server-Setup/#testing are out of date. When I run `./codalab_service.py test default`, I get:

```
$ ./codalab_service.py test default
usage: codalab_service.py [-h] {start,logs,pull,build,run,stop,delete} ...
codalab_service.py: error: argument command: invalid choice: 'test' (choose from 'start', 'logs', 'pull', 'build', 'run', 'stop', 'delete')
```

**Comment by candicegjing** [comment]
This is actually the newly updated the doc. Something is wrong here with the `test default` option.

**Comment by teetone** [comment]
Actually, we moved `test` out of `codalab_service.py`. I will update the documentation.
