### ISSUE TITLE
Implement data connectors for --link using Apache Beam

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2327]
When using --link, we should be able to enter in urls starting with schemes such as gcs://, wasb://, s3://, etc.

For this, we can run Apache Beam pipelines as an abstraction to get the contents from the specified URL.

Part of #1246

**Comment by percyliang** [comment]
Will the first version will allow us to use Azure Blob as a backend with credentials or just to allow public links?

**Comment by epicfaace** [comment]
- Make sure Azure files are deleted upon bundle deletion
- Test with 10 GB uploads

**Comment by epicfaace** [comment]
I'm going to close this issue in favor of issues that delineate clearer subtasks (such as #3188).
