### ISSUE TITLE
Look into flaky Travis/GitHub Actions runs

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2329]

**Comment by teetone** [comment]
Related: https://github.com/codalab/codalab-worksheets/issues/2319

**Comment by candicegjing** [comment]
The following error might be related:
<img width="858" alt="Screen Shot 2020-05-29 at 11 19 14 AM" src="https://user-images.githubusercontent.com/1483372/83292046-4d2e3500-a19e-11ea-8537-c42f6408f42b.png">

**Comment by teetone** [comment]
Both Travis and GitHub Actions builds are passing consistently now.

GitHub Actions PR: https://github.com/codalab/codalab-worksheets/pull/2185
