### ISSUE TITLE
[Slurm Worker Manager] Free up worker resources after codalab run finished

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#2334]
For better documentation and easy reviewing, this will be implemented as a feature for Slurm Worker Manager in additional to #2279

**Comment by nelson-liu** [comment]
if you mean disk, there's a PR here for a flag to cleanup workers after they exit https://github.com/codalab/codalab-worksheets/pull/2313

**Comment by candicegjing** [comment]
@nelson-liu Oh, I mean the allocated Slurm resource/node. Coz once the bundle is finished, even though the actual worker will stop, the allocated Slurm resource won't be free up until we program to do so.

**Comment by nelson-liu** [comment]
> Coz once the bundle is finished, even though the actual worker will stop, the allocated Slurm resource won't be free up until we program to do so.

I think it will, right? Especially if you have `--exit-when-idle` set. Slurm removes the job and frees the resources when the process exits.

**Comment by candicegjing** [comment]
Never mind... my local testing didn't have the `--exit-after-num-runs` option, that's why the resource didn't get closed. Closing this now...
