### ISSUE TITLE
Optionally prevent upload of files larger than a threshold in failing bundles

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2338]
Sometimes, bundles generate massive amounts of intermediate output. For instance, training huggingface transformers squad models can generate 10+GB worth of cached features for the dataset. These are easily removed at the end of a successful run, but sometimes things go awry. The worker will then try to upload this absolutely massive bundle, and inevitably get stuck doing so—I have to go and manually kill it, clear the work-dir, and restart it to get it back up.

It'd be nice to have some way of saying, at cl run, "if this run fails, don't upload files that are individually larger than 2GB" or something to that effect.

**Comment by percyliang** [comment]
What about a ignore pattern that excludes certain files from being uploaded in the first place?

**Comment by nelson-liu** [comment]
yeah, that'd be great!

**Comment by nelson-liu** [comment]
This is really starting to bother me, since workers that can't upload their results are basically stuck in that state until I go manually kill and restart them—I might take a crack at fixing it. Would you make this a bundle-level property, and add a corresponding new field to the bundle?

**Comment by percyliang** [comment]
Ah, thanks!  Yeah, that sounds good to me.  `cl upload` already has ignore capabilities, and I think that code should be shared by the worker.
