### ISSUE TITLE
docker container for CodaLab

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#234]

**Comment by percyliang** [comment]
Create a docker image that allows people to run local instances of CodaLab easily.  It would be just one docker container, which allows you to fire up a full CodaLab installation in one simple command.  But where does the DB live?  The bundles directory presumably should live in ~/.codalab outside the docker container.

**Comment by fabeschan** [comment]
This is about 1/2 way done

**Comment by fabeschan** [comment]
Done thanks to @kashizui
