### ISSUE TITLE
pip install src error 

### ISSUE THREAD

**Issue by Dan-Git-source** [codalab/codalab-worksheets#2341]
I'm trying to install the src package (https://pypi.org/project/src/) , but I get the following error:

PS C:\Users\hwync\Documents\Notebooks> pip install src
Collecting src
  Using cached https://files.pythonhosted.org/packages/9a/2b/a6ccfc80af698319c54f00da05f6c798cf72291938893f8bd3f730c2daf9/src-0.0
.7.zip
Building wheels for collected packages: src
  Building wheel for src (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Dan Eran\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DANER
A~1\\AppData\\Local\\Temp\\pip-install-jt7wgy3z\\src\\setup.py'"'"'; __file__='"'"'C:\\Users\\DANERA~1\\AppData\\Local\\Temp\\pip
-install-jt7wgy3z\\src\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '
"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\DANERA~1\AppData\Local\Temp\pip-wh
eel-8yy8lwyg' --python-tag cp37
       cwd: C:\Users\DANERA~1\AppData\Local\Temp\pip-install-jt7wgy3z\src\
  Complete output (41 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\src
  copying src\__init__.py -> build\lib\src
  running egg_info
  writing src.egg-info\PKG-INFO
  writing dependency_links to src.egg-info\dependency_links.txt
  writing entry points to src.egg-info\entry_points.txt
  writing requirements to src.egg-info\requires.txt
  writing top-level names to src.egg-info\top_level.txt
  reading manifest file 'src.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'src.egg-info\SOURCES.txt'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\DANERA~1\AppData\Local\Temp\pip-install-jt7wgy3z\src\setup.py", line 96, in <module>
      'install_lib': InstallCommand,
    File "C:\Users\Dan Eran\Anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Dan Eran\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\Dan Eran\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\Dan Eran\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Dan Eran\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 195, in run
      reinit_subcommands=True)
    File "C:\Users\Dan Eran\Anaconda3\lib\site-packages\setuptools\__init__.py", line 198, in reinitialize_command
      cmd = _Command.reinitialize_command(self, command, reinit_subcommands)
    File "C:\Users\Dan Eran\Anaconda3\lib\distutils\cmd.py", line 306, in reinitialize_command
      reinit_subcommands)
    File "C:\Users\Dan Eran\Anaconda3\lib\distutils\dist.py", line 950, in reinitialize_command
      for sub in command.get_sub_commands():
    File "C:\Users\Dan Eran\Anaconda3\lib\distutils\cmd.py", line 324, in get_sub_commands
      if method is None or method(self):
    File "C:\Users\Dan Eran\Anaconda3\lib\distutils\command\install.py", line 631, in has_lib
      return (self.distribution.has_pure_modules() or
  AttributeError: 'NoneType' object has no attribute 'has_pure_modules'
  ----------------------------------------
  ERROR: Failed building wheel for src
  Running setup.py clean for src
Failed to build src
Installing collected packages: src
  Running setup.py install for src ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Dan Eran\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DAN
ERA~1\\AppData\\Local\\Temp\\pip-install-jt7wgy3z\\src\\setup.py'"'"'; __file__='"'"'C:\\Users\\DANERA~1\\AppData\\Local\\Temp\\p
ip-install-jt7wgy3z\\src\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
 '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\DANERA~1\AppData\Local\Temp\pi
p-record-0f8l3g4c\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\DANERA~1\AppData\Local\Temp\pip-install-jt7wgy3z\src\
    Complete output (2 lines):
    running install
    You've probably made a mistake here and are trying to install from a 'src' directory which doesn't exist.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Dan Eran\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize;
sys.argv[0] = '"'"'C:\\Users\\DANERA~1\\AppData\\Local\\Temp\\pip-install-jt7wgy3z\\src\\setup.py'"'"'; __file__='"'"'C:\\Users\\
DANERA~1\\AppData\\Local\\Temp\\pip-install-jt7wgy3z\\src\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code
=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Use
rs\DANERA~1\AppData\Local\Temp\pip-record-0f8l3g4c\install-record.txt' --single-version-externally-managed --compile Check the lo
gs for full command output.

Any thoughts?
Many thanks,
Dan

**Comment by nelson-liu** [comment]
Not sure why you're trying to `pip install src`, the pypi link says pretty clearly that this error is intended. `src` is a placeholder package to prevent malicious use of users mistyping `pip install src`.

If you want to install codalab from source, you can run: `git clone https://github.com/codalab/codalab-worksheets ; cd codalab-worksheets; pip install .`
