### ISSUE TITLE
[USER ISSUE] Out of time quota: 9d20h / 7d0h (140.9%)

### ISSUE THREAD

**Issue by bnbn333** [codalab/codalab-worksheets#2346]
Hello, my username is bnbn333.
I have been facing "server response: Out of time quota: 9d20h / 7d0h (140.9%)".
However, the run time of my bundle that was longly staged was less than four hours and I have deleted it.
Could you fix it?

**Comment by candicegjing** [comment]
@bnbn333 It's fixed. Your account should be good to use now. Please let us know if you have other questions.

**Comment by bnbn333** [comment]
Thanks for your quick response.
