### ISSUE TITLE
[USER ISSUE] Return a default int instead of None for CodaLabManager.cli_verbose.

### ISSUE THREAD

**Issue by hao-fang** [codalab/codalab-worksheets#2350]
**Describe the bug**
In some test code of my CodaLab CLI python wrapper, I would get the following exception
```
...
env/lib/python3.7/argparse.py:1744: in parse_args
    args, argv = self.parse_known_args(args, namespace)
env/lib/python3.7/argparse.py:1776: in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
env/lib/python3.7/argparse.py:1963: in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
env/lib/python3.7/argparse.py:1941: in consume_positionals
    take_action(action, args)
env/lib/python3.7/argparse.py:1850: in take_action
    action(self, namespace, argument_values, option_string)
env/lib/python3.7/argparse.py:1146: in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
env/lib/python3.7/argparse.py:1783: in parse_known_args
    self.error(str(err))
env/lib/python3.7/site-packages/codalab/lib/bundle_cli.py:173: in error
    self.cli.do_command(['help'])
```
because [this line](https://github.com/codalab/codalab-worksheets/blob/e186a51ebbd1dffc264e9cb221f86046ec64d249/codalab/lib/bundle_cli.py#L871) failed
```
        ...
        # Bind self (BundleCLI instance) and args to command function
        command_fn = lambda: args.function(self, args)
    
>       if self.verbose >= 2:
E       TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```
This happens when I construct `cli = BundleCLI(CodaLabManager(temporary=True, config={}))` for testing purpose, which sets the `self.verbose` [here](https://github.com/codalab/codalab-worksheets/blob/e186a51ebbd1dffc264e9cb221f86046ec64d249/codalab/lib/bundle_cli.py#L502), but `codalab_manager.cli_verbose()` returns None by default [here](https://github.com/codalab/codalab-worksheets/blob/master/codalab/lib/codalab_manager.py#L436).

I can get around it by constructing `cli` as below
```           
 cli = BundleCLI(
  CodaLabManager(temporary=True, config={"cli": {"verbose": 0}})
)
```
But since `self.verbose` is an `int`, the `.cli_verbose()` should return an int instead None. Alternatively, we should check if `self.verbose` is None before doing the comparison.

**Codalab Information**
- *Your username*:
- *UUID of worksheet where problem occurred*:
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
N/A

**Expected behavior**
See above.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by nelson-liu** [comment]
unrelated, but if you're building a general-purpose python wrapper for the codalab CLI, I'd love to pitch in / use it :)

**Comment by hao-fang** [comment]
> unrelated, but if you're building a general-purpose python wrapper for the codalab CLI, I'd love to pitch in / use it :)

@nelson-liu There is some specific CodaLab usage for our team internally. So it may not be a general-purpose wrapper.
The wrapper I wrote looks like below
```python
def _cli_dry_run(
    cli: BundleCLI, parser: CodaLabArgumentParser, stdout: StringIO, argv: List[str]
) -> None:
    """A dry-run cl command used for testing purpose.

    Currently, it only validate the CLI arguments and then prints a UUID.
    """
    argv = cli.collapse_bare_command(argv)
    parser.parse_args(argv)

    print(uuid.uuid4(), file=stdout)


class CLIWrapper:
    """A Python wrapper for CodaLab CLI.

    We can always pass the args to a `cl` command to the `do_command` method so that we
    don't need to invoke `cl` in a shell environment.
    """

    def __init__(self, dry_run: bool) -> None:
        self._stdout = StringIO()
        if dry_run:
            # NOTE: We need to set `verbose` because when using `python -m pytest -n4 test/test_codalab_cli`
            # CodaLabArgumentParser.error would receive `sys.argv == ["-c"]` for some unknown reason, which
            # would call `self.cli.do_command['help']`, which would then check `self.verbose`. It raises an exception
            # because `self.verbose` is set to `CodaLabManager.cli_verbose`, which is None by default.
            # See CodaLabManager.cli_verbose.
            # See CodaLabArgumentParser.error which calls `self.cli.do_command(['help'])`
            cli = BundleCLI(
                CodaLabManager(temporary=True, config={"cli": {"verbose": 0}})
            )
            cli_parser = Commands.build_parser(cli)
            self._cli_func = partial(_cli_dry_run, cli, cli_parser, self._stdout)
        else:
            cli = BundleCLI(CodaLabManager(), stdout=self._stdout)
            self._cli_func = cli.do_command

    def do_command(self, argv: List[str]) -> str:
        self._stdout.seek(0)
        self._stdout.truncate(0)
        self._cli_func(argv)

        return self._stdout.getvalue().strip()
```

We have some other classes (e.g., `ClRunCommand`, `ClRunInputBundle`) to build the `argv` for `cl run` command, e.g.,
```python
command = ClRunCommand(....)
cli_wrapper.do_command(command.render_argv())
```
