### ISSUE TITLE
support `cl run --interactive`

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2360]
Currently, you have to create a run bundle, and then either wait an indeterminate amount of time for the job to run or spin up your own worker.

Another problem is that you can’t just poke around in the shell interactively, attach a debugger, etc.

With this change, you will be able to run

```cl run … --interactive```

Assuming shared file system and `--link`, this will create a run bundle immediately in an `interacting` state, and launch a Docker container with the appropriate dependencies mounted, runs the command that you want and then drops you into a shell (in the Docker container) where you can continue to poke around.  (Note this is a different flow because usually the worker launches Docker; the client generally does not.  So we might have to refactor some things so that the client can also run docker.  There was a local mode that was created earlier which just launched docker but didn't create a bundle, but that was deprecated.)

Bonus: you can press ‘up’ to access the last command.

When you exit the interactive session, an editor pops up with the list of all the commands that were run in the interactive session.  User can delete any extraneous commands and do any editing (e.g., remove errors or diagnostic commands like ls).  When the editing is done, the official command for the bundle that actually gets created.

If one performs `cl mimic` on this bundle, then the bundle will run for real on the worker, and this will verify that the quick and dirty interactive construction was legitimate.

**Comment by candicegjing** [comment]
I am trying to see if my understanding of this workflow is on the right track:
1. `cl run --interactive` will return the current user with an interactive shell on the machine where the user initiates this command.
1. Within the interactive shell from 1, users can run commands directly, e.g. `date`, `time`, etc, just like running on a Linux platform but utilizing the local machine as computing resources. 
1. Ctrl+D to terminate the interactive shell.

**Comment by candicegjing** [comment]
Something similar to the following example? 
<img width="424" alt="Screen Shot 2020-06-10 at 5 59 32 PM" src="https://user-images.githubusercontent.com/1483372/84333281-2a0f6800-ab44-11ea-92d1-494a8169e6ce.png">

**Comment by percyliang** [comment]
I added a full description above.
