### ISSUE TITLE
can outsiders have a try?

### ISSUE THREAD

**Issue by yupbank** [codalab/codalab-worksheets#237]
Hey, this is really an interesting project, i would like to have try, but it seems outsiders only have read permission.

**Comment by percyliang** [comment]
You can try it out (create runs, upload datasets) once you create an
account.

**Comment by yupbank** [comment]
![image](https://cloud.githubusercontent.com/assets/741544/21612637/0d082926-d1a0-11e6-981a-7906a8506244.png)

**Comment by yupbank** [comment]
i was trying to upload and it fails

**Comment by percyliang** [comment]
You can't upload to your dashboard (which is read-only).  Click on 'My
Home' in the navigation bar first.

**Comment by yupbank** [comment]
oh.. my bad, thanks for your help :)
