### ISSUE TITLE
Restage issue on codalab.stanford.edu

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#2377]
Bundle restaging seems to be not working on codalab.stanford.edu. User reported bundle ended up in `WOREKR_OFFLINE` state.

**Comment by candicegjing** [comment]
Tested locally, restaging a bundle with `pass-down-termination` seems to work. Investigating more on codalab.stanford.edu.

**Comment by nelson-liu** [comment]
This works now! I think the issue was that codalab.stanford.edu just wasn't up to date enough.

**Comment by nelson-liu** [comment]
(feel free to close)

**Comment by candicegjing** [comment]
Note: after releasing v0.5.15, this issue is resolved on codalab.stanford.edu.
