### ISSUE TITLE
[Bug v0.5.14] Invalid datetime in created field on dev environment

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#2379]
Link to the original bundle: [0x38b38ab793144756ab51b714a3465663](https://worksheets-dev.codalab.org/bundles/0x38b38ab793144756ab51b714a3465663)

<img width="917" alt="Screen Shot 2020-06-09 at 4 58 20 PM" src="https://user-images.githubusercontent.com/1483372/84212373-8013db00-aa72-11ea-9027-8db4c2eb7c69.png">

Need to fix the datetime displaying issue.

**Comment by percyliang** [comment]
I think the root issue is that `created` doesn't exist for some bundles mysteriously right now, not that it needs to be displayed.

**Comment by candicegjing** [comment]
@percyliang That's right. This bug is introduced in the commit where we restage bundles and clear out existing fields in RunBundles. It appears that `created` is also part of the bundle metadata specs. It's fixed in #2475
