### ISSUE TITLE
keyboard shortcut for 'cut' not working

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2395]
On Firefox and Chrome in Linux, 'a z' doesn't trigger 'Cut'.  Other keyboard shortcuts work, and cut works if you click on the button.

**Comment by yipenghe** [comment]
can @epicfaace try it out, it's working for me on linux and windows on dev

**Comment by percyliang** [comment]
If I replace `a z` with `a l` (or anything else) it works.  So weird.

Here's a suggestion that is both a workaround and perhaps a better solution overall: let's use `a d` for this, since with cut, I don't think we need detach anymore.  `a d` is also more ergonomic to type than `a z`.

**Comment by yipenghe** [comment]
> If I replace `a z` with `a l` (or anything else) it works. So weird.
> 
> Here's a suggestion that is both a workaround and perhaps a better solution overall: let's use `a d` for this, since with cut, I don't think we need detach anymore. `a d` is also more ergonomic to type than `a z`.

Just to confirm, I will just remove the detach button and shortcut entirely and assign "a d" for cut

**Comment by percyliang** [comment]
Yes.  Note: the keyboard shortcuts for this have been updated in #2409
