### ISSUE TITLE
style the bundle table headers better

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2397]
The tables on the worksheet have headers which are too light and too tall, which makes it hard to read.
![Screenshot from 2020-06-14 14-04-56](https://user-images.githubusercontent.com/435384/84604025-0e5bd880-ae48-11ea-8cbf-a7105bc8a592.png)
Make the header slightly darker and the same height as regular rows.

**Comment by yipenghe** [comment]
This should be a good start task
