### ISSUE TITLE
inserting bundles in a table doesn't work

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2401]
To reproduce, on a new worksheet, create two bundles, cursor to the first one and then type 'a r' to create a new run.  This run will actually be appended rather than inserted.

Before:
![Screenshot from 2020-06-14 14-25-31](https://user-images.githubusercontent.com/435384/84604470-123d2a00-ae4b-11ea-9960-f081042d80db.png)
After trying to insert `echo bye`:
![Screenshot from 2020-06-14 14-25-42](https://user-images.githubusercontent.com/435384/84604471-12d5c080-ae4b-11ea-8f66-abe6231eb11f.png)

I've noticed that sometimes insertion works, but it's kind of unpredictable.

EDIT: I realized this bug comes up when there is an extra empty markdown line after the two bundles.  If there isn't, then there's no bug!

EDIT: sometimes I hit this bug when there's no new empty markdown line after the two bundles either.

**Comment by yipenghe** [comment]
After trying, I think this happens consistently when doing the below:
1. create a new worksheet
2. directly add two new runs
3. cursor to the first bundle, add new run
the insertion doesn't work
then:
4. edit source, add a markdown line above the first bundle, save
5. try inserting, the insertion works consistently now

It seems that after we save source, the insertion then works correctly @epicfaace

**Comment by yipenghe** [comment]
Further investigation, it seems that if we 'a t', we add a blank line before the the text, while if we add a new run, we don't. After we add a new run to an empty worksheet, the sort key of the bundle is 0. If we new text to an empty worksheet, the sort key of the markdown item is 1. I suspect this might be causing some problem
