### ISSUE TITLE
make 'New worksheet' more prominent for new users

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2405]
When new user joins, they just see the dashboard.  It's not clear what you can do, since you can't start uploading things directly to the dashboard.  (When we had the landing page be people's home worksheet, it was more natural to start uploading things.)

Now, we need to make 'New Worksheet' more clearly the thing that you need to do first.  Maybe we can add it as an item in the search bar that always shows up regardless of whether you type something?

**Comment by yipenghe** [comment]
I feel like we should just add a markdown block saying things like "The dashboard is a pre-created worksheet by us that shows sth. You can use the + button next to dashboard on the top right to create your own worksheet and start running your experiments". I don't think making new worksheet more obvious itself makes it clear the first thing to do is make a new worksheet. The first question for any user would probably be "why can't I edit this worksheet"

**Comment by percyliang** [comment]
Hm, maybe the dashboard isn't really the right interface for the landing page.  Rather than repurposing the worksheet infrastructure for the dashboard --- which might be suboptimal because (i) it's confusing that you can't add to the dashboard and (ii) it's a bit inflexible --- we could have a dedicated page with the user's worksheets, a few statistics, and a 'New Worksheet' prominently featured (think of the github.com landing page if you're logged in).

We might still want to make it more obvious how to create a new worksheet regardless of the dashboard, since if I'm just browsing around, I might still want to easily create a worksheet.  If we think of the search bar as evolving into a one stop shop for everything, then new worksheet definitely can show up there.

**Comment by yipenghe** [comment]
Maybe move it to the right of the search bar

**Comment by epicfaace** [comment]
Closing this, because we now have the new dashboard.
