### ISSUE TITLE
indicator for when the cursor is "above" all bundles

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2406]
When you first load a worksheet, when you click out and when you move up beyond the first bundle, the cursor is in an invisible position, which makes it hard to reason about.  Consider adding the blue cursor bar (or a compressed version of it) to an empty space above the first bundle to make the state more intuitive.

**Comment by yipenghe** [comment]
We might want to make the dummy item somewhat visible and we can insert after this dummy item so we can something to the top
