### ISSUE TITLE
when upload, select 'File upload' by default

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2407]
Currently, when hit 'a u', need to hit 'down' to select file upload.  Just make file upload the default.
![Screenshot from 2020-06-14 15-10-30](https://user-images.githubusercontent.com/435384/84605311-37cd3200-ae51-11ea-8d4c-56840d9817da.png)

**Comment by Levilian** [comment]
Hmmm I think we had a lengthy thread on why not having a default is necessary. Let me try to find it.
