### ISSUE TITLE
links on the frontpage broken

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#242]
The 'tutorial' link and the 'CLI' links go to
https://github.com/codalab/codalab-worksheets/wiki/User_CodaLab-Worksheets-Tutorial
https://github.com/codalab/codalab-worksheets/wiki/User_Install-CodaLab-CLI
which is needs to be updated.  Check the other links too.

**Comment by maxwang7** [comment]
When should I close this issue?

**Comment by kashizui** [comment]
When the changes have been deployed. Which is this weekend?

**Comment by kashizui** [comment]
Fixed
