### ISSUE TITLE
insertion of bundle happens in wrong place

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2421]
To reproduce, create a new worksheet, add ```# a
b```
Then upload a bundle.  The bundle gets inserted in between rather than at the end.
![Screenshot from 2020-06-17 00-14-30](https://user-images.githubusercontent.com/435384/84867154-96500700-b02f-11ea-9281-511ac3cad923.png)

**Comment by yipenghe** [comment]
Can't reproduce, how exactly do you did # a b ? Shouldn't that be a single markdown text block?
