### ISSUE TITLE
cl upload -x seems to be broken (exclude pattern)

### ISSUE THREAD

**Issue by kelvinguu** [codalab/codalab-worksheets#243]
Example:

``` bash
$ cl upload -x '*.ipynb' src
UsageError: Nothing to upload
```

If I change the argument order:

``` bash
$ cl upload src -x '*.ipynb'
```

`src` is uploaded, but ipynb files aren't excluded.

**Comment by kashizui** [comment]
@kelvinguu is this happening while connected to a remote bundle service (e.g. codalab.stanford.edu)?

**Comment by kashizui** [comment]
Never mind, doesn't look like it really matters, but still good to know just in case—thanks in advance!

**Comment by kelvinguu** [comment]
Ah yes, it was on codalab.stanford.edu. Thanks!

**Comment by kashizui** [comment]
Looks like the first case didn't work because the `-x` flag eats all the following arguments—should this be undesirable behavior, or just better documented?

I'm unable to reproduce the second case—my files are excluded as specified. The CLI simply makes a command to `rsync`, with the arguments to `-x` passed as `--exclude` arguments, and I know `rsync` sometimes has different behavior between OS distros. Could you maybe send me your `rsync` version number and/or manpage?

**Comment by kashizui** [comment]
I'm unable to reproduce the second case—my files are excluded as specified. Any thoughts on why it might not be working for you?

**Comment by kashizui** [comment]
The CLI simply makes a command to `rsync`, with the arguments to `-x` passed as `--exclude` arguments, and I know `rsync` sometimes has different behavior between OS distros. Could you maybe send me your `rsync` version number and/or manpage?

**Comment by kashizui** [comment]
@kelvinguu are you still getting this issue? There have been some recent improvements (on the `develop` branch of the CLI) in the uploading procedures. I'm currently still unable to reproduce your problem.

**Comment by percyliang** [comment]
We will push develop to master tonight and then @kelvinguu can try it out
again

**Comment by kelvinguu** [comment]
Thanks! I'll be sure to try it.

**Comment by kelvinguu** [comment]
@kashizui, thanks, in my latest attempts, it works fine now.

**Comment by kashizui** [comment]
Awesome, thanks for your help @kelvinguu.

**Comment by kelvinguu** [comment]
Unfortunately, this problem came back. Here's what I see now:

``` bash
$ cl upload src -x '*.ipynb'
tar: --exclude=*.ipynb: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
```

The bundle still uploads, but the `ipynb` files are not excluded.

On a separate note, in the old behavior of codalab, the above command created a bundle called `src` with all the source files in it.

Now, the above command creates a bundle called `src`, **with a folder called `src` in it**. This seems like a bug? If so, I can create a separate issue.

**Comment by kashizui** [comment]
I cannot reproduce this error still, it must have something to do with different implementations of `tar` and other command-line utilities. Could you give us your `tar` version, OS, etc.?

**Comment by kashizui** [comment]
@kelvinguu I cannot reproduce this error (nor the new folder-in-folder issue) still, it must have something to do with different implementations of tar and other command-line utilities. Could you give us your tar version, OS, etc.?

**Comment by kelvinguu** [comment]
@kashizui 

$ tar --version
bsdtar 2.8.3 - libarchive 2.8.3

OS X Yosemite, 10.10.5

Is there a version you recommend?

**Comment by kashizui** [comment]
Ah I can see the original error now:

```
tar: --exclude=*.js: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
```

Will take a look at that.
Tar and OS info will still be helpful for figuring out the folder-in-folder issue. Thanks!

**Comment by kashizui** [comment]
@kelvinguu no clue, haha. I have the same version actually, and I don't get the folder-in-folder. To be investigated...
