### ISSUE TITLE
Support anonymous bundles and worksheets

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#243]
Build out the UI components to support anonymous worksheets and bundles.

Implementation on the API/backend side, as well as support on CLI client:
codalab/codalab-cli#400

**Comment by maxwang7** [comment]
@kashizui Have there been any updates on this?

**Comment by kashizui** [comment]
@maxwang7 No updates, backend implementation is still incomplete.

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1070
