### ISSUE TITLE
Look into GitHub One for education pricing 

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2443]
We are currently on a Free Plan for GitHub Actions, which allows only 20 concurrent runs at a time. We need to upgrade our plan to increase the quota.

https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits

**Comment by epicfaace** [comment]
It appears we're on a Team Plan, meaning that we have a limit of 60 concurrent runs. Should be enough for now.
