### ISSUE TITLE
Collapse Tables

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#247]
@maxwang7 commented on [Wed Jan 25 2017](https://github.com/codalab/codalab-cli/issues/658)

**Comment by percyliang** [comment]
To flesh this out: on large worksheets, be able to collapse a table.  (Collapsing sections in markdown might be a bit annoying to do.)

**Comment by robinjia** [comment]
+1 I would find this useful

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1068
