### ISSUE TITLE
can't text/upload/run on a newly loaded worksheet

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2482]
To reproduce, create a new worksheet with one bundle on it.  Refresh the page.  Then click 'text', 'upload', or 'run'.  Nothing happens.  You have to select the last row for it to work.

This is because the focus is at -1 when the page loads.

In the past, we have appended new blocks to the worksheet, in concordance with what happens on the CLI.  However, this doesn't mesh well with the intuition that the cursor is right before the first item on the page, so the actually new blocks should be prepended to the worksheet.  Having a reverse chronological research log isn't itself a bad idea, but the problem is that the whole CodaLab model of always referring to the *last* bundle gets broken.

Perhaps a safe thing to do is only allow text/run/upload if the focus is not -1 on a non-empty worksheet, and always put a 'Go to end' button.

Or we can just have an as-is mentality and just prepend when focus is -1.

**Comment by yipenghe** [comment]
Currently the add-item end point is written to add after an item, so to preprend we would need to modify the endpoint to preprend an item when the sort key is not given, should we do that?

**Comment by yipenghe** [comment]
I decided to go for preprend: it's more convenient. Currently a user would need to edit source to add new runs and text to the very top. If we allow prepending when no focus, user can add things at top of the worksheet without going to source, which aligns with the frontend goal (reducing the need for editing source)

**Comment by percyliang** [comment]
Ok, that's fine.  Maybe we can have a 'Go to end' button (is there a good icon for this? or maybe it should be over the current cursor?), since I really don't think we want people prepending to a worksheet (it will work well until it gets confusing if you're using the CLI).

**Comment by yipenghe** [comment]
> Ok, that's fine. Maybe we can have a 'Go to end' button (is there a good icon for this? or maybe it should be over the current cursor?), since I really don't think we want people prepending to a worksheet (it will work well until it gets confusing if you're using the CLI).

Yeh we can have a go to end button, we can place it at the right-bottom corner
