### ISSUE TITLE
Setup nightly automatic deployment from master branch to dev environment

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#2483]
With this CICD pipeline setup, we can have our master branch tested more frequently and catch any issues as early as we can.

**Comment by epicfaace** [comment]
I would actually like if we could do an automatic deployment to dev on every CI build to master. It would reduce a lot of friction (it takes time to deploy manually to dev -- you have to wait for the person on call to be available, for images to build, etc.) and make it easier to continuously test latest code this way.

We discussed this option before though and decided against it at the time -- thoughts, @percyliang ?

**Comment by percyliang** [comment]
Maybe me should deploy to `worksheets-master.codalab.org` perhaps to save `dev` as a playground.
