### ISSUE TITLE
[extremly long staged time]

### ISSUE THREAD

**Issue by yww211** [codalab/codalab-worksheets#2486]
**Describe the bug**
We have submitted several jobs with requesting 1 gpu in recent days, but we encounter extremly long staged time. Say more than two days(48 h). 
We find the resource of gpu on Codalab was not allocated  by a queue of job submission time. The user `nfliu`  and some standford users seem have occupied the  resource  on Codalab for several days. 
![image](https://user-images.githubusercontent.com/32888325/85353333-8b6b0a00-b53a-11ea-87bd-01505fe7e4b9.png)

**Comment by nelson-liu** [comment]
> The user nfliu and some standford users seem have occupied the resource on Codalab for several days.

Hm, for the bundles in the screenshot, those are all running on private workers that I've (nfliu) launched—they are not relevant to your priority in the queue. In case you weren't aware, you can run your own workers on CodaLab: https://codalab-worksheets.readthedocs.io/en/latest/Execution/#running-your-own-worker

**Comment by percyliang** [comment]
We should probably update the dashboard to only show runs on the public workers.

**Comment by shiontao** [comment]
The staged time is toooo long, especially for people like me who are using this platform for the first time. It takes a few days to debug and submit.

**Comment by yww211** [comment]
> > The user nfliu and some standford users seem have occupied the resource on Codalab for several days.
> 
> Hm, for the bundles in the screenshot, those are all running on private workers that I've (nfliu) launched—they are not relevant to your priority in the queue. In case you weren't aware, you can run your own workers on CodaLab: https://codalab-worksheets.readthedocs.io/en/latest/Execution/#running-your-own-worker

Thanks, i see.
