### ISSUE TITLE
Rethink 'wsearch' back-end: prioritizing user's own worksheets

### ISSUE THREAD

**Issue by Levilian** [codalab/codalab-worksheets#2487]
This change would also affect the search bar experience.

**Comment by percyliang** [comment]
Concretely, we want to sort the worksheet query by whether owner is the user.  Maybe also sort by last modified date?

Note that we have to be careful that this doesn't break backward compatibility.

Motivation: if you type 'home' in the search bar, then user's worksheet (`home-...`) doesn't show up...
