### ISSUE TITLE
be able to upload directories

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#25]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Tuesday Nov 17, 2015 at 15:26 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1406_

---

Do what DropBox or Google Drive do.

**Comment by bkgoksel** [comment]
Isn't this supported now?

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1050
