### ISSUE TITLE
Unable to download Docker image: Repository not found

### ISSUE THREAD

**Issue by yelongshen** [codalab/codalab-worksheets#250]
cl run --request-docker-image dit4c/dit4c-container-nltk ls (okay)
cl run --request-docker-image dit4c/dit4c-container-nltk other commands (fail)
Unable to download Docker image: Repository not found

**Comment by kashizui** [comment]
Did you quote your other commands? It might be helpful to get your full command.

**Comment by yelongshen** [comment]
Hey Stephen,
     Thanks for responding this. It sometimes had this issue, sometimes not. I would like to give your more details information once it appears again. I don’t have this issue now, so I would consider the problem has been solved.

Thanks,
Best,
Yelong.

**Comment by kashizui** [comment]
In my experience (and based on some googling), Docker will actually complain with a mysterious "Unable to download Docker image: Repository not found" even when it's just a transient network error. Usually retrying the same command (or restarting the Docker daemon) should fix it.

**Comment by kashizui** [comment]
Thanks for your input, I'll close this issue for now.
