### ISSUE TITLE
Create Help Button

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#251]

**Comment by maxwang7** [comment]
Front end:
- States:
    - 1 - "?" button
    - 2 - ">" button, text area, help text
    - 3 - Sending message: "..."
    - 4 - Failure: "X"
    - 5 - Success: check mark in button.
- Transitions:
    - Click button: 3, 4, 5 all don't change
        - 1 --> 2
        - 2 --> 3
    - Timer: 1, 2, 3, all don't change
        - 4 --> 2
        - 5 --> 1

Extensions:
- [ ] Allow user to view previously send messages
- [ ] Let the text box automatically grow to fit the text

**Comment by maxwang7** [comment]
Feature branch: https://github.com/codalab/codalab-worksheets/tree/max-help-button

**Comment by maxwang7** [comment]
@kashizui I'm getting this error for my new help button file/React class: Uncaught ReferenceError: HelpButton is not defined. I've looked around in the compilation files but haven't found any reason the file shouldn't be there.

- Here's the new file: https://github.com/codalab/codalab-worksheets/blob/fd3aa902f5b4a542cb57136f09502161cced2b7c/codalab/apps/web/static/js/worksheet/worksheet_help_button.jsx.
- The HelpButton element is being used here: https://github.com/codalab/codalab-worksheets/blob/fd3aa902f5b4a542cb57136f09502161cced2b7c/codalab/apps/web/static/js/worksheet/worksheet_interface.jsx#L665
- You can view the error here: http://138.197.208.207:8000/worksheets/0x87e7ba7c49744dbabc76eb24c05043bd/

**Comment by kashizui** [comment]
i think you will need to script src your new .js file in the relevant html
file ("detail.html"? maybe)

**Comment by maxwang7** [comment]
How do I find the current logged in user?
Example: https://github.com/codalab/codalab-cli/blob/master/codalab/rest/worksheets.py#L92

How to integrate new code into REST API?
- Probably need most of the import statements from here:
- Add import statement here: https://github.com/codalab/codalab-cli/blob/master/codalab/server/rest_server.py#L29-L39

**Comment by kashizui** [comment]
On the backend, `request.user` contains an instance of `codalab.object.user.User` representing the current logged in user. If the user isn't logged in, then it's set to `codalab.object.user.PUBLIC_USER`.

Yes you can copy imports from that module as an example. The entities like `bottle.request`, `bottle.local` are all thread-local variables that are automatically set before every request.

Yep you will just need to import your new module in `rest_server.py` to make sure Bottle knows about your new routes.

**Comment by maxwang7** [comment]
Oh, thank you Stephen! Sometimes I just take notes to myself in the comments, but having your confirmation really helps, I appreciate it!

**Comment by kashizui** [comment]
oh oops i see what you were doing there now lol

**Comment by maxwang7** [comment]
I'll say "Notes to self" when I do that in the future

**Comment by kashizui** [comment]
all good

**Comment by maxwang7** [comment]
Notes to self:

How do I create a new table?
- Tables: https://github.com/codalab/codalab-cli/blob/master/codalab/model/tables.py
- Migration: Use Alembic: https://github.com/codalab/codalab-cli/tree/master/alembic
- Table design:
    - id INTEGER
    - message text TEXT
    - owner_id STRING(63) --> joins with user table.
    - date_sent DateTime

How do I send emails?
- Example use of emailer: https://github.com/codalab/codalab-cli/blob/7e075ff3c4e3f4dc82ffb770382fc68feb90b0c2/codalab/rest/account.py#L19-L23
- The Emailer class: https://github.com/codalab/codalab-cli/blob/7e075ff3c4e3f4dc82ffb770382fc68feb90b0c2/codalab/lib/emailer.py

**Comment by maxwang7** [comment]
The corresponding in codalab-cli for the help REST API endpoint: https://github.com/codalab/codalab-cli/tree/max-help-button

**Comment by maxwang7** [comment]
Make textbox larger

**Comment by maxwang7** [comment]
Percy is also reporting a bug where typing "m <space>" causes the help box to open.

**Comment by maxwang7** [comment]
Also, add focus to the text messaging box.

**Comment by maxwang7** [comment]
Ok, fixes for textbox size and focus were pushed straight to staging. Percy's bug hasn't been resolved yet

**Comment by percyliang** [comment]
Hm, I can't reproduce that anymore...

Another note: after you click send, it would be good to gray out the
textbox or something so that the user can't type in it anymore.

**Comment by kashizui** [comment]
Done
