### ISSUE TITLE
Invariances in bundle manager can be confusing

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2555]
The invariants in the bundle manager code are extremely hard to reason about, especially with regards to what's stale. A long term issue would be to think closely about how to make it better.

Relevant PRs: https://github.com/codalab/codalab-worksheets/pull/2336 , https://github.com/codalab/codalab-worksheets/pull/2424 , https://github.com/codalab/codalab-worksheets/pull/2549

**Comment by epicfaace** [comment]
What do you mean by "invariants in the bundle manager code"? Can you link to some lines of code that give examples of these problematic invariants?
