### ISSUE TITLE
Github Actions - check for CLI / REST documentation generation

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2566]
We don't have checks yet to make sure that the latest CLI / REST documentation is generated.

**Comment by percyliang** [comment]
Functionally, this is `./pre-commit.sh` and making sure there are no changes?

**Comment by epicfaace** [comment]
Yes. We can just run:

```
./pre-commit.sh
git diff --exit-code
```

**Comment by yiboliu** [comment]
PR closed
