### ISSUE TITLE
Change CI build timeout from 6 hours -> 1 hour

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2583]
This way, CI builds that take a long time (such as those caused by #2578) won't clog up our parallel job quota.

**Comment by percyliang** [comment]
@epicfaace Is this a one character change?

**Comment by epicfaace** [comment]
I don't think this is a huge issue at the moment. We haven't seen this issue (CI jobs clogging up our job quota in a while) since GHA was implemented, and doing so may require manually adding the timeout in multiple lines for each job (so it's not an easily maintainable change). Closing this issue.
