### ISSUE TITLE
Improve documentation of jquery terminal keyboard shortcuts

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#26]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Tuesday Nov 17, 2015 at 15:28 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1407_

----

Two options:
- allow alt-f and alt-b to jump across words in jquery terminal
- allow user to click in the middle of the command to bring the cursor there.

**Comment by codalab** [comment]
<a href="https://github.com/kashizui"><img src="https://avatars.githubusercontent.com/u/614837?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kashizui](https://github.com/kashizui)**
_Wednesday Dec 02, 2015 at 01:17 GMT_

----

@percyliang @pbhatnagar3 

There are already some shortcuts for jumping around (see "Keyboard shortcuts" here: http://terminal.jcubic.pl/api_reference.php)

Do we want to override/change these?

Meanwhile, I don't see built-in functionality for setting the cursor with the mouse.

**Comment by codalab** [comment]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [percyliang](https://github.com/percyliang)**
_Wednesday Dec 02, 2015 at 05:24 GMT_

----

Ah, this is useful.  Maybe we can link to the appropriate section from our
keyboard shortcuts help page and call it good for now?

**Comment by codalab** [comment]
<a href="https://github.com/kashizui"><img src="https://avatars.githubusercontent.com/u/614837?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kashizui](https://github.com/kashizui)**
_Wednesday Dec 02, 2015 at 05:37 GMT_

----

I'd vote for that!

Reorienting this ticket...

**Comment by kashizui** [comment]
Fixed by https://github.com/codalab/codalab-worksheets/commit/8ebbb1a7258259c5107fe9b1e502381b57ad184b
