### ISSUE TITLE
worker on run throws start_bundle error

### ISSUE THREAD

**Issue by Raisins** [codalab/codalab-worksheets#26]
`cl run date`

on the worker side it reports 

```
cl worker
...
...
=== INTERNAL ERROR: start_bundle() takes exactly 4 arguments (5 given)
Traceback (most recent call last):
  File "/codalab/src/codalab-cli/codalab/objects/work_manager.py", line 114, in start_bundle
    status = self.machine.start_bundle(bundle, self.bundle_store, self.get_parent_dict(bundle), username)
TypeError: start_bundle() takes exactly 4 arguments (5 given)
```

Note my cl commands are running via remote service http://localhost:2800

**Comment by percyliang** [comment]
I just pulled master, and this works.  Are you sure you don't have an out
of date version?

**Comment by abmnv** [comment]
I am getting the same error when running examples described on the Installation page. I just cloned a fresh version of cli

**Comment by percyliang** [comment]
I see, this is a problem for the local worker.
Pushed a fix to master.

**Comment by Raisins** [comment]
fixed. Thanks
