### ISSUE TITLE
automatic run macros on upload

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#260]
When people upload a bundle and it has a specific tag, then it should trigger a macro to be run.  This makes it easier to cover the common case where someone just wants to upload new predictions and want to be added to the leaderboard.  Alternatively, just make it much more obvious how to run macros.

The current process for submission would be:
1) Click on My Worksheet (log in if necessary)
2) Click upload button and uploads predictions or code (equivalent to 'cl upload').  This adds the uploaded bundle to the current worksheet.
3) Click on macro button and select the macro (equivalent to 'cl macro qa/eval <current bundle>').  This adds some text/runs to the current worksheet with specific tags (e.g., 'webquestions-eval').
4) View the results on the public worksheet, which has a '% search ...' directive that automatically shows bundles with a particular tag.

**Comment by ilblackdragon** [comment]
I think two things need to be thought together:
1) Adding new benchmark (dataset for train / valid / test + description)
2) Uploading predictions for this benchmark.

How hard would be have a separate view from default worksheets (which are good for coding / maintaining state of the experiment, but not as easy accessible for just maintaining benchmarks) that will have benchmarks / submissions / leaderboard?

**Comment by percyliang** [comment]
On Wed, Dec 2, 2015 at 4:47 PM, Illia Polosukhin notifications@github.com
wrote:

> I think two things need to be thought together:
> 1) Adding new benchmark (dataset for train / valid / test + description)
> 2) Uploading predictions for this benchmark.
> 
> How hard would be have a separate view from default worksheets (which are
> good for coding / maintaining state of the experiment, but not as easy
> accessible for just maintaining benchmarks) that will have benchmarks /
> submissions / leaderboard?
> 
> Can you elaborate more on what you think would be a godo interface for the
> benchmarks / submissions / leaderboard?  In principle, CodaLab Competitions
> might be closer to that, but it's not currently hooked up with worksheets.

If one wants a more specialized interface other than worksheets (which
might be fine if one is already used to using worksheets for development),
one possibility is to build a separate site for that that can talk to the
worksheets.  In some sense, that was the original intention: CodaLab
worksheets is supposed to be a slim poweruser core that people can build
other apps on top of.

**Comment by percyliang** [comment]
Handled by the competitiond script.
