### ISSUE TITLE
Update Stanford instance documentation with protected mode

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2611]
Once this [feature](https://github.com/codalab/codalab-worksheets/pull/2600) gets in a future release, update the codalab.stanford.edu documentation with information on how to start in protected mode.

**Comment by epicfaace** [comment]
I think we can actually create the main page about "Protected Mode" on our public documentation (https://codalab-worksheets.readthedocs.io/en/latest/), and just link to that page / mention specifics about codalab.stanford.edu in the deployment documentation.

**Comment by teetone** [comment]
@epicfaace  This issue is just to track adding `-p` to the instructions on how to start up codalab.stanford.edu.
