### ISSUE TITLE
Address the problem that students' worksheets/bundles will be public by default

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#263]
We are concerned that there may be honor code violations

Ideas:
- Special link to sign up form where the GET params that all assets are private by default.
- Have script search through all bundles and look for the appropriate flag.

**Comment by maxwang7** [comment]
This should take 1 hr.

Questions (answers from Percy):
- What's the appropriate flag (indicator that a bundle is the SQuAD bundle)? --> Make up a tag.
- How often should we run this job? The TAs will just run it whenever they need to
- How should we be notified? Just print to console.
- How should I test this? On local setup, create two bundles, both that are SQuAD, one that's public and the other that's private. Check that only the public one is printed

**Comment by maxwang7** [comment]
search tags=cs224n
Go through each bundle, query the REST API for each individual bundle (or command line, `info <bundle_spec> -v` to get information about group permissions
check that the bundle is not publicly readable

**Comment by maxwang7** [comment]
@kashizui Have you included this functionality in your script?

**Comment by kashizui** [comment]
I have not -- shall I just include it in the script?

**Comment by kashizui** [comment]
What should be script actually do here? I haven't built in any emailing functionality into it, so I would have to do that first if we want to email an instructor or something about this. We also don't have access to the student's email when just given their CodaLab username.

**Comment by percyliang** [comment]
I think it should just be a script that you run that prints out possible
bundles that are suspect.  Instructor should run this manually once in a
while and just take care of it.  I don't think we need automation for this.

**Comment by kashizui** [comment]
To get all the bundles tagged with `xxx-submit`:
```
bundles = client.fetch('bundles', params={
    'keywords': 'tags=xxx-submit'
})
```
where client is JsonApiClient.

**Comment by kashizui** [comment]
Wrote script and submitted PR to cs224n course repo
