### ISSUE TITLE
Report errors better when worker has no more space

### ISSUE THREAD

**Issue by entslscheia** [codalab/codalab-worksheets#2630]
I am actually very confused with how to work with my own worker for CodaLab.
As pointed [here](https://codalab-worksheets.readthedocs.io/en/latest/Execution/#running-your-own-worker), we can use our own worker simply by running `cl-worker`, then if we run `cl run date`, we should see our own hostname in `remote` field of metadata, however, when I did that, `date` command was still running on CodaLab's worker not mine.
Then I tried to tag my worker by `cl-worker --tag test`, and run`cl run date --request-queue tag=test`, I finally managed to see my own hostname in `remote` field. However, the bundle state was `failed`, with failure message **Failed to download Docker image: Can't download image: 404 Client Error: Not Found ("no such image: codalab/default-cpu:latest: No such image: codalab/default-cpu:latest"): 404 Client Error: Not Found ("no such image: codalab/default-cpu:latest: No such image: codalab/default-cpu:latest")**.

FYI, I am using Ubuntu 18.04. My docker version is 18.09 as suggested being < 19.03. The link to my failed bundle is https://worksheets.codalab.org/bundles/0x15d667886c1f44cebbb4232651ff0d01

Any idea on this? I can't find any other documentations describing this. Any suggestion would be greatly appreciated!

Another issue, every time I tried to run `cl-worker --tag test` I get cut off from my server (I am visiting the sever via ssh). Not sure whether this is a coincidence but it did happen several times. Or maybe it's just some security issue of my university's server configuration.

**Comment by epicfaace** [comment]
@entslscheia can you try running `docker pull codalab/default-cpu` and see if that succeeds? Let's see if this is an issue with your connection to Docker Hub.

**Comment by entslscheia** [comment]
> docker pull codalab/default-cpu

@epicfaace I tried to run `docker pull codalab/default-cpu`. The connection was successful but it reported `write /var/lib/docker/tmp/GetImageBlob103914214: no space left on device` at the final step. I guess I can fix this by changing the default directory `/var/lib/docker` to another directory with enough space (i.e., all data on our sever are host under the `/scratch` directory). Do you think this could be the reason why I failed to run my own worker? If so, is it possible to report this error instead of logging `Connected! Successful check in` when executing `cl-worker`?

**Comment by epicfaace** [comment]
Yeah, that's probably the problem -- a lack of space. Yeah, we could have better reporting on this end, thanks for the feedback!
