### ISSUE TITLE
autocomplete for docker containers

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#264]
If type `--request-docker-image`, then should autocomplete with all the docker containers that are in the system.  This way, it's easy for people to choose from the popular docker containers (e.g., for TensorFlow).

The list of docker containers should be gotten dynamically by calling `docker search`.  Perhaps this should be cached.

**Comment by a10y** [comment]
We're using argparse so should be able to use this: https://pypi.python.org/pypi/argcomplete/1.0.0

**Comment by kashizui** [comment]
We are currently using argcomplete—you can take a look at `completers.py` (and `bundle_cli.py`) for how to add more autocompletion functionality.

**Comment by a10y** [comment]
@kashizui thanks!

**Comment by a10y** [comment]
@percyliang @kashizui did you mean `docker search`, which searches DockerHub? Or should we complete off of the images that are available on the worker machine?

**Comment by percyliang** [comment]
Yes, we should use 'docker search', which searches DockerHub (or maybe they
have a more direct API?)  Docker images that don't exist on the local
machines will be pulled automatically from the hub.

**Comment by a10y** [comment]
@percyliang sounds good. is the auto-pulling already implemented or is that going to be another change?

**Comment by percyliang** [comment]
docker already does auto-pulling

**Comment by a10y** [comment]
Implemented in https://github.com/codalab/codalab-cli/pull/290
