### ISSUE TITLE
CodaLab - Worksheet:

### ISSUE THREAD

**Issue by mirospacek** [codalab/codalab-worksheets#264]
https://worksheets.codalab.org/worksheets/0x20ce2b583c7a4ddd9496b480c0bc1b79/

has a link: <HTML like this>

https://worksheets.codalab.org/api/bundles/filecontent/0x4448a6eeefcc45eab0fce9fd6873c0db/main.html

yields-->404

Could not find the page you requested. If this is in error, please file a bug report. For more information about CodaLab, check out the wiki.

**Comment by percyliang** [comment]
Fixed.
