### ISSUE TITLE
Bundle run-related meta data should not be editable

### ISSUE THREAD

**Issue by yipenghe** [codalab/codalab-worksheets#2654]
Currently you can edit fields like requested-cpus/gpus on the bundle page, which doesn't make sense since for a run bundle, these fields should be fixed and immutable once the user submitted the run, unlike fields like name, descriptions which make sense to allow editing even after the run finishes

**Comment by nelson-liu** [comment]
fwiw: it's sometimes useful to be able to interactively change these when a bundle is still staged—agreed that it should be immutable once a bundle starts running, though.

**Comment by leilenah** [comment]
resolved
