### ISSUE TITLE
[USER ISSUE] I have attached my own worker, but my run bundle is still staged

### ISSUE THREAD

**Issue by erikchwang** [codalab/codalab-worksheets#2656]
I set up a virtual machine with GPU on Google Cloud as my own worker, and then start the worker by "cl-worker". 
But when I run my bundle, it was not running on my worker, but staged. 
I also tried adding tags to my worker, but it does not help.

**Comment by teetone** [comment]
Hi @erikchwang can you post the name of your worker and the UUID of the bundle that is still stuck in staged?

**Comment by teetone** [comment]
We just deployed a new version of CodaLab. Please open a new issue if this problem still persists.

**Comment by erikchwang** [comment]
Now it works. Thanks!
