### ISSUE TITLE
Test "cl work" command in test_cli.py

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2665]
We need to add tests involving running `cl work [domainname]::` in test_cli.py. Right now, we only catch errors in this command in the stress tests, not in the actual CLI tests.

**Comment by yiboliu** [comment]
Add a test module to try running `cl work [domainname]::` see if it succeeds. Need more info about what domainname needs to be. starting with `localhost`

**Comment by yiboliu** [comment]
localhost is finished. If more domain name checkings are needed, I'll reopen the issue.
