### ISSUE TITLE
[USER ISSUE] Bundles disappear on add new run, until dashboard refresh

### ISSUE THREAD

**Issue by cjliux** [codalab/codalab-worksheets#2669]
**Describe the bug**

**Codalab Information**
- *Your username*: cjliux
- *UUID of worksheet where problem occurred*: 0x03f687bb7d8c4fe099248ced1163857c
- *UUID of problem bundle (please don't delete)*: all
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*: Windows
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*; Chrome

**To Reproduce**
Steps to reproduce the behavior :
I have no idea why.

**Expected behavior**
I tried to add a new run to my worksheet, and on clicking the rerun button, everything got lost but the newly added run bundle.

**Screenshots**
Unavailable.

**Additional context**
Unavailable.

**Comment by cjliux** [comment]
It seems like a mess.

**Comment by yipenghe** [comment]
Sorry for what happened, are the lost bundles floating in the dashboard?

**Comment by cjliux** [comment]
No. All source files are lost except those with large size.

**Comment by cjliux** [comment]
Oh, I refresh the dashboard and I find them.

**Comment by cjliux** [comment]
But it seems incomplete.

**Comment by yipenghe** [comment]
Try add: 
% search .mine .limit=100 
to worksheet source (click edit source in your own worksheet or create a new one). It should show you all the bundles you own, can you find them there?

**Comment by yipenghe** [comment]
> But it seems incomplete.

Do they show up in this worksheet? https://worksheets.codalab.org/worksheets/0xf8c0b905c36a4dcb9d8de090b4026810

You can also add 
% search owner=cjliux .limit=10000

or 
% search .mine .limit = 10000
in your worksheet source to list all your bundles

**Comment by cjliux** [comment]
Unfortunately them don't. But I have found them copying the uuid in my run bundle.

**Comment by yipenghe** [comment]
> Unfortunately them don't. But I have found them copying the uuid in my run bundle.

The worksheet lists all the bundles you own, were some of missing ones not own by you?

**Comment by cjliux** [comment]
Oops, I see it. Thx

**Comment by yipenghe** [comment]
Glad you found them back. I'm not sure how this happened, but if you see it again or notice how to reproduce it, please comment again, thanks!

**Comment by teetone** [comment]
@cjliux  I will close this issue for now, but please feel free to open a new issue if it happens again and you are able to reproduce it.
