### ISSUE TITLE
Fix links on default dashboard page

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#267]
Write a script for checking for broken links or links that go to an empty Github Wiki page

**Comment by maxwang7** [comment]
The link was already fixed as of 8 months ago. I'm a bit confused why we haven't deployed that code yet though... https://github.com/codalab/codalab-cli/blame/master/codalab/objects/dashboard.ws

**Comment by maxwang7** [comment]
The reason the link hasn't been updated is that each CodaLab instance is initialized with a default worksheet for all users that draws from the file `dashboard.ws`. After that, the worksheet doesn't change unless the admin changes the dashboard. For my test instance, the dashbarod worksheet was not initialized, and so CodaLab creates a new worksheet for every new user.

So, to fix the problem with the link: log into the prod instance of Codalab as the admin and edit the worksheet. I don't have admin account credentials, but I'll probably just ssh into the admin machine and then run the commands I need (`cl wedit`).

**Comment by kashizui** [comment]
fix'd
