### ISSUE TITLE
Backup bundles on wsprod to another machine

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#268]

**Comment by fabeschan** [comment]
We did backups (only) during the Great Migration -- is that what you're looking for, or do you want continuous backups?

**Comment by kashizui** [comment]
Probably good to have some sort of continuous / regular backups of the bundles!

**Comment by bkgoksel** [comment]
We don't even have wsprod anymore. Any reason to keep this open @percyliang ?

**Comment by percyliang** [comment]
I think this still applies to our current prod server...

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1069
