### ISSUE TITLE
[USER ISSUE] Can't upload bundle in fresh server

### ISSUE THREAD

**Issue by szha** [codalab/codalab-worksheets#2687]
**Describe the bug**
Following the [guide](https://codalab-worksheets.readthedocs.io/en/latest/Server-Setup/), I set up a custom server with the latest master branch on host. When I log in and try to upload a file, I see the following prompt:
![image](https://user-images.githubusercontent.com/2626883/89261184-7d50e480-d5e2-11ea-9fb7-cacf7a9486e0.png)

When I use the CLI to upload, I get a different error:
![image](https://user-images.githubusercontent.com/2626883/89261432-e9cbe380-d5e2-11ea-930b-c0167b60d94c.png)

I'm using the following config with the CLI:
![image](https://user-images.githubusercontent.com/2626883/89261497-0405c180-d5e3-11ea-9947-0b2523b43ddd.png)

**Codalab Information**
- *Your username*: codalab
- *Error message received from Codalab (if applicable)*: Missing metadata key link_url.
 - *OS (if on CLI)*: the server is on Amazon Linux 2.
 - *Browser (if on Web)*; Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Launch a fresh EC2 host with Amazon Linux 2 image.
2. Launch an RDS database for mysql and use it in the mysql server config
3. Create an EFS file system for codalab home, link mount, bundle mount
4. Make sure that the security group setting let's them talk to each other
5. Open the browser and go to the IP address

**Expected behavior**
I expect the upload to succeed and the bundle to appear

**Additional context**
I left the above server running and you can visit the ip address with the default password to see the problem for yourself.

Below is the command I used to start the server.
```
./codalab_service.py start --mysql-root-password $MYSQL_ROOT_PASSWORD --mysql-password $MYSQL_PASSWORD --mysql-username $MYSQL_USERNAME --mysql-port $MYSQL_PORT --mysql-host $MYSQL_HOST --mysql-database $MYSQL_DATABASE --codalab-home $CODALAB_HOME --http-port 80 --worker-manager-type $WORKER_MANAGER_TYPE --worker-manager-aws-region $WORKER_MANAGER_AWS_REGION --worker-manager-aws-default-cpus $WORKER_MANAGER_AWS_DEFAULT_CPUS --worker-manager-aws-default-memory-mb $WORKER_MANAGER_AWS_DEFAULT_MEMORY_MB --worker-manager-max-cpu-workers $WORKER_MANAGER_MAX_CPU_WORKERS --worker-manager-max-gpu-workers $WORKER_MANAGER_MAX_GPU_WORKERS --link-mounts $CODALAB_HOME/links --server $SERVER --admin-email $ADMIN_EMAIL --bundle-mount $CODALAB_HOME/bundles
```

**Comment by epicfaace** [comment]
This change appears to have happened because non-`generated` fields are treated as `required` by default: https://github.com/codalab/codalab-worksheets/pull/2326#discussion_r432227353

**Comment by szha** [comment]
@epicfaace @teetone I pulled the latest master branch, stopped and deleted the server, and restarted the server. The error is exactly the same in both the CLI case and the web page. Could you please reopen and take another look? Thanks.

**Comment by szha** [comment]
For now I reverted to the last release in July which works.

**Comment by szha** [comment]
Actually, for the July release 0.5.20, with a fresh server, database, and fresh install of codalab through pip, I can upload bundle but running the job through the CLI fails.
```
[ec2-user@ip-10-20-14-125 codalab-worksheets]$ cl upload LICENSE.txt
Preparing upload archive...
Uploading LICENSE.txt (0x781a4d89e2d24a41a5f4b0034192c24f) to http://54.162.80.105

[ec2-user@ip-10-20-14-125 codalab-worksheets]$ cl run :LICENSE.txt "cat LICENSE.txt"
UsageError: Unexpected metadata key: exclude_patterns
```

**Comment by epicfaace** [comment]
@nelson-liu this might be related to the change in #2344. Is `exclude_patterns` supposed to be optional?

**Comment by szha** [comment]
it would be good (at least for my confidence in the project) if the project starts to:
- conduct integration tests like this for verifying releases
- stabilize the API, adopt semantic versioning, and make a 1.0 release.

**Comment by nelson-liu** [comment]
are you sure your server is fresh? The following is working for me:

```
(base) nfliu at mazama in ~
$ conda create -n cl_test python=3.6
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/nfliu/miniconda3/envs/cl_test

  added / updated specs:
    - python=3.6


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2020.6.24-0
  certifi            pkgs/main/osx-64::certifi-2020.6.20-py36_0
  libcxx             pkgs/main/osx-64::libcxx-10.0.0-1
  libedit            pkgs/main/osx-64::libedit-3.1.20191231-h1de35cc_1
  libffi             pkgs/main/osx-64::libffi-3.3-hb1e8313_2
  ncurses            pkgs/main/osx-64::ncurses-6.2-h0a44026_1
  openssl            pkgs/main/osx-64::openssl-1.1.1g-h1de35cc_0
  pip                pkgs/main/osx-64::pip-20.1.1-py36_1
  python             pkgs/main/osx-64::python-3.6.10-hf48f09d_2
  readline           pkgs/main/osx-64::readline-8.0-h1de35cc_0
  setuptools         pkgs/main/osx-64::setuptools-49.2.0-py36_0
  sqlite             pkgs/main/osx-64::sqlite-3.32.3-hffcf06c_0
  tk                 pkgs/main/osx-64::tk-8.6.10-hb0a8c7a_0
  wheel              pkgs/main/osx-64::wheel-0.34.2-py36_0
  xz                 pkgs/main/osx-64::xz-5.2.5-h1de35cc_0
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate cl_test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) nfliu at mazama in ~
$ conda activate cl_test
(cl_test) nfliu at mazama in ~
$ pip install -U codalab
Collecting codalab
  Downloading codalab-0.5.20.tar.gz (278 kB)
     |████████████████████████████████| 278 kB 1.5 MB/s
Collecting bottle==0.12.18
  Using cached bottle-0.12.18-py3-none-any.whl (89 kB)
Collecting docker==4.2.2
  Using cached docker-4.2.2-py2.py3-none-any.whl (144 kB)
Processing ./Library/Caches/pip/wheels/4f/de/68/60ec9fe9db793c532b565a0570e99d3d636edb22475ed63373/marshmallow_jsonapi-0.15.1-py2.py3-none-any.whl
Collecting marshmallow==2.15.1
  Using cached marshmallow-2.15.1-py2.py3-none-any.whl (43 kB)
Requirement already satisfied, skipping upgrade: setuptools>=40.0.0 in ./miniconda3/envs/cl_test/lib/python3.6/site-packages (from codalab) (49.2.0.post20200714)
Collecting argcomplete==1.12.0
  Using cached argcomplete-1.12.0-py2.py3-none-any.whl (38 kB)
Processing ./Library/Caches/pip/wheels/e5/9d/ad/2ee53cf262cba1ffd8afe1487eef788ea3f260b7e6232a80fc/PyYAML-5.3.1-cp36-cp36m-macosx_10_9_x86_64.whl
Processing ./Library/Caches/pip/wheels/1c/02/08/5519c2e5ce9888173991b4b979d5a0407232bd92620ac40807/psutil-5.6.6-cp36-cp36m-macosx_10_9_x86_64.whl
Collecting six==1.11.0
  Using cached six-1.11.0-py2.py3-none-any.whl (10 kB)
Collecting SQLAlchemy==1.3.18
  Using cached SQLAlchemy-1.3.18-cp36-cp36m-macosx_10_14_x86_64.whl (1.2 MB)
Processing ./Library/Caches/pip/wheels/a1/d5/fc/fddf5870c0fb0b755abdf41f4889ef54742ee21fff693aae22/watchdog-0.10.3-cp36-cp36m-macosx_10_9_x86_64.whl
Processing ./Library/Caches/pip/wheels/c5/fc/87/bd3c9942ab2366b4838ea6588f98fd096facb0dbf123e57399/fusepy-2.0.4-cp36-none-any.whl
Collecting python-dateutil==2.8.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Processing ./Library/Caches/pip/wheels/16/1b/c2/50f7a0b153931fe3f39bd642805f572ed89431fa3b091f4cb0/diffimg-0.2.3-py3-none-any.whl
Collecting selenium==3.141.0
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting websocket-client>=0.32.0
  Using cached websocket_client-0.57.0-py2.py3-none-any.whl (200 kB)
Collecting requests!=2.18.0,>=2.14.2
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting importlib-metadata<2,>=0.23; python_version == "3.6"
  Using cached importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)
Processing ./Library/Caches/pip/wheels/0b/04/79/c3b0c3a0266a3cb4376da31e5bfe8bba0c489246968a68e843/pathtools-0.1.2-cp36-none-any.whl
Collecting Pillow>=4.3
  Using cached Pillow-7.2.0-cp36-cp36m-macosx_10_10_x86_64.whl (2.2 MB)
Collecting urllib3
  Using cached urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ./miniconda3/envs/cl_test/lib/python3.6/site-packages (from requests!=2.18.0,>=2.14.2->docker==4.2.2->codalab) (2020.6.20)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting zipp>=0.5
  Using cached zipp-3.1.0-py3-none-any.whl (4.9 kB)
Building wheels for collected packages: codalab
  Building wheel for codalab (setup.py) ... done
  Created wheel for codalab: filename=codalab-0.5.20-py3-none-any.whl size=324125 sha256=9f1809b19f5f4d49ea69c53be6234da3f5760ce9ff1138b3c9a6991fe1294004
  Stored in directory: /Users/nfliu/Library/Caches/pip/wheels/95/cd/1c/54d9de148327d6f26d45212af202a07989254c81a3be3703f3
Successfully built codalab
Installing collected packages: bottle, six, websocket-client, idna, urllib3, chardet, requests, docker, marshmallow, marshmallow-jsonapi, zipp, importlib-metadata, argcomplete, PyYAML, psutil, SQLAlchemy, pathtools, watchdog, fusepy, python-dateutil, Pillow, diffimg, selenium, codalab
Successfully installed Pillow-7.2.0 PyYAML-5.3.1 SQLAlchemy-1.3.18 argcomplete-1.12.0 bottle-0.12.18 chardet-3.0.4 codalab-0.5.20 diffimg-0.2.3 docker-4.2.2 fusepy-2.0.4 idna-2.10 importlib-metadata-1.7.0 marshmallow-2.15.1 marshmallow-jsonapi-0.15.1 pathtools-0.1.2 psutil-5.6.6 python-dateutil-2.8.1 requests-2.24.0 selenium-3.141.0 six-1.11.0 urllib3-1.25.10 watchdog-0.10.3 websocket-client-0.57.0 zipp-3.1.0
(cl_test) nfliu at mazama in ~
$ cl st
codalab_home: /Users/nfliu/.codalab
session: 37929
client_version: 0.5.20
server_version: 0.5.20
address: https://worksheets.codalab.org
username: nfliu
current_worksheet: home-nfliu(0x6c26647dad70404eb6ea6a01ed8b6a99)
user: nfliu(0x23c379b450cb4552b314268c413e2468)
(cl_test) nfliu at mazama in ~
$ echo "some license" > LICENSE.txt
(cl_test) nfliu at mazama in ~
$ cl upload LICENSE.txt
Preparing upload archive...
Uploading LICENSE.txt (0x745c7c23014548ccbbf2fb08b12c823a) to https://worksheets.codalab.org
Sent 0.00MiB / 0.00MiB (100.0%) [0.00MiB/sec]
0x745c7c23014548ccbbf2fb08b12c823a
(cl_test) nfliu at mazama in ~
$ cl run :LICENSE.txt "cat LICENSE.txt"
0x44774a774e264006af00f020bf1ab9c6
```

**Comment by szha** [comment]
> address: https://worksheets.codalab.org

@nelson-liu I'm not uploading to this.

**Comment by nelson-liu** [comment]
yes, i know, but since you said that 54.162.80.105 is a "a fresh server, database", it should be the same as  worksheets.codalab.org

Can you run `cl st` and verify that you see:
```
client_version: 0.5.20
server_version: 0.5.20
```

**Comment by nelson-liu** [comment]
I remember seeing this exact error message when there was a mismatch between client version and server version—i think that's the culprit here as well.

**Comment by szha** [comment]
@nelson-liu yes I think you are right. thanks for the magic. let me look into how I got it into this state...
```
$ cl st
...
client_version: 0.5.20
server_version: 0.5.9
...
```

**Comment by szha** [comment]
things are working as expected after rebuilding 0.5.20. thanks!

**Comment by nelson-liu** [comment]
no worries, glad it worked out—thanks for looping back.

**Comment by szha** [comment]
no problem. one item that could have helped me is the version check in the CLI. it looks like the CLI already has the capability that it can give an error that warns the version mismatch between server and client. the semantic version probably wouldn't have helped given that it requires forward compatibility guarantee on the server side.

**Comment by epicfaace** [comment]
> @nelson-liu this might be related to the change in #2344. Is `exclude_patterns` supposed to be optional?

Is this not an issue then?

**Comment by nelson-liu** [comment]
> Is this not an issue then?

@epicfaace yeah, it should be optional (default is `[]`) i can't figure out where it's required, though...

**Comment by epicfaace** [comment]
@nelson-liu by default, calling `Metadata.validate()` with metadata specs treats all fields as required unless they have `generated=True` set. I changed this behavior in #2690 by adding an `optional` keyword -- when this keyword is set to true for a field, the field is also treated as non-required (so required is still the default, as per the previous behavior). We should probably set `optional=True` for `exclude_patterns` and other optional fields.

**Comment by epicfaace** [comment]
Alternatively, perhaps it would be cleaner to automatically treat MetadataSpecs as optional if they already have a `default` defined?

**Comment by nelson-liu** [comment]
> Alternatively, perhaps it would be cleaner to automatically treat MetadataSpecs as optional if they already have a default defined?

I think this is a good change.

**Comment by nelson-liu** [comment]
though I think it might be simpler to just add the `optional` key for these few instances.
