### ISSUE TITLE
SlurmWorkerManager shared output path should be all-writeable by default

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2689]
https://github.com/codalab/codalab-worksheets/blob/2de9c561bfd9b2c1a39c8773fd9e3766bb96b311/codalab/worker_manager/slurm_batch_worker_manager.py#L241

Else, other users that run the workermanager get:

```
PermissionError: [Errno 13] Permission denied: '/scr/scr-with-most-space/slurm-codalab-worker-scratch/user-codalab-slurm-worker-a2b76ac7'
srun: error: jagupard21: task 0: Exited with exit code 1
```

**Comment by percyliang** [comment]
Why does this need to be shared?  Shouldn't each user have its own scratch space?

**Comment by nelson-liu** [comment]
> Why does this need to be shared? Shouldn't each user have its own scratch space?

Yeah, you could do this too, either sounds fine to me. If you a lot of users, the scratch space can get cluttered pretty easily with `<user>-slurm-codalab-worker-scratch` directories.

**Comment by percyliang** [comment]
I thought workers aren't designed to share scratch directories, though it would be nice to have a common cache for dependencies...

**Comment by nelson-liu** [comment]
these aren't the worker's scratch directories—it's a folder to stores each worker's scratch directories. e.g., right now, the structure is:

```
/slurm-codalab-worker-scratch/pliang-cl-workdir-18291
/slurm-codalab-worker-scratch/pliang-cl-workdir-11271
/slurm-codalab-worker-scratch/pliang-cl-workdir-92829
/slurm-codalab-worker-scratch/nfliu-cl-workdir-19217
/slurm-codalab-worker-scratch/nfliu-cl-workdir-11211
/slurm-codalab-worker-scratch/nfliu-cl-workdir-13719
```

where `{user}-cl-workdir-{hash}` is the actual scratch directory used by the worker.

right now, `slurm-codalab-worker-scratch` is not writable by default. So if I make it (when i run the workermanager for the first time), you wouldn't be able to write to it.

**Comment by percyliang** [comment]
Hm, maybe `<user>-slurm-codalab-worker-scratch` would be logically cleaner?  That way it's easier for people to maintain their own scratch space - e.g., delete their own stuff without worrying about deleting someone else's.

**Comment by nelson-liu** [comment]
yeah, i agree—let's do that instead to fix this issue.
