### ISSUE TITLE
Side panel: Worksheet permissions not displaying correctly

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#274]
Repro:

- Go to any dashboard
- Click on one of the worksheets under "My Worksheets" -- not on the name, one the white space so the side panel updates
- Notice that the permissions are all empty

Problem: When a worksheet loads, all of the information needed to render the worksheet is interpreted by the server and then loaded to the client (it's a big data dump). The "My Worksheets" table is built using a `wsearch` in Markdown, and so when the table is generated only the information needed to display the table is sent to the client. The permission information of the worksheet is not sent. When the user clicks the table row of the worksheet and it is displayed in the side panel, there are no API calls involved -- the client simply displays the cached data about the worksheet, even though it does not include some of the needed information.

Proposed solutions:

- Call the REST API every time a new worksheet is selected and the side panel needs to update
- Change the interpretation code so that all of the data needed to display permissions is loaded to the client

**Comment by maxwang7** [comment]
@percyliang @kashizui Thoughts on which proposed solution would be best to take?

**Comment by percyliang** [comment]
I think we should make a second API call to fetch more information about
the subworksheet.

In general, the first call to the worksheet should be lean and only grab
the minimal information to render the page.  All other information should
be grabbed when the cursor goes over the appropriate item.  This is how it
is for bundles (although currently, more information than desired is
transmitted over on the first call).
