### ISSUE TITLE
tensorflow.python.framework.errors_impl.PermissionDeniedError: Read-only file system

### ISSUE THREAD

**Issue by zty12713** [codalab/codalab-worksheets#2743]
**Describe the bug**
When I tried to run commands to reproduce the inference file using TensorflowNMT with my vocab files and trained model, I ran into an error stating "tensorflow.python.framework.errors_impl.PermissionDeniedError: ../nmt_model/vocab_enhanced.sql; Read-only file system" (see the first screenshot). I suspect TensorflowNMT was trying to write vocab_enhanced.sql under folder nmt_model (one of the dependencies of this run). I uploaded this folder earlier, and it said I have permission "all" on this bundle (see the second screenshot). So, I feel I should be able to write vocab_enhanced.sql under this bundle. Then, how did this error come up?

**Codalab Information**
- *Your username*: zty12713
- *UUID of worksheet where problem occurred*: 0x4724a7e9cc5643ac9f21581c2983003f
- *UUID of problem bundle (please don't delete)*: 0xa9cdc5cd520b408ca6e4d1d00c5dfd02 (error due to the dependency 0x75e701cc0d2d4f31ae0c20e850b1561b)
- *Error message received from Codalab (if applicable)*: tensorflow.python.framework.errors_impl.PermissionDeniedError: ../nmt_model/vocab_enhanced.sql; Read-only file system
 - *OS (if on CLI)*: Windows 10 Home
 - *Codalab CLI Version (if on CLI)*: 0.5.21
 - *Browser (if on Web)*: Google Chrome 84.0.4147.125

**To Reproduce**
Steps to reproduce the behavior :
1. cl run "input:0x5ad987" "nmt_data:0xc86fa6" "nmt_model:0x75e701" "nmt:0x2e94ae" "cd nmt; python3 -m nmt.nmt --out_dir=../nmt_model/best_bleu --inference_input_file=../input --inference_output_file=../prediction.txt" -n run-prediction --request-network --request-docker-image codalab/codalab-legacy:py37
2. Wait until the error appears
3. See error

**Expected behavior**
prediction.txt is produced by the run (under the run bundle root directory).

**Screenshots**
![codalab_error](https://user-images.githubusercontent.com/32921051/89968326-8dd80f00-dc21-11ea-9a40-e888d3fe47a8.PNG)
![bundle_permission](https://user-images.githubusercontent.com/32921051/89968343-97617700-dc21-11ea-88c4-6686506e3d32.PNG)

**Additional context**

**Comment by teetone** [comment]
Hi @zty12713, all dependencies are mounted as read-only, so in your case, a new file cannot be written out in that particular path. A way around this would be to create a new file outside of the dependencies.

https://codalab-worksheets.readthedocs.io/en/latest/FAQ/#when-i-try-to-execute-a-command-like-make-on-codalab-it-fails-because-of-read-only-permissions-what-do-i-do

**Comment by zty12713** [comment]
> Hi @zty12713, all dependencies are mounted as read-only, so in your case, a new file cannot be written out in that particular path. A way around this would be to create a new file outside of the dependencies.
> 
> https://codalab-worksheets.readthedocs.io/en/latest/FAQ/#when-i-try-to-execute-a-command-like-make-on-codalab-it-fails-because-of-read-only-permissions-what-do-i-do

Thanks a lot! I think this is the issue here.

However, a quite tricky thing is that whenever I try to create a duplicate, TensorflowNMT seems to not be able to recognize the duplicate as nmt_model even if it has the same name and contains the same files.

More specifically, I have "nmt_model_orig:0x75e701" and "cp -RL nmt_model_orig nmt_model" as part of my cl run command. One of the steps of the run is to load hyperparameters from nmt_model/best_bleu/hparams, then "# Loading hparams from ../nmt_model/best_bleu/hparams" appears in the STDOUT. Now, with nmt_model as the created duplicate, "# Creating output directory ../nmt_model/best_bleu" appears in the STDOUT instead. This only appears when TensorFlowNMT thinks this output directory doesn't exist, but in fact, the duplicate of bundle 0x75e701 with the exact name nmt_model exists (at the parent directory of my current working directory, which is why there is ../) and has a folder named best_bleu under it.

Is there any way to make TensorflowNMT recognize the existence of nmt_model, even if nmt_model is a duplicate?

**Comment by zty12713** [comment]
> > Hi @zty12713, all dependencies are mounted as read-only, so in your case, a new file cannot be written out in that particular path. A way around this would be to create a new file outside of the dependencies.
> > https://codalab-worksheets.readthedocs.io/en/latest/FAQ/#when-i-try-to-execute-a-command-like-make-on-codalab-it-fails-because-of-read-only-permissions-what-do-i-do
> 
> Thanks a lot! I think this is the issue here.
> 
> However, a quite tricky thing is that whenever I try to create a duplicate, TensorflowNMT seems to not be able to recognize the duplicate as nmt_model even if it has the same name and contains the same files.
> 
> More specifically, I have "nmt_model_orig:0x75e701" and "cp -RL nmt_model_orig nmt_model" as part of my cl run command. One of the steps of the run is to load hyperparameters from nmt_model/best_bleu/hparams, then "# Loading hparams from ../nmt_model/best_bleu/hparams" appears in the STDOUT. Now, with nmt_model as the created duplicate, "# Creating output directory ../nmt_model/best_bleu" appears in the STDOUT instead. This only appears when TensorFlowNMT thinks this output directory doesn't exist, but in fact, the duplicate of bundle 0x75e701 with the exact name nmt_model exists (at the parent directory of my current working directory, which is why there is ../) and has a folder named best_bleu under it.
> 
> Is there any way to make TensorflowNMT recognize the existence of nmt_model, even if nmt_model is a duplicate?

To provide a few more details, by "Tensorflow thinks this output directory doesn't exist", it refers to tf.gfile.Exists('../nmt_model/best_bleu') is evaluated as False specifically. An interesting thing is that I also test the command under basically the same setting (i.e. same folder names and directory relationships) on Google Colab, and tf.gfile.Exists('../nmt_model/best_bleu') is evaluated as True there. I'm not sure why there is a discrepancy.

**Comment by teetone** [comment]
Hi @zty12713 sorry for the late response. I think I might have a simpler solution for your problem. Instead of running `cp -RL nmt_model_orig nmt_model`, can you instead run:

```
cl run "input:0x5ad987" "nmt_data:0xc86fa6" "nmt_model:0x75e701" "nmt:0x2e94ae" "cd nmt; python3 -m nmt.nmt --out_dir=/home --inference_input_file=../input --inference_output_file=../prediction.txt" -n run-prediction --request-network --request-docker-image codalab/codalab-legacy:py37
```

This is the same command as you originally posted, but I changed `out_dir` to the home directory. I think this will avoid the complication you had with Tensorflow not being able to find the output directory.

**Comment by teetone** [comment]
Hi @zty12713 will close this issue for now. Please feel free to open another issue if this issue persists.
