### ISSUE TITLE
Workers getting assigned more bundles than they can run

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#2746]
**Describe the bug**
As of today, on the SM deployment running v0.5.20 we've started having workers that are getting assigned jobs whose total requested CPU numbers are more than what's available on the worker. In general we have workers that have N CPUs and jobs also request N CPUs. Today we started seeing workers with `2N/N` or `3N/N` CPU usage on the `cl workers` output command, and the runs have been showing the `Unexpectedly unable to assign enough resources to bundle 0x123456567897812e: Requested more CPUs (N) than available (0 currently out of N on the machine)` error message.

**Codalab Information**
- SM internal deployment, running AWS worker manager with, everything is on v0.5.20

**To Reproduce**
Unclear

**Expected behavior**
Workers should not get bundles assigned to them beyond their capacity.

**Comment by teetone** [comment]
I was able to reproduce this in `dev` with our stress test script. I'm still debugging and trying to figure out why it's over-assigning bundles to workers.

@bkgoksel Is this an issue that you have noticed with just `v0.5.20`? Judging from https://github.com/codalab/codalab-worksheets/issues/1911, it seems like the issue has been around for quite some time.
