### ISSUE TITLE
Upgrade frontend to typescript

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2749]
This will add strict typechecking with our frontend, which should help prevent more errors and improve the developer experience.

This would involve:
- create a `tsconfig.json` and migrate all `.js` files to `.tsx`
- define interfaces for some of the most common data structures -- we can just use `any` for additional types that we don't want to give types to for now
- eventually, make sure everything is typed and we don't use `any` unless absolutely necessary

**Comment by epicfaace** [comment]
https://create-react-app.dev/docs/adding-typescript/

**Comment by epicfaace** [comment]
https://github.com/kulshekhar/ts-jest

**Comment by epicfaace** [comment]
https://www.typescriptlang.org/docs/handbook/compiler-options.html

`allowJs` - true
`noImplicitAny` - false

**Comment by leilenah** [comment]
@epicfaace can I close this?

**Comment by leilenah** [comment]
closing for now but @epicfaace re-open if you feel strongly
