### ISSUE TITLE
Directives Don't Refresh Immediately

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#277]
Reproduce:

Go to any worksheet and add a directive.
Save and go back and view the worksheet.
The directive does not appear.
Flipping back and forth a few times will create the directive.

**Comment by maxwang7** [comment]
Time estimate: Hard to do now because it's an open bug. My best guess: 1-2 hours to figure out the problem, 1-2 hours to make the fix.

**Comment by maxwang7** [comment]
I don't think this is a bug, pretty sure this is our worksheets API being slow since when we save changes, we do a full worksheet reload. @percyliang Maybe it would help the user if we having a loading indicator? But that may be annoying as well...

**Comment by percyliang** [comment]
We do have a loading indicator.

I thought it was a bug because you were doing it on a small worksheet.

**Comment by maxwang7** [comment]
I'll investigate more, but I'm not finding a problem with it yet.

**Comment by maxwang7** [comment]
I found the problem. It's with removing elements. Test worksheet: https://worksheets.codalab.org/worksheets/0x06fe33f2b86f4ee08e4a9fd25054c0c1/

**Comment by maxwang7** [comment]
I'm no longer able to reproduce this bug. Unfortunately the link above no longer goes to a worksheet. I've also tried many ways of removing directives and changing worksheets, but the only kind of problem I've been able to find is lagginess, no problem that indicates it's a problem with the frontend rendering code.

**Comment by maxwang7** [comment]
I'm closing this issue, will reopen if we're able to reproduce it in the future
