### ISSUE TITLE
Separate out cleanup logic from the worker

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2771]
**Describe the bug**

Currently, the cleanup logic resides inside the worker loop and only executes on a happy path. We should see if this can be separated out and cleaned up no matter what.

https://github.com/codalab/codalab-worksheets/blob/bf744068aaddccd2509e31a4c3666768bc3b0d2f/codalab/worker/worker.py#L252-L297

**Comment by yiboliu** [comment]
@teetone sorry I'm a bit confused. To my understanding the worker loop is going exit anyway, and `cleanup()` will be called in the end as it's outside of the loop. Why do we still want to cleanup no matter what?
