### ISSUE TITLE
pile of schemas rendering is awkward

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2776]
Now that we render schema definitions (` % schema ...`), they kind of pile up at the beginning of a worksheet, which is ugly:
![Screenshot from 2020-08-23 21-17-50](https://user-images.githubusercontent.com/435384/91005151-09737d80-e58b-11ea-984c-1b56097f25e6.png)

Options:
1) Reduce the amount of vertical space taken by each block.  We'd probably have to make this really thin with no spacing between schema blocks. 
2) Have an explicit verbose option...this might lead to complexity and be confusing.

**Comment by epicfaace** [comment]
Could we just not include line breaks between consecutive schema blocks?

**Comment by yipenghe** [comment]
Maybe have a "verbose"  panel where user can check options to decide whether to show certain types of items or not, for now just schema-items. Maybe we can also move the expansion mode into this panel and make it like a configuration panel for the worksheet look. This might bring some complexity in terms of the focusing though

**Comment by robinjia** [comment]
+1 was just considering filing an issue about this :)
