### ISSUE TITLE
Can't import user module in directory 

### ISSUE THREAD

**Issue by jeongHwarr** [codalab/codalab-worksheets#2778]
**Describe the bug**
My bundle can't import user module in directory. I zipped the entire source folder and uploaded it from the website. I confirmed that all files were uploaded well.(https://worksheets.codalab.org/bundles/0x0cab5bc0863245e590046db0fb4e3e2d)

However, when I try this command,  
```
cl run :valid.csv :CheXpert-v1.0-small :Chexpert "python Chexpert/bin/test.py --in_csv_path valid.csv --out_csv_path p
redictions.csv" -n run-prediction
```

 I got an error message. 
`ImportError: No module named data.dataset`

Why is this problem occurring? I did everything in a web browser. 
The address of my worksheet  is here. 
https://worksheets.codalab.org/worksheets/0xc55db485a01145d1b5f5f7cffa1988ee

**Codalab Information**
- *Your username*: 
- *UUID of worksheet where problem occurred*:  https://worksheets.codalab.org/worksheets/0xc55db485a01145d1b5f5f7cffa1988ee 
- *UUID of problem bundle (please don't delete)*: 0x46322ea2f0344f62be2977c4a73687e1
- *Error message received from Codalab (if applicable)*: ImportError: No module named data.dataset
 - *OS (if on CLI)*: Windows 
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*; Chrome

**Comment by epicfaace** [comment]
Perhaps you need to add an `__init__.py` to the data directory?

**Comment by percyliang** [comment]
Closing for now, feel free to re-open if it is still an issue.

**Comment by jeongHwarr** [comment]
@epicfaace @percyliang 
Thank you for your reply! 
Actually, I haven't tried the suggested method yet.
If the problem is not resolved after trying, I will open the issue again. Thank you.
