### ISSUE TITLE
alembic upgrade head gives error on new deployments

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#279]
On fresh deployment (using fabfile), the up to date schema is loaded onto mysql but `alembic upgrade head` gives error:`sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1060, "Duplicate column name 'owner_id'") [SQL: u'ALTER TABLE bundle ADD COLUMN owner_id INTEGER']` , as if it doesn't know what revision it's currently at.

**Comment by kashizui** [comment]
The code that is causing problems with Alembic migrations:
https://github.com/codalab/codalab-cli/blob/master/alembic/env.py#L57-L77
https://github.com/codalab/codalab-cli/blob/master/codalab/model/bundle_model.py#L98

Basically, instantiating a `BundleModel()` will automatically create all the tables according to the schemas in `tables.py`. This will cause problems if the Alembic doesn't expect these tables to be created already.

Deployment is also possibly missing an `alembic stamp head` call.

I'll need to spend more time on this to fully understand what's going on.

**Comment by fabeschan** [comment]
Added `alembic stamp head` to deployment-from-scratch. Seems to work.
