### ISSUE TITLE
Field-editing not handling some authorization errors

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#28]
<a href="https://github.com/kashizui"><img src="https://avatars.githubusercontent.com/u/614837?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kashizui](https://github.com/kashizui)**
_Monday Nov 23, 2015 at 07:33 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1429_

----

Unauthenticated users can attempt to "edit" the title of the worksheet, without displaying the authorization error that the server responds with.

**Comment by percyliang** [comment]
Don't see the bug anymore.
