### ISSUE TITLE
Test dev mode (-d flag)

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2819]
There was a strange issue in #2750 in which running codalab_service.py with the `-d` flag would give me a `PackageNotFoundError` (similar to the error seen in #2800).

It turns out that the issue was that that PR had mounted the entire Codalab directory in dev mode, which caused the server to break. (Fix: https://github.com/codalab/codalab-worksheets/pull/2750/commits/bc57a1e9ca0434d9f62f4174fe6b026e7dff7784)

We should add a CI check that makes sure that the server can still run and function properly in dev mode.

**Comment by yiboliu** [comment]
This is also seen if I reinstall the codalab package and run with `codalab-service start`
