### ISSUE TITLE
failure with "list index out of range" without further detail

### ISSUE THREAD

**Issue by YichenGong** [codalab/codalab-worksheets#282]
It's not clear why it happens. I have no clue how to solve this.

https://worksheets.codalab.org/bundles/0x825c3ef2286c4528a9bc776fee3c58d3/

**Comment by kashizui** [comment]
Thanks for the report -- we had a faulty worker which I've now taken down. Try rerunning your jobs and things should work now!

**Comment by YichenGong** [comment]
Thank you.
