### ISSUE TITLE
New worksheet creation silently fails when not signed in

### ISSUE THREAD

**Issue by kohpangwei** [codalab/codalab-worksheets#283]
If you're not signed in and you click on "New Worksheet" and then click "Cancel", you can no longer click the "New Worksheet" button until you refresh the page.

Steps to reproduce:
0) Sign out
1) Go to some CodaLab worksheet (e.g., https://worksheets.codalab.org/worksheets/0x20ce2b583c7a4ddd9496b480c0bc1b79/)
2) Click the "New Worksheet" button in the top right
3) Click "Cancel" without typing anything. This creates an uncaught TypeError: Cannot read property 'user_name' of null at toggleNewWorksheet.
4) Try to click "New Worksheet" again. 

For usability, it might also be helpful to return the "Not authorized" message upon clicking on "New Worksheet" when you're not signed in (or just grey the button out), instead of letting the user type in a worksheet name before saying that it's not authorized in the console.

**Comment by kashizui** [comment]
fix'd
