### ISSUE TITLE
Permissions for downloading predicitions

### ISSUE THREAD

**Issue by RishabGoel** [codalab/codalab-worksheets#285]
I was trying to download a model predicitions and got the following error...
User rishab does not have sufficient permissions on bundle (have none, need read).
how do i get around his??
Thanks in advance

**Comment by fabeschan** [comment]
Can you provide more information please? Otherwise this just looks like you don't have permissions to access it

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1076
