### ISSUE TITLE
Automate server deployment

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#286]
Remove fabfile from codalab-worksheets repo and switch over to ansible and put in a separate deployment repo.

Should be able to run a single command to bring up a new CodaLab webserver/master/worker stack.

**Comment by fabeschan** [comment]
Agreed to put this in low priority since server deployment-from-scratch is rare and there are docs we can follow already. Instead will wrap up deployments based on code updates and spend time on other more pressing things.

**Comment by fabeschan** [comment]
Done. Checkout `codalab-deployment/worksheets/ansible/README/md` of internal deployment code for details of automated server deployments.
