### ISSUE TITLE
CodaLab emails are getting sent to user's spam folder

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2868]
**Describe the bug**
Account verification and newsletter emails are getting sent to the spam folders of our users. It might be worth looking into these guidelines: https://support.google.com/mail/answer/81126?hl=en.

**Comment by epicfaace** [comment]
https://support.sendgrid.com/hc/en-us/articles/360041360914-What-to-do-if-I-m-blacklisted-

**Comment by epicfaace** [comment]
- Contact Sendgrid
- Contact Slack

**Comment by epicfaace** [comment]
This works now -- I'm not getting messages to spam anymore.
