### ISSUE TITLE
scrolling using keyboard shortcuts is 

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2873]
When you hit 'j' or 'k' to scroll down/up on a long worksheet, the worksheet scrolls with each key press, which leads to jerky behavior.  The desired behavior (as it was before) is to scroll only when the selected bundle cursor is near the edge and scroll a more significant amount so that scrolling happens less frequently.

**Comment by yipenghe** [comment]
refer to #1553 and #1528
