### ISSUE TITLE
tables shouldn't have scrollbars

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2875]
There should only be one scrollbar for the worksheet, but now for some reason, tables have scroll bars too, which makes it very confusing.
![Screenshot from 2020-09-22 01-17-28](https://user-images.githubusercontent.com/435384/93858792-92a4cf80-fc71-11ea-823a-70b247f2bd89.png)

**Comment by yuqijin** [comment]
The scroll bar results from #2835. And it is because a sticky header is provided now for the result table since the user wants to lock the column names when they scroll the table.
