### ISSUE TITLE
Transfer MLcomp

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#289]
- Figure out how to structure datasets and programs (no dataset/program matrix view anymore)
- Copy all public things over

**Comment by kashizui** [comment]
Will this probably involve migrating things directly from the server, or can everything be downloaded straight from the website?

**Comment by percyliang** [comment]
Would do things directly from the server.

The main thing to figure out is how we support the view: for each dataset,
ranking of the programs/runs based on accuracy.

Note that we already have some support for MLcomp checked into CodaLab.

**Comment by kashizui** [comment]
Ah that's what that script was.

Did we want to copy over user's submissions on the datasets as well? Or just the datasets themselves?

**Comment by percyliang** [comment]
Datasets, programs, and rerun all the programs on datasets.

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1054
