### ISSUE TITLE
cl search -w WORKSHEET_SPEC doesn't seem to filter by worksheet

### ISSUE THREAD

**Issue by kelvinguu** [codalab/codalab-worksheets#289]
For example:
`cl search -w nlp::mru state=running`

This just returns any bundles running on CL.
In case this matters, nlp::mru happens to be non-public.

**Comment by percyliang** [comment]
-w nlp::mru is equivalent to doing `cl work nlp::mru` first and then
running the command.

You want to do:
cl search host_worksheet=$(cl work nlp::mru -u)
