### ISSUE TITLE
[FEATURE REQUEST] Modify the algorithm of writing alembic/versions py files

### ISSUE THREAD

**Issue by yiboliu** [codalab/codalab-worksheets#2896]
**Is your feature request related to a problem? Please describe.**
The current algorithm is putting assigning values code above the importing modules. This is inconsistent with flake8. 
**Describe the solution you'd like**
Modify the algorithm so that order of writing code changes. We don't have to fix them manually each time. 
**Describe alternatives you've considered**

**Additional context**

**Comment by percyliang** [comment]
People making migrations can just fix it manually for now.
