### ISSUE TITLE
increase the space in the side panel between sections

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#29]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Monday Dec 07, 2015 at 05:34 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1479_

----

In the side panel of the worksheet interface, there should be more space between 'Contents', 'Metadata', and 'Host Worksheets' when the sections are collapsed.

Also, under 'Contents', if it's a file, no need to show the word 'contents' again.

Remember to edit the less files, not css.

**Comment by ChengshuLi** [comment]
Feel free to checkout PR
