### ISSUE TITLE
The Great Migration

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#290]
We are moving worksheets.codalab.org into container services hosted in non-classic VMs in Azure. 

Verification checklist: (i.e. things we are testing. Add more entries if necessary)

- [x] create account

- [x] account login

- [x] help button

- [x] run date

- [x] create bundle(s)

- [x] create worksheets

- [x] remove worksheets

- [x] show/render worksheets

- [x] show bundle directories on worksheet

- [x] add/rm/ls partitions

- [x] run a program with dependencies

- [x] run a GPU job

- [x] cl up

- [x] download a bundle

- [x] mimic a run

- [x] monitor.py

- [x] maintenance mode

Keep this up to date

Things that need ironing out because I'm not sure how:

- [x]  SSL stuff

- [x] database schema upgrades (alembic)

**Comment by kashizui** [comment]
I copied over the #1 model from the cs224n class, and mimicked it with a different dataset, and it worked.
http://vm-clws-prod-server-0.eastus.cloudapp.azure.com/bundles/0x3e6a9dc063604fec8bfac4fc4046945d/

**Comment by kashizui** [comment]
@fabeschan I can help setup the SSL stuff, I'll need to peruse your deployment code a bit more first though.

**Comment by fabeschan** [comment]
Awesome! Let me know if you find it hard to understand anything. I can explain, refactor, and/or restructure parts if needed.

**Comment by fabeschan** [comment]
Running `venv/bin/alembic upgrade REV` and `venv/bin/alembic downgrade REV` from within `cl.sh`'s shell seems to work (verified changes in mysql schema). Is this good enough @kashizui ? However I'd imagine the scripts will need some tweaking

**Comment by kashizui** [comment]
That should be good enough for now. Any changes that we need to make to the alembic process is independent of this migration anyway. For reference, these are the culprit lines:

https://github.com/codalab/codalab-cli/blob/master/alembic/env.py#L57-L77
https://github.com/codalab/codalab-cli/blob/master/codalab/model/bundle_model.py#L98
