### ISSUE TITLE
Ensure codalab is fast with 50 workers

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2900]
- Debug when we have lots (50+) of workers
- Why are things so slow?
- Consider this: maybe use websockets instead of checking in every second with HTTP requests

**Comment by teetone** [comment]
At one point, codalab.stanford.edu had 50+ workers and worksheets.codalab.org had 60+ and both instances seem to be running fine.

**Comment by epicfaace** [comment]
Great!
