### ISSUE TITLE
Edit mode not preserving things properly

### ISSUE THREAD

**Issue by wooters** [codalab/codalab-worksheets#291]
Entering and then immediately leaving edit mode on a worksheet doesn't seem to preserve formatting.

Example:
```
$ test_cmd=$(cat <<EOF
> echo hello
> echo hello2
> EOF
> )

$ cl run -n test_break --- "$test_cmd"
0xad88a05b2d1141338425ef6b6b2c6060

$ cl cat ^1
name    perm  size
------------------
stderr  0644     0
stdout  0644    13

$ cl cat ^1/stdout
hello
hello2
```
Notice that the `test_cmd` will contain a newline since there was no backslash at the end of the `echo hello` line.

Even with this extra newline, the bundle looks ok in the worksheet.

![image](https://cloud.githubusercontent.com/assets/2111202/24822710/2273f294-1bac-11e7-9c07-c5e04829b535.png)

However, if you go into edit mode (even if you don't change anything) and then save out of it, the formatting of the bundle breaks:

![image](https://cloud.githubusercontent.com/assets/2111202/24822737/6ba9b66a-1bac-11e7-99bb-08371f6aee18.png)

Presumably because it now "sees" the extraneous newline.

**Comment by kashizui** [comment]
Found the issue, we weren't sanitizing the text properly when generating these bundle summary lines. Pushing a fix soon.

**Comment by kashizui** [comment]
fix'd
