### ISSUE TITLE
Remove placeholder text for schema editor

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2918]
The placeholder text appears to be cut off on my screen.

![image](https://user-images.githubusercontent.com/1689183/94928153-3e7bc580-0491-11eb-9cad-0032f46c594f.png)

We can probably just remove them, since the tooltips next to the "?" buttons on the header have more information about what each of these fields are, anyway.

**Comment by percyliang** [comment]
Solution: put the placeholder text as the column headers (Column name, Path to render, How to render).

**Comment by ealvarez968** [comment]
Hey guys if you tell me which file should I look for I can fix it 😃

**Comment by Levilian** [comment]
Actually it's more complicated than we initially thought
`The general form of the commands:

    % schema <schema-name>
    % add <field-name> <generalized-path> [<post-processor>]
    % addschema <schema-name>
`
