### ISSUE TITLE
Add syntax highlighting and line wrap to worksheet markdown

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#294]
As title -- quite explanatory. Suggestion by Ice

**Comment by fabeschan** [comment]
Additional information:

Entries are very verbose (has every dependency listed), lines are long and unwieldly to scroll.
Should implement line wrap. Make size of editor fit screen correctly.

**Comment by kashizui** [comment]
To clarify, this all has to do with the worksheet markdown editor.

Currently we use Ace Editor (https://ace.c9.io/), this will require looking more into the features provided by Ace to see what we can do to address these issues, and then possibly researching other editors if Ace is not good enough.

**Comment by kashizui** [comment]
Looks like this might involve a ".tmlanguage" syntax highlighting definition (we need to define our own syntax highlighting for CodaLab-flavored markdown) and then "importing" it into Ace

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1073
