### ISSUE TITLE
Get rid of the bottom bar of the table

### ISSUE THREAD

**Issue by yuqijin** [codalab/codalab-worksheets#2948]
**Describe the bug**
<img width="1399" alt="Screen Shot 2020-10-09 at 8 22 59 AM" src="https://user-images.githubusercontent.com/34461466/95601718-b5bcd680-0a08-11eb-9c6c-36b8ba37a990.png">

**Comment by ealvarez968** [comment]
Hi, I would like to help solve this issue, is it available?

**Comment by yuqijin** [comment]
> Hi, I would like to help solve this issue, is it available?

Hi, yes, it is available.

**Comment by ealvarez968** [comment]
Great! Can you assign this to me ? and if  you could give me a clue about which file to look for because I'm new to this project, I would appreciate that.

**Comment by yuqijin** [comment]
Hi, I think you can take look at the `TableItem.js` and the related css files. It should be related to the `TableContainer`.

**Comment by yuqijin** [comment]
> Great! Can you assign this to me ? and if you could give me a clue about which file to look for because I'm new to this project, I would appreciate that.

Hi, I think you can take look at the `TableItem.js` and the related css files. It should be related to the `TableContainer`.

**Comment by ealvarez968** [comment]
Thank you
