### ISSUE TITLE
Link to show/download bundle sometimes results in mis-mangled URLs

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#295]
Reported by Ice:

Cannot show/preview/download some bundle files https://codalab.stanford.edu/rest/bundles/0x0586a5bef2e746558dc837345815f820/contents/blob/caffe%2FINSTALL.md

Note the %2 that wasn't in the original file name.

**Comment by kashizui** [comment]
Duplicate of codalab/codalab-cli#701
A fix is in and should be deployed at the end of this week. @ppasupat
