### ISSUE TITLE
Hostname does not render properly in remote field on AWS Batch WorkerManager-submitted jobs

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2958]
**Describe the bug**

This is a bug with https://github.com/codalab/codalab-worksheets/pull/2894 . In that PR, we modified the WorkerManager's launch command to add the node's `$(hostname -s)` to the worker ID.

However, this doesn't work for AWS batch---I assume that they have something that escapes out these shell commands in the "command" field of batch jobs? What actually shows up in the remote is simply something like: `$(hostname -s)-1f765cef467b478d9ec1a12b7cc1eb33` (i.e., the bash subshell is not evaluated)

**Comment by epicfaace** [comment]
Duplicate of https://github.com/codalab/codalab-worksheets/issues/3577.
