### ISSUE TITLE
use multiple disks for bundle store

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#296]
Currently, everything needs to be in one directory.  Want to be able to specify multiple directories (could be on multiple disks or not), and have the load distributed.

Specifically, in ~/.codalab/config.json, we would specify a number of data directories.  Things would be stored in
.codalab/data/0
.codalab/data/1
.codalab/data/2
...
These could be manually configured as symlinks to wherever.

Migrating between different number of disks would involve copying around lots of bundles.  Seems unavoidable or is there a clever way to do this?

**Comment by a10y** [comment]
@percyliang  I have a few questions about this, maybe we can block out ~30 minutes to talk about this sometime between tomorrow and next Tuesday:

If we want to migrate bundles between disks/folders, in a situation where folders can change we can do something like a hash ring, which will take care of load balancing and minimizing the bundles we would need to transfer in the case of a migration.

**Comment by a10y** [comment]
Merged to develop in d35a05929a9b35e78a832b383f7e8f100c17aeda
