### ISSUE TITLE
Feature request: GUI and real time preview for making tables

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#297]
Reported by Ice:

Making tables is difficult. Sometimes have to guess + trial and error
Would like a preview function for editing schema so don’t have to press buttons to switch to preview. Like real time preview.

Also would like custom GUI for editing schema

**Comment by fabeschan** [comment]
Additional information:

At least Fig has something for easily editing schema, like go to field specs -> each field is a row for easy edit. Name, mapping, formatting).

Having preview would be nice too. Would be really good to be able to preview values (then don’t have to render the entire worksheet).

Shared schema would be very good too.

**Comment by percyliang** [comment]
Will be fixed if we have better ways of editing schema, which will follow after we refactor worksheet interpretation items.
