### ISSUE TITLE
Workers getting assigned more bundles than they can run

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2990]
**Describe the bug**
Workers are getting assigned more bundles than they can run. This manifests in the error message for PREPARING bundles "Unexpectedly unable to assign enough resources to bundle 0x6e4839f7f6014e4c9b7aa64a67762257: Requested more GPUs (1) than available (0 currently out of 1 on the machine)".

Doing some digging, I noticed the following pattern happening. The worker is a 1-gpu machine, and all bundles request 1 GPU---so the worker should be only able to run 1 thing at once. One case I found was that the worker was already running bundle `0x9575f85367564a6385e4abe96d14f8c4`, but got assigned `0x6e4839f7f6014e4c9b7aa64a67762257` as well. However, it can't run `0x6e4839f7f6014e4c9b7aa64a67762257`. This is what the BundleManager log shows:

```
2020-10-26 02:20:31,082 Starting run bundle 0x9575f85367564a6385e4abe96d14f8c4 on worker tahoma(4449)
...
2020-10-26 04:14:50,258 Bringing bundle offline 0x9575f85367564a6385e4abe96d14f8c4: No worker claims bundle
...
2020-10-26 04:15:15,851 Starting run bundle 0x6e4839f7f6014e4c9b7aa64a67762257 on worker tahoma(4449)
```

At this point, the worker is erroneously running both `0x9575f85367564a6385e4abe96d14f8c4` and `0x6e4839f7f6014e4c9b7aa64a67762257`. Seems like this happens when workers temporarily go offline, so their bundles are marked as offline, but they come back online in time for them to be assigned new bundles but not in time for the BundleManager to update the worker info to record that they're already running something.

**To Reproduce**
Unclear

**Expected behavior**
Bundles are not overassigned.

**Comment by epicfaace** [comment]
Could be merged into https://github.com/codalab/codalab-worksheets/issues/2722 because it seems to only happen when bundles are stuck uploading results.
