### ISSUE TITLE
have graphing support JSON files

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#30]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Monday Dec 07, 2015 at 07:13 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1480_

---

Currently, we only support TSV files.  We'd like to support JSON files.  So for example, if the JSON file is like:

```
[{a:3, b:5, c:9}, {a:9, b:1, c:6}]
```

Then if we have `x=a y=c` in the directive, then we should get points (3, 9) and (9, 6) to plot.

The relevant file is graph_bundle_interface.js.

**Comment by percyliang** [comment]
Not a priority.
