### ISSUE TITLE
How to build my own docker image and run a container in Codalab platform?[USER ISSUE]

### ISSUE THREAD

**Issue by mellahysf** [codalab/codalab-worksheets#3010]
**Describe the bug**

I want to build a docker image in Codala platform but it fails.

**To Reproduce**

1) first I upload my docker (Dockerfile) file and the run_codala.sh file in Codala platform.
run_codala.sh file contains one simple line that should build my image: docker build -t ratsql .

2) Then, in Codalab terminal, I run the command:  cl run :run_codala.sh 'sh run_codala.sh'
But it give me the error: run_codala.sh: 2: run_codala.sh: docker: not found

So my question is how to build my own docker image in Codalab platform then run a container and work in it?
something like the following docker normal commands that work for me in my local machine without Codalab:
docker build -t ratsql .
docker run --rm -m4g -it ratsql

Thank you very much.

**Comment by epicfaace** [comment]
@mellahysf If you just need to run code in a Docker container in a CodaLab bundle, you try building the container on your own computer, then push it to Docker Hub, then set that container to the container for a particular codalab run.

Or do you actually need to run `docker` in CodaLab for some other reason?

**Comment by mellahysf** [comment]
Thank you @epicfaace for your reply.

Yes, I want to run some code inside a Docker container.

The Docker container is pushed to Docker Hub. 

Note: Project that I want to be run in Codalab platform: https://github.com/microsoft/rat-sql 
I found that the Docker container is already pushed to Docker Hub: https://hub.docker.com/r/xdeng/ratsql
Can you help me please to run this project in Codalab? 

Thank you very much.

**Comment by yiboliu** [comment]
> Thank you @epicfaace for your reply.
> 
> Yes, I want to run some code inside a Docker container.
> 
> The Docker container is pushed to Docker Hub.
> 
> Note: Project that I want to be run in Codalab platform: https://github.com/microsoft/rat-sql
> I found that the Docker container is already pushed to Docker Hub: https://hub.docker.com/r/xdeng/ratsql
> Can you help me please to run this project in Codalab?
> 
> Thank you very much.

Have you tried to log in to a server and do `docker run` your project? It should download the image and run then. Probably you can go to worksheets.codalab.org, open terminal and run it in the terminal.

**Comment by mellahysf** [comment]
Thank you @epicfaace & @yiboliu 
It works for me now.
