### ISSUE TITLE
waiting for worker startup

### ISSUE THREAD

**Issue by fereshte-** [codalab/codalab-worksheets#302]
I got this msg and after a while, my run fails (especially when I run on Johns)

Why do I get this message and how can I avoid it?

https://codalab.stanford.edu/bundles/0x0ee1cdd7374645afa6325b873771576b/
https://codalab.stanford.edu/bundles/0x8c113943c2e6422197795f6b3b2d14c7/

**Comment by kashizui** [comment]
This generally means that the worker we dispatched to the host never started up, maybe because of a Torque error, or because the queue is full for that node.. (I think there are a lot of jobs running on john and jag right now?)

**Comment by fereshte-** [comment]
Thanks,

john11 is listed as free in nlp website though and only a few Codalab jobs
are running on it though.

**Comment by kashizui** [comment]
I cleaned up some (a lot of) orphaned/immortal jobs, hopefully the queues are a bit less clogged now, let us know if problems arise again!
