### ISSUE TITLE
can't run with `--link` dependencies

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#3032]
Can't seem to run `--link` bundles:
```
$ cd /u/nlp/data
$ cl up PTB3 --link
$ cl run :PTB3 'ls -l *'
```
There are two problems:
1) The path stored in the link_url is the relative path, but it should be the absolute path.
2) Even if you used the absolute path, it still can't get the bundle:

```
Failed to download dependency PTB3: Dependency download failed: Unable to get bundle contents from bundle service: Not Found - Path 0x357a49fb2efa4f6dbddcdb7256f42185 in bundle not found
```

**Comment by epicfaace** [comment]
#2 is happening because we need to set the `CODALAB_LINK_MOUNTS` option on the Stanford instance. Will update this variable in deployment.
