### ISSUE TITLE
New landing page

### ISSUE THREAD

**Issue by yuqijin** [codalab/codalab-worksheets#3037]
For a new user, there are multiple possible landing pages right now, including:
1. https://github.com/codalab/worksheets-examples
2. https://worksheets.codalab.org/
3. https://codalab-worksheets.readthedocs.io/en/latest/
4. Dashboard Worksheet

Instead of the old Dashboard Worksheet, we'd better create a dedicated page with the user's worksheets, a few statistics, and a 'New Worksheet' prominently featured.

related issue: #2405

**Comment by yuqijin** [comment]
Here is the design doc for the possible landing pages :
https://docs.google.com/document/d/10djl0nTsW2_GoGfUj9xAuIxlPdCMwkM3Ot0lkdK1r8A/edit?usp=sharing

And here is the prototype of a new Dashboard:
https://www.figma.com/file/vQ47DEaksQu3BPZ3FW1tmE/CodaLab-User-Dashboard?node-id=0%3A1
![CodaLab User Dashboard-1](https://user-images.githubusercontent.com/34461466/99028498-c3440f80-2524-11eb-94c1-1956283fb704.png)

**Comment by percyliang** [comment]
Thanks!  Profile area and basic stats looks good.

My worksheets might need to take up more horizontal space - we might want to format the title and title, and date in a nicer way.
Would be good to make the New worksheet link more prominent (colored box with 'New').

We also don't want an actual worksheet on the right hand side...the main thing left is to show the list of created/staged/running/floating and recent bundles.

**Comment by yuqijin** [comment]
Mimic Current Dashboard Worksheet version:
![CodaLab User Dashboard-1](https://user-images.githubusercontent.com/34461466/99860204-3cf08480-2b47-11eb-9013-5a88f41564c3.png)

**Comment by yuqijin** [comment]
Note based on Nov. 13th meeting's discussion:

1. Privacy: when users view other users’ dashboard, hide basic statistics and email address

2. Worksheet format: name + date 

3. TODO: bundle format

**Comment by yuqijin** [comment]
Note based on Nov. 20th meeting's discussion:

**Sidebar**
1. Time quota + Disk Quota
2. Show a progress bar for the fraction of usage 

**Main Panel**
1.  Worksheet link: title + name + last_modified_date
2. Status boxes for bundles

**Comment by yuqijin** [comment]
Bundle Status Boxes Version:
![CodaLab User Dashboard (1)-1](https://user-images.githubusercontent.com/34461466/99860262-66111500-2b47-11eb-8ba2-a2c6e54803c2.png)

**Comment by yuqijin** [comment]
![image](https://user-images.githubusercontent.com/34461466/104707957-f5fbb700-56d1-11eb-9c26-7832d6613872.png)
