### ISSUE TITLE
Implement Ctrl-C in web terminal

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#307]

**Comment by maxwang7** [comment]
And potentially clicking to move the cursor as well?

**Comment by maxwang7** [comment]
Consider replacing web terminal -- see how long I think it would take + design doc
Find a terminal plugin

**Comment by kashizui** [comment]
Just in case this gets forgotten, the current terminal emulator supports tab completion, which is definitely something we want to keep. So finding a replacement might be difficult...
It might just be a matter of using the plugin better, since the way it's currently used might be kind of hacky (afaik a bunch of style modifications were made for example).

**Comment by maxwang7** [comment]
Interesting, didn't know we had tab completion. I've started reading the code for the web terminal, will come back later with a design doc.

User problems:
- Can't Ctrl-C
- moving around in a long command is hard -- allow mouse clicks?
- Scrolling behaves strangely

Maintain: 
- tab completion

**Comment by maxwang7** [comment]
There are a number of already built-in keyboard shortcuts. See documentation: http://terminal.jcubic.pl/api_reference.php (under "Keyboard shortcuts" section)

**Comment by kashizui** [comment]
yep it might just be a matter of wiring up the plugin properly with
callbacks..

**Comment by kashizui** [comment]
In this demo you can clearly click around the command line you are editing:
http://terminal.jcubic.pl/tilda-demo.html

We're definitely just using the plugin wrong in some way..

**Comment by maxwang7** [comment]
Yeah, I also noticed that, which is awesome. The weird scrolling is also happening in the demo though: http://terminal.jcubic.pl/

**Comment by kashizui** [comment]
What weird scrolling behavior are you referring to?

**Comment by maxwang7** [comment]
It just scrolls really quickly

**Comment by kashizui** [comment]
Ah I didn't notice it because I was using an old-school scroll-wheel --
yeah trackpad scrolling seems to works poorly with this
