### ISSUE TITLE
CLI frequently forgets which worksheet I am on

### ISSUE THREAD

**Issue by AngledLuffa** [codalab/codalab-worksheets#3078]
**Describe the bug**
After not working for a few minutes, codalab forgets the result of the previous "cl work nlp::" command and tries to connect to the public site.

**Codalab Information**
- *Your username*:   AngledLuffa
- *Error message received from Codalab (if applicable)*:
Requesting access at https://worksheets.codalab.org
 - *OS (if on CLI)*:
this is on the sc server on the stanford cluster
 - *Codalab CLI Version (if on CLI)*: 0.5.29

**To Reproduce**
Steps to reproduce the behavior :
1. Do codalab stuff
2. Wait a little while (much less than an hour)
3. have to run "cl work nlp::" again

**Expected behavior**
Would prefer it to stay on the same worksheet

**Comment by kohpangwei** [comment]
I have the same issue even when just working on the public site. It often forgets my current worksheet and then submits bundles to my home worksheet, so I need to run `cl work [worksheet ID]` again. This happens even on the same console session. It'd be nice for it to remember what worksheet I'm on. Thanks!

**Comment by AngledLuffa** [comment]
```
horatio@sc:~/lemma$ cl work nlp::
Switched to worksheet: https://codalab.stanford.edu/worksheets/0xd721cf35a6d64e6d861b4ccfd8161847 (home-AngledLuffa)
(reverse-i-search)`lemma': ls data/^Cmma/
horatio@sc:~/lemma$ cl work AngledLuffa-stanza-lemma
Switched to worksheet: https://codalab.stanford.edu/worksheets/0xc2fd6a2b40ea4ae591a14c28c8aeface (AngledLuffa-stanza-lemma)
horatio@sc:~/lemma$
horatio@sc:~/lemma$ cl work AngledLuffa-stanza-lemma
Requesting access at https://worksheets.codalab.org
```

This basically happens if I just sit around for 15 minutes doing nothing in a window.  It's kinda irritating
