### ISSUE TITLE
[USER ISSUE] Let worksheet contents take up more space in UI

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#3080]
**Describe the bug**
Small issue but I think it would look a lot better if the worksheet contents used more of the horizontal space in the UI, to avoid horizontal scrollbars.

**Codalab Information**
- *Your username*: robinjia
- *UUID of worksheet where problem occurred*: 0x39ba5559790b4099a7ff75f916ce19a4 (one example)
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*; Chrome

**To Reproduce**
Steps to reproduce the behavior :
Visit the worksheet in the browser and make the window narrow.

**Expected behavior**
Worksheet contents should fill available horizontal space. However, instead there's a lot of empty gray space on the side, while many of my tables have horizontal scroll bars.

**Screenshots**
![image](https://user-images.githubusercontent.com/7267349/100551770-811b0d80-3248-11eb-9b0d-51a7a3285696.png)

**Additional context**

**Comment by nelson-liu** [comment]
does pressing the 4 arrows in the top right corner (same row as "show terminal") do what you want?

**Comment by robinjia** [comment]
Whoa didn't notice that button, yes that is perfect

**Comment by nelson-liu** [comment]
(though also, personally speaking, I think I've never gone back to the default after turning the wide mode back on...maybe there's a better default somewhere)
