### ISSUE TITLE
[USER ISSUE] Downloads from Codalab are slower than downloads from Dropbox

### ISSUE THREAD

**Issue by kohpangwei** [codalab/codalab-worksheets#3092]
On `scdt.stanford.edu`, downloading a large file (84G) from Dropbox with

`wget https://www.dropbox.com/s/i8x1p0im11rmur9/iwildcam_data.tar.gz\?dl\=1`

is approximately 8x faster than downloading the same file from Codalab with

`wget https://worksheets.codalab.org/rest/bundles/0x32e95e547dca466cb3779150504b1b0e/contents/blob/`.

The corresponding bundle is  `https://worksheets.codalab.org/bundles/0x32e95e547dca466cb3779150504b1b0e`.

**Comment by epicfaace** [comment]
I believe this issue should now be fixed on prod.

Dropbox speed is ~10 MB/s:

![image](https://user-images.githubusercontent.com/1689183/104144789-bca20f00-5392-11eb-95c6-05f3924ae7a4.png)

CodaLab bundle download speed is also around the same order of magnitude (I tried this bundle: https://worksheets.codalab.org/bundles/0x3f1b346ff2d74b5daf1a08685d68c6ec):

![image](https://user-images.githubusercontent.com/1689183/104144801-c461b380-5392-11eb-9c17-8a4a4a99fb0c.png)


Going to close this issue, but please reopen if you still see it happening @kohpangwei .

**Comment by EntilZha** [comment]
Hi, I'm seeing a failure related to this as well using a local worker, any chance it is related, or should I create a new issue @epicfaace

Bundle: https://worksheets.codalab.org/bundles/0xac25ce18ddde4499a04bb1181a59d82c

**Comment by epicfaace** [comment]
@EntilZha thanks for reporting -- can you make a new issue for that?
