### ISSUE TITLE
Consider shifting page down when using console instead of covering worksheet

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#31]
<a href="https://github.com/kashizui"><img src="https://avatars.githubusercontent.com/u/614837?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kashizui](https://github.com/kashizui)**
_Monday Dec 07, 2015 at 11:37 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1483_

----

**Comment by percyliang** [comment]
Shifting down doesn't seem like a good solution either.  Is this actually a big problem?  I got this comment before from someone who didn't realize that you could do 'c' and 'esc' to quickly show/hide the console.
