### ISSUE TITLE
Azure worker out of memory

### ISSUE THREAD

**Issue by shimisalant** [codalab/codalab-worksheets#310]
Running on `worksheets.codalab.org`, execution is carried out by the `vm-clws-prod-worker-2` worker.
This worker is very low on available memory, running `free -h` on it yields:
```
             total       used       free     shared    buffers     cached
Mem:           13G        13G       510M        89M        25M       508M
-/+ buffers/cache:        12G       1.0G
Swap:           0B         0B         0B
```

I'm not sure whether this is the right forum for this, or if anything can be done in order to free up memory on these (kindly provided) machines. There may be a rogue job running on that worker (has been going on for a while now). Is it possible to specify that execution will be picked up by a different worker?

Thanks!

**Comment by fabeschan** [comment]
Thanks for the report. We don't have a quick solution for you and will need to decide on what to do with this issue. Meanwhile as a dirty workaround you could try submitting multiple run bundles until one of them is picked up by other workers.

**Comment by shimisalant** [comment]
Thanks, I ended up trying to resubmit a run bundle every few hours. Eventually the load on that worker above went away and my submission was able to execute.
