### ISSUE TITLE
Can't upload .tar.gz files through the web UI

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3106]
Steps to reproduce:
- Click "Upload file"
- Upload a .tar.gz file
- I get the following errors:

![image](https://user-images.githubusercontent.com/1689183/101820007-fcf04200-3af3-11eb-9c98-2ff056518338.png)

Also, the request to https://worksheets-dev.codalab.org/rest/bundles/0x1b56e9c9267b4983ba73f8e5ec5f1471/contents/blob/?finalize=1&filename=_0x64d435b1adff..2bea2d713ae2464.tar.gz&unpack=1 fails because the payload isn't correct.

![image](https://user-images.githubusercontent.com/1689183/101820040-07aad700-3af4-11eb-9008-e5831183a2b3.png)

This is probably a frontend issue, as the request payload should **not** be equal to `zip error: Invalid command arguments (long option 'disable-copyfile' not supported)`.

**Comment by Levilian** [comment]
Regarding tar.gz - I tried on the prod and it produced no issue for me? I guess the issue lies in error handling. this is undefined for some reason. Rather, uploading tar.gz works perfectly fine.

**Comment by Levilian** [comment]
@epicfaace regarding the incorrect request payload, can you say more about what actions you took before you saw the error?

**Comment by epicfaace** [comment]
Resolved by #3135 (which will be merged momentarily).
