### ISSUE TITLE
[USER ISSUE] Incorrect error reporting

### ISSUE THREAD

**Issue by entslscheia** [codalab/codalab-worksheets#3107]
When running the command `macro grailqa-resources/evaluate bert-ranking.json`, it reports an error:`bundle spec grailqa-resources doesn't match any bundles`, but what was actually wrong is that I mistyped `bert_ranking` into `bert-ranking`, i.e., there is no `bert-ranking.json` in my worksheet. 

The above error reported by codalab is misleading. Is it possible to fix it? Many thanks!

**Comment by teetone** [comment]
We should show an error similar to what `cl cat` does.

Example:

```
cl cat 0x6bb88a/stdout2
Target stdout2 doesn't exist in bundle 0x6bb88acdf1ac434885c0af0713e046f4
```
