### ISSUE TITLE
Errors for downloading.

### ISSUE THREAD

**Issue by Twsschx** [codalab/codalab-worksheets#3118]
The speed is only around 10Kb/s，what if I want to download a big file?
I can upload it quickly but when I am going to download it, it costs too much time and often breaks up.

**Comment by EntilZha** [comment]
I’ve been running into similar issues on both a local worker and one in AWS to test if it was my connection (found this issue by searching). I increased the timeouts which seems to help with errors, but it’s still very slow.

**Comment by Twsschx** [comment]
> I’ve been running into similar issues on both a local worker and one in AWS to test if it was my connection (found this issue by searching). I increased the timeouts which seems to help with errors, but it’s still very slow.

Yes. And if I want to upload a big file, it often interrupts so I have to submit again.Can the platform support "resume from break-point"? This is really awful.

**Comment by epicfaace** [comment]
@Twsschx thanks for your suggestion, we're tracking that feature in #3125.

We are currently having issues with slow downloads; I'm merging this issue with #3092.
