### ISSUE TITLE
Long time for preparing the environment

### ISSUE THREAD

**Issue by Twsschx** [codalab/codalab-worksheets#3128]
I have install the docker environment but  when I am going to prepare the running environment, it costs too much time(about 8 hours). I don't know whether this time period can be reduced by some ways.

**Comment by epicfaace** [comment]
Are you running a version of the codalab server locally? What exactly do you mean by "preparing"?

**Comment by Twsschx** [comment]
> Are you running a version of the codalab server locally? What exactly do you mean by "preparing"?

NO, I am running on the codalab website. "Preparing " means preparing for the running environment.

**Comment by epicfaace** [comment]
Merging this with #3129.
