### ISSUE TITLE
Bundles are stuck in "preparing" state

### ISSUE THREAD

**Issue by ZLCaesar** [codalab/codalab-worksheets#3129]
**Describe the bug**
What caused the preparing state to last so long? I first test a case that use a docker image found from docker hub and run a command "pip list", it runs for just 20s.  The size of my all dependency bundles are over 10G. I don’t know if the long preparing state is related to the size of my bundles. After 10 hours, the status becomes worker-offline or running if luck enough. So I want to know what it will do during preparing state. thx!
**Codalab Information**
- *Your username*: 252007913@qq.com
- *UUID of worksheet where problem occurred*: llq
- *UUID of problem bundle (please don't delete)*: 0x2c03a2
- *Error message received from Codalab (if applicable)*: worker-offline
 - *Browser (if on Web)*; Google

**Comment by jzwang43** [comment]
@ZLCaesar Hi, I was looking into the issue but it seems that the problem bundle is no long there. Are you still having this issue? If so can you provide a bundle so we can look into it? Thanks.
