### ISSUE TITLE
Inefficiency, downloading dependency cost 20+ hours

### ISSUE THREAD

**Issue by ZLCaesar** [codalab/codalab-worksheets#3132]
Every time I run on the codalab, it has to pull docker image(5G+) and download all of the dependencies(totally 8G+) , which cost nearly 20+ hours, I wonder if any methods to accelerate the download speed or reuse the downloaded docker environment？

**Comment by epicfaace** [comment]
Can you send a link to the bundle you are using? The docker image pull time should only happen during the first bundle that's run, but subsequent bundles should most probably cache.

@teetone do you think it's possible that Azure Batch ends up not caching the docker image, once new workers are spun up?

**Comment by ZLCaesar** [comment]
> Can you send a link to the bundle you are using? The docker image pull time should only happen during the first bundle that's run, but subsequent bundles should most probably cache.
> 
> @teetone do you think it's possible that Azure Batch ends up not caching the docker image, once new workers are spun up?

https://worksheets.codalab.org/bundles/0xda377227a9304149b432fbf3bfbc10ec 
thx a lot

**Comment by meisihualicooperation** [comment]
> Can you send a link to the bundle you are using? The docker image pull time should only happen during the first bundle that's run, but subsequent bundles should most probably cache.
> 
> @teetone do you think it's possible that Azure Batch ends up not caching the docker image, once new workers are spun up?

![image](https://user-images.githubusercontent.com/20720141/102845346-52a7e100-4448-11eb-88df-bc8f5f604ded.png)

**Comment by ZLCaesar** [comment]
The case is solved. After the docker image and dependencies are downloaded, if any bundle in this container is in the running state, other bundles using this docker can be run directly without downloading. But if all the bundles in this container is in the failed or ready state, the new bundle will download docker image and dependencies again.
p.s. all my dependencies and docker image are totally over 15G, it cost 20 hours to download all of them

**Comment by percyliang** [comment]
It still shouldn't take 20 hours to 15GB, re-opening so we can investigate.

**Comment by Ajanulk** [comment]
@percyliang @epicfaace I have met the same issue. However, the docker image (11g) is downloaded quickly (5 mins), while the uploaded bundle (3.5g) is downloaded slowly (still downloading). The uuid is 0xe99e6f.

**Comment by epicfaace** [comment]
This issue should now be fixed on worksheets.codalab.org.

@Ajanulk Can you try re-creating your bundle to see if the slow speed still persists for downloading the uploaded 3.5g bundle?

**Comment by Ajanulk** [comment]
> This issue should now be fixed on worksheets.codalab.org.
> 
> @Ajanulk Can you try re-creating your bundle to see if the slow speed still persists for downloading the uploaded 3.5g bundle?

@epicfaace Thanks a lot. In fact, I encountered this problem only when I run a bundle using a codalab worker with NO GPU.  I have re-run a new bundle and it seems that this problem has been solved. The bundle is 0x56c50f. Please check it. Since the "staged" issue has been solved, I may no longer call workers without GPU.
