### ISSUE TITLE
bundles stuck at running and cannot be killed

### ISSUE THREAD

**Issue by billy-inn** [codalab/codalab-worksheets#3134]
**Describe the bug**
Some bundles stuck at running, which cannot be killed or removed, when I attempt to remove them during running. As a result, my quoted space cannot be released and I cannot run anything else.  I've been stuck in this situation for a few days. CodaLab says "For run bundles, kill them first. Bundles stuck not running will eventually automatically be moved to a state where they can be deleted." I wonder how long it will take? Thanks!

**Codalab Information**
- *Your username*: peng
- *UUID of worksheet where problem occurred*: 0x5ee9b9b9a4c74e6a91ecb7308d374510
- *UUID of problem bundle (please don't delete)*: 0xe316bf; 0xbbdb50; 0x9ec8d5

**Comment by epicfaace** [comment]
I think this is related to #2722. @teetone do you know of a temporary solution that would let us manually kill these bundles for now?

**Comment by epicfaace** [comment]
Closing this in favor of #2722.

**Comment by billy-inn** [comment]
so there is no way to get around with these bundles now? @epicfaace

**Comment by epicfaace** [comment]
I was able to kill them manually, hope that helps.
