### ISSUE TITLE
Upload is very slow [USER ISSUE]

### ISSUE THREAD

**Issue by Ajanulk** [codalab/codalab-worksheets#3141]
**Describe the bug**
It takes a long time to update the uploaded size, which has not been encountered before. The upload speed is only one-fifth of the original maximum.

**Codalab Information**
- *Your username*: lrh003
- *UUID of worksheet where problem occurred*: 0xf08e868c5e434ec1adfe1e4e0b41194e
- *UUID of problem bundle (please don't delete)*: 0x40666e8dfb424d498db3ae2671c1a915
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*: Ubuntu 16.04
 - *Codalab CLI Version (if on CLI)*: 0.5.32
 - *Browser (if on Web)*; 

**Screenshots**

**Additional context**

**Comment by epicfaace** [comment]
@Ajanulk is this issue still happening for you?

**Comment by Ajanulk** [comment]
> @Ajanulk is this issue still happening for you?

@epicfaace  The upload speed has returned to the previous level. Thanks a lot! BTW, I have a new question #3143 . As the deadline for a conference is approaching, I have an urgent need for experimental results. Could you please handle it as soon as possible? Thanks again!
