### ISSUE TITLE
[USER ISSUE]Staged state has been going on for a week

### ISSUE THREAD

**Issue by Ajanulk** [codalab/codalab-worksheets#3143]
Hi, my running bundle has been staged for a week. The uuid is 0x3bef18. please check it.

**Comment by epicfaace** [comment]
@Ajanulk Can you maybe try re-requesting the bundle, but with less memory? Maybe 48GB memory is not available. Let me know if that works.

**Comment by Ajanulk** [comment]
> @Ajanulk Can you maybe try re-requesting the bundle, but with less memory? Maybe 48GB memory is not available. Let me know if that works.

@epicfaace Thanks for reply. I have tried the same running with 24g, 16g and 4g. They are still staged. The uuids are 0x8c0ac3, 0xd90156 and 0x4641c4, respectively. Please check them.

I worry that even if a small memory can work, it cannot afford data preprocessing.

**Comment by epicfaace** [comment]
Ah, I see that when I try to mimic your bundle but don't request any GPUs, it works. We might be having a problem currently with requesting GPUs (@teetone ). In the meantime, would you be able to run your job for now without a GPU?

**Comment by Ajanulk** [comment]
> Ah, I see that when I try to mimic your bundle but don't request any GPUs, it works. We might be having a problem currently with requesting GPUs (@teetone ). In the meantime, would you be able to run your job for now without a GPU?

@epicfaace Thank you very much. I will try the cpu version. If this problem is solved, please let me know in time. Using cpu to run large-scale language models is indeed a bit difficult.

**Comment by epicfaace** [comment]
Duplicate of #3153.

**Comment by epicfaace** [comment]
@Ajanulk  this issue should now be fixed -- please try again and you should be able to request GPUs now.

**Comment by Ajanulk** [comment]
> @Ajanulk this issue should now be fixed -- please try again and you should be able to request GPUs now.

@epicfaace Thanks very much! It does work. Unfortunately, I met another issue #3170 . It is a strange issue and i find a similar one #2440
