### ISSUE TITLE
my state has been staged for 2 weeks now

### ISSUE THREAD

**Issue by hello-deh** [codalab/codalab-worksheets#3144]
My bundle is https://worksheets.codalab.org/worksheets/0xb5ec515a19c54b68aab460041cbe6fd4
uuid is 0xe772c3
The state has been staged for 2weeks now, please cheek it

**Comment by epicfaace** [comment]
Bundle link: https://worksheets.codalab.org/bundles/0xe772c30601bc4835bd201534296dc396

This is a known issue -- please try requesting 0 GPUs in the meantime as a workaround, and it should run. Closing this in favor of #3153.

**Comment by epicfaace** [comment]
@hello-deh this issue should now be fixed -- please try again and you should be able to request GPUs now.
