### ISSUE TITLE
[FEATURE REQUEST] "Locking" worksheets and bundles to prevent them from being modified or deleted

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#3150]
**Is your feature request related to a problem? Please describe.**

CodaLab serves dual purposes as an experimental platform and as a place to share results. For the latter, it'd be nice if there was some way to "lock" bundles or worksheets such that they can no longer be modified (unless they're unlocked).

As someone who has many such bundles and worksheets, I'm always afraid that an errant `cl rm $(cl search)` is going to wipe away existing results that I want on CodaLab for archival.

**Describe the solution you'd like**

Commands `cl lock` and `cl unlock` for worksheets and bundles that change whether or not their metadata can be modified / whether or not they can be deleted.

**Describe alternatives you've considered**

Not sold on the `lock` and `unlock` names, `freeze` and `unfreeze` might be better, for instance.

**Comment by percyliang** [comment]
`cl wedit --freeze` exists at least...  Freezing bundles seems reasonable too.
