### ISSUE TITLE
[USER ISSUE] Codalab Quota Request

### ISSUE THREAD

**Issue by EntilZha** [codalab/codalab-worksheets#3165]
**Describe the bug**
I created a request to increase disk quota a couple weeks ago via https://docs.google.com/forms/d/e/1FAIpQLSdS22MaLyE1kx0JL-w2a8f8IasDyc36H_ZuidNBVAE_afMCpw/viewform but still haven't heard back. Could I get an update on the status?

Alternatively, is there a way to run codalab bundles so that I can provide my own storage if I'm using a local worker?

**Codalab Information**
- *Your username*: entilzha

**Comment by epicfaace** [comment]
@EntilZha Sorry we missed your request earlier! We're taking a look at it and will get back to you.

**Comment by yuqijin** [comment]
@EntilZha, I have increased your disk quota. I’m closing this issue for now. Thanks!
