### ISSUE TITLE
Improving Docker and development experience

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#317]
[ ] Docker video

Other ideas:
- Beef up codalab-ubuntu even more? (is Tensorflow in there yet?)
- More directed documentation

**Comment by fabeschan** [comment]
Perhaps have a list of recommended images instead? Plus a tutorial on how to use Dockerfiles to augment those images for more specific usage. Probably a better way to go about it than force-feeding codalab-ubuntu into becoming a harrowing monstrosity

**Comment by fabeschan** [comment]
Add entry to FAQ as a start?

**Comment by percyliang** [comment]
Handled if we create a bunch of worksheets with examples of popular models.
