### ISSUE TITLE
[USER ISSUE]"No such file or directory" while the file already exists

### ISSUE THREAD

**Issue by Ajanulk** [codalab/codalab-worksheets#3170]
**Describe the bug**
When running a bundle I met "No such file or directory" while the file already exists.

**Codalab Information**
- *Your username*: lrh003
- *UUID of worksheet where problem occurred*: 0xf08e868c5e434ec1adfe1e4e0b41194e
- *UUID of problem bundle (please don't delete)*: 0x39cd21
- *Error message received from Codalab (if applicable)*: 
python: can't open file 'HotpotQA_submission_al/bert_ner/predict.py': [Errno 2] No such file or directory
 - *OS (if on CLI)*: Ubuntu 16.04
 - *Codalab CLI Version (if on CLI)*: 0.5.32

**To Reproduce**

I have uploaded a smaller set and run the same bundle but just changed the dependency for faster detection. Strangely, it works. The bundle is 0x5a0c1d. 

**Expected behavior**
Please compare the broken bundle 0x39cd21 with the good one 0x5a0c1d. Please find the reason and provide some suggestions to avoid this problem.

**Comment by epicfaace** [comment]
This may be related to #2440 and #2723.

**Comment by Ajanulk** [comment]
> This may be related to #2440 and #2723.

@epicfaace Thanks a lot. But I have not found the solution.  @nelson-liu Hi, have you solved this issue?

**Comment by nelson-liu** [comment]
no, sorry. it happens infrequently enough that i usually just rerun and move on with my life.

**Comment by Ajanulk** [comment]
@epicfaace Hi, I have run three identical bundles and only one worked. It is worth noting that the one that ran successfully used an explicit dependency  declaration "HotpotQA_submission_al:0x40666e" instead of ":HotpotQA_submission_al". The UUIDs of these three bundles are 0xccf3db, 0xee5859, and 0x553653, respectively. I think it may provide some reference information.

**Comment by robinjia** [comment]
I've been running into this same issue for one submission on the SQuAD leaderboard. Here are 3 attempts to run the same submission, all of which fail with a "No such file" error: https://worksheets.codalab.org/bundles/0xcab3cc3b789c4393b3621a2851c18794 https://worksheets.codalab.org/bundles/0xf1a59ac36212401abaa48c94375d6a26 https://worksheets.codalab.org/bundles/0x2f188ed8171f428c81d19ae9fc6e5f9f . Interestingly, they all failed at different times in the program execution.

**Comment by epicfaace** [comment]
Now that #3236 been solved -- I'm going to close this as well. If you're still seeing this issue, though, please feel free to reopen.
