### ISSUE TITLE
show status of docker image download

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#3174]
Currently, the `run_status` is stuck in `Pulling docker image: Download starting.` for a very long time and it's not clear what's happening.  We used to show the progress of the docker download, but it disappeared during a refactor.  It'd be nice to get it back.

**Comment by epicfaace** [comment]
Show percentage (such as: `Pulling docker image: Download starting (50%).`)

**Comment by yiboliu** [comment]
am thinking about how to redirect this console info to our frontend:
![image](https://user-images.githubusercontent.com/18689351/105802961-33bdd280-5f51-11eb-85a2-15e16119100b.png)

**Comment by yiboliu** [comment]
@epicfaace looks like [it's pretty hard to get how many layers are there to download](https://stackoverflow.com/questions/25830005/how-can-i-get-percentage-of-pull-docker-image). So I propose that we just show how many layers have been downloaded and what's the progress of downloading the current layer.

**Comment by epicfaace** [comment]
Sounds good.

**Comment by epicfaace** [comment]
Fixed by https://github.com/codalab/codalab-worksheets/pull/3351

**Comment by adiprerepa** [comment]
this can't close until #3382 gets merged
