### ISSUE TITLE
cut interacts badly with cursoring

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#3176]
To reproduce, create a worksheet with three bundles b1, b2, b3.  Cursor over to b2 and detach it using 'a d'.  The cursor is now on b3.  Hit 'k' and it will skip over b1.

**Comment by yipenghe** [comment]
I don't think we still have the detach operation on frontend though? We decided to use cut for that purpose since detach requires having only one reference in the worksheet which is much more limited

**Comment by percyliang** [comment]
Oh, by detach, I meant cut.
