### ISSUE TITLE
get data for all competitions

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#3181]
A number of competitions (e.g., SQuAD) are running on CodaLab.  However, CodaLab doesn't have a notion of competitions.  One only can find out about the competitions by searching for 'codalab submission tutorial'.  It would be nice to have a list of competitions that was current (https://codalab-worksheets.readthedocs.io/en/latest/Competitions/).

Suggested steps:
1) Make a Google form / spreadsheet to keep track of all competitions.  For existing competitions, we can manually find them and do this.  We should add this to the instructions on https://codalab-worksheets.readthedocs.io/en/latest/Competitions/.
2) The form should contain competition name, leaderboard URL, JSON file that's output by the competition script (e.g., https://github.com/rajpurkar/SQuAD-explorer/blob/master/out-v2.0.json), submission tutorial worksheet, email contact.
3) Create a Google groups for competition organizers to share tips/tricks and get updates?

**Comment by epicfaace** [comment]
@yuqijin I think, next, it would be great if you could put the spreadsheet in a common place (maybe the codalab drive, or maybe we link to it from the codalab docs) so that others can find and see it.

**Comment by yuqijin** [comment]
> @yuqijin I think, next, it would be great if you could put the spreadsheet in a common place (maybe the codalab drive, or maybe we link to it from the codalab docs) so that others can find and see it.

@epicfaace The link to the google form is here: https://docs.google.com/forms/d/e/1FAIpQLSdFdQTi4i0uXfXR00JD40HlW-j-Np2XCacgaPSZVfBdL4QwQg/viewform?usp=sf_link
And the spreadsheet for the info collection/ doc for collecting the competition organizer's feedback/ spreadsheet for the list of all competition on codalab worksheet is all in the codalab google drive.
