### ISSUE TITLE
Metadata value for request_network should be of type , was false (type )

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#32]
<a href="https://github.com/kashizui"><img src="https://avatars.githubusercontent.com/u/614837?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kashizui](https://github.com/kashizui)**
_Monday Dec 07, 2015 at 11:39 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1484_

----

> When I try to edit metadata (e.g. change the description) of a run bundle from the bundle's webpage (something with url /bundles/<uuid>), I get an error at the top of the page saying, "Metadata value for request_network should be of type , was false (type )".

**Comment by percyliang** [comment]
The bundles page is going to be ditched.  But the issue still stands.

**Comment by ChengshuLi** [comment]
Please see PR :)
