### ISSUE TITLE
link to files within bundles is broken

### ISSUE THREAD

**Issue by sidaw** [codalab/codalab-worksheets#321]
to reproduce, go to:
https://worksheets.codalab.org/bundles/0xd41d3c94ff6a43dd8ca3e0430291bd33/
or any other bundle with more than 1 file
click on all.text, the link goes to:
https://worksheets.codalab.org/rest/bundles/undefined/contents/blob/all.text
it should go to:
https://worksheets.codalab.org/rest/bundles/0xd41d3c94ff6a43dd8ca3e0430291bd33/contents/blob/all.text

**Comment by kashizui** [comment]
fixed (make sure to refresh your browser cache)
