### ISSUE TITLE
Rename 'version' to 'branch'

### ISSUE THREAD

**Issue by yiboliu** [codalab/codalab-worksheets#3225]
The arg `version` in codalab-service command is not descriptive since it's actually branch in local development. We should probably rename it to `branch` to resolve confusion in development.

**Comment by epicfaace** [comment]
I don't think we should do this. Sometimes, we want to pass a specific version to the `version` parameter (vX.X.X) even during local development. Thus, `version` is a more general name for the parameter than `branch`.
