### ISSUE TITLE
Re-add docker stats

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3234]

**Comment by epicfaace** [comment]
Commit that reverted it: https://github.com/codalab/codalab-worksheets/pull/3229/commits/dd81f5f0f5668ba4009a79418dd6c45e10a7d24e

**Comment by epicfaace** [comment]
Original issue: https://github.com/codalab/codalab-worksheets/issues/3003

**Comment by adiprerepa** [comment]
Line that might be causing it: https://github.com/codalab/codalab-worksheets/pull/3081/files#diff-4dd312c2551c3bfb9c442536dee1828326dcaf3979ef09038ff6a1b963a04387R222

@epicfaace wdyt? You had similar feedback for #3370 in your comment: https://github.com/codalab/codalab-worksheets/pull/3370#discussion_r615458298

**Comment by epicfaace** [comment]
Yeah, feel free to try that.
