### ISSUE TITLE
[USER ISSUE] Dependencies are sometimes inaccessible while running a bundle

### ISSUE THREAD

**Issue by lxylxyoo** [codalab/codalab-worksheets#3236]
Why all dependencies are removed during running and only "stdout", "stderr", ".config", ".nv", ".keras", ".cache" and the intermediate output files are kept ？ I tried many times and I found that this may happen at any moment during the running of the program. This will make the entire program unable to run normally.  I think this bug has appeared recently because I have never had this situation before.

**Comment by epicfaace** [comment]
Hi @lxylxyoo , can you send a link to the bundle that you mention has this problem?

**Comment by lxylxyoo** [comment]
> Hi @lxylxyoo , can you send a link to the bundle that you mention has this problem?

Hi, this is the link. https://worksheets.codalab.org/bundles/0x4432e337588f42cc99cd53c202e38cf6

**Comment by nelson-liu** [comment]
possibly related: https://github.com/codalab/codalab-worksheets/issues/3170

**Comment by lxylxyoo** [comment]
> possibly related: #3170

I have tried the method advised by #3170，but it  does not work for me.

**Comment by lxylxyoo** [comment]
Hi @epicfaace, I tried many times, but this problem still occurs frequently. With he same code, sometimes this problem occurs, but occasionally it can run normally. My code involves multiple calls of `os.system`. I wonder if the system mistakenly thought that the entire program has ended, so it deleted all dependencies?

**Comment by epicfaace** [comment]
Hi @lxylxyoo , usually, dependencies are only mounted during a run; their entire contents are not uploaded as part of the bundle results. Can you explain a bit more about your use case? Why do you need the dependencies to be part of the bundle results? Previously, did you see different behavior by which the bundle results _would_ include dependencies?

**Comment by lxylxyoo** [comment]
Hi @epicfaace, for example, I have three model dependencies named ```model1, model2, model3```, one source code dependency named ```src``` and the command I run is ```cl run :model1 :model2 :model3 :src 'python src/run.py' ```. 
the ```src/run.py``` contains three calls to ```os.system``` which run the predictions of these three models:
1、```os.system('python src/run_model1.py')```
2、```os.system('python src/run_model2.py')```
3、```os.system('python src/run_model3.py')```
The first call always succeed, but the second or third call may fail with the 'No such file or directory' ERROR. 
I have used ```os.listdir(".")``` to print what is in the path:
before the first call, the output of ```os.listdir('.')``` is ```['model1', 'model2', 'model3', 'src']```
after the first call, if the ERROR occurs, then the output of ```os.listdir('.')``` is ```['stdout', 'stderr', '.nv', '.cache', '.config', '.keras', 'output from first call']```, otherwise it is ```['model1', 'model2', 'model3', 'src', 'stdout', 'stderr', '.nv', '.cache', '.config', '.keras', 'output from first call']``` and the next call will be run.  
According to my observation, this ERROR may occur after any call ( after 1 or 2 or 3).

**Comment by epicfaace** [comment]
Ah, I see, this is a problem. Thanks!

**Comment by epicfaace** [comment]
Another instance of this issue: https://worksheets.codalab.org/bundles/0xc526c973fa7940608625855dee18b24c

**Comment by epicfaace** [comment]
More feedback about this issue:

> I’ve gotten it on four bundles in a row (see  https://worksheets.codalab.org/bundles/0x584057d222b0462088a9965e5eeda52d, https://worksheets.codalab.org/bundles/0xe2bf44a073b044d49f0f467003e06228, https://worksheets.codalab.org/bundles/0x8b986d0f39084f368725eb12b5645ae2, https://worksheets.codalab.org/bundles/0x0fc757f104234cbd95edaeae169711f3 .) Fwiw out of four datasets (see top of https://worksheets.codalab.org/worksheets/0x7ceb817d53b94b0c8294a7a22643bf5e) I only encounter problems on CelebA https://worksheets.codalab.org/bundles/0x886412315184400c9983b32846e91ab1 .

**Comment by epicfaace** [comment]
@teetone try: https://worksheets.codalab.org/bundles/0x0fc757f104234cbd95edaeae169711f3

Also try a checksum / ls to count the number of files

**Comment by epicfaace** [comment]
Make a process to look at the files and let us know when the files change

**Comment by adiprerepa** [comment]
> Make a process to look at the files and let us know when the files change

https://pypi.org/project/watchdog/

**Comment by epicfaace** [comment]
Looking into whether Ubuntu 20 might have fixed this.

**Comment by epicfaace** [comment]
Meeting notes: Tony tried the bundle 20x but hasn't gotten a failure recently

**Comment by epicfaace** [comment]
Can't reproduce this anymore - Azure might have fixed something.
