### ISSUE TITLE
[USER ISSUE] Strange disk quota error. 

### ISSUE THREAD

**Issue by lxylxyoo** [codalab/codalab-worksheets#3243]
**Describe the bug**
The quota used is 9.9g. While the quota left seems to be negative when I set '--requeset-disk 10m'.
I'm sure I have quota left more than 10m.

**Codalab Information**
- *Your username*: yuyang-alibaba
- *UUID of worksheet where problem occurred*: 
- *UUID of problem bundle (please don't delete)*: 0x8be0f5735563446e80f2616fce5d2c51
- *Error message received from Codalab (if applicable)*:

Requested more disk (10m) than user disk quota left (-424670912) by 414m

 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;  Chrome

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yuqijin** [comment]
Hi @lxylxyoo, we have received your disk quota increase request and increased your disk quota to 20g. I will close the issue for now and let us know if you need other help! Thanks for using CodaLab.
