### ISSUE TITLE
Slowness is reproducible in PROD 

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#3247]
**Describe the bug**
worksheets.codalab.org started to lag when 20 workers were downloading a ~80GB bundle dependency and another 20 workers were downloading a ~30GB bundle dependency all at the same time. The large bundles can be found here: https://worksheets.codalab.org/worksheets/0xb44731cc8e8a4265a20146c3887b6b90

**Expected behavior**
I would expect the site not to lag.

**Comment by epicfaace** [comment]
Closing this in favor of clearer speed targets.
