### ISSUE TITLE
Workers should re-try authorization with bundle service

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3249]
**Describe the bug**
Workers should re-try authorization with bundle service. Right now, if the connection is refused (for example, if the rest server is down), then the worker just prints out "Unable to authorize with bundle service" and doesn't try to reconnect.

**To Reproduce**
Steps to reproduce the behavior :
1. Turn off the rest server.
2. Create and start a worker.
3. Start the rest server.
4. The worker never shows up in `cl workers`. I have to restart the worker in order for it to show up.

**Expected behavior**
The worker should retry connecting to the rest server, and it should therefore show up eventually in `cl workers`.

**Screenshots**
Worker logs:

![image](https://user-images.githubusercontent.com/1689183/107239525-f1879d00-69f6-11eb-98a4-bc78ccff9bdc.png)

**Comment by percyliang** [comment]
I thought the worker always tries to connect.  But if the credentials aren't right, then retrying won't help.
