### ISSUE TITLE
When worker fails, bundle preview simply show nothing

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#327]
Want increased visibility. When bundle preview fails it should say why it failed (worker offline? MySQL foreign key violation? bundlestore error?) rather than stay blank, unreadable and unreasonable. Then when a user reports it we can have better info to reference. Also better feedback for the user as any feedback is better than no feedback when the user is expecting something to appear.

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1066
