### ISSUE TITLE
Error with adding a new run

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3290]
When I add a new run and type in a command in the run, then press ctrl+enter to save the run, I get the following error:

![image](https://user-images.githubusercontent.com/1689183/108612904-aee0a000-73ba-11eb-9d82-c0879157ff63.png)

This happens when I try to add a new run to the dashboard when running locally.

**Comment by yuqijin** [comment]
@epicfaace Could you reproduce the bug with the current master branch? I could not reproduce it any more now.

**Comment by epicfaace** [comment]
Yes, I can reproduce this bug on the latest master.

**Comment by epicfaace** [comment]
Here's a reproduction (not of this exact error, but a related error). It seems to be due to a particular kind of cell being present in the worksheet:

1. Go to https://worksheets.codalab.org/worksheets/0xa955df02877344ea986d0846773a8986
2. Click on the topmost cell (the blue right before the first cell)
3. Click "Run" to add a new run.
4. type "echo hi" and "ctrl + enter"
5. The screen turns blank -- on localhost, I get this blank screen:

![image](https://user-images.githubusercontent.com/1689183/113453335-c6587300-93d3-11eb-97e4-ff7da269d37b.png)
