### ISSUE TITLE
Look into using gRPC for file uploads

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3292]
gRPC is much faster then our current method, chunked transfer encoding over HTTP. This may be a better way to handle worker-to-server communciation.

**Comment by epicfaace** [comment]
https://github.com/codalab/codalab-worksheets/blob/43eaddc8013d484fdfdde91eb07dc6eaf7902601/codalab/worker/rest_client.py#L115-L160

**Comment by epicfaace** [comment]
Let's make a design doc that addresses 1) the benefits of gRPC (ex: speed (include benchmarks), bidirectional communication) and 2) the architecture of how gRPC will work (ex: I'm guessing the rest server will just have an extra port open for gRPC? Also, which endpoints should we transition to gRPC first to get the most efficiency gains? Can we use gRPC for bidirectional communication as well?). @adiprerepa you can make the doc and save it in the CodaLab Google Drive.

**Comment by adiprerepa** [comment]
sgtm

**Comment by adiprerepa** [comment]
We will not be using `gRPC` to upload files from the cli to the server, correct? Seeing as there is an effort to upload directly to azure blob storage from the cli

**Comment by epicfaace** [comment]
Actually, we will want to support gRPC for that use case, too. Azure Blob Storage will only be available on the worksheets.codalab.org instance but not on the codalab.stanford.edu instance.

**Comment by adiprerepa** [comment]
makes sense

**Comment by adiprerepa** [comment]
also, here is a link to an (incomplete) design doc https://docs.google.com/document/d/1F7FNgAhJwG3MJkS-spNEcSoGoyiF8AhioOpMH8EfxWU

**Comment by adiprerepa** [comment]
It looks like for uploading/streaming large files, the difference in performance of the protocols in negligible.

You can see the benchmarks I wrote in: https://github.com/adiprerepa/gRPCvREST-benchmarks

I wrote a more detailed report in the design doc (section "Results of my benchmark")

Unless we face problems other than performance with our current implementation, I do not see a tangible benefit in reworking our system for gRPC.

I would love to hear other people's opinions on this.
