### ISSUE TITLE
Copy-paste from system clipboard to console doesn't work on some systems

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#33]
<a href="https://github.com/kashizui"><img src="https://avatars.githubusercontent.com/u/614837?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kashizui](https://github.com/kashizui)**
_Monday Dec 07, 2015 at 11:43 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1485_

----

I believe this is an ongoing issue for the jQuery terminal plugin:
https://github.com/jcubic/jquery.terminal/issues/3

**Comment by codalab** [comment]
<a href="https://github.com/kashizui"><img src="https://avatars.githubusercontent.com/u/614837?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kashizui](https://github.com/kashizui)**
_Monday Dec 07, 2015 at 11:52 GMT_

----

(In my experience on a Mac/Chrome, I just have to press Cmd+C/V a bunch of times until it works.)

**Comment by kashizui** [comment]
Fixed in develop branch.

**Comment by jcubic** [comment]
Why did you include div with contenteditable? Wouldn't it work without it?
