### ISSUE TITLE
Rerunning bundles with ‘a’ is inconsistent in a consistent manner

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#330]
Sometimes `a` works well. Other times `a` does nothing and you have to deselect the particular bundle and re-select it before `a` works again.

**Comment by percyliang** [comment]
also: 'u'

**Comment by maxwang7** [comment]
This problem happens after a user hits the escape key. An example workflow to reproduce:

Select a bundle
Open the web terminal
Hit "Escape" key
Typing "a" doesn't copy the command into the web terminal

**Comment by maxwang7** [comment]
Correction: You need to hit "escape" multiple times, hitting it only once doesn't lead to a problem.
