### ISSUE TITLE
Profile the slowness of each stage of a bundle

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3328]
Store the speed of each stage of a bundle in the bundle metadata.

- How long in STAGED
- How long in RUNNING
- etc.

**Comment by adiprerepa** [comment]
Note to self:

Should be able to mimic behavior of `time_used` & how its sent over the API in metadata and stuff.

benchmark transition here: https://github.com/codalab/codalab-worksheets/blob/dd81f5f0f5668ba4009a79418dd6c45e10a7d24e/codalab/worker/worker.py#L478

Open Questions:
- store time elapsed in database or start&end times?

**Comment by epicfaace** [comment]
Document the different kinds of times

**Comment by adiprerepa** [comment]
I think I will store start and end times in whatever `time.time()` gives me, and then get the diff when I send it over the API
