### ISSUE TITLE
generated summary inserts bundle uuid references too aggressively

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#333]
I have a bundle called `train` that has some uuid

Also a run bundle with command that includes the word `train` multiple times, none of them referring to the bundle named the same thing, yet the generated summary inserts the bundle uuid reference immediately after every `train` found.

Here is a screenshot (look at bundles named `run-answer`)

![screenshot 2017-06-03 01 09 35](https://cloud.githubusercontent.com/assets/4369332/26751962/0ebff516-47fa-11e7-905a-eab657c696d9.png)

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1063
