### ISSUE TITLE
[USER ISSUE] Caching not working

### ISSUE THREAD

**Issue by AnanyaKumar** [codalab/codalab-worksheets#3339]
**Describe the bug**
CodaLab isn't caching the data files and Docker containers even when running on the same machine multiple times. It says "Preparing" for a long time. This is on Stanford's NLP cluster on Jagupard16, if that helps.

**Codalab Information**
- *Your username*: skywalker94
- *UUID of worksheet where problem occurred*: 0x2613c7
- *UUID of problem bundle (please don't delete)*: 0x5970804e98b24de6923f9ee35e7a9f8e, 0x33dad0bec88a44009438a01ef51c728d
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*: 
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**
The data should be cached, ideally on the cluster (distributed file system?), but if not on the local machine? Thanks a lot for your help!

**Screenshots**

**Additional context**

**Comment by epicfaace** [comment]
Possible that the machine is running of space and purging Docker cache

**Comment by epicfaace** [comment]
- Problem is that slurm workers don't share a cache, but they should
- Solution: rethink caching for slurm workers

**Comment by epicfaace** [comment]
Relevant code for data cache: https://github.com/codalab/codalab-worksheets/blob/4206e0d10323e65113ece199658f41e4666b840b/codalab/worker/dependency_manager.py#L40

**Comment by epicfaace** [comment]
Closing this in favor of https://github.com/codalab/codalab-worksheets/issues/3647.
