### ISSUE TITLE
upload files directly to the bundle store

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#335]
Currently, RemoteBundleClient.upload_bundle first (via open_temp_file) copies things into a temporary directory, which is then copied into data.  But let us copy directly into data directory.  More specifically:

1) When user wants to upload something, we should immediately create a bundle with a uuid, add it to the current worksheet, etc., and set its state to a new state 'uploading'.
2) Then, RemoteBundleClient.upload_bundle should upload directly to the bundle data directory (we can even support partial uploads now!), updating the data_size incrementally.
3) When uploading is done, we compute the data_hash, and change the bundle state to 'ready', preventing further modifications.

For 2), we should think about what this will look like under the new REST API.

**Comment by kashizui** [comment]
#434 addresses all three issues, though incremental uploads are not technically supported yet: each upload will overwrite the previously uploaded data, and final upload can provide a `finalize` flag to lock in the contents of the bundle. We can look at how to support partial/resumable uploads in the future as a separate issue.
