### ISSUE TITLE
Enforce Single-Words for Tags

### ISSUE THREAD

**Issue by a10y** [codalab/codalab-worksheets#336]
Currently we don't enforce tags are single-words, but if we print them out on the command line as a set of space-separated characters it makes sense to check for this.

**Comment by kashizui** [comment]
This applies for both bundle and worksheet tags.
This should be enforced on the server side.

**Comment by karandesai-96** [comment]
Since merge of #543 , `cl edit <uuid> --tags a b c` results in three different tags. In my opinion, through a web interface, there shouldn't be a warning on spaces, but it should automatically treat the space separated entries as different tags. If this is not done, then anyone might be able to add only one tag through web interface  as I just checked, old tags are deleted before adding new entries whie updating metadata.

**Comment by karandesai-96** [comment]
@kashizui What are your thoughts on this ? I have found the place where change has to be made for worksheet metadata. I can sure go ahead and submit a patch to knock off this issue :smile:

**Comment by yshen-google** [comment]
I tried both ways (changing tags on UI and changing tabs through CLI) and my observations are following:
## Worksheet
### UI
In Worksheet UI, space is recognized as special character where it separates tags.
### CLI
In Worksheet CLI, space is recognized as special character where it separates tags when running `cl wedit --tags=<tags>`
## Bundle
### UI
In Bundle UI, space is recognized as special character where it separates tags and in CLI it is displayed with "|" to separate tags visually.
### CLI
In Bundle CLI, space is *not* recognized as special character and it is treated as a single tag.

There is inconsistency in bundle, and my proposal is as following:
1. Treat space as special character in Bundle for both CLI and UI to separate tags.
2. Remove the display of "|" in Bundle CLI when showing multiple tags.
3. Add support text to inform users of special character space.

The result will be using space to separate tags and if a user wants some tag like "the best", the user may need to modify it to something like "TheBest".

@percyliang WDYT? If the plan sounds good to you, I can proceed with PRs.

**Comment by percyliang** [comment]
Yes, I think this is a good plan.  Space should be treated as a delimiter and disallowed in tags.

**Comment by yshen-google** [comment]
A small correction to my comment above, it seems for CLI, both bundle and worksheet don't treat space as special delimiter for multiple tags. I will make the change for both.
