### ISSUE TITLE
Downloading a bundle fails intermittently

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#3363]
Downloading a bundle was stopped prematurely or the bundle would just be partially downloaded. This seems to be an intermittent issue.

Also, try downloading with `wget`.

Link to the bundle: https://worksheets.codalab.org/bundles/0x8b3255e21e164cd98d3aeec09cd0bc26/contents/

**Comment by percyliang** [comment]
@teetone : Probably a problem with the connection, unable to reproduce.
