### ISSUE TITLE
I can't receive confirmation email for sign-up.

### ISSUE THREAD

**Issue by skadms5355** [codalab/codalab-worksheets#3367]
**Describe the bug**
I don't receive any confirmation email not yet after sign-up.
I try to change my email address but I don't receive
You notice "Please contact us if you do not receive it within a few minutes."

**Codalab Information**
- *Your username*: skadms5355
- *Error message received from Codalab (if applicable)*: in dashboard, Error. Please provide a worksheet uuid

**Expected behavior**
I want to sign up successfully.

**Comment by adiprerepa** [comment]
sendgrid integration seems to be working. 

It looks like your email is correct too. Did you try, maybe another email address?

**Comment by adiprerepa** [comment]
maybe check your spam folder?

**Comment by skadms5355** [comment]
I tried to change another address but I can’t receive any email.
Also I checked spam folder but nothing.

**Comment by epicfaace** [comment]
@skadms5355 I just tried signing up for a new account and was able to receive the email. Which email address are you trying?

**Comment by nelson-liu** [comment]
fwiw, @ejones313 also ran into this (on the stanford instance). I think in his case, he hadn't clicked the link to confirm his account in time before it expired, and resending the email wasn't working.

**Comment by skadms5355** [comment]
Oh. I solved. I’m sorry.
I received email in another spam folder.
I can use dashboard. Thank you.
