### ISSUE TITLE
investigate time_user and time_system accuracy

### ISSUE THREAD

**Issue by adiprerepa** [codalab/codalab-worksheets#3369]
When I was working on https://github.com/codalab/codalab-worksheets/issues/3328, I noticed that `time_user` and `time_system` seemed to be always set to 0. 

I'm not 100% sure that this is an issue with in the prod database, need to check, but I am not sure how much it matters because it doesn't seem to be used anywhere. The `time` field that we see on worksheets.codalab.org on a bundle's completion seems to be accurate.

See #3328 's associated pr for more info.

**Comment by epicfaace** [comment]
We should remove `time_user`, and `time_system`.
