### ISSUE TITLE
bash: cl: command not found on web interface terminal

### ISSUE THREAD

**Issue by gmkim90** [codalab/codalab-worksheets#337]
Hi.
I am currently working on SQuAD QA challenge, and following submission tutorial exactly.
(https://worksheets.codalab.org/worksheets/0x8403d867f9a3444685c344f4f0bc8d34/#)

After successfully uploading predictions.json, when I run 
"cl macro squad-utils/dev-evaluate-v1.1 predictions.json"
it fails with message "bash: cl: command not found"

Did I miss anything?

**Comment by maxwang7** [comment]
@gmkim90 Sorry to hear that you're having that problem. We're taking a look, will get back to you soon.

**Comment by maxwang7** [comment]
@gmkim90 We just want to confirm where you ran this command: was it in the web interface (the gray bar on worksheets.codalab.org) or in your own shell after installing `codalab`?

**Comment by gmkim90** [comment]
It was in the web interface  (the gray bar on worksheets.codalab.org)

See attached log in worksheet.

[image: Inline image 2]



---------------------------
Ken Geonmin Kim
Ph.D Candidate
Computational Neuro System Laboratory
HP : ken.gmkim.kaist.ac.kr <http://kenkim.kaist.ac.kr>
Mobile: +82-10-9703-2947

**Comment by kashizui** [comment]
Hi @gmkim90 , it looks like you were trying to run this command _inside_ of a `cl run` command.
Try entering the command directly in the web terminal like so:

![screen shot 2017-06-11 at 9 01 30 pm](https://user-images.githubusercontent.com/614837/27018955-35cc0e60-4ee9-11e7-9acd-da78f953c48a.png)

**Comment by percyliang** [comment]
Please reopen if you're still having issues.
