### ISSUE TITLE
[USER ISSUE] Sporadically cannot write files in the bundle

### ISSUE THREAD

**Issue by HaritzPuerto** [codalab/codalab-worksheets#3374]
**Describe the bug**
I have a code that sometimes works and sometimes doesn't on codalab (It always works on local).
The error I get is a 

```
Traceback (most recent call last):
  File "run_prediction.py", line 63, in <module>
FileNotFoundError: [Errno 2] No such file or directory: './pred.json'
```
and that line is:
```
with open('./pred.json', 'w+') as f:
```

This bundle 0x23c5aa72af5b49a99e86f9c6eb38217b  shows the error. However, this other bundle, which is exactly the same, 0x41809449082f4ebaa1281d6dbf9e23fc works well.

Also, when executing the same project on larger data I got this other error when doing ```cd ../```:
```
cd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```
Unfortunately, I don't have the bundle with this error anymore. I had to remove it due to the disk space to keep doing more debugging on this problem.

Is it possible that the machine dies or the file system disappears while running the bundle?

**Codalab Information**
- *Your username*: haritz
- *UUID of worksheet where problem occurred*: 0x6f85515dc8cc4bf6b9255d6f9d620092
- *UUID of problem bundle (please don't delete)*: 0x23c5aa72af5b49a99e86f9c6eb38217b

Thank you.
Best,
Haritz

**Comment by nelson-liu** [comment]
The first problem seems like an instance of https://github.com/codalab/codalab-worksheets/issues/3236

**Comment by HaritzPuerto** [comment]
Thanks! My problem seems also similar to #3170

**Comment by epicfaace** [comment]
Now that #3236 been solved -- I'm going to close this as well. If you're still seeing this issue, though, please feel free to reopen.
