### ISSUE TITLE
[USER ISSUE] account verify problem on local server

### ISSUE THREAD

**Issue by yikedouer** [codalab/codalab-worksheets#3387]
I deployed a codalab server on my linux machine. I cant't accept the verify email after signup.
Need I deploy an email service? And how can I signup and verify elegantly in my local codalab service?
Is there a readme cause I didn't find any.

**Comment by jzwang43** [comment]
Hi yikedouer,

If you just need a test account for local development, you can use username codalab password codalab to login. We don't support verifying without an external email service, you can modify the code if you need local email service.
