### ISSUE TITLE
Creating Teams in Competition

### ISSUE THREAD

**Issue by huskyjo** [codalab/codalab-worksheets#339]
I am hosting competitions through Codalab and participants have been asking how to make teams. In other words, make it so more than a single account can make submissions on behalf of a Team (or however that would be done).

I did do a little digging around myself, but it still is not entirely clear to me how it works (and or if this is an option/ feature).

For instance, If you go into your account setting you are able to setup a team by specifying a team name and list members of the team. However, not clear how this links to specific competitions. 

Also, when you attempt to make a submission it prompts you for the team name, but still need to figure out if this links back to the settings. If so, how does it work (like can all members access submissions, make a submission, etc.)?

The competitions links are the following:
https://competitions.codalab.org/competitions/16742
https://competitions.codalab.org/competitions/16745

Any information and or reference you can provide would be much appreciated. We plan on using Codalab more in the future, so learning such details would be of value to our participants + future competitions that we plan to host.

Best regards,
Joe

**Comment by huskyjo** [comment]
@FlavioAlexander

**Comment by kashizui** [comment]
This is the repo for CodaLab Worksheets, please head over to (CodaLab Competitions)[https://github.com/codalab/codalab-competitions/issues?q=is%3Aopen] and re-open this issue there. Thanks!
