### ISSUE TITLE
UI is not honoring new lines \n for the command field

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#3394]
**Describe the bug**
I created a bundle with multiple commands separated by new lines `\n`. Should the UI show the multiple commands on separate lines?

![Screen Shot 2021-04-10 at 10 21 07 AM](https://user-images.githubusercontent.com/16793796/114278835-7a668900-99e6-11eb-8b59-f249fca3b583.png)

![new_lines](https://user-images.githubusercontent.com/16793796/114278772-2b205880-99e6-11eb-9019-3d4c1a18482c.png)

**Comment by leilenah** [comment]
resolved
