### ISSUE TITLE
Copy doesn't work on web cli

### ISSUE THREAD

**Issue by rajpurkar** [codalab/codalab-worksheets#340]
The shortcut command + c, command + v does not have intended copying behavior! It copies extra chunks of commands.

On mac OS sierra, chrome v58

**Comment by maxwang7** [comment]
@rajpurkar I'm not able to reproduce, I'm on OS X Yosemite with Chrome v59. Could you send me a video of this being reproduced or could you let me know some times you're available and I can drop by to debug?

**Comment by maxwang7** [comment]
@rajpurkar following up on this!

**Comment by maxwang7** [comment]
Closing for now, but let me know if you'd like me to come take a look at it sometime and I can reopen the issue then!
