### ISSUE TITLE
Look into GPU driver issue for Kubernetes GCP Worker Manager

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#3406]
From GCP documentation:
"After you create an instance with one or more GPUs, your system requires NVIDIA device drivers so that your applications can access the device. Make sure your virtual machine (VM) instances have enough free disk space (choose at least 30 GB for the boot disk when creating the new VM)."

Relevant links:

https://cloud.google.com/compute/docs/gpus/create-vm-with-gpus
https://cloud.google.com/compute/docs/gpus/install-drivers-gpu#no-secure-boot
https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#installing_drivers
https://cloud.google.com/ai-platform/deep-learning-vm/docs/cli#creating_an_instance_with_one_or_more_gpus
https://cloud.google.com/container-optimized-os/docs/how-to/run-gpus#install

**Comment by epicfaace** [comment]
Tony figured it out
