### ISSUE TITLE
Sentry is not working with dev / prod environments

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3416]
- Sentry is not working with dev / prod environments. It only works with the stanford environment.

![image](https://user-images.githubusercontent.com/1689183/115161061-821ed100-a069-11eb-8bc1-d69c70c00a4f.png)

**Comment by adiprerepa** [comment]
Looks like the sentry environment (stanford, dev, prod...) is set https://github.com/codalab/deployment/blob/master/ansible/roles/server/vars/main.yml#L12

But when I run `env | grep SENTRY` on the docker container for our current dev instance, there is no environment variable set. I assume this means the system thinks `mode` is blank, but I think we set it here: https://github.com/codalab/deployment/blob/master/ansible/roles/dev/vars/main.yml#L2

When we deploy, we also include the `-e mode=dev` flag, maybe that's overwriting it? It shouldn't really matter either way.

Thoughts @epicfaace?

**Comment by epicfaace** [comment]
I'm not sure. Maybe you can try creating a new variable called sentry_mode and see if that fixes it?

**Comment by adiprerepa** [comment]
yeah maybe that will work. 

It looks like some of the other values in `dev/vars/main.yaml` are also not being populated into the template. This may be a deeper issue...

**Comment by epicfaace** [comment]
See this: https://github.com/codalab/codalab-worksheets/blob/master/docker_config/compose_files/docker-compose.yml#L11
