### ISSUE TITLE
CodaLab development doesn't work on Apple Silicon

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3420]
The docker images need to be built for ARM.

**Comment by jzwang43** [comment]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/29891066/120038597-5e2fa300-bfb8-11eb-9651-b27e1e0c98b3.png">

This is the error I have been encountering. My guess is m1 can only run arm versions of the docker images and it may not work very well with many packages.

**Comment by epicfaace** [comment]
pyarrow is a dependency of apache beam -- so we could track https://issues.apache.org/jira/browse/BEAM-11703

**Comment by pranavjain** [comment]
Created a separate [branch](https://github.com/codalab/codalab-worksheets/tree/osx-m1) that contains the relevant changes to run the CodaLab on M1-based computers. I have only tested the frontend part of CodaLab yet.

Mysql docker image is not available for M1 yet. Replaced it with MariaDB as a temporary workaround.

Updated the disclaimer in the [Readme](https://github.com/codalab/codalab-worksheets/blob/osx-m1/README.md) file.

**Do not merge the M1 branch into the master.**
