### ISSUE TITLE
Blob storage - Support S3

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3441]
For blob storage, we should support S3 as a backend.

Perhaps we can configure it so that if someone specifies S3 credentials, they are used; otherwise, if Azure Blob Storage credentials are specified, they should be used.

When S3 credentials are specified, [the implementation of `get_bundle_location`](https://github.com/codalab/codalab-worksheets/blob/be5d92d038471da59eee1a493c60f346a6b94188/codalab/lib/bundle_store.py#L419) should return a url with protocol s3:// instead of azfs://. The Apache Beam Filesystem methods should just work out of the box with the S3 URLs.

**Comment by percyliang** [comment]
Not a priority, closing for now.
