### ISSUE TITLE
Unable to download Docker image: write /mnt/scratch/docker/tmp/GetImageBlob378972156: no space left on device

### ISSUE THREAD

**Issue by cooelf** [codalab/codalab-worksheets#345]
Hi, I have signed up an account and tried to run the "sort.py" sample  from the Quickstart instruction. But when running the script, it failed with hints: "**Unable to download Docker image: write /mnt/scratch/docker/tmp/GetImageBlob378972156: no space left on device**". 

I have tried several examples but all of them were not running normally.  Since this is a new account, I should have 10 GB space. And it seems to be an erro from the image provider. What should I do to fix this problem?  

This is one of the bundles: 
https://worksheets.codalab.org/bundles/0xb22745896f1a4b6d888b7f0c4127e20e/

**Comment by percyliang** [comment]
Should be resolved now - was an internal problem.
