### ISSUE TITLE
Failed to download dependency celebA: Dependency download failed: IncompleteRead(0 bytes read)

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3457]
See https://worksheets.codalab.org/bundles/0xc26e560d35d94a2aa475ac8a2acb2df9

**Comment by nelson-liu** [comment]
i usually see this when the server is restarted during a download---maybe @yuqijin deployed while the worker was trying to pull? not sure theres a good way to avoid this

**Comment by epicfaace** [comment]
Decided in meeting: catch the exception and retry up to 3x (because this is a transient issue happening during deployment)
