### ISSUE TITLE
BundleStore Sanity Check Script

### ISSUE THREAD

**Issue by a10y** [codalab/codalab-worksheets#346]
Add a script under `scripts/sanity-check_bundlestore.py` that:
- Checks to see if there are any bundles on disk that are not in the database. These need to be relocated to some sort of trash directory
- For each bundle, make sure its input dependencies don't show up as directories inside of the bundle.  (Currently, this should be done only for `ready` or `failed` bundles.)
- No files aside from ones matching the UUID pattern should exist in the `bundles/` directory.
- For bundles that have a `UUID.cid` file or `UUID.status/` directory should not have state `ready` or `failed`.

**Comment by a10y** [comment]
Since we're going to make this a command on the CLI, it might be better to add this as a method inside of MultiDiskBundleStore, and then hook this into bundle_cli

**Comment by percyliang** [comment]
Yes.
