### ISSUE TITLE
investigate using a CODEOWNERS or github teams

### ISSUE THREAD

**Issue by adiprerepa** [codalab/codalab-worksheets#3462]
I think we should have one or the other - most organizations do.

Benefits would be automatic code review requesting and more granular responsibilities.

cc @epicfaace

**Comment by adiprerepa** [comment]
I think we should use github teams. It greatly simplifies grouping people and we prevent `CODEOWNERS` that look like this:

```
/codalab/ @adiprerepa @epicfaace @yuqijin @jzwang43 @teetone @percyliang
/docker_config/ @adiprerepa @epicfaace @jzwang43 @teetone @percyliang
/docs/ @adiprerepa @epicfaace @jzwang43 @teetone
/frontend/ @adiprerepa @epicfaace @jzwang43 @teetone
/scripts/ @adiprerepa @epicfaace @jzwang43 @teetone
```

wdyt @epicfaace @percyliang @teetone @yuqijin @jzwang43?

**Comment by epicfaace** [comment]
About this idea, I'm just a bit unsure about the benefits we'd get from it. It doesn't seem too onerous to just request the right people to review a new PR, and when using CODEOWNERS before, the problem with having too many people is that too many people are requested on every PR review. I think we're a small enough team that we may not really need CODEOWNERS.
