### ISSUE TITLE
-bash: cl: command not found. I had installed codalab and python 3.7. The issue maybe the path, I carry out the instructions in ~/.local/lib/python3.7/site-packages/codalab

### ISSUE THREAD

**Issue by ADaBenxiong** [codalab/codalab-worksheets#3465]

**Comment by ADaBenxiong** [comment]
-bash: cl: command not found. I had installed codalab and python 3.7. The issue maybe the path, I carry out the instructions in ~/.local/lib/python3.7/site-packages/codalab

**Comment by epicfaace** [comment]
@ADaBenxiong are you still facing this issue?
