### ISSUE TITLE
"sign in" and "sign up" pages should use material-ui components

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3471]
The "sign in" and "sign up" pages should use material-ui components. We should change the buttons to be material-ui buttons (like the buttons on the home page) and perhaps change the text boxes as well.

![image](https://user-images.githubusercontent.com/1689183/117371674-4b80ed00-ae96-11eb-992c-48b05babbc84.png)
![image](https://user-images.githubusercontent.com/1689183/117371689-4fad0a80-ae96-11eb-8534-9e864a3af1f4.png)

**Comment by leilenah** [comment]
Duplicate
https://github.com/codalab/codalab-worksheets/issues/4193
https://github.com/codalab/codalab-worksheets/issues/4194
