### ISSUE TITLE
Uncaught TypeError: le(...).then(...).fail is not a function

### ISSUE THREAD

**Issue by mneilly-et** [codalab/codalab-worksheets#3484]
**Describe the bug**

Hello, I was going to try out Codalab so I cloned the repo to setup a standalone server and started it up with "codalab_service.py start --version v.05.49" (also tried master). I am able to signup and view the user page. When I click "Add" to add a new worksheet I get the popup and enter a name for the worksheet. At that point nothing happens a new error does show up in the developer console:

>react-dom.production.min.js:52 Uncaught TypeError: le(...).then(...).fail is not a function
    at n.value (MainPanel.js:238)
    at onClick (MainPanel.js:374)
    at Object.u (react-dom.production.min.js:14)
    at p (react-dom.production.min.js:14)
    at react-dom.production.min.js:14
    at m (react-dom.production.min.js:15)
    at at (react-dom.production.min.js:52)
    at it (react-dom.production.min.js:51)
    at ut (react-dom.production.min.js:52)
    at pt (react-dom.production.min.js:56)
value	@	MainPanel.js:238
onClick	@	MainPanel.js:374
u	@	react-dom.production.min.js:14
p	@	react-dom.production.min.js:14
(anonymous)	@	react-dom.production.min.js:14
m	@	react-dom.production.min.js:15
at	@	react-dom.production.min.js:52
it	@	react-dom.production.min.js:51
ut	@	react-dom.production.min.js:52
pt	@	react-dom.production.min.js:56
N	@	react-dom.production.min.js:287
V	@	react-dom.production.min.js:19
Qt	@	react-dom.production.min.js:70
Zt	@	react-dom.production.min.js:69
t.unstable_runWithPriority	@	scheduler.production.min.js:19
Ui	@	react-dom.production.min.js:122
j	@	react-dom.production.min.js:287
Xt	@	react-dom.production.min.js:68

</span></div>

**Codalab Information**
- *Your username*:
- *UUID of worksheet where problem occurred*:
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :
1.  git clone https://github.com/codalab/codalab-worksheets
2. goto web page
3. signup
4. login
5. Click green "Add" button

**Expected behavior**

I'm expecting a new worksheet to show up in the list.

**Screenshots**

![image](https://user-images.githubusercontent.com/55827703/117516916-5f3c5a00-af4f-11eb-8468-d524100f6d92.png)

**Additional context**

**Comment by epicfaace** [comment]
@yuqijin @jzwang43 there are several places in the code where we use `.fail`. We might need to change them all to use `.catch` instead to fix issues like this one.

**Comment by jzwang43** [comment]
@epicfaace This has been fixed in the recent #3482. I have checked and looks like no `.fail` is in the code anymore. Thus we should close this for now.
