### ISSUE TITLE
revamp interpretation code

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#349]
Remove the `/interpret/worksheet/` endpoint and just consolidate the logic into the fetching of worksheets.  This involves both frontend and backend coordination.

This requires using JSON API to model the interpreted worksheet items (let's call them worksheet blocks to distinguish between raw items).  This should make the interpretation logic a lot cleaner.

**Comment by bkgoksel** [comment]
Closed with #915
