### ISSUE TITLE
Change worksheets-examples to use python 3, not python 2

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3495]
See https://github.com/codalab/worksheets-examples/tree/master/01-nli

**Comment by jzwang43** [comment]
@epicfaace I just checked and looks like this example is already in python3? If might just be a typo that it says python2. I tried the tutorial and it worked fine.

**Comment by epicfaace** [comment]
Yeah, it could just be the typo

**Comment by jzwang43** [comment]
There is already a pull request to fix the typo:
https://github.com/codalab/worksheets-examples/pull/12
Will close this issue after the PR gets merged.
