### ISSUE TITLE
'a' and 'u' keys should work for all bundles

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#35]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Tuesday Dec 08, 2015 at 09:16 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1488_

---

Currently, this works only for rows in tables.  But for images, contents, graphs, etc. this should also work.  Might be wise to do this after we refactor those classes.

**Comment by percyliang** [comment]
Not important.
