### ISSUE TITLE
[USER ISSUE] Cannot create worksheet

### ISSUE THREAD

**Issue by mneilly-et** [codalab/codalab-worksheets#3500]
**Describe the bug**

This was originally reported in #3484 but I guess I conflated two issues not knowing if the error message I was seeing was related to the problem I'm having.

I am still unable to create a new worksheet with the standalone server.

**Codalab Information**

Running standalone docker containers in master branch: 56ddc914aa3c3ba6afad3128b870db22e3cf9216

**To Reproduce**

1.  git clone https://github.com/codalab/codalab-worksheets
2. cd codalab-worksheets
3. ./codalab_service.py build
4. ./codalab_service.py start
2. goto web page
3. signup
4. login
5. Click green "Add" button
6. Enter name for worksheet
7. Nothing happens (see video)

**Expected behavior**

A new worksheet is created per the Quick Start docs at https://codalab-worksheets.readthedocs.io/en/latest/examples/quickstart/

![image](https://user-images.githubusercontent.com/55827703/117825736-6b146e80-b224-11eb-9db2-0a9cbc47af50.png)

**Additional context**

The video shows the issue.

https://user-images.githubusercontent.com/55827703/117826204-d5c5aa00-b224-11eb-94c6-a7c2761b8f32.mp4

**Comment by epicfaace** [comment]
cc @yuqijin @jzwang43 

@mneilly-et , does the button next to the "My Profile" in the navbar work for you to create a new worksheet? Or is that one also broken?

**Comment by mneilly-et** [comment]
@epicfaace, neither button works...

**Comment by jzwang43** [comment]
I tried with local `codalab` account and it worked. I don't think locally a new user can create a new worksheet since the account cannot be verified, but I guess there should be a error message at least.

**Comment by yuqijin** [comment]
> I tried with local `codalab` account and it worked. I don't think locally a new user can create a new worksheet since the account cannot be verified, but I guess there should be a error message at least.

What @jzwang43 said is correct. On a local server, since you did not verify your account, you could not create your worksheet except that you use the default account `codalab`.

**Comment by mneilly-et** [comment]
An error would definitely be preferable to silent failure... Is standalone intended to only work with a single user?

I am able to create a new worksheet after setting is_verified=1 in the user table.

**Comment by epicfaace** [comment]
> Is standalone intended to only work with a single user?

It's not intended to; as long as you specify SMTP credentials when starting up codalab service locally, the verification email should be sent.

A nice-to-have improvement, though, would be to maybe print out verification emails to the console if SMTP credentials are not provided. As of now, the manual workaround that you mentioned is the only other way to verify a user without SMTP credentials.

**Comment by epicfaace** [comment]
I'm going to close this issue as it's related to email verification instead. If you'd like, you could open a separate issue about that, though.
