### ISSUE TITLE
CodaLab down, site wide

### ISSUE THREAD

**Issue by lynn-he** [codalab/codalab-worksheets#3511]
CodaLab down on 5/13 between 3:45 and 4:15 PM PST. When refreshing the worksheet page, all bundles disappear. After clicking on the 'my profile' page, no worksheets are listed. Consistent across all worksheets and bundles. 

**Codalab Information**
- *Your username*: DeepLearning.AI
- *UUID of worksheet where problem occurred*: All
- *UUID of problem bundle (please don't delete)*: All
- *Error message received from Codalab (if applicable)*: N/A
 - *OS (if on CLI)*: across multiple machines, seemed site wide. 
 - *Codalab CLI Version (if on CLI)*: 0.5.47
 - *Browser (if on Web)*; Multiple browser types.

**Expected behavior**
The when refreshing, that the bundles and worksheets would appear. 

**Screenshots**
N/A

**Additional context**
This seemed to be site wide, had several team members try to see if they could see the worksheets and bundles on their own logins.

**Comment by epicfaace** [comment]
I believe this was due to a deployment issue we had during that time. That was a one-off issue and shouldn't happen again, sorry for the inconvenience.

@jzwang43 can you confirm that is the case?

**Comment by jzwang43** [comment]
@epicfaace @lynn-he 
Yes this was caused by the deployment issue we had. We will take actions to prevent this from happening in the future.
