### ISSUE TITLE
Manual upload fails when not focusing on an item

### ISSUE THREAD

**Issue by lynn-he** [codalab/codalab-worksheets#3512]
Manual file upload fails for multiple users, starting Friday 5/14 and persisting since.

**Codalab Information**
- *Your username*: DeepLearning.AI
- *UUID of worksheet where problem occurred*: All worksheets
- *UUID of problem bundle (please don't delete)*: All new attempted uploads.
- *Error message received from Codalab (if applicable)*: N/A
 - *OS (if on CLI)*: Multiple
 - *Codalab CLI Version (if on CLI)*: 0.5.47
 - *Browser (if on Web)*; Multiple

**To Reproduce**
Steps to reproduce the behavior :
1. Go to any worksheet
2. Click on `UPLOAD`, select file.
3. Refresh page after the file doesn't upload (has 0%)
4. See no new bundles.

**Expected behavior**
To see new bundles after selecting the files to upload. 

**Screenshots**
See screenshot of the frozen screen after selecting file for upload. After refreshing the page, the worksheet remains blank. 
<img width="1407" alt="Screen Shot 2021-05-16 at 12 04 33 PM" src="https://user-images.githubusercontent.com/51978114/118407633-a90ff900-b64f-11eb-8d7f-27d5fe06a125.png">

**Additional context**
I experienced this problem on my CodaLab account, multiple beta testers for our competition also reported issues with manual uploading.

**Comment by epicfaace** [comment]
Getting this error (cc @yuqijin ):

![image](https://user-images.githubusercontent.com/1689183/118410432-68b77780-b65d-11eb-8ae3-ce9a4b4a2a92.png)

![image](https://user-images.githubusercontent.com/1689183/118410436-6e14c200-b65d-11eb-9520-8adc25cfb145.png)

**Comment by epicfaace** [comment]
@lynn-he thanks for reporting. You should be able to work around this issue for now by selecting an item in the worksheet (such as a markdown block) and then clicking "Upload". We're working on fixing this otherwise!

**Comment by lynn-he** [comment]
Thanks!
