### ISSUE TITLE
Manual upload request failed

### ISSUE THREAD

**Issue by lynn-he** [codalab/codalab-worksheets#3525]
When uploading a zip folder of 60,000 MNIST png images, upload request fails. After refreshing and trying again as error message suggests, upload still fails. 

**Codalab Information**
- *Your username*: DeepLearning.AI
- *UUID of worksheet where problem occurred*: 0x54ed2618d75944f789477fc15ea660c8
- *UUID of problem bundle (please don't delete)*: 0x96c6d1730321450b8876a38bbe4ae19d
- *Error message received from Codalab (if applicable)*: 
<img width="1135" alt="Screen Shot 2021-05-18 at 10 57 16 AM" src="https://user-images.githubusercontent.com/51978114/118693419-05eaeb00-b7d9-11eb-813e-db9ed2b48f07.png">

 - *OS (if on CLI)*: MacOS Catalina Version 10.15.17
 - *Codalab CLI Version (if on CLI)*: 0.5.47
 - *Browser (if on Web)*; Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Go try to manual upload this zip file:
[upload_assets.zip](https://github.com/codalab/codalab-worksheets/files/6503032/upload_assets.zip)

**Expected behavior**
To upload the zip file and find a bundle ready appended to end of worksheet

**Additional context**
There seems to be some sort of limit on bundle upload size. In this worksheet I've tested manually uploading zip files of MNIST images, when it gets to 40000 images the upload fails. https://worksheets.codalab.org/worksheets/0x54ed2618d75944f789477fc15ea660c8

**Comment by dillonalaird** [comment]
Hey @epicfaace, I'm working on this project with @lynn-he. Would it be possible to setup a zoom call to discuss the issue?

**Comment by epicfaace** [comment]
Hmm, when I try downloading that zip file and unzipping on my own computer, I get an error:

![image](https://user-images.githubusercontent.com/1689183/118732511-79f0b780-b808-11eb-99d9-45a51ae8183f.png)

Are you sure this is a properly formed zip file?

**Comment by epicfaace** [comment]
Maybe you could try changing it to a .tar.gz archive and uploading it instead?

**Comment by lynn-he** [comment]
changing the zip worked, thank you!
