### ISSUE TITLE
Update and make default-cpu / gpu dockerfiles smaller

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3526]
Update (to latest ubuntu) and make default-cpu / gpu dockerfiles smaller

**Comment by jzwang43** [comment]
@epicfaace Do we want to get rid of python 2? It's no longer supported and requires a lot of dockerfile changes if we upgrade to 20.04.

Also do we want to upgrade default-gpu to the latest cuda image (11.3.0-cudnn8-devel-ubuntu20.04)?

**Comment by epicfaace** [comment]
I think we probably want to keep python 2 because people still use it in research. @percyliang @nelson-liu @teetone  would have a better perspective on this though.

Let's hold off on cuda upgrades for now (unless the current version is end-of-life?) We tried doing so before and it seems like it might be nontrivial / could require careful understanding of breaking changes: https://github.com/codalab/codalab-worksheets/pull/2528

**Comment by jzwang43** [comment]
@epicfaace I think cuda9 only works with 16.04 and 17.04 (https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/unsupported-tags.md), do we want to hold off updating deafult-gpu and just update the default-cpu dockerfile for now?

**Comment by epicfaace** [comment]
I think in that case, because we need to update ubuntu to 20 (to keep getting security updates), we should also go ahead and upgrade cuda.
