### ISSUE TITLE
when select new bundle on worksheets w/o contents, contents in side panel doesn't update

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#353]

**Comment by maxwang7** [comment]
@percyliang could you elaborate more on the bug? I tried creating a new bundle that didn't produce any contents in an empty worksheet, and the side panel updated with the metadata information appropriately.

**Comment by maxwang7** [comment]
I also tried adding a bundle UUID to an empty worksheet and the sidepanel loaded correctly.

**Comment by percyliang** [comment]
Did you try creating two bundles, one with contents, and one without and
then use 'k'/'j' to go between the two?

**Comment by maxwang7** [comment]
Found the problem, this worksheet has it (you have to go to the third item in the page): https://worksheets.codalab.org/worksheets/0xcd8935a0cea047259761e3dae2411e9f/
