### ISSUE TITLE
% display contents crashes the web app if the path is wrong

### ISSUE THREAD

**Issue by krivard** [codalab/codalab-worksheets#354]
I just spent a while panicking because it looked for a moment like the app ate a rather large worksheet, and it turns out I'd just mistyped a path in a `% display contents` directive. I've been able to reproduce the error to figure out the consistent behavior described below. Literally any other response to this type of operator error would be preferable :)

1. Edit the worksheet to include a display contents directive. Type garbage in for the path. Follow with a valid UUID.
1. Hit ^ENTER or the save button. It appears to save as usual.
1. Hit 'e' to re-enter the editing interface. This has no effect.
1. Hit the "Edit Source" button. This has no effect.
1. Interface appears frozen. Reload the page.
1. Worksheet title reads <none> and body reads (empty)
1. The only buttons available are "View" and "View Source"
1. "View Source" shows a source view of the original content. Hooray, it's not gone! We also see the message "Press ctrl-enter to save. See markdown syntax." even though we're not in the editor. Buttons are "Save" and "Discard Changes".
1. Click "Save". Interface enters edit mode, and the "Updating..." widget spins indefinitely. 
1. Further clicks on "Save" have no effect. "Discard Changes" returns to source view mode, but "Updating..." perseveres.
1. 'e' has no effect.
1. ^ENTER enters edit mode.
1. Reloading the page returns to <none> / (empty)

When I load the bad sheet with the javascript console open, I get the error "this.props.item.interpreted is null ...  contents_item_interface.js:21:13"

This clued me in that it was an issue with the contents directive, and I was able to edit and binary-search my way through the document using the command-line editor on my local machine... but there's gotta be a more graceful way to handle the issue in the frontend.

**Comment by maxwang7** [comment]
@krivard thank you for the detailed bug description! I have a PR to fix this problem, it should be merged soon.
