### ISSUE TITLE
change the location of cl-worker-manager on the NLP cluster

### ISSUE THREAD

**Issue by adiprerepa** [codalab/codalab-worksheets#3541]
just a reminder to myself to do this - blocked until my codalab account gets approval on codalab.stanford.edu

currently, the `cl-worker-manager` location is `/juice/scr/nfliu/public/cl_public_main/bin/cl-worker-manager`. This is on @nelson-liu's account, and we should change it to a better location.

**Comment by adiprerepa** [comment]
We should change the location to the codalab account

**Comment by epicfaace** [comment]
@adiprerepa can you update the description of this issue with additional context about the problem and what the solution is? (So that someone with little to no context about the issue (like me) can quickly get up to speed on what's going on)

**Comment by epicfaace** [comment]
@adiprerepa before you close it, can you note what you did to fix it (what location did you change it to)?

**Comment by adiprerepa** [comment]
I changed the location to `/u/nlp/anaconda/main/anaconda3/envs/default-py37/bin/cl-worker` for the worker, instead of it being on nelsons account

**Comment by epicfaace** [comment]
You meant `/u/nlp/anaconda/main/anaconda3/envs/default-py37/bin/cl-worker-manager`, right? Sounds good.
