### ISSUE TITLE
Run bundles that depend on link bundles seem to fail

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3542]
See https://codalab.stanford.edu/bundles/0x2127059265bc413c84110186ae1f2444

Reported by @percyliang 

cc @teetone

**Comment by epicfaace** [comment]
@percyliang is this still an issue? I don't remember what this was about and I can't access the original bundle.

**Comment by percyliang** [comment]
I think this is fixed since the my demo worked last time.
