### ISSUE TITLE
Can't view contents of a --link bundle in the UI, but can see it in --interactive

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3543]
Reported by @percyliang 

>  It seems like I can't view the files of a --link bundle, either in the frontend or via cl cat

> I ran it in --interactive and it worked (I was able to see the bundle)

To reproduce:

```
cd /u/scr/pliang
cl up project --link
cl cat project
cl run :project ‘’ --interactive
```

**Comment by epicfaace** [comment]
@teetone can you look into this, and if the CODALAB_LINK_MOUNTS change fixed it (https://github.com/codalab/deployment/pull/150), just go ahead and close this issue?

**Comment by teetone** [comment]
@epicfaace Actually, it doesn't work even with the CODALAB_LINK_MOUNTS change. Do you mind taking a look since your more familiar with the `--link` feature?

**Comment by epicfaace** [comment]
I don't think the CODALAB_LINK_MOUNTS change was deployed yet (https://github.com/codalab/deployment/commit/d3f47cb1b71b8a7608681193e189499b840012dd) to codalab.stanford.edu. It looks like if I run cl upload --link with a file in /u/scr/nlp, it works, but doesn't work from /u/scr/ashwin99. This is most probably because the CODALAB_LINK_MOUNTS change hasn't yet been deployed.

**Comment by epicfaace** [comment]
The fix was to add /juice/scr to CODALAB_LINK_MOUNTS (https://github.com/codalab/deployment/pull/154). This is because /u/scr/pliang is a symlink to /juice/scr/pliang. We may need to merge https://github.com/codalab/deployment/pull/155 to fix this experience for all users (can you take a look, @percyliang ?)

**Comment by epicfaace** [comment]
Once https://github.com/codalab/deployment/pull/155 is merged, we can close this issue.
