### ISSUE TITLE
Bundles take forever in codalab.stanford.edu

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#3550]
- Bundles take forever to run
- Reduce number of staged bundles
- In staged state for a long time
- Finalizing takes for every due to lots of jobs on the instance
- Target goal: slurm, gcp: `cl run date` have it finish in 30 seconds

**Comment by epicfaace** [comment]
Replaced by #3563 which is the root cause of the issue.

**Comment by epicfaace** [comment]
@teetone make issues for some of the most important other things we could do to make it faster
