### ISSUE TITLE
Bundle refreshing is slow on codalab.stanford.edu

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#3551]
Worksheet refreshing unexpectedly and ruining the client state (e.g., when we have bundle views open) when there are running/staged bundles. This especially happens on codalab.stanford.edu

**Comment by yuqijin** [comment]
Hi, the merged PR should have fixed this: https://github.com/codalab/codalab-worksheets/pull/3547
Could you try with the latest Master branch?

**Comment by yuqijin** [comment]
For the job creating a file, the detail will still refresh and shows the new file.  @teetone 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/34461466/119738851-344e7300-be36-11eb-8698-13ea1db617f3.gif)
