### ISSUE TITLE
Move `run_status` so it's right under `state` in the bundle view for more visibility 

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#3552]
Move run_status to right under state in the bundle view to give more visibility

Run status:

![Screen Shot 2021-05-26 at 1 55 09 PM](https://user-images.githubusercontent.com/16793796/119729900-06633180-be2a-11eb-97fc-b1926e88dfa0.png)

State:

![Screen Shot 2021-05-26 at 1 55 15 PM](https://user-images.githubusercontent.com/16793796/119729919-0a8f4f00-be2a-11eb-9eda-a9964fbfb80f.png)

**Comment by percyliang** [comment]
More generally, the 'state' sometimes displays something that's not actually the state - like 'preparing docker image'.  This whole logic should be a bit more unified.
