### ISSUE TITLE
Don't check _fail_unresponsive_bundles() every iteration of the bundle manager

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#3563]
Currently, we are checking `_fail_unresponsive_bundles()` every iteration of the bundle manager. This can be expensive as we are gather all running, staged and uploading bundles.

**Comment by epicfaace** [comment]
Note: we want to look at timings of different bundle manager stages, Jane looked at timings earlier, see her doc

**Comment by epicfaace** [comment]
Closing in favor of doing more research as mentioned in https://github.com/codalab/codalab-worksheets/issues/3646
