### ISSUE TITLE
Remote for a bundle run on cloud workers shows up as $(hostname -s)-<some worker id>

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#3577]
For bundles that ran on GCP and AWS workers, the remote shows up as `$(hostname -s)-<some worker id>`. We should get rid of host name for the cloud workers (not Slurm workers) and prepend the cloud service identifier:

`azure-<some worker id>`
`gcp-<some worker id>`
`aws-<some worker id>`

Just the worker ID is needed to search logs in the console.

**Comment by epicfaace** [comment]
@teetone Can you work on this solution?

**Comment by percyliang** [comment]
Already fixed.
