### ISSUE TITLE
Notes after Friday's demo

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3581]
- long pause after running cl upload tar.gz file
- nlp should be default alias by default
- upload a folder using --link, preview contents of a file with the web UI, edit the file, refresh the web UI and you temporarily got 404 when editing a fileet a 404
- maybe turn --request-worker by default
- putting --exclude-patterns before -i doesn't work
- should --exclude-patterns be by default?
- frontend bug: sometimes "edit and rerun", the bundle gets added to the top of the worksheet instead of after the current bundle row
- schema editor: pre-populate the textboxes with some better defaults
- schema editing: when clicking on something else (refreshed), the schema gets wiped out
- when editing a table's headers, pressing ctrl + enter doesn't save
- caching output of bundles (stale-while-revalidate)
- dropdown for the available queues
- schemas: time should default to duration, size should default to size
- schemas: editing schemas doesn't rerender a table.

demos:
- demos
- automated test for E2E demo

**Comment by epicfaace** [comment]
TODO: create separate issues from these.

**Comment by percyliang** [comment]
This is stale, redo demo and collect new issues.
