### ISSUE TITLE
Loading a non-existent bundle shows "Loading..." sign forever

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3582]
Loading a non-existent bundle shows "Loading..." sign forever. It should show an error instead.

For example, https://worksheets.codalab.org/bundles/0xd57659a938534b928f9d1cee82089f03

![image](https://user-images.githubusercontent.com/1689183/120246971-dd82d800-c23f-11eb-9550-4049c7ce485c.png)

**Comment by leilenah** [comment]
Resolved

![image](https://user-images.githubusercontent.com/25855750/199908405-1471c2ce-b171-468b-aced-d62e430aa1cc.png)
