### ISSUE TITLE
Server deployment tutorial update? +production server mods

### ISSUE THREAD

**Issue by krivard** [codalab/codalab-worksheets#359]
Hi! I'm working on setting up a small codalab cluster on our lab's existing hardware. I've been trying to follow the server setup tutorial [here](https://github.com/codalab/codalab-worksheets/wiki/Server-Setup) and am stuck. It looks like some of these features have drifted:

- fabfile.py does not exist (bummer, since I was hoping to crib off of it for a production deployment)
- config_gen does not produce supervisord.conf
- nginx file produced by config_gen has changed names
- ubuntu and homebrew nginx instructions are incomplete (or possibly refer to an old version of nginx; maybe /etc/nginx/server has been changed to sites_available|enabled?)

I was able to piece most of an install together by reading the existing source and digging through git history (so clearly that should go on someone's list, or, once I have this working I'm happy to do it and submit a PR), but really I need something that lets me deploy with a hostname and not localhost.  This is obviously possible, but perhaps the details were moved to a private repo (#286?). I've tried the obvious replace-localhost/127.0.0.1-with-hostname in the config files, with no luck yet.

**Comment by maxwang7** [comment]
@krivard Thanks for your issue! Hm, let me try going through instructions again myself tomorrow. The last time I tried it was at the start of this year so it's possible that things have broken. And what are you hoping to change the hostname to?

**Comment by krivard** [comment]
The name of the server it's running on, a fully-qualified domain name on the open internet. I could probably do an IP address instead if needed though.

**Comment by fabeschan** [comment]
Just to confirm, you've tried setting server_name in nginx.conf and that didn't work?

**Comment by maxwang7** [comment]
@krivard 

Below is a sample of my personal `codalab.conf` file -- I have marked the lines that you'll need to change to point to the correct local path on your machine. You'll want to create a symlink to this file (`codalab.conf`) from `/etc/nginx/codalab.conf` and add the statement `include /etc/nginx/codalab.conf;` into the `http` portion of the `nginx.conf` file. Let me know what happens when you try that.

```upstream django {
    
    server 127.0.0.1:2700;
    
}

upstream rest {
    server 127.0.0.1:2900;
}



server {
    set $maintenance 0;

    
    listen 8000;
    

    proxy_http_version 1.1;

    gzip on;
    gzip_min_length  4096;
    gzip_buffers  4 32k;
    gzip_types    application/x-javascript text/css;
    gzip_vary on; 

    server_name localhost;
    charset     utf-8;
    client_max_body_size 4096m;
    client_body_buffer_size 64m;

    # Turn off request body buffering to allow direct streaming uploads.
    # Note that the request body will be buffered regardless of this directive   
    # value unless HTTP/1.1 is enabled for proxying (configured above).
    proxy_request_buffering off;

    #keepalive_timeout 10;
    #proxy_buffering off;
    #proxy_connect_timeout       1200;
    #proxy_send_timeout          1200;
    #proxy_read_timeout 1200;
    #send_timeout 1200;

    location /bundleservice {
        if ($maintenance = 1) {
            return 503;
        }
        proxy_pass http://rest/bundleservice;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_connect_timeout       1200;
        proxy_send_timeout          1200;
        proxy_read_timeout          1200;
        send_timeout                1200;
    }

    location /rest {
        if ($maintenance = 1) {
            return 503;
        }
        proxy_pass http://rest;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_connect_timeout       1200;
        proxy_send_timeout          1200;
        proxy_read_timeout          1200;
        send_timeout                1200;
    }

    location /media  {
        alias /home/max/codalab/codalab-worksheets/codalab/media;  # TODO your Django project's media files - amend as required
    }

    location /static {
        alias /home/max/codalab/codalab-worksheets/codalab/apps/web/static; # TODO your Django project's static files - amend as required
    }

   location / {
        if ($maintenance = 1) {
            return 503;
        }

        proxy_pass http://django/;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_connect_timeout       1200;
        proxy_send_timeout          1200;
        proxy_read_timeout          1200;
        send_timeout                1200;

    }

    error_page 503 /error/503.html;
    error_page 502 /error/50x.html;
    location ^~ /error/ {
        internal;
        root /home/max/codalab/codalab-worksheets/codalab/apps/web/static; # TODO
    }
}```

**Comment by krivard** [comment]
1. `server_name` - I got errors from nginx using the default, out-of-the-box configuration, complaining about a duplicate server_name. It turns out the Ubuntu nginx package installs a default site automatically, which defines `server_name  _`. I emptied the sites-enabled directory and stopped getting duplicate errors (& can in fact no longer recreate the error I was seeing, bummer), but trying to load my server in a browser (port 80) redirected me to localhost. Changing `server_name` to my fqdn in the main server block only gives me 502 Bad Gateway. The only message in /var/log/nginx/error.log is 'signal process started'. In codalab-worksheets/codalab/logs/nginx-error.log, I get:

 ```
2017/10/16 17:12:26 [error] 29012#29012: *1 connect() failed (111:
Connection refused) while connecting to upstream, client:
$our_ip_address, server: $our_hostname, request: "GET / HTTP/1.0",
upstream: "http://[::1]:9000/", host: "$our_hostname"

2017/10/16 17:12:26 [warn] 29012#29012: *1 upstream server temporarily
disabled while connecting to upstream, client: $our_ip_address,
server: $our_hostname, request: "GET / HTTP/1.0", upstream:
"http://[::1]:9000/", host: "$our_hostname"
```

It's looking for something at :9000, which seems to be the upstream django server. I changed that from localhost:9000 to the fq version, but I still get Bad Gateway, just with our IP instead of 127.0.0.1. What is this trying to connect to? The website's at :2700, and the API is at :2900 (and at 127.0.0.1, not sure how to reconfigure that yet). Is there another service I should be starting?

(max, I'll try yours next, but I'm still confused on what localhost/127 entries I should be changing/not)

**Comment by krivard** [comment]
2. max's magic codalab.conf for nginx

What's the first block supposed to be titled?

**Comment by krivard** [comment]
I got it working! It required a bunch of fussing. Do you want a catalogue of changes here, or a PR?

**Comment by maxwang7** [comment]
@krivard Great! A PR would be great! My apologies for not responding earlier. Also, I updated my comment so that the first line is showing -- it was a Markdown problem. Were you able to use a domain name rather than localhost?

**Comment by maxwang7** [comment]
@krivard Following up on my previous message. Would love to see the PR!

**Comment by krivard** [comment]
Right on! The -worksheets one handles the config file; the -cli one is unrelated and adds support for authless SMTP (common in academic enviros).

I also wrote up the config mods for deploying to non-localhost; github doesn't support wiki PRs but you can manually pull that from here: https://github.com/krivard/codalab-worksheets-wiki

**Comment by maxwang7** [comment]
@krivard amazing, I'll check them (cli, worksheets, wiki) out, thank you!
