### ISSUE TITLE
Rerun bundle inserted at the wrong position sometimes

### ISSUE THREAD

**Issue by yuqijin** [codalab/codalab-worksheets#3593]
**Describe the bug**
Sometimes `edit and rerun`, the bundle gets added to the top of the worksheet instead of after the current bundle row, but it is stochastic

**Comment by jzwang43** [comment]
@epicfaace @percyliang I tried edit and rerun multiple times and couldn't reproduce the bug. Have you guys encountered this before and is there a specific scenario needed to trigger this? If not I think we can close this for now.

**Comment by percyliang** [comment]
This definitely happens (it happened during my demo) and is pretty
jarring...let me see if I can try to reproduce it.

**Comment by jzwang43** [comment]
I am not sure if I am reproducing it correctly.
![image](https://user-images.githubusercontent.com/29891066/144188805-f3e578ee-d806-4854-a9d9-51ad24db2fe5.png)

In this case, the selected run is the one in blue, so edit and rerun will insert after it. Rather than the one we are editing.

**Comment by pranavjain** [comment]
@pranavjain Add repro steps.

**Comment by pranavjain** [comment]
I have filed #3989 which might have the same root cause.

@jzwang43 Please look at that one.

**Comment by jzwang43** [comment]
close this since it's the same as #3989, working in #3989 instead.
