### ISSUE TITLE
problems with empty titles

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#36]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Tuesday Dec 08, 2015 at 09:19 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1489_

----

1) If we delete the title, then there is an error: "Must have worksheet uuid and command"

2) Separately, typing a space as the title gets rendered as `<none>`.

3) Finally, when we 'cl work' to a new worksheet that doesn't have a title `<none>` doesn't show up.

**Comment by codalab** [comment]
<a href="https://github.com/kashizui"><img src="https://avatars.githubusercontent.com/u/614837?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kashizui](https://github.com/kashizui)**
_Wednesday Dec 09, 2015 at 01:54 GMT_

----

notes for future:

1) This is because CLI current doesn't even support deleting title (frontend tries to issue the command `cl wedit -t` which returns an error)

2) not sure why this is happening yet

3) fixed in #1493

**Comment by klopyrev** [comment]
For 1) the code uses the somewhat generic WorksheetEditableField. It's used for the worksheet title and name. It's easy to support having empty title. However, making that change in the naive way would also allow for an empty name. I'm not really sure what function name serves and whether it being empty is a problem. Any thoughts?

**Comment by klopyrev** [comment]
Digging a bit more, there's validation logic for the name in the Worksheet.validate method which is called when a worksheet is edited. Thus, even if any empty value is allowed for the name in the place where the current error is being thrown, the empty value would cause an error in a later part of the logic. Thus, it's safe to remove that first check. I'll test to make sure that I understood the code correctly, and if I did I'll make the change.

**Comment by percyliang** [comment]
The name needs to be non-empty, but the title can be empty.

**Comment by klopyrev** [comment]
Part 1 is fixed.

**Comment by percyliang** [comment]
Not a problem anymore.
