### ISSUE TITLE
can users be prevented from uploading empty file?

### ISSUE THREAD

**Issue by ranjita-naik** [codalab/codalab-worksheets#360]
This is a low priority request. Accidentally, I tried to upload an empty file and it let me do so.  Please refer to the attachment for repro.  Can users be warned about this while uploading? 

![empty_file](https://user-images.githubusercontent.com/32549868/31530257-ccf3106c-affc-11e7-85f9-c4026cd652a6.png)

**Comment by maxwang7** [comment]
@ranjita-naik thank you for letting us know about this request. I just want some more context around this problem: what led you to upload an empty file (was it for a project)? Did you create an empty file on purpose?

**Comment by ranjita-naik** [comment]
Hi Max,
       As mentioned in the issue description, it was accidental.  I was dealing with multiple files and ended up uploading an empty file w/o realizing that it was empty.

If you think the ROI for this fix is not going to be significant then we can close the issue. Please feel free to do so.

thanks for your help,
Ranjita

**Comment by maxwang7** [comment]
@ranjita-naik thanks for explaining further. We will put this feature on the back burner for now, but we very much appreciate your feedback!
