### ISSUE TITLE
Progress bar does not work when uploading files

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3602]
When uploading files from the Web UI, the progress bar just shows up as grey and doesn't actually progress (though the upload still works):

![image](https://user-images.githubusercontent.com/1689183/120860574-e4695d80-c553-11eb-91d8-a86b24532284.png)

**Comment by epicfaace** [comment]
@jzwang43 would you be able to take a quick look to see what might be causing this? This seems to be a recent regression -- I wonder if it's happening due to your ajax refactoring changes earlier?

**Comment by jzwang43** [comment]
I was able to locate the bug, it looks like this bug has been there for a long time, not caused by the refactoring. I fixed the issue and will have a pull request up soon.

**Comment by epicfaace** [comment]
Oh great, thanks Jizhen!
