### ISSUE TITLE
Document batch worker managers

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3603]
We should document batch worker managers and include steps for how to set them up / what needs to be configured to do so. We could start with the k8s batch worker manager, since that's what we most recently added in.

**Comment by teetone** [comment]
I added documentation for AWS: https://codalab-worksheets.readthedocs.io/en/latest/Worker-Managers/

I will need to add documentation for GKE and Azure.

**Comment by pranavjain** [comment]
Will be picked up next week.

**Comment by pranavjain** [comment]
ETA: 03/03

**Comment by epicfaace** [comment]
@teetone per our conversation, let's do the following:
- Move all AWS batch worker manager setup to main codalab docs
- In deployment docs, keep the section about checking Azure batch worker manager, and then link to the main codalab docs.
