### ISSUE TITLE
Jupyter/IPython Notebook - run is failing with the error "Head and tail not supported for directory blobs"

### ISSUE THREAD

**Issue by ranjita-naik** [codalab/codalab-worksheets#361]
I was trying to get my CaptionBot application - https://github.com/ranjita-naik/Deep-Learning/blob/master/Applications/CaptionBot.ipynb ,  running in codalab-worksheets. Uploading .ipynb worked fine, however the run failed with the error "Head and tail not supported for directory blobs". 

So I decided to try and get simple.ipynb up and running by following the steps documented at - https://worksheets.codalab.org/worksheets/0x20ce2b583c7a4ddd9496b480c0bc1b79/

the following command failed with the same error. 
ipython nbconvert --to html --execute  simple.ipynb

Any idea what could be going wrong here?

thanks,
Ranjita

**Comment by maxwang7** [comment]
@ranjita-naik is this the full command that you were running? `run main.ipynb:0xd030e3776ce3429786501f5d832f6109 "ipython nbconvert --to html --execute --ExecutePreprocessor.timeout=1000000 main.ipynb" --request-docker-image ipython/scipystack`

If you could include a link to a bundle/worksheet, that would be helpful for debugging purposes.

**Comment by ranjita-naik** [comment]
@maxwang7  good news. Instead of uploading simple.ipynb explicitly, I tried ‘Add to my homeworksheet’ option from Jupyter/Ipython notebook documentation - https://worksheets.codalab.org/worksheets/0x20ce2b583c7a4ddd9496b480c0bc1b79/ and ran nbconvert. The run went through and successfully created main.html.  

I was able to run other jupyter notebooks also seamlessly. You can close the issue. thanks for your help.

**Comment by maxwang7** [comment]
@ranjita-naik great to hear! Yes, since only the creator of that worksheet can add to it, you'll need to run the commands on your own worksheet.
