### ISSUE TITLE
time_* fields may be inaccurate

### ISSUE THREAD

**Issue by adiprerepa** [codalab/codalab-worksheets#3628]
`time_<stage>` fields in the bundle details may be inaccurate.

Steps:
- run `time cl run date --wait`
- match the time returned to the sum of the `time_<stage>` stages.

**Comment by adiprerepa** [comment]
cc @codalab/worksheets

**Comment by adiprerepa** [comment]
this is interesting...

I tried to reproduce this issue locally, but was unable to. Look at the screenshot below:
![image](https://user-images.githubusercontent.com/43913660/122647919-7f794000-d0db-11eb-9735-9599d4a3d574.png)
Adding up `time_preparing`, `time_running`, `time_cleaning_up`, and `time_uploading_results` gives me an aggregate of **48.4** seconds. The time returned by the command seemed to match, giving me **52.201** seconds, and the difference is margin of error.

This must be an issue with our codalab deployment (I think on Friday we ran it on worksheets.codalab.org) -- not an issue with our actual code under regular conditions? Maybe excessive load causes this?

The measuring of the time_* fields seem to be accurate, however.

**Comment by adiprerepa** [comment]
aditya: run 50 times to try to repro

**Comment by adiprerepa** [comment]
Unable to reproduce: https://worksheets.codalab.org/worksheets/0x55b21b5832e241869106217c358f581e

We should try to repro on fridays meeting

**Comment by epicfaace** [comment]
Doesn't this seem wrong? (this is a bundle from your worksheet)
https://worksheets.codalab.org/bundles/0x5cea94617d8a49309ad3a7eabef20006

time_running is 10.2s but the command should have taken far longer.

--
Ashwin Ramaswami

**Comment by adiprerepa** [comment]
Why would `echo hi` take longer than 10 seconds?

I think if you look at the `time_started` and `last_updated`, subtract them, get the seconds, and sum the seconds in the `time_*` fields, you get similar values, no?

**Comment by epicfaace** [comment]
> Why would `echo hi` take longer than 10 seconds?

Isn't that precisely the problem? time_running is 10.2s.


> I think if you look at the `time_started` and `last_updated`, subtract them, get the seconds, and sum the seconds in the `time_*` fields, you get similar values, no?

I don't see how this fact affects the problem above.

**Comment by adiprerepa** [comment]
> time_running is 10.2s but the command should have taken far longer.

do you mean the command should take less than 10.2 seconds to complete?

I agree with you -- but we are not measuring the time it actually takes for the command to complete (this would be in the docker container I think). We are measuring the time it takes in and out of stages **in the worker**, and there must be some non-negligible latency somewhere.

**Comment by epicfaace** [comment]
> do you mean the command should take less than 10.2 seconds to complete?

Yeah, that's what I meant to say.

**Comment by adiprerepa** [comment]
I mean, I timed it manually, and the time it takes for the stage to change from running to the next stage is around that much time. Of course `echo hi` does not take that much time, but that is how much time it spent in the running stage.
