### ISSUE TITLE
'Remove bundle permanently' enabled for tutorial worksheets

### ISSUE THREAD

**Issue by ranjita-naik** [codalab/codalab-worksheets#363]
I was going through the documentation of jupyter/Ipython notebook at https://worksheets.codalab.org/worksheets/0x20ce2b583c7a4ddd9496b480c0bc1b79/  and I see that 'remove bundle permanently' option is enabled for some of the tutorial worksheets. Please note, I wasn't signed in. Either way, this needs to be disabled as nobody should be allowed to remove them. Now, I don't know if it's designed to throw 'not authorized' error when the 'Remove bundle permanently' is clicked. I didn't want to jeopardize anything , so didn't click remove.

![remove_bundle_permanently](https://user-images.githubusercontent.com/32549868/31853795-929233a6-b6ac-11e7-97b6-059cbe82cfee.png)

**Comment by maxwang7** [comment]
@ranjita-naik thank you for bringing this to our attention. This fix is in the PR referenced above.
