### ISSUE TITLE
Running bundles showing up in the wrong place, when adding a bundle when selecting the last row

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3632]
When adding a bundle when selecting the last row of a table, the running bundles show up in the wrong place. They should be added to the bottom of the table, but they sometimes instead are inserted earlier up in the table.

This happened in https://worksheets.codalab.org/worksheets/0x2a0a3904a3e04840823aa9c7dd44f7e1 but we should try to reproduce on other worksheets too.

**Comment by leilenah** [comment]
fixed
