### ISSUE TITLE
Some bundles don’t seem to have timing measurements

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3635]
Some bundles don't seem to have timing measurements (metadata fields beginning with `time_`). We should look into this.

**Comment by adiprerepa** [comment]
which bundles?

**Comment by epicfaace** [comment]
Not sure. We saw this in an earlier demo so part of this issue is to see if we can reproduce it. If not, we should close.

**Comment by adiprerepa** [comment]
cant repro, closing
