### ISSUE TITLE
Low latency for simple jobs

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3645]
Running ‘echo hello’ bundle should have a:
- Cold start (no workers up): <1min
- Warm start (a worker already up): <10s

Test this on both {worksheets.codalab.org,codalab.stanford.edu} x {slurm, GCP, Azure Batch, AWS Batch}

Command to run to check the time: time cl run "echo hello" --wait

**Comment by pranavjain** [comment]
@epicfaace Do you have the stats/time captured for the above? Did we see any issues when you filed this task?

**Comment by epicfaace** [comment]
This was a general goal we wanted to do starting in winter 2021. Percy would often do a demo and see it take a while for a bundle to start up.
