### ISSUE TITLE
trim peripheral whitespaces/newlines in command

### ISSUE THREAD

**Issue by adiprerepa** [codalab/codalab-worksheets#3654]
We should trim leading and trailing whitespaces and newlines in commands: https://worksheets-dev.codalab.org/bundles/0x06fa741593014487b5575ffce4ecfc77

**Comment by epicfaace** [comment]
Otherwise, a command with a trailing newline can fail as in the bundle linked above.

Also, that bundle seems to be deleted @adiprerepa ?
