### ISSUE TITLE
Remove extraneous log messages for the worker

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3668]
When I look at worker logs, it's cluttered with many extraneous log messages such as "Checking resource utilization for bundle". We should remove all these log messages and ensure that the only messages that are logged are things that tell us new information (for example, a change in state of the bundle or an error). This would make it far easier to look through the logs.

![image](https://user-images.githubusercontent.com/1689183/124399444-81511f00-dce9-11eb-96b2-014e8678efeb.png)

**Comment by HidyHan** [comment]
This particular redundant log has since been removed. We can close this issue.
