### ISSUE TITLE
Building default-cpu / default-gpu Docker images is broken

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3679]
Building default-cpu / default-gpu Docker images is broken. This is likely due to some change in upstream dependencies / GHA runners, potentially related to https://github.com/actions/runner/issues/932.

The default-cpu image build fails with the following error:

```
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [32.0 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1361 kB]
Get:18 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1040 kB]
Get:19 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [416 kB]
Get:20 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [2668 B]
Get:21 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [6315 B]
Reading package lists...
E: Failed to fetch https://dl.bintray.com/sbt/debian/InRelease  403  Forbidden [IP: 34.209.176.102 443]
E: The repository 'https://dl.bintray.com/sbt/debian  InRelease' is not signed.
The command '/bin/sh -c wget http://scala-lang.org/files/archive/scala-$SCALA_VERSION.deb &&     dpkg -i scala-$SCALA_VERSION.deb &&     echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list &&     apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823 &&     apt-get -y update &&     apt-get -y install sbt &&     apt-get clean &&     apt-get autoremove &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
[CodaLab] Building default-cpu image
```

Test PR: https://github.com/codalab/codalab-worksheets/pull/3677

**Comment by anilfcc** [comment]
hello @epicfaace , did you get a solution for this, please let me know

**Comment by epicfaace** [comment]
We're still working on this. Does this affect your own workflow?

**Comment by anilfcc** [comment]
Yes, it is a part of our build process, thanks for the reply

**Comment by epicfaace** [comment]
Bintray is no longer operational https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by epicfaace** [comment]
This comes from the scala installation steps:

https://github.com/codalab/codalab-worksheets/blob/epicfaace-patch-1/docker_config/dockerfiles/Dockerfile.default-cpu#L39-L51

@percyliang Would you be okay with removing support for scala in the default-cpu and default-gpu Dockerfiles? I don't know if it's worth it to debug this and find an alternative place from which to install scala (and I'm not very familiar with the scala ecosystem and how to do this), so it might be easier to just remove support for scala. Users who need to run scala jobs could just use a Scala-based Docker image.
