### ISSUE TITLE
Default cl to nlp:: rather than main:: for Stanford NLP cluster

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3685]
When running a `cl` command in the NLP cluster, a user would be prompted to login to worksheets.codalab.org (main) instead of codalab.stanford.edu (nlp) by default. We should make codalab.stanford.edu (nlp) the default.

**Comment by teetone** [comment]
The default address is set in the user's config.json: 

```
{
    "aliases": {
        "localhost": "http://localhost",
        "main": "https://worksheets.codalab.org",
        "nlp": "https://codalab.stanford.edu"
    },
    "cli": {
        "default_address": "https://worksheets.codalab.org"
    },
    ...
```

To make codalab.stanford.edu the default address, the user needs to run: 

`cl config cli/default_address https://codalab.stanford.edu`

The next time the user runs a `cl` command, the user would be prompted to login to codalab.stanford.edu instead. I updated the _CodaLab for Stanford NLP_ documentation with the command.

**Comment by teetone** [comment]
We can consider adding a new CLI command: `cl address`. When the user runs `cl address`, it prints the current address. The user can also can set a new default address by running `cl address <address>` or `cl address <alias>`. I'm not sure if this will be used often though.

**Comment by epicfaace** [comment]
> We can consider adding a new CLI command: `cl address`. When the user runs `cl address`, it prints the current address. The user can also can set a new default address by running `cl address <address>` or `cl address <alias>`. I'm not sure if this will be used often though.

Yeah, probably not worth it.

Perhaps it would be good to update the documentation in the CLI reference for `cl work` with a description of how to set the default address by running `cl config cli/default_address [address]`?

**Comment by percyliang** [comment]
Updating the Stanford documentation is good enough - thanks!
