### ISSUE TITLE
Fix search bar on deployment docs site

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3686]
The search bar on the deployment docs doesn't work. Probably has something to do with the encryption.

**Comment by Zoronium** [comment]
hello @epicfaace is it still open , 
and if it is can you pls tell me which file should I look for it.

**Comment by epicfaace** [comment]
Oh, this is from an internal private repository that only the codalab team can access, so please pick another issue to help with. Sorry about that!
