### ISSUE TITLE
Computational Resource Limitations for Codalab Worksheet?

### ISSUE THREAD

**Issue by xiaoyanh** [codalab/codalab-worksheets#369]
Hi,

What are the computational resource limitations for running commands in Codalab Worksheet? (Max. execution time, Max. CPU's, etc.)

Are these listed somewhere. I looked around and could not find anything.

Thank you!

**Comment by fabeschan** [comment]
Each user has: (can be changed with permission)
- 10g of bundle storage
- 7 days of compute time (based on job/run-bundle)

There are no RAM, CPU or GPU limits set on a per user basis, so what's left are the limits of the provisioned machines.
