### ISSUE TITLE
worker_offline error on run bundles

### ISSUE THREAD

**Issue by lynn-he** [codalab/codalab-worksheets#3696]
**Describe the bug**
worker_offline error on run bundles

**Codalab Information**
- *Your username*: DeepLearning.AI
- *UUID of worksheet where problem occurred*: 0x37a5b4d4ec494cdeaedc73850336b8c1
- *UUID of problem bundle (please don't delete)*: 0x2bcfcf5962b94a0881d153b6596ed7df
- *Error message received from Codalab (if applicable)*: State
worker_offline(Failed to download dependency simple_data_aug_submission: Dependency download failed: Unable to get bundle contents from bundle service: Not Found - [Errno 2] No such file or directory: '/home/azureuser/codalab-worksheets/var/codalab/home/partitions/codalab3/bundles' )
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**
The run bundle to finish running successfully. 

**Screenshots**
<img width="1327" alt="Screen Shot 2021-07-07 at 5 24 51 PM" src="https://user-images.githubusercontent.com/51978114/124840813-09812f80-df49-11eb-95ed-7783b675856a.png">

**Additional context**

**Comment by epicfaace** [comment]
Related bundle: https://worksheets.codalab.org/bundles/0x2bcfcf5962b94a0881d153b6596ed7df

**Comment by epicfaace** [comment]
I mimicked this bundle in https://worksheets.codalab.org/bundles/0x6d1f7c5e3de54671a9a597420ce4d26b. If that bundle succeeds, then we can consider this bug as part of the transient disk issues and mark it as fixed

**Comment by epicfaace** [comment]
This bug should be fixed now! Feel free to reopen if you see it again.
