### ISSUE TITLE
run bundle stuck in finalizing 

### ISSUE THREAD

**Issue by lynn-he** [codalab/codalab-worksheets#3697]
**Describe the bug**
a run bundle is stuck in the state finalizing

**Codalab Information**
- *Your username*: DeepLearning.AI
- *UUID of worksheet where problem occurred*: 0x37a5b4d4ec494cdeaedc73850336b8c1
- *UUID of problem bundle (please don't delete)*: 0x9cefe6087b0e4198b386ece04c1c4e39
- *Error message received from Codalab (if applicable)*: State
finalizing(Error while uploading: Unable to update bundle contents in bundle service: Bad Request - Error while parsing chunked transfer body.)
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**
The run bundle to finish running and turn to a ready state.

**Screenshots**
<img width="1326" alt="Screen Shot 2021-07-07 at 5 31 22 PM" src="https://user-images.githubusercontent.com/51978114/124841091-b065cb80-df49-11eb-8f61-da77088c5aa6.png">

**Additional context**

**Comment by lynn-he** [comment]
This error has occurred for multiple bundles

**Comment by epicfaace** [comment]
I mimicked this bundle in https://worksheets.codalab.org/bundles/0x8f1014b5a2cb48339fd7a328807e844d. If that bundle succeeds, then we can consider this bug as part of the transient disk issues and mark it as fixed

**Comment by epicfaace** [comment]
This bug should be fixed now! Feel free to reopen if you see it again.
