### ISSUE TITLE
[USER ISSUE] Can't sign up for an account from China

### ISSUE THREAD

**Issue by SergeLiu** [codalab/codalab-worksheets#3698]
**Describe the bug**
when I sign up on https://worksheets.codalab.org/account/signup，the “sign up>>” button in the bottom has no response so I can't regist.

**To Reproduce**
Steps to reproduce the behavior :
1. Go to 'https://worksheets.codalab.org/account/signup'
2. Fill in all the fields and click on 'sign up' and it doesn't work！

**Screenshots**
![image](https://user-images.githubusercontent.com/40231580/124945459-bdb1b180-e040-11eb-8faa-2b1fba987557.png)

**Comment by epicfaace** [comment]
I can reproduce this.

**Comment by epicfaace** [comment]
@SergeLiu for a workaround for now, please first ensure you are logged out before signing up:

![image](https://user-images.githubusercontent.com/1689183/124946460-0a63a100-dfdd-11eb-89f3-80933a623a1e.png)

Once you do this, it should work.

**Comment by SergeLiu** [comment]
> @SergeLiu for a workaround for now, please first ensure you are logged out before signing up:
> 
> ![image](https://user-images.githubusercontent.com/1689183/124946460-0a63a100-dfdd-11eb-89f3-80933a623a1e.png)
> 
> Once you do this, it should work.

thank you for reply but it still exist because I am not in logged in status.
I dont have an account before.
![image](https://user-images.githubusercontent.com/40231580/124948886-af18c980-e043-11eb-89f1-1e2bb912333c.png)

@epicfaace

**Comment by epicfaace** [comment]
What browser are you using? You should see a CAPTCHA:

![image](https://user-images.githubusercontent.com/1689183/124959043-ceced400-dfe8-11eb-90a5-83cb2cf281b4.png)

Can you try using Google Chrome? Also, in what country are you currently located?

**Comment by SergeLiu** [comment]
@epicfaace I am using Google Chrome and it still can't work. I am located in China. No CAPTCHA is displayed

**Comment by SergeLiu** [comment]
@epicfaace I use Chrome，no CAPTCHA displayed. I am located in China

**Comment by yifanmai** [comment]
There is a [flag in recaptcha options](https://www.npmjs.com/package/react-google-recaptcha#global-properties-used-by-recaptcha) that would load it from a China-friendly URL. I can try making the change and seeing if it works.
