### ISSUE TITLE
focus on 'Upload Bundle' for too long

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#37]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Tuesday Dec 08, 2015 at 09:20 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1490_

----

After a bundle is uploaded, the focus should be taken off 'Upload Bundle'.  Otherwise, it gets accidentally triggered when the user presses enter in the action bar.

**Comment by percyliang** [comment]
Already fixed.
