### ISSUE TITLE
Cannot use / in table schema postprocessing regex

### ISSUE THREAD

**Issue by ppasupat** [codalab/codalab-worksheets#37]
In the schema syntax

```
% add <key-name> <genpath> [<post-processor>]
```

One of the post-processor is regular expression substitution `s/<old>/<new>`.
The problem is that `<old>` will not accept `/`, even when it is escaped as `\/` or `[/]`
I had to use `\x2f`, which is a hacky workaround.

**Comment by percyliang** [comment]
Fixed by #51
