### ISSUE TITLE
Competition daemon fails when bundle does not have public read permissions

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3705]
Reported by @lynn-he

Just ran into this issue with the new competition daemon:

```
[INFO] 2021-07-09 17:21:16,459: Mimicking submission for naveenkb
[INFO] 2021-07-09 17:21:17,061: Submission 0xbeabde273acf442eb66a0d8f77cb4eb1 by naveenkb is missing expected dependencies.
[INFO] 2021-07-09 17:21:17,061: Aborting submission for naveenkb
Traceback (most recent call last):
  File "competitiond.py", line 768, in run
    self.run_once()
  File "competitiond.py", line 761, in run_once
    self.generate_leaderboard(num_total_submissions, num_period_submissions)
  File "competitiond.py", line 692, in generate_leaderboard
    or submit_bundle['metadata']['description'],  # Allow description override
KeyError: 'description'
```

would expect that it shouldn't quit the daemon

_Originally posted by @lynn-he in https://github.com/codalab/codalab-worksheets/issues/3700#issuecomment-877506123_

**Comment by epicfaace** [comment]
Relevant LOC:

https://github.com/codalab/codalab-worksheets/blob/master/scripts/competitiond.py#L692

https://github.com/codalab/codalab-worksheets/blob/master/scripts/competitiond.py#L642

https://github.com/codalab/codalab-worksheets/blob/master/scripts/competitiond.py#L608-L615

**Comment by epicfaace** [comment]
@teetone do you think you'd be able to take a look at this?

**Comment by epicfaace** [comment]
@lynn-he do you have any additional logs from that issue? I'm wondering if it's printing the bundle uuid that is causing the issue below the stack trace.

**Comment by lynn-he** [comment]
@epicfaace there is nothing below the stack trace, all I have is the uuid of the submission it's failing on
<img width="875" alt="Screen Shot 2021-07-13 at 12 11 54 PM" src="https://user-images.githubusercontent.com/51978114/125503722-766cf143-df4b-4bc3-8ee2-c370c03d09c1.png">

**Comment by lynn-he** [comment]
0xbedf2704f0054bc091c05c86133c94e8

**Comment by epicfaace** [comment]
Permissions

https://worksheets.codalab.org/bundles/0xbedf2704f0054bc091c05c86133c94e8

![image](https://user-images.githubusercontent.com/1689183/125529362-c00b5f02-ed99-42ac-abd2-fe2801641e91.png)

**Comment by lynn-he** [comment]
0x5198856ce1204a5d8abf35bbafe8eb76

**Comment by epicfaace** [comment]
Failed bundle which properly showed an error message: https://worksheets.codalab.org/bundles/0x2e66e01758da4509857a1ff5e49d9d4f

**Comment by epicfaace** [comment]
Work on a better way to debug / test competitions
