### ISSUE TITLE
Bundle permissions change requests

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3714]

**Comment by lynn-he** [comment]
@epicfaace 0xf5ae0c1b66af418595554b78879c3f47

**Comment by epicfaace** [comment]
0xf5ae0c1b66af418595554b78879c3f47 is fixed now

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
@epicfaace 0x262c49d4d7b4437b9f9c2687eaef7374

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
@epicfaace 0xe9ba0c41ab334220abfa8eb5f2e47ac9

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
thanks @epicfaace , here's another 0xfd7cff80ded84e22976c2c30f19e9dd7

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
@epicfaace 0xdcf93c9344d74b0a9f4751db78d22fde

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
@epicfaace 0x38c0dadc8fb24833b3757e883ffe1a6b

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
@epicfaace 0x93586091c0c44ff4959aebf8516de13b

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
thanks @epicfaace 0x335f047a85d1411c8078456d6e5a2989

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
@epicfaace 0xaee2bcf009e2479db409f55e94149c64

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
@epicfaace 0x9e990d78e8134ec0ab1fe21e721a98d4

**Comment by epicfaace** [comment]
The bundle 0x9e990d78e8134ec0ab1fe21e721a98d4 does not exist -- maybe it
was deleted?

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
Oops sorry got that error from running the cl-competitiond instead of the local version.

**Comment by lynn-he** [comment]
@epicfaace 0xaee2bcf009e2479db409f55e94149c64

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
@epicfaace 0xe7be6ef33fe04ae6ad90f9dd32516b14

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
@epicfaace 0x0eba3e3b94be47af9ecf1aa1eedf8bae

**Comment by lynn-he** [comment]
hey @epicfaace , gentle ping on the above bundle. Thanks!

**Comment by epicfaace** [comment]
Done. Thanks for the ping!

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
@epicfaace thanks! here's another: 0x4d0ef433f7dd4c999d6f682e2f3f2853

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
@epicfaace 0xdcf93c9344d74b0a9f4751db78d22fde

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
@epicfaace 0xaee2bcf009e2479db409f55e94149c64

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
@epicfaace 0xe7be6ef33fe04ae6ad90f9dd32516b14

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
@epicfaace thanks, 0xbe0807fe56ce44909ced5462be97fc8a

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
@epicfaace 0x5342687975ad496b8692458f6adc9929

**Comment by epicfaace** [comment]
Done

--
Ashwin Ramaswami

**Comment by lynn-he** [comment]
Thanks, that should be all for today!

**Comment by lynn-he** [comment]
@epicfaace 0x92c8355f502f46e99086bab6cfad1124

**Comment by lynn-he** [comment]
Hey @epicfaace , gentle ping on this one ^

**Comment by adiprerepa** [comment]
done

**Comment by lynn-he** [comment]
@adiprerepa 0x92262a437947478a9d8602537fa58955

**Comment by adiprerepa** [comment]
done
