### ISSUE TITLE
Support model checkpoints

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3716]
Save and restore checkpoints if a run fails / worker gets offline.

Two options:
1. Bundles should be able to upload things in-progress to the bundle store.
2. Once https://github.com/codalab/codalab-worksheets/issues/3710 is implemented, store the `runs` in a shared drive such as a PersistentVolume, and allow other workers to resume from directories within `runs`.

**Comment by epicfaace** [comment]
Design doc: https://docs.google.com/document/d/1ifcuXLPldSWJehZgl9RTmPogllbyUJ_vRIOiW2BF1i0/edit#

**Comment by nelson-liu** [comment]
Might also be interesting to look into docker checkpointing for resuming bundles

**Comment by epicfaace** [comment]
Ah, that's a good point. I was initially thinking we could just use a
network drive for the bundle's working directory, then resume from that
working directory if a worker were preempted -- but this approach wouldn't
work if our command was also installing pip dependencies or saving things
in, say, a "/tmp" directory. docker checkpointing might help for that.

Do you think the above scenario is common when training models, though? If
not, we could probably just go with the "network drive for the bundle's
working directory" solution which might be simpler / more elegant than
docker checkpointing (the latter would have to be done periodically and
slow the bundle execution down).

--
Ashwin Ramaswami

**Comment by epicfaace** [comment]
Doc will be ready by Oct 27
