### ISSUE TITLE
[USER ISSUE] The submission is not presented in the leaderboard

### ISSUE THREAD

**Issue by Gloria0702** [codalab/codalab-worksheets#3718]
**Describe the bug**
I have strictly followed the instruction but my submission is still not presented on the leaderboard. 
I have generated the results, tagged that evaluation output, and submitted the google form.

**Codalab Information**
- *Your username*:gloria0702
- *UUID of worksheet where problem occurred*:
0x0b07a1c4066842f99806049ca1273e2d
- *UUID of problem bundle (please don't delete)*:0x0b07a1
- *Error message received from Codalab (if applicable)*:-
 - *OS (if on CLI)*:-
 - *Codalab CLI Version (if on CLI)*: -
 - *Browser (if on Web)*;Chrome

**To Reproduce**
Steps to reproduce the behavior.
1. Training and testing completed. 
2. Prediction file generated with tags.
3. Public permission set as read.
4. Google form submitted.

**Expected behavior**
Set the submission on the leaderboard.

**Comment by epicfaace** [comment]
Which competition is this for?

**Comment by Gloria0702** [comment]
Data-Centric AI Competition, https://https-deeplearning-ai.github.io/data-centric-comp/?utm_source=thebatch&utm_medium=newsletter&utm_campaign=dc-ai-competition&utm_content=dl-ai

**Comment by epicfaace** [comment]
@lynn-he should be able to help with that.

**Comment by lynn-he** [comment]
@Gloria0702 please message me on Discourse with the link to your submission bundle for help debugging.

**Comment by Gloria0702** [comment]
Hi @lynn-he, I cannot find you through the Discourse. 
The link to the submission bundle: 
https://worksheets.codalab.org/bundles/0x0b07a1c4066842f99806049ca1273e2d
Thanks for your kind assistance！

**Comment by lynn-he** [comment]
@Gloria0702 my username on Discourse is `@lynn` . Going forward, please message me there and see this thread https://community.deeplearning.ai/t/help-i-dont-see-my-submission-on-the-leaderboard/21292/4. Your submission was made on Tuesday, after we updated the leaderboard already. You should see your submission next time we update.
