### ISSUE TITLE
competition daemon does not run continuously on its own

### ISSUE THREAD

**Issue by lynn-he** [codalab/codalab-worksheets#3722]
**Describe the bug**
Competition daemon does not run continuously on its own. If you just leave it running, no new submissions submitted after I run the command are picked up. I have to rerun it constantly to mimic new submissions. 

**To Reproduce**
Steps to reproduce the behavior :
1. Run this command `python competitiond.py -d competition-config.yml leaderboard.json`
2. Make a submission 5-10 minutes after 

**Expected behavior**
that if i leave the terminal running, the script will continue taking in bundles with the competition tag

**Comment by epicfaace** [comment]
@epicfaace todo -- send Tony competition config

**Comment by epicfaace** [comment]
@lynn-he looking at the code for competitiond.py, it seems like you may need to wait for at least 60 seconds before new bundles are picked up. Did you leave the terminal running for over 60 seconds since the last bundle was processed -- can you confirm that?

**Comment by lynn-he** [comment]
@epicfaace yes, I've been leaving the terminal open for at least that long. I think it actually works fine now with the new script, since it just prints out the errors but doesn't interrupt the process. With the last script, it would just print out one error and then would not continue to pick up submissions after 60 seconds. 
<img width="553" alt="Screen Shot 2021-08-11 at 11 48 53 AM" src="https://user-images.githubusercontent.com/51978114/129070058-1c4386da-db80-46c7-859e-dd94fe86aef8.png">

**Comment by epicfaace** [comment]
Okay, that's great!
