### ISSUE TITLE
competitiond script is not picking up on all submissions with the right tag

### ISSUE THREAD

**Issue by lynn-he** [codalab/codalab-worksheets#3727]
**Describe the bug**
Over the past few days, the competition script competitiond.py has not picked up on submissions that have the proper tags. These competitors have submitted successfully in the past using the same formatting. Sometimes remaking the submission bundle helps, other times it does not. 

**Expected behavior**
Script to pick up on all submission tagged for the competition

**Comment by epicfaace** [comment]
Can you send a link to these submission bundles? I'm wondering if it's because of the limit that users can't submit too many submissions in a certain time period.

**Comment by lynn-he** [comment]
Sent to your email

**Comment by lynn-he** [comment]
@epicfaace this was also resolved with a fix to the competition script that allowed it to continuously run
