### ISSUE TITLE
Workers not properly stopping and stuck in cleanup

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3729]
I noticed this after deploying to dev. This might be due to https://github.com/codalab/codalab-worksheets/pull/3569. (cc @teetone @adiprerepa )

Logs from Azure batch for dev-cpu:

![image](https://user-images.githubusercontent.com/1689183/127553604-f6cf01d3-bc88-4c4c-86a2-9120cd476bcf.png)

It appears to be hanging on the "self._downloading.stop()" line, as it never prints "Stopped image manager". Thus, the worker just keeps staying idle, but in a state where it's stuck in cleanup and can't run other jobs.

For relevant code, see: https://github.com/codalab/codalab-worksheets/blob/fcdd6353c05289280083a85c7b18f9be64a62b87/codalab/worker/image_manager.py#L73-L80

**Comment by adiprerepa** [comment]
this is fixed now, right?

**Comment by epicfaace** [comment]
I'm waiting for stress tests to pass and for rc1.0.3 to be merged into
master before closing this issue.

--
Ashwin Ramaswami

**Comment by epicfaace** [comment]
Stress tests passed
