### ISSUE TITLE
Can't detach first item (bundle) in a worksheet

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#373]
Example worksheet (try to right click and detach): https://worksheets.codalab.org/worksheets/0x2644fd6a840e4c8790307bf32ef9161a/

It doesn't matter the permissions of the bundle, only that it's the first item in a worksheet (or maybe the first in a table?).

It is possible to remove non-first items.

Should probably spend some more time determining the exact failure cases.

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1059
