### ISSUE TITLE
Disable mathjax for bundle details page

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3731]
Like https://github.com/codalab/codalab-worksheets/issues/1108, but for bundle details page.

For example, 
![image](https://user-images.githubusercontent.com/1689183/127586183-c0cf9cab-64bd-48ad-a2a4-5ce953841242.png)

**Comment by pranavjain** [comment]
This was given as a starter task. Unassinging myself from this as it is also a P3.

**Comment by percyliang** [comment]
Doesn't seem like an issue anymore.
