### ISSUE TITLE
Run bundles failing on NotADirectoryError: [Errno 20] Not a directory: 

### ISSUE THREAD

**Issue by lynn-he** [codalab/codalab-worksheets#3739]
**Describe the bug**
Run bundles on zip files formatted as such: 

folder.zip
...folder
......train
......val

fail on NotADirectoryError: [Errno 20] Not a directory: 'folder/folder/train'

**Codalab Information**
Happening across many users. 

**To Reproduce**
Follow these steps: https://worksheets.codalab.org/worksheets/0x7a8721f11e61436e93ac8f76da83f0e6
Randomly fails on step 3. 

**Expected behavior**
This is an example of a successful submission, with a run bundle that succeeded. https://worksheets.codalab.org/worksheets/0x48ac66ba7d99418d9a2560082e800bcb

**Comment by epicfaace** [comment]
@lynn-he can you please provide a link to a bundle that failed with this error?

**Comment by epicfaace** [comment]
I'm going to close this because I assume it's no longer relevant / happening now. Feel free to reopen though.

**Comment by lynn-he** [comment]
Sorry for being late on this, that works for us!
