### ISSUE TITLE
run bundles fail on a file not found error

### ISSUE THREAD

**Issue by ss20212** [codalab/codalab-worksheets#3743]
**Describe the bug**
When creating a CodaLab run bundle, the bundle will throw an error where it cannot find a file, when I have the file. 

**Codalab Information**
- *Your username*: DeepLearning.AI
- *UUID of worksheet where problem occurred*:
- *UUID of problem bundle (please don't delete)*:0xbddf0fe31d2d4489b1448d1281fbf8c0
- *Error message received from Codalab (if applicable)*:
- Traceback (most recent call last):

  File "/0xbddf0fe31d2d4489b1448d1281fbf8c0/train.py", line 15, in <module>
    train = tf.keras.preprocessing.image_dataset_from_directory(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/keras/preprocessing/image_dataset.py", line 175, in image_dataset_from_directory
    image_paths, labels, class_names = dataset_utils.index_directory(
  File "/opt/conda/lib/python3.9/site-packages/tensorflow/python/keras/preprocessing/dataset_utils.py", line 65, in index_directory
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [Errno 2] No such file or directory: 'original2/original2/train'

 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*; firefox

**To Reproduce**
Steps to reproduce the behavior :
try following the steps for submission outlined in this guide: https://worksheets.codalab.org/worksheets/0x7a8721f11e61436e93ac8f76da83f0e6

**Expected behavior**
The run bundle to fail

**Additional context**
Link:

https://worksheets.codalab.org/worksheets/0x8ee6a8180506472ca7a3f3cfcc853d51#

**Comment by epicfaace** [comment]
The failed bundle you refer to is at https://worksheets.codalab.org/bundles/0xbddf0fe31d2d4489b1448d1281fbf8c0. To fix this, try running the bundle with the command `python train.py original2/original2 label_book` instead. It looks like the bundle https://worksheets.codalab.org/bundles/0xa04a364775b648bb8af6aac1a53ae37d has its contents in the path `original2/original2`.

cc @lynn-he

**Comment by lynn-he** [comment]
@epicfaace is correct, the file structure of your bundle should be

original2.zip
...original2
......train
......val

Please see this worksheet for an example of a properly structured submission zip file: https://worksheets.codalab.org/worksheets/0x48ac66ba7d99418d9a2560082e800bcb
