### ISSUE TITLE
[query] Is the CLI supported on windows?

### ISSUE THREAD

**Issue by ranjita-naik** [codalab/codalab-worksheets#375]
I was trying to setup the CLI on a windows m/c and I see no explicit instructions for windows in the documentation - https://github.com/codalab/codalab-worksheets/wiki/CLI-Basics . So, thought would double check before proceeding. Is the CLI supported on windows?

**Comment by fabeschan** [comment]
Hi @ranjita-naik, I don't think the CLI was created with windows in mind, but you are free to try to make it work.
