### ISSUE TITLE
runs taking much longer in CodaLab than out of CodaLab

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#376]
This could be a docker issue?

**Comment by thashim** [comment]
[this worksheet](https://codalab.stanford.edu/bundles/0x5860a341063e4968bd919779f6ab29da/) should complete in ~ 10 hours, but is currently at 22.75 and still going. (I have timings from past runs on jagupard 6, which should be the same config as jagupard 5 which this is running on.

It is at 100% cpu, and is using a free GPU slot. There's some light usage other than me, but the rest of the usage seems low (though they could still be the issue).

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1045
