### ISSUE TITLE
CLI Basics Macro Instruction

### ISSUE THREAD

**Issue by tuzhucheng** [codalab/codalab-worksheets#377]
Hi,

On the [CLI Basics](https://github.com/codalab/codalab-worksheets/wiki/CLI-Basics) wiki page, it says add the following line to `.bashrc` to include some handy macros.

```
. <path to codalab>/rc
```

However, there doesn't seem to be a `rc` file inside my codalab installation?

```
-bash: /usr/local/lib/python2.7/dist-packages/codalab/rc: No such file or directory
```

**Comment by maxwang7** [comment]
@tuzhucheng Thank you for your issue, we are actively working to fix this problem and I'll let you know when we have the fix out. It's not an essential component of using CodaLab, so you can continue with the rest of the instructions and upgrade once we have a fix out.

**Comment by tuzhucheng** [comment]
Thanks for the quick response! The video intro and tutorial look awesome, I'm just about to start using Codalab for my research.

**Comment by bkgoksel** [comment]
Tutorial no longer says that as that file is no longer provided.
