### ISSUE TITLE
[USER ISSUE] CLI installation fails when using Python 3.9

### ISSUE THREAD

**Issue by aniketsharma00411** [codalab/codalab-worksheets#3775]
**Describe the bug**
I use Python 3.9 and I was not able to install it using pip as instructed in the [Quickstart guide](https://codalab-worksheets.readthedocs.io/en/latest/examples/quickstart/). codalab has apache-beam[azure]==2.27.0 as a requirement and apache-beam[azure]==2.27.0 has pyarrow<3.0.0,>=0.15.1 as a requirement and pyarrow 2.0.0 (the only version below 3.0.0) does not support Python 3.9.

I was able to install Codalab CLI after removing the version requirement from apache-beam[azure] i.e. changing `apache-beam[azure]==2.27.0` in requirements.txt to `apache-beam[azure]`.

**Codalab Information**
- *Your username*: aniketsharma00411
- *UUID of worksheet where problem occurred*: N/A
- *UUID of problem bundle (please don't delete)*: N/A
- *Error message received from Codalab (if applicable)*: N/A
 - *OS (if on CLI)*: Garuda Linux
 - *Codalab CLI Version (if on CLI)*: 1.1.1
 - *Browser (if on Web)*; N/A

**To Reproduce**
Steps to reproduce the behavior :
1. Update Python version to Python 3.9
2. Install Codalab CLI using `pip install codalab -U --user`

**Expected behavior**
CLI should have been installed.

**Screenshots**

**Additional context**

**Comment by epicfaace** [comment]
I think we can only fix this once the latest version of Apache Beam supports Python 3.9.

**Comment by aniketsharma00411** [comment]
It does. After installing the latest version of Apache Beam I am able to use the CLI properly. It gives a warning that the version is not tested properly though.

**Comment by epicfaace** [comment]
I see. Would you be willing to make a PR that upgrades to the latest
version of Beam so that this is fixed?

**Comment by aniketsharma00411** [comment]
Sure
