### ISSUE TITLE
bypass codalab server for Azure blob storage uploads

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3779]
Part of this megaissue: https://github.com/codalab/codalab-worksheets/issues/3799
Design doc: https://docs.google.com/document/d/1TOsO4gnxUm1XMmlGUb7BJ4Z6y_olFbv9APbx0-IEy6M/edit#

---

We should bypass the codalab server when doing blob storage uploads. First, the CLI should call `POST /bundles/{bundle_uuid}/locations/` in order to get a SAS token. Then it should use the SAS token to upload the .tar.gz and the index file directly to Blob Storage. Finally, it should tell the server that it's done (perhaps with another endpoint)?

**Comment by pranavjain** [comment]
@epicfaace Is this same as #3963 ?

**Comment by epicfaace** [comment]
No -- https://github.com/codalab/codalab-worksheets/issues/3963 is for a specific issue with blob storage downloads.

**Comment by epicfaace** [comment]
Design doc: https://docs.google.com/document/d/1l4kOqi9irBjOApmn4E6vlzsjAXDJbetIyVw8gMRHrpU/edit#

The client can request POST /bundles/{bundleid}/locations to create a bundle location called “blob” and get SAS tokens for uploading the archive file and archive index file on Blob Storage. It will then create these two files and upload them directly to Blob Storage. Finally, it will call POST /bundles/{bundleid}/locations/blob to notify the server that the bundle has been fully uploaded.

PUT /bundles/{bundleid}/contents/blob will maintain its existing implementation that streams through the server for backwards compatibility reasons (or if someone doesn’t want to put a bundle on Blob Storage).

**Comment by pranavjain** [comment]
@wwwjn needs to talk with @epicfaace to resolve azure upload issues.

**Comment by wwwjn** [comment]
update: Finish the upload process. Working on error handling and testing. Details: https://docs.google.com/document/d/1qFT6OWSUW5-2ZfnkK_q6P-Q-9sVe_fyBLX3UfEIWRiY/edit?pli=1#
