### ISSUE TITLE
URL has redundant components when you navigate through folder 

### ISSUE THREAD

**Issue by cpchen** [codalab/codalab-worksheets#378]
In the worksheet view, if you open a folder with a lot of data, it takes a while to load. 

You can click on that folder name many times before it finishes loading and when it finally opens, the folder name is prepended many times to the file URL, making the files all point to weird URLs.

**Comment by cpchen** [comment]
v0.2.18

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1057
