### ISSUE TITLE
[USER ISSUE] ModuleNotFoundError: No module named 'pwd'

### ISSUE THREAD

**Issue by vchaudhri** [codalab/codalab-worksheets#3798]
**Describe the bug**

After successfully installing the codalab command line interface under Windows 10, when I run
cl work
I get the error: 
ModuleNotFoundError: No module named 'pwd'
(I am using python 3.7.2)

This seems like some trivial configuration issue. Could you help figure out what this is about?

**Comment by epicfaace** [comment]
The CodaLab CLI doesn't support Windows -- I believe you need to use Mac / Linux.
