### ISSUE TITLE
no usage is printed out

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#38]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Tuesday Dec 08, 2015 at 09:22 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1491_

----

In the action bar, if we type something like `wperm`, only 'too few arguments' is printed out, whereas in the CLI, we get: 'usage: cl wperm [-h] worksheet_spec group_spec permission_spec', which is the desired behavior.

**Comment by kashizui** [comment]
Fixed by codalab/codalab-cli#319
