### ISSUE TITLE
Allow bundles to have more than one BundleLocation

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3804]
Part of this megaissue: https://github.com/codalab/codalab-worksheets/issues/3799
Design doc: https://docs.google.com/document/d/1TOsO4gnxUm1XMmlGUb7BJ4Z6y_olFbv9APbx0-IEy6M/edit#

---

Allow bundles to have more than one BundleLocation. We might not need to change much code here, except for that we probably need to add some logic that creates an order of precedence: blob is preferred, and then disk. We should also add tests to ensure that bundles can have more than one BundleLocation and that this order of precedence is respected.

**Comment by pranavjain** [comment]
Done and merged as part of another PR. Closing.
