### ISSUE TITLE
Migrate all bundles from disk storage to blob storage

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3805]
Part of this megaissue: https://github.com/codalab/codalab-worksheets/issues/3799
Design doc: https://docs.google.com/document/d/1TOsO4gnxUm1XMmlGUb7BJ4Z6y_olFbv9APbx0-IEy6M/edit#

---

Migrate all bundles from disk storage to blob storage -- start with dev, then do this with prod. We can do this by creating a simple helper script that calls the `cl replicate` command.

**Comment by wwwjn** [comment]
close because of #4380
