### ISSUE TITLE
[USER ISSUE] bundle staged for days

### ISSUE THREAD

**Issue by hhexiy** [codalab/codalab-worksheets#3824]
**Describe the bug**
This bundle (https://worksheets.codalab.org/bundles/0x29a6edfa86a449cfa88329d5b3758ff2) has been staged for several days. Is there a way to know more details?
**Codalab Information**
- *Your username*: hhe
- *UUID of worksheet where problem occurred*: 0x1976df1c790b48c79eb8519c97d130dc
- *UUID of problem bundle (please don't delete)*: 0x29a6edfa86a449cfa88329d5b3758ff2
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by epicfaace** [comment]
How was this fixed? @hhexiy

**Comment by hhexiy** [comment]
The bundle is completed now, so I suppose it might just be a busy period.
