### ISSUE TITLE
instruction not working

### ISSUE THREAD

**Issue by sidaw** [codalab/codalab-worksheets#383]
The instruction for CLI is not working for me. In step 3 of 

https://github.com/codalab/codalab-worksheets/wiki/CLI-Basics#installation

`pip show codalab` does not return a directory that contains a `rc` file. It outputs

```
Name: codalab
Version: 0.2.18
Summary: CLI for CodaLab, a platform for reproducible computation
Home-page: https://github.com/codalab/codalab-cli
Author: CodaLab
Author-email: codalab.worksheets@gmail.com
License: Apache License 2.0
Location: /home/username/.local/lib/python2.7/site-packages
Requires: watchdog, six, psutil, SQLAlchemy, setuptools, argcomplete, PyYAML, fusepy
```

There are a few codalab related packages in there, but nothing with a clear rc. I understand it can be found `https://github.com/codalab/codalab-cli` but not clear how to get this working.

The old manual installation still seem to work, so I'm fine for now.

**Comment by percyliang** [comment]
Removed from step from the wiki for now to avoid confusion.

**Comment by sidaw** [comment]
`cl work` does not work using the setup as instructed

**Comment by percyliang** [comment]
What's the error?

**Comment by sidaw** [comment]
It's just that pip did not automatically set up the path, so `cl` is not
found.
