### ISSUE TITLE
Go through Stanford NLP documentation for a first time

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3830]
- Go through [this](https://docs.google.com/document/d/168v0WnvhUjYvUFfv5xmw4WbYwaFG-2VqBN9mzT3odAY/edit) documentation
- Talk with users of Codalab (Nelson, etc.)

**Comment by epicfaace** [comment]
- File issues from Nelson's feedback

**Comment by pranavjain** [comment]
Will pick this one again once #3873 is done.
Moving to p2.

**Comment by pranavjain** [comment]
We went through this during Percy's demo and have taken notes under the 12/08 weekly meeting section.

Do we still need to keep this one and #3873 open? @epicfaace @percyliang
