### ISSUE TITLE
Show more information about the states 

### ISSUE THREAD

**Issue by jzwang43** [codalab/codalab-worksheets#3837]
Put an (i) which shows more information about the states and links to a description of the stages (which should be visualized as a DAG figure)

**Comment by pranavjain** [comment]
@epicfaace @jzwang43 Can you share with me the complete flow/list of states? I can run a bundle to get it but just want to make sure that everything is in order.

**Comment by pranavjain** [comment]
How about using something like below to show one-liner info and flow of states? I still need to decide about its exact placement in our front end.
<img width="861" alt="Screen Shot 2021-12-08 at 10 48 54 AM" src="https://user-images.githubusercontent.com/10134824/145266452-675ab8b6-47ee-4213-bad3-fcea1df26760.png">

@percyliang @epicfaace

**Comment by epicfaace** [comment]
Are these bundle states?

**Comment by epicfaace** [comment]
If so, they're all here: https://github.com/codalab/codalab-worksheets/blob/178fa23ecfa5061830d06107e4bb5ba6cc9d69d6/codalab/worker/bundle_state.py#L5

**Comment by pranavjain** [comment]
Thanks! We seem to be having too many states. It might make sense to put this in our CodaLab documentation and link to that page.

**Comment by percyliang** [comment]
Create documentation with a flowchart and put a link to the flowchart from the website.

**Comment by pranavjain** [comment]
As discussed in the meeting, we would first add the flowchart in the student documentation to get feedback. Post course, this would be added to the official CodaLab documentation and linked to the website.

**Comment by pranavjain** [comment]
@jzwang43 assigning this to you as per our discussion.

**Comment by jzwang43** [comment]
@pranavjain are we just adding this to the student documentation for now?

**Comment by pranavjain** [comment]
We added some text for the states to the student documentation. The proposed flowchart and suggestions are on our slack group.
