### ISSUE TITLE
Worksheet should automatically refresh when a bundle is in uploading state

### ISSUE THREAD

**Issue by jzwang43** [codalab/codalab-worksheets#3839]
Worksheet should automatically refresh when a bundle is in uploading state (basically as long as there are bundles that aren’t in terminal states (ready, failed, killed)).  This used to work for running bundles, but this doesn’t seem to be the case anymore.

**Comment by jzwang43** [comment]
I was able to reproduce the issue. I think right now if you open a new page, the website is not starting a check for bundles in non-terminal states. I am working on identifying the cause of this. It's likely the `checkRunBundle` is not working properly for this case.

**Comment by leilenah** [comment]
fixed
