### ISSUE TITLE
Typo in Wiki: Execution

### ISSUE THREAD

**Issue by YikSanChan** [codalab/codalab-worksheets#385]
[https://github.com/codalab/codalab-worksheets/wiki/Execution#default-workers](https://github.com/codalab/codalab-worksheets/wiki/Execution#default-workers)

Currently, each **non-GPU** machine has 4 cores and 14 GB of memory, and each **non-GPU** machine has 6 cores and 56 GB of memory (but this is subject to change).

I think there is something wrong here.

**Comment by percyliang** [comment]
Fixed - thanks.
