### ISSUE TITLE
Change wordings of My Profile

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#3864]
"My Profile" button on the navigation bar leads to the users' worksheets list. As a user, I was trying to find the worksheets page, and "My Profile" wasn't intuitive to me.

Should we change it to "My Worksheets" or "Worksheets"?

![Screenshot from 2021-10-27 13-14-27](https://user-images.githubusercontent.com/10134824/139140219-1d5f9329-9a76-4362-9181-1904ad93dcf0.png)

Suggestions @percyliang / @epicfaace ?

**Comment by pranavjain** [comment]
Percy's Comments from the Slack:

> The original idea was that the Profile would contain other things besides worksheets...and it's kind of like a dashboard or a user page - it's analogous to someone's github page
> But agree that 'Profile' suggests that you're just editing your personal info
> So could be 'My Stuff'?
> but since worksheets are the main entry point, 'My Worksheets' might be fine too
> 'My' might be useful because one could imagine 'Gallery' which is public worksheets

**Comment by pranavjain** [comment]
Still awaiting to reach a consensus on the new name.

**Comment by percyliang** [comment]
What about 'My Hub'?

**Comment by pranavjain** [comment]
> What about 'My Hub'?

I think 'Hub' might confuse the users. Let's keep it 'My Worksheets' to be very clear and simple. I know its repetitive with the inner tab wordings. We can also use something like 'My Home' or 'My Documents'.

**Comment by percyliang** [comment]
Let's not use 'Home' because there's a notion of a home worksheet.

We can say 'My Worksheets', and then change the tabs to be 'Owned by me'
and 'Shared with me'.
