### ISSUE TITLE
scrolling down on worksheets page doesn't jump to the right place

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#3866]
Press shift-G or click the down arrow in the bottom-right.  The focusIndex goes to the right place, but this goes off the screen (the page should scroll).

**Comment by pranavjain** [comment]
This was implemented as part of https://github.com/codalab/codalab-worksheets/pull/2585

I think this started regressing when we removed JQuery via https://github.com/codalab/codalab-worksheets/pull/3529

Looking into this.
