### ISSUE TITLE
[USER ISSUE] Not getting any e-mail for 'forgot your password?'

### ISSUE THREAD

**Issue by combacsa** [codalab/codalab-worksheets#3869]
**Describe the bug**
I'm trying to reset password for a CodaLab account using [forgot your password?](https://worksheets.codalab.org/account/reset). The screen showed me _We have sent you an e-mail. Please contact us if you do not receive it within a few minutes._ but I got no e-mail. I sent an inquiry to codalab.worksheets@gmail.com, but not getting any replies yet since last friday.

**Codalab Information**
- *Your username*: N/A (I sent the specific username and UUID to the codalab.worksheets@gmail.com)
- *UUID of worksheet where problem occurred*: N/A
- *UUID of problem bundle (please don't delete)*: N/A
- *Error message received from Codalab (if applicable)*: N/A
 - *OS (if on CLI)*: N/A
 - *Codalab CLI Version (if on CLI)*: N/A
 - *Browser (if on Web)*; Google Chrome 97.0.4683.2(Official Build) canary (x86_64)

**To Reproduce**
Steps to reproduce the behavior :
1. Go to [forgot your password?](https://worksheets.codalab.org/account/reset)
2. Type the e-mail address, and then Click on `Request Password Reset` button
3. Wait
4. Not getting any e-mail from CodaLab

**Expected behavior**
Get an e-mail with Password Reset Link

**Screenshots**
N/A

**Additional context**
I sent two e-malis with the inquiry about password reset to the e-mail account, `codalab.worksheets@gmail.com`, which I believe the 'contact point' of the official CodaLab worksheet service. First mail sent at 2021. 10. 29. 20: 45 (UTC +09:00) and second mail sent at 2021. 11. 01. 13:37 (UTC +09:00). I'm creating this issue at 2021. 11. 02. 00:00 (UTC +09:00).

**Comment by epicfaace** [comment]
Looking into it!

--
Ashwin Ramaswami

**Comment by combacsa** [comment]
Thanks! Could you confirm that you've got two e-mails I've sent? (I'm trying my best not to expose any account info on this public github issue area... The title of the mail is `Looking for the way to reset password for account` (username))

**Comment by epicfaace** [comment]
Yes, thanks for sending.

--
Ashwin Ramaswami

**Comment by combacsa** [comment]
Now I'm happy to close this issue. All issues resolved. Thank you very much!
