### ISSUE TITLE
Bundle manager changes required for model checkpoints

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3874]
As per https://docs.google.com/document/d/1ifcuXLPldSWJehZgl9RTmPogllbyUJ_vRIOiW2BF1i0/edit#

**Comment by pranavjain** [comment]
Estimate: 02/14

**Comment by epicfaace** [comment]
Status: nearly done, need to add tests and the PR will be ready (https://github.com/codalab/codalab-worksheets/pull/3882)

**Comment by pranavjain** [comment]
ETA: 03/08

**Comment by pranavjain** [comment]
@epicfaace Are we on track to close this one? Do you need inputs from someone?

**Comment by epicfaace** [comment]
I need to test that PR manually and it should be good to go afterwards.

--
Ashwin Ramaswami
