### ISSUE TITLE
How to upload a single updated file in a folder

### ISSUE THREAD

**Issue by himat** [codalab/codalab-worksheets#388]
I first uploaded a folder with my data and code, and then I do `cl run :uploaded-dir-name 'python uploaded-dir-name/code/run.py'`

But if I then update run.py locally, is there a way to just upload run.py *into* the previous uploaded-dir-name folder instead of having to upload the entire large folder again? If I just upload the single file, then it wouldn't be found in the `uploaded-dir-name` directory on codalab right? 

I want to be able to run the same command as I did before which locates the run.py file in the folder (python uploaded-dir-name/code/run.py).

**Comment by percyliang** [comment]
A workaround I typically use is to create a separate directory `upload2/code` which contains a symlink to your `run.py` file.  Then upload `upload2`, which should have the right directory structure and the single file.
