### ISSUE TITLE
Investigate Material UI vs Bootstrap for CodaLab Frontend

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#3883]
We are currently using both Material UI (MUI) and Bootstrap at different places.

The goal of this task is to compare both of these and eventually move CodaLab to use only one.

(This will be a mega issue and sub-tasks would be added.)

**Comment by pranavjain** [comment]
Not a priority right now. Clearing assignment.

**Comment by leilenah** [comment]
Moving towards MUI for all new features.
