### ISSUE TITLE
"format" CI task broken

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3889]
![image](https://user-images.githubusercontent.com/1689183/142285407-b1a69345-fc09-44b0-b158-b48b7ab228d9.png)

@jzwang43 can you look into this? It seems to have started with this commit (https://github.com/codalab/codalab-worksheets/commit/299466ab7fd95d71a9cc6d7a71270402396c2c15).

**Comment by epicfaace** [comment]
Related issue? https://github.com/mkdocs/mkdocs/issues/2469

**Comment by jzwang43** [comment]
@epicfaace I think the CI is working properly now so I will close this issue.

**Comment by epicfaace** [comment]
Thanks

--
Ashwin Ramaswami
