### ISSUE TITLE
Configure default Kubernetes worker managers with multiple queues

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#3898]
Have two different queues - one for smaller jobs and the other for larger jobs

**Comment by percyliang** [comment]
Does it make sense to size them according to what is necessary to train a
GPT-2-{micro, small, medium, large, xl}?

**Comment by teetone** [comment]
New queues documented here: https://github.com/stanford-crfm/mistral-stanford/tree/codalab/codalab
