### ISSUE TITLE
sanitize cells in tables

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#39]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Tuesday Dec 08, 2015 at 09:23 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1492_

---

If we have:

```
% display table /stdout
```

and stdout contains a binary file, then the worksheet crashes.

**Comment by kashizui** [comment]
fix'd
