### ISSUE TITLE
Reserving GPU memory

### ISSUE THREAD

**Issue by connorbrinton** [codalab/codalab-worksheets#391]
Hi CodaLab team!

First off, thanks so much for making this incredible resource available! It's been really enjoyable to start using it.

We're having trouble getting GPUs with enough free memory to perform our jobs. The last few jobs we tried to run were assigned to GPUs with about 8GB of memory, but only about 80MB free (yup, MB). Obviously our jobs failed rather quickly.

Is there any way to reserve a particular amount of memory on requested GPUs?

Thanks!
Connor

**Comment by fabeschan** [comment]
There's currently no way to reserve GPU memory -- that's on our roadmap for next quarter though.

**Comment by fabeschan** [comment]
Of course, if you need this feature sooner and decide to implement it yourself, we are happy to give you pointers to help you go about it

**Comment by connorbrinton** [comment]
I looked into the bundle_manager.py code that handles job to worker assignments, but I don't think I have the time to work on an acceptable pull request.

For future reference, as far as I can tell, it would require looking at all running jobs on each worker to determine whether or not the requested resource is exhausted in the function `_filter_and_sort_workers`. This filtering should probably be performed after all other filtering, because other filtering requires only pre-loaded information. The filtering could proceed as follows:
* Generate a mapping from run_uuids -> workers using `worker.run_uuids` for each `worker` in `workers_list`
* Make a deep copy of `workers_list` to prevent modifying values in the WorkerInfoAccessor
* Obtain list of `running_bundles` by calling `self._model.batch_get_bundles(state=State.RUNNING, bundle_type='run')`
* For each `bundle` in `running_bundles`
  * Look up corresponding worker using uuid
  * For each exhaustable resource used by the bundle (i.e. gpu, memory)
    * Decrement the corresponding value in worker by the amount used by the bundle
* Perform original filtering again

Though the above is all based on my own understanding, so there are probably things that should be tweaked, or might be completely incorrect.

**Comment by fabeschan** [comment]
I did some more research on nvidia-docker. It seems like there's no way to limit/reserve a specific amount of GPU memory for a process. https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#can-i-limit-the-gpu-resources-eg-bandwidth-memory-cuda-cores-taken-by-a-container

The next best thing to avoid having jobs failing due to random resource contention would be to assign jobs to specific GPUs. This is something we are working on.

**Comment by fabeschan** [comment]
https://github.com/codalab/codalab-cli/issues/841
