### ISSUE TITLE
"cl store add" should infer --storage-type from --url

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3911]
"cl store add" should infer --storage-type from --url so that --storage-type is not required.

So, current command:

```
cl store add --name blob --storage-type azure_blob --url azfs://devstoreaccount1/bundles
```

Ideal command that we want:

```
cl store add --name blob --url azfs://devstoreaccount1/bundles
```

**Comment by epicfaace** [comment]
@wwwjn link to store documentation: https://codalab-worksheets.readthedocs.io/en/latest/Multiple-Bundle-Stores/

https://github.com/codalab/codalab-worksheets/pull/3928

**Comment by pranavjain** [comment]
@wwwjn To update documentation.
