### ISSUE TITLE
Show bundle stores when running "cl info"

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3914]
When running "cl info [uuid]", it should show the associated bundle locations / bundle stores for that bundle.

**Comment by epicfaace** [comment]
![image](https://user-images.githubusercontent.com/1689183/146284389-94cd8542-d1c9-49dd-a72f-a060e4db154f.png)


Also don't show the "store" field

**Comment by pranavjain** [comment]
Estimate Date: Feb 9
