### ISSUE TITLE
Implement "cl replicate" CLI command

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3922]
Design doc: https://docs.google.com/document/d/1TOsO4gnxUm1XMmlGUb7BJ4Z6y_olFbv9APbx0-IEy6M/edit#

cl replicate [bundle uuid] --store [store name]
Replicates the contents of the specified bundle to the specified bundle store.

**Comment by leilenah** [comment]
still creating / updating feasible design

**Comment by wwwjn** [comment]
New design doc: https://docs.google.com/document/d/1wwMX93k2a7jMpHwR2IrG6jsSbiV0mi0kZ0kzblOmc6I/edit#
