### ISSUE TITLE
Implement "cl rm -d --store" command

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3923]
Design doc: https://docs.google.com/document/d/1TOsO4gnxUm1XMmlGUb7BJ4Z6y_olFbv9APbx0-IEy6M/edit#

cl rm -d --store [store name]
Updates existing command “cl rm -d”; keeps the bundle, but removes the bundle contents from the specified bundle store.

**Comment by percyliang** [comment]
Since each bundle is only in one store right now, don't need this.
