### ISSUE TITLE
Is there a way to prevent codalab from extracting a gz file?

### ISSUE THREAD

**Issue by rosecatherinek** [codalab/codalab-worksheets#393]
I have a large data file compressed to a .gz file to save space and read/write time. The code processes the compressed file and doesn't require it to be in its extracted form. 

When I upload the data file, either using the cli or the browser gui of codalab, it extracts the gz file. I could not find an option here: https://github.com/codalab/codalab-worksheets/wiki/CLI-Reference
that would prevent codalab from extracting the uploaded file. I'm not sure if I'm missing something. Any suggestions would be helpful. Thanks!

For now, my work around is to compress it again in a codalab run bundle after uploading and then forcefully deleting the first file bundle.

**Comment by bkgoksel** [comment]
The -p (or --pack) flag of the cl up command should keep the file packed after upload.

**Comment by rosecatherinek** [comment]
Cool! Thanks!
