### ISSUE TITLE
CLI: Show name of currently uploading file

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#3933]

**Comment by wwwjn** [comment]
Now we can see the file name for uploading files.

![Image](https://user-images.githubusercontent.com/40016222/188961500-44642ae4-c330-494b-9985-c2e5c99041ef.png)


![Image](https://user-images.githubusercontent.com/40016222/188961410-109545b9-359c-421e-8a16-678437794ff7.png)
