### ISSUE TITLE
Stanford: simplify cl-worker-manager startup command

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3946]
Right now, the cl-worker-manager command in the [CodaLab for NLP guide](https://docs.google.com/document/d/168v0WnvhUjYvUFfv5xmw4WbYwaFG-2VqBN9mzT3odAY/edit?disco=AAAAS141NIQ&usp_dm=false) is quite long and complicated:

```
cl-worker-manager --server https://worksheets.codalab.org --min-workers 0 --max-workers 10 --worker-tag nlpgpu --worker-work-dir-prefix /scr/scr-with-most-space/ --worker-pass-down-termination --worker-exit-on-exception --worker-delete-work-dir-on-exit --worker-exit-after-num-runs 1 slurm-batch --partition jag-standard --cpus 4 --gpus 1 --memory-mb 20000 --password-file ~/.codalab/codalab-main.password --slurm-work-dir ~/scr/slurm_output/ --job-name codalab-slurm-worker-stanford-standard  --exclude jagupard28,jagupard29
```

We should make this command easier, use defaults, etc. so it's shorter and people only need to pass in the defaults you only need.

**Comment by teetone** [comment]
Verified. I also updated to use the correct `cl-worker-manager` and `cl-worker`. I will update the NLP guide.

**Comment by epicfaace** [comment]
@teetone What's the new command you replaced it with in the NLP guide?

**Comment by teetone** [comment]
@epicfaace The command was out of sync with we have in the `deployment` repo. I replaced it.

**Comment by epicfaace** [comment]
Replaced it with what new command?

**Comment by teetone** [comment]
> Replaced it with what new command?

The script in the cluster was out of sync with https://github.com/codalab/deployment/blob/master/scripts/nlp-cl-worker-manager. I also updated the NLP guide. You can see the latest changes in the doc.

**Comment by epicfaace** [comment]
Great, thanks!

--
Ashwin Ramaswami
