### ISSUE TITLE
Set oauth token expiration default to a month

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#3948]
![extend oauth token expiration](https://user-images.githubusercontent.com/16793796/149629521-08beeed8-1f44-4f38-b2dd-3754130dda96.png)

**Comment by pranavjain** [comment]
Estimate: 1 Day of work.

**Comment by teetone** [comment]
Try just:

```
nlp-cl-worker-manager nlp
nlp-cl-worker-manager nlp
```

without logging in.

**Comment by percyliang** [comment]
Seems to be working.
