### ISSUE TITLE
worker_offline

### ISSUE THREAD

**Issue by YikSanChan** [codalab/codalab-worksheets#395]
I try to run this bundle https://worksheets.codalab.org/bundles/0x2beb0962a9e34732b4ee44de43b87e03/ but gets worker_offline state. What does it mean and how to solve it? Thank you

**Comment by fabeschan** [comment]
Docker pull image can get stuck sometimes, causing the server to think the worker has gone offline. Could you try again and see if the issue persists?

**Comment by YikSanChan** [comment]
Now it throws error. https://worksheets.codalab.org/rest/bundles/0xd7200d824c8840788c2349c033b99208/contents/blob/stderr
Could you please kindly take a look? Thanks

**Comment by fabeschan** [comment]
Out of memory; perhaps this bundle was placed in a worker that didn't have enough working memory. Retrying may place your bundle in a different worker that has enough memory.

Sensible memory allocation is a feature we are working on currently that we hope can fix this soon.

I will close this for now; feel free to reopen if you see it again.
