### ISSUE TITLE
cs324 - users who haven't been added to the protected mode server get ugly exceptions

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3961]
- User creates an account on cs324.codalab.org
- User gets ugly experience (can't create worksheets, etc.)

Ideal behavior:
- users should just be presented with a message that says "please contact the admins to get access to this server"

**Comment by pranavjain** [comment]
I just created a new account, and things were smooth for me until I tried creating a "New Worksheet."

No error is shown to the user, nor is the worksheet created.

@percyliang When are you getting the 'error message'? Was it via CLI?

**Comment by jzwang43** [comment]
I am getting this after trying to register and click on the confirmation link sent to my email:

![image](https://user-images.githubusercontent.com/29891066/150742224-653878aa-9c91-4231-acfc-58a2de048c1e.png)

I was able to complete registration without any issue.

**Comment by pranavjain** [comment]
Estimated Completion Date: Feb 8

**Comment by pranavjain** [comment]
@jzwang43 Can you please add a video/image of the new behavior? When is it expected for the user to see an error now? I will run some manual tests to verify.
