### ISSUE TITLE
Problem with dragging open web terminal

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#397]
Clicking and dragging open the web terminal doesn't expand the area where the output is shown.

![screen shot 2017-12-11 at 10 54 13 am](https://user-images.githubusercontent.com/5680188/33848148-bf6dc8c2-de61-11e7-9fc7-68182f225379.png)

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1061
