### ISSUE TITLE
Extend SAS token logic to bypass server for GCS downloads

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3974]
Right now we only support generating SAS tokens for Azure Blob downloads (and soon uploads). We should extend this logic to generate signed URLs that can be used in GCS as well.

**Comment by pranavjain** [comment]
ETA: 03/15

**Comment by epicfaace** [comment]
@wwwjn let's first start by bypassing server for GCS downloads and do that in one PR. We can then bypass the server for GCS uploads in another PR.

**Comment by wwwjn** [comment]
Update: Figure our problem in python package Httplib2 and Apache Beam. 
Design Doc and Solution: https://docs.google.com/document/d/1q2zTXFPlkjnm-xm6_IcfenAm5twBsYOIEdopxEHCbx0/edit#

**Comment by pranavjain** [comment]
@epicfaace and @wwwjn will work on resolving the test cases.
