### ISSUE TITLE
Launch jobs through a kubernetes runtime instead of a docker runtime (because GKE has deprecated the docker runtime)

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3975]
https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

https://kubernetes.io/blog/2022/01/07/kubernetes-is-moving-on-from-dockershim/

**Comment by pranavjain** [comment]
This is planned to be depreciated in Kubernetes 1.24 (ETA April 2022).

**Comment by pranavjain** [comment]
@epicfaace will pick this task after the necessary tasks for the course are done.

**Comment by epicfaace** [comment]
Two options:
1. Mount containerd socket (`/run/containerd/containerd.sock`) instead of docker socket (`/var/run/docker.sock`). (https://github.com/containerd/containerd/blob/main/docs/getting-started.md, https://github.com/codalab/codalab-worksheets/blob/master/codalab/worker_manager/kubernetes_worker_manager.py#L133)
2. Rather than running a Docker container, a worker can just interface with the k8s API to launch a job.

2) is probably the right path forward.

**Comment by pranavjain** [comment]
@epicfaace Are you working on this one actively? Do we have some rough ETA?

**Comment by epicfaace** [comment]
The plan is for me to have something written up by Tuesday as to a possible
approach to solve the problem. Will work on this soon.

--
Ashwin Ramaswami

**Comment by epicfaace** [comment]
Details: https://docs.google.com/document/d/1QsnUYAb0DzbH6uKA1L5oTbmxQYikGQ7F_FI4n3Tgp_g/edit

**Comment by epicfaace** [comment]
https://cloud.google.com/kubernetes-engine/docs/deprecations/docker-containerd

**Comment by epicfaace** [comment]
Good read / explanation: https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-removal-affects-you/

**Comment by pranavjain** [comment]
@teetone to help with the testing Nvidia containerd

**Comment by pranavjain** [comment]
https://jamboard.google.com/d/1_wV8vM9A5nMo1i4r6A8ZmgBMUSGKe7hkXyHZscLV8w0/viewer?ts=62c74ff8

**Comment by pranavjain** [comment]
ToDo: Code Cleanup by Ashwin

**Comment by pranavjain** [comment]
#4214 is ready for review (ToDo: @wwwjn )
#4090 Still pending code clean up.
