### ISSUE TITLE
Show current file/folder path in the navigation pane

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#3988]
We don't show the path/directory in which the user is browsing, which is confusing for the user.

https://user-images.githubusercontent.com/10134824/152869119-3a3dc686-7a62-4503-93b7-2bfcf4192e4c.mov

`In the above example path is a1/a2/..`

**Comment by leilenah** [comment]
Added in https://github.com/codalab/codalab-worksheets/pull/4150

**Comment by leilenah** [comment]
https://user-images.githubusercontent.com/25855750/180669802-3ad630fa-acb6-48bd-a619-3611846af9d9.mov
