### ISSUE TITLE
New bundle is added at a random place

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#3989]
### Implementation
- [x] Prevent a worksheet row from having a `null` sort key when rows are created using the cli
    * **Note:** cl commands should always add bundles to the end of the worksheet
- [x] Check for `null` sort keys when we initially fetch a worksheet and fix them on the spot if needed
- [x] Code documentation
- [x] Write tests if needed
- [x] QA
    - [x] Ensure that source editing is not impacted
    - [x] Test large worksheets that have lots of rows with null sort keys
    - [x] Test a worksheet with a mixture of bundles created in web and bundles created in CLI
    - [x] Remove test console logs 

### Background

The bundle should be added at the same place where the user has selected. Currently, it is getting placed at random places in the worksheet.

https://user-images.githubusercontent.com/10134824/152871649-3a46f325-000f-41e6-853b-421011812961.mov

**Comment by pranavjain** [comment]
Estimate: 02/14

**Comment by pranavjain** [comment]
@jzwang43 Is there any update on this one?

**Comment by jzwang43** [comment]
I have narrowed it down to after_sort_key and getAfterSortKey function. The after_sort_key determines where the new run should be inserted. Still working on figuring out why this after_sort_key is incorrect.

**Comment by jzwang43** [comment]
looks like sometimes sort key is set to null for some rows:

![image](https://user-images.githubusercontent.com/29891066/154439414-3b36179e-d169-46b1-9429-e4208ccd26a1.png)

This is returned from the backend. could it be some issue with the backend? The api is rest/interpret/worksheet/

@epicfaace @pranavjain do you have any insights on this?

**Comment by epicfaace** [comment]
@jzwang43 Can you please send me the worksheet link?

**Comment by jzwang43** [comment]
> @jzwang43 Can you please send me the worksheet link?

@epicfaace try 0x411c4f80346b4732a1aacb8402ec4d04 on codalab.worksheets.org. It's also pretty easy to reproduce locally.

**Comment by epicfaace** [comment]
I'm not sure why this is happening -- would take more time to debug

**Comment by epicfaace** [comment]
I'm not prioritizing working on this atm, but let me know if I should

**Comment by epicfaace** [comment]
@jzwang43 is this something maybe you'd be able to debug? I'm not very familiar with the sort key logic, if you have bandwidth could you take some time and step through the code to figure out what's happening?

**Comment by leilenah** [comment]
### Investigation
* view affected is worksheet view
* the user should be able to select and determine where the bundle is to be added
* likely an issue with  `after_sort_key` and `getAfterSortKey` function 
    * The `after_sort_key` determines where the new run should be inserted
* sometimes sort key is set to null for some rows
    * potentially could be an issue with the way the backend is sending data over
    * we could adjust that, or re-sort on the frontend, TBD

**Comment by leilenah** [comment]
### Unable to Repro
@pranavjain @epicfaace I am unable to reproduce this bug. Are either of you able to repro on your end? I'm wondering if this was fixed with some other issue.

### Screen Recording

https://user-images.githubusercontent.com/25855750/175366624-a3442df1-7cb0-41b6-a97d-12a654f00a82.mov

**Comment by leilenah** [comment]
@percyliang do you happen to know if this was resolved with a different issue? Are you able to repro on your end?

**Comment by jzwang43** [comment]
You might have to create bundles through CLI and open the same worksheet on
web to reproduce.

**Comment by leilenah** [comment]
@jzwang43 I just attempted that flow and am still unable to repro. Are you able to point me to a worksheet on production where this is happening?

**Comment by leilenah** [comment]
Removing myself from this issue for now, as I am unable to repro it. If anyone is able to repro or if a user reports this issue, feel free to re-assign me.

**Comment by epicfaace** [comment]
> > @jzwang43 Can you please send me the worksheet link?
> 
> @epicfaace try 0x411c4f80346b4732a1aacb8402ec4d04 on codalab.worksheets.org. It's also pretty easy to reproduce locally.

@leilenah did you try this worksheet?

If you can't reproduce, please close this issue.

**Comment by leilenah** [comment]
@epicfaace I don't have access to modify that worksheet. Are you able to grant me access?

**Comment by epicfaace** [comment]
@leilenah Try logging in as the codalab admin user? https://github.com/codalab/deployment/blob/main/ansible/roles/credentials/vars/main.yml#L3-L4

**Comment by pranavjain** [comment]
@leilenah, I was able to repro it. Please select a bundle on your bottom sheet before clicking on the `run` button. This new bundle should be added below the selected one, but it goes to a random place.

**Comment by leilenah** [comment]
@pranavjain @epicfaace below is a screen recording of me trying to repro the issue on worksheet `0x411c4f80346b4732a1aacb8402ec4d04` while logged in as the codalab admin user. I am still unable to repro (even with Pranav's latest instructions). 

I'm going to close this issue for now. Please let me know if anyone comes across this issue again.

### Screen Recording

https://user-images.githubusercontent.com/25855750/177068320-f8dc3a5c-55a9-43c1-b5e3-6fd0e613442c.mov

**Comment by jzwang43** [comment]
@leilenah 
only the last two items in the worksheet have issues, try clicking on one of the last two items. You will see the new run show up above them instead of below

**Comment by jzwang43** [comment]
@leilenah The reason why this happens is that the items have sort-key as "null", check out my previous pull request for this issue and the conversations for more context.

https://worksheets.codalab.org/rest/interpret/worksheet/0x411c4f80346b4732a1aacb8402ec4d04?brief=1

This is the API request for the worksheet items and then search for sort_key and you will see the nulls.

**Comment by leilenah** [comment]
@jzwang43 here's an updated screen recording of me only creating runs below the last two items. It looks like they appear in the correct place. Am I missing a step? Or perhaps am I misunderstanding where the bundles should end up in the UI?

**Browser Used:** Chrome
**Worksheet Used:** https://worksheets.codalab.org/worksheets/0x411c4f80346b4732a1aacb8402ec4d04

https://user-images.githubusercontent.com/25855750/177205466-0bf8eb4d-31f6-4f76-b4d4-216ba95b225d.mov

**Comment by jzwang43** [comment]
@leilenah Hi, when you were trying to reproduce, there were no null sort_keys in the worksheet for some reason.
Sort keys were created by creating run bundles via CLI. 

I created several null sort key items at the bottom, you can try again to reproduce, or manually create null sort_keys items by running `cl run "xxxxx"` in the command line on the web UI.

https://user-images.githubusercontent.com/29891066/177210806-f765c070-c579-4ae2-bb73-f9ebb83f3234.mov

**Comment by leilenah** [comment]
Ah, thanks for the additional context @jzwang43.
