### ISSUE TITLE
make deployment not fill up disk space

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#399]
Currently, all requests from worker to main server are logged, which fills up quickly.  Reduce the logging frequency.

**Comment by bkgoksel** [comment]
`resume_bundles` calls seem to be problematic. Will handle this with worker 2.0 update.

**Comment by bkgoksel** [comment]
Fixed with worker 2.0 (no more resume_bundle calls for each bundle)

**Comment by bkgoksel** [comment]
If happens in the future we should look into reducing the docker log size.
