### ISSUE TITLE
allow partial download and upload of bundles

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#4]
<a href="https://github.com/Raisins"><img src="https://avatars.githubusercontent.com/u/123099?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Raisins](https://github.com/Raisins)**
_Friday Aug 01, 2014 at 22:47 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/571_

---

allow partial download and upload of bundles

**Comment by percyliang** [comment]
Supporting partial download (via wget -c ...) is more important.  Handle this on codalab-cli side.

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1084
