### ISSUE TITLE
Show actual progress in upload progress bars 

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#40]
<a href="https://github.com/kashizui"><img src="https://avatars.githubusercontent.com/u/614837?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kashizui](https://github.com/kashizui)**
_Wednesday Dec 09, 2015 at 23:20 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1495_

---

**Comment by kashizui** [comment]
Fixed by #219
