### ISSUE TITLE
Anonymous worksheets and bundles

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#400]
When submitting to a double-blind conference, it would be nice to be able to include a link to a CodaLab worksheet without revealing the user identity.  Worksheets and bundles should have an anonymous flag such that when set, people can still read the bundle, but the user is not revealed.

**Comment by kashizui** [comment]
To clarify, if a bundle (or worksheet) is anonymous:

- the owner should still be able to see their own identity
- users with 'all' permission should still be able to see the identity of the bundle
- users with 'all' permission can modify the anonymous flag
- users with 'read' permission should NOT be able to see who owns the bundle (should all group permissions also be hidden from these users?)
- users with 'none' permission should not be able to see anything about the bundle

**Comment by kashizui** [comment]
Also:
- only the owner can modify can update the anonymous flag (or should users with 'all' permissions also be able to do so?)

**Comment by kashizui** [comment]
Policy:
Just hide

- owner_id
- request_docker_image
- docker_image
- job_handle
- remote

To determine which fields to hide/show, add another field to MetadataSpec, like generated or formatting?
