### ISSUE TITLE
When starting a bundle, its state keeps flickering between "starting" and "staged"

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4004]
Steps to reproduce:
1. Create a bundle
2. Go to the bundle details page and keep refreshing
3. The state keeps flickering between "starting" and "staged" on different page loads.

**Comment by epicfaace** [comment]
related debugging:

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/1689183/154350396-2140b8ff-47ce-47b9-8480-6ac363e33f95.png">

**Comment by pranavjain** [comment]
Does this only repro in case we do consistent refreshing of the page? If so, this might be corner care, and we can prioritize it later.

**Comment by epicfaace** [comment]
Yes, but the state is actually being constantly toggled from starting<->staged on the backend. I wonder if this is the reason why bundles are often stuck in "staged" (maybe they're stuck in some kind of loop)... Fixing it might make the bundle manager much faster.

**Comment by pranavjain** [comment]
Amazing! Do we know the root cause for this one yet?

**Comment by epicfaace** [comment]
I can no longer replicate. I think it was fixed by https://github.com/codalab/codalab-worksheets/pull/4024
