### ISSUE TITLE
[CS324] resize main disk

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4008]
Resize main disk to be ~10 TB.

https://cloud.google.com/compute/docs/disks/resize-persistent-disk

**Comment by epicfaace** [comment]
@pranavjain this is also needed to be done before we open

**Comment by pranavjain** [comment]
@epicfaace Marking this one as active as we need it asap for the course.

**Comment by pranavjain** [comment]
@epicfaace Is this one done?

**Comment by epicfaace** [comment]
Done!

![image](https://user-images.githubusercontent.com/1689183/154995169-d6fc3afe-46ab-4d2a-9ea3-05dd7fc08f02.png)
