### ISSUE TITLE
files disappearing mysteriously

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#401]
1) Some of the jobs I've launched having been losing data. The files accessible via Codalab are not the complete set of files that my jobs write to. In particular, my tensorboard files are being lost. Here are some examples:

https://worksheets.codalab.org/bundles/0x190ff71e77f9455eaeed35e6b239415e/
https://worksheets.codalab.org/bundles/0x0d73a518f49b4c3c892a2828725e86a6/
https://worksheets.codalab.org/bundles/0x9a74dfc6dc9a42478eb8b69cc26f49ce/

Seems to be the jobs that fail with this error message:

Container 66c1ac1252eb5b11cd24dfd642a2b179eafb5bb6e7541c5595abb8befdc1a64b Lost by Docker

2) these following bundles that have successfully completed, currently with the "ready" status, but are also missing my tensorboard files.

https://worksheets.codalab.org/bundles/0x69d279ad6261478b8d78efb7faa88e82/
https://worksheets.codalab.org/bundles/0x019cd1d032d94795a45f6595ecf79809/

**Comment by percyliang** [comment]
Talk to Evan about this.

**Comment by sunmeng01** [comment]
We had the same problem, and the failure_message was "Container 621c107b34a96c701e372d4f3c143964604ad23a318d100a1a2656a154d56f56 Lost by Docker".
However, We didn't find any missing file in the worksheets.

**Comment by percyliang** [comment]
We're planning to revamp the worker system, closing for now.
