### ISSUE TITLE
Screen goes blank when looking at a JSON bundle

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#4037]
To reproduce, visit this page:

https://codalab.stanford.edu/bundles/0x6e3abaeb28e34640a12a9a66d27d8ddf

**Comment by jzwang43** [comment]
@teetone 
I uploaded a json and didn't get the blank page. But when I opened your bundle I'm getting the blank page.
Is there anything special about your bundle you can share to help me identify the issue?

My test bundle: https://worksheets.codalab.org/bundles/0x127c1ca815104f7d927ebb17781a01c3

**Comment by pranavjain** [comment]
@teetone Can you provide more details about this one?
