### ISSUE TITLE
GKE auto scale + nvidia driver installation takes some time when spinning up new VMs

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#4042]
Time:

Worker manager GPU pool (9 minutes to start a worker)
2022-02-23 00:40:33,898 Starting a worker!
At 45 the VM came up (4.5 minutes)
At 49 the nvidia drivers are installed (4.5 minutes)

GKE node images:

https://cloud.google.com/kubernetes-engine/docs/concepts/node-images
https://stackoverflow.com/questions/60151864/does-google-kubernetes-engine-support-custom-node-images-and-or-10gbps-networkin
https://groups.google.com/g/gce-discussion/c/jIX6jN6X4r0

**Comment by teetone** [comment]
From https://stackoverflow.com/questions/60151864/does-google-kubernetes-engine-support-custom-node-images-and-or-10gbps-networkin, "GKE...does not support custom node images." Also, see this related link: https://groups.google.com/g/gce-discussion/c/jIX6jN6X4r0?pli=1.

When I first worked on GKE + CodaLab, I didn't see any other solution except for installing the Nvidia drivers via DaemonSets.

**Comment by epicfaace** [comment]
@teetone What does that mean? Are we still able to solve the issue?

**Comment by teetone** [comment]
> @teetone What does that mean? Are we still able to solve the issue?

I don't think it's possible. We will save some time when we switch to Pods since we can just skip the Docker-related installation.
