### ISSUE TITLE
[USER ISSUE] Downloading a bundle from the UI fails (cl download works)

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#4049]
I tried to download a bundle from the browser but it keeps failing with a network connection issue: https://worksheets.codalab.org/bundles/0xf8f802d486fc44aabadb57e7f5fabc92. Running `cl download 0xf8f802d486fc44aabadb57e7f5fabc92` in a terminal works though.

**Comment by epicfaace** [comment]
How did you download it? Did you click on the URL in your browser? What error do you get?

**Comment by teetone** [comment]
> How did you download it? Did you click on the URL in your browser? What error do you get?

I clicked on the download button. I got a `Network Error`.

**Comment by pranavjain** [comment]
I was able to start the download. Did you get the error after a part of the download had been completed?

**Comment by pranavjain** [comment]
@teetone Can you check if there is a repro at your end? Else, we will close this one.
