### ISSUE TITLE
worksheets.codalab.org is broken

### ISSUE THREAD

**Issue by htfy96** [codalab/codalab-worksheets#405]
Not sure should I report here, but it seems that worksheets.codalab.org is broken at the moment:
```
➜  ~ curl -v https://worksheets.codalab.org/
*   Trying 40.71.231.153...
* TCP_NODELAY set
* connect to 40.71.231.153 port 443 failed: Connection refused
* Failed to connect to worksheets.codalab.org port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to worksheets.codalab.org port 443: Connection refused
➜  ~ nc -vvv 40.71.231.153 443
nc: connect to 40.71.231.153 port 443 (tcp) failed: Connection refused
```

Feel free to close this issue if you think it is out-of-scope.

**Comment by percyliang** [comment]
Looks like Azure just decided it wanted to reboot the machine.  Should be
fixed now.

**Comment by fabeschan** [comment]
seems to coincide with kernel updates to address the recently-publicized security vulnerabilities discovered in Intel chips

https://azure.microsoft.com/en-us/blog/securing-azure-customers-from-cpu-vulnerability/
