### ISSUE TITLE
Why can not I use mkdir and cp command in codalab shell and Permission denied

### ISSUE THREAD

**Issue by JiexingQi** [codalab/codalab-worksheets#4054]
**Describe the bug**
I run a simple script like this:
```
cl run "text-to-sql:0x45c42b" "run_on_codalab.sh:0xdfb517" "data:0x6aee79" "database:0x853385" "bash run_on_codalab.sh" --request-network --request-cpus 16 --request-memory 32g --request-docker-image codalab/default-cpu
```
and the content for run_on_codalab.sh is 
```
#!/bin/bash

mkdir /app
mkdir /app/gen-cpp2
mkdir /app/gen-py3

echo "show pwd"
pwd
echo "show ls"
ls

echo "cp command"
pushd text-to-sql
cp picard.thrift /app/
cp -r gen-cpp2 /app/gen-cpp2/
cp -r gen-py3 /app/gen-py3/
popd
```
but it show that Permission denied
the output is as follows:
```
[stdout](https://worksheets.codalab.org/rest/bundles/0x9fb44b48628f45f8ae77e7fe11595e82/contents/blob/stdout) ▾
show pwd
/0x9fb44b48628f45f8ae77e7fe11595e82
show ls
data
database
run_on_codalab.sh
stderr
stdout
text-to-sql
cp command
~/text-to-sql ~
~
```

```
[stderr](https://worksheets.codalab.org/rest/bundles/0x9fb44b48628f45f8ae77e7fe11595e82/contents/blob/stderr) ▾
mkdir: cannot create directory ‘/app’: Permission denied
mkdir: cannot create directory ‘/app/gen-cpp2’: No such file or directory
mkdir: cannot create directory ‘/app/gen-py3’: No such file or directory
cp: cannot create regular file '/app/': Not a directory
cp: cannot create directory '/app/gen-cpp2/': No such file or directory
cp: cannot create directory '/app/gen-py3/': No such file or directory
```

**Codalab Information**
- *Your username*:jxqi
- *UUID of worksheet where problem occurred*:https://worksheets.codalab.org/worksheets/0x522f03a4d5a84341ae235395ef87e056
- *UUID of problem bundle (please don't delete)*:https://worksheets.codalab.org/bundles/0x9fb44b48628f45f8ae77e7fe11595e82
- *Error message received from Codalab (if applicable)*: ref to above
 - *OS (if on CLI)*: linux
 - *Codalab CLI Version (if on CLI)*: 1.4.6
 - *Browser (if on Web)*;Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. Go to ['...'](https://worksheets.codalab.org/bundles/0x9fb44b48628f45f8ae77e7fe11595e82)
2. See error

**Expected behavior**
description shown above

**Comment by epicfaace** [comment]
I don't think you can create directories at "/app". You should try to create files within your working directory ("mkdir app"), does that work?

**Comment by JiexingQi** [comment]
Thank you, @epicfaace , I find the problem occoured in my own mechine and when I use a codalab remote mechine, this porblem disappeared, I think it may be the docekr version in my mechine is 20.03>19.03. After all, it run normally now. Thanks again.

**Comment by JiexingQi** [comment]
By the way, can you help me for issue https://github.com/codalab/codalab-worksheets/issues/4055, thanks a lot.

**Comment by epicfaace** [comment]
I don't think you can create directories at "/app". You should try to
create files within your working directory ("mkdir app"), does that work?

--
Ashwin Ramaswami
