### ISSUE TITLE
More disk space needed

### ISSUE THREAD

**Issue by JiexingQi** [codalab/codalab-worksheets#4055]
Hi, I'm running T5-3B model in codalab, and a checkpoint for this is 10.6G, more than 10G that a the upper limit of user storage. I find my run bundle was killed after I download a checkpoint in huggingface website. Can you give me more disk space for runing my model. Thank you.

**Codalab Information**
- *Your username*: jxqi
- *UUID of worksheet where problem occurred*: https://worksheets.codalab.org/worksheets/0x74d9be71534a40248f9b2f1e56d5d936

**Comment by epicfaace** [comment]
@JiexingQi Done!

**Comment by JiexingQi** [comment]
Thanks a lot @epicfaace
