### ISSUE TITLE
Does a larger memory GPU can be provided？

### ISSUE THREAD

**Issue by JiexingQi** [codalab/codalab-worksheets#4056]
Hi，I'm running T5-3B model to inference, and the submit bundle can not run in K80 GPU because of out-of-memory(OOM). However, I run my model in A100(40G) normally. Does Codalab provide gpus with larger memory(such as A100)? 

**Codalab Information**
- *Your username*:jxqi
- *UUID of worksheet where problem occurred*:https://worksheets.codalab.org/bundles/0x1b9420b6fda8437f9e5aa7ad4806654d

**Comment by epicfaace** [comment]
@teetone do you know?

**Comment by teetone** [comment]
Hi @JiexingQi, we currently don't provide A100s, but you can also attach your own worker by following the instructions here: https://codalab-worksheets.readthedocs.io/en/latest/Execution/#running-your-own-worker.

**Comment by JiexingQi** [comment]
Well，thank you @teetone

**Comment by JiexingQi** [comment]
@teetone Sorry to bother you again, but I wonder if I can use another GPU (such as 3090, or 16GB v100) whose memory is larger than 12GB. Does the codalab only support 12GB memory GPU in this platform?

**Comment by teetone** [comment]
> @teetone Sorry to bother you again, but I wonder if I can use another GPU (such as 3090, or 16GB v100) whose memory is larger than 12GB. Does the codalab only support 12GB memory GPU in this platform?

Hi @JiexingQi, we currently have K80 GPUs, but you can attach your workers.

**Comment by JiexingQi** [comment]
@teetone  oh, I got it. Thank you very much.
