### ISSUE TITLE
Provide user information about the different fields in the Bundle View

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#4057]
- We should link these fields to the relevant section in the doc.
- Why do we allow users to change these fields once the bundle is in finished state? cc: @epicfaace @percyliang 

![image](https://user-images.githubusercontent.com/10134824/161332935-93878607-1acd-44dc-8092-1eb419e6018e.png)

**Comment by leilenah** [comment]
@pranavjain I think that having individual tooltips would be more beneficial to the user than turning each metadata field into a link.

However I can also make one doc that contains all the metadata definitions, and then have each tooltip icon link out to that doc (like I did with the state tooltip).

Lmk your thoughts.

**Comment by leilenah** [comment]
@pranavjain to clarify ☝️ each tooltip would contain the relevant metadata description only (unlike the state tooltip, which has the says the same thing in every tooltip).

**Comment by pranavjain** [comment]
I agree that having an individual tooltip would be better.

I have two concerns though:
- It might look a bit cluttered with so many tooltip icons.
- Tooltip is good if we have short/one-liner text which looks like the case right now. But, it might not be extensible later on.

Can you attach a screenshot with tooltip icons in each of the rows to see how it looks?

**Comment by leilenah** [comment]
### Percy Sync
* The backend should provide the description

**Comment by leilenah** [comment]
### Implementation
1. ~~Get descriptions sent from the backend~~
2. ~~Pass descriptions into a tooltip icon (mimic state icon UI)~~
3. ~~Make sure UI matches state icon~~
4. ~~Confirm that editable fields are still editable~~
6. ~~QA~~

**Comment by leilenah** [comment]
@epicfaace or @wwwjn  I would love a review when you have a chance 🙃
