### ISSUE TITLE
Add spinner for STDOUT file output section

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#4058]
Frontend takes time to fetch stdout content and display on the bundle details page. Add a spinner to inform user about this action.

**Comment by leilenah** [comment]
### Implementation
1. Add "Loading..." placeholder to bundle details page stdout content section
2. Replace loading placeholder with spinner icon
    * search repo for existing spinner ui
    * if none exists, pull from mui

**Comment by pranavjain** [comment]
Please hold on to this task. We might not need this anymore due to recent STDOUT changes.

**Comment by leilenah** [comment]
@pranavjain sounds good, added blocked label. Going to un-assign myself as well.

**Comment by leilenah** [comment]
### Notes
* Loading blocks might be better UI than a spinner (see worksheet loading block)
