### ISSUE TITLE
Can't delete bundles in worker_offline state

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#406]

**Comment by fabeschan** [comment]
@bkgoksel can you confirm my suspicions that this issue is limited to bundles stuck in an infinite loop trying to upload results? I have been able to delete bundles in worker_offline state for those that aren't in that loop.

**Comment by bkgoksel** [comment]
I believe this is the case. The reason this happened so frequently earlier was:
1. Uploads were capped by server nginx at 4GB
2. When server dropped the upload at 4GB the worker was configured to retry a lot of times (I don't remember the precise number but something like 72 maybe)
3. Each retry would then go until it uploaded ~4GB and failed, retrying

After disk quota/upload limit issue fixes are merged this should only happen if a worker tries to upload something bigger than our new global limit (which will be 64 or 100GB). I can't see an easy way of not running into this issue short of reducing the number of retries for failed uploads.

**Comment by LivingProgram** [comment]
I've seen this infinite loop of trying to upload 9.9 gb of data when using Codalab, does the request disk need to be increased to avoid this?

**Comment by percyliang** [comment]
How many times do we retry?  Presumably we should just cap it to 3 or some
small number and then fail.  But there shouldn't be a bound on the number
of times the worker tries to connect to the server since the contract is
that the server might go away for a long period of time.

**Comment by bkgoksel** [comment]
@LivingProgram the default request disk is 10gb so runs stop once they hit 10gb of data. You can't request more disk as the user disk quota per user is also 10 gb. We have a patch in review that will make all of this logic more transparent. There's also a separate issue that makes uploads bigger than 4gb unreliable which will also be fixed in next release and doesn't require anything on your part. 

@percyliang looks like we retry 720 times. (I think the retry function was written with the expectation that connection failures would happen immediately so 720 times with a 30 second cooldown was thought as a 6 hour retry period). 

The problem is that the worker cannot differentiate between the connection dropping and the server refusing the upload (this is apparently due to how large http requests work in bottle) I'm worried that reducing the number of retries here would reduce the number of retires for all kinds of network troubles.

**Comment by LivingProgram** [comment]
@bkgoksel  thanks for the clarification
