### ISSUE TITLE
Ensure compatibility of certificates used by webhook backends and aggregated API server backends before upgrading your clusters to Kubernetes Engine version 1.23

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#4060]
1. Follow the guide to [identifying affected users] to check if you have affected clusters with webhooks or aggregated API servers using backend services with incompatible certificates.
2. Update the affected backend services to use certificates with appropriate SANs prior to upgrading the clusters to version 1.23.

You can temporarily prevent auto-upgrade of affected clusters to version 1.23 by configuring a [maintenance exclusion]to disallow minor upgrades.

**Comment by pranavjain** [comment]
@teetone triaging the issue.

**Comment by teetone** [comment]
More information: https://cloud.google.com/kubernetes-engine/docs/deprecations/webhookcompatibility

**Comment by teetone** [comment]
It's not really an issue, as long as we create a fresh cluster with the new version.
