### ISSUE TITLE
`cl upload` needs user-friendly message when specify wrong storage name 

### ISSUE THREAD

**Issue by wwwjn** [codalab/codalab-worksheets#4062]
**Describe the bug**
Need to change the error message to user friendly message when user specify a wrong storage name in "cl upload --store xxx file.txt". For example, as the screenshot shows, there is no storage named  "gcs2"  but I use "cl upload --store gcs file.txt".  The error message  says internal error. Can we change to some user-friendly error message, eg "Might specify wrong store name"?

**Codalab Information**
- *Your username*: wwwjn
- *UUID of worksheet where problem occurred*: N/A
- *UUID of problem bundle (please don't delete)*: N/A
- *Error message received from Codalab (if applicable)*: Internal Server Error about Nonetype
 - *OS (if on CLI)*: MacOS
 - *Codalab CLI Version (if on CLI)*:  1.4.6
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :
1. Specify a wrong store name in `cl upload --store store_name file.txt`, where `store_name` does not exist in current bundle stores. (List all the bundle store using `cl store ls`)

**Expected behavior**
A clear and user-friendly error message.

**Screenshots**
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/40016222/162644901-2a0b94c6-fadd-443b-9488-dde6e70df2b6.png">
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/40016222/162645006-6f30b4c1-6401-47ed-bf5c-65431de43732.png">

**Comment by pranavjain** [comment]
@wwwjn Do we need to do step 1 (Add some store) to repro this error?

**Comment by wwwjn** [comment]
> 

Oh, we do not actually need to add a new store. I will modify the description.

**Comment by leilenah** [comment]
### Implementation
1. ~~If `--store` flag is present, check valid store name before attempting to upload~~
2. ~~If store name is invalid, notify the user~~
3. ~~Show the user a list of valid store names~~
4. Add tests
5. Delete test text after capturing screen recording

### Investigation
* when you upload with an invalid store name, the bundle still gets uploaded to the user's home worksheet
    * we should prevent this
* we should check the store name before attempting to upload 
* we should also list the valid stores if LOE to do so is low
    * otherwise we can say something like "run `cl store ls`" to see stores 

### Developing CLI

#### Option 1
Install the local version of CLI commands
```
pip install -e .
```

Connect to local dockers, e.g. rest-servers to test
```
cl work localhost::
```

#### Option 2

If you would like to modify the rest server, bundle manager, or worker, then you can edit the code and then start only that single Docker container.

Start rest-server container:
```
./codalab_service.py start -bd -s rest-server
```

Run cl commands in docker:
```
docker exec codalab_rest-server_1 cl <command>
```

#### Option 3

```
python3 codalab/bin/cl.py work localhost::
```

**Comment by leilenah** [comment]
### Refactors 
1. Revert store metadata validation
2. Update backend to throw 404 if store is not found
3. Update messaging to tell user to try `cl store ls` 
4. Update `test_cli.py` (if needed)

**Comment by leilenah** [comment]
This issue was resolved by @wwwjn as part of https://github.com/codalab/codalab-worksheets/issues/3779

Specifically with this line: https://github.com/codalab/codalab-worksheets/blame/master/codalab/model/bundle_model.py#L2989

Closing this issue.
