### ISSUE TITLE
Setup my own codalab server

### ISSUE THREAD

**Issue by RogerXT** [codalab/codalab-worksheets#407]
I tried to setup my own codala server. When I started all the necessary services, codalab is not working properly. Many js and css files were missing and I can't sign up. In the instruction, I should navigate to http://localhost:8000. But it seems no setting is related to http://localhost:8000.

![screenshot from 2018-01-31 22-28-58](https://user-images.githubusercontent.com/11673650/35665468-3b7368fe-06db-11e8-9cdc-2c0b5ff49097.png)
![screenshot from 2018-01-31 22-29-30](https://user-images.githubusercontent.com/11673650/35665469-3b926ad8-06db-11e8-9a00-322651af00fa.png)
![screenshot from 2018-01-31 22-30-18](https://user-images.githubusercontent.com/11673650/35665470-3bb04a62-06db-11e8-9965-2d593bcc2ff2.png)
![screenshot from 2018-01-31 22-46-03](https://user-images.githubusercontent.com/11673650/35665471-3bca7860-06db-11e8-9a34-c292855f456b.png)
![screenshot from 2018-01-31 23-09-02](https://user-images.githubusercontent.com/11673650/35665596-ca2a3d52-06db-11e8-8803-08a396d471da.png)

**Comment by fabeschan** [comment]
Is ngix configured and running?

**Comment by RogerXT** [comment]
Thank you for your reply!
It seems nginx will include all the conf files in include /etc/nginx/conf.d/*.conf. So I put codalab.conf in this folder and started nginx. I am not sure whether this was right.
![screenshot from 2018-02-01 10-55-46](https://user-images.githubusercontent.com/11673650/35697278-87264ace-073e-11e8-8acb-c4320a86c5ae.png)

**Comment by RogerXT** [comment]
Monitor didn't run properly.

![screenshot from 2018-02-02 15-07-00](https://user-images.githubusercontent.com/11673650/35758838-c686c076-082a-11e8-82e6-95d6cc67aa43.png)

**Comment by fabeschan** [comment]
Your `cl` is not in your path, which explains the stacktrace while running monitor.

**Comment by fabeschan** [comment]
Can you check your nginx.conf and see if the `/rest` endpoint rewrite is there?

**Comment by RogerXT** [comment]
Thank you for your reply.

I added cl to my path, but monitor is still not working.

As for nginx.conf, do you mean codalab.conf (after rename in the Server Setup part)? If I made no mistake, the only thing we did before start nginx is to include codala.conf, i.e., the one generated by ./manage config_gen?
![screenshot from 2018-02-02 18-39-10](https://user-images.githubusercontent.com/11673650/35762287-2bffa31e-0849-11e8-9a47-3faf21d92c63.png)
![screenshot from 2018-02-02 18-43-02](https://user-images.githubusercontent.com/11673650/35762288-2c1b08d4-0849-11e8-8aa9-51a61b1a5741.png)

**Comment by fabeschan** [comment]
When you run monitor with `sudo`, you are running it as the root user, which may not have the same path as you do.

**Comment by fabeschan** [comment]
Try setting `set $maintenance = 1` and restart nginx. If `localhost:2700` homepage doesn't change then it's something to do with how you configured nginx

**Comment by RogerXT** [comment]
Thank you so much for your kind help.
You are right. I set $maintenance = 1 and localhost:2700 homepage didn't change. Then the problem is about nginx configuration. Do we just need to include codalab.conf? Or we need to change other parts?

**Comment by fabeschan** [comment]
I don't know enough to answer your question. Perhaps consult the nginx documentation

**Comment by RogerXT** [comment]
Hi, me again... So sorry for bothering you.
When I started a worker, I got an internal error. I think this might be the real problem.
Any ideas?
![screenshot from 2018-02-08 12-08-23](https://user-images.githubusercontent.com/11673650/35995843-71d86158-0cc9-11e8-8eea-d98cd0b7e912.png)

**Comment by fabeschan** [comment]
The worker cannot talk to the rest api because nginx is not configured properly, hence the internal error. Again, please consult the nginx documentation.

**Comment by fabeschan** [comment]
This might help https://github.com/codalab/codalab-worksheets/issues/359
