### ISSUE TITLE
More disk space for evaluating T5-3B

### ISSUE THREAD

**Issue by longxudou** [codalab/codalab-worksheets#4071]
**Describe the bug**
I am evaluating the T5-3B and meet the same `kill` problem as [this issue](https://github.com/codalab/codalab-worksheets/issues/4055), could you please spare more disk space for the following worksheet.

**Codalab Information**
- *Your username*: longxud
- *UUID of worksheet where problem occurred*:
- https://worksheets.codalab.org/worksheets/0xb2ec1d7b42b740c98404622e003869ac
- https://worksheets.codalab.org/worksheets/0xf0d7378d020846ae85054c7b508be66b
- https://worksheets.codalab.org/worksheets/0x5582d07c522e4033b37daa4d8a3c9b47

Here are the worksheet for three tasks. I need to download the T5-3B model (10.6 gb) from huggingface (three times) and running evaluation on that.

Thanks you!

**Comment by longxudou** [comment]
Hi @epicfaace @teetone , if the space use is difficult to expand, you can just deal with https://worksheets.codalab.org/worksheets/0xb2ec1d7b42b740c98404622e003869ac . And I will reuse this worksheet for other two evaluations. The permission to `ADMIN` is open.

Add 10G to my account would be very helpful indeed.

Thanks in advance.

**Comment by epicfaace** [comment]
Sure, we have given you a 20GB disk quota.

**Comment by longxudou** [comment]
Thanks!
