### ISSUE TITLE
bypass codalab server for GCS blob storage uploads

### ISSUE THREAD

**Issue by wwwjn** [codalab/codalab-worksheets#4074]
Similar issue for bypass server download #3974.

Need to add support for bypass server when upload to Azure or GCS. 

Azure blob storage manager design: https://docs.google.com/document/d/1l4kOqi9irBjOApmn4E6vlzsjAXDJbetIyVw8gMRHrpU/edit#heading=h.vat4mpk6gcza

**Comment by pranavjain** [comment]
Blocked by #4201

**Comment by wwwjn** [comment]
09/30 Group meeting update: First test this branch on dev environment, benchmarking upload to GCS, then get it merged to master
