### ISSUE TITLE
`cl ls` ref number error when rerun a bundle using front end.

### ISSUE THREAD

**Issue by wwwjn** [codalab/codalab-worksheets#4075]
**Describe the bug**
When rerun some bundles at front end, the order and ref number of the new bundle is wrong.

**Codalab Information**
- *Your username*:
- *UUID of worksheet where problem occurred*:
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*: MacOS
 - *Codalab CLI Version (if on CLI)*:  1.4.6
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :
1. Use front-end first. Connect to a worksheet using front-end, create some new bundles by rerun some existing bundles. 
2. Change to use CLI. Run `cl ls`, list all the existing bundles and ref numbers
3. Run other `cl` commands using refer numbers, eg, `cl mimic ^1`
4. The ref number does not match in `cl ls` and other cl commands

**Screenshots**
The bundle `0x4ef9a9` and `0xf8485f` was created click rerun button at front-end. The latest bundle should not at the top of all the bundles
<img width="852" alt="image" src="https://user-images.githubusercontent.com/40016222/164947237-9d7d4088-ee7c-4829-90bf-91812d36375d.png">
The order of bundles in front end is also wrong. 
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/40016222/164947308-6e4bcb1b-7dd9-404d-bc15-a16b12b3f48c.png">

**Additional context**

**Comment by pranavjain** [comment]
@wwwjn Is this related to #3989? I feel that the root cause is the same.

**Comment by wwwjn** [comment]
Similar to #3989. Close this.
