### ISSUE TITLE
Prevent worker manager from launching more workers if there are pending ones in the Slurm queue.

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#4078]

**Comment by teetone** [comment]
Attempt to start a worker on jagpuard28, where we know the Slurm job will be stuck in `PENDING`:


`conda activate tonyhlee_codalab`
`cl-worker-manager --server https://worksheets.codalab.org  --worker-tag-exclusive --worker-tag nlp --min-workers 0 --min-seconds-between-workers 20 --sleep-time 10 --worker-max-work-dir-size 250g --max-workers 3 --worker-shared-memory-size-gb 8 --worker-work-dir-prefix /scr/scr-with-most-space/tonyhlee/error --worker-pass-down-termination --worker-exit-on-exception --worker-exit-after-num-runs 2 slurm-batch --partition jag-standard --cpus 4 --gpus 1 --memory-mb 50000 --password-file ~/.codalab/codalab-main.password --slurm-work-dir ~/scr/slurm_output/error --job-name codalab-slurm-worker-stanford-standard  --exclude jagupard10,jagupard11,jagupard12,jagupard13,jagupard14,jagupard15,jagupard16,jagupard17,jagupard18,jagupard19,jagupard20,jagupard21,jagupard22,jagupard23,jagupard24,jagupard25,jagupard26,jagupard27,jagupard29,jagupard30,jagupard31`

Slurm job for the worker is stuck in PENDING. 

Rerun the above command. Notice that the worker manager will not launch a new worker:

```
2022-07-04 12:43:33,365 Workers: 3846460
2022-07-04 12:43:33,400 1 staged bundles (0 removed since last time), 1 worker jobs (min=0, max=3) (0 active, 1 pending)
2022-07-04 12:43:33,400 Want to launch a worker because we have 1 > 0 staged bundles
2022-07-04 12:43:33,400 Don't launch because still more pending workers than staged bundles (1 >= 1)
```

We already have [logic to check to check for PENDING Slurm jobs](https://github.com/codalab/codalab-worksheets/blob/master/codalab/worker_manager/slurm_batch_worker_manager.py#L196).

**Comment by pranavjain** [comment]
@pranavjain To Repro
