### ISSUE TITLE
Design how to support TPUs

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#4083]
Our workers are compatible with Nvidia GPUs but not TPUs. We need to design a way to support both.

https://cloud.google.com/tpu/docs
https://trisongz.medium.com/accessing-your-tpus-in-docker-containers-with-tpu-vm-e944f5909dd4

**Comment by pranavjain** [comment]
Is this an urgent requirement blocking a user? Do we need p1 for this?

**Comment by percyliang** [comment]
Out of scope for now.
