### ISSUE TITLE
Improve STDOUT for users

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#4084]
Currently, a user has to wait several minutes before seeing an output. Improve STDOUT logic to display output instantly, like in real-life code debugging. We tried to solve this earlier via #4023

**Comment by pranavjain** [comment]
@percyliang Do we still want to do this given that #3975 would solve it for most of the users (other than NLP Slurm Users)?

**Comment by pranavjain** [comment]
We realized during the demo that #3975 wouldn't solve the issue directly and we would need some changes for the STDOUT to read not from the file but directly from Kubernetes output.

**Comment by percyliang** [comment]
I think we need to not just be able to read out stdout, but any file in real time from a worker (which could be be on any machine, including ad-hoc workers).

**Comment by epicfaace** [comment]
Here's how we can fix this:

Replace the worker check-in / messaging mechanism (which depends on polling) to instead communicate messages over a websocket between the server and worker. This would make server-worker communication nearly instantaneous and not take 5-20 seconds per message. This would entail:
- the server would maintain a websocket for each worker
- **server side**: in worker_model.py, change `send_json_message` and `get_json_message` to instead read / write from the server-worker websocket. (Currently, these methods write to a socket, which is sent to the worker only upon check-in)
- **worker side**: in worker.py, replace `self.checkin` with just some event-based code that listens to the websocket, and upon message receipt, lets workers handle the message instead.

This would be a surgical solution that significantly changes the way workers / servers operate, but hopefully it would be self-contained enough to allow us to use the same APIs (send_json_message, etc.) to send / receive messages. I think I understand the worker-server communication logic enough to be able to take this on, if we agree on this approach.

**Comment by percyliang** [comment]
This sounds a lot cleaner!

I'm curious: if I'm downloading a large file from the worker through the server, can I still get a quick request about stdout and have the run status automatically update?

**Comment by pranavjain** [comment]
Code cleaning is in progress before the final review.

**Comment by leilenah** [comment]
@AndrewJGaut look @ Ashwin's PR for this. May be helpful.

**Comment by leilenah** [comment]
TODO: Ashwin review PR
