### ISSUE TITLE
Codalab working on Ubuntu 16.04 or CentOS 7

### ISSUE THREAD

**Issue by RogerXT** [codalab/codalab-worksheets#409]
I tried to setup Codalab on Ubuntu 14.04, it finally worked. Actually I am trying to setup Codalab on the server in our own lab, which is running Cent OS7. 

BTW, when I was creating initial worksheets, I was requested access at https://worksheets.codalab.org
not localhost. I don't know whether this was right. I am not able to create the public home worksheet. And when I ran my script, the status was staged and I didn't get the results. But I can run the script with root user. Maybe we can just share the root user.

Previously I was trying to setup Codalab on Ubuntu 16.04. The last necessary step, starting a worker, I got this error:
![screenshot from 2018-02-08 12-08-23](https://user-images.githubusercontent.com/11673650/36057652-a6ca207a-0dc5-11e8-88dc-18b4b78d62d9.png)

I'd be really very appreciated if you can just have a try on CentOS 7 or Ubuntu 16.04 and update the tutorial. I'll continue to find solutions to make Codalab work on CentOS 7.
Codalab is a powerful platform. I hope it can play an important role in our research.

**Comment by fabeschan** [comment]
We have been using Ubuntu 16.04 on our production servers for a while now. See:

https://github.com/codalab/codalab-worksheets/blob/master/Dockerfile
https://github.com/codalab/codalab-cli/blob/master/Dockerfile.server
https://github.com/codalab/codalab-cli/blob/master/Dockerfile.worker
