### ISSUE TITLE
RuntimeError: cannot release un-acquired lock

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4092]
@teetone I think this might be a quick fix. I noticed this error when I ran several workers through kubernetes on my local computer.

![image](https://user-images.githubusercontent.com/1689183/166130121-42640759-883f-477c-99d8-d11d22f5c0a2.png)

**Comment by percyliang** [comment]
Waiting for Kubernetes.

**Comment by epicfaace** [comment]
Showing up on sentry as well: https://sentry.io/organizations/codalab/issues/2992373860/?project=5383515&referrer=weekly-email
