### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by Shuailong** [codalab/codalab-worksheets#4097]
Hi, I am not sure whether here is the best place to contact the Codalab admin, but I did not find any contact info on the website.

I have registered Codalab account several years ago, and now would like to delete the account as well as some sensitive data. However, when there's some bundles in my account so I cannot delete my account. I tried to delete the bundle, but the UI disable the delete button, which indicates that I don't have persmission to delete it. Could you help me delete all the bundles in my account and delete my account as well?

If it's possible I will send my account info in following emails.

Regards,

Shuailong

**Comment by epicfaace** [comment]
Hi, what is your username and which bundles do you want deleted? Please send the information to codalab.worksheets@gmail.com.

**Comment by percyliang** [comment]
You can use `cl ufarewell` to delete your account.  Please re-open this issue if you still need help.
