### ISSUE TITLE
Web terminal doesn't initialize if app loaded when window was too small

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#41]
<a href="https://github.com/kashizui"><img src="https://avatars.githubusercontent.com/u/614837?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kashizui](https://github.com/kashizui)**
_Wednesday Dec 09, 2015 at 23:51 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1496_

---

If the window is too narrow (and thus displays in tablet/smartphone mode) when the worksheet interface is loaded, the web terminal does not work even after we expand the window again.

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1089
