### ISSUE TITLE
Compute on another computer

### ISSUE THREAD

**Issue by RogerXT** [codalab/codalab-worksheets#410]
Can we do all the computation on another computer? For example, there's no NVIDIA GPU on computer A. I want to host all the CodaLab files on computer A and compute on computer B which has an NVIDIA GPU.

Thanks a lot!

**Comment by fabeschan** [comment]
You can set up computer B as a worker. Then your run bundles can run on worker B.

**Comment by RogerXT** [comment]
Thank you. I will try.

**Comment by RogerXT** [comment]
Hi, I have a little question. Where can I change the ip address of API service? For example, from 127.0.0.1:2900 to 0.0.0.0:2900.
