### ISSUE TITLE
codalab.stanford.edu web CLI broken

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4105]
<img width="537" alt="image" src="https://user-images.githubusercontent.com/1689183/168888397-d495f9e7-349c-4077-9a8c-d2b5b5298672.png">

<img width="485" alt="image" src="https://user-images.githubusercontent.com/1689183/168888466-0c1ff5a5-951a-4927-bae6-b971c612e157.png">

**Comment by pranavjain** [comment]
Did we change anything recently related to this?

**Comment by pranavjain** [comment]
No more repro.
