### ISSUE TITLE
Improve run_status: upload "147 done" should render bytes properly

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#4114]

**Comment by leilenah** [comment]
### Investigation
* Issue is likely with this line https://github.com/codalab/codalab-worksheets/blob/master/codalab/worker/worker_run_state.py#L692

https://user-images.githubusercontent.com/25855750/177217860-b50970fd-03b8-402e-a20e-9dae03d39a5d.mov

**Comment by leilenah** [comment]
Issue pending more clarification from @pranavjain (via Slack)

**Comment by pranavjain** [comment]
New Bug: Modify the size string to add a flag to include bytes if needed.

**Comment by percyliang** [comment]
Add `include_bytes=True` as a argument to `size_str`.

**Comment by leilenah** [comment]
### Notes
* kilobyte - 1024 bytes
* megabyte - 1024 kilobytes 
* gigabyte - 1024 megabytes
* terabyte - 1024 gigabytes

```
def size_str(size, include_bytes):
    for unit in ('', 'k', 'm', 'g', 't'):
        if size < 100 and size != int(size):
            return '%.1f%s' % (size, unit)
        if size < 1024:
            return '%d%s' % (size, unit)
        size /= 1024.0
```

**Comment by leilenah** [comment]
@pranavjain I ended up just re-opening this. No need to create a new bug since it should be a small update.
