### ISSUE TITLE
Put a (info) icon next to the state, tooltip shows a brief description and clicking goes to the full documentation.

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#4116]

**Comment by leilenah** [comment]
### Implementation
1. ~~Choose tooltip from Material UI~~
2. ~~Add documentation to user docs~~
3. ~~Create shared tooltip~~
5. ~~Add state tooltip to Dashboard View~~
6. ~~Add state tooltip to Worksheet View~~
7. ~~Add state tooltip to Bundle View~~
9. ~~Run pre-commit script~~

### Research
1. ~~Find an existing tooltip on the site~~
1. ~~Determine all the locations where the state is shown to the user~~
1. ~~Find out where the state documentation is~~

### Notes
* Slack Convo: https://codalab.slack.com/archives/C09ULEJAV/p1642461378000400
* Ashwin Notes
    * not all bundles go through the "MAKING" state, only bundles made using "cl make" do so
    * bundles that are make bundles go directly from MAKING -> READY / FAILED
    * Otherwise, MAKING is not part of the regular bundle lifecycle
* Existing tooltip: worksheet view shortcut icon: https://worksheets.codalab.org/worksheets/0x9014b735b2ff4dbe9e2328b8c54053b6
* State Locations:
    1. Dashboard View
    11. Worksheet View
    12. Bundle View
* States are defined in the code: https://github.com/codalab/codalab-worksheets/blob/178fa23ecfa5061830d06107e4bb5ba6cc9d69d6/codalab/worker/bundle_state.py
* Bundles in WORKER_OFFLINE state can be moved back to the RUNNING or PREPARING state if a worker resumes the bundle indicating that it's still in one of those states.

![CODALAB (1)](https://user-images.githubusercontent.com/25855750/174462672-107642e1-3d2a-41be-b2a1-bc22f6b420db.jpg)

**Comment by leilenah** [comment]
### Separate Issues 

 1. https://github.com/codalab/codalab-worksheets/issues/4131
 2. https://github.com/codalab/codalab-worksheets/issues/4132
3. https://github.com/codalab/codalab-worksheets/issues/4133

**Comment by leilenah** [comment]
### Percy Notes

![Screen Shot 2022-06-30 at 1 22 24 PM](https://user-images.githubusercontent.com/25855750/176771667-b89affd1-d2f0-4232-b7ae-f4f961dc830b.png)

* state and run status are different
* the run status is a refinement of the actual states 
* the user sees both states and run statuses
* state and run status could be redundant
    * note that run status is currently in prod
* Merge run status with description
* If run status is telling us something new, we should figure out how to display it
* but we want to reduce redundancy 
* bundle view can be improved
* keep the CLI in mind `cl info`
* CL info can be refined
     * remove redundancies
* the sidebar and bundle view should be consistent
* Look into the fields and determine how to display
    * e.g. "requests" vs "time"
    * want the bundle view to be consistent with the sidebar

**Comment by leilenah** [comment]
### Refactors
1. ~~Update tooltip UI to use downward arrows~~
2. ~~Indicate current state~~
6. ~~Send bundle state details with `bundleInfo` from backend~~
1. ~~Remove run status~~
5. ~~Handle staged_status~~
7. ~~Move state next to info icon (keep details below)~~
9. ~~Add documentation~~
8. ~~Add unit tests for `get_bundle_state_details` util~~
9. ~~Move docs to Concepts~~
10. ~~Rename to "lifecycle of a bundle"~~
11. ~~fix margin for current state~~
12. ~~Re-add in flow chart to documentation~~
13. ~~Add screen recording of running bundle~~

### Alternatives
1. Move `state_details` into bundle `metadata`.
2. Update `state_details` dynamically as bundles move through each state.

**Comment by pranavjain** [comment]
![Image](https://user-images.githubusercontent.com/10134824/177631611-0bf9dc44-cb5e-4f63-9d82-3cc1b029d28f.png)

Add a new page under concepts -> Lifecycle of a Bundle
