### ISSUE TITLE
Codalab workers deployment on Grid Computing Environment

### ISSUE THREAD

**Issue by thammegowda** [codalab/codalab-worksheets#412]
Could you please share more details of how the codalab workers were modified to work on systems like computing grids? The worker design doc states that codalab.stanford.edu is based on TORQUE(correct me if I am wrong, I assume it is a shared grid computing environment)

---
Right now, we have a dedicated node to run webapp, REST api and bundle server. We just want to move workers to the nodes in grid.
Our grid has Portable Batch System (PBS) where I request (CPU and GPU) resources using `qsub`. 

1. Any suggestions/thoughts on how to make workers run in a distributed fashion, on-demand (i.e. request resources from grid's job scheduler, launch worker, and release the resources back when job is done). [Seems like the codalab.stanford.edu has a similar deployment](https://github.com/codalab/codalab-worksheets/wiki/worker-design.pdf) . 
2. Additionally, I want to do run the jobs without using Docker (because we are unhappy about the [docker daemon attack surface](https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface)). We have a shared FS that has same view across grid nodes (so download, upload not needed). I wont have too many different kinds of pipelines or worksheet, so, worksheets can assume all requirements are pre-setup. This is for the future step, doing step 1 is necessary for now, but just showing what might happen next.

Thanks,

**Comment by percyliang** [comment]
At Stanford, we use Torque (which itself is flaky), which can be turned on by adding ```"workers": {
        "default_docker_image": "codalab/ubuntu:1.9",
        "shared_file_system": true,
        "torque": {
            "bundle_service_url": "...",
            "log_dir": "...",
            "min_seconds_between_qsub": 10,
            "password_file": "...",
            "ssh_host": "<where to ssh to run job>"
        }
    }
}```
But if you have a different setup, you might have to change the code to make it work.  We might deprecate this stuff anyway, since it's pretty flaky.

I'd probably recommend just running a bunch of `cl-worker` jobs manually on a bunch of your machines.

**Comment by thammegowda** [comment]
Thank you very much for sharing the config and recommendation. I will try this setting, and make any changes to the code if necessary.
