### ISSUE TITLE
Why my running bundle is killed?

### ISSUE THREAD

**Issue by JiexingQi** [codalab/codalab-worksheets#4123]
**Describe the bug**
I'm running evaluation in codalab and use the t5-3b model, but the GPU provided in codalab is not suitable to load it and I have to run it in CPU in codalab. However, it may take a long time to run, but I find that my running bundle is killed when a long time run.  And this occurs in many times in my running. What is the problem with it? How can I avoid it?

**Codalab Information**
- *Your username*: jxqi
- *UUID of worksheet where problem occurred*:https://worksheets.codalab.org/worksheets/0x676b3834abe642d684b99d0981927388
- *UUID of problem bundle (please don't delete)*:[0x21f3bf](https://worksheets.codalab.org/bundles/0x21f3bf208a9c421ba90504fb5e203524) and https://worksheets.codalab.org/bundles/0x46666881ffa5454f8b8224939618835f
- *Error message received from Codalab (if applicable)*:

```
 27%|██▋       | 221/813 [3:35:10<12:26:48, 75.69s/it]
 27%|██▋       | 222/813 [3:36:23<12:18:24, 74.96s/it]
 27%|██▋       | 223/813 [3:36:59<10:20:37, 63.11s/it]
 28%|██▊       | 224/813 [3:39:04<13:22:04, 81.71s/it]
 28%|██▊       | 225/813 [3:41:09<15:28:05, 94.70s/it]
 28%|██▊       | 226/813 [3:43:19<17:10:34, 105.34s/it]run_sparc_prediction_t5_3b_5696_beam_12.sh: line 35:    46 Killed                  CUDA_VISIBLE_DEVICES="-1" python3 /app/seq2seq/eval_run_seq2seq.py /app/configs/eval_t5_3b_5696_sparc_beam_12.json
cp: cannot stat '/eval/predicted_sql.txt': No such file or directory

```

 - *OS (if on CLI)*: Ubuntu 18.04 LTS
 - *Codalab CLI Version (if on CLI)*:  1.5.3
 - *Browser (if on Web)*; Chrome

**Comment by JiexingQi** [comment]
I try to use request-time=20h but it dosen't work. My running bundle still be killed.

**Comment by JiexingQi** [comment]
Hi, @epicfaace , @teetone ,can you help me with this problem? What is meaning for 

```

46 killed
```
Thanks a lot.

**Comment by epicfaace** [comment]
@JiexingQi Maybe it ran out of memory?

**Comment by JiexingQi** [comment]
@epicfaace Thanks a lot. This is indeed the reason why it was killed. By the way, I wonder the max memory a user can request? Maybe it is 54G? When I request more than 54G, my bundle will be staged? How can I request a larger memory without being staged? Could you kindly provide me with some suggestions? Thanks again.

**Comment by epicfaace** [comment]
Perhaps, it might be 54G, though I'm not sure. There's no way to increase the max because we have certain VMs with a pre-set amount of memory running as workers.

**Comment by JiexingQi** [comment]
Well, I got it. Thanks a lot, @epicfaace
