### ISSUE TITLE
output file missing

### ISSUE THREAD

**Issue by sunmeng01** [codalab/codalab-worksheets#413]
I have run a same bundle several times,  all were normal except one. The failure bundle state is 'ready', however, can not find the output file. The failure bundle metadata run_status was 'Uploading results: 16k done (archived size)', and the successful bundles   metadata run_status were 'Finished'.

**Comment by bkgoksel** [comment]
How big is the output of the bundle? 
We have a known bug where run bundles that output more than 4gb of data sometimes have problems uploading their results, getting stuck in the 'Uploading results' stage you described. We're actively working on a fix.

**Comment by sunmeng01** [comment]
The log of the bundle is about 7k, and the output is 524k. 
the snippet of code is:
`logger.info('Writing results to %s' % out_file)
with open(out_file, 'w') as f:
    json.dump(results, f)
logger.info('Total time: %.2f' % (time.time() - t0))
`
the out_file is about 524k, I saw both the first log "Writing results to ..." and last log "Total time ..." , but can not find the output file.

**Comment by w0nche0l** [comment]
@sunmeng01 , is the worksheet where you did this public? If so, could you include a link?

**Comment by sunmeng01** [comment]
@w0nche0l sorry, the worksheet is missing......

**Comment by percyliang** [comment]
Closing for now, please re-open if it is an issue.
