### ISSUE TITLE
Optimize Bundle `cl info` output in CLI

### ISSUE THREAD

**Issue by leilenah** [codalab/codalab-worksheets#4133]
### Implementation
- [x] Remove `:` from print
- [x] Update run bundle groupings to match detail sidebar
- [x] Update uploaded bundle groupings to match detail sidebar
- [x] Update make bundle groupings to match detail sidebar
- [x] Ensure that arguments passed in still function as expected
    * -f, --field
    * -r, --raw
    * -v, --verbose
    * -w, --worksheet-spec
- [x] Ensure that headless client is not impacted
- [x] Delete unused print code
- [x] Code docs
- [x] Update CLI tests

**Comment by leilenah** [comment]
### Research 
![image](https://user-images.githubusercontent.com/25855750/180893398-689b332e-459d-4fae-ba3f-ca4691e0ef64.png)

**Comment by pranavjain** [comment]
Not pursuing this right now.
