### ISSUE TITLE
Fix `staged_status` and add it to bundle state details

### ISSUE THREAD

**Issue by leilenah** [codalab/codalab-worksheets#4139]
### Implementation
- [x] Remove `staged` from `get_bundle_state_details()`
- [x] Update `get_bundle_state_details()` to return `staged_status` when the bundle is `staged`
- [x] Show generic `staged_status` when we transition to `staged`
    * "Bundle’s dependencies are all ready. Waiting for the bundle to be assigned to a worker to be run."
- [x] If we found an optimal worker for the bundle, update `staged_status` to reflect this
- [x] Comb through `_filter_and_sort_workers()` and update `staged_status` where applicable
- [x] Write `_generate_resource_recommendations` tests
- [x] Update `_filter_and_sort_workers()` tests
- [x] Update `get_bundle_state_details()` tests
- [x] QA

### Overview

`staged_status` isn't consistently getting added to bundle metadata. We need to figure out why that is occurring, resolve the issue. We also need to show `staged_status` to users as part of `state_details`.

### Acceptance Criteria
1. `staged_status` is present whenever a bundle is in a `staged` state
2. staged statuses are clear and accurate
3. `state_details` reflects `staged_status` when a bundle is in `staged` state
    * this logic will be similar to how we show `run_status` when a bundle is `running`
    * see `get_bundle_state_details` helper in `bundle_util.py` 

### Related Issue
https://github.com/codalab/codalab-worksheets/issues/4116

### Related PR
https://github.com/codalab/codalab-worksheets/pull/4127

**Comment by leilenah** [comment]
### Notes

#### Notes from @percyliang 
Staged status should show up when we don't have enough resources to run a job (you might be able to do `cl run --request-gpus 10` or something to trigger). This is pretty important to see show up.

**Comment by leilenah** [comment]
@pranavjain heads up, this has been added to the User Experience milestone.

**Comment by epicfaace** [comment]
See https://github.com/codalab/codalab-worksheets/blob/master/codalab/server/bundle_manager.py#L378

**Comment by epicfaace** [comment]
See https://github.com/codalab/codalab-worksheets/blob/f377d24b16ebaba1b5c205dfa29ad8fc028970a3/codalab/server/bundle_manager.py#L556:
- for each filtering function, if the list is empty, then append a message to staged_status (i.e., cpus not sufficient)

Possible messages:
- No workers with the desired (tag, CPUs, GPUs, memory, disk space, availability) exist. You requested ("",5,5,0,0,1) but the following are available: ("",4,1,0,0,1) ("",1,4,0,0,1).

algorithm:
- find workers >= all dimensions for the job, if exists, you're good
- for workers <= requested, pick workers highest along this strict ordering

**Comment by leilenah** [comment]
Sample `worker_list`
```
[   {   'checkin_time': datetime.datetime(2022, 8, 30, 21, 41, 46),
        'cpus': 4,
        'dependencies': [   ('0x21e4e887dda2446ea408bba59178d1cb', ''),
                            ('0x653a09be2ec64ee6a886a81936e6c029', ''),
                            ('0x5bbc6130647047bb90e8dee6c2b2911a', ''),
                            ('0x90cfc8fece4f4d849c61200e4c7086d2', ''),
                            ('0xe15a4c6a79604081848f957b0ae07c22', ''),
                            ('0xda83739ddbbd41a9b7ef52234b72959b', ''),
                            ('0xd8ab892363dd4ff99b96be63d8d22fa0', ''),
                            ('0x9cdbe44f06cc410982f78f61178ea395', ''),
                            ('0x1fc2c39f928c40939d89f6825345bc63', ''),
                            ('0xb6b8c27ce3d0440eb640be4dfd2f5e7e', ''),
                            ('0x3623a67dbe614b38b7ede20e2da87bd3', ''),
                            ('0xc29fb637bd8b424291f7f8e4d55eb4e5', '')],
        'exit_after_num_runs': 999999999,
        'free_disk_bytes': 310985338880,
        'gpus': 0,
        'group_uuid': None,
        'has_gpus': False,
        'is_terminating': False,
        'memory_bytes': 2082197504,
        'preemptible': False,
        'run_uuids': [],
        'shared_file_system': False,
        'socket_id': 4187,
        'tag': None,
        'tag_exclusive': False,
        'user_id': '0',
        'worker_id': 'Leilenahs-MacBook-Air.local'}
]
```

**Comment by leilenah** [comment]
### Meeting Notes
- it's important that the user sees the full context of which resources aren't available
- the resource list is subject to grow over time
- it may be useful to create a class that encapsulates the resources
- we should only present the user the fields that they have violated when showing them worker recommendations.

**Comment by leilenah** [comment]
### Refactors
- [x] Create `Resource` dataclass (see Percy notes below)
- [x] Handle request_queue logic as part of resources
    * Need to update in two places
- [x] Don't need to copy workers_list; better to make the subsequent logic immutable.
- [x] Remove defensive check from `_set_staged_status` OR add `staged_status` to make bundle metadata
    * confirm that this function is only ever called for run bundles (it looks like some make bundles get staged as well)
- [x] Make resource recommendations easier to read (tuple format isn't great)
- [x] Show the `tag` field when recommending workers
    * tag determines which queue a run is on 
    * the tag of the worker corresponds to `--request-queue` on the job
- [x] Make sure post-filter sorting still functions as expected
- [x] Add type annotations to everything
- [x] Are there workers with exit_after_num_runs = 0? This shouldn't be the case?
- [x] Update code docs
    * in one section we say that we return a tuple but we actually return a string
- [x] Update tests
- [x] Investigate `socket error when calling send_json_message`
- [x] QA
- [x] Resolve comments

### Notes from Percy
I think it would be helpful first to define a dataclass Resource which has cpus, gpus, memory, disk, queue. Then each worker object can be converted into a Resource and the bundle we're trying to schedule can be converted into a Resource. Then we can define a function def dominates(self, other: Resource) which returns True if each dimension (cpus, gpus, etc.) for self is at least as great as other. Then,

1. We compute the list of feasible workers (those that dominate the bundle). If this is non-empty, we're done.
2. If not, then we take all the workers and keep only those workers that aren't dominated by another worker. For each of these potential workers, we generate a string (worker_resource.render_shortcomings(bundle_resource)) which lists all the dimensions where worker_resource falls short. For example, if worker_resource has gpus=2 and bundle_resource has gpus=4, then we'd generate something like "2 GPUs (4 requested)". So then the final staged status would be something like "Insufficient resources, but the following workers are available: ...".
