### ISSUE TITLE
Dev environment upload to Azure connection timeout

### ISSUE THREAD

**Issue by wwwjn** [codalab/codalab-worksheets#4149]
**Describe the bug**
When using dev environment upload large files, it will give connection time out. Please see 3:29 in the following video.
```
azure.core.exceptions.ServiceResponseError: ('Connection aborted.', timeout('The write operation timed out'))
```

https://user-images.githubusercontent.com/40016222/179626844-6adb941e-118c-474c-9da2-956c403b290c.mov

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by teetone** [comment]
Does this happen from `scdt` (ssh scdt)?

**Comment by wwwjn** [comment]
> 

It also happens from my PC when uploading to Azure. I think it's a common problem. And it happens sometimes, and uploads success other times. 
Related issue: https://github.com/Azure/azure-sdk-for-python/issues/12166

This is because "sometime the first put blob request cannot finish within the specified/default timeout value". Since we are using Apache Beam, I'm trying to find corresponding parameters to fix this.

**Comment by pranavjain** [comment]
Jiani will deploy to dev env. today and run the test.

**Comment by pranavjain** [comment]
@wwwjn to share the PR with Ashwin for review.
