### ISSUE TITLE
Bundle page fixes

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4153]
<img width="302" alt="image" src="https://user-images.githubusercontent.com/1689183/180062343-72923170-5628-4a30-bda8-e150bd67dfdc.png">

**Comment by epicfaace** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/1689183/180062439-14ebd1fb-305e-46a2-8958-a8f92f4e4db1.png">

**Comment by epicfaace** [comment]
Make "bundle page" a more prominent button at the bottom 

<img width="337" alt="image" src="https://user-images.githubusercontent.com/1689183/180062530-dbba2b50-a1d5-4301-ad73-716bd006cc45.png">

**Comment by epicfaace** [comment]
Reduce flashing

**Comment by epicfaace** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/1689183/180063178-7a1f3e63-dd44-4cfd-a3e8-9dbcc0bfafd6.png">

Add a navbar to the top showing which folder / path you're on

**Comment by leilenah** [comment]
Will address as part of https://github.com/codalab/codalab-worksheets/issues/4131
