### ISSUE TITLE
Benchmarking blob storage upload tests

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4154]

**Comment by wwwjn** [comment]
The test result is in the`test` part. https://docs.google.com/document/d/1qFT6OWSUW5-2ZfnkK_q6P-Q-9sVe_fyBLX3UfEIWRiY/edit?pli=1#heading=h.nzsd7jt9zuoh

Issue: The generate index process is really slow.

**Comment by wwwjn** [comment]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/40016222/182766689-7a5a3cfd-b8f8-4ebb-a91d-17ed6ea8c5c9.png">
