### ISSUE TITLE
Values of `Permissions` overlap `Created` in Bundle View page

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#4165]
https://worksheets.codalab.org/bundles/0x5739deb8cdc94a978dd692203d17c358

![Screen Shot 2022-07-27 at 3 40 59 PM](https://user-images.githubusercontent.com/16793796/181385022-5c0cfcb7-7cb0-47a2-a0ef-663e2c32477a.png)

**Comment by leilenah** [comment]
@teetone I have fixed this in the scope of this ticket https://github.com/codalab/codalab-worksheets/issues/4169
will close this one out.
