### ISSUE TITLE
`remote` field missing in Bundle View page

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#4166]
We used to be able to see which worker the bundle was running on (`remote`). I can't seem to find it anymore.

https://worksheets.codalab.org/bundles/0x5739deb8cdc94a978dd692203d17c358

**Comment by teetone** [comment]
@pranavjain I think we should prioritize. I miss seeing the value for `remote`.

**Comment by percyliang** [comment]
cc @leilenah This should be easy to add back.
