### ISSUE TITLE
bash: line 1: 7 Killed

### ISSUE THREAD

**Issue by sunmeng01** [codalab/codalab-worksheets#417]
A bundle could run successfully for many times about one month ago, however, the same bundle running on the same worksheet was always failed today. And the failure_message was:
bash: line 1: 7 Killed ( python src/train.py ) > stdout 2> stderr

**Comment by sunmeng01** [comment]
Is the default memory allocated of bundle decreased?

**Comment by bkgoksel** [comment]
Hi sunmeng, as of version 0.2.25, we started defining particular memory limits for every job. (default being 2GB) Prior to this change, jobs with no specified memory limits would be given access to the entire memory of the machine they run on, but we wanted to prevent people's jobs from cannibalizing others'. 
You can manually request more memory with the  `--request-memory <memory>g` flag. This flag works on commands like `run`, `mimic`, `macro` etc.
We're working on fixing the error message so it's more apparent this is what's happening.

**Comment by bkgoksel** [comment]
Closing the issue as we already have [https://github.com/codalab/codalab-cli/issues/887](this issue) to track fixing the error message.

**Comment by sunmeng01** [comment]
@bkgoksel Thanks!
