### ISSUE TITLE
[CLI] cl work tab key doesn't auto complete

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#4172]

**Comment by leilenah** [comment]
@pranavjain can you please provide more detail on the expected behavior?

**Comment by percyliang** [comment]
For example, if you type `cl work pliang-` and then hit tab, nothing happens.  It should produce a list of options if there are more than 1 or autocomplete if there is 1.

**Comment by leilenah** [comment]
@percyliang did this used to work before, but then it broke? Or is this a completely new feature?

**Comment by percyliang** [comment]
It used to work (though perhaps not fully) a long time ago.

**Comment by leilenah** [comment]
Reference: https://github.com/codalab/codalab-worksheets/blob/master/codalab/lib/completers.py

**Comment by leilenah** [comment]
**Meeting Notes**
- allow this for all commands, not just `cl work`

**Comment by leilenah** [comment]
**Dev Notes:**
* Marking as blocked for now, need to discuss the findings below with team 
* Worrisome comment from 4 years ago: https://github.com/codalab/codalab-worksheets/blob/master/codalab/lib/completers.py#L132-L135
* Old issue that was closed: https://github.com/codalab/codalab-worksheets/issues/223

**Comment by leilenah** [comment]
Setting this to p3 for now, and removing from fall goals.

Per this older issue https://github.com/codalab/codalab-worksheets/issues/223https://github.com/codalab/codalab-worksheets/issues/223 

It appears that a custom autocomplete solution may be required.
