### ISSUE TITLE
DELETE Bundle UI Issues

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#4176]
- When deleting a bundle via UI, delete takes a long time (10+ sec) to process
- While delete is in process, a random bundle is removed temporarily from UI, and a copy of another bundle is created.

There is not a 100% repro of the above cases.

Recording of one repro (Restricted to team members): https://drive.google.com/file/d/1s2Z_UTaoJ8YdcxRDy501fv57hUJwRJZv/view?usp=sharing

**Comment by leilenah** [comment]
### Investigation

**Worksheet:** https://codalab.stanford.edu/worksheets/0x9e16b0fe372c4b49bcf2004a4c020da0

**Repro:**

https://user-images.githubusercontent.com/25855750/189775113-84186f76-26d0-4971-bd8e-00bf6012a9c0.mp4

**Notes:**
- Looks like this happens during `executeCommand()` 
- once the bundle is deleted, the worksheet is reloaded correctly
- potential fix is to ensure that worksheet state is locked until `executeCommand()`  completes
- could potentially freeze worksheet reloads during delete
