### ISSUE TITLE
Show status of PREPARING

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#4186]
We used to display why a bundle was preparing: downloading dependency, downloading docker image, etc.

I don't see this information anymore on the Bundle View page.

**Comment by teetone** [comment]
@pranavjain @leilenah  can you try it out?

**Comment by leilenah** [comment]
@teetone Now you have to hover over the colored state box to see the specific state details. This isn't great. I'll figure out a way to show this elsewhere.

**Comment by leilenah** [comment]
### Meeting Notes
* This information should already be present in `run_status`
* The only reason it's not showing up is when using a cached image
* To test, use an uncached image
