### ISSUE TITLE
Maybe the nginx config template should be updated

### ISSUE THREAD

**Issue by RogerXT** [codalab/codalab-worksheets#419]
I am using CodaLab on my own machine.
When I click a worksheet's name in my dashboard or a bundle's uuid, I got an issue like this:
![selection_001](https://user-images.githubusercontent.com/11673650/39603300-b3ed4234-4edc-11e8-84c7-6ad8acba13be.png)
I added
proxy_set_header Host $host; 
after proxy_pass http://django/; in nginx config, and then issue resolved.
Maybe this should be added to the nginx config template, or maybe I did something wrong and this line is not necessary.

**Comment by percyliang** [comment]
We plan to make deployment much simpler (#404), so closing this.
