### ISSUE TITLE
More disk space to upload and run our model

### ISSUE THREAD

**Issue by lihaoyang-ruc** [codalab/codalab-worksheets#4190]
Hi,

I'm trying to upload and run our fine-tuned T5 model (about 11G)  in CodaLab. However, due to the disk space limitation (10G), I can't upload it to the server. (Same issue as #4055 and #4071)

I filled out the "disk quota request form" three days ago, but haven't received a reply. Can you assign me a 20G disk quota?

Thank you in advance for any help you might be able to provide.

**Here is some information.**
- _Username: seeklhy_
- _UUID of worksheet where problem occurred:_
- https://worksheets.codalab.org/worksheets/0xf3eae863f29947afb8c55a1f29c2192e

**Comment by epicfaace** [comment]
Thanks, we'll look into this shortly!

**Comment by lihaoyang-ruc** [comment]
Hello @epicfaace,

Thanks for your quick reply.

However, before investigating the issue with the "request form", could you please address the issue of my insufficient disk quota? Currently my disk quota is still 10G. 

<img width="337" alt="image" src="https://user-images.githubusercontent.com/45526716/183327324-6bdc47f3-4fe6-431a-97e4-8623bfa82f92.png">

We must submit our models to the leaderboard by tomorrow (Aug 9th) or we will miss an important experimental result in our paper.

Thanks! :)

**Comment by epicfaace** [comment]
Quota increased

**Comment by lihaoyang-ruc** [comment]
Thanks a million.
