### ISSUE TITLE
time and dependencies should be shown without having to click 'more detail'

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#4192]
Currently, you have to click 'more detail' to see time and dependencies.  Dependencies are special and can be shown closer to the top, although for some bundles, there could be a lot of dependencies, which could also make it bulky...

Time is currently grouped nicely with the other time that makes sense, so maybe we should leave that there, but put an additional timing next to the state or something?

In general, there is a complete verbose view where information is grouped accordingly (like right now), but the leaner, simpler view (less detail) should hit the basic things including time, dependencies, and remote (at least when the job is running).

**Comment by leilenah** [comment]
@percyliang when a bundle is `running`, `time` will be displayed right next to the `running` box in the bundle state diagram. Same with `preparing`.

As for deps, I can move those up 👍

**Comment by leilenah** [comment]
### Meeting Notes
* The amount of time it took to run the bundle should be with the top-level fields even after the bundle is done running
* `Total Time` is not an accurate label for `time` -- need to think of better label

**Comment by leilenah** [comment]
### Implementation
- [x] Re-name `Total Time` to something more appropriate
- [x] Determine which `time` field(s) merit being in the top-level view 
- [x] Move relevant `time` to top-level
- [x] get rid of `MoreDetail` component
- [x] Confirm run bundles
- [x] Confirm uploaded bundles
- [x] Confirm make bundles
- [x] Confirm logged out user
