### ISSUE TITLE
`search_bundles` is extremely slow

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#4196]
Even uploading an empty file (via `cl upload`) takes 38 seconds.

-----

codalab.stanford.edu:

- Creating bundle (create an entry in DB): 0.19s
- Checking bundle location logic: 0.01s
- Sending data through (tiny file): 0.0s
- Reading the response: 21.11s
    - Upload to bundle store: 0.01s
     - [Update disk metadata](https://github.com/codalab/codalab-worksheets/blob/master/codalab/model/bundle_model.py#L1097): 21.034s
            - [_get_disk_used](https://github.com/codalab/codalab-worksheets/blob/master/codalab/model/bundle_model.py#L2709) causes the slowness
- **Total time: 24.453s**

`search_bundles` is slow: https://github.com/codalab/codalab-worksheets/blob/1b27806a419950695d6cb57d00e5bbd9068c83af/codalab/model/bundle_model.py#L354

Example query:

```
SELECT sum(q2.num) AS sum_1
FROM (SELECT DISTINCT bundle.uuid AS uuid, bundle_metadata.metadata_value * :metadata_value_1 AS num
FROM bundle, bundle_metadata
WHERE bundle.uuid = bundle_metadata.bundle_uuid AND bundle_metadata.metadata_key = :metadata_key_1 AND bundle.owner_id = :owner_id_1 AND bundle.data_hash LIKE :data_hash_1 AND (bundle.owner_id = :owner_id_2 OR bundle.uuid IN (SELECT group_bundle_permission.object_uuid
FROM group_bundle_permission
WHERE (group_bundle_permission.group_uuid = :group_uuid_1 OR group_bundle_permission.group_uuid IN (SELECT user_group.group_uuid
FROM user_group
WHERE user_group.user_id = :user_id_1)) AND group_bundle_permission.permission >= :permission_1))) AS q2
2022-08-24 22:24:46,454 query: SELECT DISTINCT bundle.uuid, bundle.id
FROM bundle ORDER BY bundle.id * :id_1 DESC
 LIMIT :param_1 OFFSET :param_2
```

Nested subqueries are really slow.

**Comment by epicfaace** [comment]
We need to change it to use joins instead of subqueries.

```sql
select count(*) from bundle where bundle.uuid in (
   select bundle_uuid from bundle_metadata where metadata_key = "created" and metadata_value >= 1661149840
);

prod: 72 (29.86 sec)
stanford: ??? (times out)

select count(*) from bundle b inner join bundle_metadata bm 
    on b.uuid = bm.bundle_uuid
    where bm.metadata_key = "created" and bm.metadata_value >= 1661149840;

prod: 72 (1.58 sec)
stanford: 26 (4.88 sec)
```


This will drastically speed things up. This will also fix https://github.com/codalab/codalab-worksheets/issues/3787

**Comment by epicfaace** [comment]
Other notes about the size of the bundle / bundle metadata tables -- note that stanford has much larger tables:

```
select count(*) from bundle;

prod - 185653
stanford - 397672

select count(*) from bundle_metadata;

prod - 3046993
stanford - 10990914
```

**Comment by percyliang** [comment]
This is helpful!  One thing that was discussed a few years ago is to remove bundle_metadata and just add the fields as columns inside bundle.  This was not done in the past because we thought there might be a huge amount of metadata we didn't want to load, but I think this really hasn't been the case.  This would make many of our queries more direct.

**Comment by epicfaace** [comment]
> One thing that was discussed a few years ago is to remove bundle_metadata and just add the fields as columns inside bundle.

I think that would certainly be the best way to go long-term, but it might be a pretty involved migration -- so the easiest optimization for now would be to use joins instead of subqueries (as it seems it might get us all the way there to stop these queries from timing out).

**Comment by teetone** [comment]
Synced with @AndrewJGaut and @yifanmai on this issue. Andrew will look into converting subqueries to joins.
