### ISSUE TITLE
Improve the experience of having to restart backend docker containers during development

### ISSUE THREAD

**Issue by leilenah** [codalab/codalab-worksheets#4199]
Having to restart the backend docker containers during dev can be cumbersome. Is there a workaround for this? If not, is there room to make the builds faster?

**Comment by epicfaace** [comment]
See https://github.com/codalab/codalab-worksheets/issues/1182

**Comment by epicfaace** [comment]
Watch: https://github.com/codalab/codalab-worksheets/blob/master/docker_config/compose_files/docker-compose.dev.yml

dockerfiles: https://github.com/codalab/codalab-worksheets/blob/master/docker_config/dockerfiles/Dockerfile.server and https://github.com/codalab/codalab-worksheets/blob/master/docker_config/dockerfiles/Dockerfile.worker

**Comment by yifanmai** [comment]
Will take a look. This might just require changing the server file watch settings and docker folder mount settings.
