### ISSUE TITLE
Scrolling is erratic on mobile device

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#42]
<a href="https://github.com/kashizui"><img src="https://avatars.githubusercontent.com/u/614837?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kashizui](https://github.com/kashizui)**
_Thursday Dec 10, 2015 at 09:27 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1497_

---

Chrome on iOS

trying to scroll up sometimes pulls down the address bar instead (as if already reached the top of the page)

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1081
