### ISSUE TITLE
Create a view that pulls the answers to the questions in the on-call template

### ISSUE THREAD

**Issue by leilenah** [codalab/codalab-worksheets#4200]
Each on-call team member must answer a series of questions posed in the [On-Call template](https://docs.google.com/document/d/1DPnKwfpoLedf42PN7DM1jNV9xqyw8Uho-xmvuHgRPnE/edit#heading=h.xy65heetpwqp). We should create a view in Codalab that pulls the answers to these questions programmatically.

**Comment by pranavjain** [comment]
Things to look at:

- Sentry
- Monitor Script

**Comment by leilenah** [comment]
Blocked by https://github.com/codalab/codalab-worksheets/issues/4309

Holding off on this until the above investigation is complete.

**Comment by percyliang** [comment]
Closing for now, opting for a simpler solution.
