### ISSUE TITLE
Improve bundle view responsiveness

### ISSUE THREAD

**Issue by leilenah** [codalab/codalab-worksheets#4216]
### Implementation
- [x] Prevent horizontal scroll in `CodeSnippet`
- [x] Reduce `CodeSnippet` font size (potentially)
- [x] Improve bundle view responsiveness 
- [x] QA

**Comment by leilenah** [comment]
Sample Bundle
https://worksheets.codalab.org/bundles/0xb9b23f28450c49e6bc11428bc818e6df

**Comment by percyliang** [comment]
Also on this page, it looks like the stdout/stderr is too big so there's undesired horizontal scrolling.  I think we can reduce the font size on failure message, command, stdout, stderr.
