### ISSUE TITLE
[USER ISSUE] Bad request when creating bundles through REST API

### ISSUE THREAD

**Issue by hhexiy** [codalab/codalab-worksheets#4219]
**Describe the bug**
We have been using codalab worksheets to host a competition. Specifically, we adapted the competitiond.py script and it has been running smoothly. However, this week I can no longer run it to evaluate new submissions and it throws an HTTPError when creating bundles for the submission.

Specifically, when it opens the following url
`https://worksheets.codalab.org/rest/bundles?worksheet=0x1976df1c790b48c79eb8519c97d130dc&detached=1`

it throws:
`urllib.error.HTTPError: HTTP Error 500: Internal Server Error`

If I open it in the browser I get:
```
Error: 400 Bad Request

Sorry, the requested URL 'https://worksheets.codalab.org/rest/bundles?worksheet=0x1976df1c790b48c79eb8519c97d130dc&detached=1' caused an error:

Request must include either 'keywords' or 'specs' query parameter
```

**Codalab Information**
- *Your username*: hhe
- *UUID of worksheet where problem occurred*: 0x1976df1c790b48c79eb8519c97d130dc
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*: 
 - *OS (if on CLI)*: OSX
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :
1. git clone git@github.com:hhexiy/quac-eval.git
2. cd quac-eval
3. python competitiond.py lb-config.json lb.json -v

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by leilenah** [comment]
@hhexiy heads up, I'm currently investigating this, so you may see me poking around / creating bundles in your worksheet. I will clean up when I'm done.

In the meantime, are you able to add your specific steps to repro the bug under the `To Reproduce` section of this issue?

**Comment by leilenah** [comment]
@hhexiy it appears that your bundle was potentially deleted. Will investigate further to try to see what happened there.

![image](https://user-images.githubusercontent.com/25855750/185526798-6aae1fb4-f9c8-4d39-af26-e953820036dd.png)

**Comment by leilenah** [comment]
Actually I can see it when I log in as admin.

![image](https://user-images.githubusercontent.com/25855750/185527230-5cbd744a-c610-4a5b-9381-fbe45888d17e.png)

**Comment by hhexiy** [comment]
> @hhexiy heads up, I'm currently investigating this, so you may see me poking around / creating bundles in your worksheet. I will clean up when I'm done.
> 
> In the meantime, are you able to add your specific steps to repro the bug under the `To Reproduce` section of this issue?

I have updated the 'reproduce' steps. Thanks!

The competitiond.py is adapted from the one under `script`.

**Comment by leilenah** [comment]
@hhexiy this is the output that I see when I try to repro your issue: 

![image](https://user-images.githubusercontent.com/25855750/185698422-da4a4aa4-c8bd-4c15-a10f-6bc17cc5bad5.png)

What version of python are you using? Can you switch to **Python 3.7.13** and try again?

**Comment by leilenah** [comment]
@hhexiy following up -- please let me know if bumping your Python version made a difference.

**Comment by leilenah** [comment]
Closing this out, as it appears that the user is able to run their competition script now.

@hhexiy please reach out if you run into further issues :)
