### ISSUE TITLE
What is the right way to compile a package for use with project?

### ISSUE THREAD

**Issue by arunchaganty** [codalab/codalab-worksheets#422]
I am trying to upload an executable paper and my code depends on two external packages (METEOR and fasttext in particular). Both of these do not distribute executables and require you to compile them from source. Unfortunately, these produce errors because the git repo folders are read-only bundles.

How one should manage this (rather common) scenario?

Some options I can see are:
1. Bake these packages into the Docker image.
2. Upload the compiled executables and hope that it works on the target machine (which comes an associated question: how does one upload a file and preserve its executable permissions)
3. Change the source files to allow specification of a target output directory

## Reproducing the error for fastText
I have uploaded the fasttext repo onto CodaLab using `cl upload -g https://github.com/epfml/sent2vec.git`.

I then try to compile it using `cl run -t :sent2vec.git 'cd sent2vec.git; make'`, which gives me the following output:
```
c++ -pthread -std=c++0x -O3 -funroll-loops -c src/args.cc
Assembler messages:
Fatal error: can't create args.o: Read-only file system
make: *** [args.o] Error 1
```

## Reproducing the error for METEOR

I have uploaded the METEOR repo onto CodaLab using `cl upload -g https://github.com/cmu-mtlab/meteor.git`.

I then try to compile it using `cl run -t :meteor.git 'cd meteor.git; ant'`, which gives me the following output:
```
0x16900e65b20049188872a8dad94bc02b
Buildfile: /0x16900e65b20049188872a8dad94bc02b_dependencies/meteor.git/build.xml

init:

BUILD FAILED
/0x16900e65b20049188872a8dad94bc02b_dependencies/meteor.git/build.xml:10: Directory /0x16900e65b20049188872a8dad94bc02b_dependencies/meteor.git/build creation was not successful for an unknown reason

Total time: 0 seconds
```

**Comment by percyliang** [comment]
I think the problem is that you can't write to bundles, so you have to copy them.  So something like: `cl run -t sent2vec.git-orig:sent2vec.git 'cp -RL sent2vec.git-orig sent2vec.git && cd sent2vec.git && make'  You can also do `cl make ^/sent2vec.git` if you want to make it a top-level thing.

**Comment by arunchaganty** [comment]
Ok, that seems to have worked. I didn't get the `cl make ^/sent2vec.git` comment, but here's a suggested update to the FAQ wiki page (I'm unable to edit it as I am not a contributor to codalab):

#### When I try to execute a command like `make` on CodaLab, it fails because of "read-only" permissions. What do I do?

Each bundle uploaded to CodaLab is read-only. If a command you are running creates new files, you'll have to create a duplicate of the in the run command. For example, instead of running `cl run :my-bundle 'cd my-bundle && make`, run `cl run :my-bundle 'cp -r my-bundle duplicate && cd duplicate && make' -n duplicate`. Your freshly compiled executable will now be present in the `duplicate` bundle.

**Comment by percyliang** [comment]
Added a modification of this to the FAQ - thanks!

**Comment by arunchaganty** [comment]
Thanks!
