### ISSUE TITLE
Update default codalab docker to a newer version of Ubuntu?

### ISSUE THREAD

**Issue by arunchaganty** [codalab/codalab-worksheets#424]
It would be really convenient to have codalab docker images with more recent Ubuntu releases (e.g. 16.04 and 18.04) which respectively contain more recent versions of python (e.g 3.5 and 3.6). PyTorch for example does not support python3.4.

**Comment by percyliang** [comment]
The plan is to list a set of canonical images that are recommended (e.g., with PyTorch).  Is this all that's needed?  There's nothing specific to CodaLab about this, right?

**Comment by arunchaganty** [comment]
Yep. Having a set of canonical images should help reduce the need to have
to build your own docker images.

This supercedes this particular issue, but I think the faq could use some
documentation on how to pip install ones own packages. Currently I believe
one needs to roll their own docker container?

**Comment by percyliang** [comment]
Yes, if there's no docker image that has exactly what you want, then you need to roll your own...
