### ISSUE TITLE
Bundles with --link are not compatible with running your own worker

### ISSUE THREAD

**Issue by vaibhavad** [codalab/codalab-worksheets#4245]
**Describe the bug**
Linked bundles on my own worker that are accessible via worker's file system are not picked up by `cl-worker`.

**Codalab Information**
- *Your username*: vaibhav.adlakha
- *UUID of worksheet where problem occurred*: 0x30a7d1367e994e338a1c989c58c7aa1e
- *UUID of problem bundle (please don't delete)*: 0x7d487caab9e74204afe36c7e58f0347f, 0x097c7fe6d0a644438402199b9f95666c
- *Error message received from Codalab (if applicable)*: ccodalab.worker.bundle_service_client.BundleServiceException: Unable to get bundle info from bundle service: Not Found - Path '' in bundle 0x7d487caab9e74204afe36c7e58f0347f not found
 - *OS (if on CLI)*: `cl-worker` on Ubuntu 20.04.4 LTS
 - *Codalab CLI Version (if on CLI)*:  1.5.8

**To Reproduce**
Steps to reproduce the behavior :
1. Start `cl-worker` from own instance. I started from an AWS EC2 instance using the command `cl-worker --tag testing`
2. Make a file `a.txt` on the worker instance. For me the absolute path of the file is `/home/ubuntu/a.txt`
3. From a second system, make a linked bundle - `cl upload /home/ubuntu/a.txt --link`
4. From the same system, submit a run that depends on the linked bundle created above, add necessary queue information such that the bundle runs on the EC2 worker - `cl run :a.txt "date" --request-queue testing`
5. The worker will execute the bundle and throw an error (run logs attached)

**Expected behavior**
The bundle should run successfully as the path of `a.txt` is correct.

**Additional context**
I am planning to host a competition on the conversational retrieval task. I plan to run the submissions of this competition on custom AWS codalab workers as they generally require high CPU memory (often > 200GB). I plan to make some of the big files such as the retrieval corpus (15GB) and baseline dense index (70GB) available to participants as linked bundles that will be present on the workers filesystem.

[codalab_worker_logs.txt](https://github.com/codalab/codalab-worksheets/files/9480581/codalab_worker_logs.txt)

**Comment by epicfaace** [comment]
Unfortunately, `--link` only works for paths that are accessible by the CodaLab server. So you can't use a path that is only accessible by the worker.

**Comment by vaibhavad** [comment]
Thanks a lot for the clarification!
