### ISSUE TITLE
2 out of 5 GPU Jobs staged

### ISSUE THREAD

**Issue by Shuailong** [codalab/codalab-worksheets#425]
Hi! Thank you so much for providing such an excellent platform! I just submitted 5 GPU jobs with the resource requst as follows:

```
request_docker_image      : floydhub/pytorch:0.3.0-gpu.cuda9cudnn7-py2.24
request_time              : 3d
request_memory            : 32g
request_disk              : 4g
request_cpus              : 1
request_gpus              : 1
request_priority          : 0
request_network           : False
```
Two jobs are staged and never get running. Is it because the three jobs have exceeded the maximum allowed runing time for 7 days (3*3=9)?

Best,
Shuailong

**Comment by bkgoksel** [comment]
Hi Shuailong,
Staged usually means there are no machines available with enough resources to run your jobs at the moment. We have a limited number of GPUs available on our platform so some of your jobs probably had to wait for your earlier jobs to finish to get GPU slots. I've checked your account and seems like all your jobs are ready or are currently running (and you still have time quota left. You can check your quotas on the cli using the `cl uinfo` command). 

Closing this issue for now. Let us know if you run into any other issues!

Thanks,
Kerem

**Comment by Shuailong** [comment]
@bkgoksel So could I know how many GPU jobs could I run concurrently? If I used up all my time quota,  does this mean that I could not run any jobs anymore ? Thank you so much!
