### ISSUE TITLE
provide download link for bundles

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#4262]
![image](https://user-images.githubusercontent.com/435384/193417251-25387626-1220-487c-9093-fd168de14b66.png)
Right now you can click on a button to download a bundle, but it would be nice to be able to get the download link (right click, get link doesn't work) so that people can download programmatically.  We should make sure this works when we switch over to Azure blob storage, bypassing server, etc.

**Comment by leilenah** [comment]
@percyliang will do 👍
