### ISSUE TITLE
[USER ISSUE] abusive peer2profit-one-click-command-installations are all over the running/staged jobs 

### ISSUE THREAD

**Issue by Soonhwan-Kwon** [codalab/codalab-worksheets#4264]
**Describe the bug**
It seems there are abusive peer2profit-one-click-command-installations, and they are all over the running/staged jobs 
and they prevents normal jobs to run.
https://github.com/spiritLHLS/peer2profit-one-click-command-installation

**Screenshots**
![abuse1](https://user-images.githubusercontent.com/7395166/193436662-6a3ffb9d-a30c-42b0-9889-4418fd19d9c0.PNG)
![abuse2](https://user-images.githubusercontent.com/7395166/193436667-52cdcf26-2d7a-487b-9202-c6fe3f4b55de.PNG)

**Comment by epicfaace** [comment]
Thanks, we'll look into it.

**Comment by pranavjain** [comment]
Closing as we are not facing this issue for now.
