### ISSUE TITLE
Benchmarking GCS blob storage upload tests

### ISSUE THREAD

**Issue by wwwjn** [codalab/codalab-worksheets#4265]
Similar to #4154, GCS bypass server upload has been merged into 

Will test upload from local PC -> dev environment.

Test cases:
1. small files
2. multi-layer directories and large amount of small files (eg, cpython)
3. large files (eg, openwebtext)

**Comment by percyliang** [comment]
Do this on Stanford too.

**Comment by wwwjn** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/40016222/195406425-ca681142-cd35-408a-83d9-bbe1eda87bf7.png">

**Comment by wwwjn** [comment]
New benchmarking file: https://docs.google.com/document/d/1dj-xxO_zdXNcGKzn9L97nNIaOwjNSeqr0RevQMPJdhA/edit#
