### ISSUE TITLE
CLI command to list users

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#427]
`cl uls`

List users using the users API, and in particular perhaps an `--online` or `--active` flag to search to users who have recently been active. (This maybe can be restricted to admin users only.)
The latter would be equivalent of one or both of the following (written by Konstantin):

```
SELECT DISTINCT user_name FROM oauth2_token JOIN user ON oauth2_token.user_id = user.user_id WHERE client_id = "codalab_cli_client" AND expires > utc_timestamp();
SELECT user_name, last_login FROM user WHERE last_login > utc_timestamp() - 30 * 24 * 60 * 60 ORDER BY last_login DESC;
```

**Comment by kashizui** [comment]
Simply need to call the Users API

`JsonApiClient.fetch('users')`

Can add more query parameters to `rest/users.py` if necessary to implement more fancy features.

**Comment by percyliang** [comment]
Want to also be able to search by username, email, etc.

**Comment by Levilian** [comment]
Lists users on CodaLab (returns 10 results by default).
    uls <keyword> ... <keyword>         : Username or id contains each <keyword>.
    uls user_name=<value>               : Name is <value>, where `user_name` can be any metadata field (e.g., email).

    uls .limit=<limit>                  : Limit the number of results to the top <limit> (e.g., 50).
    uls .offset=<offset>                : Return results starting at <offset>.

    uls .joined_before=<datetime>       : Returns users joined before (inclusive) given ISO 8601 timestamp (e.g., .before=2042-03-14).
    uls .joined_after=<datetime>        : Returns users joined after (inclusive) given ISO 8601 timestamp (e.g., .after=2120-10-15T00:00:00-08).
    uls .active_before=<datetime>       : (Root user only) Returns users last logged in before (inclusive) given ISO 8601
    timestamp (e.g., .before=2042-03-14).
    uls .active_after=<datetime>        : (Root user only) Returns users last logged in after (inclusive) given ISO 8601 timestamp (e.g., .after=2120-10-15T00:00:00-08).

    uls .disk_used_less_than=<percentage> or <float>      : (Root user only) Returns users whose disk usage less than (inclusive) given value (e.g., .disk_used_less_than=70% or 0.3).
    uls .disk_used_more_than=<percentage> or <float>      : (Root user only) Returns users whose disk usage more than (inclusive) given value (e.g., .disk_used_more_than=70% or 0.3).
    uls .time_used_less_than=<percentage> or <float>      : (Root user only) Returns users whose time usage less than (inclusive) given value (e.g., .time_used_less_than=70% or 0.3).
    uls .time_used_more_than=<percentage> or <float>      : (Root user only) Returns users whose time usage more than (inclusive) given value (e.g., .time_used_more_than=70% or 0.3).

    uls size=.sort                      : Sort by a particular field (where `size` can be any metadata field).
    uls size=.sort-                     : Sort by a particular field in reverse (e.g., `size`).
    uls .last                           : Sort in reverse chronological order (equivalent to id=.sort-).
    uls .count                          : Count the number of matching bundles.
    uls .format=<format>                : Apply <format> function (see worksheet markdown).
    Arguments:
      keywords              Keywords to search for.
      -f, --field           Print out these comma-separated fields.

**Comment by Levilian** [comment]
Key use cases:
1. Search by a range of dates to see active and newly registered users, both in rows and in count summary
2. Search by time and disk quota usage percentage calculated from disk_used divided by disk_quota
3. Freedom to display different sets of user information yet having the best-looking default display
                    'id',
                    'user_name',
                    'first_name',
                    'last_name',
                    'affiliation',
                    'url',
                    'date_joined',
                    'last_login',
                    'email',
                    'time',
                    'disk',
                    'parallel_run_quota',
