### ISSUE TITLE
Optimize User Profile View

### ISSUE THREAD

**Issue by leilenah** [codalab/codalab-worksheets#4294]
**User Profile View:** https://worksheets.codalab.org/users/codalab

The scope of this issue is to audit the user profile view and determine what can be done to improve its UI. Present any major changes to Percy before implementing.

**Comment by leilenah** [comment]
Related: https://github.com/codalab/codalab-worksheets/issues/4293

**Comment by leilenah** [comment]
**Meeting Notes**
- Consider ORCID: https://orcid.org/
- should tie into whatever we implement for user incentives

**Comment by leilenah** [comment]
cc @percyliang

**Comment by percyliang** [comment]
This issue is a bit generic, closing in favor of more specific issues.
