### ISSUE TITLE
graphing: need to delete old lines

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#43]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Friday Dec 18, 2015 at 05:00 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1504_

----

Here's how to reproduce the bug:

Create a worksheet with:

    % display graph /a.tsv
    [...bundle with a file inside called a.tsv...]

Save and look at the graph.  Now go back and change:

    % display graph /a.tsv display_name=summary

The bug is that there are two curves instead of one.  Basically, old items should be deleted.

Relevant file: graph_bundle_interface.js.

**Comment by ChengshuLi** [comment]
Submitted for CR
