### ISSUE TITLE
cl macro mura-utils/valid-eval-v1.1 returns Not found: '/bundles/undefined' error

### ISSUE THREAD

**Issue by zhiaozhou** [codalab/codalab-worksheets#430]
I was trying to evaluate my predictions output based on your tutorial. However, when I ran this line "cl macro mura-utils/valid-eval-v1.1 predictions-{MODELNAME}", it returns Not found: '/bundles/undefined' and there's not output.

**Comment by bkgoksel** [comment]
Hi @zhiaozhou,
Are you still experiencing this issue? If so could you share the UUID of the failing run attempt and the worksheet you're running these commands on so we can debug.
Thanks,
Kerem from CodaLab team

**Comment by zhiaozhou** [comment]
Hi @bkgoksel 
Thank you for your reply but it's been such a long time that I'm not even working on it no more. But thanks anyway.
