### ISSUE TITLE
More disk space for evaluating T5-11B

### ISSUE THREAD

**Issue by sniper343** [codalab/codalab-worksheets#4317]
Hi,

I'm trying to upload and run our fine-tuned T5-11b model (about 40G) in CodaLab. However, the worksheets I applied has only 100m disk space, I wonder if there is something wrong with my application(this issue as https://github.com/codalab/codalab-worksheets/issues/4295)

I filled out the "disk quota request form",  Can you assign me a 50G disk quota? 

Thank you in advance for any help you might be able to provide.

Here is some information.

Username: hongzhiyou
UUID of worksheet where problem occurred:
https://worksheets.codalab.org/worksheets/0xdcac22c71c4f46859cf3fc699f0a89c6

**Comment by AndrewJGaut** [comment]
Yes, your request has been fulfilled. Sorry about that; we had some internal issues on our end. The form will work correctly in the future and requests made through the form will be fulfilled. Thanks for reaching out!
