### ISSUE TITLE
What's the mura competition's deadline?? 

### ISSUE THREAD

**Issue by Zzmonica** [codalab/codalab-worksheets#432]
I want to know the deadline of the MURA competition, I can't find it in the reference, I'll appreciate that if who can let me know that!!

**Comment by bkgoksel** [comment]
Hi,
The competition is not organized by the CodaLab team. Please reach out to the competition organizers for competition-related issues and the CodaLab team for technical issues with the CodaLab platform.

Thanks,

**Comment by Zzmonica** [comment]
Oh..OK,that's my mistake,thank you all the same!
