### ISSUE TITLE
Redesign disk usage

### ISSUE THREAD

**Issue by AndrewJGaut** [codalab/codalab-worksheets#4323]
Currently, the data_size for a bundle is equivalent to its size in the first bundle location and is stored as general bundle metadata.

We want to make the following changes:
- Have one data_size per bundle location
- That data_size should be the real size of the bundle (i.e. compressed if its compressed and uncompressed if not)
- There should be a different disk quota per user for different stores.

**Comment by percyliang** [comment]
Closing this for now since we'll probably leave each bundle having one location for the foreseeable future.
