### ISSUE TITLE
Test failing -- adds "y" to arbitrary time duration

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4326]
![image](https://user-images.githubusercontent.com/1689183/206238321-66b04ecd-6120-4ae5-8142-45f57f0b38c9.png)

**Comment by epicfaace** [comment]
Caused by @AndrewJGaut 's change in https://github.com/codalab/codalab-worksheets/blob/2389cde78d482ef095729ee19d42f6d59301ec68/tests/cli/test_cli.py#L398.

**Comment by epicfaace** [comment]
Fixed in https://github.com/codalab/codalab-worksheets/pull/4316/commits/c9b9d2b8d8dd3156d0e32e319bcb30444c390dba

**Comment by percyliang** [comment]
Does that mean we can close this?

**Comment by AriWebb** [comment]
Yes I believe so, will close now
