### ISSUE TITLE
submission of a prediction to our own competition via scripts/competitiond.py doesn't work properly

### ISSUE THREAD

**Issue by tahasevim** [codalab/codalab-worksheets#433]
I am trying to host a custom competition using small evaluation daemon tool that is placed in scripts/competitiond.py.

I have read the documentation of the evaluation daemon script and configured a config file.(Also checked that SQuAD's config file.)
For the submission, I reviewed SQuaD submission tutorial and created a run bundle that will be submitted to my competition.In the first step, predict step, script generates a predict bundle that's stage is ready however in the second step script generates a result bundle that's stage is failed.Reason of the failure that I can see is result bundle uses predict bundle itself not the submitted dependency of the predict bundle.

I couldn't figure out how to solve failure of result step because of the lack of documentation for competition leaderboard evaluation daemon. 
Thanks for interesting.

**Comment by tahasevim** [comment]
Solved.

**Comment by nangeblog** [comment]
I also encountered this problem, how can I solve it?
