### ISSUE TITLE
Application for more disk quota

### ISSUE THREAD

**Issue by canghongjian** [codalab/codalab-worksheets#4335]
I am preparing a dataset evaluation and I find that 10G disk quota is not enough for me. And I register other accounts and I see new accounts including accounts registered by edu email can only get 100M disk quota. 

Could you please improve my disk quota or check the problem that edu user only get 100M disk quota? It is urgent because I need the evaluation results for the paper I'm writing. In addition I have filled out the form for more disk quota and time quota.

My main account info:
username: *****
email: *****

Thanks a lot.

**Comment by canghongjian** [comment]
@AndrewJGaut Would you please check on it? Thank you so much.

**Comment by AndrewJGaut** [comment]
Filled!
