### ISSUE TITLE
stuck in staged state

### ISSUE THREAD

**Issue by ellonde** [codalab/codalab-worksheets#434]
All the jobs I try to run is stalled in the staged state, even simple things like running through the tutorial.

**Comment by ymcui** [comment]
same problem here. waiting more than 24h+ :(

**Comment by bkgoksel** [comment]
Staged means all workers are busy with other runs and your runs are waiting for these to complete. We're having higher usage this week and will be launching new worker machines shortly, so you should start experiencing shorter wait times soon.
