### ISSUE TITLE
Run crfm-helm on CodaLab

### ISSUE THREAD

**Issue by yifanmai** [codalab/codalab-worksheets#4365]
We need to be able to run crfm-helm end-to-end on CodaLab i.e. JSON assets are generated and hosted on CodaLab.

**Comment by yifanmai** [comment]
Ran a [worksheet](https://worksheets.codalab.org/worksheets/0xc896f05df5c24dca95e4c581d9150340) with slightly less than 300 bundles. This seems to work reasonably well in terms of scheduling and UI.

CodaLab notes:

- When using Azure Batch Manager, it's possible for jobs to crash the worker, causing a `worker_offline` bundle state. This also causes the nodes in the Azure Batch pool to be permanently stuck in the "unusable" state. Unusable nodes have to be manually deleted. --> _we should look into this_
- Bundles with an upstream failed bundle get stuck in pending forever (should they get transitioned to failed, since it can never get scheduled?) --> _this is true only for worker-offline, so not an issue._
- How to throttle the number of bundles concurrently running? Less of a problem if we use our own worker queue (then we can control the number of workers using the worker manager). --> _worker parallel run quota_
- Would also be nice to the order of bundle scheduling / throttle the the number of bundles concurrently running per _HELM model_ (so we don't DDoS the model APIs) --> _we have --request-priority_

**Comment by percyliang** [comment]
Not prioritizing.
