### ISSUE TITLE
Sentry sends too many logs

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4373]
This is too noisy on the rest server logs and makes it harder to view other logs. Can we turn off debug logging for sentry?

<img width="865" alt="image" src="https://user-images.githubusercontent.com/1689183/216159769-48113b15-cbe1-497c-89e3-db2e8b9ac1b4.png">

**Comment by percyliang** [comment]
Only a problem on dev for debugging, not on prod.
