### ISSUE TITLE
Bundle fails showing `Failed to download dependency`

### ISSUE THREAD

**Issue by ymcui** [codalab/codalab-worksheets#438]
Hi,
I uploaded a toy python script and tried to run it.
But it turned out to be a fail with `Failed to download dependency` error, while the command does not rely on any bundle dependencies.
However, if I run the same command with `--request-gpus 1`, then it will be fine.
Also, I have not encountered this problem in several days ago, so I suspect there is something wrong with the CPU server.
Any ideas?

**Comment by bkgoksel** [comment]
Hi Yiming,
One of our CPU workers did have an old dependency cleanup related problem after a recent update. We've fixed the issue after your report. Thanks for bringing it to our attention!
CodaLab team

**Comment by ymcui** [comment]
Hello, @bkgoksel 
The problems appear again on `vm-clws-prod-gpuworker-1`

**Comment by bkgoksel** [comment]
Hi Yiming,
Thanks for letting us know. The fixes are merged to our code base, but haven't been deployed to our servers yet. We've been manually cleaning the dependencies until the new version is deployed. We're planning to deploy the new version today, which should fix the problem for good. Thanks for bringing this to our attention.

**Comment by ymcui** [comment]
Hi, 
I am not sure if the updates have been deployed, but the issue still happens.

Best,
Yiming
