### ISSUE TITLE
Create migration script that moves bundles from disk to blob

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4380]
- The script should keep bundle id, but change the bundle storage type, and move it from disk to blob
- It can also do specific actions to clean up bundles (bundles which are not in database but are still on disk)

**Comment by wwwjn** [comment]
Design: https://docs.google.com/document/d/1-QPERr__VFLuMtbGhoAEPnz-_wXC9FtRTlB_g9Gs3zo/edit#
