### ISSUE TITLE
ImportError: No module named torch

### ISSUE THREAD

**Issue by Zzmonica** [codalab/codalab-worksheets#440]
When I running my python  file , it comes out  No module named torch.And I don't know why..

**Comment by bkgoksel** [comment]
Hi Zzmonica,
CodaLab runs your bundles in Docker containers, which means your runs can only use packages that are installed in the Docker image used. If you don't specify a particular Docker image, the default CodaLab image is used, which at this time does not include torch or pytorch (we're working on getting a more fully featured image out).

If you want to use PyTorch or tensorflow (or any package that's not included in the default image, you need to specify a Docker image that has these packages installed via the `--request-docker-image` command flag to the `cl run` command. 

You can use any flag from https://hub.docker.com 
For example for PyTorch, you can find the official Docker images at https://hub.docker.com/r/pytorch/pytorch
You can see the available versions under the `Tags` tab on that page. Once you know the Docker image user, name and tag you want to use, you can include it on your run like the following:
`cl run <your command> --request-docker-image pytorch/pytorch:0.4.1-cuda9-cudnn7-runtime`

Hope this helps,
Kerem from CodaLab team.
