### ISSUE TITLE
My bundle failed to run

### ISSUE THREAD

**Issue by gonglinyuan** [codalab/codalab-worksheets#441]
My bundle is 0xcd5a578c639f4ee0b6926b620faa8097
The similar arguments used to work for my pervious bundles, but it failed this time.
The error message was "Failed to download dependency MURA-v1.1:"
And when I removed this target_spec, the error message becomes "Failed to download dependency models:"
However, the target_spec mapping showed in the table of https://worksheets.codalab.org/bundles/0xcd5a578c639f4ee0b6926b620faa8097/ is correct. It seems that the worker failed to load all bundles.
My inputs to the cli is "cl run valid_image_paths.csv:valid_image_paths.csv MURA-v1.1:valid src:src configs:configs models:models "python -O src/run_test_all.py valid_image_paths.csv predictions.csv" --request-docker-image gonglinyuan/deep_learning --request-disk 8g --request-gpus 1 --request-memory 16g -n run-predictions". I tried both web cli and the python one.
My codalab account is gonglinyuan
Thank you

**Comment by mit10000** [comment]
We have the same problem.
Several days ago everything was fine. But now keep have error:
"Failed to download dependency MURA-v1.1:"

Obviously this  is a bug.

**Comment by bkgoksel** [comment]
Dependency bug is now fixed and the fixed version is deployed to our production servers. Thanks for reporting the issue and your patience. Let us know if any other issues surface.
