### ISSUE TITLE
Update "back" button behavior

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4414]
The "back" button is pretty confusing. I also often accidentally click it to try to exit from the web CLI, but then the whole page goes to the previous page. It's basically the same as the browser back button too, so not needed.

**Comment by AndrewJGaut** [comment]
We can change this so that back button is greyed out when on the worksheet page and ungreyed when you go to the full bundle details

**Comment by percyliang** [comment]
Not important, dropping for now.
