### ISSUE TITLE
Think about shared disks for docker caches

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4422]
Consider how to do this

**Comment by yifanmai** [comment]
Consider using [Docker registry as a pull through cache](https://docs.docker.com/registry/recipes/mirror/):

> If you have multiple instances of Docker running in your environment, such as multiple physical or virtual machines all running Docker, each daemon goes out to the internet and fetches an image it doesn’t have locally, from the Docker repository. You can run a local registry mirror and point all your daemons there, to avoid this extra internet traffic.

My main concerns with shared disk are that network disks are expensive, and that you could get potential race conditions and data corruption if multiple workers try to write to the same disk location at the same time.

**Comment by percyliang** [comment]
Let's not do this then for now for simplicity.
