### ISSUE TITLE
Application for more disk quota 

### ISSUE THREAD

**Issue by WWJ002233** [codalab/codalab-worksheets#4424]
I am preparing a dataset evaluation which need 15G disk quota, but the account I register can only get 100M disk quota.I wonder if there is something wrong with my application(this issue as #4335) 

Could you please improve my disk quota or check the problem that edu user only get 100M disk quota? It is urgent because I also need the evaluation results for the paper I'm writing. 

Here is some information. 
username: hongone 
email: 19051825@hdu.edu.cn
uuid:https://worksheets.codalab.org/worksheets/0x69ae758b63954857b0ecce060db5a80a 

Thank you in advance for any help you might be able to provide.

**Comment by yifanmai** [comment]
Hi, I have increased your disk quota to 20 GB. Let me know if you have any other questions.

**Comment by WWJ002233** [comment]
thank you for your reply!
Since the preprocessing and debugging of the data takes too much time . Could you please increase my time quota to 6 hours? In addition I have filled out the form for more time quota.
Here is some information.
username: hongone
email: 19051825@hdu.edu.cn
uuid:https://worksheets.codalab.org/worksheets/0x69ae758b63954857b0ecce060db5a80a 
Thanks a lot.

**Comment by WWJ002233** [comment]
thank you for your reply!
Since the preprocessing and debugging of the data takes too much time . Could you please increase my time quota to 6 hours? In addition I have filled out the form for more time quota.
Here is some information.
username: hongone
***@***.***
uuid:https://worksheets.codalab.org/worksheets/0x69ae758b63954857b0ecce060db5a80a
Thanks a lot.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "codalab/codalab-worksheets"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月15日(星期三) 凌晨2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [codalab/codalab-worksheets] Application for more disk quota  (Issue #4424)





 
Hi, I have increased your disk quota to 20 GB. Let me know if you have any other questions.

**Comment by AndrewJGaut** [comment]
I see that your time quota was increased, so I'm closing this issue. Thanks!
