### ISSUE TITLE
Broken pipe when running multiple run bundles

### ISSUE THREAD

**Issue by ChengshuLi** [codalab/codalab-worksheets#443]
I start my worker like this:
worker/worker.sh --bundle-service-url http://localhost:2900 --work-dir /Users/chengshuli/.codalab/worker_scratch --slots 4 --verbose

To reproduce, run 5 run bundles 

```
run "while true; do echo 1 >> output; sleep 1; done"
```

Sooner or later, I got broken pipes. 

Here is the error msg for rest-server:

<img width="811" alt="screenshot" src="https://cloud.githubusercontent.com/assets/6732996/15408013/daf2e124-1dc2-11e6-81a0-fb3214a9853f.png">

Here is the error msg for bundle-manager:
<img width="1028" alt="screenshot" src="https://cloud.githubusercontent.com/assets/6732996/15408245/0bf12fdc-1dc4-11e6-921d-0a328304ae8e.png">

**Comment by bkgoksel** [comment]
The worker has changed considerably since this issue was opened. Closing as no longer relevant.
