### ISSUE TITLE
Application for more time quota 

### ISSUE THREAD

**Issue by WWJ002233** [codalab/codalab-worksheets#4438]
I am preparing a dataset evaluation, but the account I register can only get 100M disk quota and 1h time quota.I applied for more disk quota and got a timely reply(this issue as #4424).But when I applied for more time quota, I didn't get a reply for a long time, whether through issue or form for more time quota.

Could you please improve my time quota to 6hours ? It is really urgent because I need the evaluation results for the paper I'm writing. 

Here is some information. 
username: hongone 
email: 19051825@hdu.edu.cn
uuid:https://worksheets.codalab.org/worksheets/0x69ae758b63954857b0ecce060db5a80a 
Thank you in advance for any help you might be able to provide.

**Comment by AndrewJGaut** [comment]
Granted!
