### ISSUE TITLE
Dependency Caching Feature

### ISSUE THREAD

**Issue by AndrewJGaut** [codalab/codalab-worksheets#4458]
We want to add in better dependency caching. See design doc [here](https://docs.google.com/document/d/16Q69styPdlFKmXyrqklIn5wzYYOAysm2QFk0e2RJoGo/edit)

This is important for running HELM on Codalab.

**Comment by AndrewJGaut** [comment]
@percyliang We talked last meeting about whether or not suggested solution step 1) from the doc above was already implemented (i.e that 'bundles are assigned to workers that already have the needed dependencies').

Upon reading bundle-manager code, that functionality **already has been implemented**.

To see why, we can look at the scheduling code. Bundles are scheduled [here](https://github.com/codalab/codalab-worksheets/blob/master/codalab/server/bundle_manager.py#L422). That function essentially (1) sorts bundles by running priority within users ([here](https://github.com/codalab/codalab-worksheets/blob/dc5beda8c0f7b6bb95cdeffe80ef8214c60fcaf6/codalab/server/bundle_manager.py#L444-L472)), (2) computes workers available to each user and how many resources they have ([here](https://github.com/codalab/codalab-worksheets/blob/dc5beda8c0f7b6bb95cdeffe80ef8214c60fcaf6/codalab/server/bundle_manager.py#L474-L496)), and (3) starts running the staged bundles ([here](https://github.com/codalab/codalab-worksheets/blob/dc5beda8c0f7b6bb95cdeffe80ef8214c60fcaf6/codalab/server/bundle_manager.py#L505)).

Within (3), it gets the worker list for each worker and checks if workers are offline before actually trying to schedule the run bundles. That scheduling is done [here](https://github.com/codalab/codalab-worksheets/blob/dc5beda8c0f7b6bb95cdeffe80ef8214c60fcaf6/codalab/server/bundle_manager.py#L543-L558). We attempt to run the bundle on each worker in the order decided on by [`_filter_and_sort_workers`](https://github.com/codalab/codalab-worksheets/blob/dc5beda8c0f7b6bb95cdeffe80ef8214c60fcaf6/codalab/server/bundle_manager.py#L660) (meaning that workers which are sorted closer to the beginning of that list are more likely to run the bundle). Within `_filter_and_sort_workers`, we see that the number of dependencies needed by the bundle and already cached on the workers is taken into account (see [here](https://github.com/codalab/codalab-worksheets/blob/dc5beda8c0f7b6bb95cdeffe80ef8214c60fcaf6/codalab/server/bundle_manager.py#L695-L722)). 

So, ostensibly, that functionality does already exist.

@epicfaace See what you think about this, but it could imply we can just move to suggested solution step 2) if we want. (One other option would be to re-order the tuple of keys used for sorting so that the number of dependencies already cached by the worker has a higher priority, but I personally think that would be a bad idea since the current ordering looks correct to me.)

**Comment by epicfaace** [comment]
> Within `_filter_and_sort_workers`, we see that the number of dependencies needed by the bundle and already cached on the workers is taken into account (see [here](https://github.com/codalab/codalab-worksheets/blob/dc5beda8c0f7b6bb95cdeffe80ef8214c60fcaf6/codalab/server/bundle_manager.py#L695-L722)).

Well, but it looks like it's only comparing the _number_ of dependencies (not whether the exact same dependencies are available)?

**Comment by AndrewJGaut** [comment]
> > Within `_filter_and_sort_workers`, we see that the number of dependencies needed by the bundle and already cached on the workers is taken into account (see [here](https://github.com/codalab/codalab-worksheets/blob/dc5beda8c0f7b6bb95cdeffe80ef8214c60fcaf6/codalab/server/bundle_manager.py#L695-L722)).
> 
> Well, but it looks like it's only comparing the _number_ of dependencies (not whether the exact same dependencies are available)?

Aren't they comparing whether the exact same dependencies are available when they take the set intersection [here](https://github.com/codalab/codalab-worksheets/blob/dc5beda8c0f7b6bb95cdeffe80ef8214c60fcaf6/codalab/server/bundle_manager.py#L702)?

When there's a shared file system, though, they do just set it to `len(needed_deps)` ([here](https://github.com/codalab/codalab-worksheets/blob/dc5beda8c0f7b6bb95cdeffe80ef8214c60fcaf6/codalab/server/bundle_manager.py#L698-L699)) because all dependencies are shared and so workers shouldn't be filtered by that anyway (and that setting it to `len(needed_deps)` will make it the same for all workers and therefore won't play a factor in sorting). That is a little confusing, though, so perhaps we should just set it to 0 and add a comment or something.

**Comment by yifanmai** [comment]
> That is a little confusing, though, so perhaps we should just set it to 0 and add a comment or something.

This is fine if all your workers are `shared_file_system` or not ` shared_file_system`. If you have a mix of both workers, and you set the sort key to `0`, then non-`shared_file_system` workers will be prioritized over `shared_file_system` workers.

From the HELM perspective, I feel like the shared persistent disk (solution step 2) feels more like an optimization and should be is lower priority than other stuff that is blocking HELM from working.

**Comment by AndrewJGaut** [comment]
> > That is a little confusing, though, so perhaps we should just set it to 0 and add a comment or something.
> 
> This is fine if all your workers are `shared_file_system` or not ` shared_file_system`. If you have a mix of both workers, and you set the sort key to `0`, then non-`shared_file_system` workers will be prioritized over `shared_file_system` workers.
> 
> From the HELM perspective, I feel like the shared persistent disk (solution step 2) feels more like an optimization and should be is lower priority than other stuff that is blocking HELM from working.

Ah, yes, good point.

Also, I agree with your second point -- I definitely think we can proceed with the HELM on Codalab implementation without doing  solution step 2).

**Comment by epicfaace** [comment]
Wait should we still keep this issue open though? @AndrewJGaut

**Comment by AndrewJGaut** [comment]
> Wait should we still keep this issue open though? @AndrewJGaut

Not sure; are we still planning on doing this?

**Comment by epicfaace** [comment]
I thought we might? Not sure though, maybe let's discuss
