### ISSUE TITLE
(Infinite) loop when Pulling docker image

### ISSUE THREAD

**Issue by ellonde** [codalab/codalab-worksheets#446]
Hello there

Im trying to run a bundle which requests a docker image. The run_status seems to be stuck in an infinite loop, pulling and extracting the requested image.

At first it seem to both download and extract the image multiple times but now its stuck between the message:
Pulling docker image: Status: Image is up to date for ellonde/pytorch04:latest
and
Pulling docker image: ellonde/pytorch04

Edit: At some point it does proceed(so not infinite after all) but it seems like it did repeat the same operations quite a lot of times.

**Comment by bkgoksel** [comment]
Hi ellonde,
Thanks for reporting this bug. We believe it is related to our cleanup process that tries to limit the total size of downloaded docker images on our worker machines at any given time. At times when many people are requesting large docker images these situations happen. We're working on a fix but in the meantime please let us know if you run into this issue again (preferably with the bundle uuid that had the stuck image download)

**Comment by ellonde** [comment]
Thanks a lot for the answer. As I mentioned I managed to make it work, but ill let you know if I experience this issue again.

**Comment by bkgoksel** [comment]
Closing as we've deployed fixes for all known issues with docker image downloads. Feel free to reopen if anything else goes wrong.
