### ISSUE TITLE
Resources tests issues

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4465]
Resources

The two linked CI failures [here](https://github.com/codalab/codalab-worksheets/actions/runs/4493408758/jobs/7904748770) and [here](https://github.com/codalab/codalab-worksheets/actions/runs/4305932181/jobs/7509225119) are actually different failures within resources, which is interesting.

For the first failure, it looks like the bundle with the command python -c "import urllib.request; urllib.request.urlopen('https://www.google.com/').read()" failed, but there is no failure message (failure message was logged as None in the worker logs) even though it shows Exit Code 1. Thus, this one will be hard to debug unless I can replicate it locally, which I haven't yet been able to do.

Not sure what happened with the second one; the failure message is Error. Memory limit 10m exceeded. and it occurs when we run perl main.pl 1 1 5, where main.pl is the file [stress_test.pl file](https://github.com/codalab/codalab-worksheets/blob/master/scripts/stress-test.pl) (which is uploaded [here](https://github.com/codalab/codalab-worksheets/blob/master/tests/cli/test_cli.py#L2515) in the cli test). I'm not sure why it fails for Kubernetes in this case; the arsg 1 1 5 indicate that only 1 MB of RAM should be used, yet it apparently goes over the memory limit. Perhaps @epicfaace has an idea here? This could be related to Kubernetes.

**Comment by percyliang** [comment]
Haven't seen this lately.
