### ISSUE TITLE
need more disk quota and time quota for evalution

### ISSUE THREAD

**Issue by atomzhang1111** [codalab/codalab-worksheets#4467]
My account has only 1 hour  and 100m disk space . I have filled out many forms and applied many times, but I got no reply , Can you allocate me 30G space quota and 20 days  quota,  I need to evaluate my model and complete the paper as soon as possible,can you help me ?
username: atomzhang
email: atomzhang@aliyun.com
uuid:https://worksheets.codalab.org/worksheets/0x6cc18d608c0545a99437e2a84ca4647d

**Comment by AndrewJGaut** [comment]
Allocated to username atomzhang. Let me know if you got it!

**Comment by atomzhang1111** [comment]
i got the extra disk  ,thanks
