### ISSUE TITLE
application for extra disk quota

### ISSUE THREAD

**Issue by cloud3632** [codalab/codalab-worksheets#4469]
i use the codalab to submit my model then the  blind test will be taken out ,but i used up the disk quota though i have deleted some of my bundle , i still cannot run my model , can you allocate me extra 30G disk ,i need to evaluate about  5 models and each model will take about 5G, i need to finish this evaluation to write my paper .i will be appreciate if you can process my request as soon as possible ，thanks
my username ：atom
my email：icloud3632@163.com

**Comment by AndrewJGaut** [comment]
I granted you the extra space.

Out of curiosity, what do you mean by "deleted some of my bundle"? What commands did you run, if you don't mind me asking?

**Comment by cloud3632** [comment]
i delete some bundles that has large size to reuse the disk but i find the disk cannot reuse by delete some bundle , i have received the disk quote that you grant to me  ,thank

**Comment by cloud3632** [comment]
i delete some bundle to reuse the disk but i find the disk cannot be reused，so i ask for extra disk space .
thanks for your grant me extra disk



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/11/2023 09:55 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [codalab/codalab-worksheets] application for extra disk quota (Issue #4469) |

I granted you the extra space.

Out of curiosity, what do you mean by "deleted some of my bundle"? What commands did you run, if you don't mind me asking?
