### ISSUE TITLE
[USER ISSUE] "Dependency quota full" on custom worker, even though there's enough storage.

### ISSUE THREAD

**Issue by GreenParachute** [codalab/codalab-worksheets#4474]
**Describe the bug**
We have set up our own custom codalab worker to run some particularly heavy jobs.
While it has previously executed jobs successfully, currently when submitting the below run bundle, the web interface quickly says the worker is offline (see screenshot), however the CLI on our server keeps outputting progress and downloading dependencies (see screenshot). In addition, running `cl workers ` shows the worker is still active and available (see screenshot). 
Once all dependencies are seemingly downloaded, the CLI beings outputting the following error on a loop:
`"Dependency quota full but there are only downloading dependencies, not cleaning up until downloads are over"`
even though nothing else seems to be downloading anymore (and the appropriate amount of disk space seems to have been used up).

Run bundle in question:
`cl run "run_on_codalab_dev_eval.sh:0x8c788d" "run.py:0x1d0a49" "natsql_table_converter:0xe1652c" "tables_for_natsql_dev.json:0x7c97fa" "convert_natsql.py:0xa5b989" "natsql2sql:0x109cd4" "src:0x2c215d" "requirements.txt:0x1ebc63" "huggingface.conf:0x91a61a" "NatSQL_RASAT_model:0x8a3b3a" "QP-model:0xa02108" "NatSQLSpider:0xd46b08" "data:0xb357bf" "dev_gold.sql:0xbf1c2f" "database:0xc12aea" "evaluation.py:0xf141ef" "process_sql.py:0xaa1811" 'source run_on_codalab_dev_eval.sh' --request-network --request-docker-image allennlp/allennlp:v2.5.0-cuda11.1  --request-time 120m --request-memory 50g --request-cpus 6 --request-gpus 1 --request-queue adapt`

We have also tried to execute a simpler, smaller run bundle, which seems to work fine, so suspect it might have something to do with available storage or dependency cleanup.
`cl run 'echo "Hello World!"' --request-docker-image allennlp/allennlp:v2.5.0-cuda11.1 --request-cpus 6 --request-gpus 1 --request-queue adapt`

**Codalab Information**
- *Your username*: GreenParachute
- *UUID of worksheet where problem occurred*: 0x21b86b64910945c7b1d5775da875ff4f
- *UUID of problem bundle (please don't delete)*: 0xfbcde0e2ce334c0eaa7e133346bc2035
- *Error message received from Codalab (if applicable)*: "Dependency quota full but there are only downloading dependencies, not cleaning up until downloads are over" - just repeating on a loop
 - *OS (if on CLI)*: linux
 - *Codalab CLI Version (if on CLI)*: 1.6.3

**Screenshots**
![image](https://github.com/codalab/codalab-worksheets/assets/11292484/a6ca0a07-3e8c-4acb-9e0b-d110655473fc)
Worker offline, even though in the shell we can see it's still downloading:
![image](https://github.com/codalab/codalab-worksheets/assets/11292484/dfbd773d-c4ee-49cb-a69c-1f5e051e185b)
And `cl-workers` indicates it is still available
![image](https://github.com/codalab/codalab-worksheets/assets/11292484/9841d38b-80ea-4a91-bd39-69c4d2fb9a2c)
Once downloads finish, this keeps outputting:
![image](https://github.com/codalab/codalab-worksheets/assets/11292484/cf52e57c-a5d0-4dc4-8ae7-fd25db45af2c)

**To Reproduce**
Steps to reproduce the behavior :
Would need to submit another run bundle to our worker using the above run command.

**Additional context**
We followed the instructions for setting up a custom worker exactly, and have previously executed jobs successfully, jobs which were very similar in size and scope to the job that's currently causing problems. 

Still, is it possible our worker somehow isn't set up correctly? 
Or is there an issue with dependency cleanup?
Or is there a 'dependency quota' that we're not aware of (which is presumably separate from the "disk quota", which is again separate from actual available disk storage on the server hosting the worker? Do I understand that correctly?)

Any advice would be appreciated, or any pointers in the documentation that could help us better understand what's going on would also be helpful! 

Thanks

**Comment by yifanmai** [comment]
@AndrewJGaut This sounds related to the new quota calculation system, could you take a look?

**Comment by yifanmai** [comment]
@GreenParachute Would you be able to send us the complete worker logs? There might be something useful in there.

**Comment by GreenParachute** [comment]
@yifanmai Hi, thanks for the reply! I ran the job again and observed the same error. I recorded a full worker log, see attached.
[output.log](https://github.com/codalab/codalab-worksheets/files/11592469/output.log)

That said, this time I didn't immediately stop the worker when error was raised, and while I observed the exact same behaviour, after a while the "Dependency quota full" message stopped displaying and the bundle displays the expected results on the web interface. 
 
So it seems the job was still running, but there is a seeming disconnect between the web interface and the worker--the interface seems to still believe the worker is offline, however the worker actually runs the job, and the results are uploaded back to the worksheet upon completion.

You can see this on the bundle in question--the job is completed, the results of the job are there, but throughout the process the grey 'worker offline' tag was and still visible, even though the worker is very much online.

- _UUID of worksheet where problem occurred:_ 0x21b86b64910945c7b1d5775da875ff4f
- _UUID of problem bundle (please don't delete):_ 0x3e47532993dc424580ba9684b547d375 [link](https://worksheets.codalab.org/bundles/0x3e47532993dc424580ba9684b547d375)

While the assumed problem of the job not running is essentially not an issue, the "Dependency quota full" message does still show up, and the 'worker_offline' tag is incorrect and misleading. Any idea what could be causing this?

**Comment by percyliang** [comment]
Is this still an outstanding issue?

**Comment by GreenParachute** [comment]
We never managed to resolve the issue, but thankfully it didn't cause problems for us as the jobs did run in the background and generated outputs in spite of the 'worker_offline' error message. Could have something to do with our particular local codalab installation, perhaps something got corrupted. In any case, as long as the jobs are running we're happy, so if there's no immediate fix happy to close the issue.
