### ISSUE TITLE
application for extra disk quota

### ISSUE THREAD

**Issue by linxin6** [codalab/codalab-worksheets#4479]
Hello, may I please be allocated an additional 30GB of storage space? I received the following error message when attempting to upload a file:

UsageError: Upload failed: Can't save bundle, bundle size 880313724 greater than user's disk quota left: 103288790.0

It says here that my quota is only 100MB, but I need to upload data of 880MB and a model of over 10GB.

my username:SolitudeLin
my email:1090090659@qq.com

**Comment by yifanmai** [comment]
Hi, I've granted 20 GB of disk quota to your account (SolitudeLin).

**Comment by linxin6** [comment]
Thank you so much.

**Comment by linxin6** [comment]
I'm sorry to bother you again. Due to the complexity of my program, I have spent too much time debugging it. Could you please allocate me another hour?

**Comment by linxin6** [comment]
> I'm sorry to bother you again. Due to the complexity of my program, I have spent too much time debugging it. Could you please allocate me another hour?

I apologize for disturbing you again, but could you please allocate me some more time? I need to continue validating my paper using Codalab.

**Comment by linxin6** [comment]
> Hi, I've granted 20 GB of disk quota to your account (SolitudeLin).

I apologize for disturbing you again, but could you please allocate me some more time? I need to continue validating my paper using Codalab.
