### ISSUE TITLE
At the moment Codalab run not working

### ISSUE THREAD

**Issue by korquad** [codalab/codalab-worksheets#448]
Hello, there

My run bundle is not working but seems to be staged forever.
Even my simple python script printing hello is not working but staged.
Is there any issues in Codalab running environment? Isn't it so busy?
Uuid is 0x2989a12bdfbc47568ff2c2760982441b.
Check it please.

**Comment by percyliang** [comment]
Codalab has been very busy lately, but it seems like the job has finally run.
