### ISSUE TITLE
Application for extra disk quota

### ISSUE THREAD

**Issue by Dakingrai** [codalab/codalab-worksheets#4480]
Hello, 

I am currently using Codalab to submit my model and script for a competition, but I am unable to proceed due to my model's size exceeding the 10GB limit. Could you please increase my disk space to 30 GB? Thank you!

My account details- 
my username: daking
my email: drai2@gmu.edu

**Comment by yifanmai** [comment]
Hi, I've granted 20 GB of disk quota to your account (daking).

**Comment by Dakingrai** [comment]
Hi @yifanmai, Thank you for allocating the extra space. I'm trying to run T5-3B and 20 GB seems not enough for the inference. Is it possible to increase the disk size to 30GB? Thank you!
