### ISSUE TITLE
Disk quota request

### ISSUE THREAD

**Issue by sangHa0411** [codalab/codalab-worksheets#4484]
Hi! I am preparing [Korquad Competition](https://korquad.github.io/KorQuad%201.0/). 
So I signed up codalab and learning how to use codalab.

But I can use only 100M disk quota, though I need minimum 10G for trained model.

I wrote [google form](https://forms.gle/NumtS9uYe1PSB1ts6) on Monday, but I have got no answer yet.

Could you please improve my disk quota? It is urgent because I also need the evaluation results for seminar in company.

Here is some information.
username: sangha110495
email: [sangha110495@lgresearch.ai](sangha110495@lgresearch.ai)
uuid:https://worksheets.codalab.org/worksheets/0xcdd2633dae5f4ed2865a759f59a237ff

Thank you in advance for any help you might be able to provide.

@yifanmai

**Comment by epicfaace** [comment]
Your request has been processed, thanks!

**Comment by sangHa0411** [comment]
Thank you for update disk quota! 
Can you update time quota from 1h to 5h or more please?
@epicfaace

**Comment by epicfaace** [comment]
Done

**Comment by sangHa0411** [comment]
Hi! I am preparing [Korquad 2.0 Competition](https://korquad.github.io). 

It has many data and requires much more time for inference than [Korquad 1.0 Competition](https://korquad.github.io/KorQuad%201.0/). 
I need more time to inference this competition dataset.
So can you update time quota from 5h to 50h or more please?

Thank you!
@epicfaace
