### ISSUE TITLE
Insufficient disk space

### ISSUE THREAD

**Issue by shuoshuo0** [codalab/codalab-worksheets#4486]
Hello, can you allocate 30GB of storage space to me? I received the following error message when trying to upload a file:
UsageError: Upload failed: Can't save bundle, bundle size 4740283961 greater than the user remaining disk quota :103288790.0
It shows that my quota is only 100MB, but I need to upload 880MB of data and more than 10GB of models.
My username is PERCENT
My E-mail address is :jishuo.zhang@percent.cn

**Comment by epicfaace** [comment]
Your request has been processed, thanks!
