### ISSUE TITLE
[USER ISSUE] Worksheet not found after open it from my dashboard

### ISSUE THREAD

**Issue by brucepang** [codalab/codalab-worksheets#4487]
**Describe the bug**
A worksheet that I created recently couldn't be opened. 

**Codalab Information**
- *Your username*: brucepang
- *UUID of worksheet where problem occurred*: 0x8c8bde9ad7dd4a888877a76bffe8fd5b
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:  Not found: '/worksheets/0x8c8bde9ad7dd4a888877a76bffe8fd5b'
 - *OS (if on CLI)*:
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*; Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. logged into my account
2. clicked that worksheet, [Spider test evaluation [hidden]](https://worksheets.codalab.org/worksheets/0x8c8bde9ad7dd4a888877a76bffe8fd5b) , from owned by me tab 
3. See error

**Expected behavior**
Able to see the worksheet

**Screenshots**
![image](https://github.com/codalab/codalab-worksheets/assets/18299241/f6a99d97-f3db-4549-abe8-4708bb7d5ee3)

**Additional context**

**Comment by epicfaace** [comment]
Thanks for reporting, we're looking into this.

The worksheet exists, but looks like some error is happening in the backend -- will look into this.

`Got duplicate values 1684126341 and 1684126341 for key last_updated. ...`

**Comment by epicfaace** [comment]
Related to https://github.com/codalab/codalab-worksheets/issues/4488.

**Comment by pranavjain** [comment]
Should be fixed now
