### ISSUE TITLE
Insufficient GPU memory issue.

### ISSUE THREAD

**Issue by linxin6** [codalab/codalab-worksheets#4491]
Hello developer, codalab is a great platform, but I found that the 12GB GPU allocated by codalab cannot meet my requirements. My model requires at least 24GB of GPU memory. Could you please assign a GPU with larger memory to me or guide me on how to use my own GPU to run the code?

**Comment by AndrewJGaut** [comment]
Hello,

Unfortunately, we cannot assign a GPU with higher than 12GB RAM. But, I can help guide you to use your own GPU with our infrastructrue!

CodaLab is designed to allow users to run their own workers and hook them up to CodaLab. (A worker is just something with compute and an internet connection.) We have instructions for running your own worker [here](https://codalab-worksheets.readthedocs.io/en/latest/Execution/#running-your-own-worker). Feel free to leave more comments if you're having a hard time with the instructions!

**Comment by linxin6** [comment]
If the GPU memory cannot be increased, can I use CPU debugging instead? Can more running time be allocated to my account? I think I need an additional 5 hours of time.
username: SolitudeLin
email:1090093659@qq.com

**Comment by linxin6** [comment]
> Hello,
> 
> Unfortunately, we cannot assign a GPU with higher than 12GB RAM. But, I can help guide you to use your own GPU with our infrastructrue!
> 
> CodaLab is designed to allow users to run their own workers and hook them up to CodaLab. (A worker is just something with compute and an internet connection.) We have instructions for running your own worker [here](https://codalab-worksheets.readthedocs.io/en/latest/Execution/#running-your-own-worker). Feel free to leave more comments if you're having a hard time with the instructions!

**Comment by linxin6** [comment]
> Hello,
> 
> Unfortunately, we cannot assign a GPU with higher than 12GB RAM. But, I can help guide you to use your own GPU with our infrastructrue!
> 
> CodaLab is designed to allow users to run their own workers and hook them up to CodaLab. (A worker is just something with compute and an internet connection.) We have instructions for running your own worker [here](https://codalab-worksheets.readthedocs.io/en/latest/Execution/#running-your-own-worker). Feel free to leave more comments if you're having a hard time with the instructions!

If the GPU memory cannot be increased, can I use CPU debugging instead? Can more running time be allocated to my account? I think I need an additional 5 hours of time.
username: SolitudeLin
email:[1090093659@qq.com](mailto:1090093659@qq.com)

**Comment by percyliang** [comment]
Time quota granted.
