### ISSUE TITLE
Facing issues when trying to download BERT model for SQuaD 2.0 leaderboard submission

### ISSUE THREAD

**Issue by sidarora1990** [codalab/codalab-worksheets#4495]
As per the instructions mentioned for SQuaD 2.0 leaderboard (https://worksheets.codalab.org/worksheets/0x8212d84ca41c4150b555a075b19ccc05/), each user would be provided a 10GB of disk space. But, it seems I am getting just 100 MB of disk space(PFA - squad_disk_issue.jpg, squad_disk_issue2.jpg). As of now, I am unable to upload anything on Codalab. So, I humbly request you to please help me out in resolving this issue.

**Codalab Information**
- *Your username*: sidarora1990
- *UUID of worksheet where problem occurred*: Squad_exp1
- *Error message received from Codalab (if applicable)*: User Disk Quota exceeded (PFA)
 - *OS (if on CLI)*: N/A
 - *Codalab CLI Version: N/A
![squad_disk_issue](https://github.com/codalab/codalab-worksheets/assets/13280479/856e3d3a-4e10-46d1-9972-57347c1add2a)
 (if on CLI)*: 
 - *Browser (if on Web)*;
![squad_disk_issue2](https://github.com/codalab/codalab-worksheets/assets/13280479/3e9e786f-6705-4150-b0ee-d3fd521f0b5f)

**Expected behavior**
As per the instructions on SQuad 2.0 leaderboard submission, each user should be given a disk space of 10 GB which I am not getting currently (PFA-Ssquad_disk_allot.png).
![squad_disk_allot](https://github.com/codalab/codalab-worksheets/assets/13280479/d547cb8e-5a24-404e-9652-d510e7f146f0)

**Screenshots**
squad_disk_issue.jpg
squad_disk_issue2.jpg
squad_disk_allot.png

**Additional context**
N/A

**Comment by wwwjn** [comment]
Hi @sidarora1990 , thanks for using CodaLab! The disk quota request has already been fulfilled and the disk quota of your account is 10GB right now. If you have any more questions, feel free to contact us again!
