### ISSUE TITLE
Facing issue while trying to download BERT & RoBERTa model for SQUAD2.0 leaderboard submission

### ISSUE THREAD

**Issue by narayanm-dev** [codalab/codalab-worksheets#4496]
**Facing issue while trying to download BERT & RoBERTa model for SQUAD2.0 leaderboard submission**
Facing issue while trying to download BERT & RoBERTa model for SQUAD2.0 leaderboard submission.

**Codalab Information**
- *Your username*: cresttop8
- *UUID of worksheet where problem occurred*: eka_nlp1
- *Error message received from Codalab (if applicable)*: User Disk Quota exceeded (PFA)
![Disk_Quota_Exceeded](https://github.com/codalab/codalab-worksheets/assets/36432053/4212bb5f-7db9-436a-a813-953c474c758a)

 - *OS (if on CLI)*: Windows
 - *Codalab CLI Version (if on CLI)*: 1.6.3
 - *Browser (if on Web)*; N/A

**Expected behavior**
As per the instructions on SQuad 2.0 leaderboard submission, each user should be given a disk space of 10 GB which I am not getting currently (PFA-Squad_disk_allot.png). Please update this to 10 GB.

![Squad_Disk_Allot3](https://github.com/codalab/codalab-worksheets/assets/36432053/32e12a87-bc89-46a0-b340-5c4acb7ce942)
![SQuad_Disk_Allot](https://github.com/codalab/codalab-worksheets/assets/36432053/1e06bb76-7771-44c1-b3c8-044287848840)

**Screenshots**
squad_disk_issue.jpg
squad_disk_issue2.jpg
squad_disk_allot.png

**Comment by AndrewJGaut** [comment]
Done. Sorry for the delay. With regard to the instructions, we need to update them. This year, we had some attackers who were taking advantage of the free compute to mine bitcoin, so we changed the default disk and time quotas for non-edu emails.

Sorry about that!
