### ISSUE TITLE
Facing time related issue when trying to follow SQuad 2.0 leaderboard instructions for evaluation on test set. 

### ISSUE THREAD

**Issue by sidarora1990** [codalab/codalab-worksheets#4498]
Error: Requested more time (30m0s) than user time quota left (29m50s) by 9.7s

**Codalab Information**
- *Your username*: sidarora1990
- *UUID of worksheet where problem occurred*: Squad_exp1
- *UUID of problem bundle (please don't delete)*: 0x5f32d9aef11e430d87b82f992a60762c
- *Error message received from Codalab (if applicable)*: Requested more time (30m0s) than user time quota left (29m50s) by 9.7s
 - *Browser (if on Web)*; Chrome

**To Reproduce**
Steps to reproduce the behavior : Please follow SQuaD 2.0 leaderboard instructions from [https://worksheets.codalab.org/worksheets/0x8212d84ca41c4150b555a075b19ccc05/]
1. The attached error ("codalab_time_error.png") occurs in Step 3 (Run evaluation script on the dev set) and similarly on test set step as well.
2. See error: codalab_time_error.png
![codalab_time_error](https://github.com/codalab/codalab-worksheets/assets/13280479/a0d
![codalab_time_squad1](https://github.com/codalab/codalab-worksheets/assets/13280479/0f9caf2a-c841-47fc-a1a3-c7d0408c5ac7)
dc316-6fc1-4129-9a33-bff7b0bf6e62)

**Expected behavior**
Since I am following SQuaD 2.0 leaderboard instructions, so I need to complete all the steps without any error in order to make a successful submission.

**Screenshots**
1. codalab_time_error.png: Error on codalab platform
2. codalab_time_squad1: Step on which error is coming

**Comment by AndrewJGaut** [comment]
Done. Sorry for the delay. With regard to the instructions, we need to update them. This year, we had some attackers who were taking advantage of the free compute to mine bitcoin, so we changed the default disk and time quotas for non-edu emails.

Sorry about that!
