### ISSUE TITLE
Not getting Default Disk space in my account, Unable to upload bundle

### ISSUE THREAD

**Issue by hemantsinghiitk** [codalab/codalab-worksheets#4499]
**Describe the bug**
I have only 100mb of disk space in my account instead of the Default 10gb mentioned in Squad 2.0 Submission Guide, as a result I'm unable to upload files in my worksheet. I have to upload around model of around 160mb.

**Codalab Information**
- *Your username*: hemant
- *UUID of worksheet where problem occurred*: 0x30003ba5acb24a2f9744eca734195dd6
- *UUID of problem bundle (please don't delete)*:  couldn't upload bundle due to disk size
- *Error message received from Codalab (if applicable)*: UsageError: Upload failed: Can't save bundle, bundle size 177282719 greater than user's disk quota left: 104726928.0
 - *OS (if on CLI)*: windows 11
 - *Codalab CLI Version (if on CLI)*: 1.6.3
 - *Browser (if on Web)*; NA

**To Reproduce**
Steps to reproduce the behavior :
Screenshot of error and command attached below.

**Expected behavior**
The file should have uploaded Successfully.

**Screenshots**
![Screenshot 2023-07-03 132127](https://github.com/codalab/codalab-worksheets/assets/135040709/e66efe63-b429-4d2d-a61a-3952f6a342db)

**Additional context**
NA

**Comment by AndrewJGaut** [comment]
Done. Sorry for the delay. With regard to the Submission Guide, we need to update it. This year, we had some attackers who were taking advantage of the free compute to mine bitcoin, so we changed the default disk and time quotas for non-edu emails.

Sorry about that!
