### ISSUE TITLE
Not getting Default Disk space in my account, Unable to upload bundle

### ISSUE THREAD

**Issue by chinmayeedongre** [codalab/codalab-worksheets#4500]
Describe the bug
I have only 100mb of disk space in my account instead of the Default 10gb mentioned in Squad 2.0 Submission Guide, as a result I'm unable to upload files in my worksheet. I have to upload around model of around 160mb.

Codalab Information

Your username: Cdongre
registered email id - chinmayeedongrekd@gmail.com
UUID of worksheet where problem occurred: 0x45e2684fa7e94e7981fb2eb7c7ca37a4
UUID of problem bundle (please don't delete): couldn't upload bundle due to disk size
Error message received from Codalab (if applicable): Upload failed: Can't save bundle, bundle size 361761625 greater than user's disk quota left: 104726928.0
OS (if on CLI): macOS
Codalab CLI Version (if on CLI): 1.6.3
Browser (if on Web); NA
To Reproduce
Steps to reproduce the behavior :
Screenshot of error and command attached below.

<img width="1438" alt="image" src="https://github.com/codalab/codalab-worksheets/assets/23479149/e536ceb4-aa30-4fe4-8e5e-b6dbab96f719">

<img width="1436" alt="Screen Shot 1402-04-12 at 21 18 10" src="https://github.com/codalab/codalab-worksheets/assets/23479149/459ec78c-7757-452d-94fd-43b298a48313">

**Comment by AndrewJGaut** [comment]
Done. Sorry for the delay. With regard to the Submission Guide, we need to update it. This year, we had some attackers who were taking advantage of the free compute to mine bitcoin, so we changed the default disk and time quotas for non-edu emails.

Sorry about that!

**Comment by chinmayeedongre** [comment]
Hi Andrew , Still I haven't received 10gb disk quota and I'm unable to upload files.
<img width="375" alt="image" src="https://github.com/codalab/codalab-worksheets/assets/23479149/b9444266-b1ec-4399-8c9b-6a15c954991c">

<img width="375" alt="image" src="https://github.com/codalab/codalab-worksheets/assets/23479149/b5254a49-4c49-4395-878e-5123350871db">

**Comment by chinmayeedongre** [comment]
<img width="816" alt="image" src="https://github.com/codalab/codalab-worksheets/assets/23479149/6850cbaa-0e56-42b4-9910-823e41619583">
