### ISSUE TITLE
Unable to upload bundle due to unavailability of default disk space

### ISSUE THREAD

**Issue by Subarna-saha16** [codalab/codalab-worksheets#4502]
Describe the bug
I have only 100mb of disk space in my account instead of the Default 10gb mentioned in Squad 2.0 Submission Guide, as a result I'm unable to upload files in my worksheet. I have to upload a model of around 150mb.

Codalab Information
Your username: subarnasaha
registered email id - [subarnasaha2006@gmail.com]
UUID of worksheet where problem occurred: 0x863e454f1f2246ebaa1fff4fde6239f6
UUID of problem bundle (please don't delete): couldn't upload bundle due to disk size
Error message received from Codalab (if applicable): Upload failed: Can't save bundle, bundle size 159655077 greater than user's disk quota left: 104742551.0
OS (if on CLI): Windows 8
Codalab CLI Version (if on CLI): 1.6.3
Browser (if on Web); NA
To Reproduce
Steps to reproduce the behavior :
Screenshot of error and command attached below.

Expected behavior
The file should be uploaded successfully.

Screenshots
![codalab_error](https://github.com/codalab/codalab-worksheets/assets/79191903/a67c4999-e545-48d8-842b-6535ee1b6e95)

**Comment by Fu-Dayuan** [comment]
+1

**Comment by AndrewJGaut** [comment]
Done. Sorry for the delay. With regard to the Submission Guide, we need to update it. This year, we had some attackers who were taking advantage of the free compute to mine bitcoin, so we changed the default disk and time quotas for non-edu emails.

Sorry about that!
