### ISSUE TITLE
application for extra disk quota and time qouta[USER ISSUE]

### ISSUE THREAD

**Issue by Fu-Dayuan** [codalab/codalab-worksheets#4504]
Hi! I am preparing spider(https://yale-lily.github.io/spider)
So I signed up codalab and learning how to use codalab.

But I can use only 100M disk quota, though I need minimum 1.5G(different from the what in the google from) for upload database and other meterial.

I wrote google form twice, but I have got no answer yet.

Could you please improve my disk quota? It is urgent because I also need the evaluation results.

Here is some information.
username: fudayuan
email: fudayuan2000@gmail.com

(also I am curious about the time quota, is that mean the max time in one run? maybe I should have a 1day quota(different from the what in the google from)
Thank you in advance for any help you might be able to provide.

**Comment by AndrewJGaut** [comment]
Got it, just filled your request! Time quota means total execution time you have; i.e., if you used 10 hours for a single run, that would permanently count against your time quota. For now, I gave you 36 hours (a day and half), so hopefully that will be sufficient!
