### ISSUE TITLE
Any dependency bundle size limit when running a job?

### ISSUE THREAD

**Issue by kayemkim** [codalab/codalab-worksheets#451]
Hi, there.

I'm trying to run a job which has dependencies with the bundles.
Some bundles have large size which is more than 500 MB.
I cannot run a job because those large files' dependies are not working.
Is there any bundle size limit when running a job?

**Comment by nikhilxb** [comment]
Any time or disk usage is subject to your user quota: try running `cl uinfo` and see how much disk you have remaining? If you're at the quota limit, try deleting bundles that you're not using any more.

**Comment by bkgoksel** [comment]
On top of that, large dependencies should not cause any errors. Errors you're seeing may be due to a system bug. Could you share the UUID of your bundle that has failing dependencies?

**Comment by kayemkim** [comment]
@bkgoksel 
The UUID of my bundle is 0x7f25e35da4f14b0fba827edfb72aa10a.

**Comment by percyliang** [comment]
We have made a number of dependency manager fixes, closing.  Please re-open if this is still an issue.
