### ISSUE TITLE
[USER ISSUE]

### ISSUE THREAD

**Issue by Bhavya9991** [codalab/codalab-worksheets#4520]
Unable to access Codalabs (url: https://codalab.lisn.upsaclay.fr/) getting 504 network timeout issue.

Tried flushing the DNS and resetting the DNS server but nothing helped.

DNS is not able to resolve the URL. 
**Additional context**

**Comment by yifanmai** [comment]
Hi, I am able to access the website that you linked to. That website is also externally accessible (see https://isitdownorjust.me/codalab-lisn-upsaclay-fr/). It is likely that the issue is with your network connection or DNS provider; could you check that those are working?

**Comment by Bhavya9991** [comment]
Hi,

I think it was an outage for some time back when I created this ticket.
The next day, I was able to access it.


Thank you for your help.
