### ISSUE TITLE
The leaderboard is not showing scores in the specified ordering[USER ISSUE]

### ISSUE THREAD

**Issue by Bhavya9991** [codalab/codalab-worksheets#4528]
I have hosted a private competition which can be accessed via the following link: https://codalab.lisn.upsaclay.fr/competitions/15402?secret_key=9fd0e11a-abc8-4a23-8135-a54b8e2f0acc

The metric with the lowest ordering (1 in my case) should get the highest priority in ranking but it is not working as specified.
![Screenshot 2023-09-10 094425](https://github.com/codalab/codalab-worksheets/assets/59372130/c9c895ab-a241-49cd-8de2-3289d03b3637)
![Screenshot 2023-09-10 095002](https://github.com/codalab/codalab-worksheets/assets/59372130/8df932eb-008a-4259-9da6-5da4f91ff7c6)

[competition_15402.zip](https://github.com/codalab/codalab-worksheets/files/12567457/competition_15402.zip)

![Screenshot 2023-09-10 095536](https://github.com/codalab/codalab-worksheets/assets/59372130/ffd1a118-3a41-4e3b-a69c-cfe84f2f21e8)

I have attached some relevant snapshots for reference and the competition yaml file as well. You can see that in the above image that the leaderboard is messed up. The scores against the username are also not in the right order.

Please help with this issue and let me know if you need more information.

**Comment by epicfaace** [comment]
Hi, it looks like you are using CodaLab Competitions, not CodaLab Worksheets. Please open an issue here: https://github.com/codalab/codalab-competitions
