### ISSUE TITLE
specify  docker image fail

### ISSUE THREAD

**Issue by handsomefun** [codalab/codalab-worksheets#453]
I participate a competition which need to submit code and evaluate performance by codalab.
My code need fasttext and jieba python package, so i build a docker image and push to docker hub. 
I have pull this image from docker hub and run it, i can import fasttext, jieba successfully  in python command line.

But when I run my python script in codalab with --request-docker-image to specifiy docker image. 
`
run 'fst_predict.py:0x0c0c2f' 'sir.model.ft.bin:0x5e4e5c' 'dev.json:0x1f96bc' 'python fst_predict.py dev.json predict.json --request-docker-image floydfan/fasttext-jieba:0.0.1'`

this task fail fast, and error log

`Traceback (most recent call last):
  File "fst_predict.py", line 8, in <module>
    import fasttext
ImportError: No module named fasttext`

It fail so fast, seems do not run in docker. I think pull docker image from docker hub will cost much time.

uuid: 0x1f79b90f28ea405e85be64e60be90125

**Comment by fabeschan** [comment]
`--request-docker-image floydfan/fasttext-jieba:0.0.1` should sit outside the python command

**Comment by handsomefun** [comment]
@fabeschan 
thanks!

**Comment by bkgoksel** [comment]
Hopefully this should work. Thanks for the guidance @fabeschan @handsomefun do let us know if you run into any other issues!

**Comment by fabeschan** [comment]
np
