### ISSUE TITLE
Run bundles stuck on finalizing and using up time quota

### ISSUE THREAD

**Issue by yicheng-w** [codalab/codalab-worksheets#454]
Hi, I attempted to kill two running bundles 4 days ago (uuids of 0xed9780e96bd44907aad4fbabd3e3f090 and 0xaf3c3ee1ad4549f19bc8a90d20abccf4), and the bundles have been stuck at 'finalizing' for 3 days. Moreover, the time-quota on my account from running 'uinfo' displays:

time           : 761y172d / 7d0h (3970535.7%)

which doesn't seem correct.

Furthermore, other bundles that my co-workers have been trying to run have been stucked at the `staging` phase. I am unsure if these two issues are related, but we've not been able to run any commands.

**Comment by bkgoksel** [comment]
Hi Yicheng,
Our apologies for the issues. We recently experienced two independent issues affecting both our worker machines and our central server, and as a result some runs fell into degenerate states. We have a fix for the time calculation issue that we experience in this particular degenerate state but it hasn't been deployed to production yet. I'll go ahead and kill the offending bundles you reported and make sure your time quota use is restored. 

For the staging runs, they should start running as of last night/this morning as we brought back all our workers (and couple extra machines to make up for the increased queues). Please let us know

**Comment by yicheng-w** [comment]
Everything works now, thanks for the help! I'll close the issue.
