### ISSUE TITLE
Insufficient disk space

### ISSUE THREAD

**Issue by qidi1** [codalab/codalab-worksheets#4553]
Hello, can you allocate 30GB of storage space to me? I received the following error message when trying to upload a file: UsageError: Upload failed: Can't save bundle, user disk quota exceeded. Bundle size 5368709120 greater than the user's disk quota left: -5268812000.0, It shows that my quota is only 100MB, but I need to upload more than 24GB of llm models.
My username is tomato
My E-mail address is :[qidiwj1234@gmail.com](mailto:qidiwj1234@gmail.com)

**Comment by qidi1** [comment]
I need to run the llm model on codalab, which requires approximately 40GB of GPU memory. I'm not sure how to increase the available video memory.

**Comment by pranavjain** [comment]
Can you please fill this form?

https://docs.google.com/forms/d/e/1FAIpQLSebCBrglB7z2R7OeHJ_NsVWcUcHVMAW4AQnFxNt0YvTS-rDNA/viewform?usp=sf_link
