### ISSUE TITLE
[Time sensitive] Site down

### ISSUE THREAD

**Issue by msaroufim** [codalab/codalab-worksheets#4558]
Hi I'm one of the organizers of the LLM efficiency competition which is due on Wednesday Oct 25 https://llm-efficiency-challenge.github.io/

We use HELM for model evals which in turn relies on datasets you host https://github.com/stanford-crfm/helm/issues/1930

Am hoping this is just a transient issue but please let me know if not cause I'd need to make some major changes to the way we do our dataset eval very close to the competition due date

**Comment by pranavjain** [comment]
CodaLab is back online now. Please do let us know if you are still facing issues.
