### ISSUE TITLE
Azure Batch Workers Pools are not working

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#4563]
This is blocking all the jobs on CodaLab right now.

@epicfaace did create [pools](https://github.com/codalab/deployment/pull/262) but this needs more investigation.

**Comment by sangHa0411** [comment]
I think I have related issue.
I requested 1 cpu and 2gb memory for running simple command.
But This command has been staged for 2~3 days and not started.
About 2 weeks ago, this issue didn't happened at all, so I think there must be some problem.

**Comment by pranavjain** [comment]
@sangHa0411 Yes, it is related to the same issue. We are looking into it. Thanks for your patience.

**Comment by linxin6** [comment]
> @sangHa0411 Yes, it is related to the same issue. We are looking into it. Thanks for your patience.

Hi, have you solve this question?

**Comment by sangHa0411** [comment]
@linxin6 

I think it hasn't solved perfectly.
Just small amount of memory and cpu request has been done, but gpu request which is necessary for me has not been started (It's status keeps staged status).

**Comment by linxin6** [comment]
thanks!

sangha110495 ***@***.***> 于2023年11月20日周一 21:41写道：
