### ISSUE TITLE
[USER ISSUE] Device unassigned issue (not changed from stage to starting)

### ISSUE THREAD

**Issue by switiz** [codalab/codalab-worksheets#4569]
**Describe the bug**
I requested GPU work and it hasn't worked for a week.
To check, I created a new worksheet and tested it with a simple command like ls and it doesn't go from stage to starting.
These issues seem to occur across worksheets.

Do you know anything about this issue?

**Comment by pranavjain** [comment]
We have an issue related to GPU pool. We are tracking it. Closing this issue for now.
