### ISSUE TITLE
Official demo doesn't work

### ISSUE THREAD

**Issue by Promise-Lv** [codalab/codalab-worksheets#4570]
**Describe the bug**
I follow the instructions of the official demo, which uses a single python file to output something from a file, however, the bundle status stays on staged all the time.

Is there anythong wrong with my operation?

**Codalab Information**
- *Your username*: xiaoketongxue2023
- *UUID of worksheet where problem occurred*: xiaoketongxue2023-test
- *UUID of problem bundle (please don't delete)*: 0x0f3e7084c3b949c4bad4ee690e7e9896
- *Error message received from Codalab (if applicable)*:
 - *OS (if on CLI)*: Linux version 3.10.0-1160.88.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) )
 - *Browser (if on Web)*;

![图片](https://github.com/codalab/codalab-worksheets/assets/52311141/03826177-ac8f-4a2c-bc74-2feb41910914)

**Comment by pranavjain** [comment]
Hi @Promise-Lv,

We have an ongoing issue which is stopping the execution of bundles right now. We are actively looking into it and hope to resolve it soon!

**Comment by pranavjain** [comment]
Closing this issue for now.
