### ISSUE TITLE
Migration Issue: Unexpected End of Data

### ISSUE THREAD

**Issue by AndrewJGaut** [codalab/codalab-worksheets#4572]
Traceback (most recent call last):\n  File \"codalab/migration.py\", line 316, in migrate_bundle
bundle_uuid, disk_location, bundle_info, is_dir, target_location\n  File \"codalab/migration.py\", line 219, in sanity_check   new_file_list = tarfile.open(fileobj=f, mode='r:gz').getnames()
File \"/opt/conda/lib/python3.7/tarfile.py\", line 1769, in getnames
    return [tarinfo.name for tarinfo in self.getmembers()]\n  File \"/opt/conda/lib/python3.7/tarfile.py\", line
1761, in getmembers
self._load()        # all members, we first have to\n  File \"/opt/conda/lib/python3.7/tarfile.py\", line 2348, in _load
tarinfo = self.next()
File \"/opt/conda/lib/python3.7/tarfile.py\", line 2281, in next
raise ReadError(\"unexpected end of data\")\ntarfile.ReadError: unexpected end of data

**Comment by percyliang** [comment]
How do you reproduce this?

**Comment by AndrewJGaut** [comment]
{
    "unexpected end of data": {
        "uuid": [
            "0x0010b52d853b46bbb522bff4c80c21b4",
            "0x004192f64515479ebe14145cf4eefc53",
            "0x00517d4ac0e448b1b5d6299af1fe5c86",
            "0x005410fe6f5f48088f10e7b197c77d52",
            "0x00613a51b5ae48b4b9e501556e64865b",
            "0x006e83c2761e4c43b9b88bfbed725f35",
            "0x007c8af66f684838afe617c13a16ce8d",
            "0x007dbf30e3a145f483789f3e2d1889aa",
            "0x00b34a5b271a4e7c9bdafb1b606838f0",
            "0x00e15e636ed449ada2eee4d76ddc103b",
            "0x011a84546043492c96371835ebaed2d2",
            "0x013e2f4933a74ae38b2d6a1be18509ca",
            "0x0162e3ce38774e81a9bbff7baf254f78"
        ],
        "traceback": "Traceback (most recent call last):\n  File \"codalab/migration.py\", line 316, in migrate_bundle\n    bundle_uuid, disk_location, bundle_info, is_
dir, target_location\n  File \"codalab/migration.py\", line 219, in sanity_check\n    new_file_list = tarfile.open(fileobj=f, mode='r:gz').getnames()\n  File \"/opt/con
da/lib/python3.7/tarfile.py\", line 1769, in getnames\n    return [tarinfo.name for tarinfo in self.getmembers()]\n  File \"/opt/conda/lib/python3.7/tarfile.py\", line
1761, in getmembers\n    self._load()        # all members, we first have to\n  File \"/opt/conda/lib/python3.7/tarfile.py\", line 2348, in _load\n    tarinfo = self.ne
xt()\n  File \"/opt/conda/lib/python3.7/tarfile.py\", line 2281, in next\n    raise ReadError(\"unexpected end of data\")\ntarfile.ReadError: unexpected end of data\n",
        "count": 13
    },

**Comment by AndrewJGaut** [comment]
Example UUID: 0x00613a51b5ae48b4b9e501556e64865b

**Comment by AndrewJGaut** [comment]
Reproduce with instructions in [this doc](https://docs.google.com/document/d/19HdlX0RrTDYw924sTT5F7jsuUr8IOrNYRj1h5d22AZI/edit) from section "Reproduce the issue in local / dev environment"

**Comment by wwwjn** [comment]
> 0x00613a51b5ae48b4b9e501556e64865b

This issue actually can not be reproduced with this bundle in the dev environment.

**Comment by percyliang** [comment]
Don't need this for migrating the bulk of the bundles.
