### ISSUE TITLE
Migration: Zip issue

### ISSUE THREAD

**Issue by AndrewJGaut** [codalab/codalab-worksheets#4573]
Traceback (most recent call last):\n  File \"codalab/migration.py\", line 320, in migrate_bundle   self.adjust_quota_and_upload_to_blob(bundle_uuid, bundle_location, is_dir)\n  File \"codalab/migration.py\", line 288, in adjust_quota_and_upload_to_blob
    raise e  # still raise the expcetion to outer try-catch wrapper
File \"codalab/migration.py\", line 280, in adjust_quota_and_upload_to_blob
    self.upload_to_azure_blob(bundle_uuid, bundle_location, is_dir)
File \"codalab/migration.py\", line 164, in upload_to_azure_blob
    source_fileobj = zip_directory(bundle_location)
File \"/opt/codalab-worksheets/codalab/worker/file_util.py\", line 150, in zip_directory
    with open(tmp_zip_name, \"rb\") as out:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp1v4u5xto/tmp.zip'

**Comment by AndrewJGaut** [comment]
Example UUID: 0x004b29f3e7d544d3b61b04259e40dc9a

**Comment by AndrewJGaut** [comment]
Reproduce with instructions in [this doc](https://docs.google.com/document/d/19HdlX0RrTDYw924sTT5F7jsuUr8IOrNYRj1h5d22AZI/edit) from section "Reproduce the issue in local / dev environment"

**Comment by HidyHan** [comment]
I followed the doc but couldn't reproduce for 0x004b29f3e7d544d3b61b04259e40dc9a. Here's what I have got: 
![Screenshot from 2023-11-28 20-50-34](https://github.com/codalab/codalab-worksheets/assets/14281098/fe881e15-e788-47fc-8211-3ab96854d0f4)
![Screenshot from 2023-11-28 20-48-20](https://github.com/codalab/codalab-worksheets/assets/14281098/e93fc008-524c-4646-9210-9ebf839705a9).

0 bundles uploaded, though cl print shows some content for the worksheet.

**Comment by wwwjn** [comment]
> I followed the doc but couldn't reproduce for 0x004b29f3e7d544d3b61b04259e40dc9a. Here's what I have got: ![Screenshot from 2023-11-28 20-50-34](https://private-user-images.githubusercontent.com/14281098/286480866-fe881e15-e788-47fc-8211-3ab96854d0f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDc1MDcsIm5iZiI6MTcwMTI0NzIwNywicGF0aCI6Ii8xNDI4MTA5OC8yODY0ODA4NjYtZmU4ODFlMTUtZTc4OC00N2ZjLTgyMTEtM2FiOTY4NTRkMGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4NDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MmM4YTdlN2JiODNmMzY3NTJiODEyZGJmZjE3MjI0MzRjNWMzZWNlY2MyNDY3OWUwN2E1N2UyOTFiMzU2OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kUyblt1lvzM4uSa2ttUauSfWfkO6ZiPuHCLk1HDoadw) ![Screenshot from 2023-11-28 20-48-20](https://private-user-images.githubusercontent.com/14281098/286480871-e93fc008-524c-4646-9210-9ebf839705a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDc1MDcsIm5iZiI6MTcwMTI0NzIwNywicGF0aCI6Ii8xNDI4MTA5OC8yODY0ODA4NzEtZTkzZmMwMDgtNTI0Yy00NjQ2LTkyMTAtOWViZjgzOTcwNWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4NDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNmFmMmRjYmE0Zjk0ZDdmYzUyMDhmZjA2NzVmOTcwZWYyZmIyMTI0YTUzMDRlOGY5Yjc4NzA1NzJhZDUwMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oJzK5kK867fXhximz1ML2z_0YO5SK6W22iTn21WzW78).
> 
> 0 bundles uploaded, though cl print shows some content for the worksheet.

This is a bug because of function `limit()` [here](https://github.com/codalab/codalab-worksheets/blob/128bf4df3b0045fd0d4696c6fdd0006daed300cb/codalab/migration.py#L74C17-L74C33). It should not be None. Change `max_results={some number}` works.

<img width="1104" alt="image" src="https://github.com/codalab/codalab-worksheets/assets/40016222/3fd83107-0307-4954-8669-ceb0d516d450">

Then, the issue is reproducible:
<img width="1107" alt="image" src="https://github.com/codalab/codalab-worksheets/assets/40016222/d3323bac-9704-4f20-b652-d9473750b71d">

**Comment by wwwjn** [comment]
The root cause is clear: The bundle is an empty folder. So the `zip` command fails.

<img width="1100" alt="image" src="https://github.com/codalab/codalab-worksheets/assets/40016222/e8c299cc-a45c-42e2-89e7-65ddf4aebf76">

We should bypass it (or use tar.gz) if the bundler is an empty folder

**Comment by wwwjn** [comment]
Use command `zip -rq  {tmp_path} . -i .` instead

**Comment by HidyHan** [comment]
This is super weird - I tried to reproduce with bundle id 0x15a26c1901154927bde5e842101328d0, and the upload just succeeded on dev machine even though the error is thrown on prod.

Regardless, changing the command should be the way to go, so I will go ahead with the change.

**Comment by percyliang** [comment]
Don't need this for migration.
