### ISSUE TITLE
Migration: index.sqlite Not Found

### ISSUE THREAD

**Issue by AndrewJGaut** [codalab/codalab-worksheets#4574]
[Errno 2] Not found: azfs://storageclwsprod1/bundles/0x0137e17add6648b893945ed29752bd6c/index.sqlite

Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py\", line 999, in get_blob_pr
operties\n    **kwargs)\n  File \"/opt/conda/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_blob_operations.py\", line 393, in get_properties\n
  raise models.StorageErrorException(response, self._deserialize)\nazure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid
 status 'The specified blob does not exist.'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt
/conda/lib/python3.7/site-packages/apache_beam/io/azure/blobstorageio.py\", line 609, in __init__\n    properties = self._get_object_properties()\n  File \"/opt/conda/l
ib/python3.7/site-packages/apache_beam/utils/retry.py\", line 253, in wrapper\n    return fun(*args, **kwargs)\n  File \"/opt/conda/lib/python3.7/site-packages/apache_b
eam/io/azure/blobstorageio.py\", line 623, in _get_object_properties\n    return self._blob_to_download.get_blob_properties()\n  File \"/opt/conda/lib/python3.7/site-pa
ckages/azure/core/tracing/decorator.py\", line 83, in wrapper_use_tracer\n    return func(*args, **kwargs)\n  File \"/opt/conda/lib/python3.7/site-packages/azure/storag
e/blob/_blob_client.py\", line 1001, in get_blob_properties\n    process_storage_error(error)\n  File \"/opt/conda/lib/python3.7/site-packages/azure/storage/blob/_share
d/response_handlers.py\", line 147, in process_storage_error\n    raise error\nazure.core.exceptions.ResourceNotFoundError: Operation returned an invalid status 'The sp
ecified blob does not exist.'\nErrorCode:BlobNotFound\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  Fi
le \"codalab/migration.py\", line 316, in migrate_bundle\n    bundle_uuid, disk_location, bundle_info, is_dir, target_location\n  File \"codalab/migration.py\", line 23
2, in sanity_check\n    new_content = read_file_section(new_location, 5, 10)\n  File \"/opt/codalab-worksheets/codalab/worker/file_util.py\", line 460, in read_file_sec
tion\n    if offset >= get_file_size(file_path):\n  File \"/opt/codalab-worksheets/codalab/worker/file_util.py\", line 435, in get_file_size\n    with OpenFile(linked_b
undle_path.bundle_path, 'rb') as fileobj:\n  File \"/opt/codalab-worksheets/codalab/worker/file_util.py\", line 273, in __enter__\n    with OpenIndexedArchiveFile(linke
d_bundle_path.bundle_path) as tf:\n  File \"/opt/codalab-worksheets/codalab/worker/file_util.py\", line 216, in __init__\n    compression_type=CompressionTypes.UNCOMPRE
SSED,\n  File \"/opt/conda/lib/python3.7/site-packages/apache_beam/io/filesystems.py\", line 244, in open\n    return filesystem.open(path, mime_type, compression_type)
\n  File \"/opt/conda/lib/python3.7/site-packages/apache_beam/io/azure/blobstoragefilesystem.py\", line 177, in open\n    return self._path_open(path, 'rb', mime_type,
compression_type)\n  File \"/opt/conda/lib/python3.7/site-packages/apache_beam/io/azure/blobstoragefilesystem.py\", line 138, in _path_open\n    path, mode, mime_type=m
ime_type)\n  File \"/opt/conda/lib/python3.7/site-packages/apache_beam/io/azure/blobstorageio.py\", line 139, in open\n    self.client, filename, buffer_size=read_buffe
r_size)\n  File \"/opt/conda/lib/python3.7/site-packages/apache_beam/io/azure/blobstorageio.py\", line 612, in __init__\n    raise IOError(errno.ENOENT, 'Not found: %s'
 % self._path)\nFileNotFoundError: [Errno 2] Not found: azfs://storageclwsprod1/bundles/0x0137e17add6648b893945ed29752bd6c/index.sqlite\n

**Comment by percyliang** [comment]
How do you reproduce this?

**Comment by AndrewJGaut** [comment]
Example UUID: 0x0137e17add6648b893945ed29752bd6c

**Comment by AndrewJGaut** [comment]
Reproduce with instructions in [this doc](https://docs.google.com/document/d/19HdlX0RrTDYw924sTT5F7jsuUr8IOrNYRj1h5d22AZI/edit) from section "Reproduce the issue in local / dev environment"

**Comment by AndrewJGaut** [comment]
Closing for now; hasn't been seen in a little while?
