### ISSUE TITLE
Migration: Can't zip large bundles due to lack of RAM

### ISSUE THREAD

**Issue by AndrewJGaut** [codalab/codalab-worksheets#4580]
We get the following stack trace when zipping some bundles:

2023-11-22 19:05:32,218 - __main__ - ERROR - [migration] [3] Error for 0xc1cb46ffa761492b908a31a9492a9e12: Traceback (most recent call last):
  File "codalab/migration.py", line 417, in migrate_bundle
    self.adjust_quota_and_upload_to_blob(bundle_uuid, bundle_location, is_dir)
  File "codalab/migration.py", line 361, in adjust_quota_and_upload_to_blob
    raise e  # still raise the expcetion to outer try-catch wrapper
  File "codalab/migration.py", line 353, in adjust_quota_and_upload_to_blob
    self.upload_to_azure_blob(bundle_uuid, bundle_location, is_dir)
  File "codalab/migration.py", line 233, in upload_to_azure_blob
    source_fileobj = zip_directory(bundle_location)
  File "/opt/codalab-worksheets/codalab/worker/file_util.py", line 148, in zip_directory
    proc = subprocess.Popen(args, stdout=subprocess.PIPE, cwd=directory_path)
  File "/opt/conda/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.7/subprocess.py", line 1430, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory

It appears to me that we don't have enough RAM to fork and execute that subprocess. Not sure why? That bundle listed above is not big...

**Comment by AndrewJGaut** [comment]
Example UUID: 0xc1cb46ffa761492b908a31a9492a9e12
Reproduce with instructions in [this doc](https://docs.google.com/document/d/19HdlX0RrTDYw924sTT5F7jsuUr8IOrNYRj1h5d22AZI/edit) from section "Reproduce the issue in local / dev environment"

**Comment by AndrewJGaut** [comment]
OK, this is very strange. At first I thought it was due to the way I was computing the migration stats, but now I don’t think so. In fact, I can see the combined size of all the dataframes in use in terms of memory usage:
```
>>> df.memory_usage(deep=True)
Index               128
Unnamed: 0        38448
uuid             437346
status           306761
error_message    362304
dtype: int64
```
And we see here the full size of the dataframe:
```
>>> sys.getsizeof(df)
1145011
```
which is just over 1MB.
However, when we look at the container, we see that RAM usage is quite high:
```
CONTAINER ID        NAME                                       CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
b1bb94e38b95        codalab_azure-batch-worker-manager-gpu_1   0.00%               128.6MiB / 13.7GiB   0.92%               2.26GB / 298MB      690MB / 0B          2
d1697f4a313f        codalab_azure-batch-worker-manager-cpu_1   0.00%               130.9MiB / 13.7GiB   0.93%               2.36GB / 222MB      318MB / 0B          2
e5f50690b21f        codalab_monitor_1                          0.00%               8.727MiB / 13.7GiB   0.06%               7.8GB / 213MB       43.2GB / 1.73GB     1
2a77632cf17e        codalab_nginx_1                            7.81%               9.656MiB / 13.7GiB   0.07%               4.86TB / 4.69TB     26GB / 0B           5
9ad361075504        codalab_frontend_1                         0.00%               49.73MiB / 13.7GiB   0.35%               598MB / 8.59GB      6.64GB / 0B         11
fe77c4244b2b        codalab_bundle-manager_1                   27.63%              133.4MiB / 13.7GiB   0.95%               565GB / 155GB       11.4GB / 0B         6
a8899aa4f3f5        codalab_rest-server_1                      126.33%             7.287GiB / 13.7GiB   53.18%              1.83TB / 5.06TB     5.4TB / 12.1GB      119
5569e2c91ab4        codalab_ws-server_1                        0.00%               265.8MiB / 13.7GiB   1.89%               10.6MB / 10.8MB     74.1MB / 0B
```
(And note that the migration script is running on the REST server, in this case with just A SINGLE PROCESS! So RAM usage is huge!)
When we kill the migration script, we see the usage decreases HUGELY:
```
CONTAINER ID        NAME                                       CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
a8899aa4f3f5        codalab_rest-server_1                      55.43%              3.278GiB / 13.7GiB   23.92%              1.84TB / 5.06TB     5.4TB / 12.1GB      111
```
I don’t know why RAM usage is so high with the migration script…

**Comment by AndrewJGaut** [comment]
Moreover, it doesn't seem to have much of a correlation with bundle size? e.g. we see here in the logs:
```
0xc3e670573a24406cac2fb21898d082c4,ERROR,[Errno 12] Cannot allocate memory
0xc3e6fa8bfc3446c396770da798090c74,CHANGED_DB,
```
If I look at the sizes of these two bundles, the first bundle `0xc3e670573a24406cac2fb21898d082c4` has size `4.1k` and the second bundle `0xc3e6fa8bfc3446c396770da798090c74` has size `116k`. Yet the first triggers an OOM error. Very strange. Of course, it's hard to definitively conclude anything with four processes running; we should try a single process, I believe.

**Comment by AndrewJGaut** [comment]
Looks like this might be due to multiprocessing too? See [here](https://stackoverflow.com/questions/21485319/high-memory-usage-using-python-multiprocessing). Might be an underlying issue...

**Comment by percyliang** [comment]
Was needed for migration, but I think we moved off of zip anyway.
