### ISSUE TITLE
Migration: Path '' in bundle <UUID> not found  

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4581]
Issue for the migration: "Error 2: Path '' in bundle <UUID> not found"

For these bundles, just don't migrate it. But change the database to say "blob"

(if you run "rm -d" for a bundle on blob, that same state should be reflected for these bundles.)

**Comment by pranavjain** [comment]
@dma1dma1 Is this issue fixed with your change?
