### ISSUE TITLE
Application for more space quota. 

### ISSUE THREAD

**Issue by itcrazy0918** [codalab/codalab-worksheets#4585]
Hi! I am preparing [Spider Leaderboard](https://yale-lily.github.io/spider).
So I signed up codalab and learning how to use codalab.

But I can use only 100M disk quota, though I need minimum 30G for model and data.

I wrote [google form](https://forms.gle) on Wednesday, but I have got no answer yet.

Could you please improve my disk quota? It is urgent because I also need the evaluation results.

Here is some information.
username: tangliangyun
email: [1170382650@qq.com]
uuid:https://worksheets.codalab.org/worksheets/0x8eb1174989ad49c49042a8db59c97511

Thank you in advance for any help you might be able to provide.

@yifanmai

**Comment by pranavjain** [comment]
We have been actively working on fixing some of the CodaLab issues and were not able to look into this request earlier. Sorry for that. Please reopen a new issue if you still want us to process this request.
