### ISSUE TITLE
[USER ISSUE]

### ISSUE THREAD

**Issue by pangwenfeng** [codalab/codalab-worksheets#4586]
I am preparing a task of text2sql which need at least 30G disk space, but there is only 100M disk quota in the account.

Could you please increase my disk quota or check the problem why I can only get 100M disk quota?

Here is the information of my account.
username: pangwenfeng
email: [wenfengpang@gmail.com)
uuid:https://worksheets.codalab.org/worksheets/0x4fde41cc713345edb3c17faec6c84c91#

Thank you in advance.

**Comment by likeqi077** [comment]
buddy, I am having the same issue here, has yours been solved yet?

**Comment by pranavjain** [comment]
We have been actively working on fixing some of the CodaLab issues and were not able to look into this request earlier. Sorry for that. Please reopen a new issue if you still want us to process this request.
