### ISSUE TITLE
[USER ISSUE] Cannot upload bundle--"Quota full" error even though there is plenty storage available.

### ISSUE THREAD

**Issue by GreenParachute** [codalab/codalab-worksheets#4587]
**Describe the bug**
Attempting to upload a relatively large bundle to the CodaLab servers using the CLI. The upload begins, the upload progress updates regularly as data is transmitted, and only after all the files have seemingly been uploaded (in this case after about 40 minutes of active upload) the following error message is returned: 
```
$ cl upload /model_directory/NatRASAT_Preprocessed_model
Preparing upload archive...
Uploading NatRASAT_Preprocessed_model.tar.gz (0xed810627617d4a23beedfec484785373) to https://worksheets.codalab.org
Sent 10088.90MiB [4.09MiB/sec]    			
UsageError: Upload failed: Can't save bundle, user disk quota exceeded. 
Bundle size 11407987161 greater than user's disk quota left: 9153300000.0
```

It is correct that the model file is about 11GB in size, however there is more than sufficient storage available as we had previously been granted a quota increase to 20GB. So the information about remaining quota in the error message is incorrect and should not be an issue. In fact, both the web interface and `cl uinfo` return a different value for remaining quota, see screenshots and output below:
```
$ cl uinfo
id             : 0x31072ec5734c476ca14762b0a85b3d10
user_name      : GreenParachute
has_access     : False
[...]
date_joined    : Thu Feb  2 16:46:21 2023
last_login     : Fri Dec 22 23:54:57 2023
time           : 22h4m / 60d0h (1.5%)
disk           : 871m / 20.0g (4.3%)
parallel_run_quota: 4
``` 

We also ran `cl search .mine size=.sort-` to confirm uploaded bundle sizes, and also checked for floating bundles, and it all adds up as it should---see below screenshot and output:

```
$ cl search .mine size=.sort-
Only 10 results are shown. Use .limit=N to show the first N results.
uuid      name                        summary  owner           created              data_size  state
----------------------------------------------------------------------------------------------------
0xc12aea  database                             GreenParachute  2023-02-15 20:07:39       839m  ready
0xd46b08  NatSQLSpider                         GreenParachute  2023-03-08 17:55:05      31.1m  ready
0xe0ebdc  src                                  GreenParachute  2023-12-22 12:13:15       261k  ready
0x109cd4  natsql2sql                           GreenParachute  2023-03-29 19:27:42       159k  ready
0xbf1c2f  dev_gold.sql                         GreenParachute  2023-02-15 20:09:39       121k  ready
0xf141ef  evaluation.py                        GreenParachute  2023-02-15 20:28:57      33.8k  ready
0xaa1811  process_sql.py                       GreenParachute  2023-02-15 20:29:48      17.0k  ready
0xa5b989  convert_natsql.py                    GreenParachute  2023-05-18 12:21:43        16k  ready
0xe1652c  natsql_table_converter               GreenParachute  2023-05-18 12:21:56        16k  ready
0x7c97fa  tables_for_natsql_dev.json           GreenParachute  2023-05-18 12:23:19        16k  ready
```

**Expected Behavior** 
So there should be about 19.1GB of storage available and the bundle should upload with no issues, yet the 11GB upload fails every time (tried multiple attempts).

**Additional Information** 
I should also note that uploads such as this have worked in the past---we previously had a 11GB model in the worksheet, and are now just replacing it with an updated model of similar size (the old model was deleted from the worksheet before uploading the new one).
We also tried uploading the model folder through the web interface, but this was just stuck on 'preparing upload' for a couple of hours hours before we decided to close the session, I am assuming the web gui is not a viable option for uploading such a large file.
We have since also tried to upload much smaller bundles using the CLI that fall within the 'imagined' quota and these upload fine.
Also note that all the bundles already in the worksheet are required, and even if we did remove everything we would still get the same error message as the system believes our quota is 10GB and the bundle itself is 11GB.

**Codalab Information**
- *Your username*: GreenParachute
- *UUID of worksheet where problem occurred*: 0x21b86b64910945c7b1d5775da875ff4f
- *UUID of problem bundle (please don't delete)*: 0x033f438eb04445f08af52008342474d3
- *Error message received from Codalab (if applicable)*: UsageError: Upload failed: Can't save bundle, user disk quota exceeded. Bundle size 11407987161 greater than user's disk quota left: 9153300000.0
 - *OS (if on CLI)*: linux
 - *Codalab CLI Version (if on CLI)*: 1.7.2
 - *Browser (if on Web)*; Firefox

**Screenshots**

Disk Quota:
![Screenshot from 2023-12-23 13-52-40](https://github.com/codalab/codalab-worksheets/assets/11292484/f7560d4e-550f-48f8-bdeb-a62a3a44e426)

Floating bundles list:
![Screenshot from 2023-12-23 12-45-56](https://github.com/codalab/codalab-worksheets/assets/11292484/24a523a1-e794-479a-b921-00a656e7ff03)

**Comment by epicfaace** [comment]
Hi @GreenParachute we just increased your disk quota, can you try again and see if it works? Please ping / email if you're still having issues.

**Comment by GreenParachute** [comment]
Hi @epicfaace, just uploaded successfully so that must have resolved the issue. Thank you so much! :)
I guess this issue can be considered closed (though I'd still be curious to know what exactly caused it, but hey!)
