### ISSUE TITLE
codalab.stanford.edu uses MySQL engine that doesn't support transactions

### ISSUE THREAD

**Issue by klopyrev** [codalab/codalab-worksheets#460]
Transactions are not working on codalab.stanford.edu. This is problematic in a few cases, including:

1) When bundle metadata is being updated there is a delete and then an insert. This sometimes causes metadata fields to be missing during a concurrent read. This is the reason that the old work manager kept crashing. The new bundle manager simply catches the exception and continues trucking on. It's still bad.
2) The worker relies on transactions to prevent some bad cases. Although, these are rare, so it's not too bad.

@percyliang 

We should upgrade MySQL and switch from MyISAM to InnoDB

**Comment by percyliang** [comment]
Upgraded.
