### ISSUE TITLE
cl rm sometimes doesn't work

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#460]
Somewhat randomly (but consistently with the same bundle), when trying to execute `cl rm` on it, it prints out something about a `None` bundle.

**Comment by bkgoksel** [comment]
Would be good to have a bundle uuid so we can trace it in the logs, db, bundle store etc

**Comment by percyliang** [comment]
Yeah I was having a hard time reproducing this.  I think it depends on the
worksheet.

**Comment by percyliang** [comment]
To reproduce, create a worksheet with text after the last bundle, then do `cl rm ^`.  This prints out `Bundle None not found`.

**Comment by w0nche0l** [comment]
Issue moved to [codalab/codalab-cli #1041](https://github.com/codalab/codalab-cli/issues/1041) via [**ZenHub**](https://www.zenhub.com/)
