### ISSUE TITLE
Cut down noise from monitoring

### ISSUE THREAD

**Issue by nikhilxb** [codalab/codalab-worksheets#462]
Right now, our monitoring system sends an incredible large number of emails. This is overwhelming, and if there's any signal it's lost in the noise. A property of a good monitoring system is that it intelligently decides what to surface, compress, and hide.

**Comment by nikhilxb** [comment]
<img width="990" alt="screen shot 2018-11-11 at 5 30 56 pm" src="https://user-images.githubusercontent.com/16842594/48321494-be67c080-e5d7-11e8-93b4-728e11989a6f.png">

**Comment by percyliang** [comment]
Closing since any issue is a bug that we should actually fix.
