### ISSUE TITLE
symlink dependencies + read-only break commands

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#462]
In the new worker system, since dependencies now appear as symlinks and furthermore read-only, the old pattern of `cp -a src src.tmp && cd src.tmp && make` doesn't work since `-a` just copies the symlink.

Is there a way to make this work, or in general, a better way of dealing with commands that fundamentally need to write into the current directory?

The default fix is tell people to do: `cp -aL src src.tmp ...`

**Comment by bkgoksel** [comment]
Let's make an issue for writable dependency syntactic sugar and this doesn't matter anymore.
