### ISSUE TITLE
run_status hold in "Uploading results" for a long time 

### ISSUE THREAD

**Issue by WHJTC** [codalab/codalab-worksheets#463]
This run-bundle work well in the past and I just added a new dependency this time ,is there any error in my operating

**Comment by bkgoksel** [comment]
Hi, apologies for the late reply. Did you manage to get the bundle running? If not do you have any bundle or worksheet UUIDs we can check for issues?

**Comment by percyliang** [comment]
Closing for now.  Please re-open if still an issue.
