### ISSUE TITLE
99% completed error

### ISSUE THREAD

**Issue by susht3** [codalab/codalab-worksheets#465]
i try for many times, when i upload for 99%, then failed.

**Comment by susht3** [comment]
a big file

**Comment by bkgoksel** [comment]
Hi, this might happen if the file size is larger than your disk quota remaining. You can see your disk quota by running the `uinfo` command. Can you check that the file fits in your remaining disk quota?
Thanks

**Comment by percyliang** [comment]
Please re-open if you are still having problems.
