### ISSUE TITLE
Stuck in staged state

### ISSUE THREAD

**Issue by joshinh** [codalab/codalab-worksheets#469]
I am currently facing an issue where my bundles are getting stuck in staged state for a long time. My co-workers are experiencing a similar situation as well. What could be the reason for this?

**Comment by in2uitive** [comment]
Same for me. Even `cl run date` is stuck in staged for hours, and still it is stuck. No --request-queue option.

**Comment by percyliang** [comment]
This happens typically when all the workers are busy.  You can start your own workers (https://github.com/codalab/codalab-worksheets/wiki/Execution#running-your-own-worker) if you don't want to wait.  If it looks like something is abnormally wrong, please let us know again.
