### ISSUE TITLE
Docker Error

### ISSUE THREAD

**Issue by kh522** [codalab/codalab-worksheets#472]
Hi, I'm new to codalabs
When I try running the tutorial, I get the error 

failure_message | Cannot start Docker container: Unable to start Docker container: {"message":"No such image: codalab/default-cpu:latest"}

Can someone give an intuition behind the error?

**Comment by percyliang** [comment]
Can you provide the bundle uuid?  Does this happen consistently?

@bkgoksel I think you fixed this?

**Comment by bkgoksel** [comment]
Yes we've merged and deployed a fix to an issue that would cause this error message under some conditions since this issue was opened. I'm happy to close this for now and revisit if anybody sees the same error in the future.
