### ISSUE TITLE
Non-deterministic 404 error on retrieving bundle data

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#479]
There's this weird thing where like 50% of the time, for the same exact path in the same bundle, trying to load it in the web interface gives a 404 error. For example, this url https://worksheets.codalab.org/rest/bundles/0x2713d9c73b8a4242969b50499632126c/contents/blob/eval.json

If I just hit refresh a bunch of times, I sometimes get the 404 and sometimes get the actual data.

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1043
