### ISSUE TITLE
Errors about bundles information on dashboard page

### ISSUE THREAD

**Issue by caoyu1991** [codalab/codalab-worksheets#482]
I tried to delete some bundles using "--force" command and delete the relevant worksheet, and it caused such errors on dashboard page. The information about bundles cannot be displayed normally. And the disk space is also abnormal, some bundles cannot be tracked by me but they still occupy disk space. 
Here is my dashboard link
https://worksheets.codalab.org/worksheets/0xb843335f02a9443995db2013fbe2e7f4/

If possible, could you just clean up all my data on codalab? Since I have all backup of them and I really need to free my disk space. Thank you very much!

**Comment by w0nche0l** [comment]
This issue was moved to codalab/codalab-cli#1090
