### ISSUE TITLE
Setup general testing infrastructure for frontend

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#49]
Old: Don't call 'cl' to create temporary worksheet.

Split this up into multiple issues.

**Comment by percyliang** [comment]
Things to test (end-to-end):

- Upload a file
- Create a run through the interface
- Type something into the web terminal
- Edit source / save
- Click a bundle and show the contents

**Comment by yashsavani** [comment]
@percyliang @kashizui Could you please recommend a UI test that you think would be a good one to start with?

**Comment by kashizui** [comment]
A good one to start with might be to click on the "Edit source" button and then the "Save" button and check that nothing crashes.

**Comment by percyliang** [comment]
This is selenuim end-to-end test.
