### ISSUE TITLE
.codalab/misc_temp directory should be created if it does not exist

### ISSUE THREAD

**Issue by arunchaganty** [codalab/codalab-worksheets#495]
If any command that requires the downloading of a file (e.g. cl edit) is run if the .codalab/misc_temp directory does not exist, it fails with an `OSError`:

> OSError: [Errno 2] No such file or directory: '/home/$USER/.codalab/misc_temp/tmpGphHBJ.c'

Codalab should automatically create this directory if it does not already exist.

**Comment by kashizui** [comment]
#434 will fix this specific issue, since download will no longer use misc_temp.
