### ISSUE TITLE
Improve robustness around invalid bundle references in worksheet items

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#504]
When `cl wadd` is run and Ctrl-C is pressed, this results in an invalid bundle being created.

**Comment by kashizui** [comment]
@percyliang Based on our conversation on #536, the more precise issue is better/more consistent handling of invalid bundles in a worksheet?
And `wadd` already does its best to fail gracefully.

**Comment by leilenah** [comment]
unable to repro
