### ISSUE TITLE
cl diff, grep

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#505]
Make it easy to perform lightweight commands on bundles without downloading the entire bundle(s) or creating another bundle:

```
cl diff <bundle1> <bundle2>
```

should print out the differences between the two bundles.

```
cl grep <keyword> <target>  ... <target>
```

should print out lines in target that match keyword.

**Comment by candicegjing** [comment]
@percyliang What's the diff result we want to print out in `cl diff <bundle_1> <bundle_2>` ? The returning result?
