### ISSUE TITLE
Make style consistent

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#514]
Make code style more consistent and PEP8-conformant, in an independent PR.
- [ ] Decide on style guidelines (PEP8, [Google Python Style](https://google.github.io/styleguide/pyguide.html), etc.)
- [ ] Include PyLint as part of the automated CI pipeline
- [ ] Update files across project to meet a stricter subset of the guidelines

**Comment by percyliang** [comment]
Do we still need to do this?

**Comment by kashizui** [comment]
I think our policy now is just to update the style of any code you're modifying, so no need to go through the entire codebase in one go.
