### ISSUE TITLE
Create a pip package

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#517]
`pip install codalab-cli`

**Comment by maxwang7** [comment]
Instructions: https://packaging.python.org/distributing/

TODOs:
- [ ] create setup and initialization files
  - [ ] choose a versioning scheme
  - [ ] Run setup commands and place the `cl` inside the user's search paths
- [ ] Package project as a Pure Python Wheel
- [ ] Upload project to PyPi
- [ ] Test installation on different machines using pip and easy_install

**Comment by fabeschan** [comment]
@maxwang7 This link has been useful for my packages, see if it helps you. IMO it explains the process  in a much clearer manner:

http://python-packaging.readthedocs.io/en/latest/index.html

**Comment by maxwang7** [comment]
Thank you Fabian!

**Comment by maxwang7** [comment]
Thank you Fabian!

**Comment by maxwang7** [comment]
Some questions:
For the package name, should we use a hyphenated (codalab-cli) or underscore (codalab_cli) version?
Are all the requirements we need inside of requirements.txt?
Are we using semantic versioning? If so, is 0.0.1 the correct first version label?
Are we using Percy's name and email address?
Should we create a CodaLab PyPI account?

**Comment by kashizui** [comment]
I'm actually not sure, what is the canonical form for pip packages?
All the rquirements we need to run the CLI client should be in requirements.txt.
We are using semver, and our current version number is defined in `codalab-cli/codalab/common.py`
re: name/address/account, I don't know -- @percyliang?

**Comment by percyliang** [comment]
Can we use codalab.worksheets@gmail.com?

**Comment by kashizui** [comment]
package name: use hyphen codalab-cli
Name: CodaLab

**Comment by maxwang7** [comment]
Some notes:

To get all the packages, use setuptools' find_packages() tool: http://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages

There are a lot of different recommendations on how to add a command line tool:
- This tutorial uses a new __main__.py file and a console entrypoint that hooks into that file: https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/
- Virtualenv seems to take a similar approach: https://github.com/pypa/virtualenv/blob/master/setup.py
- Ok, this is the recommended approach that's also given in setuptools' documentation: https://packaging.python.org/distributing/#scripts

**Comment by maxwang7** [comment]
pip's setup.py is also useful: https://github.com/pypa/pip/blob/master/setup.py

**Comment by maxwang7** [comment]
We should ask students to ensure that they have run: `apt-get install gcc` and `apt-get install python2.7-dev` before doing `pip install codalab-cli` -- I didn't have either of those on a new Docker image. Not sure what a new Azure instance will have.

**Comment by kashizui** [comment]
Done
