### ISSUE TITLE
reduce amount of logging

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#518]
Currently, `event_log` is getting pretty big.  Consider cutting back / making this more efficient.

**Comment by kashizui** [comment]
What about more machines? ;) (or perhaps some other form of storage than a MySQL database)

What's our current use case besides perusing `cl events`?

And could we drop events past a certain age or do we want keep all of them indefinitely?

**Comment by percyliang** [comment]
I don't think we need to radically change anything yet.  I think we can
just be more careful about what to log...currently, each worksheet view
generates three events which are being stored as fairly long strings with
useless information.

But again, this is not urgent; it's not like we're running out of space due
to event logs...

Also, once @ChengshuLi fixes the problem where we request all bundle
contents when we load a worksheet, we should have much fewer events.

**Comment by kashizui** [comment]
Ah I see, that does seem unnecessary.

**Comment by percyliang** [comment]
Get rid of this logging in the DB and instead log to some service with analytics support.

**Comment by percyliang** [comment]
Todo:
1) Clear the events table on prod
2) Keep only create bundle / worksheet events.

**Comment by candicegjing** [comment]
There are 25236554 records in the `event` table. Among those records, 
1. `POST /bundles` has 53590 records
2. `POST /worksheets` has 880 records
I'll just keep the above two types of events and delete the rest of them, right?

**Comment by percyliang** [comment]
What are the other records?  I think we might not need to keep all the
/bundles records either...only the upload and start_bundle,
finalize_bundle, perhaps?

**Comment by candicegjing** [comment]
This is the full list of commands in database:
```
+---------------------------------------------------+----------+
| command                                           | count(*) |
+---------------------------------------------------+----------+
| resume_bundle                                     | 14473273 |
| GET /bundles/<uuid:re:0x[0-9a-f]{32}>             |  3262577 |
| fetch_bundle_contents_info                        |  2170186 |
| GET /interpret/worksheet/<uuid:re:0x[0-9a-f]{32}> |  1897135 |
| fetch_bundle_contents_blob                        |  1771834 |
| GET /bundles                                      |   486368 |
| GET /worksheets/<uuid:re:0x[0-9a-f]{32}>          |   314811 |
| GET /user                                         |   288036 |
| finalize_bundle                                   |   195053 |
| GET /worksheets                                   |   163735 |
| POST /interpret/file-genpaths                     |    54379 |
| POST /bundles                                     |    53677 |
| update_bundle_contents_blob                       |    48792 |
| start_bundle                                      |    26707 |
| POST /cli/command                                 |    25991 |
| DELETE /bundles                                   |    25371 |
| POST /worksheet-items                             |     9783 |
| PATCH /bundles                                    |     2436 |
| POST /worksheets/<uuid:re:0x[0-9a-f]{32}>/raw     |     2267 |
| GET /groups/<group_spec>                          |     1815 |
| GET /titlejs/bundle/<uuid:re:0x[0-9a-f]{32}>/     |      937 |
| POST /worksheets                                  |      880 |
| POST /bundle-permissions                          |      870 |
| POST /worksheet-permissions                       |      793 |
| PATCH /worksheets                                 |      703 |
| POST /bundle-actions                              |      607 |
| GET /titlejs/worksheet/<uuid:re:0x[0-9a-f]{32}>/  |      579 |
| POST /interpret/genpath-table-contents            |      240 |
| GET /account/css                                  |      176 |
| GET /users/<user_spec>                            |      142 |
| PATCH /user                                       |      131 |
| DELETE /worksheets                                |      129 |
| POST /help/                                       |       46 |
| GET /groups                                       |       36 |
| PATCH /users                                      |       24 |
| POST /groups/<group_spec>/relationships/members   |       23 |
| POST /groups                                      |       16 |
| POST /groups/<group_spec>/relationships/admins    |        4 |
| GET /users                                        |        2 |
| DELETE /groups/<group_spec>/relationships/members |        1 |
+---------------------------------------------------+----------+
40 rows in set (8.84 sec)
```

**Comment by percyliang** [comment]
Upon further reflection, I think we should just remove everything related
to `cl events`, since we never use it anyway.  We have nginx logs for the
short term, and long term, we should use Application Insights or something
more scalable.

**Comment by candicegjing** [comment]
Just to double-check before I make any changes that are non-revertable, I'll delete all the records in `event` table for this ticket, right?

**Comment by percyliang** [comment]
Yes.

**Comment by candicegjing** [comment]
Removed all entries in the database by the time I log in to the system.

**Comment by epicfaace** [comment]
> Upon further reflection, I think we should just remove everything related to `cl events`, since we never use it anyway. We have nginx logs for the short term, and long term, we should use Application Insights or something more scalable.

Does this mean that in the long term we may want to re-add event logging but log it to a different backend instead?

**Comment by percyliang** [comment]
Probably use Application Insights or mixpanel instead of building our own.
