### ISSUE TITLE
Remove unnecessary dependencies from client requirements

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#521]
If one does:

```
./setup.sh client
```

One should be able to use the `cl` command.  However, because of `codalab/rest/util.py`, basic CL commands need bottle, marshmallow.  Should remove these dependencies when in client mode.

**Comment by kashizui** [comment]
This might be difficult to extricate until LocalBundleClient is gone.
Temporary solution is to add these dependencies to the client requirements.

**Comment by kashizui** [comment]
Temporarily addressed by https://github.com/codalab/codalab-cli/commit/e30c2e07eb396fa409fb3c18ca0af287492041d1 but re-orienting this ticket to extricate these dependencies in the future once LocalBundleClient is gone.

Excessive dependencies to remove from `requirements.txt` are:
- bottle
- oauthlib
- marshmallow-jsonapi
