### ISSUE TITLE
Tests on master & develop currently failing

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#531]
```
UsageError: You cannot add worksheet links across instances.
>> codalab/bin/cl add worksheet 0x3828aabb5656493aa13c726dc8616db9 . (exit code 1, expected 0)

ERROR: Exit codes don't match
```

probably related to recent spate of hotfixes.

**Comment by kashizui** [comment]
In the future we (I) should consider a policy of rolling back recent changes in the face of production failures, then fix the bug(s) with proper PRs that pass the CI tests before merging.

**Comment by percyliang** [comment]
Yes, that sounds like a good idea.  It's tricker if there are changes to
the DB though...
