### ISSUE TITLE
Create full integration test environment with Docker Compose

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#534]
Idea:
Create a Dockerfile that will spin up the full ecosystem of servers/workers and (optionally) run a full set of tests (`test-cli.py` for the most part) within that environment. This would simplify running tests (can use the same process for both local dev and for CircleCI tests), and also avoid polluting one's own instance/filesystem with extra bundles or files that weren't cleaned up.

**Comment by kashizui** [comment]
Another way to phrase this: I want to be able to start up (and restart) the full set of servers & workers for CodaLab with a single command, be able to start playing with it immediately.

**Comment by kashizui** [comment]
Reference:
- https://engineering.gosquared.com/testing-with-docker
- https://docs.docker.com/compose/overview/

**Comment by kashizui** [comment]
This might actually be crucial to running automated tests with multiple users (#523, #304, #546), and without polluting local environments (#548).

**Comment by kashizui** [comment]
done

**Comment by bkgoksel** [comment]
I don't think this was done as I'm currently  working on this :) 
Adding reference to the current issue for this just for reference. #1046
