### ISSUE TITLE
docker environment variables not visible to command

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#537]
Docker images currently can define environment variables, but these are not picked up by CodaLab because we run commands inside `sudo bash -c ...` (see docker_client.py).  The problem is if we don't do sudo, then the files generated by the commands might not be readable by the outside world.  Though this might be okay, as long as we then change the permissions on everything once the run finishes.  The big picture is that any docker container people build should work in CodaLab without any special considerations.

**Comment by percyliang** [comment]
@kashizui Is this issue addressed with your recent change that removes sudo?

**Comment by kashizui** [comment]
Probably! I'll make a note to test this too.

**Comment by kashizui** [comment]
Fixed
