### ISSUE TITLE
Ignore certain files when uploading a bundle

### ISSUE THREAD

**Issue by kelvinguu** [codalab/codalab-worksheets#54]
When uploading a folder containing code, I often want to ignore large subfolders which contain data, saved parameters, IPython caches, the .git folder, etc.

It would be _very_ useful to have a .clignore file, with the same semantics as .gitignore.

**Comment by percyliang** [comment]
Just to understand the use case better: how deep inside nested directories
do you need ignoring to happen?  If it's very deep, it seems like something
suboptimal about the directory layout.

I generally create a folder (say, 'package') with symlinks to the src and
scripts, and then I do cl upload package -L, where '-L' tells CodaLab to
follow symlinks.

Can you give an example of what you're trying to do?

 -Percy

**Comment by kelvinguu** [comment]
Hi Percy,

Sure, one example below (my actual code):

code/
  .git
  util.py
  optimize.py
  ...
  scripts/
    evaluation_1.ipynb
    evaluation_2.ipynb
    .ipynb_checkpoints

.ipynb_checkpoints can often be >50 Mb. The .git folder also grows over
time.
I could rearrange my directory to look like this:

code/
  util.py
  optimize.py
scripts/
  evaluation_1.ipynb
  evaluation_2.ipynb
  .ipynb_checkpoints

Then I have to mirror this structure using symlinks, while excluding
.ipynb_checkpoints. I would need to create a new symlink for every
evaluation_x.ipynb. I don't think IPython can be easily configured to put
that checkpoint folder anywhere you want.

I think just like with Git, there are certain things you don't want in your
repo, but they belong where they are.

**Comment by percyliang** [comment]
Does doing

cl upload dataset code scripts *.py *.ipynb

solve your problem?  This creates a single bundle with the files.

**Comment by kelvinguu** [comment]
I think so? Can you explain the syntax? To me, it reads "upload everything in the code folder, the scripts folder, and all files with .py or .ipynb suffix". How does it ignore .ipynb_checkpoints?

**Comment by percyliang** [comment]
cl upload dataset <X> behaves like cp -R <X> in terms of selecting which
files are copied.

**Comment by ppasupat** [comment]
I think this is a great feature to have. Either something similar to the .gitignore file or the --exclude tag in rsync would be very useful.

**Comment by percyliang** [comment]
Resolved by #59
