### ISSUE TITLE
if website-config.json doesn't exist, create a file with '{}' in it

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#54]

**Comment by andreweduffy** [comment]
@percyliang is this something that's best done in the setup script, or `settings/__init__.py` do this for you when it detects not configuration file?

**Comment by percyliang** [comment]
Let's have the place that tries to read the website-config.json file create
the file if it doesn't exist.

Either way, this should be consistent with the behavior for config.json in
codalab-cli.
