### ISSUE TITLE
[Backend] Test malformed worksheets

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#547]
Record problematic cases that have crashed worksheet interpretation in the past (or now) and add tests for these cases.

Requires some discussion on how to set up these tests.

**Comment by percyliang** [comment]
@teetone now that you created those stress test worksheets, could we turn that into a test that runs on Travis?

**Comment by teetone** [comment]
@percyliang I can work on this. Do we want full front end automation and screenshot tests using Selenium?

**Comment by percyliang** [comment]
There is a backend part of this which we can test now at least (to hit the appropriate end points) - you can invoke `cl print`.  For frontend, maybe using React testing library?
