### ISSUE TITLE
CLI tests don't always clean up properly after themselves

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#548]
CLI tests still often leave stray bundles and files, after both successful and failure states.

The most complete solution could involve proposal in #534, but not necessarily.

**Comment by bkgoksel** [comment]
Modified the cleanup of tests to attempt to kill any remaining bundles before removing and force removals, seems to be much less of an issue since then but not closing since it's still possible.

**Comment by bkgoksel** [comment]
Hasn't really happened since. Closing as #1046 should preclude any possibility of this happening
