### ISSUE TITLE
Create (or find) framework for testing REST API

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#549]
Medium tests between unit (small) tests and the CLI (large) tests. Hit REST API endpoints directly and check that behavior matches expectation for all known cases.

While unit tests and CLI tests together are good for testing functionality, these REST API tests should probably focus on testing our assumptions about the _interface_ (e.g. how query parameters are parsed and used).

**Comment by kdexd** [comment]
[pyresttest](https://github.com/svanoort/pyresttest) looks promising to me.

**Comment by kashizui** [comment]
Looks nice.

Just for consideration/discussion, a couple other options:
- [Chakram (JavaScript based)](http://dareid.github.io/chakram/)
- [Assertible (QA of web services, as a service)](https://assertible.com/)

**Comment by kashizui** [comment]
For reference, these should probably be "medium-sized" tests, as per this post:
http://googletesting.blogspot.com/2010/12/test-sizes.html

We may also want to have a simple job that regularly checks that our deployed services are alive and healthy, though this will probably be further down the line.

**Comment by kdexd** [comment]
Well testing a REST API is not bounded by programming language, so these options definitely are worth a shot. Well I had contributed a little on OWASP's Web Testing Framework some months ago, it is availble in a web interface and useful for unleashing security bugs as well. I am not experienced much with penetration testing, but it can help in maintaining security of the platform: https://www.github.com/owtf/owtf

**Comment by epicfaace** [comment]
Let's merge this with #2714.
