### ISSUE TITLE
mount CodaLab as a filesystem

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#556]
Often one has ad-hoc visualization scripts which operate on the results of some big run.  The big run can and should go inside CodaLab, but it's not natural for the visualization script to.

What might be valuable is to have the ability to mount CodaLab bundles on your filesystem, so you can perform random access on the bundle from the comfort of your shell.  This would allow people to more easily incorporate CodaLab into their workflow.

Should first figure out how feasible this is.  Here's a starting point:
http://unix.stackexchange.com/questions/67568/mount-http-server-as-file-system

**Comment by fabeschan** [comment]
I think the main wrinkle is mounting private bundles. This means coming up with an authentication layer that restricts bundle mount access to certain users.

My first thoughts on going about doing that is storing ssh public keys for each user and letting them use SSHFS to set up mounts from their clients shells. On the server/bundle storage vm, spin up a SSHFS server container with a readonly mount to whatever bundle and set up authentication with the appropriate user's ssh key.

**Comment by fabeschan** [comment]
Will also look at http mounts
