### ISSUE TITLE
Support metadata override in mimic

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#558]
Add an option `--ignore-metadata` which takes in a list of metadata keys to not copy over.  This is useful if we want to run on a different queue, different docker image, or with different memory requirements.

Alternatively (and this might be better), allow user to specify the metadata fields as for 'cl run', which override the original metadata keys.  Need to be able to specify None though.

**Comment by percyliang** [comment]
Is it more natural to be able to specify a list of new metadata flags to override?

**Comment by kashizui** [comment]
I think so -- in cases where a user wants to `--ignore-metadata`, they probably also wants to specify the values that should replace those metadata fields (instead of just assuming they want the default.)

**Comment by kashizui** [comment]
Fixed by #785
