### ISSUE TITLE
Remove support for commands in worksheet markdown

### ISSUE THREAD

**Issue by ChengshuLi** [codalab/codalab-worksheets#56]
Not sure if this is a bug, it's more like a question. 

From the tutorial, I learn that if I put these two lines in the worksheet

```
[run run-echo-hello : echo hello]{0xa113e342f21347e4a65d1be833c3aaa8}
!rm ^
```

then the first bundle "run-echo-hello" should be removed. But it doesn't happen. Can someone clarify? Maybe my understanding is wrong? 

Thanks!

**Comment by percyliang** [comment]
This functionality is currently broken.  Consider removing this since with the web interface, it's less essential and more dangerous than using the web interface to remove bundles.

**Comment by kashizui** [comment]
Is the goal of this issue now to remove the bang syntax in worksheets?

**Comment by percyliang** [comment]
Yeah, let's just rip it out because I don't think anyone uses it.  Too
annoying to maintain.

**Comment by kashizui** [comment]
fix'd
