### ISSUE TITLE
Refactor worksheet interpretation code

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#561]
I hate proposing this, in the spirit of "if it ain't broke, don't fix it" but I think the worksheet interpretation code is broken.

These issues are all related, directly or indirectly to worksheet interpretation, and work has stalled on all of these issues I think because of the complexity involved with modifying the code:
#504 , codalab/codalab-worksheets#204, codalab/codalab-worksheets#191, codalab/codalab-worksheets#147

**Comment by percyliang** [comment]
Should document this first.

**Comment by maxwang7** [comment]
I'd be willing to take this on and create a design doc for it for the first part of this sprint.

**Comment by bkgoksel** [comment]
Closed with #915
