### ISSUE TITLE
Clean up Docker images on worker automatically

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#568]
Periodically clean up the stalest images on the worker, impose a disk usage limit?

**Comment by percyliang** [comment]
Workers should clear their cached bundles periodically and docker images too.

**Comment by percyliang** [comment]
Docker containers currently are a big problem.

**Comment by kashizui** [comment]
Another postportem from @percyliang 

> The number of bundles on the worker machines exceeded some number, so we were getting a lot of 'Request Too Large' errors.  Seems like three things went wrong:
> - We didn't get notified about this problem (we need to change this somehow).
> - We should be able to handle larger requests (thought we fixed this).
> - We shouldn't let the number of bundles fill up in the first place (this is on the list of TODOs).
> 
> I manually cleared out all the scratch directories on the worker machines, and things are back running now.
> 
>  -Percy

**Comment by kashizui** [comment]
Easy solution: Periodically clear all worker caches.

Better solution: Workers should keep track of when dependencies and docker images were last used and clean up stales ones when disk utilization reaches a certain threshold.

**Comment by kashizui** [comment]
Actually, dependencies are already cleaned up in a separate thread when they exceed a certain amount of disk usage, and containers are cleaned up automatically after runs. The main problem is Docker images. Going to narrow the scope of this issue.

**Comment by kashizui** [comment]
Currently kind of stuck on how to estimate how much disk space the Docker images are currently using (so that my cleanup thread can know when to start cleaning up old images) @fabeschan any idea?

**Comment by kashizui** [comment]
One way appears to be something like `du -s /var/lib/docker/aufs/diff` but that does not appear to generalize to Mac. Maybe we just forgo Mac support on this.

**Comment by percyliang** [comment]
What about just deleting images that haven't been used in a while?

**Comment by kashizui** [comment]
@percyliang I'm fine with that, but we may still run into disk full problems in the case where users suddenly use a bunch of different images in a short period of time. Thoughts?

**Comment by percyliang** [comment]
We can just look at the usage of the disk and remove old images until the
usage is below some threshold?

**Comment by kashizui** [comment]
That sounds good. So we specify a disk to monitor, and as long as the disk usage is above a certain threshold (should this be by percentage or say, leave a buffer of 5gb?), we keep removing the stalest images.

**Comment by percyliang** [comment]
Something like that...  Does our bundle cleanup logic work the same way?

Stalest implies you can get the 'last used' date of an image, not 'last
created' - is that possible?

**Comment by kashizui** [comment]
The bundle cleanup logic sets a maximum on the size of the bundles directory (in bytes), and clears out the stalest dependencies until the directory is within the size limit. I was hoping to do the same thing for Docker images but I got stuck at how to get the amount of space that the Docker images were consuming in total.

Right, I'm keeping track of the 'last used' date of an image. The same is already being done for dependencies.

**Comment by kashizui** [comment]
done
