### ISSUE TITLE
save worksheet doesn't work

### ISSUE THREAD

**Issue by ChengshuLi** [codalab/codalab-worksheets#58]
I set up my local instance, logged into a non-root account, opened my worksheet, went to 'Edit source', made some changes, clicked 'Save'. Then I got this error and my change was not saved. 
![screenshot](https://cloud.githubusercontent.com/assets/6732996/12180673/e266917e-b532-11e5-98b0-de166bb478a2.png)

Note: 
1. I can edit and save my worksheet on command line cli, but not on the web interface
2. The error disappears when I used a root account
3. I am using Mac OS 10.10

**Comment by andreweduffy** [comment]
It didn't upload the screenshot, can you try again? Just drag and drop it into the issue

**Comment by andreweduffy** [comment]
How did you create your user? Are you certain the user exists? If you do `cl wls`, is the worksheet you're trying to open actually owned by the user you believe you're logging in as?

**Comment by ChengshuLi** [comment]
I created my user on the webpage by "Sign up". I double checked that the worksheet did belong to the user that I logged in as. I can also use the command line on the webpage to edit my worksheet; I just can't use the web interface. Strange bug.

**Comment by percyliang** [comment]
Did this ever get resolved?

**Comment by ChengshuLi** [comment]
don't see that bug any more. I will close the issue.
