### ISSUE TITLE
cl wedit doesn't work with sublime text?

### ISSUE THREAD

**Issue by kelvinguu** [codalab/codalab-worksheets#58]
I set the editor to Sublime Text with `export EDITOR=subl`.

When I call `cl wedit`, Sublime Text opens with the worksheet as expected, but the process behind `cl wedit` doesn't wait for me to make changes. It immediately shows `UsageError: No change made; aborting`.

This error might not be specific to Sublime Text.

**Comment by percyliang** [comment]
I guess the problem is that sublime doesn't block.  You could write a
wrapper that launches sublime and then waits for the process to terminate
before yielding control.

**Comment by kelvinguu** [comment]
Thanks, yes, that was the issue. To make sublime block, you can replace `subl` with the following script, `subl_wait`:

```
#!/bin/bash
subl -w $*
```

Then, make sure to export EDITOR=`subl_wait`
