### ISSUE TITLE
Print user quotas in `cl status`

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#582]
`cl status` doesn't print out user quotas anymore, like it used to.

Also, when we're root, `cl uedit pliang -d 30g` throws an exception:

codalab.client.json_api_client.JsonApiException: Unable to fetch users: Internal Server Error - Internal Server Error

**Comment by kashizui** [comment]
@percyliang `cl uinfo` does show the quota information -- should we also show it in status?

**Comment by kashizui** [comment]
@percyliang I'm also unable to reproduce the Exception on modifying disk quota on my local instance -- could you try it with your root credentials on wstest?

**Comment by kashizui** [comment]
@percyliang Never mind, I found the credentials -- it appears to work on wstest!

**Comment by percyliang** [comment]
Yeah, don't need it in status if it shows up in cl uinfo.
