### ISSUE TITLE
Copy public permissions across instances

### ISSUE THREAD

**Issue by rajpurkar** [codalab/codalab-worksheets#583]
I copied a worksheet from the main instance to another. While some of the bundles kept the right permissions (for public at least), others now had public read permissions when originally they did not.

**Comment by percyliang** [comment]
In general, metadata isn't copied and it should.  See #71 

However, group permissions will not be copied, because the groups might be different between instances.

**Comment by kashizui** [comment]
Should this be closed? Or should we support some form of permission copying?

**Comment by percyliang** [comment]
Well, we should do something to make it clear what we do.  I think we could
support permissions copying, but it's tricky because groups might not exist
on the target.  Might be easier to just say we don't do it (or just copy
the permissions for the public group)?

**Comment by kashizui** [comment]
Copying public group permissions might be a good idea -- that would allow users to be able to keep their private bundles private on the target instance without an extra `cl perm` command.

**Comment by percyliang** [comment]
Copying across instances is a bit janky...if we want to do this, need to take a step back and figure out what we want.
