### ISSUE TITLE
How to use Codalab on a remote server without admin privileges?

### ISSUE THREAD

**Issue by yashoteja** [codalab/codalab-worksheets#586]
Hi,

I conduct most of my experiments on a server machine where I have no admin privileges.
Is it possible to install Codalab locally without sudo?

If above is not possible, can I run the experiment on the server first, then transfer the outputs to local machine and create the experiment on Codalab with them?

Or does Codalab create simple bash scripts etc. which can later be run anywhere with or without Codalab being installed?

Thanks a lot!
Yash

**Comment by kashizui** [comment]
Hi Yash, thanks for your message.

Yes it might be possible to use CodaLab locally without sudo, but installing the necessary dependencies (such as Docker) may require root privileges. Please refer to the [Server Setup page](https://github.com/codalab/codalab-worksheets/wiki/Server-Setup) to investigate whether or not you'll be able to install and run a local CodaLab instance on your server machine. [This StackExchange post](http://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo) might also be helpful to figure out whether or not you can run a CodaLab worker (which uses Docker) without root privileges. 

The easiest alternative is to run all your experiments on the main CodaLab server. Sign up for an account on https://worksheets.codalab.org to get started. You can use the CLI and connect to this server without root privileges.

I'm not sure what you mean by creating bash scripts, could you clarify?

Thanks,
Stephen

**Comment by yashoteja** [comment]
Dear Kashizui,

Thanks for your advice!
Actually I have tried using https://worksheets.codalab.org earlier. But most of my datasets are 1-10 GB large, and the the ML models generated are of the order of 50 GB. I was unable to upload my dataset last time I tried.

Thanks,
Yash

**Comment by kashizui** [comment]
You're right, each user by default only has 20 GB of storage, since we have limited capacity on our systems at the moment. The best option would definitely be to run a CodaLab instance on a server that you own. I'm going to go ahead and close this issue for now, but feel free to keep us posted in this thread about your efforts, we appreciate your feedback.

Thanks,
Stephen
