### ISSUE TITLE
Worker checkin payloads too large

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#608]
Some workers went offline because they were getting bounced by the server with "Request entity too large". I imagine this is because of the huge dependency lists they accumulated.

Maybe we can use some form of diffing and compression to update the dependencies, especially since most of the time the dependencies have not changed.

**Comment by kashizui** [comment]
Looks like the default limit is 1mb
http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

Not sure how upload sidestepped this issue.

**Comment by percyliang** [comment]
Hm, that's perplexing.  Diffing sounds like a good idea.

**Comment by kashizui** [comment]
We actually set it to 4G.
https://github.com/codalab/codalab-worksheets/blob/master/codalab/config/templates/nginx.conf#L49

Not sure what the issue was then.

**Comment by percyliang** [comment]
But we've been definitely uploading files larger than 4G...that's okay
because it's streaming?

**Comment by kashizui** [comment]
I'm not really sure..

**Comment by percyliang** [comment]
What is left to do on this issue since you already increased the payload?

**Comment by kashizui** [comment]
Nothing left to do here, the fix just needs to be merged with master.
We have a separate issue for cleaning up workers.

**Comment by kashizui** [comment]
Duplicate of #627
