### ISSUE TITLE
Log monitor.py results as events

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#611]
Add entries to the event table for monitor.py results with the profiling information, so that we can see trends over time more easily than in a semistructured log file.

**Comment by percyliang** [comment]
Seems like a good idea.  But it's a bit strange to have all the results of monitor.py saved into the DB since the monitor script runs kind of at a meta-level, backing up the DB, running unittests...

**Comment by kashizui** [comment]
Hm that's a good point.
I'm hesitant to complicate things a lot more, but maybe there would be use for a separate database that just stores our server metrics (jumping into the DevOps rabbit hole here). The event table on codalab_bundles would remain as a log of only user-level actions.

**Comment by percyliang** [comment]
Yeah, probably not worth having a separate DB for now.
