### ISSUE TITLE
Bundle copying loses some files

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#615]
From @robinjia

> I found another cl add issue: some files just disappear altogether.
> 
> I did `cl add -d` from https://worksheets.codalab.org/bundles/0xb1054602f4d74bef91ceb949387e2180/ to create https://codalab.stanford.edu/bundles/0xb1054602f4d74bef91ceb949387e2180/ .  You'll note that there are many fewer output files on the second bundle than the first.

> I tried repeatedly doing
> 
> cl add bundle main::0xb1054602f4d74bef91ceb949387e2180 .
> 
> followed by
> 
> cl rm ^1
> 
> Most of the time, the added bundle is missing some files; exactly what's missing is non-deterministic.  The '-d' flag doesn't seem to matter.

**Comment by kashizui** [comment]
On codalab.stanford.edu::
```
➜  cl rm ^1 && cl add bundle main::0xb1054602f4d74bef91ceb949387e2180 . && cl cat ^1     16-11-26 17:28:22
0xa5f789d71ed4499f83267e2c42d7d3a2
Copying run-sh(0xb1054602f4d74bef91ceb949387e2180)...
Copied 51.60MiB [0.72MiB/sec]
name             perm   size
----------------------------
data_token.txt   0644   8.7m
prediction.json  0644   526k
prob_tensor1     0644  12.8m
prob_tensor2     0644  12.8m
prob_tensor4     0644  12.8m
prob_tensor5     0644  12.8m
stderr           0644    198
test_output.txt  0644   206k
```

Seems like prob_tensor3 and stdout like to get lost.

**Comment by kashizui** [comment]
I suspect that the BundleManager on the destination server is trying to run these bundles upon creation (since it just sees a run bundle and doesn't know that it's being copied from another server) and causing some sort of race condition.

**Comment by kashizui** [comment]
Just confirmed that BundleManager is trying to stage these bundles. Not sure if that's the cause yet though.

**Comment by kashizui** [comment]
Solution ideas: For bundles copied from somewhere else, either

- don't create them as run bundles (which may be semantically strange), or
- allow users to specify that their run bundle will be uploaded from somewhere else when they create a new bundle, so that we can initialize the state to UPLOADING 

so that BundleManager doesn't stage them.

**Comment by kashizui** [comment]
@percyliang  thoughts?

**Comment by percyliang** [comment]
I think we should keep it as a run bundle.  When we create a new bundle
(via copying), maybe we can just set the state to UPLOADING (or a new state
COPYING).  But uploading is probably easier.

**Comment by kashizui** [comment]
@robinjia I've pushed and deployed a fix to this bug, hopefully there are no more lost files on copying!
