### ISSUE TITLE
Docker image downloading times out when waiting on another process

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#618]
I had some jobs fail with the message "Unable to download Docker image: timed out".  It seems like what's happening is that there are multiple jobs on the same machine requesting the same Docker image.  One job actually downloads the image and works fine; however, the other job that waits for the download to finish times out after 5 minutes.

**Comment by percyliang** [comment]
In general, what is the behavior when two jobs need to download the same docker image?

**Comment by bkgoksel** [comment]
Fixed with worker 2.0
