### ISSUE TITLE
worker checkin request too large

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#627]
After a while, when the number of bundles for a worker grows to 15G or so and state.json is 353K, then worker is unable to checkin:

File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
BundleServiceException: Unable to check in with bundle service: Request Entity Too Large - Request to large

and jobs cannot be run on that worker anymore.

**Comment by kashizui** [comment]
Found the source of the problem (MEMFILE_MAX is 102400):
https://github.com/bottlepy/bottle/blob/release-0.12/bottle.py#L1178-L1188

We sidestepped this limit by using 'wsgi.input' directly for file uploads.

The limit can be increased:
http://stackoverflow.com/questions/16865997/python-bottle-module-causes-error-413-request-entity-too-large

We can increase the limit temporarily while we work on capping the size of the worker cache?

**Comment by percyliang** [comment]
Nice!  Yeah, let's increase the limit.  There are times when we might actually want to send a large request.  Independently, we should flush the worker cache once in a while (along with docker, etc.)

**Comment by kashizui** [comment]
What's a good number for the limit? 24 MB? (roughly 230x)

**Comment by percyliang** [comment]
Maybe even 8 MB is fine.

**Comment by kashizui** [comment]
@rajpurkar Tagging you on this so that you can be notified when the fix is merged into master (this issue will close automatically)
