### ISSUE TITLE
fix monitor.py so we don't get so many emails

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#635]
Either figure out why some runs time out (what fraction?) and fix that or raise the time limit if we think it's benign.

**Comment by fabeschan** [comment]
@percyliang Based on the 40 timeout emails I received to date:

6 are from the command `timeout 300s cl wait 0x...`, 5 of these hitting the hard timeout (hence the exit code 124 for early termination), with the remaining one hitting the soft timeout (232s, exit code 0 so the command still ran to completion). We should dig in and see what is causing this behavior; however these don't occur that frequently so hopefully the upcoming stress tests can tease them out a little more to give us a bit more clue as to what is going on.

The rest of the alerts are from smaller/shorter commands (cl work, cl up, cl rm etc), all hitting the soft timeout of 5s but still running to completion. Most of them finish running within 10s with the remaining two or three finishing within 15s. These 'timeouts' seem benign so I think raising the soft timeout should be fine.

**Comment by percyliang** [comment]
On Fri, Jan 20, 2017 at 1:50 PM, Fabian Chan <notifications@github.com>
wrote:

> @percyliang <https://github.com/percyliang> Based on the 40 timeout
> emails I received to date:
>
> 6 are from the command timeout 300s cl wait 0x..., 5 of these hitting the
> hard timeout (hence the exit code 124 for early termination), with the
> remaining one hitting the soft timeout (232s, exit code 0 so the command
> still ran to completion). We should dig in and see what is causing this
> behavior; however these don't occur that frequently so hopefully the
> upcoming stress tests can tease them out a little more to give us a bit
> more clue as to what is going on.
>
> The rest of the alerts are from smaller/shorter commands (cl work, cl up,
> cl rm etc), all hitting the soft timeout of 5s. Most of them finish running
> within 10s with the remaining two or three finishing within 15s. These
> 'timeouts' seem benign so I think increasing the soft timeout should be
> fine.
>
Sounds good to me.  Do you want to up the time limit to reduce the number
of emails we're getting...?

**Comment by fabeschan** [comment]
Yup, I'll up the time limit. Just wanted to run it by you before I do that

**Comment by fabeschan** [comment]
closing as #645 has been merged
