### ISSUE TITLE
Allow users to add licensing information about a worksheet

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#656]

**Comment by percyliang** [comment]
I don't think there's a clear meaning to licensing a worksheet - does that include all the bundles on the worksheet (but in general, a bundle could belong to multiple worksheets).  Also, a project could span multiple worksheets.  Probably best to let the user just explicitly mention the license on the worksheet or in a `LICENSE.txt` file in the code bundle.
