### ISSUE TITLE
Incorrect session in SSH login shell

### ISSUE THREAD

**Issue by ppasupat** [codalab/codalab-worksheets#662]
An SSH login shell is invoked with a `-` prefix (e.g., `-bash`). This complicates the session computation in the `session_name` method of `lib.codalab_manager.CodaLabManager`.

For reference, here's the relevant portion of the `session_name` method.
```
        # Otherwise, go up process hierarchy to the *highest up shell* out of
        # the consecutive shells.  Include Python and Ruby so we can script from inside them.
        #   cl bash python bash screen bash gnome-terminal init
        #                  ^
        #                  | return this
        # This way, it's easy to write scripts that have embedded 'cl' commands
        # which modify the current session.
        process = psutil.Process(os.getppid())
        session = 'top'
        max_depth = 10
        while process and max_depth:
            name = os.path.basename(process.cmdline()[0])
            if name not in ('sh', 'bash', 'csh', 'tcsh', 'zsh', 'python', 'ruby'):
                break
            session = str(process.pid)
            process = process.parent()
            max_depth = max_depth - 1 
        return session
```

Running a `cl` command on the shell:
`-bash --> sshd --> sshd --> init`
The method exits at `-bash`, so the resulting session is `top`

Running a `cl` command in a python script (or a bash / ruby script):
`python (or bash or ruby) --> -bash --> sshd --> sshd --> init`
The method exits at `-bash`, so the resulting session is the PID of `python`.

Ideally the two sessions should be the same.

**Comment by kashizui** [comment]
My terminal emulator actually also calls `-zsh` with a dash, no wonder all my tabs always shared the same session...
