### ISSUE TITLE
Make all groups publicly visible

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#671]
Everyone can know a group exists

Questions

Where are the permissions enforced for this right now?

How do we want to expose the list of groups?

Look in get_groups_info (thanks Stephen!) [in this file](https://github.com/codalab/codalab-cli/blob/f33ff172db28f592aac97cf75c0911040ac3bf22/codalab/rest/util.py#L151-L161). Pretty sure we can do something like setting `group_info` to `None`, but do some more digging on where else `get_group_info` is being used.

Time estimate: 4 hours

**Comment by maxwang7** [comment]
- Where are the permissions enforced for this right now?

- How do we want to expose the list of groups?

**Comment by maxwang7** [comment]
Following the proposed solution in the issue description, here are descriptions of the uses of `get_group_info`. They are all in rest/groups.py:

- fetch_group(): Allows the user to fetch a group. --> Our goal with this issue is to allow fetch_group() to fetch any group.
- delete_groups(): Uses `get_group_info` as a way of checking the user's permissions. Changing `get_group_info`'s behavior would effect this function (causing a major security hole -- anyone could delete anyone else's group!).
- add_group_members_helper(): Uses `get_group_info` as a way to fetch the group, but only if the user is an admin of the group. Changing `get_group_info` should not effect this method since this function needs admin privileges in the group.
- delete_group_members(): Same as with add_group_members_helper(). Uses `get_group_info` as a way to fetch the group, but only if the user is an admin of the group. Changing `get_group_info` should not effect this method since this function needs admin privileges in the group.

In summary, it looks like there will need to be some functionality that support the use case in `delete_groups` so that an arbitrary user isn't allowed to delete a group that s/he doesn't belong to. I'm going to add a keyword argument `access_all_groups` that defaults to False. Setting it to True gives the caller access to all groups. The only place where I set it to True will be for the fetch_group() function. This way I can ensure that no previous functionality is broken from this change.

---

Testing

General testing:

- Test `cl ginfo <group_spec>` by using the `group_spec` of a group that doesn't belong to the logged in user. Expected result: The group's information should still be successfully shown.
- Test `cl grm <group_spec>` by using a `group_spec` of a group that doesn't belong to the logged in user. Expected result: The group should not be deleted.

bundles:

- Test `cl perm <bundle_spec> <group_spec> r` by using any `bundle_spec` and a `group_spec` of a group that doesn't belong to the logged in user. Expected result: The group should be successfully added to with read permissions.

worksheets:

- Test `cl wperm <ws_spec> <group_spec> a` by using any `ws_spec` and a `group_spec` of a group that doesn't belong to the logged in user. Expected result: The group should be successfully added to the worksheet with all permissions. Try editing the worksheet an ensuring that everything works.

**Comment by kashizui** [comment]
Done
