### ISSUE TITLE
Every user should have a group

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#672]
Created lazily

Questions:

- What should the name of the group be?

- What should we do is users remove themselves from the group they were automatically put into?

- Do we need a special table to store the information about Groups that should only contain one user?

Time estimate: 5 hours

**Comment by maxwang7** [comment]
Questions:

- What should the name of the group be?

- What should we do is users remove themselves from the group they were automatically put into?

- Do we need a special table to store the information about Groups that should only contain one user?

**Comment by percyliang** [comment]
I think the easiest thing to do is to create a group for each user when the
user account is created, and then no other logic is required.  We then need
to just add a migration script that adds such groups for existing users.
Any problems with this lean solution?

On Mon, Feb 13, 2017 at 11:13 AM, maxwang7 <notifications@github.com> wrote:

> Questions:
>
>    -
>
>    What should the name of the group be?
>
> The username, presumably like in Linux.

>
>    -
>    -
>
>    What should we do is users remove themselves from the group they were
>    automatically put into?
>
> The easiest thing is to do nothing.  Perhaps we can prevent them to do
that if it doesn't introduce complexity.

**Comment by maxwang7** [comment]
My only concern is if the user deletes their own group -- how do we ensure that those groups aren't deleted? We could have a flag that keeps track of if a group shouldn't be deleted?

Though, we'll have the same trouble with any other scheme for lazily loading groups. So yes, this sounds good, but I think we need to find a way to keep these groups around.

**Comment by maxwang7** [comment]
@percyliang: @kashizui and I talked some more, and we're wondering if we even need this change for the 224N competition. If users are adding the competition organizer's group to give read access to the user's own worksheet, having the other feature to add any other group seems to be enough for the competition. Thoughts?

**Comment by percyliang** [comment]
That's a really good point.  We might even need per-user groups for a
while.  The main point was trying to avoid the n^2 groups problem, but in
practice, I don't think we want user1=>user2 sharing to be common.  Either
there's a group project (in which you need a group anyway) or things should
be public.

**Comment by maxwang7** [comment]
Not sure I'm following the last sentence, when you say "group project" are you referring to a group for the 224N competition which students would give access to their own bundles? And does "things should be public" refer to the students' bundles should be public?

**Comment by percyliang** [comment]
This was more of a general comment.

- If 4 people are working on a project together, they will just create a
group with 'all' access.
- If they want to keep it private they can set public:none.
- But in general, people should be encouraged to keep bundles public.
