### ISSUE TITLE
Make script to bump versions of both codalab-cli and codalab-worksheets

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#679]
Maybe do some more thinking about how to manage multiple repos as well

**Comment by maxwang7** [comment]
Also should tag the release, upload to PYPI, and deploy to production

**Comment by kashizui** [comment]
While we're at it, this script could also compare the master and release branches and generate a rough draft of the release notes for this version that we can then edit and email out in the next newsletter / put it on the wiki. (We currently manually do this for the "Latest Features" page on the Wiki.

**Comment by percyliang** [comment]
Nervous about automating all of this.  Should instead put this in the checklist for deployment.
