### ISSUE TITLE
Cannot change user settings (first/last name)

### ISSUE THREAD

**Issue by vene** [codalab/codalab-worksheets#68]
Browser: Chromium Version 47.0.2526.73 Ubuntu 15.04 (64-bit)

![codalab_bug](https://cloud.githubusercontent.com/assets/241745/12291789/5876f43e-b9b7-11e5-94d4-420ab46a4625.png)

**Comment by percyliang** [comment]
Will be fixed when the new user authentication system is in place.

**Comment by kashizui** [comment]
Will reimplement user profile page on next sprint.

**Comment by kashizui** [comment]
Fixed by #134

**Comment by vene** [comment]
Thank you all for the great work! :)
