### ISSUE TITLE
GPU jobs not working on any host besides jag8

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#688]
My latest survey of all the machines:
https://codalab.stanford.edu/worksheets/0xbcd61bc3324b469f925f721e411225dd/

Will try to resolve this slowly with some manual experiments and talking to action@cs

**Comment by kashizui** [comment]
@hhexiy

After jag updates most of the jags are now working with CodaLab!
https://codalab.stanford.edu/worksheets/0xbcd61bc3324b469f925f721e411225dd/

**Comment by hhexiy** [comment]
Yayyy! Thanks!!

**Comment by kashizui** [comment]
@hhexiy I resolved the issue with jag11, you can run jobs on there now too
