### ISSUE TITLE
Out of time quota: 10d12h / 7d0h (150.5%)

### ISSUE THREAD

**Issue by yelongshen** [codalab/codalab-worksheets#697]
It returns "Out of time quota" message all the time for any commands i executed. i.e.,
 cl run "python -V"  
Out of time quota: 10d12h / 7d0h (150.5%)

**Comment by percyliang** [comment]
Increased your time quota for now.

**Comment by yelongshen** [comment]
Thanks Percy. The out of time quota issue is gone. 
Could you also help me with another issue? 
 Out of disk quota: 12.3g / 10.0g (123.0%) 
(i.e., Could I have 20G disk for usage?) 
Thanks.

**Comment by percyliang** [comment]
Can you first check to see if you have no bundles that don't need anymore
that you can delete?  (You can also delete a bundle with --data-only to
free up disk space without losing the metadata/provenance.)  If that
doesn't work for you, let me know.

**Comment by yelongshen** [comment]
Hey Percy, I removed a few unused bundles, and now it is 9.9G. i could use it with 10G limitation.  
The question is, I have two bundles being used by public people (for Squad leaderboard). I can't remove it, and it will be kept in my disk. I guess my disk will easily go over 10G limitation soon.

**Comment by percyliang** [comment]
These requests should go through the CodaLab site, not be a GitHub issue.
Can you do that through the web interface (click the '?' in the
bottom-right corner on a worksheets page)?

**Comment by yelongshen** [comment]
Sure, Thanks!
Best,
Yelong.
