### ISSUE TITLE
Automatically pull nvidia/cuda:8.0-runtime

### ISSUE THREAD

**Issue by hhexiy** [codalab/codalab-worksheets#700]
Just got this error upon job startup. Tried on Jag8 and Jag15 and the result is the same.
```
DockerException: Unable to start Docker container: {"message":"No such image: nvidia/cuda:8.0-runtime"} 
```
See complete failure message here: https://codalab.stanford.edu/bundles/0x12fe95498133408cbc205c7afee9d99e/

**Comment by kashizui** [comment]
Sorry @hhexiy, we had some unexpected incompatibilities in our last deploy earlier today. I just reverted back to an earlier version now until we have a fix. Let me know if it still doesn't work.

**Comment by hhexiy** [comment]
working now. thanks!

**Comment by kashizui** [comment]
@fabeschan Could you update our worker code to automatically pull this image? This is causing issues for people who are running their own workers as well. We have existing code to automatically pull images, and we can factor it out as "ensure_docker_image" or something.

**Comment by fabeschan** [comment]
PR is merged, should be live on next deploy.
