### ISSUE TITLE
wrong path for file in output directory

### ISSUE THREAD

**Issue by hhexiy** [codalab/codalab-worksheets#701]
@kashizui We've talked about this:

https://codalab.stanford.edu/rest/bundles/0x0251caa383ab4a13b1ca90f20e145b9e/contents/blob/html%2Ftranscripts.html

%2F needs to be replaced with /. Would be nice to have it fixed so that we don't have to manually change it :).

**Comment by kashizui** [comment]
Thanks for creating the issue for us :) sorry for dropping the ball earlier

**Comment by kashizui** [comment]
Realized why I couldn't reproduce this bug earlier: nginx and bottle don't care about whether a slash is escaped or not in a path, but the bug only occurs on codalab.stanford.edu, which uses Apache. Looks like Apache does care.
The fix: simply to make sure links on the UI file browser use proper slashes without escaping them, and then it should work for all deployments.
