### ISSUE TITLE
cl cp sync metadata

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#71]
Make cl cp copy over the metadata and update the bundle - don't skip entirely if the bundle already exists.  This allows us to keep the metadata consistent across bundles.

The annoying thing is that while the bundle is immutable, the metadata of the bundle is mutable (and must be in order to write descriptions about it and transfer ownership, etc.).  Which means that the uuid doesn't actually specify everything.

If the user is frequently transferring bundles between two instances, then it's his/her responsibility to know which one is the master version.

**Comment by epicfaace** [comment]
I don't think cl cp even exists anymore, so closing. Feel free to reopen if this is still relevant.

**Comment by percyliang** [comment]
It's called `cl add` now, so it's still relevant.
