### ISSUE TITLE
Jobs sent to nodes by TorqueScheduler die if node doesn't have codalab/ubuntu image pulled 

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#710]
They failed with "Worker failed to start. You may have requested too many resources."

The error is resolved when codalab/ubuntu:1.9 image is pulled on that node.

**Comment by percyliang** [comment]
I assume this is any image that is being requested...

**Comment by percyliang** [comment]
Not going to support Torque anymore, closing.
