### ISSUE TITLE
Support user deletion

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#714]
Support a way to delete users on request. 

To be discussed:

- Should anyone be able to delete their own account with just a few clicks? Or should it be a manual email request process? In which case we would just create an administrative command for deleting users.

**Comment by w0nche0l** [comment]
Create CLI command as well as REST endpoint
REST endpoint should require you to be root

will create another issue for creating a user-facing way to delete own account

**Comment by w0nche0l** [comment]
There exist helper functions in group commands for checking if root, use those

**Comment by w0nche0l** [comment]
Merged.
