### ISSUE TITLE
Migrate MySQL configurations to new server

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#725]
- [ ] Copy (subset of?) old configurations to new server
- [ ] Link into `/etc/mysql/conf.d` (?)
- [ ] Dump and reload tables
- [ ] Update deployment doc
- [ ] (future) automate deployment of configurations from deployment repo (instead of a static config file that only lives on the server)

**Comment by fabeschan** [comment]
Put codalab.cnf in deployment directory. `run-mysql.sh` will mount this config file on startup for mysql

**Comment by fabeschan** [comment]
@kashizui is there any more work needed to be put into this ticket?

**Comment by kashizui** [comment]
not necessarily on this ticket, but next step is to ansible-ize the mysql deployment. though much less urgent since we don't do that very often!

**Comment by kashizui** [comment]
done
