### ISSUE TITLE
Executable bit not copied when uploading executables

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#727]
Reported by Ice: uploaded executables don’t execute (permission denied)

**Comment by kashizui** [comment]
more info: Issue is b/c file permissions don't get copied (i.e. the execute bit)

**Comment by kashizui** [comment]
Repro:

`cl upload $(which echo)`
`cl run :echo './echo hello'`

**Comment by fabeschan** [comment]
Closing: dupe of #745
