### ISSUE TITLE
Design: "Root" dependency for run bundles

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#731]

**Comment by percyliang** [comment]
The goal is to make it easy for users to think about CodaLab as they do
with git - you have a working directory containing source code and data,
and you run experiments which get output to directories.  Proposals:

1) Allow users to just type `cl upload . -n project` and `cl run ::project
'python src/train.py`, where :: makes the contents of project accessible to
the run at the top level (avoid silly `cp` hacks).  Pro: the project is a
single unit. Cons: more work to implement and every time we upload, we get
a completely new bundle with no space savings.

2) Provide some macros to allow the user to type `cl sync .`, which would
upload the bundles that have changed.  So then the worksheet acts more like
a directory.  Pro: get sharing of files (only one-level).  Cons: there's no
one bundle to point to (everything is implicit in the bundle directory and
the ordering of the bundles).  Also, there could be a lot of files, which
makes the worksheet harder to visualize.

Probably 2) is better provided we provide some support to make this easy to
use.

**Comment by percyliang** [comment]
An extension of 2): we have a .codalab.json file that specifies the environment of the project:
- default docker image and other run arguments (memory, time, etc.)
- default dependencies

Then the workflow is:
- ...edit code...
- cl sync # uploads only things that change
- cl run 'python src/train.py' # note we don't have to specify the dependencies explicitly

**Comment by fabeschan** [comment]
Option 2 sounds better and more flexible -- if users can specify exactly how they want their bundles to be uploaded and organized like they can with dependencies then `cl sync` and `cl run` become very convenient

**Comment by maxwang7** [comment]
Design doc: https://docs.google.com/document/d/11OZZ7qOlhbSFTMi6snB1ExwRHpHGwwynsf9LB4QOMJo/edit#

Next steps:
- Run sempre and see how `cl sync` would work with it
- Work with Sida and see how `cl sync` would work with his code.
- Create a prototype

**Comment by percyliang** [comment]
Not supporting for now because this is too heavyweight.
