### ISSUE TITLE
Make run bundles more robust to worker failure

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#736]
* Increase timeout period for failing a run when a worker is unresponsive
    * Increase from 20 minutes to 7 hours?
    * Alternatively, never fail the run automatically, but provide some sort of feedback to the user that the worker has been unresponsive (maybe set "run_status" to "Worker unresponsive")
* Allow `cl kill` to fail a job with a non-responding worker
    * currently `cl kill` just queues up a "kill" message for a worker.
    * if a worker stops responding 
    * perhaps allow an additional

**Comment by fabeschan** [comment]
Closed with #805
