### ISSUE TITLE
Persist run results on worker indefinitely until successful reconnect

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#737]
* Motivation: Since jobs on a worker run in Docker containers independently of the worker process, we shouldn't lose the results of a job just because the worker process died temporarily, or because the worker couldn't connect to the server for a long time. We also want jobs to be able to continue running while the worker updates itself. 
 * Current situation: The worker currently just has a lightweight thread for each job, polling Docker to check if the container has finished running. When the job completes, this thread tries to upload the results to CodaLab for 6 hours, then gives up. When you signal a worker to tell it to terminate, it waits until all current runs are complete before exiting. This isn't really necessary though: an exited container will contain the results of the job on disk up until the container gets deleted.
 * Solution:
     * Maintain some state (that gets periodically flushed to disk) keeping track of which Runs are still running, so that when the worker restarts, it can re-spawn the Run threads that are tracking the jobs. Then increase the try time from 6 hours to infinity.
     * Alternative (maybe better?) design idea:
         * Spawn only a single thread to watch all the runs. when a run completes, it should be added into a queue of runs that need to be uploaded back to CodaLab.
         * Another thread pops runs off of this queue and one-by-one tries to upload the results of each run to CodaLab. For each run, try indefinitely until the first successful reconnect (i.e. the first time we hear something substantive back from the server, whether or not failed or succeeded -- we don't want to be stuck in an infinite loop because of something like the bundle got deleted).
     * Considerations:
         * Should probably factor out a single WorkerState class that manages and persists the state. Currently both DependencyManager and DockerImageManager maintain their own state as separate JSON files. But this can get unwieldy especially now that we want to add Run data to this as well. Instead maybe just have a single (thread-safe) WorkerState class with simple getters and setters that manages this state data and periodically serializes the state to disk as a single state.json file.

**Comment by fabeschan** [comment]
Done. See #805
