### ISSUE TITLE
TorqueBundleManager should clean up jobs that no longer correspond to existing/running bundles

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#739]
it seems like there were a bunch of jobs in the Torque queue under the codalab user that were never completing, even though those bundles were long marked as failed/deleted in CodaLab itself

I wrote a script to clean them up for now on NLP server

but TorqueBundleManager should probably have some logic to clean up jobs that no longer correspond to existing or running bundles

**Comment by percyliang** [comment]
Don't bother supporting Torque.
