### ISSUE TITLE
Server errors on invalid worksheet markdown syntax

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#754]
In a worksheet, add a line that's just "%". Saving the worksheet causes an internal server error. It's impossible to reload the worksheet at this point because the interpretation code breaks.

**Comment by maxwang7** [comment]
I'm pretty sure this actually has to do with the Unicode problems, but will need to do more testing

**Comment by percyliang** [comment]
Fixed by #791 .
