### ISSUE TITLE
Further automate deployment and config generation

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#755]
- [x] Bring us closer to one-click deploy on fresh machines
- [x] I think Docker images should contain CodaLab code as well - just mount config files and bundle store and should work (add Dockerfiles to codalab-cli repo and push a tagged image for each release of CodaLab).
- [x] Generate all config files with ansible templates
- [x] Use idempotent Ansible actions
- [ ] ~Autogenerate host lists from azure templates?~
- [x] Alembic stuff
- [x] ...
- [x] Make things gr8

**Comment by fabeschan** [comment]
Make deployment gr8 again

**Comment by kashizui** [comment]
done
