### ISSUE TITLE
Usage of tar executable not cross-platform

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#759]
The upload1 and upload4 tests are failing on release. Reasons:

- `--exclude-patterns` flag isn't working
- Waiting on a finished bundle doesn't return an error code 1 (and instead runs fine).

**Comment by kashizui** [comment]
why isn't this happening on master?

**Comment by kashizui** [comment]
tar has different specifications on Linux, BSD, GNU etc.

**Comment by OrthoDex** [comment]
I have not been able to replicate this issue. `bsdtar` and gnu tar both work on macos and ubuntu 18. Are there any repro steps that I can follow?

**Comment by kashizui** [comment]
Hello,
I'm sorry that I didn't provide more details in my last comment above -- I can't recall anymore the details of the tar implementation differences.
It's been 3 years now though, it's possible the latest versions are different. Perhaps this issue can be closed until it comes up again.

**Comment by OrthoDex** [comment]
Sounds good!
