### ISSUE TITLE
Logging causes `wadd` across instances to fail

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#761]
Problem: Bundles are failing uploading on worksheets.

Reason: From Stephen: Looks like it's failing because these bundles have a large number of child bundles, and default behavior is to get the bundle_infos for all of those children as well when fetching the bundle metadata, which results in a huge JSON blob. The server event logger attempts to log this JSON blob in the request and then fails with "MySQL has gone away",

Example bundles:

https://worksheets.codalab.org/bundles/0xeb089d479e84499c8435d9f909aa63f0/
https://worksheets.codalab.org/bundles/0xdb6c770c59a5404cb881f3e029c44da0/

**Comment by kashizui** [comment]
fixed in release: stopped logging json blobs.
