### ISSUE TITLE
codalab-cli no longer available on pypi

### ISSUE THREAD

**Issue by wooters** [codalab/codalab-worksheets#763]
It looks like `codalab-cli` is no longer available on pypi. This url: https://pypi.python.org/pypi/codalab-cli produces a 404.

**Comment by percyliang** [comment]
We moved the repo to `codalab` instead.  Sorry for the inconvenience.

**Comment by wooters** [comment]
Ah, ok. So for installing/updating the cli tools, we should now use `pip install codalab`?

**Comment by kashizui** [comment]
Yep!
