### ISSUE TITLE
FAQ Missing

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#766]
This is a pretty broad issue, but the basic problem is that people have nowhere to turn to when facing specific problems. This contrasts the wiki in that the wiki has mostly high-level descriptions and overview of things.

We do have a google groups thing but it's not very visible and hard to search. The format is not exactly conducive to quick resolution of common issues either, hence the need for an FAQ list.

**Comment by maxwang7** [comment]
GPU, environment failed

**Comment by kashizui** [comment]
@maxwang7 feel free to reassign if you're overloaded

**Comment by maxwang7** [comment]
https://github.com/codalab/codalab-worksheets/wiki/FAQ

**Comment by kashizui** [comment]
done
