### ISSUE TITLE
No automatic order-resolution when deleting a bunch of bundles

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#767]
Steps to reproduce:

```
repeat until satisfaction:
    upload a bunch of files
    run a bunch of things that depend on the bundles above
cl rm ^1-^N (remove all bundles mentioned above)
```

Removing bundles in bulk will fail even though intuitively if they don't depend on anything else other than within themselves it should not fail.

**Comment by kashizui** [comment]
@fabeschan task: find a failure case so that we can debug it

**Comment by fabeschan** [comment]
Cannot reproduce :)  Closing issue.
