### ISSUE TITLE
Problem installing codalab (codalabwoker)

### ISSUE THREAD

**Issue by wooters** [codalab/codalab-worksheets#784]
I ran into a problem installing codalab via `sudo pip install codalab -U`. It looks like it is failing when it tries to install `codalabworker`. So, I tried `sudo pip install codalabworker` and that failed (see attached log file).

I think the issue may be a problem with `setup.py` for `codalabworker` here: https://github.com/codalab/codalab-cli/blob/master/worker/setup.py#L24  I think the value used in the `package_data` dict should be a list not a string (according to https://docs.python.org/2/distutils/setupscript.html#installing-package-data).

[pip.log.zip](https://github.com/codalab/codalab-cli/files/1095834/pip.log.zip)

**Comment by wooters** [comment]
I think this may have just been an issue with my `pip` being out of data. I just did a `sudo pip install --upgrade pip` and after that everything worked fine... Sorry for the noise.

**Comment by fabeschan** [comment]
np, closing this now.
