### ISSUE TITLE
Unable to install codalabworker with old versions of pip

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#786]

**Comment by maxwang7** [comment]
@percyliang I know that there's an error when installing codalab (as well as codalabworker) when using an old version of setuptools. I did a rough manual binary search algorithm and found that somewhere between v. 17.0.0 and v. 25.0.0 is where some bug was fixed in setuptools that allows codalab to be installed. I tried using the debug log to fix the problem but didn't make any headway. I propose adding a check for the setuptools version in setup.py and alerting the user if setuptools is older than v25.0.0 with the advice to upgrade setuptools.

**Comment by percyliang** [comment]
That sounds fine.
