### ISSUE TITLE
Stop adding newlines between cl mimic bundles

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#788]
This is totally a nit, but I find it annoying that when you cl mimic, it adds a newline in the worksheet markdown between every bundle.  I usually try to put things in tables to control what columns show up on the web interface, but the newlines mess this up and I have to go in and delete them every time.

**Comment by fabeschan** [comment]
Letting @maxwang7 take a look at this -- sounds like a webserver issue?

**Comment by percyliang** [comment]
I think it's a backend issue because it happens when you use the CLI too.
