### ISSUE TITLE
Run bundle fail error

### ISSUE THREAD

**Issue by rajpurkar** [codalab/codalab-worksheets#792]
Run bundle fails with error:
"Unable to get bundle contents from bundle service: Not Found - Not found."

**Comment by percyliang** [comment]
Can you give more info (what's the bundle uuid and what commands were run
to cause this?)

**Comment by rajpurkar** [comment]
I had to remove the associated bundles, but it was the result of macro squad-utils/test-evaluate-v1.1. The dependency bundles looked fine.

**Comment by rajpurkar** [comment]
Managed to reproduce error. Here's the failed bundle uuid: 0xad4e0b39a8ba443ea60bfd06bf0f43b7

**Comment by maxwang7** [comment]
@rajpurkar I'm re-running the bundle and they're completing just fine. For example, this one: 0x9a0ebd0b41e645b4bbe0057b1479bc2b. Is this something that's dependably reproducible or intermittent?

**Comment by rajpurkar** [comment]
It doesn't happen deterministically, from what I've seen. But it pops up on
evaluation bundles sometimes...

**Comment by maxwang7** [comment]
OK, I'll see if I can reproduce it. Let me know if it happens again for you.

**Comment by maxwang7** [comment]
@rajpurkar I've been unable to reproduce this problem after a few dozen runs (https://worksheets.codalab.org/worksheets/0xead271e0b0f24dc5aa9a3870772ee3f4/). Have you noticed anything else that may help me reproduce the issue?

**Comment by rajpurkar** [comment]
No worries, Max! I'll let you know if I come across the problem again!

**Comment by maxwang7** [comment]
Sounds good, thank you @rajpurkar!

**Comment by maxwang7** [comment]
Closing until we are able to reproduce

**Comment by rajpurkar** [comment]
Another bundle with the same issue @maxwang7:
0x43962913640e4ce5abcaa5d6462d5ae4
