### ISSUE TITLE
"cl work <username>" returns "no worksheet found"

### ISSUE THREAD

**Issue by strin** [codalab/codalab-worksheets#81]
Running
"cl work http://localhost:2800::<username>"
gives
"UsageError: No worksheet found with name "<username>"

However, just running
"cl work http://localhost:2800::"
will switch to the user worksheet correctly.

**Comment by percyliang** [comment]
The two commands you described are the same.  Are you saying the first time
you run it gives the error, and the second time works?

**Comment by strin** [comment]
I typed cl work http://localhost:2800::<username>. But <username>  was interpreted as a tag, and not displayed. Sorry about the confusion.

**Comment by percyliang** [comment]
Are you running a local version of codalab-cli?  (If so, you need to setup
the web server.)
Can you give more details about your setup?

**Comment by strin** [comment]
Yes, I am. But this is also the case for codalab.org. For example,

strin@Strin-Mac:~$ cl work https://codalab.org/bundleservice::tianlins
UsageError: No worksheet found with name 'tianlins'
strin@Strin-Mac:~$ cl work https://codalab.org/bundleservice::
Switched to worksheet https://codalab.org/bundleservice::tianlins(0x0528f288fae9425ba512c510abf81382).

**Comment by percyliang** [comment]
This is strange, since here's what happens on my computer:

% cl work https://codalab.org/bundleservice::tianlins
Switched to worksheet
https://codalab.org/bundleservice::tianlins(0x0528f288fae9425ba512c510abf81382)
.

I assumed you're logged in as 'tianlins'.  Does this always/still happen?

**Comment by strin** [comment]
Yes. This happens only when I am logged in as 'tianlins'. 
Thanks for making this clear.

**Comment by percyliang** [comment]
But you should be able to do
cl work https://codalab.org/bundleservice::tianlins
that when you're logged in as tianlins.
Does this still not work?

 -Percy

**Comment by strin** [comment]
It works now. Issue fixed.
