### ISSUE TITLE
Docker images with an ENTRYPOINT not replaced by `cl run`

### ISSUE THREAD

**Issue by connorbrinton** [codalab/codalab-worksheets#824]
To replicate, do the five-minute quick start and try to run using a docker image such as `huanjason/scikit-learn` or `davidshen84/scikit-learn`. Not even stdout/stderr is created. Presumably this is because the request sent to the Docker daemon in [worker/codalabworker/docker_client.py](https://github.com/codalab/codalab-cli/blob/8e5f782ac0a2bff9076e42d1cb6096ee1f5b3105/worker/codalabworker/docker_client.py#L428) doesn't execute properly.

**Comment by fabeschan** [comment]
<img width="1221" alt="screenshot 2017-12-11 18 50 17" src="https://user-images.githubusercontent.com/4369332/33864959-25d09580-dea4-11e7-8ad7-b6e297d923c8.png">
I don't have time right now to put in a fix and test it thoroughly but here's a note for myself when I get around to doing it. Meanwhile please use a docker image without an entrypoint (or make one yourself).

**Comment by fabeschan** [comment]
Fixed in upcoming patch
