### ISSUE TITLE
idle GPU workers creating excessive numbers of virtual network interfaces

### ISSUE THREAD

**Issue by krivard** [codalab/codalab-worksheets#827]
Hey, I'm seeing a weird behavior on my GPU workers that's threatening to overrun my /var partition with log files.

In syslog I get loads of these:

    Dec 20 15:58:47 saskia NetworkManager[1754]:    SCPlugin-Ifupdown: devices removed (path: /sys/devices/virtual/net/vetha664f1a, iface: vetha664f1a)
    Dec 20 15:58:47 saskia NetworkManager[1754]:    SCPlugin-Ifupdown: devices removed (path: /sys/devices/virtual/net/veth25f0549, iface: veth25f0549)
    Dec 20 15:58:53 saskia kernel: [1919630.395122] aufs au_opts_verify:1612:dockerd[114207]: dirperm1 breaks the protection by the permission bits on the lower branch
    Dec 20 15:58:53 saskia kernel: [1919630.423643] aufs au_opts_verify:1612:dockerd[126622]: dirperm1 breaks the protection by the permission bits on the lower branch
    Dec 20 15:58:53 saskia kernel: [1919630.469859] aufs au_opts_verify:1612:dockerd[122283]: dirperm1 breaks the protection by the permission bits on the lower branch
    Dec 20 15:58:53 saskia NetworkManager[1754]:    SCPlugin-Ifupdown: devices added (path: /sys/devices/virtual/net/vethd032079, iface: vethd032079)
    Dec 20 15:58:53 saskia NetworkManager[1754]:    SCPlugin-Ifupdown: device added (path: /sys/devices/virtual/net/vethd032079, iface: vethd032079): no ifupdown configuration found.
    Dec 20 15:58:53 saskia NetworkManager[1754]: <warn> /sys/devices/virtual/net/vethd032079: couldn't determine device driver; ignoring...
    Dec 20 15:58:53 saskia NetworkManager[1754]:    SCPlugin-Ifupdown: devices added (path: /sys/devices/virtual/net/vethb196c3b, iface: vethb196c3b)
    Dec 20 15:58:53 saskia NetworkManager[1754]:    SCPlugin-Ifupdown: device added (path: /sys/devices/virtual/net/vethb196c3b, iface: vethb196c3b): no ifupdown configuration found.
    Dec 20 15:58:53 saskia kernel: [1919630.472872] device vethb196c3b entered promiscuous mode
    Dec 20 15:58:53 saskia kernel: [1919630.473319] IPv6: ADDRCONF(NETDEV_UP): vethb196c3b: link is not ready
    Dec 20 15:58:53 saskia kernel: [1919630.473325] docker0: port 1(vethb196c3b) entered forwarding state
    Dec 20 15:58:53 saskia kernel: [1919630.473335] docker0: port 1(vethb196c3b) entered forwarding state
    Dec 20 15:58:53 saskia kernel: [1919630.473827] docker0: port 1(vethb196c3b) entered disabled state
    Dec 20 15:58:53 saskia NetworkManager[1754]: <warn> /sys/devices/virtual/net/vethb196c3b: couldn't determine device driver; ignoring...
    Dec 20 15:58:53 saskia NetworkManager[1754]:    SCPlugin-Ifupdown: devices removed (path: /sys/devices/virtual/net/vethd032079, iface: vethd032079)
    Dec 20 15:58:53 saskia kernel: [1919630.889489] eth0: renamed from vethd032079
    Dec 20 15:58:53 saskia kernel: [1919630.917787] IPv6: ADDRCONF(NETDEV_CHANGE): vethb196c3b: link becomes ready
    Dec 20 15:58:53 saskia kernel: [1919630.918073] docker0: port 1(vethb196c3b) entered forwarding state
    Dec 20 15:58:53 saskia kernel: [1919630.918090] docker0: port 1(vethb196c3b) entered forwarding state
    Dec 20 15:58:53 saskia kernel: [1919631.299413] vethd032079: renamed from eth0
    Dec 20 15:58:53 saskia NetworkManager[1754]:    SCPlugin-Ifupdown: devices added (path: /sys/devices/virtual/net/vethd032079, iface: vethd032079)
    Dec 20 15:58:53 saskia NetworkManager[1754]:    SCPlugin-Ifupdown: device added (path: /sys/devices/virtual/net/vethd032079, iface: vethd032079): no ifupdown configuration found.
    Dec 20 15:58:53 saskia NetworkManager[1754]: <warn> /sys/devices/virtual/net/vethd032079: couldn't determine device driver; ignoring...
    Dec 20 15:58:53 saskia kernel: [1919631.358592] docker0: port 1(vethb196c3b) entered disabled state
    Dec 20 15:58:53 saskia kernel: [1919631.359649] device vethb196c3b left promiscuous mode
    Dec 20 15:58:53 saskia kernel: [1919631.359657] docker0: port 1(vethb196c3b) entered disabled state
    Dec 20 15:58:53 saskia NetworkManager[1754]:    SCPlugin-Ifupdown: devices removed (path: /sys/devices/virtual/net/vethb196c3b, iface: vethb196c3b)
    Dec 20 15:58:53 saskia NetworkManager[1754]:    SCPlugin-Ifupdown: devices removed (path: /sys/devices/virtual/net/vethd032079, iface: vethd032079)

Docker seems to be creating 10-20 network interfaces (veth*) every minute. I don't see these messages on my CPU-only workers, just with GPUs. Nobody is running any jobs at the moment. On looking up the above error messages, they all seem to be legit things I'd expect a docker container to be doing, it's just the volume that's excessive. This makes me think it's the cl-worker running nvidia-smi every few seconds when it checks in with the server.

At the moment I have a cron job in place to clear out the bajillions of network-interface-vethXXXXXXX.log files that accumulate in /var/log/upstart, but --  is this the designed behavior for GPU workers, or is my environment horked somehow?

**Comment by fabeschan** [comment]
Thanks for reporting this @krivard, we have pushed a fix.
