### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#829]
`2018-01-12 02:52:33,223 Received read message: {u'uuid': u'0x754c7cf74e5c416d9af1330692617d58', u'socket_id': 3103506, u'meta': {u'version': u'0.2.21'}, u'path': u'stderr', u'read_args': {u'truncation_text': u'\n... [truncated] ...\n\n', u'num_tail_lines': 50, u'type': u'summarize_file', u'max_line_length': 128, u'num_head_lines': 50}, u'type': u'read'}
Traceback (most recent call last):
  File "/opt/worker/codalabworker/run.py", line 393, in read
    read_args['truncation_text']))
  File "/opt/worker/codalabworker/file_util.py", line 210, in summarize_file
    return ''.join(lines)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 24: ordinal not in range(128)`

**Comment by bkgoksel** [comment]
Seems related to #256

**Comment by bkgoksel** [comment]
Seems related to #502
