### ISSUE TITLE
CircleCI Build on forks

### ISSUE THREAD

**Issue by jder** [codalab/codalab-worksheets#836]
I've been trying to reproduce the CI failures with my docker branch, but it looks like the current codalab master build of circle is dependent on an existing cache of the `venv` folder. Here's a CI run using the same commit as current master and failing: https://circleci.com/gh/semanticmachines/codalab-cli/22. If I skip the line causing trouble, I run into another issue with python-dev not being installed: https://circleci.com/gh/semanticmachines/codalab-cli/23. 

I can continue tracking this down (it's why I was trying to get Circle 2.0 working) but wanted to make sure someone else didn't already know what's going on here. Is there some CI configuration which I need to replicate in our Circle CI UI? Or is master's build just broken without a previous cache? (e.g. if you choose "rebuild without cache" does it work?)

**Comment by fabeschan** [comment]
@jder I haven't been able to locate the cached venv folder in CircleCI (but it does exist, and you are correct that without it, CI runs will fail), but we have recently migrated to Travis so you might want to do the same.
