### ISSUE TITLE
'k' key doesn't work to go up on certain worksheets

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#84]
https://worksheets.codalab.org/worksheets/0xb843335f02a9443995db2013fbe2e7f4/
Go to the 'My disk usage' line and hit 'k'.  Get:
Uncaught TypeError: Cannot read property 'length' of undefined (worksheet_interface.js:43)

**Comment by maxwang7** [comment]
For some reason, sometimes the sub_item doesn't have a bundle_info property at all.
