### ISSUE TITLE
Dashboard link

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#85]
Rename 'My Worksheet' to 'Dashboard' and point to the worksheet named 'dashboard'.  If it doesn't exist, create one and populate it with the source found in:
https://worksheets.codalab.org/worksheets/0xb843335f02a9443995db2013fbe2e7f4/

The main 'issue' with this is that we don't create home worksheets by default now...

**Comment by percyliang** [comment]
@ChengshuLi Note: if the dashboard doesn't exist, the first user to go to it will get the dashboard created under his/her account.  Not ideal, so when people deploy an instance, they should click on 'dashboard' as the root user or something.

**Comment by ChengshuLi** [comment]
@percyliang I understand the first part, basically when a new user log in, he/she will land in his/her dashboard created under his/her account, right? but what do you mean it is not ideal? What is not ideal?

**Comment by percyliang** [comment]
There is only one 'dashboard' worksheet, not one per user.

So the first user who tries to access 'dashboard' when it doesn't exist
will have to create it, and that singleton 'dashboard' worksheet will be
owned by that user.
