### ISSUE TITLE
Can't refer to bundles from other worksheets as dependencies for runs

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#867]
Currently cl run can depend on bundles from other worksheets using their uuids:
`cl run dep:0x01234 'command dep'` 

However run doesn't accept referring by name:
`cl run dep:<host-ws>/<bundle> 'command dep'` -> throws `bundle spec <host-ws> doesn't match any bundles`

To run it this way one needs to first add the bundle to the current worksheet:
`cl add bundle <host-ws>/<bundle> .` 
and then refer to it in a run:
` cl run dep:<bundle> 'command dep'`

We should either not allow the first case (you always have to add to the current worksheet before depending) or better yet, we should allow the second form of usage as well.

**Comment by percyliang** [comment]
The second usage is problematic because `dep:a/b` refers to the path `b`
inside bundle `a`.

**Comment by bkgoksel** [comment]
Decided to implement it such that
`dep:a//b/c` will refer to path `c` in bundle `b` from worksheet `a`

**Comment by bkgoksel** [comment]
Also noting here that depending on a bundle from a worksheet on a different instance might be tricky. I think we allow this on other commands, so maybe we want to allow this for `cl run` too, but I'm not sure if it's worth the trickiness.
Similar issue in #768

**Comment by percyliang** [comment]
Can you explain what the trickiness is?  It'd be nice to have one uniform
way of referencing bundles everywhere via the
`<worksheet>//<bundle>/<target path>[^<index>]` syntax.
