### ISSUE TITLE
Worker disk space getting full

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#880]
DependencyManager and/or ImageManager isn't cleaning up disk space as well as it should. `/mnt` is showing 100% used on `prod-worker0`

**Comment by bkgoksel** [comment]
Closing for now as new worked update is merged. I manually cleaned all old images on 8/3/2018.
If we see that we're still not cleaning up properly can reopen.
One thing to look at in the future might be to limit docker log size so old logs are discarded.
