### ISSUE TITLE
Worker Run() objects are not resumable

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#881]
Runs can be resumed if the worker dies while the container is running, but if the Run object is interrupted at any other point, the worker will be unable to recover it. This is the reason why a worker that goes offline while one of its bundles are "uploading results" is unrecoverable.

**Comment by bkgoksel** [comment]
Hopefully will be fixed with #896

**Comment by bkgoksel** [comment]
Solved in PR for #909
