### ISSUE TITLE
Unable to reserve worker resources for resumed runs

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#882]
When a worker starts up, it tries to do two things: checkin with the server, and resume previous runs.

There exists a conflict between the two actions:
If the checkin happens first, then the server bundle manager might assign new run bundles to the worker without any regard for the resources taken up by those previous runs, because the rows for them have not yet been inserted into `worker_run`.

If resume previous runs happens first, then the server throws an exception because resuming previous runs involves inserting rows into `worker_run`; but these rows reference a worker that hasn't checked in. This is a foreign reference violation.

**Comment by bkgoksel** [comment]
Hopefully will be fixed with #896

**Comment by bkgoksel** [comment]
Solved in the PR as of now
