### ISSUE TITLE
Flaky stdout/stderr for long running jobs

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#891]
Some jobs sometimes seem to not update stdout/stderr until the end (or will update them to a point, then stdout/stderr will seem to be frozen until the job ends and they will be populated)

Both cases happened to me and also happened during 224N Codalab submissions.
In one case I tried debugging by entering a shell inside the container running the bundle and read the `/proc/<pid>/fd/1` and `/proc/<pid>/fd/2` of the command running (direct file descriptors to the process' stdout/stderr) and even these seemed to be stuck (one had stopped printing midway).

In another case, the same job running locally would populate its stdout fine.

**Comment by bkgoksel** [comment]
Seems like flushing the console explicitly alleviates this. This might not really be related to us given that the stdout isn't written to even inside the docker container and maybe people should just flush their streams more.

**Comment by percyliang** [comment]
Ok, closing until this is a problem again.
