### ISSUE TITLE
--request-gpus flag not respected on custom worker

### ISSUE THREAD

**Issue by ezliu** [codalab/codalab-worksheets#895]
I've run cl-worker on a machine with GPUs, with the CUDA_VISIBLE_DEVICES variable set to 0. My jobs are all run with --request-gpus 1, but multiple jobs are being run on the same worker.

**Comment by fabeschan** [comment]
Please use the --gpuset flag on the worker instead of CUDA_VISIBLE_DEVICES

For reference take a look at https://github.com/codalab/codalab-cli/blob/master/worker/codalabworker/main.py#L41
