### ISSUE TITLE
support GitHub markdown

### ISSUE THREAD

**Issue by codalab** [codalab/codalab-worksheets#9]
<a href="https://github.com/percyliang"><img src="https://avatars.githubusercontent.com/u/435384?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [percyliang](https://github.com/percyliang)**
_Monday May 04, 2015 at 05:11 GMT_
_Originally opened as https://github.com/codalab/codalab-competitions/issues/1007_

---

Currently, only vanilla markdown is supported.  It would be nice to support the GitHub flavor:
https://help.github.com/articles/github-flavored-markdown/

**Comment by percyliang** [comment]
Not urgent
