### ISSUE TITLE
cl make from running or failed bundles

### ISSUE THREAD

**Issue by kelvinguu** [codalab/codalab-worksheets#91]
I am typically training models that take several days to converge.
Every epoch, model parameters are saved.
I often want to extract those parameters and analyze them, while the job continues to run.

Currently, if I try to call `cl make 0x34dsaf1/params`, Codalab will wait until the job finishes. However, since you never know when a neural net might converge, my jobs are configured to run indefinitely, until I manually decide to kill them. Unfortunately, manually killing a job gives it a "failed" status, and codalab refuses to make bundles from failed bundles.

So, the only way to "snapshot" the parameters is to `cl download 0x34dsaf1/params` and then `cl upload dataset params`. This ruins provenance and is very prone to mistakes.

Ideally, calling `cl make` would create a bundle which is a snapshot of those parameters at a particular point in time. The metadata could say when the snapshot was taken. A snapshot of the directory contents could also be taken. This is not perfect provenance, but it's much better than nothing.

**Comment by kelvinguu** [comment]
I wanted to add that `cl download` and `cl upload` are almost prohibitively slow when the parameters are around 100 Mb compressed. So, a workaround for this is much needed.

**Comment by percyliang** [comment]
Use the `--allow-failed-dependencies` flag
