### ISSUE TITLE
issue with multiple users running competition

### ISSUE THREAD

**Issue by rajpurkar** [codalab/codalab-worksheets#921]
When I'm running a competition-d script that another host of a competition has also run, it redoes the mimics! Ideally, I'd like it to recognize that the run was made by a member of a group, rather than as an individual!

**Comment by percyliang** [comment]
In general, mimic is probably too powerful and probably should grab the computation graph restricted to one worksheet, so it doesn't go crazy.

**Comment by percyliang** [comment]
The competition-d script should also be based on a group.

**Comment by bkgoksel** [comment]
We deployed a feature that enables fetching bundles by group permissions. 
Next step would be updating the competitiond script to use this feature.

**Comment by percyliang** [comment]
Also related to #2220, which should help with multiple users hosting the same competition
