### ISSUE TITLE
Dependency downloads really slow

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#929]
Today a 100 mb dependency took > 6 minutes to download on a prod worker machine.
Uploads are ok as the same file took ~10 seconds to upload as a bundle result.

**Comment by percyliang** [comment]
Can't reproduce.

**Comment by hhexiy** [comment]
I'm also experiencing this issue, e.g. https://worksheets.codalab.org/bundles/0x4d3e465f9bc248e98bdfb32d42805c36/
