### ISSUE TITLE
Users can see groups on a worksheet they do not belong to. 

### ISSUE THREAD

**Issue by Raisins** [codalab/codalab-worksheets#93]
When viewing public or other worksheets I am able to see groups I do not belong to. 
Related to issue https://github.com/codalab/codalab/issues/959
![bba7559a-ef3b-11e4-9958-86f313b99b71](https://cloud.githubusercontent.com/assets/123099/7636538/b15cd29a-fa1c-11e4-8ffa-b055a751e3ff.png)

**Comment by kashizui** [comment]
@percyliang Just to clarify, should this be fixed at the client level in `local_bundle_client.get_worksheet_info` or at the model level in `bundle_model.batch_get_group_permissions`?

**Comment by percyliang** [comment]
This should be fixed inside bundle_model since you have the user_id passed
in.

**Comment by kashizui** [comment]
Is there a way to manipulate users (create/edit/destroy) on a local codalab instance, and to "log in" as a user other than `codalab`? How would you recommend testing this?

**Comment by percyliang** [comment]
I would create a bunch of users (sign up).  Then you can set CODALAB_HOME
to something other than ~/.codalab and this gives you different
environments for connecting to the cl server.
