### ISSUE TITLE
Worksheet item divs have class type-table instead of type-worksheet

### ISSUE THREAD

**Issue by ppasupat** [codalab/codalab-worksheets#94]
I'm not sure if this is intentional, but the divs for worksheet items have class `type-table` (used for displaying bundles) instead of `type-worksheet` (which displays a worksheet icon). Should it be changed to `type-worksheet`?

**Comment by percyliang** [comment]
Not sure - what is the effect on actual layout?

**Comment by ppasupat** [comment]
Currently it looks like this:

![screenshot - 02032016 - 06 33 06 pm](https://cloud.githubusercontent.com/assets/5135317/12804093/ae1b305a-caa4-11e5-82e1-163df8c26860.png)

I remember that it used to look something like this:

![screenshot - 02032016 - 06 35 50 pm](https://cloud.githubusercontent.com/assets/5135317/12804127/051c1662-caa5-11e5-8997-2d2fb01aed48.png)

**Comment by percyliang** [comment]
Ah, we got rid fo the logo so that long lists of worksheets (with the %
wsearch directive) look reasonable.

**Comment by ppasupat** [comment]
I see. I will close the issue then.
