### ISSUE TITLE
Bundle time use calculation inconsistent

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#940]
Currently the runtime calculation of a bundle is inconsistent. We should clearly define what it should include (including preparing and uploading or only docker container runtime) and be consistent in our display during and after the run and inclusion in user quota.

**Comment by percyliang** [comment]
The 'time' field should really only be the wall clock runtime of the run.  We should add another field which is `extended_time` or something that includes the total time through all stages.

**Comment by nikhilxb** [comment]
@percyliang @bkgoksel: Right now, `codalab-cli/codalab/bundles/run_bundle.py` defines `time`, `time_user`, and `time_system` as metadata for a run. How about the following wording:

-  `'time', float, 'Amount of time (seconds) used by this run in total (user + system).'`
- `'time_user', float, 'Amount of user time (seconds) used by this run, i.e. actually running user command.'`
- `'time_system', float, 'Amount of system time (seconds) used by this run, e.g. startup/teardown time, Docker preparation/upload.'`

**Comment by percyliang** [comment]
Are we using time_user and time_system currently?

This might be confusing since user and system time are notions within the
running of a normal command.  CodaLab overhead is on top of that.

Maybe time (process_time) and total_time or something?

**Comment by nikhilxb** [comment]
Yes `time_user` and `time_system` are currently extracted from docker container's cpu stats: https://github.com/codalab/codalab-cli/blob/e22e2cedaa25a8145c655bdca0720c12468db8e3/worker/codalabworker/docker_client.py#L518-L530

**Comment by nikhilxb** [comment]
How about `process_time`, `process_user_time`, `process_system_time` (all components of the user's actual command run time); and `total_time` (which includes startup/teardown, Docker container preparation, etc)?

Other variants: `command_[...]_time` (which I like because it conserves terminology), `run_[...]_time` (which may be confusing since "run" clashes with `cl run` so I'd intuitively expect to include all time including setup).

**Comment by bkgoksel** [comment]
1. Do we even show the user time and system time in the UI or in the bundle metadata currently? 

2. I don't think the total_time is that important or meaningful (it really depends on things like what dependencies are cached etc) so I'd say we don't even need to compute/store/display 
it. 

3. So I think what we need to do is to make sure we compute the process time correctly both during and at the end of the run. The trick here is to update the time metadata during the run correctly, which isn't the case right now.

**Comment by bkgoksel** [comment]
Also re @percyliang's point. We only really launch the user's command in a docker image without much else so as long as docker stats are accurate these (user vs system time) might be somewhat meaningful.

**Comment by percyliang** [comment]
I think the information contained in process_time, process_user_time,
process_system_time, and total_time are good to have.  Names sound good to
me, although this breaks backward compatibility?  (I think we do want
total_time, because it is the time that people will reason about when they
think about how long it takes to run things on CodaLab).

**Comment by bkgoksel** [comment]
If we change bundle metadata we need to write a db migration don't we? Or is our architecture ok with some bundles missing some metadata in the db?

**Comment by percyliang** [comment]
It should be robust (but we should check).  Migrations are kind of annoying
(in this case, there's no schema changes).  we could do time, time_system,
time_user, time_total...?

**Comment by bkgoksel** [comment]
We still need to distinguish the total runtime of the docker container (for quota purposes) and the total runtime of the bundle (for users' reference) don't we?

**Comment by percyliang** [comment]
I was thinking 'time' would be the former and 'total_time' is the latter.

**Comment by bkgoksel** [comment]
Ah got it, that sounds good to me. Maybe we could call it time_codalab instead of time_total to emphasize it includes codalab overhead? Not sure if that's any better though.

**Comment by percyliang** [comment]
I like the specificity.  One might worry if it connotes only the overhead
from codalab, but I suspect it's fine.
