### ISSUE TITLE
Disk quota related error messages display disk use in bytes

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#941]
We should format these to MB or GB.

**Comment by percyliang** [comment]
To reproduce try creating a run that requests more disk than the user's quota.

**Comment by nikhilxb** [comment]
Reproduced with: `cl run --request-disk 100g "echo hello" -n echo-hello`.
- **state:** failed
- **failure_message:** Requested more disk (107374182400) than user disk quota left (10737378811.0)

**Comment by nikhilxb** [comment]
Found additional similar issues: `cl run --request-disk 100g --request-memory 100g --request-time 100d "echo hello" -n echo-hello`
- **state:** failed
- **failure_message:** Requested more disk (107374182400) than user disk quota left (10737378811.0). Requested more time (8640000.0) than user time quota left (604656.878). Maximum memory limit (107374182400) exceeded (59055800320)

**Comment by nikhilxb** [comment]
After update, output is:
- **state:** failed
- **failure_message:** Requested more disk (100g) than user disk quota left (10.0g). Requested more time (100d0h) than user time quota left (6d23h). Maximum memory limit (100g) exceeded (55g)

**Comment by bkgoksel** [comment]
Did you already code the changes? If so can you make a PR and link to this issue?

**Comment by nikhilxb** [comment]
@bkgoksel: I did but can't upload/PR my branch. Can you help me fix the permissions?

**Comment by bkgoksel** [comment]
What's the issue? Did you clone the original repo, create a branch locally and now trying to push that branch back upstream?

**Comment by nikhilxb** [comment]
Yes. I cloned the repo, created a branch locally, and now am trying to push to Github:
<img width="1085" alt="screen shot 2018-09-29 at 3 48 25 pm" src="https://user-images.githubusercontent.com/16842594/46251123-3353b200-c3ff-11e8-8b1f-33359b363b5f.png">

**Comment by bkgoksel** [comment]
Hmm are you a member of the codalab org on github? I think only @percyliang can give you write access to the repo by adding you as a member (although I thought he already added you). Can you try from a command line git by any chance?

**Comment by nikhilxb** [comment]
Yeah, I thought so too:
```
git push --set-upstream origin fix/941-pretty-failure-msg
remote: Permission to codalab/codalab-cli.git denied to nikhilxb.
fatal: unable to access 'https://github.com/codalab/codalab-cli.git/': The requested URL returned error: 403
```

**Comment by bkgoksel** [comment]
Was this merged to master? If not can you create a PR to do so?
