### ISSUE TITLE
Clicking on a worksheet item redirects to "javascript:0"

### ISSUE THREAD

**Issue by ppasupat** [codalab/codalab-worksheets#95]
To reproduce:
- Add a worksheet item to the current worksheet. For example: `cl add worksheet yay .`
- Click on the worksheet item. A new tab with the new worksheet opens, but the address of the original tab is changed to `javascript:0` (and the page displays just the number 0).

**Comment by ChengshuLi** [comment]
Hi @ppasupat,

It seems like I can't reproduce the bug right now. I did what you said above, and the original tab stays the same without changing to javascript:0. Would you mind trying again to see if the bug is still there?

**Comment by ppasupat** [comment]
Hi. I seems that the bug only happens in Firefox. I could not reproduce 
it in Chrome.

In static/js/worksheet/worksheet_item_interface.js, changing 
"javascript:0" to "javascript:void(0)" solves the problem for me.

**Comment by ChengshuLi** [comment]
Hi @ppasupat,

Got it. Thanks a lot! I will fix it now.
