### ISSUE TITLE
Extremely large docker images are allowed

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#955]
Currently we have no limits on individual Docker image sizes, this has 2 problems:
1. People can put their data on their Docker image to go over disk quotas
2. If a single image moves disk use above the worker image size limit, the cleanup process get stuck in an infinite loop of trying to remove the image as soon as it is downloaded, and restarting downloads.

We should  enforce individual size limits on Docker images and pass on informative error messages to people who request docker images that are too large.

**Comment by percyliang** [comment]
Dup of #1894
