### ISSUE TITLE
work manager dies once in a while with unexpected metadata key: actions

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#96]
This is the error message:
=== kill_bundle(0x1a318dd87a2d4c36a881a2b099a961e9)
ERROR: bundle 0x1a318dd87a2d4c36a881a2b099a961e9 does not have job handle; metadata is <codalab.objects.metadata.Metadata o
bject at 0x1701590>
UsageError: Unexpected metadata key: actions

**Comment by percyliang** [comment]
This happens very infrequently and is thus hard to diagnose.

**Comment by kashizui** [comment]
WorkManager is gone!
