### ISSUE TITLE
Git clone bundle error

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#981]
User report:

We’re noticing something else regarding these bundles, specifically when we try to run a git clone with network, the bundle finishes with no files available whatsoever (not even stdout and stderr), see: https://worksheets.codalab.org/bundles/0x94904b611cf44a25857087f8baff06bc/

**Comment by bkgoksel** [comment]
This one is really odd. For now people can use `cl up --git https://github.com/<user>/<repo>` and use that bundle as a dependency downstream (which is what I normally what I do and hence never ran into this issue). 

However this is definitely a bug that we should fix.

**Comment by bkgoksel** [comment]
This was a wider bug with docker image config files which is fixed now.
