### ISSUE TITLE
Failed dependencies in one machine are never retried

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#986]
Reported by @thashim

If the initial download attempts fail for the custom worker, worker reports following error: 

Failed to download dependency cond-editor-codalab:" 

even if dependency exists in the worksheet, and the hash is specified correctly

**Comment by percyliang** [comment]
@bkgoksel Is this still an issue?

**Comment by epicfaace** [comment]
I think we should close this; I don't know if we want to institute a retry for downloading dependencies in a bundle. What do you think @percyliang ?
