### ISSUE TITLE
cli upload bug 

### ISSUE THREAD

**Issue by Qbuer** [codalab/codalab-worksheets#988]
Hi, I just tried the cli and found a upload bug.

Here are files in directory:

`./result/lstm/checkpoing`
`./result/lstm/.data-000000-of-00001`
`./result/lstm/.index`
`./result/lstm/.meta`
`./result/lstm/model.weights.data-00000-of-00001`
`./result/lstm/model.weights.index`
`./result/lstm/model.weights.meta`
`./result/lstm/.meta.tmpbb651d3d85e14c849fff5dcc9e995551`

But when I uploaded this directory using  
`cl upload result`
I got this in my worksheets:

`.data-00000-of-00001`
`.index`
`.meta`
`.meta.tmpbb651d3d85e14c849fff5dcc9e995551`
`checkpoint`
`model.weights.data-00000-of-00001`
`model.weights.index`
`model.weights.meta`

It's seems that the cli handled the filename suffix incorrectly.

**Comment by bkgoksel** [comment]
Hi @Qbuer,
Sorry we missed this issue. I can't see a problem here. What was the results you expected to see?

**Comment by Qbuer** [comment]
> Hi @Qbuer,
> Sorry we missed this issue. I can't see a problem here. What was the results you expected to see?

Sorry, the case posted here seems alright but I've forgotten the details... I'll close this issue.
