### ISSUE TITLE
Non-bundle worksheet items are counted when resolving index-based bundle references

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#997]
As reported by Robin, if someone has a worksheet that looks like this:
```
[bundle2]{UUID2}
# Here's a section title
[bundle1]{UUID1}
```
And they run `cl rm ^2` to delete `bundle2`, they'll get a `Bundle None not found` error.
However if they run `cl rm ^3`, `bundle2` will be deleted.

`cl rm ^1` would delete `bundle1` as expected.

This is because when the index `^` is being resolved, it seems to count all worksheet items and not just bundles. So adding a new line before the section title in the example above would make `bundle2` aligned with `^4` instead. 

This seems like it could be related to the worksheet interpretation revamp? @w0nche0l

**Comment by bkgoksel** [comment]
@w0nche0l You looked into this. It would be good if you could summarize your findings so whoever gets to look at this issue next can ramp up faster.

**Comment by robinjia** [comment]
Hi,

I am still encountering this problem as of today. I needed to remove 20 bundles from the middle of a worksheet.

```
cl rm ^11-30
NotFoundError: Bundle None not found
```

I am on codalab version 0.3.0 (just pip-upgraded).
